### ISSUE TITLE
Render director.yml.erb.erb to director.yml.erb failed when deploying bosh release by bosh-init

### ISSUE THREAD

**Issue by jianqiu** [cloudfoundry/bosh#1000]
Command 'deploy' failed:
  Deploying:
    Building state for instance 'bosh/0':
      Rendering job templates for instance 'bosh/0':
        Rendering templates for job 'director/50f0a11bd41eb9c6e45a20428dcf421b78a02c2b':
          Rendering template src: director.yml.erb.erb, dst: config/director.yml.erb:
            Rendering template src: /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/bosh-init-release650101005/extracted_jobs/director/templates/director.yml.erb.erb, dst: /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/rendered-jobs255123368/config/director.yml.erb:
              Running ruby to render templates:
                Running command: 'ruby /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/erb-renderer900836996/erb-render.rb /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/erb-renderer900836996/erb-context.json /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/bosh-init-release650101005/extracted_jobs/director/templates/director.yml.erb.erb /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/rendered-jobs255123368/config/director.yml.erb', stdout: '', stderr: '/root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/erb-renderer900836996/erb-render.rb:180:in `rescue in render': Error filling in template '/root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/bosh-init-release650101005/extracted_jobs/director/templates/director.yml.erb.erb' for director/0 (line 87: #<NoMethodError: undefined method `[]=' for nil:NilClass>) (RuntimeError)
	from /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/erb-renderer900836996/erb-render.rb:166:in `render'
	from /root/.bosh_init/installations/9e0532bf-590a-4792-67a0-0a76485f7742/tmp/erb-renderer900836996/erb-render.rb:191:in `<main>'
':
                  exit status 1

I checked the line 87 of director.yml.erb.erb
```
if_p('dns.domain_name') do |domain_name|
      params['dns']['domain_name'] = domain_name
end
```
When commented line 87, bosh-init could deploy bosh release successfully. The ruby version used by bosh-init is Ruby 2.2.3

```
if_p('dns.domain_name') do |domain_name|
      // params['dns']['domain_name'] = domain_name
end
```

**Comment by bonzofenix** [comment]
We encounter the same thing. I think its because `params['dns']` has not been initialized with an `{}`

**Comment by cppforlife** [comment]
@bonzofenix It doesnt really make sense to set dns.domain if rest of dns properties are not set. Btw do you have a manifest snippet that fails?

**Comment by bonzofenix** [comment]
@cppforlife here is the manifest that failed. It is currently working with the same template on version 217.
https://gist.github.com/bonzofenix/9d0ad5273c1112e98a28

**Comment by voelzmo** [comment]
@cppforlife I agree that it doesn't make any sense. However, `dns.domain_name` has a default and is therefore always set: http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=218#p=dns.domain_name

Just encountered the same thing when deploying my director with v218

**Comment by hashmap** [comment]
@voelzmo do you deploy using bosh-init? I wonder why I  don't have this issue with this code on dev build.

**Comment by voelzmo** [comment]
@hashmap using bosh-init on aws with the config from bosh.io, bosh v218, aws-cpi v35

Note: 
* I don't use DNS, to I don't specify anything in the manifest
* I don't co-locate the powerdns job

**Comment by cppforlife** [comment]
Resolved in bosh v219. Sorry for the inconvenience.
