### ISSUE TITLE
bosh-release.tgz doesn't contain a LICENSE

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1008]
The LICENSE file in the project root is not automatically put into the release.tgz files. So if you download the .tgz from bosh.io you have no idea what license this release actually has.

To include a license we would need to add another license file in the `release` directory. Should we just copy it or create a symlink to the directory so that it gets picked up during release creation automatically?

**Comment by voelzmo** [comment]
*bump* any updates on this?

**Comment by dpb587-pivotal** [comment]
Will be fixed as part of https://www.pivotaltracker.com/story/show/132719183

**Comment by voelzmo** [comment]
looking forward to this, it has been a while :)

**Comment by dpb587-pivotal** [comment]
Closing - it happened :)
