### ISSUE TITLE
Failed to upload stemcell when deploy bosh by bosh-init

### ISSUE THREAD

**Issue by yyl8815** [cloudfoundry/bosh#1014]
I am trying to deploy bosh when I got below error.

Please somebody help me out.

[bosh-init version]
root@boshcli:~/my-bosh# bosh-init -v
version 0.0.80-a62aad7-2015-10-28T01:52:30Z

[error log] 
root@boshcli:~/my-bosh# bosh-init deploy bosh-iad.yml
Deployment manifest: '/root/my-bosh/bosh-iad.yml'
Deployment state: '/root/my-bosh/bosh-iad-state.json'

Started validating
  Validating release 'bosh'... Finished (00:00:02)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:04)
Finished validating (00:00:07)

Started installing CPI
  Compiling package 'vsphere_cpi_mkisofs/b3ebe039dae6a312784ece4da34d66053d1dfbba'... Finished (00:00:00)
  Compiling package 'vsphere_cpi_ruby/3ce375f2863799664bff235e2c778a3131f1e981'... Finished (00:00:00)
  Compiling package 'vsphere_cpi/99ebc132ef07ddf733989aff19f7093f847d4187'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3126'... Failed (00:00:03)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3126):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"getaddrinfo: Name or service not known (https://https:443)","ok_to_retry":false}

[vCenter config]
   vcenter: &vcenter # <--- Replace values below
      address: https://my-domain:4430
      user: xxx
      password: xxx
      datacenters:
      - name: cf
        vm_folder: vm_folder
        template_folder: template_folder
        datastore_pattern: 10.32.102.201
        persistent_datastore_pattern: 10.32.102.201
        disk_path: director_disk
        clusters: [cf]

**Comment by cppforlife** [comment]
Error returned:

```
getaddrinfo: Name or service not known
```

indicates that vcenter address could not be resolved to an IP.

**Comment by yyl8815** [comment]
Hi @cppforlife 
You are correct. It's strange because I have set the dns in the network configuration. The domain should be recognized.

Whatever, after I replace the domain with IP, it worked.

Thank you. @cppforlife
