### ISSUE TITLE
Latest nokogiri fails to build on El Capitan

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh#1019]
When I did a `gem install bosh_cli` I kept on getting build errors for nokogiri/libxml2:

```
conftest.c:15:27: error: too few arguments to function call, single argument 'cur' was not specified
int t(void) { xmlParseDoc(); return 0; }
              ~~~~~~~~~~~ ^
/Users/jasonkeene/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/ports/x86_64-apple-darwin14.1.0/libxml2/2.9.2/include/libxml2/libxml/parser.h:841:11: note: 'xmlParseDoc' declared here
XMLPUBFUN xmlDocPtr XMLCALL
          ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2:
 3: #include <libxml/parser.h>
 4:
 5: /*top*/
 6: extern int t(void);
 7: int main(int argc, char **argv)
 8: {
 9:   if (argc > 1000000) {
10:     printf("%p", &t);
11:   }
12:
13:   return 0;
14: }
15: int t(void) { xmlParseDoc(); return 0; }
/* end */
```

I tried various builds of ruby (apple's build, macports and various rvm versions) and changing my compile flags to try and get it to grab a macports built libxml2 but I guess nokogiri carry their own libxml2? Anyways I was able to get bosh_cli installed by installing an older version of nokogiri:

``` bash
gem install nokogiri -v "< 1.5"
```

I know this might sound like an obvious solution for the ruby initiated but for those who are not, packaging issues like this can be quite the hurdle to overcome. This took me at least an hour of trying different things to figure out.

**Comment by cppforlife** [comment]
Unfortunetly nokogiri version in BOSH is tied with all the other gems and some expect it to be >1.5. I'm surprised that this was an issue since there are several people in the office that use El Capitan with newer nokogiri.

**Comment by patrice4github** [comment]
Hi,

I have the exact same issue, with the latest nokogiri-1.6.6.4 while trying:

`gem install rails`

`int t(void) { xmlParseDoc(); return 0; }
              ~~~~~~~~~~~ ^
/Users/patricegagnon/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.6.4/ports/x86_64-apple-darwin13.4.0/libxml2/2.9.2/include/libxml2/libxml/parser.h:841:11: note: 'xmlParseDoc' declared here
XMLPUBFUN xmlDocPtr XMLCALL
          ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <libxml/parser.h>
 4: 
 5: /*top*/`

Perhaps using RVM changes something?

Sorry I could not figure out how to print the code correctly.

**Comment by allomov** [comment]
I was able to fix this problem by installing nokogiri 1.6.6.2:
```
gem install nokogiri -v 1.6.6.2
gem install bosh_cli --no-ri --no-rdoc
```

**Comment by dprotaso** [comment]
@jasonkeene I've seen this issue if you have `xz` package installed from brew

**Comment by jasonkeene** [comment]
I'm closing this issue. The [new bosh cli](https://github.com/cloudfoundry/bosh-cli) is implemented in Go with all of its deps vendored and can be compiled as a static binary.

**Comment by allomov** [comment]
Yey!
