### ISSUE TITLE
problem in installing bosh cli

### ISSUE THREAD

**Issue by chaitu554** [cloudfoundry/bosh#1024]
Ruby 2.0.0 has been installed but it is showing error in installing bosh cli as it requires only 1.9.3

**Comment by allomov** [comment]
It does seem to be a strange error. I haven't heard about such error before. At the moment I run ruby 2.1.5 on my jumpbox with latest bosh_cli:
```
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

$ gem list bosh_cli
*** LOCAL GEMS ***
bosh_cli (1.3130.0, 1.3126.0, 1.3100.0)
```

Could you tell more about the error? How do you install bosh cli? What is the error message? Is there any stack trace?

**Comment by chaitu554** [comment]
Actually I have installed Ruby 1.8.7 version and tried to install bosh_cli
it is showing error as it require 1.9.3 version,if I ask for update it is
not updating.

**Comment by chaitu554** [comment]
I need clear steps to install bosh_cli . Will you help me through it? As
I'm unable to install ruby 1.9.3 version.

**Comment by chaitu554** [comment]
I need clear steps to install ruby (1.9.3 ) version and bosh_cli will you
help through it?

**Comment by allomov** [comment]
Sorry for late response. As far as I understand you need following things:

* install Ruby with the version higher than 1.9.3
* install BOSH CLI gem

The first task is easy to do with [RVM](https://rvm.io/) (ruby version management tool). I believe you'll find useful [this docs](https://rvm.io/rvm/install). You haven't mentioned a system on your host, still RVM is possible to use with [Windows](http://blog.developwithpassion.com/2012/03/30/installing-rvm-with-cygwin-on-windows/). Despite of this fact my advice is to use Linux.

After you install RVM you'll need to run following commands:
```bash
rvm install 2.1.5                       #  choose the version you need here
rvm use 2.1.5@bosh --create             #   create and use a separate ruby environment for your work
gem install bosh_cli --no-ri --no-rdoc  #   install BOSH CLI 
```

Wish you luck with this.

**Comment by chaitu554** [comment]
thank you so much i will work out with this and let u know...

**Comment by zhang-hua** [comment]
You can try to install RVM at first, then use RVM to install ruby 1.9.3 for you easily.
Remember to create a specific gem set  before installing bosh_cli which may make it faster to load all the gems.
 
-Edward
----- 原始邮件 -----发件人： chaitu554 <notifications@github.com>收件人： cloudfoundry/bosh <bosh@noreply.github.com>抄送：主题： Re: [bosh] problem in installing bosh cli (#1024)日期： 2015年11月17日 (周二) 下午2:31 I need clear steps to install ruby (1.9.3 ) version and bosh_cli will youhelp through it?

**Comment by chaitu554** [comment]
we are facing problem in deploying micro-bosh as we have followed this link
below

https://bosh.io/docs/deploy-microbosh-to-openstack.html

kindly help me through it.

**Comment by dpb587-pivotal** [comment]
Closing - microbosh is no longer supported in favor of bosh-init/[bosh](https://github.com/cloudfoundry/bosh-cli). Please give those a try, or open a new issue with updated information.
