### ISSUE TITLE
Bosh not working after update

### ISSUE THREAD

**Issue by ChandraNarayanasamy** [cloudfoundry/bosh#1034]
We were using bosh earlier to install cloudfoundry. It was working as expected and we installed cloudfoundry locally. 
Today, we updated the bosh after that bosh stopped working. Below is the error message we get when we type bosh command.

Failed to load plugin /usr/local/share/gems/gems/bosh-workspace-0.9.4/lib/bosh/cli/commands/deployment_patch.rb: cannot load such file -- bosh/workspace

Can somebody help to resolve this error.

Thank you in advance.

**Comment by bosh-ci-push-pull** [comment]
that doesnt look like a bosh error. it seems that you are using some kind of a plugin?

@drnic ideas?

**Comment by ChandraNarayanasamy** [comment]
We are not using any plug-ins. just did an update and executed command bosh. 

[root@hello commands]# bosh
Failed to load plugin /usr/local/share/gems/gems/bosh-workspace-0.9.4/lib/bosh/cli/commands/deployment_patch.rb: cannot load such file -- bosh/workspace

**Comment by cppforlife** [comment]
looking at the stacktrace there is a mention of bosh-workspace. thats not something that vanilla bosh cli tool provides.

**Comment by drnic** [comment]
bosh-workspace is a separate rubygem that BOSH CLI loads up dynamically and
overrides `bosh deploy` and `bosh deployment` commands.

Try installing the gem:

gem install bosh-workspace

Or better still, use a Gemfile to install everything.

cf-boshworkspace repo has one; run:

bundle install



On Wed, Nov 18, 2015 at 11:32 AM, Dmitriy Kalinin <notifications@github.com>
wrote:

> looking at the stacktrace there is a mention of bosh-workspace. thats not
> something that vanilla bosh cli tool provides.
>
> Sent from my iPhone
>
> > On Nov 18, 2015, at 11:20 AM, ChandraNarayanasamy <
> notifications@github.com> wrote:
> >
> > We are not using any plug-ins. just did an update and executed command
> bosh.
> >
> > [root@hello commands]# bosh
> > Failed to load plugin
> /usr/local/share/gems/gems/bosh-workspace-0.9.4/lib/bosh/cli/commands/deployment_patch.rb:
> cannot load such file -- bosh/workspace
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh/issues/1034#issuecomment-157834343>.
>



-- 
Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic

**Comment by jrsaravanan** [comment]
We tried bundle install from cf-boshworkspace repo

Failed to load plugin /usr/local/share/gems/gems/bosh_cli_plugin_micro-1.3130.0/lib/bosh/cli/commands/micro.rb: cannot load such file -- bosh/deployer

**Comment by bosh-ci-push-pull** [comment]
not sure what is installed in your envirobment but if you just install bosh cli without other cli plugins it should work. it works on my env.

**Comment by jrsaravanan** [comment]
removed all the bosh components and all bosh dependencies  and installed BOSH 1.3143.0.
It is working fine now .
Thanks for your support !!

**Comment by cppforlife** [comment]
Closing.
