### ISSUE TITLE
Running `bosh recreate` when the version is `create` for a release causes error

### ISSUE THREAD

**Issue by amitkgupta** [cloudfoundry/bosh#1042]
If I have a release in my deployment manifest where the `version` is `create` (and I've included a `url` for the release which is a path to a local release directory), then when I do a `bosh recreate` I get an error:

```
$ bosh -d Documents/workspace/kubernetes-release/example_deployments/bosh-lite/kubernetes.yml recreate master 0
Acting as user 'admin' on deployment 'kubernetes' on 'Bosh Lite Director'
You are about to recreate master/0
Recreate master/0? (type 'yes' to continue): yes

Performing `recreate master/0'...

Director task 198
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Failed: Release version `kubernetes/create' doesn't exist (00:00:00)

Error 30006: Release version `kubernetes/create' doesn't exist

Task 198 error

For a more detailed error report, run: bosh task 198 --debug
```

I think the ideal behaviour would be that this command (and many other commands, e.g. `ssh`, `download logs`, etc.) should not require a deployment manifest argument, but just some way to say "recreate the `master 0` job from the `kubernetes` deployment".  These sorts of commands currently often require the awkward flow of:

```
bosh download manifest DEPLOYMENT_NAME /tmp/himom.yml
bosh -d /tmp/himom.yml ssh # or recreate, etc.
```

**Comment by cppforlife** [comment]
This is a planned future enhancement.

**Comment by amitkgupta** [comment]
Ok, thanks.

**Comment by cppforlife** [comment]
Let's keep this open until this is fixed.

**Comment by mfine30** [comment]
This should be addressed in the new golang cli. Closing. If it comes up again, please open a new issue.
