### ISSUE TITLE
Improve error handling for "bosh errands"

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/bosh#1048]
In case of a deployment did not run successfully the deployment manifest is not uploaded correctly. While all other bosh command work as expected the command "bosh errand" prints out "HTTP: 500". 

In our use case a CF deployment fails sometimes (because of statsd which expects to connect to riemann which is temporarily not available). A Jenkins job which runs smoke tests as errand in parallel results in a mysterious HTTP 500.

**Comment by cppforlife** [comment]
We are planning to save the manifest regardless of the successful deploy or not in future; however, I'm not sure how you are able to run errand and a deploy in parallel since there is an exclusive lock on a deployment.

**Comment by sklevenz** [comment]
+1 for saving the manifest always

"Parallel" is not correct. The Jenkin job runs independently and is time triggered. If a deployment runs in parallel then of course it is blocked by the lock. But after a failed deployment the run errand reports HTTP 500.

**Comment by cppforlife** [comment]
What behavior would you expect given that deployment was not successfully deployed? running old versions of errand?

**Comment by sklevenz** [comment]
The errand can fail to run but should report a more meaningful error message. 

I was thinking about to add a flag like run-force but honestly I don't have a use case for that. If the root cause for a non running errand is a failed deployment then the deployment needs to be fixed to get the errand run.

My proposal is just to improve the error message.

**Comment by mfine30** [comment]
The bosh team has done significant work on the errands implementation since this issue was opened. I don't believe it should still be an issue. If it is, please reopen this github issue.
