### ISSUE TITLE
AWS EC2 ephemeral disk lost after stop/start for some jobs

### ISSUE THREAD

**Issue by wgu** [cloudfoundry/bosh#1050]
Jobs like cloud_controller or mysql server on AWS are on instance type other than t2.micro which has EBS-only disk type. The below code piece might create instance storage for a job instead of EBS-backed ones if the configured ephemeral disk size is less than the instance size for the instance type. This will cause the ephemeral disk lost as AWS does not persistent instance storage after the job is shutdown.

https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/instance_manager.rb#L191-L199

**Comment by cppforlife** [comment]
That's an expected behavior due to how AWS treats instance storage.
