### ISSUE TITLE
Can we upgrade the kernel level and library packages to the latest version？

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1051]
We followed the Bosh standard process to build Ubuntu stemcells, we found the kernel level and library version are pretty old, we want to upgrade to the latest level to avoid security issues. We may want to run the following commands to upgrade:

apt-get update
apt-get -y install --install-recommends linux-generic-ltd-vivid
apt-get upgrade 

Can we do that? Thanks.

**Comment by cppforlife** [comment]
What kernel version are you running on? Official ubuntu stemcells are on a recent 3.19 kernel: 3.19.0-33-generic #38~14.04.1-Ubuntu.

**Comment by mattcui** [comment]
@cppforlife We ran "apt-get -y install --install-recommends linux-generic-ltd-vivid" to upgrade to the latest level of 3.19.0.x for Ubuntu 14.04. Actually, I have more concerns about "apt-get upgrade", do you think if we could run this command to upgrade library packages in the stemcell? Thanks.

**Comment by cppforlife** [comment]
each version of stemcell ships with recent version of packages for trusty. there is no need to run any upgrade procedure since the stemcell is updated as whole.

**Comment by mattcui** [comment]
@cppforlife Currently we used a pretty old code base to build stemcell (we will move to use community version soon). We upgraded kernel level, but we are not very sure if we could upgrade packages with "apt-get upgrade". So from your comments, community stemcell always install the latest level for packages, if so, I think we could upgrade packages also, right? Thanks.

**Comment by cppforlife** [comment]
Probably, we have never tried to run upgrade commands on a live machine.
