### ISSUE TITLE
cf commands failing due to VMs not accessible

### ISSUE THREAD

**Issue by smokingfly** [cloudfoundry/bosh#1060]
Hi,  

While trying to deploy Cloud Foundry on AWS, I ran into problems related to non-availability of service.  

 I see the following VMs:
+------------------------------------+---------+---------------+---------------+
| Job/index | State | Resource Pool | IPs |
+------------------------------------+---------+---------------+---------------+
| api_z1/0 | running | small_z1 | 10.0.16.4 |
| doppler_z1/0 | running | small_z1 | 10.0.16.6 |
| etcd_z1/0 | running | small_z1 | 10.0.16.104 |
| ha_proxy_z1/0 | running | small_z1 | 10.0.0.11 |
| | | | 52.70.161.122 |
| hm9000_z1/0 | running | small_z1 | 10.0.16.5 |
| loggregator_trafficcontroller_z1/0 | running | small_z1 | 10.0.16.7 |
| nats_z1/0 | running | small_z1 | 10.0.16.103 |
| nfs_z1/0 | running | small_z1 | 10.0.16.105 |
| postgres_z1/0 | running | small_z1 | 10.0.16.101 |
| router_z1/0 | running | small_z1 | 10.0.16.102 |
| runner_z1/0 | running | small_z1 | 10.0.16.9 |
| uaa_z1/0 | running | small_z1 | 10.0.16.8 |
+------------------------------------+---------+---------------+---------------+

When I try to access one of the VMs e.g. http://api.cloudrahul-cfapp.com, I get "503 Service Unavailable". A "bosh show cf attributes" results in the following:
bosh-cloudfoundry-0.7.6/lib/bosh/cloudfoundry/release_version_cpi.rb:23:in `initialize': CPI aws_cpi not available for version 149 (RuntimeError)

All the cf commands are failing with the error:

"$ cf target http://api.cloudrahul-cfapp.com

Setting target to http://api.cloudrahul-cfapp.com... FAILED
CFoundry::BadResponse: 503:
503 Service Unavailable
No server is available to handle this request."

Something is certainly missing in my config, could someone please help? I confirm that all VMs (including api_z1) listed above are up and running, including the NAT VM.

This error does not change even after deleting bosh deployments, deleting bosh director server and redeploying bosh from scratch, even with using IP address with "xip.io" e.g. "1.2.3.4.xip.io" in cloudfoundry.yml.

Attached are my configs.

Any help will be greatly appreciated.

[bosh.yml.txt](https://github.com/cloudfoundry/bosh/files/55646/bosh.yml.txt)
[cloudfoundry.yml.txt](https://github.com/cloudfoundry/bosh/files/55647/cloudfoundry.yml.txt)

Some background to the case can be obtained from https://github.com/cloudfoundry/bosh/issues/1037. This issue is also opened on Pivotal Tracker https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/thread/ZOIPJI5KKQWCJ4DRA3XEEMUFFDZP6K2C/ but since no one responded, I thought of having a git ticket rather.

Thanks.

**Comment by cppforlife** [comment]
Im going to close this issue here, since Release Integration team responded on the mailing list.
