### ISSUE TITLE
How to upload a release without dependent files

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1069]
Hello, all

I am trying to create a release, in spec file I will not depend on any file.
But I will download something from somewhere in packaging script.

But with these, I cannot upload the release as there is no dependent files.
Also I don't want to put downloading things to the blobstore of the project as it will cost much space in github.

Right now to work around this, I added one needless file dependency.
Considering my problem, what should I do to avoid adding this needless file, or if there are some other suggestion?

Thanks in advance.

**Comment by dpb587-pivotal** [comment]
As background... BOSH packages are frequently compiled from machines without internet access, so for this reason packages are designed to always expect files. If you're creating a release for public consumption, I'd encourage you to download the file and reference it from the package spec file. For more information about creating releases and blobs, you might be interested in [this page](http://bosh.io/docs/create-release.html) on bosh.io which discusses how blobs are handled and how to avoid committing them to your repository.

If you're just doing `wget`-type for development it really is necessary for you, using a needless file is the only solution.

**Comment by StanleyShen** [comment]
OK, thanks for explanation.
