### ISSUE TITLE
bosh ssh port

### ISSUE THREAD

**Issue by Yancey1989** [cloudfoundry/bosh#1070]
Hi!
It's a problem when i use "bosh ssh ", it will use the ssh session port instead 22. For example, my ssh sesssion's port is 3222, I can not ssh to my vm correct. Is this a bug?
I find the code in bosh_cli/lib/commands/ssh.rb:186 blow:

```
          if gateway
            port        = gateway.open(session['ip'], 22)
            known_host_option  = ssh_session.ssh_known_host_option(port)
            ssh_session_pid = Process.spawn('ssh', "#{ssh_session.user}@localhost", '-p', port.to_s, private_key_option, skip_strict_host_key_checking, known_host_option)
            Process.waitpid(ssh_session_pid)
            gateway.close(port)
          else
```

**Comment by cppforlife** [comment]
Where do you configure 3222 port as your ssh port? Bosh currently only works through port 22 for ssh.

**Comment by Yancey1989** [comment]
I ssh to the host that i deploy with the bosh-lite. like "ssh -p3222 user@host". Then when i run "bosh ssh " it use the port 3222 instead 22.

**Comment by dpb587-pivotal** [comment]
Closing - ssh only works with port 22, and we're moving to a [new CLI](https://github.com/cloudfoundry/bosh-cli) where this shouldn't be an issue. Feel free to reopen there if you still experience this with the new cli, and include more detailed information about the commands you run and which hosts they're run on.
