### ISSUE TITLE
How can I disable the global cache

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1075]
Hello, all

I am trying to create a release and debug some issues.
When I try to "bosh -n deploy", it says getting packages from global cache.
But it seems the global cache is not the latest one.

In this first time, this deploy executes about 30+ minutes since it will download several packages.
But now it finished quickly.

I tried to recreate the package in my local, I even tried to delete the deployment, but it doesn't work.

So how can I disable this "global cache" ?
And if there are some documentation about this global cache, and how does it work?

**Comment by cppforlife** [comment]
Are you using bosh-lite. If you are you can just delete contents of tmp/ folder next to your Vagrantfile. If you are not then you can reconfigure your bosh director manifest.

**Comment by StanleyShen** [comment]
It it good to mentioned it somewhere in document?
