### ISSUE TITLE
bosh deploy --dry-run

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1076]
AFAICT there is no way to perform a deploy dry-run, e.g. to check which jobs/indexes will be affected by a bosh deploy. It would help a lot to have a way to check this.

Even better, when the "manifest diff" is presented during bosh deploy, a list of the jobs/indexes that will be updated could be displayed for confirmation.

**Comment by cppforlife** [comment]
We are planning to add comprehensive diff to replace what CLI currently provides: https://www.pivotaltracker.com/story/show/109914094. Coming up soon.

**Comment by dpb587-pivotal** [comment]
Closing - `bosh deploy --dry-run` was introduced somewhere around v248/v3181 in the linked story. There's a related issue about specific details surrounding affected instances: https://github.com/cloudfoundry/bosh/issues/859

**Comment by dpb587-pivotal** [comment]
Oops... `--dry-run` is on develop but was never released in the CLI gem. But the new CLI has it if you want to give it a try... https://github.com/cloudfoundry/bosh-cli
