### ISSUE TITLE
bosh sync blobs sha1 mismatch

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#1079]
Not 100% why but latest version of bosh cli I get 
```
/home/lnguyen/.rvm/gems/ruby-2.2.1/gems/blobstore_client-1.3163.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:38:in `check_sha1': sha1 mismatch expected=3af011cc19b21c7180f2604fd85fbc4ddde97143 actual=e62d3649ce2710833408f1ab451a1c7ef506c631 (Bosh::Blobstore::BlobstoreError)
```
on bosh sync blobs. It worked for a friend on `1.3147.0` so I switched to using that and it works. Haven't had time to pin point version that it broke on. Anyone seeing this?

**Comment by cppforlife** [comment]
Does this happen consistently? This error is shown when downloaded blob did not match expected sha1. That may happen when somehow either remote blob is corrupted or download procedure was somehow corrupted and transferred bits are not correct.

**Comment by longnguyen11288** [comment]
It happen consistently, it's interesting that when I revert back to older version it just works and I know remote isn't corrupted because bosh.io can even cut releases. Will try again today and see what happens. 

On January 6, 2016 at 7:49:27 PM, Dmitriy Kalinin (notifications@github.com) wrote:

Does this happen consistently? This error is shown when downloaded blob did not match expected sha1. That may happen when somehow either remote blob is corrupted or download procedure was somehow corrupted and transferred bits are not correct.

**Comment by poblin-orange** [comment]
Just met this with bosh-cli:  BOSH 1.3167.0

```
 bosh upload release ./releases/networking/networking-5.yml
Acting as user 'admin' on 'micro-bosh'
Downloading from blobstore (id=772fcc8a-c4c7-4119-9722-c51a9140c47a)...
Blobstore error: sha1 mismatch expected=28a1d88aba72724f0a4b0173a814c8c3bd36448c actual=f97f1ebad98e3d29ac2aed31c9df8381f25bea48
```

**Comment by frodenas** [comment]
Any release that uses the `encryption_key` feature (like the [networking](https://github.com/cf-platform-eng/networking-boshrelease/blob/master/config/final.yml#L9) release) will hit this problem if using a bosh cli version > 3144. See this [post](https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/thread/H365YFWROOHGOGBGLPBNWT7LLBGBIQEB/).

**Comment by bosh-ci-push-pull** [comment]
Ah that would be it. I just sent a response about this to the mailing list.
