### ISSUE TITLE
VM timezone and time mismatch

### ISSUE THREAD

**Issue by linlynn** [cloudfoundry/bosh#1082]
When we use bosh to deploy cloud foundry , timezone in VM is UTC however time in VM is local time(China) .Bosh version is 1.3138.0 . Any idea about this mismatch ? 
CF is deployed over Vsphere

**Comment by cppforlife** [comment]
Are you configuring NTP servers as shown in the example: http://bosh.io/docs/init-aws.html?

**Comment by linlynn** [comment]
@cppforlife  good point , looks like we are missing that
