### ISSUE TITLE
How to clean up the fingerprint for the old director VM?

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1083]
I am deploying CF on AWS with bosh-lite way.

When I ssh to one job VM, I will use the director VM like this:
bosh ssh --gateway_identity_file=~/.ssh/id_rsa_bosh  --gateway_host=xx.xx.xx.xx --strict_host_key_checking=no

And then I recreated the director VM(xx.xx.xx.xx) and deployed CF again on it.
The director IP is the same one with before.

But right now I got below error when I tried to ssh to the job VM again:

/var/lib/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/verifiers/secure.rb:50:in `process_cache_miss': fingerprint ee:ea:40:19:64:a1:db:cc:3f:93:80:c2:6d:b0:56:c6 does not match for "xx.xx.xx.xx" (Net::SSH::HostKeyMismatch)
How can I clean this?

**Comment by dpb587-pivotal** [comment]
Since you recreated the bosh-lite/director it has a new fingerprint and you should run `ssh-keygen -R xx.xx.xx.xx` which will remove the old fingerprint from `~/.ssh/known_hosts`. Then your existing `bosh ssh ...` command should work.

**Comment by StanleyShen** [comment]
Thanks
