### ISSUE TITLE
bosh health monitor fails to start if nats password contains /

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1084]
When your nats password contains slashes, the ruby bosh monitor fails to start. The password is correctly placed into [config](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/health_monitor/templates/health_monitor.yml.erb#L8), but the app fails with st. like (sorry I don't have the logs anymore) `"Wrong module name <nats_password>"`. 

I tried putting quotes and double quotes around the password in the yaml config, also escaping the slashes, but it didn't fix the problem. Removing slashes from the password fixes the issue. The rest of the BOSH components didn't have problem with the NATS password containing slashes...

**Comment by dpb587-pivotal** [comment]
I've run into this sort of thing as well; agree a fix would be nice.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/111192606

**Comment by mtekel** [comment]
Looks like this was released...

**Comment by dpb587-pivotal** [comment]
Thanks for remembering and closing! Officially in [v247+](https://github.com/cloudfoundry/bosh/releases/tag/stable-3177).
