### ISSUE TITLE
Bosh template should enable trim_mode

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/bosh#1086]
Hello,

For now, bosh template does not set trim_mode [(erb doc)](http://ruby-doc.org/stdlib-2.3.0/libdoc/erb/rdoc/ERB.html#method-c-new), which makes it hard to make a properly formatted output.

We wish to have bosh template supporting `<% -%>` modifier by setting `trim_mode = "-"` in `lib/bosh/template/renderer.rb` file of `bosh-template` lib.

This change should not break backward compatibility.

**Comment by dpb587-pivotal** [comment]
Closing - thanks for PR #1159 which was merged and fixed this issue!

**Comment by liuweichu** [comment]
Ohh sorry, I forgot to close.
Thank you 😃
