### ISSUE TITLE
upgrading one release resulting in monit restart all or restart all

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry/bosh#1087]
We have redis cluster and a custom sensu release along with redis for monitoring when we update our sensu release .. it restart all processes on VM .. including redis expected behavior is it should restart only sensu not redis .. or restarting everything for even single release change is expected ?

**Comment by bosh-ci-push-pull** [comment]
That is expected at this point. All processes on a machine are restarted.

**Comment by geofffranks** [comment]
+1

What would it take to have bosh know which jobs were affected (via package updates, or job templates changing), and only restart the corresponding monit processes?

**Comment by mfine30** [comment]
While this is a valid use case, it is outside of the scope of work that we are currently interested in addressing on the bosh team. To help gauge interest though, please feel free to comment and leave specific use cases.
