### ISSUE TITLE
bosh stop --hard does not work on AWS

### ISSUE THREAD

**Issue by sudhindrarao** [cloudfoundry/bosh#1088]
Commits here does not work on AWS
https://github.com/cloudfoundry/bosh/commit/05cae32fea37875eb3fac6cacadb08e79f39ee28

I have tried to do a bosh stop --hard on PCF 1.6.4 -build 1( Stemcell 3040) Jobs and with resurrector disabled (running all these in a script)

jobs name becomes "unknown" and job state shows "running" state.
Diego Cells job is worse - I see no diego processes inside the VM - drain scripts fails upon bosh start - only way I can get this fixed is to recreate the Diego cells vm. -----------------+---------+--------------------------------------------------------------+------------+ | Job/index | State | Resource Pool | IPs | +-----------------+---------+--------------------------------------------------------------+------------+ | unknown/unknown | running | clock_global-partition-f99bec444d276db0e93a | 10.0.16.30 | | unknown/unknown | running | cloud_controller-partition-f99bec444d276db0e93a | 10.0.16.34 | | unknown/unknown | running | cloud_controller_worker-partition-f99bec444d276db0e93a | 10.0.16.33 | | unknown/unknown | running | consul_server-partition-f99bec444d276db0e93a | 10.0.16.37

**Comment by cppforlife** [comment]
@sudhindrarao Team has confirmed that issue is fixed in later Director builds.

**Comment by sudhindrarao** [comment]
Can you please advice on which stemcell  this is fixed in ?
I have tried this on  stemcell 3046 and it fails the same way.
