### ISSUE TITLE
httpclient is out of date and throws warnings in Ruby 2.3

### ISSUE THREAD

**Issue by jpalermo** [cloudfoundry/bosh#1092]
We see these warnings:
```
Object#timeout is deprecated, use Timeout.timeout instead.
```

* https://github.com/nahi/httpclient/issues/292

One or more sub-gems specify `spec.add_dependency 'httpclient', '=2.4.0'`, ex:
* https://github.com/cloudfoundry/bosh/blob/develop/agent_client/agent_client.gemspec#L22

**Comment by ramonskie** [comment]
any update on this?
because those deprecation warnings are really annoying..

**Comment by eddiewebb** [comment]
@ramonskie I just updated the gemspec file in question locally to use 2.7.1 and it eliminates the error until the gem can be patched properly.

**Comment by SamuelMarks** [comment]
In the meantime you can also run these two on your `httpclient-2.4.0` directory:
```
find -name '*.rb' -type f -exec sed -i 's/ timeout(\@/ ::Timeout.timeout\(/g' {} \;
find -name '*.rb' -type f -exec sed -i 's/ timeout\(([[@]]\)/ ::Timeout.timeout\1/g' {} \;
```

**Comment by dpb587-pivotal** [comment]
Tracker story for reference: https://www.pivotaltracker.com/story/show/111538726

**Comment by dpb587-pivotal** [comment]
Closing - `httpclient` was updated to 2.7.1 via f789444f4 and released as of [3189](https://github.com/cloudfoundry/bosh/releases/tag/stable-3189).
