### ISSUE TITLE
Adding disable-axfr=yes property to bosh power dns does not take effect

### ISSUE THREAD

**Issue by sdheepa** [cloudfoundry/bosh#1093]
In the bosh director yaml I tried to add the following property to power dns to disable zone xfer (to prevent the vulnerability) and deployed the bosh director. But I see that in the power dns config file (pdns.conf) on the director, this change is not getting reflected. I only see the recursor property but not the disable-axfr.  Is this property something that cannot be set through the yaml? By default I believe this value is false which means zone transfers are allowed. Is that a correct understanding? How do I update this property in bosh power dns? Appreciate any help!

dns:
      recursor: 8.8.8.8
      disable-axfr: true

**Comment by cppforlife** [comment]
You will have to expose that configuration in https://github.com/cloudfoundry/bosh/blob/master/release/jobs/powerdns/spec and use it in https://github.com/cloudfoundry/bosh/blob/master/release/jobs/powerdns/templates/pdns.conf.erb.

**Comment by sdheepa** [comment]
Thanks for the quick response! A follow on question..After making these changes, in order for the director to pick up these changes I would have to build a bosh stemcell and then deploy the bosh director with the updated yaml file that contains the new property. Does that sound correct?

**Comment by cppforlife** [comment]
@sdheepa Just have to build a new bosh release and use bosh-init to update Director. For example see http://bosh.io/docs/init-aws.html how it points to bosh release. You can use `url: file://~/bosh-rel.tgz` and skip sha1 when using local file.
