### ISSUE TITLE
Pre-script + Monit

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1094]
I tried adding a `pre-script` to one of my releases which wants to manually start a monit process before everything else. Worked well on existing instances, but on newly created VMs it errored. Turned out monit didn't have the configs installed yet.

    $ monit summary
    /var/vcap/bosh/etc/monitrc:8: Warning: include files not found '/var/vcap/monit/job/*.monitrc'
    The Monit daemon 5.2.5 uptime: 8m 

    System 'system_localhost'           running

Is it intentional to run pre-scripts before installing the latest monit configs?

director = v215 on 3104; deployment = 3169

**Comment by cppforlife** [comment]
That's expected. pre_start scripts run when before jobs are not configured with monit. You'll have run your ctl explicitly (e.g. blah_ctl start, do some work, blah_ctl stop).

**Comment by dpb587** [comment]
Ah, that's a great alternative. Thanks!
