### ISSUE TITLE
make EM.threadpool_size configurable

### ISSUE THREAD

**Issue by leizhu** [cloudfoundry/bosh#1098]
Due to network latency, the sending speed of Bosh metrics is slow from China region to Datadog server.
After a period,  the time lag is so big  that Datadog drops any new incoming metric.

The possible fix is to change the following file to accept a config param for EM.threadpool_size
bosh_monitor/lib/bosh/monitor/runner.rb

**Comment by dpb587-pivotal** [comment]
Closing - thanks for PR #1102 which was merged and fixed this issue!
