### ISSUE TITLE
BOSH command to show history of deployments

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh#1103]
I can't find a way to see when a certain version of a release was deployed. This makes debugging a faulty component very difficult, because it's unclear with what version a certain misbehavior was introduced. The `bosh tasks recent` command also doesn't help here, because it doesn't allow to show deployment actions for only one release.

**Comment by drnic** [comment]
It's long winded - but you could look at the top of the task logs where the deployment manifest is cached:




bosh task <num> --debug | head

**Comment by petergtz** [comment]
I think that's not exactly what I want (unless I misunderstood you). Instead, what I want to ask BOSH is e.g.:
"Which versions of MyComponent did you deploy in the last 10 days at what time?"

In the end, it's very similar to what `bosh tasks recent` gives me. But this tells me only when a certain release (including version) was *created*, but not when this version was *deployed*. Instead it only gives me:

    | 995  | done | 2016-01-14 11:24:03 UTC | admin | create deployment  | /deployments/MyComponent          |
    | 994  | done | 2016-01-14 10:39:26 UTC | admin | create release     | Created release `MyComponent/26'  |

 To map incidents that happened in the past to a certain code version, something like this seems like an essential feature for a deployment tool. Is it possible that BOSH does not support this?

**Comment by bosh-ci-push-pull** [comment]
BOSH currently does not have an audit history that's nicely presentable via
CLI, but it's something that we want to add as part of auditing feature.
Majority of our deployments (bosh deploys) are from within <
http://concourse.ci/> so we in most cases we look at the build history.

**Comment by cppforlife** [comment]
We recently started work on https://github.com/cloudfoundry/bosh-notes/blob/master/events.md. "events" label in tracker.

**Comment by petergtz** [comment]
Nice! This is pretty much what I had in mind.

**Comment by cppforlife** [comment]
Events were added few months ago: https://bosh.io/docs/events.html. Over time we are expanding information recorded in/as events as we change/add Director functionality.
