### ISSUE TITLE
BOSH VM Creation and Re-Creation in one run

### ISSUE THREAD

**Issue by jrbudnack** [cloudfoundry/bosh#1104]
Greetings - 

We just recently upgraded our microboshes from v219 to v246 and are now using stemcell 3177 for vSphere. Since doing that upgrade, we have not been able to consistently run bosh errands - in some deployments we aren't able to at all. I tried rolling back to stemcell 3033 (the last known good one) and it didn't solve the problem, so it looks like BOSH may be the culprit.  

We keep getting this error:

Error 450002: Timed out sending `update_settings' to 6fec090d-f5f8-4d3e-a1a6-183d87284f77 after 45 seconds

"45" seems to be the default timeout for the AgentClient class when it isn't fed a timeout through its options.

After doing further digging, we traced it to the "env.bosh.password" property on one of our resource pools.  When this property exists, BOSH goes through the following workflow:

1) Create the instance.
2) Change the password - and in order to do that...
   a) Shut down the instance
   b) Re-create the instance with the new password

The problem:  When BOSH re-creates the instance with the new password, it issues a new UUID for the bosh agent.  However, BOSH still listens for the first UUID issued (during "1) Create the instance.").  Since that bosh agent is no longer running, the timeout occurs.

So, when we remove env.bosh.password, the problem seems to go away.

**Comment by jrbudnack** [comment]
Here is an example of what we see in the logs (shortened and annotated, with sensitive data redacted):

CREATE THE FIRST VM:
I, [2016-01-19T18:03:42.870144 #26066]  INFO -- : Creating vm: vm-fbd9071f-8257-4b2d-b3bc-58f2ab2d188a on <[Vim.ClusterComputeResource] domain-c8> stored in <[Vim.Datastore] datastore-97>
I, [2016-01-19T18:03:42.881412 #26066]  INFO -- : Stemcell lives on a different datastore, looking for a local copy of: sc-1a8926ab-d1f7-4649-b2e6-743ef7a4d0a9.
I, [2016-01-19T18:03:42.887621 #26066]  INFO -- : Found local stemcell replica: <[Vim.VirtualMachine] vm-10871>
I, [2016-01-19T18:03:42.887684 #26066]  INFO -- : Using stemcell VM: <[Vim.VirtualMachine] vm-10871>
I, [2016-01-19T18:03:42.944202 #26066]  INFO -- : Cloning vm: (VSphereCloud::Resources::VM (cid="sc-1a8926ab-d1f7-4649-b2e6-743ef7a4d0a9")) to vm-fbd9071f-8257-4b2d-b3bc-58f2ab2d188a
D, [2016-01-19T18:03:42.971320 #26066] DEBUG -- : Found requested resource pool: <[Vim.ResourcePool] resgroup-533>
I, [2016-01-19T18:03:50.566056 #26066]  INFO -- : Setting VM env: {"vm"=>{"name"=>"vm-fbd9071f-8257-4b2d-b3bc-58f2ab2d188a", "id"=>"vm-11504"},
 "agent_id"=>"6f99c79b-cf47-457f-9005-24ccae5f471b",
 "networks"=>
  {"default"=>
    {"ip"=>"10.19.48.248",
     "netmask"=>"255.255.240.0",
     "cloud_properties"=>{"name"=>"SB_PCF"},
     "default"=>["dns", "gateway"],
     "dns"=>["10.18.99.10"],
     "gateway"=>"10.19.48.1",
     "mac"=>"00:50:56:ae:57:83"}},
 "disks"=>{"system"=>"0", "ephemeral"=>"1", "persistent"=>{}},
 "ntp"=>["10.18.99.10", "10.18.99.5"],
 "blobstore"=>
  {"provider"=>"dav",
   "options"=>
    {"endpoint"=>"http://10.19.64.4:25250",
     "user"=>"agent",
     "password"=>"REDACTED"}},
 "mbus"=>"nats://nats:nats@10.19.64.4:4222",
 "env"=>
  {"bosh"=>
    {"password"=>
      "REDACTED"}}}
...
PASSWORD CHANGE:
D, [2016-01-19 18:04:48 #26039] [canary_update(push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625))] DEBUG -- DirectorJobRunner: env_changed? changed FROM: {} TO: {"bosh"=>{"password"=>"REDACTED"}} on instance push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625)
D, [2016-01-19 18:04:48 #26039] [canary_update(push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625))] DEBUG -- DirectorJobRunner: VM needs to be shutdown before it can be updated.
D, [2016-01-19 18:04:48 #26039] [canary_update(push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625))] DEBUG -- DirectorJobRunner: Failed to update in place. Recreating VM
I, [2016-01-19 18:04:48 #26039] [canary_update(push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625))]  INFO -- DirectorJobRunner: Deleting VM
D, [2016-01-19 18:04:48 #26039] [canary_update(push-apps-manager/0 (99d94835-0e6a-4fc9-aac2-8ece3ce81625))] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"delete_vm","arguments":["vm-fbd9071f-8257-4b2d-b3bc-58f2ab2d188a"],"context":{"director_uuid":"095aa975-c092-40c4-aa2a-2a5337a30353"}} with command: /var/vcap/jobs/vsphere_cpi/bin/cpi
...
CREATE SECOND VM:
[2016-01-19T18:05:03.638964 #26391] DEBUG -- : VM creator initialized with memory: 4096, disk: , cpu: 2, placer: (VSphereCloud::FixedClusterPlacer (cluster="(VSphereCloud::Resources::Cluster (name="FD1"))"))
D, [2016-01-19T18:05:03.745740 #26391] DEBUG -- : Looking for a ephemeral datastore in FD1 with 17408MB free space.
D, [2016-01-19T18:05:03.745989 #26391] DEBUG -- : All datastores within cluster FD1: ["STORAGE3-BLOCK (6689244MB free of 31457024MB capacity)", "STORAGE2-BLOCK (9354899MB free of 36699904MB capacity)", "STORAGE1-BLOCK (8572882MB free of 36699904MB capacity)"]
D, [2016-01-19T18:05:03.746187 #26391] DEBUG -- : Datastores with enough space: ["STORAGE3-BLOCK (6689244MB free of 31457024MB capacity)", "STORAGE2-BLOCK (9354899MB free of 36699904MB capacity)", "STORAGE1-BLOCK (8572882MB free of 36699904MB capacity)"]
I, [2016-01-19T18:05:03.746565 #26391]  INFO -- : Creating vm: vm-fa204871-c84c-4cd8-9b3e-be1832fb5745 on <[Vim.ClusterComputeResource] domain-c8> stored in <[Vim.Datastore] datastore-97>
I, [2016-01-19T18:05:03.773032 #26391]  INFO -- : Stemcell lives on a different datastore, looking for a local copy of: sc-1a8926ab-d1f7-4649-b2e6-743ef7a4d0a9.
I, [2016-01-19T18:05:03.787062 #26391]  INFO -- : Found local stemcell replica: <[Vim.VirtualMachine] vm-10871>
I, [2016-01-19T18:05:03.787209 #26391]  INFO -- : Using stemcell VM: <[Vim.VirtualMachine] vm-10871>
I, [2016-01-19T18:05:03.903580 #26391]  INFO -- : Cloning vm: (VSphereCloud::Resources::VM (cid="sc-1a8926ab-d1f7-4649-b2e6-743ef7a4d0a9")) to vm-fa204871-c84c-4cd8-9b3e-be1832fb5745
D, [2016-01-19T18:05:03.947784 #26391] DEBUG -- : Found requested resource pool: <[Vim.ResourcePool] resgroup-533>
I, [2016-01-19T18:05:11.549443 #26391]  INFO -- : Setting VM env: {"vm"=>{"name"=>"vm-fa204871-c84c-4cd8-9b3e-be1832fb5745", "id"=>"vm-11505"},
 "agent_id"=>"85e712f6-95e9-429b-b812-1795bfb3024d",
 "networks"=>
  {"default"=>
    {"ip"=>"10.19.48.248",
     "netmask"=>"255.255.240.0",
     "cloud_properties"=>{"name"=>"SB_PCF"},
     "default"=>["dns", "gateway"],
     "dns"=>["10.18.99.10"],
     "gateway"=>"10.19.48.1",
     "mac"=>"00:50:56:ae:2c:f5"}},
 "disks"=>{"system"=>"0", "ephemeral"=>"1", "persistent"=>{}},
 "ntp"=>["10.18.99.10", "10.18.99.5"],
 "blobstore"=>
  {"provider"=>"dav",
   "options"=>
    {"endpoint"=>"http://10.19.64.4:25250",
     "user"=>"agent",
     "password"=>"REDACTED"}},
 "mbus"=>"nats://nats:nats@10.19.64.4:4222",
 "env"=>
  {"bosh"=>
    {"password"=>
      "REDACTED"}}}
at depth 0 - 20: unable to get local issuer certificate
at depth 0 - 20: unable to get local issuer certificate
I, [2016-01-19T18:05:18.108711 #26391]  INFO -- : Powering on VM: (VSphereCloud::Resources::VM (cid="vm-fa204871-c84c-4cd8-9b3e-be1832fb5745"))
...
ERROR:
Error 450002: Timed out sending `update_settings' to 6f99c79b-cf47-457f-9005-24ccae5f471b after 45 seconds

**Comment by dpb587-pivotal** [comment]
I think this issue was fixed in bosh [v250](https://github.com/cloudfoundry/bosh/releases/tag/stable-3184.1).
