### ISSUE TITLE
upgrade dogapi

### ISSUE THREAD

**Issue by funcode** [cloudfoundry/bosh#1105]
Currently DadaDog Ruby API gem dogapi-1.6.0 is used by bosh-monitor. However, this version has a drawback in APIService class(in common.rb): the timeout value for HTTP session is not configurable:
```
    # Manages the HTTP connection
    def connect
      uri = URI.parse(@api_host)
      session = Net::HTTP.new(uri.host, uri.port)
      if 'https' == uri.scheme
        session.use_ssl = true
        # FIXME - turn off SSL verification for now until we can spend
        # some time figuring out how to find certs across platforms.
        # - matt 10/06/2011
        session.verify_mode = OpenSSL::SSL::VERIFY_NONE
      end
      session.start do |conn|
        conn.read_timeout = 5
        yield(conn)
      end
    end
```
This is needed as when sending from a remote place to Datadog, the connection read timeout value should be bigger, like 60. It is supported in the newer version of dogapi package. 
Please refer: https://github.com/DataDog/dogapi-rb/issues/29

**Comment by dpb587-pivotal** [comment]
Closing - `dogapi` was upgraded in to 1.21 via [#1142](https://github.com/cloudfoundry/bosh/pull/1142).
