### ISSUE TITLE
Unable to delete deployment after upgrading from v219 to v246

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1106]
We're running into some DB schema issues when trying to delete a deployment on a BOSH that we've upgraded from v219 to v246. The error being thrown is: 

PG::Error: ERROR:  update or delete on table "deployments" violates foreign key constraint "vms_deployment_id_fkey" on table "vms" DETAIL:  Key (id)=(18) is still referenced from table "vms".

It's occurring on BOSH's hooked up to both AWS + vSphere. When we take a look at the VMs table, there are a bunch of VMs in there with cids who do not match any live instances. It looks like the data from the `vms` table was migrated into the `instances` table, somewhere between v219 and v246, but never cleaned up. Is the `vms` table no longer used for anything?

If so, can it be cleaned up via another schema migration?

Reproduction steps should be deploy BOSH v219.. deploy a boshrelease with VMs. Upgrade BOSH to v246. Try running a `bosh delete deployment`

**Comment by cppforlife** [comment]
yup. unfortunelty our integration testing didnt catch this migration breakage. next build will it.

**Comment by dpb587-pivotal** [comment]
I think this was fixed in [v250](https://github.com/cloudfoundry/bosh/releases/tag/stable-3184.1) and can be closed.
