### ISSUE TITLE
AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1107]
I am trying to deploy cf release to AWS and the manifest file was working, the VMs can be created with my AWS security keys.

Lately I changed my AWS security keys and replaced  them in the manifest file.
But now the VMs cannot be created due to errors like:

   Failed creating bound missing vms > medium_z1/3: Unknown CPI error 'Unknown' with message 'AWS was not able to validate the provided access credentials' (00:00:46)

I also tried to delete the deployment and try again, but I still run into this issue.
The new key is correct, I can use it in my AWS cli.

What could be the problem?

**Comment by dpb587-pivotal** [comment]
Double check that your director is using the correct time. If it's noticeably off, AWS will respond with the error you mentioned.

**Comment by StanleyShen** [comment]
@bosh-cpi-robot Thanks, it's my case. I thought the key used is the one specified in my cf-release manifest, and I didn't notice it's actually the one specified when I deployed the director VM.
@dpb587-pivotal you mentioned is not my case, but I did find this answer for such case when I was googling this issue.

So if the key specified when deploying the director VM is used, why do we still need to specify AWS credentials in cf-release manifest, is that useless?

If we specified the AWS credentials in cf-release manifest, won't it override the one specified in deploying  director?

In my first opinion, I think the credential we specified in deploying director is only for launching director VM. And in other manifest, we still need to specify AWS credential to launch VMs needed in that deployment.

**Comment by StanleyShen** [comment]
It looks like I am wrong in understanding it.
the AWS credential specified in cf-release.yml is not used for launching VMs defined in deployment.

So we always use the AWS credential provided in creating the director to launch VMs in deployment.
