### ISSUE TITLE
Missing stemcell AMI image for AWS Asia Pacific (Seoul) region

### ISSUE THREAD

**Issue by premist** [cloudfoundry/bosh#1110]
AWS [launched](https://aws.amazon.com/ko/blogs/aws/now-open-aws-asia-pacific-seoul-region/) Asia Pacific (Seoul) region this month. After modifying [bosh-aws-cpi-release](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/25/files) to have support for AWS Seoul region, I encountered another error related to stemcell.

	Command 'deploy' failed:
	  creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3012):
	    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Stemcell does not contain an AMI for this region (ap-northeast-2)","ok_to_retry":false}

I created a PR([#1109](https://github.com/cloudfoundry/bosh/pull/1109)) which adds `ap-northeast-2` to the AWS region list, but I'm not sure which part I should look into in order to create a stemcell AMI image for the new region.

**Comment by dpb587-pivotal** [comment]
Light stemcells include AMIs for `ap-northeast-2` as of 3189...

    $ curl -s -L https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3189 | tar -xzOf- stemcell.MF | grep ap-northeast-2 | awk '{print $2}'
    ami-37f63859

Related story: https://www.pivotaltracker.com/story/show/112368753

**Comment by srik54760** [comment]
like this only I am getting the same error . Error: CPI error 'Bosh::Clouds::CloudError' with message 'Stemcell does not contain an AMI in region eu-west-1' in 'create_stemcell' CPI method (CPI request ID: 'cpi-626547')
