### ISSUE TITLE
Possible to build a set of images with bigger root partition?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1115]
I saw there is the commit [e9681a7](https://github.com/jianqiu/bosh/commit/e9681a7eb04f0fa6dfd0814d5fae8ffb72319308) reducing the size of / from 10G to 3G, but in production environment, 3G is really too small, is it possible to build 2 set of images with 3G and 10G root partition for dev and production? Thanks.

**Comment by dpb587-pivotal** [comment]
Which CPI/IaaS are you using? In AWS you can use `resource_pools[*].cloud_properties.root_disk.size` ([docs](http://bosh.io/docs/aws-cpi.html#resource-pools)) to get a larger root disk, but it doesn't look like other CPIs currently have this option.

**Comment by mattcui** [comment]
It's vmware.

**Comment by voelzmo** [comment]
@mattcui out of curiosity: What are you putting on the root disk that you need a bigger one?

**Comment by mattcui** [comment]
Our customers need to install some security/audit softwares, they are pretty big....

**Comment by dpb587-pivotal** [comment]
As of [v25](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/releases/tag/v25) you can configure a `root_disk.size` on your resource pool (see the [docs](http://bosh.io/docs/openstack-cpi.html)) for more details.
