### ISSUE TITLE
A critical bug in Ubuntu kernel impacting Diego

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1117]
We got a report that there is a critical bug (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043) introduced in the kernel of Ubuntu in the late of last Oct. It effects Diego (Garden in particular) and Docker, seems it's already fixed in AUFS, but from the bug's comments, there hasn't built a kernel release including the fix. We are using stemcell for SoftLayer, hope to see some suggestions from Bosh community on how to revert the kernel to an earlier level before last Oct. when building the stemcell before this problem is fixed in the kernel? Thanks.

@cppforlife @maximilien

**Comment by cppforlife** [comment]
@mattcui we are still waiting for ubuntu to publish updated kernel. will publish a new stemcell when that happens. meanwhile diego team is confirming that their fix works in our dev envs.

**Comment by cppforlife** [comment]
Closing, since there was a fix in https://github.com/cloudfoundry/bosh/releases/tag/stable-3192
