### ISSUE TITLE
bosh upload release --fix doesn't upload jobs

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1119]
Using director v250, it seems like `bosh upload release --fix` only uploads packages, not the jobs.

### Steps to reproduce:
* `bosh upload release dummy/0+dev.1`
* Switch blobstore in bosh manifest and re-deploy with bosh-init
* `bosh upload release dummy/0+dev.1 --fix`

### Expected
All artifacts are uploaded to the new blobstore and you can do `bosh deploy` on the dummy release

### Actual
`Error 100: S3 object 'e9759a54-0be5-427e-92a9-2ba61db5bfda' not found`

### Screenshots
Here is the output of `bosh inspect release`:
<img width="1209" alt="screen shot 2016-01-30 at 13 17 24" src="https://cloud.githubusercontent.com/assets/2256887/12695627/bfd99bfe-c754-11e5-8f43-7ca0e61e0442.png">

And the S3 view of the blobstore
<img width="347" alt="screen shot 2016-01-30 at 13 17 37" src="https://cloud.githubusercontent.com/assets/2256887/12695629/c6ba7f24-c754-11e5-82dd-37c97de397d5.png">

Doing `bosh delete release` and a `bosh upload release` fixes the problem, so I can deploy.

**Comment by guoger** [comment]
@voelzmo We believe this is related to this story https://www.pivotaltracker.com/story/show/103869294 and we were indeed only focusing on broken packages but not jobs. Probably we should hear back from @cppforlife on this.

**Comment by cppforlife** [comment]
@voelzmo mind giving it a try to see if it solved this problem?

**Comment by voelzmo** [comment]
@cppforlife can confirm this is fixed and works out. Thanks!
