### ISSUE TITLE
Repeated manifest value type changes in deploys (String/Float)

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1120]
Without changing my deployment manifest, director tells me the version of a release and a resource pool's stemcell needs to change type (`String` -> `Float`). Odd, but even if I deploy with the type change, the next deploy tells me the exact same thing.

Was deployed against director with `bosh/v250`, `bosh-aws-cpi/v39`, `aws-xen-hvm-ubuntu-trusty-go_agent/v3184.1`, and no cloud-config. Didn't notice this issue last deploy, which was with director `bosh/v215`, `bosh-aws-cpi/v33`, `aws-xen-hvm-ubuntu-trusty-go_agent/v3104`.

Local manifest snippet...

    releases:
        -
            name: tle-httpforwarders
            version: 8.0.0
        -
            name: logsearch-shipper
            version: 2+dev.1
        -
            name: consul-bosh-links
            version: latest
        -
            name: consul
            version: latest
    resource_pools: 
        - 
            cloud_properties: # more stuff
            env: 
                bosh: 
                    password: # more stuff
            name: z0_default 
            network: z0_public 
            stemcell: 
                name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent 
                version: 3184.1 
    # more stuff

Downloading the manifest says...

    releases:
    - name: tle-httpforwarders
      version: 8.0.0
    - name: logsearch-shipper
      version: 2+dev.1
    - name: consul-bosh-links
      version: 0+dev.3
    - name: consul
      version: '17'
    resource_pools:
    - cloud_properties: # more stuff
      env:
        bosh:
          password: # more stuff
      name: z0_default
      network: z0_public
      stemcell:
        name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
        version: '3184.1'

Deployment output...

    $ bosh deploy
    Acting as user 'dannyb' on deployment 'httpforwarders' on 'prod-abraxas-aws-usw2'
    Getting deployment properties from director...

    Detecting deployment changes
    ----------------------------
    Releases
    consul
      version type changed: String -> Fixnum
        - 17
        + 17

    Compilation
    No changes

    Update
    No changes

    Resource pools
    z0_default
      stemcell
        version type changed: String -> Float
          - 3184.1
          + 3184.1

    Disk pools
    No changes

    Networks
    No changes

    Jobs
    No changes

    Properties
    No changes

    Please review all changes carefully

    Deploying
    ---------
    Are you sure you want to deploy? (type 'yes' to continue): yes

    Director task 9449
      Started preparing deployment > Preparing deployment. Done (00:00:00)

      Started preparing package compilation > Finding packages to compile. Done (00:00:01)

    Task 9449 done

    Started		2016-01-31 21:44:18 UTC
    Finished	2016-01-31 21:44:19 UTC
    Duration	00:00:01

    Deployed `httpforwarders' to `prod-abraxas-aws-usw2'

Attempting to deploy again gives the same diff...

    $ bosh deploy
    Acting as user 'dannyb' on deployment 'httpforwarders' on 'prod-abraxas-aws-usw2'
    Getting deployment properties from director...

    Detecting deployment changes
    ----------------------------
    Releases
    consul
      version type changed: String -> Fixnum
        - 17
        + 17

    Compilation
    No changes

    Update
    No changes

    Resource pools
    z0_default
      stemcell
        version type changed: String -> Float
          - 3184.1
          + 3184.1

    Disk pools
    No changes

    Networks
    No changes

    Jobs
    No changes

    Properties
    No changes

    Please review all changes carefully

    Deploying
    ---------
    Are you sure you want to deploy? (type 'yes' to continue): yes

    Director task 9450
      Started preparing deployment > Preparing deployment. Done (00:00:00)

      Started preparing package compilation > Finding packages to compile. Done (00:00:00)

    Task 9450 done

    Started		2016-01-31 21:44:54 UTC
    Finished	2016-01-31 21:44:54 UTC
    Duration	00:00:00

    Deployed `httpforwarders' to `prod-abraxas-aws-usw2'

Relevant releases on the director...

    $ bosh releases
    Acting as user 'dannyb' on 'prod-abraxas-aws-usw2'

    +------------------------+------------+-------------+
    | Name                   | Versions   | Commit Hash |
    +------------------------+------------+-------------+
    | bosh-consul-links      | 0+dev.19*  | 00000000+   |
    | consul                 | 12+dev.14  | ff75f392+   |
    |                        | 12+dev.18  | f52f9875+   |
    |                        | 17*        | ae2f7872+   |
    | logsearch-shipper      | 1          | 88eb3239+   |
    |                        | 2*         | 5607842f+   |
    |                        | 2+dev.1*   | 4dd8e035    |
    | tle-httpforwarders     | 6.0.0      | e9fa1cc1    |
    |                        | 7.0.0      | 873f8839+   |
    |                        | 8.0.0*     | d0575ec6+   |
    +------------------------+------------+-------------+

(internal ref `af395b1@1454277299`)

**Comment by mariash** [comment]
Hey Danny, this is an old style diff. Are you using old cli? The new style does not differentiate version types.

Maria

**Comment by dpb587** [comment]
Oops, I forgot to double check that. I'll verify that tonight.


On Monday, February 1, 2016, Maria Shaldibina <notifications@github.com>
wrote:

> Hey Danny, this is an old style diff. Are you using old cli? The new style
> does not differentiate version types.
>
> Maria
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh/issues/1120#issuecomment-178020716>.
>


-- 
Danny Berger
http://dpb587.me

**Comment by dpb587** [comment]
Upgraded bosh_cli to 3184.1 and this is no longer happening (although more weirdness around [null values](https://github.com/cloudfoundry/bosh/issues/1121)). It'd be nice if cli would warn me if it's too far out of date with the director it's talking to.
