### ISSUE TITLE
worker process count not configurable on director job

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/bosh#1131]
We want to increase the number of parallel tasks that our single-node director will execute.

[monit file for director job](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/monit#L9) has a "director.workers" property that changes the worker process count.

This is not whitelisted in the [spec file](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/spec).

**Comment by dpb587-pivotal** [comment]
Related story: [#114189259](https://www.pivotaltracker.com/story/show/114189259)

**Comment by dpb587-pivotal** [comment]
Released in v255.4
