### ISSUE TITLE
bosh agent should report locked read-only FS

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#1136]
Hello,
recently met a major outage on one of our internal QA Iaas.
A network storage failure switched all of our VMs persistent disk filesystem readonly. bosh ping didnt report any issue, bosh vms / instances were ok, from Bosh point of vue .
It was a tedious work of troubleshooting before we realized the FS had switched RO.

Could this type of check be included in bosh agent vitals control ? I know its quite specific, but when these occurs, it defeats all purpose of bosh health management and resurector features

**Comment by cppforlife** [comment]
@poblin-orange yup agreed. we had a problem with this too.

**Comment by mfine30** [comment]
https://www.pivotaltracker.com/story/show/131320561

**Comment by svrc-pivotal** [comment]
We run into this one a lot with flakey storage array networking.  Requires a reboot of all VMs affected (often an entire AZ); ideally BOSH shuts down or reboots any RO vm's as all our failure healing abilities center around stop failures.

**Comment by poblin-orange** [comment]
Again bitten by the same issue. Shame we didnt address it since 2016 ...
We will compensate with a  cron bosh release, testing the disk rw, and rebooting for this emergency case

**Comment by gberche-orange** [comment]
@mgadiya Any chance this issue be considered as part of the bosh-agent backlog ? See related slack exchange at https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1564595480038500 ?
