### ISSUE TITLE
Need better error message, rather than: "undefined method `[]' for false:FalseClass"

### ISSUE THREAD

**Issue by SamuelMarks** [cloudfoundry/bosh#1139]
Not a new issue at all: https://github.com/cloudfoundry/bosh/issues/669

Here they propose some `monit summary` way of figuring out the issue:
https://botbot.me/freenode/bosh/2014-10-05/?msg=22913985&page=1

Where do I actually run `monit summary` (with bosh-lite)? This new bosh release hasn't been deployed, and `vagrant ssh` on its own doesn't have monit. Do I trick *it* to giving remote monit access? - On that not, what is *it*?

PS: Danny Berger (@dberger) on Slack suggested I post here.

**Comment by cppforlife** [comment]
Filed as story: https://www.pivotaltracker.com/story/show/114891805

**Comment by dpb587-pivotal** [comment]
Fixed in bosh/v255.4.
