### ISSUE TITLE
CF205 error filling in template for nfs/0

### ISSUE THREAD

**Issue by sdheepa** [cloudfoundry/bosh#1143]
I am deploying cf205 (manifest attached) with bosh-stemcell-3169-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz

Director task 16
  Started preparing deployment > Preparing deployment. Done (00:00:02)
Started preparing package compilation > Finding packages to compile. Done (00:00:01)
Error 100: Error filling in template `syslog_forwarder.conf.erb' for `nfs/0' (line 44: undefined method `strip' for nil:NilClass)

In googling I read that this could be a problem with nfs getting an IP. The problem is that this deployment works with bosh-stemcell-3008-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz. I changed the stemcell to a later version (to get security updates) but using the same manifest.yml to deploy cf. Any suggestions on how to proceed further will be much appreciated!
[cf-vmsdev1control.yml.txt](https://github.com/cloudfoundry/bosh/files/144033/cf-vmsdev1control.yml.txt)

**Comment by dpb587-pivotal** [comment]
Looks like the error comes from [this file](https://github.com/cloudfoundry/loggregator/blob/6ba377d828bb3119dec541666bb3779c8b476bb8/bosh/jobs/metron_agent/templates/syslog_forwarder.conf.erb#L44).

There may be a few more people on the [#general](http://slack.cloudfoundry.org/) slack channel who have run into this CF issue before.

**Comment by cppforlife** [comment]
@sdheepa This seems to be cf-release specific issue. I would recommend filing this against cf-release repo.
