### ISSUE TITLE
Please choose the bosh deployment

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/bosh#1144]
Hi Am working on bosh deployment deletion script

I follow following step

```
bosh -u $BOSH_USERNAME -p $COMMON_PASSWORD target $BOSH_PRIVATE_IP

bosh login $BOSH_USERNAME $COMMON_PASSWORD

bosh -n delete deployment cf-$SUBDOMAIN --force
```

Upto this point it works fine
 `cd /opt/myexample/installer/tenant-$SUBDOMAIN/deployments`
# This folder contain micro01/bosh_micro_deploy.log

micro01/micro_bosh.rb
micro01/micro_bosh.yml

```
    `bosh -n micro delete`
```

Please choose the deployment

I get this error randomly.some time i get this error other time it works like a charm.
For work around I delete bosh director using nova command
`Nova delete bosh_director id`

Is this correct to delete like this ?
Am I missing something here.What is the correct way to delete bosh deployment ?

**Comment by cppforlife** [comment]
You should switch to using bosh-init (http://bosh.io/docs/install-bosh-init.html). bosh micro CLI is deprecated.
