### ISSUE TITLE
[redacted]

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/bosh#1148]
[redacted]

**Comment by jchesterpivotal** [comment]
Additionally, running reboot via AWS did not resolve our issue.

**Comment by jchesterpivotal** [comment]
Pretty much every google search points to doing a cloudcheck, which was my first port of call.

The `cck` fails on what appears, at face value, to be an AWS authentication failure:

```
Failed: Received unknown error from cpi: Unknown with message AWS was not able to validate the provided access credentials (00:00:19)

Error 100: Received unknown error from cpi: Unknown with message AWS was not able to validate the provided access credentials
```

Which is mysterious, since we haven't changed our credentials to my knowledge.

**Comment by dpb587-pivotal** [comment]
Double check that your director's AWS API credentials are still valid, and double check that the date/time on the director VM has not drifted and is correct.

**Comment by jchesterpivotal** [comment]
How do I check the time on the director VM? I skimmed the docs and didn't see an obvious option.

**Comment by jchesterpivotal** [comment]
Wait, I know this: SSH with AWS credentials. Which thickens the plot, because it fails on a changed remote host id.

**Comment by jchesterpivotal** [comment]
@dpb587-pivotal I am now suspecting a compromise, can you please remove this issue ASAP.

**Comment by jchesterpivotal** [comment]
oh github, you so terrible
