### ISSUE TITLE
Uninitialized constant Aws::S3::Errors while deleting a deployment when using S3 Blobstore

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1149]
I have S3 blobstore setup in bosh. 

Everything OK, but when deleting deployment I got this error:

```
E, [2016-02-25 16:21:25 #9144] [] ERROR -- DirectorJobRunner: Worker thread raised exception: uninitialized constant Aws::S3::Errors - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3192.
0/lib/blobstore_client/s3_blobstore_client.rb:103:in `rescue in delete_object'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3192.0/lib/blobstore_client/s3_blobstore_client.rb:94:in `delete_object'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3192.0/lib/blobstore_client/base.rb:69:in `delete'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/rendered_job_templates_cleaner.rb:24:in `block in clean_all'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/rendered_job_templates_cleaner.rb:22:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/rendered_job_templates_cleaner.rb:22:in `clean_all'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/instance_deleter.rb:37:in `block (2 levels) in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/error_ignorer.rb:9:in `with_force_check'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/instance_deleter.rb:36:in `block in delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/instance_deleter.rb:19:in `delete_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3192.0/lib/bosh/director/instance_deleter.rb:55:in `block (3 levels) in delete_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3192.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3192.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3192.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3192.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

It seems like  a bug in the code, like it cannot find the Module.

Changing  `/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/blobstore_client-1.3192.0/lib/blobstore_client/s3_blobstore_client.rb` with `Exception` instead of `Aws::Errors` and works.

**Comment by keymon** [comment]
Personally I do not understand why it fails.  The module is defined in `aws-sdk-resources`:

``` 
$ GEM_HOME=/var/vcap/packages/director/gem_home/ruby/2.1.0/ /var/vcap/packages/ruby/bin/ruby -raws-sdk-resources -e 'puts Aws::S3::Errors.class'
Module
```

**Comment by cppforlife** [comment]
I wonder if this is some kind of cross thread class loading issue. Is this something you are seeing consistently?

**Comment by timmow** [comment]
@cppforlife This doesn't appear to be consistent, some of the tasks will fail with this error, but on re running the delete deployment command they will be able to delete the instance.

**Comment by alext** [comment]
To add to this, I'm seeing quite strange behaviour when deleting a deployment. I've seen 3 different errors on repeated runs as follows:

1st run: `Failed deleting instances > example_z1/0 (3483c6de-e5a2-4372-bdf2-b6f97e8b385d): uninitialized constant Aws::S3::Errors`

2nd run: `Failed deleting instances > example_z1/0 (3483c6de-e5a2-4372-bdf2-b6f97e8b385d): wrong number of arguments (1 for 0)`

3rd run: `Failed deleting instances > example_z1/0 (3483c6de-e5a2-4372-bdf2-b6f97e8b385d): PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "rendered_templates_archives_instance_id_fkey" on table "rendered_templates_archives"
DETAIL:  Key (id)=(116) is still referenced from table "rendered_templates_archives".`

Continuing to run it resulted in the number of errors gradually reducing until it succeeded.

**Comment by ljfranklin** [comment]
In the AWS CPI we have a bit of code that seems like it was intended to fix a similar issue:

https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/77f493fd1723e0403e57e55f7e41132ad2a65d3d/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L61-L63
```
# AWS Ruby SDK is threadsafe but Ruby autoload isn't,
# so we need to trigger eager autoload while constructing CPI
AWS.eager_autoload!
```

Might be worth a try to drop that line into the blobstore client and see if the issue persists.

**Comment by cppforlife** [comment]
We have resolved this issue in recent bosh releases by switching Director to use s3cli and davcli binaries that are used by the Agent as well (to maintain nice consistency).
