### ISSUE TITLE
Need a way to run long migrations

### ISSUE THREAD

**Issue by mbhave** [cloudfoundry/bosh#1151]
Currently, there is no bosh lifecycle phase where we can perform migrations. Since there isn't a good way to change default monit timeout, we cannot wait for migrations to finish as part of our startup script.

**Comment by mariash** [comment]
Hi @mbhave, sounds like pre-start script is what you want https://bosh.io/docs/pre-start.html

**Comment by tylerschultz** [comment]
Tips:

Please note that pre-start scripts will not time out, so the deploy will not proceed onto further steps if the pre-start script never exits.

If you are running more than 1 instance of your job, you may not want all instances attempting to migrate your database. You can work around this by only migrating on the instances where `spec.bootstrap==true`. The instance that is bootstrap will always start first. It is best not to depend on index==0. With the introduction of azs in bosh, there may be a case where there is no instance at index 0. 

If it is important that no other instance in the instance group start before the pre-start script finishes, it may be helpful to take advantage of the update section of your manifest.

**Comment by mbhave** [comment]
@mariash @tylerschultz I spoke to @cppforlife and he said pre-start is not meant for this purpose because it does not handle job dependencies. So, if the postgres job wasn't up yet UAA migrations would fail.

**Comment by cppforlife** [comment]
what @mbhave said. still looking into possible solutions...
