### ISSUE TITLE
BOSH overwrites old release before calling monit stop

### ISSUE THREAD

**Issue by christianang** [cloudfoundry/bosh#1154]
It looks like BOSH is sometimes improperly overwriting old release scripts before **monit stop** is called. We noticed this because one of our stop scripts logic changed between releases to account for a package directory change and it failed to stop the old process. We have reproduced this issue using a minimal BOSH deployment.

**Reproduction steps:**

Download the following: [bosh-issue.zip](https://github.com/cloudfoundry/bosh/files/152039/bosh-issue.zip)

The zip contains two release tarballs, two manifests, and a helper script.
_Note: The only difference between the two releases is a test_ctl script in the job which echoes its version during monit start and stop to /var/vcap/sys/logs/test/test.log._

Target a bosh lite director and change the uuid in the manifest to match the director.

Run

```
./deployme 5
```

This script will deploy our two releases 5 times and echo our job’s log file, which contains a record of when the start and stop scripts are called.

We expect to see the start and stop script called back to back for each release:

```
v1 start
v1 stop
________
v2 start
v2 stop
________
v1 start
v1 stop
... 
```

However while running this script we will occasionally see that the wrong stop script gets called:

```
________
v1 start
v2 stop
________

```

or

```
________
v2 start
v1 stop
________

```

Let us know if you need anything else.

@cloudfoundry-incubator/cf-infrastructure

**Comment by cppforlife** [comment]
Waiting for cf-release to switch over to webdav server before rolling this out.

**Comment by bodymindarts** [comment]
@cppforlife why is having cf-release use webdav server a blocker for this?

**Comment by drnic** [comment]
Can this be rolled out now?

**Comment by dpb587-pivotal** [comment]
I believe this is covered by [Story 117716387](https://www.pivotaltracker.com/story/show/117716387) which is sitting on develop for our next release.

**Comment by drnic** [comment]
Sweet.

**Comment by drnic** [comment]
@dpb587-pivotal to confirm what I see - the work was merged onto `develop` on July 1; but isn't yet shipped? Or what does the last comment on the tracker ticket mean?

**Comment by cppforlife** [comment]
bosh-release v258+ in combination with stemcells 33xx+ should will now wait for `monit stop` to finish before continuing onto a next step.
