### ISSUE TITLE
Need to upgrade glibc in Base OS for Ubuntu.

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1156]
We got 2 vulnerability issues about glibc:

https://exchange.xforce.ibmcloud.com/vulnerabilities/110675
https://exchange.xforce.ibmcloud.com/vulnerabilities/110711

According to the report, there needs to upgrade glibc, the current version is glibc-2.19-1 in the stemcell.
```
Remedy
Upgrade to the latest version of glibc (2.23 or later), available from the GNU Web site. See References.
```

**Comment by cppforlife** [comment]
I dont know which stemcell you are running on but we are using latest available package: http://packages.ubuntu.com/trusty-updates/libc-bin
