### ISSUE TITLE
Provide sha1 hashes for stemcells

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1157]
On http://bosh.io/stemcells/bosh-aws-xen-ubuntu-trusty-go_agent, you only provide md5 hashes. But bosh init wants sha1:
```
Command 'deploy' failed:
  Validating deployment manifest:
    resource_pools[0].stemcell.sha1 must be provided for http URL
```
You already provide sha1 hashes for releases, I think you should provide them for stemcells as well.

Or at least write release notes for stemcells and include sha1 hash there. Now I have to download the stemcell manually, check that md5 matches, then compute sha1 and use that in my manifest...

**Comment by voelzmo** [comment]
See https://github.com/cloudfoundry/bosh-init/issues/41 feel free to chime in there.
