### ISSUE TITLE
Ability to turn off redact diff

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#1158]
It looks like redact diff is build into director and doesn't seem to work on cli

**Comment by cppforlife** [comment]
@longnguyen11288 yup. currently there is no way to show redacted values from the manifest. im assuming you want that feature?

**Comment by longnguyen11288** [comment]
yeah it would be nice just to make sure what we're changing is what we want.

**Comment by voelzmo** [comment]
+1 seems helpful. The diff on the Director side is now done only after authentication, so anybody who gets a diff also can do `bosh download manifest`. Therefore, this is no additional security measure, but only helpful for CIs where the logs are publicly visible. 

You could even argue that the default should be redact-diff turned off, but I'll leave you to that.

**Comment by dpb587** [comment]
Personally, I agree as well - was surprised it was happening on the director and always redacting. For at least some manual deployments it would be nice if I could verify the diff - especially when interpolation/variables are involved in the manifest and I want to make sure they are being included as intended.

**Comment by geofffranks** [comment]
:+1:

**Comment by amhuber** [comment]
Definitely agreed.  When doing manual deployments we use the diff as a final "make sure I didn't screw anything up" check and expect the diff to be there by default. Having the option to turn it off is fine for folks that need it, as it was before.

**Comment by cppforlife** [comment]
Sounds like it's worth introducing an option to show redacted values e.g. bosh deploy --show-redacted or something like that.

**Comment by geofffranks** [comment]
Would is be possible to make the redacting behavior configurable via .bosh_config as well?

**Comment by voelzmo** [comment]
@cppforlife why not having the default vice versa? Typing is annoying for humans, but easy for machines. So if you don't want properties to be on your CI, add `--redact-properties` to the deployment statement?

**Comment by dpb587** [comment]
+1 for the `--redact-properties` approach

**Comment by fj** [comment]
+1 for `--redact-properties`, but possibly allow a comma-separated-list?

e.g.:

* `--redact-properties`: redact everything
* `--redact-matching-properties=S1,S2,...`: redact properties containing any of the substrings S1, S2, ... (I may want to redact `SECRET_API_PASSWORD` but not `PUBLIC_SERVICE_NAME`

**Comment by cppforlife** [comment]
@voelzmo i would like to be more paranoid by default (hide potentially sensitive info).

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/114912611

**Comment by cppforlife** [comment]
As part of [v255.4](https://github.com/cloudfoundry/bosh/releases/tag/stable-3213) we added `--no-redact`.

**Comment by Rylon** [comment]
Hi @cppforlife do you know if this `--no-redact` option can be made default, for example by setting something in the BOSH config yml?

**Comment by dpb587-pivotal** [comment]
@Rylon, originally nothing was redacted and, for improved default security, we started redacting all properties. We want to retain the more secure, default behavior, so we're not planning on making it default again in the future, even through bosh config settings (since that would result in differing behavior between environments, which negates some of the "expect secure defaults" approach).

**Comment by Rylon** [comment]
Hi @dpb587-pivotal thanks for your response. I understand and agree with the motivation behind making it "secure by default", but in this case I'm asking for a way for users to opt-out, by explicitly adding the option to the config file.

This seems like it would still satisfy the "expect secure defaults" approach, but still give people the option to disable it if they have valid reasons, best of both worlds? :)
