### ISSUE TITLE
USN-2914-1: OpenSSL vulnerabilities

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#1160]
Is this slated to be fixed in next stemcell? http://www.ubuntu.com/usn/usn-2914-1/

**Comment by longnguyen11288** [comment]
Also what is the criteria for a CVE being added to stemcell? (for my own education)

**Comment by cppforlife** [comment]
We follow Ubuntu's severity recommendations. If there is a USN with high severity or above we immediately issue a hotfix release, otherwsie bumps to OS packages happen in subsequent builds.

**Comment by longnguyen11288** [comment]
Ok thanks! 


On March 3, 2016 at 12:43:24 PM, Dmitriy Kalinin (notifications@github.com) wrote:

We follow Ubuntu's severity recommendations. If there is a USN with high severity or above we immediately issue a hotfix release, otherwsie bumps to OS packages happen in subsequent builds.
