### ISSUE TITLE
Manifest diff should be readable by the color-blind

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1161]
A diff like this

<img width="325" alt="screen shot 2016-03-04 at 15 48 36" src="https://cloud.githubusercontent.com/assets/2256887/13530232/a6f1c396-e220-11e5-97a0-dcc4a4b598a4.png">

means to some colleagues the same as 

![fuck-the-color-blind-t-shirt](https://cloud.githubusercontent.com/assets/2256887/13530113/0fd9c68e-e220-11e5-9abe-b10006daaf7f.jpg)

So let's be nice to them and add some nice diff markers like other diff tools use, e.g. plus or minus signs or such.

**Comment by mariash** [comment]
you can run it with --no-color and bosh will add +/-

**Comment by voelzmo** [comment]
Ah awesome, thanks!
