### ISSUE TITLE
Wishlist: Start and stop timestamps

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry/bosh#1165]
As an operator
I want both a start and stop timestamp in `bosh tasks recent` output
So that I can search for events that correlate to something that happened at a certain time.

**Comment by pronoiac** [comment]
@jim80net

**Comment by cppforlife** [comment]
Makes sense.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/115793569

**Comment by dpb587-pivotal** [comment]
Closing - fixed as of [v256](https://github.com/cloudfoundry/bosh/releases/tag/stable-3232).
