### ISSUE TITLE
Shelling out to 'file' without checking the exit status

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/bosh#1176]
In upload_release.rb, there are two cases where BOSH executes the 'file' utility to determine the type of a file:

https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/commands/release/upload_release.rb#L32

https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/commands/release/upload_release.rb#L70

The output is used, but the exit status is not checked, so if the execution fails, it does so silently. We recently had this happen to us when we ran BOSH in a Concourse container in which file was not installed; BOSH carried on, and failed somewhere else with a cryptic error message, which took a while to debug.

Could we check the exit status of these executions? Could we also check that the 'file' utility is available on the path? We would be happy to submit a PR with these changes if so.

Cheers,
@tinygrasshopper and @tomwhoiscontrary in :guardsman:

**Comment by dpb587-pivotal** [comment]
Closing - we're not planning further enhancements or fixes to the CLI in favor of the upcoming [bosh-cli](https://github.com/cloudfoundry/bosh-cli). Feel free to give the beta a try if you're interested - it's much better at propagating failures.
