### ISSUE TITLE
Consistent Failed creating missing vms errors due to timeouts

### ISSUE THREAD

**Issue by valenbb** [cloudfoundry/bosh#1178]
I am currently attempting to deploy cloud foundry on vsphere but am consistently getting "Failed creating missing vms" error:

```
Done creating missing vms > nats_z1/0 (0bfa1112-1889-409e-953d-22f77841c8c0) (00:01:12)
     Done creating missing vms > loggregator_trafficcontroller_z1/0 (a334b950-74e9-4afb-8834-4c0e362d392a) (00:01:12)
     Done creating missing vms > doppler_z1/0 (038dd5f6-f324-4bbd-aad4-8ff653ed20a8) (00:01:12)
     Done creating missing vms > consul_z1/1 (f1c4d773-55ff-420d-b3ef-ecd563ec5ecf) (00:01:13)
     Done creating missing vms > ha_proxy_z1/0 (0fb51afc-060e-4fa6-9f70-ec52ff02fda2) (00:01:13)
     Done creating missing vms > runner_z2/0 (7104eb67-bd05-46c6-b8a5-e7a6da65adc8) (00:01:14)
     Done creating missing vms > postgres_z1/0 (3ad4c0fd-6915-4ec8-aab0-6506e8cef149) (00:01:16)
     Done creating missing vms > etcd_z1/0 (5db42112-7516-48cf-baf4-2ac6e3d702d6) (00:01:16)
     Done creating missing vms > uaa_z1/0 (ae33c541-a1b2-4ab0-86fe-ea09b4dcfe15) (00:01:18)
     Done creating missing vms > uaa_z2/0 (b1b9f90c-458e-4f6f-83b3-4b429753d8ba) (00:01:20)
     Done creating missing vms > clock_global/0 (099c405a-5521-427f-ba8e-df8ae4618e34) (00:01:19)
     Done creating missing vms > loggregator_trafficcontroller_z2/0 (f6b9ca52-010c-49df-8a4d-06a90c231442) (00:01:19)
     Done creating missing vms > runner_z1/0 (e038f65b-27ef-47e5-a5ba-818f7619a89f) (00:01:22)
   Failed creating missing vms > consul_z2/0 (7d7e0158-fb6a-4efe-9b91-81863f771a43): Timed out sending `apply' to 0f0f05ad-10f2-4ee4-96cd-60f1bbf4b584 after 45 seconds (00:01:58)
     Done creating missing vms > etcd_z1/1 (7f7c3823-2f7b-4281-a495-d84fbda1ac9a) (00:02:02)
     Done creating missing vms > etcd_z2/0 (ed7580c4-e9d3-4ba6-97ad-c538714dd529) (00:02:21)
   Failed creating missing vms > consul_z1/0 (6f7b939b-aaab-4a57-80a1-9a6ad8f1961e): Action Failed get_task: Task with id e00a7878-0cfb-484c-6dfa-e0abe1d1f26f could not be found (00:02:46)
   Failed creating missing vms > hm9000_z1/0 (4632b5e7-265e-40fa-8952-d875284d045e): Action Failed get_task: Task with id e66ccdc8-5a27-4767-69b5-8cce4210ca59 could not be found (00:02:50)
   Failed creating missing vms > nats_z2/0 (ea125979-6853-43ff-9703-0b46d0ca1cac): Action Failed get_task: Task with id 923a8d23-3a77-41e9-6c2e-d1e7b1fb64f1 could not be found (00:02:55)
   Failed creating missing vms > blobstore_z1/0 (3e43f0da-ca0e-42a5-8f6b-1f81b085b6f0): Action Failed get_task: Task with id 0ff5f6d7-548a-413d-57e6-a5bd367a02af could not be found (00:02:56)
   Failed creating missing vms > api_z2/0 (fd67b795-9c4d-4b83-91a9-97b054ec88ca): Timed out sending `get_task' to bb194aa2-7cda-4649-b0e1-e4cdb6921e22 after 45 seconds (00:03:31)
   Failed creating missing vms > doppler_z2/0 (5204e488-93a1-4cf6-80a5-af2fe26d0ef2): Timed out sending `get_task' to 9a8e8822-6ae0-48ae-a02d-4fc209826c2f after 45 seconds (00:03:34)
   Failed creating missing vms > hm9000_z2/0 (6509d79e-c146-4d06-b9f5-ece28e0ec865): Timed out sending `get_task' to 36bc1689-e727-4736-af35-7a62327329ad after 45 seconds (00:03:38)
   Failed creating missing vms > router_z1/0 (5b3cdf17-cd8e-4807-9072-c19835f2aa8b): Timed out sending `get_task' to 3c66dc1f-c834-4af8-9a99-cb12689e8f0c after 45 seconds (00:03:39)
   Failed creating missing vms > stats_z1/0 (9f67a030-9826-4c9e-9f30-3a9c7a28e82c): Timed out sending `get_task' to 68f8dd99-5e0c-4f88-b647-3b16ae06b274 after 45 seconds (00:03:40)
   Failed creating missing vms > router_z2/0 (978770fb-fd18-49bc-b5cc-19bec8535e05): Timed out sending `get_task' to c912d46d-622c-4bae-8243-7e601e3796ce after 45 seconds (00:03:43)
   Failed creating missing vms > api_worker_z1/0 (1e64b6f7-3310-442a-88f9-3259633ce1c7): Action Failed get_task: Task with id e87e205e-7cd6-4ce1-5643-f80d28b49de8 could not be found (00:04:00)
   Failed creating missing vms > api_z1/0 (c07ab2da-2332-4d2a-8885-60fedb6e908a): Action Failed get_task: Task with id 827665bf-cf3f-4e0b-67ea-790c0cb3a68f could not be found (00:04:07)
     Done creating missing vms > api_worker_z2/0 (c6e681c0-7f8a-4bd9-b7cf-c887881abdff) (00:05:54)
   Failed creating missing vms (00:05:55)

Error 450002: Timed out sending `apply' to 0f0f05ad-10f2-4ee4-96cd-60f1bbf4b584 after 45 seconds

Task 818 error
```

For a more detailed error report, run: bosh task 818 --debug
I've output the content to a log and can be obtained from here: https://drive.google.com/file/d/0By5IxI5JnQTWVUdnejQwdlo3MmM/view?usp=sharing

From the above, some VMs are successfully created and I can ssh into them. Those that failed and not created. 

All hosts have enough vCPU, RAM and the datastore has enough capacity.

I am not sure on how to proceed in terms from a vsphere perspective why this is failing consistently. 
At one point in time, 22 vms are created successfully then another time only 20.

I have applied 3 vsphere resource pools and the vms are correctly placed in them as expected.

Bosh cck works only for vms created; after the failure I run bosh deploy again but it still fails. Recreate fails due to IP conflicts being detected.

CF manifest: https://drive.google.com/file/d/0By5IxI5JnQTWQ1pRa25uYkhKN2s/view?usp=sharing
passwords and keys have been replaced.

Versions used are from latest release a few days ago.
I appreciate any advice offered.

**Comment by cppforlife** [comment]
Either this is a networking problem, duplicate IPs in use, or an agent issue. I would check:
- does `bosh vms` keep on returning all as `running` several times?
- do you have IPs associated with these VMs used by something else?
- log into one of the agents and see if there are error in the agent log

> Recreate fails due to IP conflicts being detected.

Do you mean "Cannot create new VM because of IP conflicts with other VMs on the same" error? If so this does mean that you have multiple VMs using the same IPs. You'll have to delete those VMs to avoid IP conflicts.

**Comment by valenbb** [comment]
I will double check for IP conflicts, but if it was/is, bosh would report it. Per item #1, running bosh vms does report unresponsive agents for a few vms that were successfully created. So I will login to one of these vms and check the agent log for reported issues. 

Recreate fails due to IP conflicts being detected. -- I believe this is due to bosh trying to recreate vms that were successfully created from the first deployment (command ran was bosh deploy --recreate).

Thanks for the suggestions and I will continue investigating further and update along the way.

**Comment by valenbb** [comment]
Just a quick update:
I update the static IP block in the deployment manifest to use a range that have no servers associated to any IPs in the range I specified. However, the timeouts are still occurring, so from this I gather that IP conflict is not the cause. 

Is there a way to slow the deployment just in case network traffic is causing this? 

I have not had time to look into one of the vms that have an unresponsive agent status, but will look into this later.

**Comment by valenbb** [comment]
@cppforlife, Thanks again. I setup a new static IP range but it still failed with a timeout for 5 servers. Reran bosh deploy again and this time it reported IP conflicts; i did see some of the dynamic IPs bosh is trying to use was attached to servers in DNS. So I added a new reserved IP range and reran the deployment; this succeeded. I am now able to proceed to the updating process.

Closing ticket.

**Comment by deepakdefender264** [comment]
Hi @valenbb 
We are getting the similar issue on deploying cloud foundry on vSphere environment but its getting failed on bosh deploy.
Below is the error and deployment file we have created. Is the error similar to your deployment ?

![error](https://cloud.githubusercontent.com/assets/22387902/25665311/da3c7c1e-303a-11e7-8bd4-99a627da086b.jpg)

[cf-stub.txt](https://github.com/cloudfoundry/bosh/files/973628/cf-stub.txt)
[bosh.txt](https://github.com/cloudfoundry/bosh/files/973627/bosh.txt)
[cf-deployment.txt](https://github.com/cloudfoundry/bosh/files/973629/cf-deployment.txt)

**Comment by dpb587-pivotal** [comment]
@deepakdefender264, your screenshot is showing a different error than this issue. I'd recommend giving the suggestions from http://bosh.io/docs/tips#unreachable-agent a try. If you need further help, please make a new issue.

**Comment by valenbb** [comment]
Agreed with @dpb587-pivotal. It sounds like your agent is not responding. Give his suggestion a try.

**Comment by deepakdefender264** [comment]
Thanks @dpb587 and @valenbb we will raise a new issue.
