### ISSUE TITLE
Micro bosh deploy cloud foundry dependency issue

### ISSUE THREAD

**Issue by leontp587** [cloudfoundry/bosh#1186]
I've followed the "minimal AWS deployment" guide here https://github.com/cloudfoundry/cf-release/tree/master/example_manifests to try CloudFoundry.

I understand that I have to install the bosh_cli_plugin_micro, but when I run this on an AWS Ubuntu 14.04 VM:

`gem install bosh_cli_plugin_micro`

I get:

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: blobstore_client requires aws-sdk-resources (= 2.2.0); aws-sdk requires aws-sdk-v1 (= 1.60.2)
```
Installing the AWS ruby sdk doesn't solve the problem. I suspect it's a problem of the aws sdk being a newer version than the one the micro bosh cli expects. Any suggestions?

**Comment by allomov** [comment]
`bosh_cli_plugin_micro` is outdated way to install BOSH to your IaaS.

Possibly the best way to start with CF will be using [bosh-lite](https://github.com/cloudfoundry/bosh-lite). It will create a VM on your localhost (or AWS) with BOSH, after that you'll be [able to deploy CF easily](https://github.com/cloudfoundry/bosh-lite#deploy-cloud-foundry) within this VM.

**Comment by allomov** [comment]
You should follow [this docs](https://bosh.io/docs/init.html) to deploy BOSH to IaaS of your choice.
