### ISSUE TITLE
Mobile BOSH for Android.

### ISSUE THREAD

**Issue by tedsuo** [cloudfoundry/bosh#1191]
Currently Mobile BOSH only works for iOS. What are the plans for an android edition?

http://mobilebosh.cfapps.io/

**Comment by drnic** [comment]
Hehe funny stuff

Sent from Outlook Mobile




On Fri, Apr 1, 2016 at 11:10 AM -0700, "Dmitriy Kalinin" <notifications@github.com> wrote:












Closed #1191.
