### ISSUE TITLE
'bosh upload blobs' returns confusing error if private.yml is missing

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1194]
Running `bosh upload blobs` when `final.yml` specifies an S3 bucket but `private.yml` is missing returns the following error:

```
$ bosh upload blobs
Total: 7, 17.8M

You have some blobs that need to be uploaded:
new vsphere_cpi_ruby/bundler-1.11.2.gem 257.0K
new vsphere_cpi_ruby/ruby-2.2.4.tar.gz  15.9M
new vsphere_cpi_ruby/rubygems-2.6.2.tgz 467.4K

When ready please run `bosh upload blobs'

Upload blob vsphere_cpi_ruby/bundler-1.11.2.gem? (type 'yes' to continue): yes
vsphere_cpi_ruby/bundler-1.11.2.gem uploading...
/Users/cpiuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/blobstore_client-1.3184.1.0/lib/blobstore_client/s3_blobstore_client.rb:62:in `create_file': unsupported action (Bosh::Blobstore::BlobstoreError)
```

It would be nice if the error message told the user to create a `private.yml` file containing the blobstore credentials.

**Comment by keymon** [comment]
Actually, if you are using environment variables to pass the credentials (#941), or IAM profiles (#1402) the file content has to be empty:

```
---
blobstore:
  s3:
    access_key_id: ''
    secret_access_key: ''
```

Which is a little bit silly. It should simply not require it in that case.

**Comment by tjvman** [comment]
Closing, ruby CLI is no longer receiving updates.
