### ISSUE TITLE
Ruby appears outdated (2.1.7 < 2.1.9)

### ISSUE THREAD

**Issue by jaustinhughey** [cloudfoundry/bosh#1202]
In going through some docs/tutorials and poking around on my own today, I noticed that bosh appears to be using an outdated version of ruby (specifically `ruby-2.1.7`) which may have security impact later on down the line.

As of this writing, `ruby-2.1.9` appears to be the latest 2.1 release available. Additionally, as mentioned [here](https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/), the only 2.1 updates to be released from here on will be maintenance/security releases; it may be worth considering an upgrade to 2.3.

Step one here is flagging this as an issue, and then if I have time to do so - and with guidance from the community (because I'm a noob when it comes to this project, not gonna lie) - I'll see what I can do about updating ruby within this project to use 2.1.9.

So far I see the following places where we may need to make updates; problem is, I don't personally know how all these pieces fit together and what other areas I may have missed. Hoping someone more familiar with the project can comment here:
- https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/ci/docker/install-bundler.sh#L6
- https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/ci/docker/install-ruby.sh#L6 (additionally, is `0.5.0` the current "best" version of ruby install to use here? Same with chruby?)
- https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/ci/pipelines/os-image/docker/install-ruby.sh#L6
- https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/release/packages/ruby/spec#L5

Of course, updating Ruby here may also necessitate updating various libs, Rubygems, and possibly other things I'm just not thinking of right now. Comments from the community would be appreciated here, and by all means, if some one more experienced wants to take this and run with it, go right ahead! No ego to bruise, here. :)

**Comment by cppforlife** [comment]
yup. should bump. story: https://www.pivotaltracker.com/story/show/117398595

**Comment by dpb587-pivotal** [comment]
As of director [v257](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262), ruby 2.3.1 is used.
