### ISSUE TITLE
Is there a way to change deployment name without recreating VMs

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/bosh#1210]
Hello, all

I am having several deployments now, and for better management, we may need to change deployment names to follow a rule defined recently.

But it looks bosh take the deployment name as the unique key.
If I changed the deployment name, then it's a new deployment, which means I cannot update the name of an existed deployment.

Maybe it's a rare case, but why don't we use a unique key like UUID to identify a deployment, but not a deployment name?

**Comment by cppforlife** [comment]
@StanleyShen as you find out there is currently no way to rename a deployment. IDs dont necessarily make UX nicer. previously it was briefly mentioned that it may makes sense to add a command/config for renaming of deployments.

if you want to hacky way of doing it, you should be able to rename a deployment via DB. See http://bosh.io/docs/tips.html#director-db for how to access DB via Ruby. You should be able to run `Bosh::Director::Models::Deployments.where(name: "old").update(name: "new")` (check on a test deployment).

**Comment by StanleyShen** [comment]
Thanks for information, and close it then since we had a way to do that.

**Comment by jagadish-kb** [comment]
@StanleyShen @cppforlife 
I tried the above and renaming breaks resurrection. Bosh resurrection no longer works if we rename the deployment with the above approach. I renamed one of the deployment from `service-fabrik-backup-2107-4a6e7c34-d97c-4fc0-95e6-7a3bc8030ba4` to `service-fabrik-backup-4a6e7c34-d97c-4fc0-95e6-7a3bc8030ba4`. Manually deleted the VM from the horizon console & wanted resurrector to fix the deployment. I was waiting to see if there would be a `scan & fix` event in bosh tasks. I waited for long and didn't see any. Then i took a peek at health monitor log and below is what i found:

```
[2017-12-29T11:30:17.762089 #7277]  INFO : [ALERT] Alert @ 2017-12-29 11:30:17 UTC, severity 4: Notifying Director to recreate instance: 'blueprint/b4957a8c-c6ed-4bc1-a226-e2a0dd25ff09'; deployment: 'service-fabrik-backup-4a6e7c34-d97c-4fc0-95e6-7a3bc8030ba4'; 1 of 1 agents are unhealthy (100.0%)
[2017-12-29T11:30:17.762220 #7277]  INFO : (Event logger) notifying director about event: Alert @ 2017-12-29 11:30:17 UTC, severity 4: Notifying Director to recreate instance: 'blueprint/b4957a8c-c6ed-4bc1-a226-e2a0dd25ff09'; deployment: 'service-fabrik-backup-4a6e7c34-d97c-4fc0-95e6-7a3bc8030ba4'; 1 of 1 agents are unhealthy (100.0%)
[2017-12-29T11:30:17.762509 #7277]  WARN : (Resurrector) event did not have deployment, job and id: Alert @ 2017-12-29 11:30:17 UTC, severity 4: Notifying Director to recreate instance: 'blueprint/b4957a8c-c6ed-4bc1-a226-e2a0dd25ff09'; deployment: 'service-fabrik-backup-4a6e7c34-d97c-4fc0-95e6-7a3bc8030ba4'; 1 of 1 agents are unhealthy (100.0%)
```

So this is certainly a dangerous operation to perform and i guess even the above option should not be recommended. Is there any other work around to make even resurrection work post this renaming ?

**Comment by jagadish-kb** [comment]
@cppforlife - Bosh resurrection worked. What had happened was since I had deleted the VM manually from Openstack console, the neutron port was still present and bosh resurrection had failed as it reported that the IP was still in use. I manually deleted even the neutron port and resurrection was able to fix the deployment. 
So then is it safe to rename deployments? Are there any other tests/gotchas that i need to check before i can start doing this ? Would appreciate your recommendations here.

**Comment by cunnie** [comment]
### Updated Paths and Models 

- Path to get into the console has changed:
```
/var/vcap/jobs/director/bin/console
```

- Model `Deployments` is now `Deployment` (singular, not plural), e.g.

```
irb(main):007:0> Bosh::Director::Models::Deployment.map(:name)
=> ["cf", "concourse-nginx-ntp-pdns"]
=> ["cf", "concourse-nginx-ntp-pdns"]
irb(main):010:0> Bosh::Director::Models::Deployment.where(name: "concourse-nginx-ntp-pdns").update(name: "sslip.io")
=> 1
irb(main):011:0> Bosh::Director::Models::Deployment.map(:name)
=> ["cf", "sslip.io"]
```
