### ISSUE TITLE
syncing blobs in parallel sometimes results in hanging bosh task

### ISSUE THREAD

**Issue by utako** [cloudfoundry/bosh#1213]
It doesn't happen every time, but we have noticed that when running `bosh --parallel 10 sync blobs`, it hangs indefinitely and reports a percentage for downloading a blob that is well above 100%. 

We are running this on bosh-lite, on virtualbox version 9000.105.0 and bosh version 1.3215.3.0. 

![247percent](https://cloud.githubusercontent.com/assets/1895962/14502770/d7f48266-0161-11e6-9978-e986b5c92bf1.png)

Thanks.

**Comment by cppforlife** [comment]
sync blobs problems are resolved in the new [bosh cli](https://github.com/cloudfoundry/bosh-cli). it also defaults to 5 parallel workers.
