### ISSUE TITLE
Show deployment name in the create-deployment task description

### ISSUE THREAD

**Issue by avade** [cloudfoundry/bosh#1214]
It would be great when running `bosh tasks` if the task description could include the deployment name, or if this was in another field.

I would also like to see this available in the API.

**Comment by cppforlife** [comment]
We have added "deployment" field for each task. That should be authoritative source for which deployment tasks belong to.

**Comment by dpb587-pivotal** [comment]
A deployment field was added to tasks in director [v255.4](https://github.com/cloudfoundry/bosh/releases/tag/stable-3213).
