### ISSUE TITLE
Update ubuntu stemcell libpcre3

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry/bosh#1216]
There is a vulnerability in libpcre3_1:8.31-2ubuntu2.1 and it should be updated to libpcre3_1:8.31-2ubuntu2.2.

Whats the best way of doing that?

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/117646763 as requested.

**Comment by dpb587-pivotal** [comment]
Updated in stemcell 3215.4 - https://github.com/cloudfoundry/bosh/releases/tag/stable-3215.4
