### ISSUE TITLE
BOSH team admin cannot get task state after deployment deletion

### ISSUE THREAD

**Issue by mariantalla** [cloudfoundry/bosh#1225]
The issue occurs when a user is a team admin (not bosh admin or bosh director admin), they make a deployment and subsequently attempt to delete that deployment. The user cannot then successfully get task state relating to the deletion of their deployment.

We are using BOSH release 255.4.

To reproduce:
1. Create team admin user in UAA
   
   ```
   uaac client add $CLIENT_ID \
       --secret $CLIENT_SECRET \
       --authorized_grant_types "refresh_token password client_credentials" \
       --authorities bosh.teams.my-team.admin \
   ```
2. Deploy with that user
   
   ```
   BOSH_CLIENT=$CLIENT_ID BOSH_CLIENT_SECRET=$CLIENT_SECRET bosh deploy
   ```
3. Delete the deployment
   
   ```
   BOSH_CLIENT=$CLIENT_ID BOSH_CLIENT_SECRET=$CLIENT_SECRET bosh delete deployment $DEPLOYMENT_NAME
   ```

The last step does delete the deployment, but reports failure:

```
Acting as client 'kafka-on-demand-broker-dev1' on deployment 'kafka-on-demand-broker-dev1-team' on 'enablement-bosh-v2'

You are going to delete deployment `kafka-on-demand-broker-dev1-team'.

THIS IS A VERY DESTRUCTIVE OPERATION AND IT CANNOT BE UNDONE!

Are you sure? (type 'yes' to continue): yes

Director task 12969
  Started deleting instances > broker/0 (9d07caf6-e180-42b4-a379-3eccbf994be4)Error 600000: Require one of the scopes: bosh.admin, bosh.76f2d2b1-fc3f-47d2-bbfe-4109dc799337.admin
```

In addition, if we call the tasks API endpoint directly, we observe a change in the response when the task completes. This request:

```
curl -v --insecure --header "Authorization: Bearer $OAUTH_TOKEN" https://<redacted>:25555/tasks/12969
```

While the task is running, results in this response (edited for brevity):

```
< HTTP/1.1 200 OK
{"id":12969,"state":"processing","description":"delete deployment kafka-on-demand-broker-dev1-team","timestamp":1461083208,"result":null,"user":"kafka-on-demand-broker-dev1","deployment":"kafka-on-demand-broker-dev1-team"}
```

The same request immediately after the task has completed results in this response:

```
< HTTP/1.1 401 Unauthorized
{"code":600000,"description":"Require one of the scopes: bosh.admin, bosh.76f2d2b1-fc3f-47d2-bbfe-4109dc799337.admin"}
```

The OAuth token was obtained just before the deletion, and is valid for six hours, so this is not a result of token expiry.

Thanks,
@mariantalla and @tomwhoiscontrary

**Comment by cppforlife** [comment]
yup we've run into this bug. fix is via this story: https://www.pivotaltracker.com/story/show/117557245

will be in bosh v256.

**Comment by dpb587-pivotal** [comment]
Fixed in director [v256](https://github.com/cloudfoundry/bosh/releases/tag/stable-3232).
