### ISSUE TITLE
Tasks filtered by deleted deployment name not working

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/bosh#1229]
We encountered inconsistent behavior while working with the tasks api and filtering by the deployment name. For a deployment which was deleted, we get a 404 when we filter by the deployment name, but we do get the tasks for the deployment when we don't use the deployment name as a query parameter. 

For example,

``` bash
curl -H "Authorization: Bearer $TOKEN" https://52.16.223.196:25555/tasks?deployment=foo | jq
```

``` json
{
  "code": 70000,
  "description": "Deployment `foo doesnt exist"
}
```

but

``` bash
curl -H "Authorization: Bearer $TOKEN" https://52.16.223.196:25555/tasks | jq
```

``` json
[
{
    "id": 12193,
    "state": "done",
    "description": "delete deployment foo",
    "timestamp": 1460733498,
    "result": "/deployments/foo",
    "user": "bar",
    "deployment": "foo"
  }
]
```

**Comment by cppforlife** [comment]
As we are changing tasks to have direct association with teams, this problem will be resolved.

**Comment by dpb587-pivotal** [comment]
Fixed in director [v257](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262).
