### ISSUE TITLE
No `-d` flag for `bosh logs`

### ISSUE THREAD

**Issue by quintessence** [cloudfoundry/bosh#1230]
Can the `-d` flag be added so that we can use `bosh -d ${MANIFEST} logs` so we don't have to run `bosh deployment ${MANIFEST}` as a separate command? Similar to `bosh -d ${MANIFEST} deploy`.

**Comment by dpb587-pivotal** [comment]
Closing - Ruby CLI is feature frozen in favor of development on the upcoming go-based CLI. Feel free to [give it a try](https://github.com/cloudfoundry/bosh-cli) and provide feedback there. All commands in the go CLI respect a deployment flag.
