### ISSUE TITLE
make --git the default for bosh init release

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/bosh#1231]
Can the `--git` option to `bosh init release` be made the default? Probably not many users will create bosh releases without checking them into git.

If there is a need to skip git maybe a `--no-git` option?

**Comment by tjvman** [comment]
@mmb Ruby CLI is frozen and won't have new features added - if you'd like to have this feature in the [v2 Go CLI](https://github.com/cloudfoundry/bosh-cli), please feel free to open an issue there.

**Comment by cppforlife** [comment]
but we should make that a default for new cli. will do that.
