### ISSUE TITLE
Bosh accepts a deployment request when another deployment task is already running

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/bosh#1238]
To reproduce:
1. Ensure BOSH has at least two free workers
2. Start a deployment (set the shell variables as appropriate):
   
   ```
   curl -v -k -H 'Content-type: text/yaml' -H "Authorization: bearer $TOKEN" https://$DIRECTOR_IP:25555/deployments -XPOST --data "$(cat $MANIFEST_PATH)"
   ```
   
   Observe that the response is a 302, with a redirection to a task URL.
3. Immediately start another deployment, with the exact same command. Observe that the response is again a 302, with a redirection to a different task URL.
4. Wait 20 seconds, then query the state of the second task:
   
   ```
   curl -k -H "Authorization: bearer $TOKEN" $TASK_URL_FROM_REDIRECT
   ```
   
   The response will look something like:
   
   ```
   {"id":13424,"state":"error","description":"create deployment","timestamp":1461324134,"result":"Redis lock lock:deployment:foo is acquired by another thread","user":"bar","deployment":"foo"}
   ```

Current behaviour:
The first deployment starts a task which completes successfully. The second deployment starts a task which inevitably and very quickly fails. 

Desired behaviour:
The second deployment should fail when we POST '/deployments', rather than creating another task and then failing. 

It is much more work to detect the failure of the second deployment by monitoring the task state than it would be to do so via the response to the deployment request itself. What do you think?

Thanks,
@tomwhoiscontrary and @tinygrasshopper

**Comment by allomov** [comment]
Hey @tinygrasshopper! Could you tell what version of BOSH do you use?

I am sure that the latest version of BOSH got rid of using Redis for locks already. As far as I can see `no-redis-no-cry` branch is merged to master.

**Comment by allomov** [comment]
right, thank you for notice. seems like latest changes can fix this problem.

**Comment by tinygrasshopper** [comment]
Thanks for reply. So I guess this issue will be solved when https://www.pivotaltracker.com/n/projects/956238/stories/115056593 is complete.

**Comment by allomov** [comment]
@tinygrasshopper actually, current changes to deployments controller are not going to change behavior: [you'll get redirect (302 http status) to task object every time you try to create deployment](https://github.com/cloudfoundry/bosh/blob/7e68d8c09fec6ed54bd9384ba9549fbedd13b9f5/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L349). This is a common pattern to provide asynchronous calls (`create_deployment` method just [queues a job](https://github.com/cloudfoundry/bosh/blob/7e68d8c09fec6ed54bd9384ba9549fbedd13b9f5/bosh-director/lib/bosh/director/api/deployment_manager.rb#L19-L21) to create deployment) and I don't think it should be or will be changed.

**Comment by craigfurman** [comment]
Hi @allomov, Thanks for replying! I'm a little confused though: Are you saying that returning 302 when task is submitted for deployments with ongoing tasks is not changing now, or that it should always be the current behaviour?

IMO it's not uncommon for async HTTP APIs to reject long-running operations up-front if it can be determined from initial state that the request is unacceptable, e.g. insufficient permissions to perform the task.

@cppforlife what do you think?

**Comment by allomov** [comment]
Hey, @craigfurman! Yes, this is a behaviour that is currently implemented in the bosh-director code. I can't say if it is going to be changed in future, I just put my thoughts on this point.

It is good for REST API to follow one way of processing the same requests on objects. Currently, most of requests that change state of object make redirects to task object. Doing it in such way allows to support client side easier. Also it allows to track every event that took place in a system (by saving tasks to database). I have seen such redirects on number of projects, so I my believe is that bosh-director can go with it.

**Comment by avade** [comment]
@cppforlife thoughts on this issue? Seems like it would be easier to know upfront if a deployment is going to fail due to an existing operation rather than having to poll another endpoint.

**Comment by tinygrasshopper** [comment]
This behaviour has one more unintended side effect, one of updates might be lost when multiple users are operating on the same deployment. 

Consider the scenario:
- No workers is available on the bosh director. 
- User 1 starts a deployment, modifying a important flag, will get the output. 
  ```
  Acting as client 'admin' on deployment 'empty_box_deployment' on 'bosh'
  Getting deployment properties from director...

  Detecting deployment changes
  ----------------------------
  properties:
  really_important_flag: "<redacted>"

  Deploying
  ---------

  Director task 89
  ```
- User 2 starts a deployment, modifying another flag, will get the output. 
  ```
  Acting as client 'admin' on deployment 'empty_box_deployment' on 'faster-bosh'
  Getting deployment properties from director...

  Detecting deployment changes
  ----------------------------
  properties:
    another_flag: "<redacted>"

  Deploying
  ---------
  ```
Note that User 2 didn't see that `really_important_flag` was being overriden 

- A worker becomes available and processes both the deploy tasks
- Both the users see success messages, but user1's changes are lost

Also, the above scenario would have a totally different outcome if more than one workers were available.

I think we can stop issues of this ilk by acquiring a lock on the deployment, when it is received for processing, rather than when its picked up processing, @cppforlife what do you think?

**Comment by dpb587** [comment]
On a multi-worker bosh the second deployment task will likely fail with "unable to acquire deployment lock." It does seem like a valid, broken scenario on busy BOSHes though.

Still seems like there might be timing issues if the /deployment endpoint starts the lock, but the worker may not pick up the task right away (might be busy working other concurrent deployments). And who would be responsible for the lock in the meantime - the controller responding to the task shouldn't keep it and the workers might not be ready for it yet.

Another thing to note is that the diff call is completely independent from the command to deploy a manifest. Another more involved, possibly more correct option might be for the director diff call to respond back with a hash of the current manifest which then gets forwarded to the actual deploy task. If the deployment has changed by the time it's ready to deploy, it errors.

Just some thoughts. Not sure what @cppforlife thinks.

**Comment by mfine30** [comment]
Closing as this isn't something that we are intending to address. We'd rely on clients doing a better job of managing the deployment lifecycle and potential error cases.
