### ISSUE TITLE
Generating cf manifest file fails using generate_development_manifest on AWS

### ISSUE THREAD

**Issue by Niranjana-5588** [cloudfoundry/bosh#1240]
I followed the link [](https://docs.cloudfoundry.org/deploying/common/create_a_manifest.html) to create  cf manifest file. I have cloned 

> cf-release

 from git on my linux system and created cf-stub.yml file as below
```
---
director_uuid: 5f60d6bd-3775-4f6d-a6b8-52ed6b5c5249
properties:
  domain: bosh-lite.com
```
Then executed file "generate_development_manifest'.
`[ec2-user@ip-10-0-1-234 cf-release]$ ./scripts/generate_deployment_manifest aws cf-stub.yml > cf-deployment.yml`
It gave an error as below
```
error generating manifest: unresolved nodes:
        (( merge ))     in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      networks        (networks)
        (( merge ))     in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      properties.template_only        (properties.template_only)
        (( static_ips(1) ))     in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[0].networks.[0].static_ips        ()
        (( static_ips(1) ))     in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[1].networks.[0].static_ips        ()
        (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))  in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[2].networks.[0].static_ips        ()
        (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))  in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[3].networks.[0].static_ips        ()
        (( static_ips(27, 28, 29) ))    in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[10].networks.[0].static_ips       ()
        (( static_ips(27, 28, 29) ))    in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[11].networks.[0].static_ips       ()
        (( static_ips(10, 25) ))        in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[12].networks.[0].static_ips       ()
        (( static_ips(9) ))     in /home/ec2-user/workspace/cf-release/templates/cf-infrastructure-aws.yml      jobs.[13].networks.[0].static_ips       ()
```
after looking deep in it come to know that it merges three files 
```
cf-infrastructure-aws.yml
cf.yml
generic-manifest-mask.yml
```
why this error comes ?
How to fix ?

**Comment by Niranjana-5588** [comment]
Any solutions or suggestions?

**Comment by ljfranklin** [comment]
@Niranjana-5588 the folks watch the [cf-release repo](https://github.com/cloudfoundry/cf-release) would be better equipped to answer manifest generation questions. You could also ask at cloudfoundry.slack.com in the #release-integration channel.

**Comment by Niranjana-5588** [comment]
I don't belongs to cloudfoundry.slack.com team. Please add me to this team. It will be helpful to post this issue in #release-integration channel.

**Comment by jleavers** [comment]
@Niranjana-5588 You can sign up here: https://slack.cloudfoundry.org/

**Comment by robdimsdale** [comment]
Hi @Niranjana-5588 . It looks like your stub is incomplete -- for example, you're missing a section in your stub for networks. The best place to start is with [these docs on creating a stub for AWS](http://docs.cloudfoundry.org/deploying/aws/cf-stub.html). If you have any further issues or questions, please open a github issue on [cf-release](https://github.com/cloudfoundry/cf-release).

@ljfranklin, feel free to close this issue.

**Comment by ljfranklin** [comment]
Apparently I can't close issues in this repo, pinging @tylerschultz or @cppforlife to close.
