### ISSUE TITLE
Allow referencing from ERB templates other fields of properties in a job spec file

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1241]
When writing jobs we currently have two ERB helpers for accessing the value of properties: `p("my_property")` and `if_p("my_property")`. What we are noticing is that we often find ourselves repeating the description of a property (in the spec file) as comments inside the ERB templates (e.g. in the deployed configuration files). 

A proposal that could help is to be able, in a configuration file, to do something like:

``` erb
my_configuration_directive: <%= p("my_property") %>   # <%= pdesc("my_property") %>
```

where `pdesc(prop)` returns the description of property `prop` if available, empty string otherwise.

Going one step further, if we wanted to allow access not just to the description but also to other fields that may have been defined in the spec file (e.g. the default value or other non-standard fields - we often have `example` keys in our spec files):

``` erb
my_configuration_directive: <%= P("my_property") %>   # <%= P("my_property").description %>
```

where `P` returns an object/hash with all fields defined in the spec file for that properties, plus `value` and `default_value` (for the actual value and the value defined in the spec file, respectively). The object's `to_s` method would simply return whatever is the content of `value` (to be used as a drop-in replacement for `p`).

**Comment by cppforlife** [comment]
I am bit surprised you are adding descriptions to your configuration files. I don't think I've seen that before. We are planning to add property types soon to the Director and may consider this as a use case; however, I am not too eager to expand the `p(...)` interface only for this use case.

**Comment by Amit-PivotalLabs** [comment]
Hi @CAFxX 

I don't think we're too eager to expand the `p(...)` interface for this use case, as @cppforlife mentioned.  As there hasn't been activity on this issue for some time, we will close this out for now.  Please feel free to re-open if you'd still like to discuss this further.

Cheers,
Amit

/cc @mfine30 @dpb587 @jfmyers9
