### ISSUE TITLE
bosh delete orphaned disk

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/bosh#1242]
`bosh disks --orphaned` does show a long list of disks not in use anymore. Actually this disks do not exist in infrastructure anymore *). Now I can't get rid of this orphaned disks:

```
bosh delete disk 15d2c56a-8327-4663-b05e-7b7279e23dbd
RSA 1024 bit CA certificates are loaded due to old openssl compatibility

Director task 85017
  Started deleting orphaned disks > Deleting orphaned disk 15d2c56a-8327-4663-b05e-7b7279e23dbd. Failed: OpenStack API Bad Request. Check task debug log for details. (00:00:04)

Error 100: OpenStack API Bad Request. Check task debug log for details.
```
OS API fails because of disk does not exist. Bosh fails and keeps disk. 

So, I would like to request a `--force` option for `bosh delete disk` to get rid of this inconsistency between Bosh and the infrastructure layer.

Regards,
Stephan

*) One reason could be that a disk deletion job gets a timeout and Bosh keeps it in database. Actually the deletion process on infrastructure was just slow and disk is deleted.

**Comment by cppforlife** [comment]
I would be curious to see debug log for this failure. Typically CPI should raise NotFound error for disks [1] and then record will be removed from the DB.

[1]: https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh-director/lib/bosh/director/disk_manager.rb#L133

cc @voelzmo

**Comment by sklevenz** [comment]
I am closing.

Actually this not an issue of Bosh but more an issue of infrastructure. I am getting a 400 because there are snapshots attached to disk. But there are no snapshots. I have to check infra first...

[debug-dump.txt](https://github.com/cloudfoundry/bosh/files/239868/debug-dump.txt)
