### ISSUE TITLE
Feature Request: `bosh upload blobs` accepts a filename parameter for private.yml

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh#1244]
I would like to use a password management tool such as Last Pass to track my credentials for my blobstore (e.g. I have a note with the contents of my private.yml). Right now, I need to copy/paste that into a file, upload blobs, then remove the file. This leaves traces of my credentials that I'd rather not leave.

I would like to be able to do something like `bosh upload blobs --private-file <(fetch-my-creds)` so that the credentials are only in memory for a short period of time.

Thanks,
Dan

**Comment by cppforlife** [comment]
Agreed.

**Comment by jfmyers9** [comment]
Moved this issue to the bosh-cli: https://github.com/cloudfoundry/bosh-cli/issues/464
