### ISSUE TITLE
BOSH cck/resurrector to respect order of manifest 

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry/bosh#1246]
Is it possible to have cck and resurrector respect order of manifest like deploys does. I've ran into issues with random recreating of vms with cck. The db I want isn't booted up first

**Comment by dpb587-pivotal** [comment]
Related: https://github.com/cloudfoundry/bosh/issues/417

**Comment by cppforlife** [comment]
@longnguyen11288 I think that makes sense.

**Comment by cppforlife** [comment]
Closing. We are slowly converging to having `bosh deploy --fix` having ability to recover deployments in a irregular state. Ultimately we may even turn bosh cck into a command that just reports problems instead of allowing to interactively fix them.
