### ISSUE TITLE
S3 blobstore client ignores host option when downloading blobs

### ISSUE THREAD

**Issue by sax** [cloudfoundry/bosh#1248]
When the `S3BlobstoreClient` is initialized, it builds aws options based on the options passed into the initializer. It then ignores these options for reads, using the default s3 endpoint. Note that `@options` are used to generate `@aws_options`, which are then not used. Instead, the original `@options` is modified to set the `:endpoint` to `S3BlobstoreClient::ENDPOINT`.

https://github.com/cloudfoundry/bosh/blob/d75157676d0fdffd3aa56965d940fb69a28ad366/blobstore_client/lib/blobstore_client/s3_blobstore_client.rb#L30-L54

I am trying to build a local proxy with a cache, to remove the combined waiting time for my team when every workstation downloads the same blobs from s3 when developing on cf-release. I see that the blobstore configuration takes a `:host` key, which I would like to set to my cache/proxy. Instead, bosh directly downloads the files from s3.

**Comment by cppforlife** [comment]
@sax would it be simpler to keep ~/.bosh/cache folder in sync?

**Comment by sax** [comment]
That might end up being the best solution. I had thought that it would be simpler to provide a cache, but something like BitTorrent Sync wind up being less difficult to manage.

Also, I realized that `:host` is only used when configuring a writable S3 blobstore. I can set `:endpoint` directly in my configuration to get the behavior that I was expecting.

Thank you!
