### ISSUE TITLE
Stemcell for Ubuntu 16.04

### ISSUE THREAD

**Issue by wayneeseguin** [cloudfoundry/bosh#1249]
Several clients are interested in seeing their stuff running on Ubuntu 16.04 now that it is officially released. Can we please add an Ubuntu 16.04 stemcell.

Thanks!

  ~Wayne

**Comment by dpb587-pivotal** [comment]
Related list topic: https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/message/PXQYTMJCZ2ZR7F6AIDX42X3DANKEHBYF/

**Comment by rishigits** [comment]
Folks ... do we have any update on this?  Wondering if work has already started to build 16.04 stemcells and if so do we have any release timeline in place.

Thanks.

**Comment by cppforlife** [comment]
@rishigits this is pretty low on our priority list, since we are on the LTS stemcell version + upgraded LTS kernel (4.4). as of now i don't believe garden team or container networking teams are asking for a newer kernel. out of curiosity, what feature in 16.04 are you waiting for?

**Comment by rishigits** [comment]
@cppforlife I am interested in getting Cloud Foundry running on s390x (Linux on Z systems) but s390x only supports xenial. I already tried building a compatible stemcell but ran into issues midway.  Issues were mostly related to BOSH unable to connect to ssh services running inside 16.04 stemcell.  I did not spend too much time to investigate as I thought if x86 xenial stemcell comes out it will be easier to model it for this platform.

**Comment by apeschel** [comment]
@cppforlife It would be nice to switch to 16.04 to make sure everything is systemd compatible sooner than later. 14.04 is only good until 2019 -- 2 more years from now. The longer it takes to get the 16.04 stemcell, the less time people working under Cloud Foundry have to port everything over and make sure it's compatible.

**Comment by ldemailly** [comment]
+1 on support for Ubuntu 16.04.2 LTS

**Comment by tjvman** [comment]
There is a PR for 16.04 stemcells: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/20, we aim to get in the next supported stemcell line.

**Comment by hwinkel** [comment]
We are just entering into the CF world. Was a bit a surprise that the latest supported ubuntu release is 14.04. Is there any more recent, 16.04 LTE available soon. Especially with the latest Security updates it would be a good catch to have it.

**Comment by cppforlife** [comment]
ubuntu bosh stemcells typically follow lts ubuntu releases. 

ubuntu community maintains multiple lts releases at a time. for example trustry is fully supported and updated for the next 2 years. so we are running on a secure and supported version of ubuntu.

at the same time we also pick up new lts releases and make a new stemcell lines based on that. typically its not an urgent thing to do as most bosh releases do not depend on specific os version. we wait a bit for new lts to stabilize and get all the new release bugs out.

currently we are in progress of preparing xenial based stemcell and hoping to release as a beta in next month or so. (next lts version based stemcell - 18.04 - may come a bit quicker though).

**Comment by cppforlife** [comment]
xenial v40 is on bosh.io. light stemcells coming tomorrow.
