### ISSUE TITLE
Can't specify security groups in AWS vm_types

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1250]
In new cloud config for AWS, in `vm_types`, `security_groups` in `cloud_properties` are ignored. Other settings like `iam_instance_profile` or `elbs` are read and applied correctly. Nevertheless, when you do specify `security_groups` under a network definition in `networks`, they are read and applied correctly.

This means that to apply security groups to some VMs, you need to create artificial network definition (along everything that this brings - e.g. ensuring separate address ranges). It would be better if `security_groups` definition worked under `vm_types` - like it is documented:
https://bosh.io/docs/cloud-config.html#vm-types - "CPI specific" link for AWS links to https://bosh.io/docs/aws-cpi.html#resource-pools .

Resource pools do support specifying security groups (added in https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/pull/28), but it seems the same feature is missing when using `vm_types` & cloud config.

BOSH version 255.8

**Comment by cppforlife** [comment]
are using aws cpi 46+?

**Comment by mtekel** [comment]
We used 44. I guess that explains it...
