### ISSUE TITLE
Is there a good way to extend 45s timeout for starting jobs?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1252]
In our deployment, there needs to install some heavy jobs, which need almost 2 mins to start up. But BOSH only sets 45s as the default timeout for starting jobs -> https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/agent_client.rb#L39

Seems this setting is not parameterized, is there a good way to adjust this setting? Thanks.

@jianqiu

**Comment by cppforlife** [comment]
@mattcui 45s timeout is not related to amount of time it takes for the job to start. what failures are you actually seeing as part of the deploy?

**Comment by mattcui** [comment]
@cppforlife We saw the following error when jobs take much longer time to start up:

```
D, [2016-04-26 05:26:34 #24909] [task:78091-checkpoint] DEBUG -- DirectorJobRunner: (0.001116s) COMMIT
D, [2016-04-26 05:26:35 #24909] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:yz-stage0
D, [2016-04-26 05:26:40 #24909] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:yz-stage0
D, [2016-04-26 05:26:45 #24909] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:yz-stage0
D, [2016-04-26 05:26:50 #24909] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:yz-stage0
E, [2016-04-26 05:26:51 #24909] [instance_update(api_worker_dal06/0)] ERROR -- DirectorJobRunner: Error updating instance: #<Bosh::Director::RpcTimeout: Timed out sending `start
' to 45b2363e-ab3a-43bf-9630-a699e4bb7d5c after 45 seconds>
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:227:in `block in handle_method'
/var/vcap/packages/ruby/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:222:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:291:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:326:in `start_task'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:302:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/agent_client.rb:82:in `start'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:126:in `start!'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:74:in `block in update_steps'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:88:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:88:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:87:in `each'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/instance_updater.rb:87:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/job_updater.rb:94:in `block (2 levels) in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/job_updater.rb:92:in `block in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/job_updater.rb:91:in `update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3153.0/lib/bosh/director/job_updater.rb:85:in `block (2 levels) in update_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3153.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

From the source code, seems that the director waits a response from bosh agent for job startup (a sync command) for 45s.
```go
      result.synchronize do
        while result.empty?
          timeout = timeout_time - Time.now.to_f
          unless timeout > 0
            @nats_rpc.cancel_request(request_id)
            raise RpcTimeout,
              "Timed out sending '#{method_name}' to #{@client_id} " +
                "after #{@timeout} seconds"
          end
          cond.wait(timeout)
        end
      end
```

If 45s here is not the timeout waiting for the job startup, where can we set a timeout duration for job startup? Thanks.

**Comment by mattcui** [comment]
@cppforlife this problem got more serious, it could be a blocking issue to migrating our environments now. We hope to get support from BOSH community to help us understand the problem. Firstly, we want to know what's the use of this 45s timeout, in what condition, there will trigger this timeout exception? Thanks. 

/cc @maximilien @jianqiu

**Comment by dpb587-pivotal** [comment]
It might be helpful to see `/var/vcap/bosh/log/current` to know exactly what steps are taking so long for this. Should just be laying down pre-compiled templates and making directories, which shouldn't take long. Perhaps take a look at those, or provide them in anonymized form with full output or just the debug messages.

fwiw, might be similar area of code as https://github.com/cloudfoundry/bosh/issues/1245

**Comment by mattcui** [comment]
@dpb587-pivotal Yes, we checked agent log, we saw the agent got a message from director to start jobs, but we didn't see the agent sent back a response message (may be because jobs are not started within a given time). We always saw "45s timeout" exception in bosh debug log, do you know what kind of problems would trigger this "45s timeout" exception? Thanks.

**Comment by cppforlife** [comment]
@mattcui @maximilien can we arrange a debug session or retrieve agent logs? i'd like to understand exactly what's happening on the agent side. this might be related to start being synchronous operation, which means correct thing to do here would be to switch it to async like many other agent ops.

**Comment by maximilien** [comment]
Yeah, what about tonight 6:30p if no resolution.

**Comment by jianqiu** [comment]
@cppforlife , @maximilien, @mattcui 
Hi Dmitriy,
We found most of the time (45s) was consumed in "monit reload", and did not post "start" action to monit in 45s. But，we could not determine why "monit reload" was blocked,  one possibility is that there are too many monit process (https://github.com/cloudfoundry/bosh/issues/1245), the other is that lots of security jobs failure in the process of starting. 

func (m monitJobSupervisor) Reload() error {
	var currentIncarnation int

	oldIncarnation, err := m.getIncarnation()
	if err != nil {
		return bosherr.WrapError(err, "Getting monit incarnation")
	}

	// Monit process could be started in the same second as `monit reload` runs
	// so it's ideal for MaxCheckTries * DelayBetweenCheckTries to be greater than 1 sec
	// because monit incarnation id is just a timestamp with 1 sec resolution.
	for reloadI := 0; reloadI < m.reloadOptions.MaxTries; reloadI++ {
		// Exit code or output cannot be trusted
		_, _, _, err := m.runner.RunCommand("monit", "reload")
		if err != nil {
			m.logger.Error(monitJobSupervisorLogTag, "Failed to reload monit %s", err.Error())
		}

		for checkI := 0; checkI < m.reloadOptions.MaxCheckTries; checkI++ {
			currentIncarnation, err = m.getIncarnation()
			if err != nil {
				return bosherr.WrapError(err, "Getting monit incarnation")
			}

			// Incarnation id can decrease or increase because
			// monit uses time(...) and system time can be changed
			if oldIncarnation != currentIncarnation {
				return nil
			}

			m.logger.Debug(
				monitJobSupervisorLogTag,
				"Waiting for monit to reload: before=%d after=%d",
				oldIncarnation, currentIncarnation,
			)

			time.Sleep(m.reloadOptions.DelayBetweenCheckTries)
		}
	}

	return bosherr.Errorf(
		"Failed to reload monit: before=%d after=%d",
		oldIncarnation, currentIncarnation,
	)
}

**Comment by bgandon** [comment]
Hello,

I'm facing the same issue. My BOSH deploys very often hit the 45s timeout. Currently I circumvent the problem  with the following script that patches the director and restarts it.

```
cd /var/vcap/packages/director/gem_home/ruby/2.*.*/gems/bosh-director-1.*.0 || exit 115
patch -p0 <<'END_OF_PATCH'
--- lib/bosh/director/agent_client.rb 2016-05-11 14:13:17.000000000 +0000
+++ lib/bosh/director/agent_client.rb 2016-05-26 10:13:53.971352833 +0000
@@ -36,7 +36,7 @@
       @service_name = service_name
       @client_id = client_id
       @nats_rpc = Config.nats_rpc
-      @timeout = options[:timeout] || 45
+      @timeout = options[:timeout] || 90
       @logger = Config.logger
       @retry_methods = options[:retry_methods] || {}
 
END_OF_PATCH
/var/vcap/bosh/bin/monit restart director
```

However I would be happy to find a better way to cure the issue.
In the situation above, what solution did you finally identify?

@cppforlife : how can I know if job start is sync or async in my case? How can I switch it to async?

Thank you for your help.

**Comment by Amit-PivotalLabs** [comment]
Hi all,

To answer the original question about extending the timeout, it is not configurable, and this is intentional since the problem is likely symptomatic of other root cause problems that should be addressed.  There have been improvements made to how the Agent interacts with monit since the issue was opened which might address those root causes.  If this issue is still a challenge, please give the latest stemcells a shot (or a stemcell built with the latest Agent code if you're using a stemcell not maintained by the core BOSH maintainers).  We'll close this issue out due to inactivity, please feel free to re-open if the issue persists with the latest Agent code.

Thanks,
Amit

/cc @jfmyers9 @mfine30 @dpb587
