### ISSUE TITLE
When BOSH_MICRO_ENABLED=no, bosh-init failed to bootstrap a director by the stemcell built with published OS image 

### ISSUE THREAD

**Issue by jianqiu** [cloudfoundry/bosh#1256]
If you want to build a stemcell without bosh release, you need to set BOSH_MICRO_ENABLED=no
but the stemcell built with published OS image did not have the directory for blobstore path, for example, /var/vcap/micro_bosh/data/cache.

So when bootstrapping a director by bosh-init, it will get the following error:

Command 'deploy' failed:
  Deploying:
    Building state for instance 'bosh/0':
      Rendering job templates for instance 'bosh/0':
        Uploading rendered job template archive '/root/.bosh_init/installations/936a5ef7-3b01-4fe2-63b5-ce31f0b73dab/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir717328491' to the blobstore:
          Putting file '/root/.bosh_init/installations/936a5ef7-3b01-4fe2-63b5-ce31f0b73dab/tmp/bosh-platform-disk-TarballCompressor-CompressFilesInDir717328491' into blobstore (via DAVClient) as blobID 'd486275a-73c9-41ac-7e21-8eee542877fe':
            Putting dav blob d486275a-73c9-41ac-7e21-8eee542877fe: Wrong response code: 500; body: Opening blob store file: open /var/vcap/micro_bosh/data/cache/d486275a-73c9-41ac-7e21-8eee542877fe: no such file or directory

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/115537581

**Comment by jianqiu** [comment]
[Uploading @40000000572088ba2421234c.s.txt…]()

**Comment by cppforlife** [comment]
I think this is covered by recent stemcells as they are now produced from concourse.
