### ISSUE TITLE
Security issue: Need to upgrade postgresql to 9.5.2 or later version

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1259]
Two vulnerability issues:

https://exchange.xforce.ibmcloud.com/vulnerabilities/112005
https://exchange.xforce.ibmcloud.com/vulnerabilities/112006

**Comment by cppforlife** [comment]
Planning to bump to latest 9.4.x: https://www.pivotaltracker.com/story/show/119379617

**Comment by mattcui** [comment]
@cppforlife Possible to upgrade to 9.5.x? The security issue is fixed in 9.5.2 according to vulnerability reports. Thanks.

**Comment by cppforlife** [comment]
@mattcui i would rather not bump to another minor version. we just recently added 9.4.x series. any security vulnerabilities would have been fixed in the latest 9.4.x

**Comment by dpb587-pivotal** [comment]
Closing - postgres was updated to the latest 9.4 version in [v257](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262), although the mentioned vulnerabilities did not affect 9.4, only 9.5.
