### ISSUE TITLE
net-ssh version in bosh_cli makes deprecated call

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/bosh#1264]
Version 2.9.2 of net-ssh, in Ruby 2.3.0, packaged into bosh_cli makes a deprecated call:

`.../.gem/ruby/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in`initialize': Object#timeout is deprecated, use Timeout.timeout instead.`

This causes some minor unnecessary log noise, updating to net-ssh 2.10.0 would seem to stop this.

**Comment by cppforlife** [comment]
@BooleanCat 2.10 has been yanked. 2.10+ are Ruby 2+. I do know a few cases when people are still relying on Ruby 1.9 even though it's not supported.

**Comment by dpb587-pivotal** [comment]
Closing - ruby CLI is now frozen in favor of developing [bosh-cli](https://github.com/cloudfoundry/bosh-cli). Upcoming go-based CLI does not spam the extra log messages in output. Feel free to give the new CLI a try and provide feedback in that repo.
