### ISSUE TITLE
`bosh target <BOSH_URL>` should not require login

### ISSUE THREAD

**Issue by suhlig** [cloudfoundry/bosh#1265]
If there is no `.bosh_config`, like in a fresh install, setting the bosh target requires the user to enter username and password interactively via the console. This makes it hard to write scripts:

```
$ rm .bosh_config
$ bosh target https://192.168.50.4:25555
Your username: ^C
Exiting...
```

What we'd like instead is to split setting the target from actually logging in:

```
$ rm .bosh_config
$ bosh target https://192.168.50.4:25555
Target set to `Bosh Lite Director'
$ bosh login admin admin
Logged in as `admin'
```

Alternatively, passing username and password to `bosh target` would also be fine, e.g.:

```
$ bosh target https://192.168.50.4:25555 -u admin -p admin
Target set to `Bosh Lite Director'
Logged in as `admin'
```

**Comment by voelzmo** [comment]
@suhlig If I understand you correctly, you are looking for a way to separate setting the target and logging in? Does `bosh -n target <target>` help? You can call `bosh login <user> <pass>` afterwards to login.

**Comment by suhlig** [comment]
Nevermind, we just found out that

```
$ bosh -u admin -p admin target https://192.168.50.4:25555
```

does what we want. 

Thanks!
