### ISSUE TITLE
Duplicate director workers running

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1270]
I made the mistake of doing a `monit restart director` while a [snapshot] task was running. An hour later I get the following confusing error during a deploy...

```
Director task 12507
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started updating job main > main/0 (de56ea95-4a03-4655-bd46-0498c54429a6) (canary)

Error 100: Failed to acquire lock for lock:deployment:yarnblog uid: 10a7bde4-9b65-46ee-9b3e-186441202cb0

Task 12507 error
```

Turns out director had duplicate #2 workers. Both of them happened to pickup the task and while one of them failed to acquire the lock and errored the task, the other continued with the deployment task...

```
  ├─ruby,21899 /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_2.yml -i 2
  │   ├─ruby,23482 /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_2.yml -i 2
  │   │   ├─{ruby},23484
  │   │   ├─{ruby},23485
  │   │   ├─{ruby},23486
  │   │   ├─{ruby},23487
  │   │   ├─{ruby},23488
  │   │   ├─{ruby},23489
  │   │   ├─{ruby},23490
  │   │   ├─{ruby},23491
  │   │   ├─{ruby},23492
  │   │   ├─{ruby},23493
  │   │   ├─{ruby},23494
  │   │   ├─{ruby},23495
  │   │   ├─{ruby},23496
  │   │   ├─{ruby},23497
  │   │   ├─{ruby},23498
  │   │   ├─{ruby},23499
  │   │   ├─{ruby},23518
  │   │   ├─{ruby},23519
  │   │   ├─{ruby},23520
  │   │   ├─{ruby},23525
  │   │   ├─{ruby},23526
  │   │   ├─{ruby},23528
  │   │   ├─{ruby},23530
  │   │   ├─{ruby},23575
  │   │   └─{ruby},23576
  │   ├─{ruby},23478
  │   └─{ruby},23483
  ├─ruby,22115 /var/vcap/packages/director/bin/bosh-director-worker -c /var/vcap/jobs/director/config/worker_2.yml -i 2
  │   └─{ruby},23718
```

This is reproducible with the steps:
1. Start a brief task
2. Do `monit restart director`
3. Wait for tasks being up
4. See an extra worker running (with a different PID than the original workers)

Seems like this shouldn't be possible. I guess it's unlikely to be an issue on bosh-init-managed directors where they're always recreated/restarted from scratch, but on bosh-managed directors it's more plausible.

Director 1.3232.2.0

**Comment by jadekler** [comment]
We're seeing this problem, too

**Comment by DonBower** [comment]
Any Resolution?

**Comment by dpb587-pivotal** [comment]
Fixed in [v262](https://github.com/cloudfoundry/bosh/releases/tag/v262).
