### ISSUE TITLE
Upload Base AMI to GovCloud Regions

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh#1271]
Each build copies the AMI image to each region, such as us-east-1.  In order to deploy in GovCloud, we would like the build process to upload the AMI to one additional region: **us-gov-west-1** (list of all regions: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html)

Currently this process is shown in the ami.log for other regions:
`I, [2016-05-16T23:39:15.991606 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'sa-east-1'
I, [2016-05-16T23:39:15.991807 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'eu-west-1'
I, [2016-05-16T23:39:15.991901 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'eu-central-1'
I, [2016-05-16T23:39:15.992004 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'ap-southeast-1'
I, [2016-05-16T23:39:15.992077 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'ap-southeast-2'
I, [2016-05-16T23:39:15.992185 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'ap-northeast-1'
I, [2016-05-16T23:39:15.992372 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'ap-northeast-2'
I, [2016-05-16T23:39:15.992427 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'us-west-1'
I, [2016-05-16T23:39:15.992490 #25438]  INFO -- : Copying AMI 'ami-25c62e48' from region 'us-east-1' to region 'us-west-2'
I, [2016-05-16T23:44:41.910298 #25438]  INFO -- : [AWS EC2 200 0.502354 0 retries] describe_tags(:filters=>[{:name=>"key",:values=>["Name"]},{:name=>"resource-type",:values=>["image"]},{:name=>"resource-id",:values=>["ami-25c62e48"]}])  
​
I, [2016-05-16T23:44:42.347700 #25438]  INFO -- : Finished copying AMI 'ami-25c62e48' from region 'us-east-1' to AMI 'ami-89e908e8' in region 'ap-northeast-1'
I, [2016-05-16T23:44:46.533796 #25438]  INFO -- : [AWS EC2 200 0.152518 0 retries] describe_tags(:filters=>[{:name=>"key",:values=>["Name"]},{:name=>"resource-type",:values=>["image"]},{:name=>"resource-id",:values=>["ami-25c62e48"]}])  
​
I, [2016-05-16T23:44:46.795683 #25438]  INFO -- : Finished copying AMI 'ami-25c62e48' from region 'us-east-1' to AMI 'ami-a45d25c4' in region 'us-west-1'
I, [2016-05-16T23:44:47.485773 #25438]  INFO -- : [AWS EC2 200 0.031049 0 retries] describe_tags(:filters=>[{:name=>"key",:values=>["Name"]},{:name=>"resource-type",:values=>["image"]},{:name=>"resource-id",:values=>["ami-25c62e48"]}])  
​
I, [2016-05-16T23:44:47.800282 #25438]  INFO -- : Finished copying AMI 'ami-25c62e48' from region 'us-east-1' to AMI 'ami-696b9709' in region 'us-west-2'
I, [2016-05-16T23:44:55.332455 #25438]  INFO -- : [AWS EC2 200 0.080949 0 retries] describe_tags(:filters=>[{:name=>"key",:values=>["Name"]},{:name=>"resource-type",:values=>["image"]},{:name=>"resource-id",:values=>["ami-25c62e48"]}])  
​
I, [2016-05-16T23:44:55.684389 #25438]  INFO -- : Finished copying AMI 'ami-25c62e48' from region 'us-east-1' to AMI 'ami-7abc3416' in region 'sa-east-1'
I, [2016-05-16T23:45:07.241101 #25438]  INFO -- : [AWS EC2 200 0.079862 0 retries] describe_tags(:filters=>[{:name=>"key",:values=>["Name"]},{:name=>"resource-type",:values=>["image"]},{:name=>"resource-id",:values=>["ami-25c62e48"]}])  `

**Comment by LinuxBozo** [comment]
This may be more an issue with the AWS CPI, and definitely an issue in documentation, but the situation we'd like to solve is bootstrapping with `bosh-init` into AWS GovCloud using either:
1. A Mac or
2. Inside a Concourse pipeline

The bosh-init documentation doesn't really list any limitations for something like this, but clearly, they exist.

When using a full stemcell, if you try to run on the Mac:

```
creating stemcell (bosh-aws-xen-ubuntu-trusty-go_agent 3232.4):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Timed out reading instance metadata, please make sure CPI is running on EC2 instance","ok_to_retry":false}
```

Ok, so we have Concourse on EC2. However, if you try running within a Concourse job (and therefore, garden container):

```  
creating stemcell (bosh-aws-xen-ubuntu-trusty-go_agent 3232.4):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Cannot find EBS volume on current instance","ok_to_retry":false}
```

So, the issue is that using a full stemcell to bootstrap with `bosh-init` currently requires that it is run within a full EC2 instance. If `create_stemcell` needs an EC2 instance to build an AMI from stemcell image, shouldn't it provision it, and tear it down when finished, much like compilation vms?

/cc @sharms @dlapiduz @cnelson

**Comment by ljfranklin** [comment]
Hello @LinuxBozo and friends,

Definitely agree that the requirement to be within a full EC2 instance is a no-go in Concourse. We currently don't have a nice workaround, but sounded like @cppforlife would be open to supporting your use-case in the CPI.

If you are feeling adventurous, you could try to produce your own light stemcells. We created the [light stemcell builder](https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder) tool to produce the official light AWS stemcells. This runs within Concourse (see [pipeline config](https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder/blob/master/ci/pipeline.yml)) and creates a light stemcell with the following workflow:
1. Convert heavy stemcell image to stream optimized VMDK (shortens upload time)
1. Upload VMDK to S3 bucket
1. Create Volume from file on S3
1. Create Snapshot from Volume
1. Create AMI from Snapshot

One problem, I don't think this tool currently provides a way to configure the AWS endpoint. You could try your luck at a PR to make the endpoint configurable, or talk @cppforlife into prioritizing that work. Let us know if you have other questions / thoughts.

**Comment by dlapiduz** [comment]
@ljfranklin @cppforlife we did a test with very few modifications and it worked like a charm.

Thanks!

**Comment by ljfranklin** [comment]
Glad to hear it @dlapiduz! If you have the time, would you mind submitting a PR with your changes to the light stemcell project? It's always tough for us to add GovCloud changes on our own as we don't have access to that environment.

**Comment by dlapiduz** [comment]
@ljfranklin here is a very small PR for the change https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder/pull/1. Most of the other stuff came as pipeline changes (https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder/compare/master...18F:master?expand=1) and they are not backwards compatible :(

**Comment by ljfranklin** [comment]
@cppforlife @tylerschultz I think this can be closed out
