### ISSUE TITLE
bosh login does not read $BOSH_USER and $BOSH_PASSWORD

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1273]
In the `bosh login` help it [says here](https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/bosh_cli/lib/cli/commands/login.rb#L12): 

> The username and password can also be set in the BOSH_USER and BOSH_PASSWORD environment variables.

But I think that is not really true. 

If you are using UAA, then the right variables are `BOSH_CLIENT` and `BOSH_CLIENT_PASSWORD` [as defined here](https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/client/uaa/auth_info.rb#L14) 

But that object [is only used for UAA](https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/bosh_cli/lib/cli/commands/login.rb#L32-L41), with the basic authentication is not used at all. So you cannot set the password as environment variables when using basic auth.

**Comment by cppforlife** [comment]
@keymon yup the help text for the command is poorly worded and incorrect for UAA use case. we do support UAA clients for non-interactive usage: https://bosh.io/docs/director-users-uaa.html#client-login

I believe BOSH_USER/PASSWORD env vars are not meant to be used with login command but rather you can just set them before running any other command (when basic auth is used) and you will be authenticated. https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/base_command.rb#L160

**Comment by dpb587-pivotal** [comment]
Closing - ruby CLI is frozen and behavior won't be changing. Discussion around this topic is continuing in the new bosh-cli repo with [#48](https://github.com/cloudfoundry/bosh-cli/issues/48).
