### ISSUE TITLE
DNS is missing in vm after deleted bosh VM resurrects

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/bosh#1280]
I have cloud foundry deployment .I have 3 kafka,3 zookeper and 3- vault/consul instance. 

```
kafka/0 10.20.0.174 
zookeeper/2 10.20.0.242 
vault_consul/0 10.20.0.247 
```

 For testing purpose i delete one of the vm from each .All the vm's are resurrecting and these vm's have new IP now,but dns is missing in them. 
 bosh vms output is as follows 

```
 kafka/0             | running | service-net-medium | 10.20.0.251 | n/a  | 
 zookeeper/2      | running | service-net-medium | 10.20.0.250 | n/a  |
 vault_consul/0   | failing |   small | 10.20.0.25 | n/a 
```

On Analysing the Microbosh DB I found dns name are still mapped with old ip.
Microbosh PostgresDB output 

./psql bosh -c "select id, name, type, content from records;"  

```
46 | 0.kafka.ccc-service-net.cf-devtest21vik.microbosh | A | 10.20.0.174 
47 | 174.0.20.10.in-addr.arpa | PTR | 0.kafka.ccc-service-net.cf-devtest21vik.microbosh  
28 | 2.zookeeper.ccc-service-net.cf-devtest21vik.microbosh | A | 10.20.0.242 
29 | 242.0.20.10.in-addr.arpa | PTR | 2.zookeeper.ccc-service-net.cf-devtest21vik.microbosh  
67 | 0.vault-consul.ccc-service-net.cf-devtest21vik.microbosh | A | 10.20.0.247
70 | 247.0.20.10.in-addr.arpa | PTR | 0.vault-consul.ccc-service-net.cf-devtest21vik.microbosh   
```

Microbosh manifest file 

 <% load 'micro01/micro_bosh.rb' %>  
name: <%= $os_tenant %>  
logging: level: DEBUG  
network: type: manual
   ip: <%= $ip_address %> 
   cloud_properties: name: ccc-bosh-net 
   net_id: <%= $net_id %>  
resources: persistent_disk: 50000 
cloud_properties: instance_type: <%= $bosh_flavor %> disk: 16384  cloud: plugin: openstack properties: openstack: auth_url: <%= $os_auth_url %> username: <%= $os_username %> api_key: <%= $os_password %> tenant: <%= $os_tenant %> default_security_groups: [vms-security-group] default_key_name: <%= $key_name %> private_key: <%= $key_file %> ignore_server_availability_zone: true  
apply_spec: 
   properties: director: 
   max_threads: 32 hm: 
  resurrector_enabled: true 
  director_account: user: <%= $bosh_username %> 
  password: <%= $bosh_password %> 
  ntp: - <%= $ntp1 %> - <%= $ntp2 %> 
  dns: 
    recursor: 8.8.8.8 env: bosh: password: <%= $sha_password %> 

 Is is possible for VM to have same ip if not at least it should update it MIcrobosh DM.Let me know   how to achieve  this.
 Is there any config missing in this. Help me to resolve this issue.

**Comment by cppforlife** [comment]
which version of bosh are you using (bosh status output)?

**Comment by chrisrana** [comment]
bosh --version
BOSH 1.3071.0

**Comment by chrisrana** [comment]
root@dev-inception-vm21:/home/ubuntu# bosh status
Config
             /root/.bosh_config

Director
  Name       installdev2
  URL        https://10.20.0.55:25555
  Version    1.3155.0 (00000000)
  User       admin
  UUID       3dc7bb73-4fa6-4c83-ab33-e9c870861e05
  CPI        openstack
  dns        enabled (domain_name: microbosh)
  compiled_package_cache disabled
  snapshots  disabled

Deployment
  Manifest   /opt/installer/tenant-devtest21vik/cf-deploy/cf-devtest21vik.yml
root@dev-inception-vm21:/home/ubuntu#

**Comment by cppforlife** [comment]
ah older version. since that version we have fixed several issues with how we track dns records in the director. i would recommend updating your director to the latest version to get those dns fixes.

**Comment by chrisrana** [comment]
What is the latest version of bosh cli .which one I should use

**Comment by cppforlife** [comment]
to clarify you should update your director not the cli to the latest version. though you should also update your cli while you are updating.

see https://bosh.io for the latest versions of bosh release.

**Comment by dpb587** [comment]
@cppforlife, [this story](https://www.pivotaltracker.com/story/show/77843762) was about this issue as well, but sounds like it can be closed as fixed elsewhere?

**Comment by chrisrana** [comment]
Bosh director means stemcell version is it ?

**Comment by dpb587-pivotal** [comment]
@chrisrana, you can try using bosh_cli/[1.3232.0](https://rubygems.org/gems/bosh_cli/versions/1.3232.0) and director/[256.2](http://bosh.io/releases/github.com/cloudfoundry/bosh?version=256.2). DNS fixes are mostly director related, but would still recommend using the latest stemcell, currently 3232.4.

**Comment by chrisrana** [comment]
I forgot mention I use MicroBosh for deployment because it is Single VM director.

**Comment by dpb587-pivotal** [comment]
I see. The `bosh micro` deployment method is deprecated and will be discontinued soon. I'd recommend [migrate to bosh-init](http://bosh.io/docs/migrate-to-bosh-init.html) and upgrade your versions. If you need microbosh, you can still use your current procedure, just bump `STEMCELL_VERSION`.

**Comment by dpb587-pivotal** [comment]
Closing - please [migrate to bosh-init](http://bosh.io/docs/migrate-to-bosh-init.html) and update your director release to ensure you have the latest fixes to DNS related issues which may have come up earlier.
