### ISSUE TITLE
Deploy Error 190014: Deployment manifest should not contain cloud config properties: ["compilation", "networks", "resource_pools"]

### ISSUE THREAD

**Issue by huangered** [cloudfoundry/bosh#1282]
I create own mongodb release, when Upload the manifest, it throws Error 190014

my bosh version is 1.3232.0
my platform is vsphere, i search the google and bosh site, it may relate to the cloud-config opt-in. but i have no idea anymore.

    Director task 163
      Started preparing deployment > Preparing deployment. Failed: Deployment manifest should not contain cloud config properties: ["compilation", "networks", "resource_pools"] (00:00:00)
    
    Error 190014: Deployment manifest should not contain cloud config properties: ["compilation", "networks", "resource_pools"]

my manifest is :

    ---
    name: mongodb3
    director_uuid: d3df0341-4aeb-4706-940b-6f4681090af8
    
    releases:
    - name: mongodb
      version: latest
    
    compilation:
      workers: 1
      reuse_compilation_vms: false
      network: default
      cloud_properties:
        cpu: 4
        datacenters:
        - clusters:
          - cf_z2:
              resource_pool: mongodb
          name: cf_z2
        disk: 20480
        ram: 4096
    
    update:
      canaries: 1
      canary_watch_time: 15000-30000
      update_watch_time: 15000-30000
      max_in_flight: 1
    
    networks:
    - name: default
      type: manual
      subnets:
      - cloud_properties:
          name: VM Network
        range: 10.62.90.133/25
        gateway: 10.62.90.129
        static:
        - 10.62.90.140
        reserved:
        - 10.62.90.130 - 10.62.90.139
        - 10.62.90.151 - 10.62.90.254
        dns:
        - 10.254.174.10
        - 10.104.128.235
    
    resource_pools:
    - cloud_properties:
        cpu: 2
        datacenters:
        - clusters:
          - cf_z2:
              resource_pool: mongodb
          name: cf
        disk: 10480
        ram: 4096
      name: mongodb3
      network: default
      stemcell:
        name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
        version: latest
    jobs:
    - name: mongodb3
      instances: 1
      templates:
      - {name: mongodb3, release: mongodb3}
      persistent_disk: 10_240
      resource_pools: mongodb3
      networks:
      - name: default

**Comment by huangered** [comment]
solved, these three parts need to be put in a single file.

**Comment by arut95** [comment]
Those 3 parts should be kept in cloud-config.yml
