### ISSUE TITLE
final release creation expects s3 access key, despite env_or_profile being set

### ISSUE THREAD

**Issue by aristotelesneto** [cloudfoundry/bosh#1286]
When attempting to create a final release, looks like the cli doesn't allow it through unless s3.access_key and secret are present.

https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/release.rb#L76

This is an issue for those using iam profiles (credentials_source: env_or_profile).

Other tasks (for example sync blobs, are able to leverage credentials from the profile).

**Comment by aristotelesneto** [comment]
Doesn't I'm afraid - fails here: https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/bosh-registry/lib/bosh/registry/instance_manager/aws.rb#L67

**Comment by cppforlife** [comment]
are you sure? thats registry code which is not used by the cli in the finalize release path.

**Comment by aristotelesneto** [comment]
Sorry wrong file (i just did a quick search on github for the env_of_profile and picked the first error) - fails with a similar error. IIRC it was on the blobstore, so here: https://github.com/cloudfoundry/bosh/blob/master/blobstore_client/lib/blobstore_client/s3_blobstore_client.rb#L172

**Comment by dpb587-pivotal** [comment]
Closing - the new [CLI](https://github.com/cloudfoundry/bosh-cli) supports the `credentials_source` setting. The ruby CLI is now frozen, so we won't be making further changes. Feel free to give the new CLI a try and leave feedback/issues in that repo. Thanks, @aristotelesneto!
