### ISSUE TITLE
Improve cross platform support for bosh cli

### ISSUE THREAD

**Issue by 0x1mason** [cloudfoundry/bosh#1292]
I've made some changes to my local install to bosh cli overall cross platform support. The main issue is differing behavior of `tar` across platforms.  By replacing calls to `tar` with Ruby code, I've been able to standardize behavior and reduce code paths. E.g., special handling for BSD vs GNU tar is no longer required. The most significant impact of the change is that bosh cli now works on Windows without hassle.

I'd like to submit my code for consideration. I am not suggesting bosh cli add "official" Windows support. Rather, I hope you'll consider the PR as a Rubification of existing archive handling logic that reduces external dependencies and provides better XP experience.

**Comment by 0x1mason** [comment]
Moving to bosh-lite

**Comment by dpb587-pivotal** [comment]
Hi @0x1mason - glad to hear you were able to get CLI working locally on Windows! Windows support has come up a couple times over the years, but it hasn't been a high priority.

I think the CLI has some planned enhancements which may make the changes difficult to merge right now, but, community-wise, you could still push your changes to a branch in case others are interested in trying out the CLI on Windows in the meantime. I'd also personally be curious to see what kinds of changes you found were required.

Thanks for raising an issue to discuss this!

**Comment by 0x1mason** [comment]
Thanks. I'll do that. It'll take me a bit--swamped at work and I need to jump thru some more hoops to get the lawyers to sign the CLA.

The heart of the changes were removing `tar` and using ruby instead. There is existing platform-specific handling for differences between BSD and GNU `tar`. My changes make all that unnecessary. . So you can think of this as a "make it work the same way for everyone regardless of OS" change.  It's basically just a drop-in for the `tar` invocations.

**Comment by 0x1mason** [comment]
I have tar on Windows. It works great from the command line. The sys calls from Ruby, not so much.

**Comment by dpb587-pivotal** [comment]
Closing - we won't be making further changes to ruby CLI in favor of continuing development of our go-based [bosh-cli](https://github.com/cloudfoundry/bosh-cli). There is currently an open issue about enabling builds for Windows if you want to follow that there - https://github.com/cloudfoundry/bosh-cli/issues/53.
