### ISSUE TITLE
Stemcell Openstack KVM Ubuntu 14.04 / JNA startup issue with Cassandra

### ISSUE THREAD

**Issue by baschno** [cloudfoundry/bosh#1293]
I'm setting up a bosh release for Apache Cassandra 2.2.5/2.2.6. 
Both 2.2.x releases fail to start with the newer stemcell releases 3232.x throwing a JNA NoClassDefFound exception like below:

```
WARN  10:51:20 JNA link failure, one or more native method will be unavailable.
INFO  10:51:20 jemalloc seems to be preloaded from /usr/lib/x86_64-linux-gnu/libjemalloc.so.1
INFO  10:51:20 JMX is enabled to receive remote connections on port: 7199
INFO  10:51:20 Initializing SIGAR library
INFO  10:51:20 Could not initialize SIGAR library org.hyperic.sigar.Sigar.getFileSystemListNative()[Lorg/hyperic/sigar/FileSystem; 
INFO  10:51:20 Sigar could not be initialized, test for checking degraded mode omitted.
INFO  10:51:21 Initializing system.sstable_activity
ERROR 10:51:22 Error in ThreadPoolExecutor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at org.apache.cassandra.utils.memory.MemoryUtil.allocate(MemoryUtil.java:82) ~[apache-cassandra-2.2.6.jar:2.2.6]
....
```

I checked all 3232.x releases up to the newest.

Both releases will execute successful if switching the stemcell release back to 3215...
Is anyone aware of changes to JNA/JNI components within those stemcell versions? How can this be fixed?
Thanks

**Comment by cppforlife** [comment]
@baschno https://github.com/cloudfoundry/bosh/releases/tag/stable-3232 did enable auditd and few other sec related changes. that may be somehow causing this problem. anything in dmesg related to this?

this may be related: we now mount /tmp with noexec. may be that's causing the problem?

```
root@371be127-9908-48e2-47e4-40322589d3fc:/home/vcap# mount|grep /tmp
/var/vcap/data/root_tmp on /tmp type ext4 (rw,noexec)
```

**Comment by cppforlife** [comment]
@baschno any findings?

**Comment by baschno** [comment]
No findings so far... I need to make some more checks. Currently sticking with the old stemcell release.

**Comment by baschno** [comment]
@cppforlife With the 3262 stemcell releases the issue disappeared and Cassandra is working again...
So this issue only appears for all 3232.x releases.

**Comment by cppforlife** [comment]
Failure remained undiagnosed in earlier stemcell versions. Feel free to reopen if new information comes up.
