### ISSUE TITLE
Bosh cleanup --all not recursive

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1294]
Hi,

it seems like `bosh cleanup --all` command is not recursive. On the 1st pass it will remove a lot of things, but it seems like there could be some dependencies (e.g. between packages and releases). This makes BOSH not remove all the things. When you then do `bosh cleanup --all` again, BOSH will now clean up the rest (because dependencies were removed in previous pass). And so on. Sometimes it takes 3-4 cleanups to really clean up everything. So perhaps the command could be recursive and do that already - keep cleaning up until there's nothing more to remove...

e.g.:
```
...
 Started deleting packages > golang/5519bcd760fbf15e8c2a0562da4cf2e00d846df9
     Done deleting packages > shadow/ffd1741bd9e0a176e67c61ef70cd0ed76b0ec285 (00:00:00)
  Started deleting packages > garden-linux/e869024b1c7e49ca2ad3d17fcd2bc623f0ef5ff3. Done (00:00:00)
  Started deleting packages > golang_1.6.1/7c83e83f822259c6324742e3dfc5d4aaae25e9e6
     Done deleting packages > golang/5519bcd760fbf15e8c2a0562da4cf2e00d846df9 (00:00:00)
     Done deleting packages (00:00:01)

  Started deleting jobs > rds-broker/0bee13ee9c95c44da61c9015a74f5680284ca3d6. Done (00:00:00)

     Done deleting releases > aws-broker/0.0.3 (00:00:02)

     Done deleting packages > golang_1.6.1/7c83e83f822259c6324742e3dfc5d4aaae25e9e6 (00:00:00)
  Started deleting packages > iptables/7226d311e90f49b05287e79f339581a1de9ea82e. Done (00:00:00)
     Done deleting packages (00:00:01)

     Done deleting releases > garden-linux/0.337.0 (00:00:02)
     Done deleting releases (00:00:02)

Task 47 done

Started		2016-06-07 14:30:58 UTC
Finished	2016-06-07 14:31:00 UTC
Duration	00:00:02

Cleanup complete
/tmp/build/e55deab7 # bosh cleanup --all
Acting as user 'admin' on 'my-bosh'

Director task 48
  Started deleting releases
  Started deleting releases > diego/0.1467.0
  Started deleting releases > etcd/45
  Started deleting releases > grafana/commit-44564533c9d4d656bdcd5633b808f0bf6fb177ae
  Started deleting releases > logsearch-shipper/4

  Started deleting packages
  Started deleting packages > logsearch-collectd/f1647001221502d1d5750b5d2f5bd69f07661cc5
  Started deleting packages > grafana/edabf0bd5a909fd446bb048e19a034660daaa231
...
```

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/122079561

**Comment by mingxiao** [comment]
We started looking into this but haven't found the issue yet. It would be helpful to see the full task logs. Do you still have the task logs for the `bosh cleanup --all` commands?

**Comment by mtekel** [comment]
Hi,

I don't have the logs from the time of the initial description. I will check again if I can reproduce it and provide full logs then. This all was/will be on BOSH 255.8. Maybe you have changed something how this command works/behaves since then, the logs might be a bit less useful then.

**Comment by mtekel** [comment]
Hi,

I have checked again. Find the logs attached - they also contain CLI (1.3202.0) and BOSH (1.3215.3.0) version details. Initially I have seen some issues with PSQL (there's connection issue in debug log). Then PSQL complains some items can't be removed from DB as they have dependencies. But even in the end, when the errors go away, it takes multiple successful `bosh cleanup --all` runs to really remove all the things. Altogether, it took me 4 tasks to clean up everything...

**Comment by mtekel** [comment]
Some issues attaching zip, so plaintext files instead:
[363.debug.txt](https://github.com/cloudfoundry/bosh/files/361323/363.debug.txt)
[363.txt](https://github.com/cloudfoundry/bosh/files/361321/363.txt)
[364.debug.txt](https://github.com/cloudfoundry/bosh/files/361320/364.debug.txt)
[364.txt](https://github.com/cloudfoundry/bosh/files/361319/364.txt)
[365.debug.txt](https://github.com/cloudfoundry/bosh/files/361324/365.debug.txt)
[365.txt](https://github.com/cloudfoundry/bosh/files/361322/365.txt)
[366.debug.txt](https://github.com/cloudfoundry/bosh/files/361325/366.debug.txt)
[366.txt](https://github.com/cloudfoundry/bosh/files/361328/366.txt)
[367.debug.txt](https://github.com/cloudfoundry/bosh/files/361326/367.debug.txt)
[367.txt](https://github.com/cloudfoundry/bosh/files/361329/367.txt)
[bosh.txt](https://github.com/cloudfoundry/bosh/files/361327/bosh.txt)

**Comment by dpb587-pivotal** [comment]
Helpful thanks! We'll take another look.

Mentioned error looks like...

    PG::Error: ERROR:  update or delete on table "packages" violates foreign key constraint "compiled_packages_package_id_fkey" on table "compiled_packages"
DETAIL:  Key (id)=(103) is still referenced from table "compiled_packages".

**Comment by mtekel** [comment]
With the latest bosh (v257.14, also known (and reported by BOSH) as 3263.7 - you should only have one version number scheme) this seems to be fixed. It cleans up everything in one pass. Will reopen if I see the issue again.

**Comment by dpb587-pivotal** [comment]
Interestingly, I don't think our fix has made it to an official release - but I'm happy to hear it's working! From our fix for this, it looked like the issue may have occurred when blobs could not be immediately deleted. We did refactoring to at least do a better job at raising full error details. Those changes should be in the next release.

Next release should also fix the versioning inconsistency you noticed (I agree that is confusing).
