### ISSUE TITLE
Update monit to more recent version in stemcell

### ISSUE THREAD

**Issue by sax** [cloudfoundry/bosh#1295]
There are some nice features that were added to monit a few years ago, including the ability to configure a `check program`, which runs a script and checks the exit status, without needing a process to stay running.

When we check monit version in bosh-lite, we see that it uses monit `5.2.4`, which was released in 2011.

I'm unclear on what it would take to make this update, but with the slow upgrade path of bosh installations in the wild, it seems like this would be a useful thing to do earlier rather than later, so that people could use more current monit syntax at some point in the future.

**Comment by uzzz** [comment]
Stemcell for bosh-lite is bit outdated. Stemcells for other IaaSes contains monit 5.2.5.

**Comment by mtekel** [comment]
Looks like 5.2.5 [was released on 29/03/2011](https://wincent.com/wiki/Monit_5.2.5)... making it 5 years and 3 months old...

**Comment by dpb587-pivotal** [comment]
Just for reference, some existing issues and discussions on this topic for more context...

:link: merged PR, [Update monit to 5.2.5](https://github.com/cloudfoundry/bosh/pull/743)

:link: open PR, [Update monit to 5.14](https://github.com/cloudfoundry/bosh/pull/937)

 > It sounds like for now we can only update to 5.2.5. ([comment](https://github.com/cloudfoundry/bosh/pull/937#issuecomment-141506146))

:link: closed PR, [Upgrade to monit 5.8.1](https://github.com/cloudfoundry/bosh/pull/590)

 > In future we will move away from monit. That will allow us to cross platform (windows), more modular and hopefully less people would have to deal with monit annoyances. ([comment](https://github.com/cloudfoundry/bosh/pull/590#issuecomment-50842712))

**Comment by mtekel** [comment]
That comment about the future was made 2 years ago. The future is now!

It would be good if we could at least do some compatible update. I am not sure, but perhaps for some OS version, fixes of monit might have been backported to previous monit versions? I myself have experienced the 90s/90x restarts issue, which was not nice.

Regarding healthchecks - you now also use consul. And for consul you define healthchecks (if you want it to dynamically update service availability in its store/DNS). It would be great if monit _and_ consul could use the same healthchecks.

From other comments it seems like for some reason monit has been 'frozen' and there's no way/process/CI for you to upgrade it easily. I wonder what's behind this decision, as this seems to be quite important component wrt what BOSH does...

**Comment by jfmyers9** [comment]
At this time we are unable to update the version of `monit` due to a licensing change made by monit after `v.5.2.5`.

From other threads, our recommendation is to not rely heavily on `monit` features and hopefully we will be moving away from `monit` in the stemcell as a longer term goal.

Hopefully this helps.
