### ISSUE TITLE
Backup fails due to pg_dump version mismatch

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/bosh#1297]
When trying to run `bosh backup`, it fails with the following error:

```
Started backing up director > Backing up database. Failed: pg_dump exited 1, output: '', error: 'pg_dump: server version: 9.4.6; pg_dump version: 9.0.23
pg_dump: aborting because of server version mismatch
' (00:00:00)
```

We are using the following versions of BOSH:

```
$ bosh version
BOSH 1.3232.0

$ bosh status
[...]
Director
  Version    1.3215.3.0 (00000000)
  CPI        openstack_cpi
[...]
```

We are using Postgres 9.4, but the Director references package `postgres` (https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/spec#L25).

**Comment by allomov** [comment]
Hey @philippthun!

It appeared that in current release of BOSH postgresql server [has version 9.4.6](https://github.com/cloudfoundry/bosh/blob/300a93d4d87be2ebbd1ab4cbf2a843c0aff5c717/release/packages/postgres-9.4/spec#L4), but client libpq library [still has version 9.0.23](https://github.com/cloudfoundry/bosh/blob/3ca6c2c38887757f41dfb7971ea67bba90e6038f/release/packages/postgres/spec#L4). I am sure that BOSH team will fix it in upcoming releases.

If you have a strict requirement to use backup functionality, you can downgrade to `stable-3196` version (bosh release v254).

Thank you for making report for this error.

**Comment by cppforlife** [comment]
@philippthun we have made the fix https://github.com/cloudfoundry/bosh/commit/91a975355e5769ad06b374960c5ba61d914389bc but have not yet published new release. sorry for the inconvenience.

**Comment by dpb587-pivotal** [comment]
:link: someone also raised this issue in [cloudfoundry#bosh](https://cloudfoundry.slack.com/messages/bosh/) on [2016-06-09T14:27Z](https://cloudfoundry.slack.com/archives/bosh/p1465482450000322)

**Comment by cppforlife** [comment]
Closing. Fix available since v258+.
