### ISSUE TITLE
use compiled package cache as a fallback and ignore fetching errors

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/bosh#1300]
Hi,

We make use of the [compiled package cache](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=compiled_package_cache) feature and found out that bosh fails in any case of problem with this cache. Problems are that there is a S3 change in policy setting, user credentials or network issues. In the worst case a change in AWS can break all deployments.

Because of the cache is only an optimization I would like to suggest to handle issues with the cache as minor or warning issues and start compiling instead of break the deployment. 

WDYT?

Regards,
Stephan

**Comment by cppforlife** [comment]
@sklevenz sounds like a good suggestion.

**Comment by mfine30** [comment]
Given some roadmap items and the overall shift to moving towards compiled releases, this is not a big priority for us. I'm going to close it, but if you'd like to continue the conversation, feel free to reopen.
