### ISSUE TITLE
"Can't find link '<linkname>'" message on releases that support links

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1302]
I tried deploying Concourse CI v1.2.0 (and 1.3.0) to BOSH (release v255) on AWS, and got the following error:

```
Error 100: Error filling in template `tsa_ctl.erb' for `web/0' (line 20: undefined method `if_link' for #<Bosh::Template::EvaluationContext:0x007f1b8c1608d8>)
```

When I upgrade to a version of BOSH that supports links (v256 through the latest), and try to redeploy the manifest, I get the following error:

```
Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'web'. Errors are:
     - Unable to render templates for job 'atc'. Errors are:
       - Error filling in template 'atc_ctl.erb' (line 35: Can't find link 'db')
   - Unable to render jobs for instance group 'worker'. Errors are:
     - Unable to render templates for job 'groundcrew'. Errors are:
       - Error filling in template 'beacon_ctl.erb' (line 15: Can't find link 'tsa')
       - Error filling in template 'static_known_hosts.erb' (line 13: Can't find link 'tsa')
```

If I then `bosh delete deployment` and redeploy from scratch, it works. Is something causing the link-detection logic to be bypassed for existing deployments, resulting in finding missing links? Would this issue also show up if a link was added to a release being upgraded in an existing deployment?

**Comment by dpb587-pivotal** [comment]
This can happen if you uploaded the release on an older director which didn't understand the links v2 metadata. Try deleting and re-uploading the release to the director to ensure it has the latest metadata stored.

:link: [cloudfoundry#bosh@slack](https://cloudfoundry.slack.com/archives/bosh/p1459456579001178) - same issue showed up on slack a couple months ago

**Comment by cppforlife** [comment]
@geofffranks it does sound exactly what @dpb587-pivotal describes.

**Comment by friegger** [comment]
If the release cannot be deleted, because it is already in use by the deployment, one can do:
`bosh upload release <url> --fix`

**Comment by mfine30** [comment]
Given updates to the director and more modern directors, this is less likely to be an issue. I'm going to close this, but if it's still a problem, feel free to reopen.
