### ISSUE TITLE
Allow users to specify a default vcap/root password for VMs at a director level

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1308]
Right now, we can override the default vcap/root password on VMs by specifying `env.bosh.password` inside the resource pool definition. However, to enforce that all VMs deployed via BOSH have an overridden password, every resource pool in every deployment needs to have it specified.

Could a feature be added to have a default vcap password specified at the bosh director level, so that any VMs that don't specify a password in their resource pool definition get the default?

Precedence order:
hard-coded default < customized director default < resource-pool specific override

**Comment by cppforlife** [comment]
Will this do? https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=256.10#p=director.generate_vm_passwords

**Comment by geofffranks** [comment]
That doesn't allow users to know the vcap/root passwords after the fact, correct? That's the only downside I would see with that. Though, I only really ever need the vcap user/pass so I can get into a bosh director itself. I don't think I've ever needed to ssh into a VM without bosh being up, but perhaps someone might have a DR plan that required it for changing something quickly while the bosh director is offline.

For my immediate needs, the generate_vm_passwords setting should be fine, but this might be useful eventually? Or maybe Cloud Config makes that easier, since we can leverage spruce/spiff to templatize each resource pool and ensure they get the password overrides.

**Comment by cppforlife** [comment]
I think if such configuration is necessary [user_add addon](https://bosh.io/docs/addons-common.html#misc-users) can be used to add additional users.

**Comment by geofffranks** [comment]
Works for me
