### ISSUE TITLE
Allow `bosh -d` and `bosh deployment` to specify deployments by name as well as by file

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1312]
It would be very useful to be able to run arbitrary `bosh` commands specifying the deployment either by manifest file, or by deployment name (when users do not have manifests). 

Could the `bosh -d` and `bosh deployment` be updated to look for a file, and if not found, look for a deployment matching the provided value?

I'm open to any other possible solutions as well

**Comment by drnic** [comment]
Oh specifically "bosh ssh". Would love to be able to run that without the manifest.

**Comment by dpb587** [comment]
Great idea! Personally, I bet I would like the bosh CLI much better if it supported this sort of thing :)

**Comment by tjvman** [comment]
Closing, the behavior of `-d` and `deployment` has changed in the [new cli](https://github.com/cloudfoundry/bosh-cli)
