### ISSUE TITLE
Enable rsyslog omkafka module

### ISSUE THREAD

**Issue by tcnksm** [cloudfoundry/bosh#1313]
In [Rakuten](http://www.rakuten.com/), we use [Apache Kafka](http://kafka.apache.org/) with CloudFoundry.  To forward syslog to Kafka, we use [omkafka rsyslog module](http://www.rsyslog.com/doc/master/configuration/modules/omkafka.html) and configure omkafka via metron’s [`syslog_daemon_config.custom_rule`](https://github.com/cloudfoundry/loggregator/blob/develop/jobs/metron_agent/spec#L42_) property ( [Here](http://techblog.rakuten.co.jp/2016/01/28/rakuten-paas-kafka
) is detail blog post about this). 

To install omkafka module, we created a bosh job. In the bosh job, we build `omkafka.so` and `omkafka.la` in packaging phase and place them on the  `LD_LIBRARY_PATH `in `ctl` script. We execute this job on all VMs we run. This is kind of hacking way and difficult to maintain.  

So we thought it would be great if bosh stemcell supports omkafka module (We also think about building our own stemcell based on one but we concluded it’s also hard to catching up latest version every time). 

What I want to ask is it acceptable to send a PR to enable rsyslog module?  For compatibility point of view, it should not have a serious problem at all I think.

And as you may know, Apache Kafka is getting more and more popular for a component of building data pipeline and other CF users may want to use omkafka in future.

Thank you for taking account of this in advance.

**Comment by cppforlife** [comment]
@tcnksm i am curious to see how job/package turned out. mind sharing that somehow so that i can have something to play around with. (not sure why LD_LIBRARY_PATH is necessary. im pretty sure we can load in a syslog module with messing with library paths.)

i'm interested in including this in cloudfoundry/syslog-release and using it as an addon.

**Comment by tcnksm** [comment]
So your question is our way to install omkafka module by bosh job/package in more detail, right ?

In `packaging` script,  we rebuild rsyslog with enabling omkafka like below, 

```bash
...
./configure --prefix=/usr --enable-omkafka ...
make
```
After this, we can get `.la` and `.so` files and put them into install target, 

```bash
$ cp /usr/lib/rsyslog/omkafka.so ${BOSH_INSTALL_TARGET}/omkafka.so
$ cp /usr/lib/rsyslog/omkafka.la ${BOSH_INSTALL_TARGET}/omkafka.la
```

In job script, we just put them on `/usr/lib/rsyslog` directory,

```bash
$ ln -sf ${PACKAGE_DIR}/omkafka.so /usr/lib/rsyslog/omkafka.so
$ ln -sf ${PACKAGE_DIR}/omkafka.la /usr/lib/rsyslog/omkafka.la
```
Sorry, now we don't configure `LD_LIBRARY_PATH` (we did before). 

This is what we do now. But apparently if bosh stemcell enables omkafka when building rsyslog [here](https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/base_ubuntu_packages/apply.sh#L57). We can exclude these package/job script.

So we want to ask it's acceptable to put `--enable-omkafka` there.

**Comment by cppforlife** [comment]
@tcnksm i see, interesting. i think having it in a release (and installing it by specifying it as an addon) makes sense instead of maintaining it in the stemcell. is using it as an addon cause a problem?

we are *only* building rsyslog from source on powerpc stemcells. in other cases we use os package manager to install those packages [1].

[1] https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/base_ubuntu_packages/apply.sh#L28-L33

**Comment by giner** [comment]
@cppforlife following the link, is there any specific reason to build from source and not package source?
What I mean is that instead of
"wget ...; tar ...; ./configure; ./make; ..."
you might use
"apt-get build-dep pkgname; apt-get source pkgname; cd ...", make some changes if necessary and then "dpkg-buildpackage" and dpkg -i pkgfile.deb

About addon.
omkafka plugin must be used with the same version of rsyslog, librdkafka (and other external dependencies and there are any) it is build against otherwise it might be unstable or crash.

**Comment by giner** [comment]
Here is what we do now to build against proper versions:

- packages/librdkafka/packaging
``` 
#!/bin/bash

set -euo pipefail

# Available variables
# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package

LIBRDKAFKA_VERSION=0.8.6

TMP=$(mktemp --directory --tmpdir=$BOSH_COMPILE_TARGET)
LIBRDKAFKA_DIR=$TMP/librdkafka_src/

# Build and install librdkafka
mkdir -p $LIBRDKAFKA_DIR
tar -xf ${BOSH_COMPILE_TARGET}/librdkafka/librdkafka-${LIBRDKAFKA_VERSION}.tar.gz --strip-components=1  --directory $LIBRDKAFKA_DIR
cd $LIBRDKAFKA_DIR
./configure --prefix=${BOSH_INSTALL_TARGET}
make
make install
```
- packages/omkafka/packaging
```
# Available variables
# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package

# abort script on any command that exits with a non zero value
# and report the usage of uninitialized variables
set -euo pipefail

# Detect rsyslog version which is used for building omkafka module
OMKAFKA_VERSION=$(rsyslogd -v | head -n1 | grep -o '^rsyslogd 8\.[0-9]\+\.[0-9]\+,' | awk -F'[ ,]' '{ print $2 }')

# Detect versions of dependencies
LIBESTR_VERSION=$(dpkg-query -f '${Version}\n' -W libestr0 || true)
LIBJSON_C_VERSION=$(dpkg-query -f '${Version}\n' -W libjson-c2 || true)
LIBFASTJSON_VERSION=$(dpkg-query -f '${Version}\n' -W libfastjson || true)

# Install detected versions of dependencies to build rsyslog
DEBS=""
[ -n "$LIBESTR_VERSION" ] && DEBS="$DEBS ${BOSH_COMPILE_TARGET}/omkafka/libestr-dev_${LIBESTR_VERSION}_amd64.deb" || true
[ -n "$LIBJSON_C_VERSION" ] && DEBS="$DEBS ${BOSH_COMPILE_TARGET}/omkafka/libjson-c-dev_${LIBJSON_C_VERSION}_amd64.deb" || true
[ -n "$LIBFASTJSON_VERSION" ] && DEBS="$DEBS ${BOSH_COMPILE_TARGET}/omkafka/libfastjson-dev_${LIBFASTJSON_VERSION}_amd64.deb" || true
dpkg -i $DEBS

LIBRDKAFKA_DIR=/var/vcap/packages/librdkafka

TMP=$(mktemp --directory --tmpdir=$BOSH_COMPILE_TARGET)
DEST=$TMP/dest
RSYSLOG_DIR=$TMP/rsyslog_src/
LIBFASTJSON_DIR=$TMP/libfastjson_src/

# Build rsyslog (we only build it to have omkafka plugin)
mkdir -p $RSYSLOG_DIR
tar -xf ${BOSH_COMPILE_TARGET}/omkafka/rsyslog-${OMKAFKA_VERSION}.tar.gz --strip-components=1 --directory $RSYSLOG_DIR
cd $RSYSLOG_DIR
export CPATH=${LIBRDKAFKA_DIR}/include
export LIBRARY_PATH=${LIBRDKAFKA_DIR}/lib
./configure --prefix=/usr --enable-omkafka --disable-uuid --disable-liblogging-stdlog --disable-generate-man-pages
make
make DESTDIR=$DEST install

# Install omkafka plugin
cp $DEST/usr/lib/rsyslog/omkafka.so ${BOSH_INSTALL_TARGET}/omkafka.so
cp $DEST/usr/lib/rsyslog/omkafka.la ${BOSH_INSTALL_TARGET}/omkafka.la
```

**Comment by tcnksm** [comment]
@cppforlife 

> is using it as an addon cause a problem?

It's not a problem. But we need to run addon script on all VMs we manage. 
If omkafka is enabled by default, we don't need to run that every time and we don't need to maintain script.

**Comment by cppforlife** [comment]
@tcnksm I think keeping release packaging for now makes sense from stemcell maintenance perspective. Will re-evaluate in coming months while we improve syslog-release/rsyslog integration (and think about more default logging subsystem).

Out of curiosity how long does it take to compile?

cc @ajackson

**Comment by tcnksm** [comment]
> Will re-evaluate in coming months while we improve syslog-release/rsyslog integration (and think about more default logging subsystem).

That's great 👍

> Out of curiosity how long does it take to compile?

You mean time of package script ? I can not say exact time right now. But it's not that slow. 
(I will post here next time we run it )

**Comment by cppforlife** [comment]
Closing for now. Will keep an eye for a possible inclusion.
