### ISSUE TITLE
"Quick" test scripts that use Concourse need updates

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh#1314]
When attempting to run the unit and integration tests with the "quick" test scripts, I found they didn't work out of the box. They failed with mount issues:

```
$ DB=postgresql CONCOURSE_TARGET=lite ./quick-unit-tests.sh 
task outputs will be written to /var/folders/_9/_kxq8y357cnf7zf5rc2m5rsm0000gn/T/fly-exec2WUiq
task: test-unit...
targeting http://192.168.100.4:8080

executing build 4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.1M    0 63.1M    0     0  15.1M      0 --:--:--  0:00:04 --:--:-- 15.0M
initializing
running bosh-src/ci/tasks/test-unit.sh
Starting postgresql...
mount: permission denied
```

Also the `mktemp` command failed:

```
mktemp: too few X's in template ‘fly-exec’
```

But it doesn't look like it's relevant or needed? Maybe it should be removed? If not, just adding some X's to the stem would address it.

The mount failure can be addressed by adding the `-p` (privileged) flag on the fly command.

**Comment by dpb587-pivotal** [comment]
Hi - thanks for pointing this out! We discussed this, and because our team doesn't use these scripts and aren't planning on maintaining them when we change our CI tasks, we've gone ahead and removed them.

Instead, I'd recommend using the `rake fly:unit` and `rake fly:integration` tasks (which we do use internally). They also assume a `CONCOURSE_TARGET` environment variable, and you'll probably want to specify `CONCOURSE_TAG=` (empty value).

**Comment by sykesm** [comment]
Since you removed the scripts in 828d5c490483d219ee4102a7a02e8b38c26b7320, you should probably update the instructions that tell contributors how to execute tests as well.

[running_tests.md](https://github.com/cloudfoundry/bosh/blob/828d5c490483d219ee4102a7a02e8b38c26b7320/docs/running_tests.md) says:

> You can also use ./quick-unit-tests.sh to run all unit tests against a local Concourse CI instance.

and

> You can also use ./quick-integration-tests.sh to run all integration tests against a local Concourse CI instance.

Thanks.

**Comment by dpb587-pivotal** [comment]
Ah, forgot about those. Will update them on Monday. Thanks again!

**Comment by sykesm** [comment]
@dpb587-pivotal - Just a friendly reminder to update the doc. Thanks.

**Comment by dpb587-pivotal** [comment]
Ah, appreciated. Updated in https://github.com/cloudfoundry/bosh/commit/07e794792d843becdccd56d1f4e0b40511ac6c27, and thanks!
