### ISSUE TITLE
Please allow to limit orphaned disks to quota/size

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/bosh#1319]
We are creating Bosh deployments on the fly for various reasons (e.g. continuous integration, provisioning in productive environments). We know we can delete orphaned disks with `cleanup --all` and we can even delete them directly using your ReST API.
However, in some cases it makes really sense to preserve the orphaned disks, but since we can't control the amount of deployments, we regularly exceed our infrastructure quota. Setting the days to preserve the orphaned disks is not ideal as even if we reduce it, we may exceed our infrastructure quota if a lot is going on in the system at once.
It would be better, if we could define something like a quota/size for orphaned disks, e.g. to keep orphaned disks, but only if they don't exceed a certain disk space (configurable, e.g. 2 TB) and if exceeded start to delete orphaned disks by age (oldest first).
Would that be possible please? From the code it seems, it could be done with minimal effort. This extension would eliminate the risk that by having too many orphaned disks the entire infrastructure tenant becomes unusable, because disk quota is exceeded.

**Comment by cppforlife** [comment]
@vlerenc seems like you effectively want to turn this feature off. currently to come close to that you can set it to 0 days which means it would be GC-ed in the next half an hour (according to clean up schedule). even if we have disk size setting it will also be cleaned up within half an hour, so it's not much different from just setting it to 0 days.

**Comment by vlerenc** [comment]
@cppforlife I know I can set it to 0, but that isn't turning the feature off actually, because if there is a lot going on (CI landscape), it could still blow my quota, even if it is a comfortable quota.

I like to keep that feature active for productive landscapes, but I am fine if only x TBs are kept - in the limits of the quota (i.e. the money I am willing to pay) I have then as much safety as possible.

The problem with the days setting (even 0 as the GC may kick in too late) is that it doesn't reflect the infrastructure reality. The infrastructure reality is quota based (OpenStack, AWS, ...). So the orphan setting that reflects that best is likewise a quota, not a time window in days as I can't control what's happening in this time window (even if we talk about 30 minutes).

**Comment by cppforlife** [comment]
>  I am fine if only x TBs are kept

But cleanup to satisfy x TBs will also happen on schedule unless you are proposing bigger change to the Director that would do the cleanup inline.

**Comment by vlerenc** [comment]
Thank you @cppforlife. This would already help as it would reduce the time window in which the quota can blow up. But indeed, if the restrictions (days/quota) would be evaluated "inline" it would make the feature safer.

**Comment by mfine30** [comment]
Added [Pivotal Tracker #159805408](https://www.pivotaltracker.com/story/show/159805408) to track this
