### ISSUE TITLE
Error filling in template 'dea.yml.erb' (line 95: bad component(expected user component):

### ISSUE THREAD

**Issue by cpraveen412** [cloudfoundry/bosh#1320]
Hello All,
when i tried to deploy cloud foundry, I got below error. Could you please help me on this?

thank you

Error 100: Unable to render instance groups for deployment. Errors are:
Unable to render jobs for instance group 'runner_z1'. Errors are:
Unable to render templates for job 'dea_next'. Errors are:
Error filling in template 'dea.yml.erb' (line 95: bad component(expected user component):

**Comment by allomov** [comment]
It looks more like issue with properties in manifest deployment, I've answered you in your issue in [cf-release](https://github.com/cloudfoundry/cf-release/issues/992#issuecomment-228770014). imo there should be only one place with this issue and you can close this one.
