### ISSUE TITLE
`watch monit summary` causes strange failure when updating job

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1330]
I have an instance group with 4 jobs, and during a fresh deploy, on one of the instances, several of the jobs were not running after update.  I SSH'd on right away and they were running.  (As a side note, I did this a few times, sometimes I would catch them in the "Does not exist" state briefly, but then they'd be running.  I thought I could fix this by increasing the watch times, but didn't help.)

So to see what was happening I tried SSH'ing on after the deploy failed, doing a `watch monit summary`, then redoing the `bosh deploy`.  Can't fully recall what I saw, looked like all the monit processes were shut down properly (showed `not monitored`) but then I expected to see the processes get restarted/recreated.  Instead, I just saw something like:

```
Warning: include files not found '/var/vcap/monit/job/*.monitrc'
```

and it only showed the system process in the `running` state.

**Comment by cppforlife** [comment]
This is expected from monit since we remove all monit configurations (aside from builtin system one) between stops and starts.
