### ISSUE TITLE
symlinks under `src/` not followed/included for BOSH packaging

### ISSUE THREAD

**Issue by teddyking** [cloudfoundry/bosh#1332]
Just ran into a situation where files pointed at by a symlink under the `src/` dir were not added to the compilation VM, even though we specified the files in the package's `spec` file.

For example:

```
$ pwd

/Users/pivotal/workspace/garden-runc-release # bosh release directory
```

```
$ cat packages/runc/spec

---
name: runc

dependencies:
  - libseccomp
  - golang_1.6.1

files:
  - github.com/opencontainers/runc/**/* # include everything under src/github.com/opencontainers/runc/
```

```
$ ls -lah src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/

total 8
drwxr-xr-x   4 pivotal  staff   136B May 11 16:52 .
drwxr-xr-x  13 pivotal  staff   442B Jul  4 09:55 ..
lrwxr-xr-x   1 pivotal  staff    79B May 11 16:52 runc -> /Users/pivotal/workspace/garden-runc-release/src/github.com/opencontainers/runc
drwxr-xr-x   4 pivotal  staff   136B Apr 22 12:05 runtime-spec
```

The symlinked files under `src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc` do not make it to the compilation VM.

Is this expected behaviour or is this a bug?

Cheers,
Ed

**Comment by cppforlife** [comment]
@teddyking this is expected -- for packaging symlink files themselves.

**Comment by dpb587-pivotal** [comment]
Closing - sounds expected, but symlinking methods have changed slightly in the [new CLI](https://github.com/cloudfoundry/bosh-cli). Feel free to give that a try and start providing feedback in that repo. Ruby CLI code is frozen.
