### ISSUE TITLE
Release 'cf' not found on director. Unable to resolve 'latest' alias in manifest.

### ISSUE THREAD

**Issue by YuPengZTE** [cloudfoundry/bosh#1334]
root@bosh-lite:/home/vagrant/contribute/cf-release# bosh create release
Syncing blobs...

Building DEV release
---------------------------------
Release artifact cache: /root/.bosh/cache

Building license
----------------
Building license...
  Using final version '861d82c0d9745784acfcd026ccf44e942579824a'

Building packages
-----------------
Building smoke-tests...
  Using final version '7549c4b297608d27501c6972d1a1c3fc332ac750'

Building gnatsd...
  Using final version 'f1af48ea824ef64c751da0c8fa4c9660c4cb9cdd'

Building nginx...
  Using final version 'b7c8aadb18d53f81a7455e447c5941313872b81d'

Building ruby-2.1.8...
  Using final version '0a758a4dc3408937b64f89aaa39f8ee25cce5454'

Building nats-common...
  Using final version '1f712a21c0b1cbb3b547eccc79eb159aaee48b99'

Building staticfile-buildpack...
  Using final version '16fdace8cb282ef9c154c0abc0e1c5493fca0e30'

Building go-buildpack...
  Using final version 'c2c06116e228833dd1f44915691bdfea977dc04b'

Building python-buildpack...
  Using final version '2349c17ede42a810208662b9b0456b534422b808'

Building routing_utils...
  Using final version '197be7c60198c3a679b111d2d1e3d7af24ec08a6'

Building capi_utils...
  Using final version 'f0746a954b2d4ab7bf905b8bc742584801e21357'

Building consul...
  Using final version '786f3d52dcbb785f523f3b39b172b9b7e2a9c148'

Building stager...
  Using final version '7d1cb08cab5995f857f6fe3c41f272ce6703a59a'

Building nginx_webdav...
  Using final version 'ee1d48cbce7f78f1395b12837a500c11e5066fa7'

Building route_registrar...
  Using final version '2ec8e115fd10d508f4c96123c92400dfef5ec801'

Building debian_nfs_server...
  Using final version 'aac05f22582b2f9faa6840da056084ed15772594'

Building etcd...
  Using final version '015a370c4578c19dd3578329477b1f1a549f0c60'

Building loggregator_trafficcontroller...
  Using final version 'ccf5540a1a825b32f7cd39e850ae70500dff77a3'

Building nodejs-buildpack...
  Using final version 'b8601eca1061406214db95b5319b84e5150e2a8a'

Building php-buildpack...
  Using final version '8807a71c61d8a26301fd0067aebf1aaf60c47594'

Building cli...
  Using final version '0f19a1df7ef777208cc3bfcdc875b2b56613ab40'

Building nats...
  Using final version '9da10677048bd8c1237ae5f14ffe6be34ad16def'

Building binary-buildpack...
  Using final version 'c44701a411a078710c07025a4536ea94e0a4cf70'

Building metron_agent...
  Using final version 'de115ca3c7dc968f5b8e654f635b5c4bcd3b2bf5'

Building golang1.5...
  Using final version '73d2dfd26bf1136e2cd3d460a1043668dca5725a'

Building blobstore_url_signer...
  Using final version '09ff302425c2edda6bc8c6275585cc86acffa473'

Building etcd_metrics_server...
  Using final version '91d58980775f626ed771488e7d0332b2613f3f6d'

Building ruby-buildpack...
  Using final version '9d6eef80a4d9917c932fe2ed8d1d50b2651d4ff3'

Building cc_uploader...
  Using final version '8d4e2c38c0631d019adff01ec1a59106996d1254'

Building dea_next...
  Using final version '8c276c6c796a777b7443bbaacacccdf56f8a2608'

Building doppler...
  Using final version 'd5e9a3299aa9bf06bc4b5e6fb9e5e736a5053a9a'

Building confab...
  Using final version 'b81eb066665668ef14c8725f6169fa3ba0b4a84d'

Building haproxy...
  Using final version 'f5d89b125a66892628a8cd61d23be7f9b0d31171'

Building tps...
  Using final version '63d1150497d1bd4a2edb60d3b1736f98571f5c12'

Building rootfs_cflinuxfs2...
  Using final version 'ceae1d8453eb4ea8f18979c59a0816746abbd0fe'

Building loggregator_common...
  Using final version '6e89e9e4c155576dfc47b5959887807831ddf2df'

Building etcd-common...
  Using final version '0f365b3a98184c2a6537efd51f67e8d5e9d2c486'

Building nginx_newrelic_plugin...
  Using final version '2de1c5ba9dec62be54c9ff4ed3b32a126463e0d8'

Building hm9000...
  Using final version '478e01f02e17cdc8700b7f596ccce86fcc468382'

Building etcd-dns-checker...
  Using final version '9676918944de93dd773b706cc7ecc68073492372'

Building uaa_utils...
  Using final version 'fc2e416c5af94d6293ac70bb594c984e31097fb7'

Building nsync...
  Using final version '94ebe985101dba60c281365bc031422e1b84ca70'

Building dea_logging_agent...
  Using final version '001d5ac5148b21224aba31b13c4c63ab317a70d8'

Building uaa...
  Using final version 'f73fad99b72013a94239d1a0e7cc2abbd5bc4247'

Building buildpack_java_offline...
  Using final version '9515914b0b721805a65b9610ea8d8fd76396f08a'

Building statsd-injector...
  Using final version 'd289b6582aa579fc15d419e4f3923205a938e95e'

Building buildpack_java...
  Using final version '236dcbff7cede91099765856b6e26cb42692e6f3'

Building syslog_drain_binder...
  Using final version '159d235514f78d9aeace810986a954095e51e78d'

Building golang1.6...
  Using final version '85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8'

Building postgres-9.4.6...
  Using final version '4ca292f2443cfc682e87632ebd15fb3f3fa53123'

Building cloud_controller_ng...
  Using final version 'b460066ea0bfd9d2106228a0f9c45dc228548787'

Building libpq...
  Using final version '36290c252abdd5750583eca92a8c4fd134594fa8'

Building ruby-2.3...
  Using final version 'debd726c1edb8dea8654bb3c46539a4ee75bff75'

Building common...
  Using final version '953ccbc1b39fc972d2b4903beb16af7daf78cc85'

Building ruby-2.2.5...
  Using final version '33d7f66f46dff60f8aa224cfe2d65ea1e7a0653c'

Building acceptance-tests...
  Using final version '83cfdc1ebb835d2c87f0fe2c3cf0a4155b6bc396'

Building libmariadb...
  Using final version '90d7836132e02bb570d91f08c9e116c394888d75'

Building gorouter...
  Using final version 'c8b205401a01c37c302b98d8c6e65cb5662e8b7b'

Building collector...
  Using final version '9f8dfbcbcfffb124820327ad2ad4fee35e51d236'

Building warden...
  Using final version 'fe6b989f204edcbab3713df2f082cd9f069dccb7'

Resolving dependencies
----------------------
Dependencies resolved, correct build order is:
- binary-buildpack
- buildpack_java
- buildpack_java_offline
- capi_utils
- cli
- common
- consul
- debian_nfs_server
- etcd-common
- go-buildpack
- golang1.5
- golang1.6
- haproxy
- libmariadb
- libpq
- loggregator_common
- nats-common
- nginx
- nginx_webdav
- nodejs-buildpack
- php-buildpack
- postgres-9.4.6
- python-buildpack
- rootfs_cflinuxfs2
- routing_utils
- ruby-2.1.8
- ruby-2.2.5
- ruby-2.3
- ruby-buildpack
- staticfile-buildpack
- uaa
- uaa_utils
- smoke-tests
- gorouter
- route_registrar
- acceptance-tests
- blobstore_url_signer
- cc_uploader
- confab
- dea_logging_agent
- doppler
- etcd
- etcd-dns-checker
- etcd_metrics_server
- gnatsd
- hm9000
- loggregator_trafficcontroller
- metron_agent
- nsync
- stager
- statsd-injector
- syslog_drain_binder
- tps
- collector
- nats
- cloud_controller_ng
- dea_next
- nginx_newrelic_plugin
- warden

Building jobs
-------------
Building smoke-tests...
  Using final version '759607fd96cc92dffee95f57c6688a60c05f4d30'

Building nats_stream_forwarder...
  Using final version '46f3801b194edf0116ac36b4afb96032f0362fe9'

Building staticfile-buildpack...
  Using final version '6031f7be3c42493fd3e147de50ee109d83f483c1'

Building postgres...
  Using final version '56e079561020524e156f7f8254b1c4228ab0bd81'

Building go-buildpack...
  Using final version '6a96c195d72160f64d4624612c235fe0142f0a42'

Building nfs_mounter...
  Using final version '2cd5a8f93bbeec01b82ea552c56933c0e078778c'

Building python-buildpack...
  Using final version 'c3ebd738c93c1dba9274c435022da84377f23639'

Building stager...
  Using final version '60d1f0773f0f0a8d4946bb1338e7361b9c3f662a'

Building route_registrar...
  Using final version '60110d700ae15a5789c69b8cc44aac5ff11809f7'

Building blobstore...
  Using final version '56ae4955a6509a1ffa5ae81f5d2503a0f0bd2767'

Building debian_nfs_server...
  Using final version '8c6159eca06f8b8dfbea48f9885340ba2fca6baf'

Building etcd...
  Using final version '82302ab1804781dd95d1ca42969875c7bd117d4d'

Building cloud_controller_worker...
  Using final version '2b84746535f39ddfdf0563506331dcfe36409772'

Building loggregator_trafficcontroller...
  Using final version 'b8c7d27d67cebdd05dbf1248f4361c829d802766'

Building nodejs-buildpack...
  Using final version '4c9350acbe70b71e8f851d16b6a24fd6074a7400'

Building php-buildpack...
  Using final version '29d809f43b59ffc3c2a14ac3888d7b20eb869c67'

Building java-offline-buildpack...
  Using final version 'baba85203f19cb43788847dc5b06f4cb594e63fe'

Building nats...
  Using final version '87cbe4b9fd08fa9940983a2d042e709a1f521660'

Building binary-buildpack...
  Using final version 'e2753ad7c384717801a27475b99bdea16669685d'

Building metron_agent...
  Using final version '902a847a9dd28141bf78ebf584ef94b09a3836c6'

Building etcd_metrics_server...
  Using final version '08dca0d781c365a475c406c344a032ec352649c4'

Building ruby-buildpack...
  Using final version '5c7e00c6e3deacb08ee95798a9194055bedbf246'

Building cc_uploader...
  Using final version '70c04fc466916e999109d0c9e9dfa448e8b6d5f3'

Building dea_next...
  Using final version 'd2264cedac999208474451838a5e2e89257fb896'

Building doppler...
  Using final version 'd756abb0896e9a40f7dc26e7755756227258be49'

Building consul_agent...
  Using final version 'a039219ec0e1a98ced2aec7f45286a99980b5670'

Building haproxy...
  Using final version '4f3ec0a3095526957c51ce9320fe4d0294d9e85a'

Building tps...
  Using final version 'fbec0883ddba30e77df453f98b0a8f99cd76e3c6'

Building cloud_controller_clock...
  Using final version 'b523882080682f308813804d3063feb83e322dc1'

Building java-buildpack...
  Using final version '3129e468525792deb8d482d5fea6bed79c585f95'

Building hm9000...
  Using final version '8785ef9ddc2dee4b4ab2533477858c58f7fbf7ab'

Building nsync...
  Using final version '4b1882ac9b399b9723f9322dca72359b7eb41109'

Building dea_logging_agent...
  Using final version '59de9485646549194e501ce2878449842943020c'

Building uaa...
  Using final version 'dcff8b06b46ef9efee25edeffe2d72c3b6a8e38f'

Building statsd-injector...
  Using final version '7bb836cf603a4084493d1cc0bb5403b867c0dc15'

Building syslog_drain_binder...
  Using final version 'e61f420765c1390543216f8f321ccfd78e292061'

Building cloud_controller_ng...
  Using final version 'f49368a1f09f87a79f15738c8141bdafb66a49fc'

Building acceptance-tests...
  Using final version '7f0c7747468b54a57c5d2d931c0bb697a8e47388'

Building gorouter...
  Using final version '2bcb9a29c21a016ca6030b113c7889304a7186b9'

Building collector...
  Using final version '6c210292f18d129e9a037fe7053836db2d494344'

Building release
----------------

Generating manifest...
----------------------
Writing manifest...

Release summary
---------------
License
+---------+------------------------------------------+-------+
| Name    | Version                                  | Notes |
+---------+------------------------------------------+-------+
| license | 861d82c0d9745784acfcd026ccf44e942579824a |       |
+---------+------------------------------------------+-------+

Packages
+-------------------------------+------------------------------------------+-------+
| Name                          | Version                                  | Notes |
+-------------------------------+------------------------------------------+-------+
| smoke-tests                   | 7549c4b297608d27501c6972d1a1c3fc332ac750 |       |
| gnatsd                        | f1af48ea824ef64c751da0c8fa4c9660c4cb9cdd |       |
| nginx                         | b7c8aadb18d53f81a7455e447c5941313872b81d |       |
| ruby-2.1.8                    | 0a758a4dc3408937b64f89aaa39f8ee25cce5454 |       |
| nats-common                   | 1f712a21c0b1cbb3b547eccc79eb159aaee48b99 |       |
| staticfile-buildpack          | 16fdace8cb282ef9c154c0abc0e1c5493fca0e30 |       |
| go-buildpack                  | c2c06116e228833dd1f44915691bdfea977dc04b |       |
| python-buildpack              | 2349c17ede42a810208662b9b0456b534422b808 |       |
| routing_utils                 | 197be7c60198c3a679b111d2d1e3d7af24ec08a6 |       |
| capi_utils                    | f0746a954b2d4ab7bf905b8bc742584801e21357 |       |
| consul                        | 786f3d52dcbb785f523f3b39b172b9b7e2a9c148 |       |
| stager                        | 7d1cb08cab5995f857f6fe3c41f272ce6703a59a |       |
| nginx_webdav                  | ee1d48cbce7f78f1395b12837a500c11e5066fa7 |       |
| route_registrar               | 2ec8e115fd10d508f4c96123c92400dfef5ec801 |       |
| debian_nfs_server             | aac05f22582b2f9faa6840da056084ed15772594 |       |
| etcd                          | 015a370c4578c19dd3578329477b1f1a549f0c60 |       |
| loggregator_trafficcontroller | ccf5540a1a825b32f7cd39e850ae70500dff77a3 |       |
| nodejs-buildpack              | b8601eca1061406214db95b5319b84e5150e2a8a |       |
| php-buildpack                 | 8807a71c61d8a26301fd0067aebf1aaf60c47594 |       |
| cli                           | 0f19a1df7ef777208cc3bfcdc875b2b56613ab40 |       |
| nats                          | 9da10677048bd8c1237ae5f14ffe6be34ad16def |       |
| binary-buildpack              | c44701a411a078710c07025a4536ea94e0a4cf70 |       |
| metron_agent                  | de115ca3c7dc968f5b8e654f635b5c4bcd3b2bf5 |       |
| golang1.5                     | 73d2dfd26bf1136e2cd3d460a1043668dca5725a |       |
| blobstore_url_signer          | 09ff302425c2edda6bc8c6275585cc86acffa473 |       |
| etcd_metrics_server           | 91d58980775f626ed771488e7d0332b2613f3f6d |       |
| ruby-buildpack                | 9d6eef80a4d9917c932fe2ed8d1d50b2651d4ff3 |       |
| cc_uploader                   | 8d4e2c38c0631d019adff01ec1a59106996d1254 |       |
| dea_next                      | 8c276c6c796a777b7443bbaacacccdf56f8a2608 |       |
| doppler                       | d5e9a3299aa9bf06bc4b5e6fb9e5e736a5053a9a |       |
| confab                        | b81eb066665668ef14c8725f6169fa3ba0b4a84d |       |
| haproxy                       | f5d89b125a66892628a8cd61d23be7f9b0d31171 |       |
| tps                           | 63d1150497d1bd4a2edb60d3b1736f98571f5c12 |       |
| rootfs_cflinuxfs2             | ceae1d8453eb4ea8f18979c59a0816746abbd0fe |       |
| loggregator_common            | 6e89e9e4c155576dfc47b5959887807831ddf2df |       |
| etcd-common                   | 0f365b3a98184c2a6537efd51f67e8d5e9d2c486 |       |
| nginx_newrelic_plugin         | 2de1c5ba9dec62be54c9ff4ed3b32a126463e0d8 |       |
| hm9000                        | 478e01f02e17cdc8700b7f596ccce86fcc468382 |       |
| etcd-dns-checker              | 9676918944de93dd773b706cc7ecc68073492372 |       |
| uaa_utils                     | fc2e416c5af94d6293ac70bb594c984e31097fb7 |       |
| nsync                         | 94ebe985101dba60c281365bc031422e1b84ca70 |       |
| dea_logging_agent             | 001d5ac5148b21224aba31b13c4c63ab317a70d8 |       |
| uaa                           | f73fad99b72013a94239d1a0e7cc2abbd5bc4247 |       |
| buildpack_java_offline        | 9515914b0b721805a65b9610ea8d8fd76396f08a |       |
| statsd-injector               | d289b6582aa579fc15d419e4f3923205a938e95e |       |
| buildpack_java                | 236dcbff7cede91099765856b6e26cb42692e6f3 |       |
| syslog_drain_binder           | 159d235514f78d9aeace810986a954095e51e78d |       |
| golang1.6                     | 85a489b7c0c2584aa9e0a6dd83666db31c6fc8e8 |       |
| postgres-9.4.6                | 4ca292f2443cfc682e87632ebd15fb3f3fa53123 |       |
| cloud_controller_ng           | b460066ea0bfd9d2106228a0f9c45dc228548787 |       |
| libpq                         | 36290c252abdd5750583eca92a8c4fd134594fa8 |       |
| ruby-2.3                      | debd726c1edb8dea8654bb3c46539a4ee75bff75 |       |
| common                        | 953ccbc1b39fc972d2b4903beb16af7daf78cc85 |       |
| ruby-2.2.5                    | 33d7f66f46dff60f8aa224cfe2d65ea1e7a0653c |       |
| acceptance-tests              | 83cfdc1ebb835d2c87f0fe2c3cf0a4155b6bc396 |       |
| libmariadb                    | 90d7836132e02bb570d91f08c9e116c394888d75 |       |
| gorouter                      | c8b205401a01c37c302b98d8c6e65cb5662e8b7b |       |
| collector                     | 9f8dfbcbcfffb124820327ad2ad4fee35e51d236 |       |
| warden                        | fe6b989f204edcbab3713df2f082cd9f069dccb7 |       |
+-------------------------------+------------------------------------------+-------+

Jobs
+-------------------------------+------------------------------------------+-------+
| Name                          | Version                                  | Notes |
+-------------------------------+------------------------------------------+-------+
| smoke-tests                   | 759607fd96cc92dffee95f57c6688a60c05f4d30 |       |
| nats_stream_forwarder         | 46f3801b194edf0116ac36b4afb96032f0362fe9 |       |
| staticfile-buildpack          | 6031f7be3c42493fd3e147de50ee109d83f483c1 |       |
| postgres                      | 56e079561020524e156f7f8254b1c4228ab0bd81 |       |
| go-buildpack                  | 6a96c195d72160f64d4624612c235fe0142f0a42 |       |
| nfs_mounter                   | 2cd5a8f93bbeec01b82ea552c56933c0e078778c |       |
| python-buildpack              | c3ebd738c93c1dba9274c435022da84377f23639 |       |
| stager                        | 60d1f0773f0f0a8d4946bb1338e7361b9c3f662a |       |
| route_registrar               | 60110d700ae15a5789c69b8cc44aac5ff11809f7 |       |
| blobstore                     | 56ae4955a6509a1ffa5ae81f5d2503a0f0bd2767 |       |
| debian_nfs_server             | 8c6159eca06f8b8dfbea48f9885340ba2fca6baf |       |
| etcd                          | 82302ab1804781dd95d1ca42969875c7bd117d4d |       |
| cloud_controller_worker       | 2b84746535f39ddfdf0563506331dcfe36409772 |       |
| loggregator_trafficcontroller | b8c7d27d67cebdd05dbf1248f4361c829d802766 |       |
| nodejs-buildpack              | 4c9350acbe70b71e8f851d16b6a24fd6074a7400 |       |
| php-buildpack                 | 29d809f43b59ffc3c2a14ac3888d7b20eb869c67 |       |
| java-offline-buildpack        | baba85203f19cb43788847dc5b06f4cb594e63fe |       |
| nats                          | 87cbe4b9fd08fa9940983a2d042e709a1f521660 |       |
| binary-buildpack              | e2753ad7c384717801a27475b99bdea16669685d |       |
| metron_agent                  | 902a847a9dd28141bf78ebf584ef94b09a3836c6 |       |
| etcd_metrics_server           | 08dca0d781c365a475c406c344a032ec352649c4 |       |
| ruby-buildpack                | 5c7e00c6e3deacb08ee95798a9194055bedbf246 |       |
| cc_uploader                   | 70c04fc466916e999109d0c9e9dfa448e8b6d5f3 |       |
| dea_next                      | d2264cedac999208474451838a5e2e89257fb896 |       |
| doppler                       | d756abb0896e9a40f7dc26e7755756227258be49 |       |
| consul_agent                  | a039219ec0e1a98ced2aec7f45286a99980b5670 |       |
| haproxy                       | 4f3ec0a3095526957c51ce9320fe4d0294d9e85a |       |
| tps                           | fbec0883ddba30e77df453f98b0a8f99cd76e3c6 |       |
| cloud_controller_clock        | b523882080682f308813804d3063feb83e322dc1 |       |
| java-buildpack                | 3129e468525792deb8d482d5fea6bed79c585f95 |       |
| hm9000                        | 8785ef9ddc2dee4b4ab2533477858c58f7fbf7ab |       |
| nsync                         | 4b1882ac9b399b9723f9322dca72359b7eb41109 |       |
| dea_logging_agent             | 59de9485646549194e501ce2878449842943020c |       |
| uaa                           | dcff8b06b46ef9efee25edeffe2d72c3b6a8e38f |       |
| statsd-injector               | 7bb836cf603a4084493d1cc0bb5403b867c0dc15 |       |
| syslog_drain_binder           | e61f420765c1390543216f8f321ccfd78e292061 |       |
| cloud_controller_ng           | f49368a1f09f87a79f15738c8141bdafb66a49fc |       |
| acceptance-tests              | 7f0c7747468b54a57c5d2d931c0bb697a8e47388 |       |
| gorouter                      | 2bcb9a29c21a016ca6030b113c7889304a7186b9 |       |
| collector                     | 6c210292f18d129e9a037fe7053836db2d494344 |       |
+-------------------------------+------------------------------------------+-------+

Release name: baseCF
Release version: 0+dev.3
Release manifest: /home/vagrant/contribute/cf-release/dev_releases/baseCF/baseCF-0+dev.3.yml
root@bosh-lite:/home/vagrant/contribute/cf-release# bosh update release
Unknown command: update release
root@bosh-lite:/home/vagrant/contribute/cf-release# bosh upload release
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'Bosh Lite Director'

Copying packages
----------------

Copying jobs
------------
smoke-tests
nats_stream_forwarder
staticfile-buildpack
postgres
go-buildpack
nfs_mounter
python-buildpack
stager
route_registrar
blobstore
debian_nfs_server
etcd
cloud_controller_worker
loggregator_trafficcontroller
nodejs-buildpack
php-buildpack
java-offline-buildpack
nats
binary-buildpack
metron_agent
etcd_metrics_server
ruby-buildpack
cc_uploader
dea_next
doppler
consul_agent
haproxy
tps
cloud_controller_clock
java-buildpack
hm9000
nsync
dea_logging_agent
uaa
statsd-injector
syslog_drain_binder
cloud_controller_ng
acceptance-tests
gorouter
collector

Copying license
---------------
license

Generated /tmp/d20160705-27598-1mhrd1p/d20160705-27598-1orn1fo/release.tgz
Release size: 189.9K

Verifying manifest...
Extract manifest                                             OK
Manifest exists                                              OK
Release name/version                                         OK

Uploading release
release.tgz:    96% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo   | 182.9KB   2.0MB/s ETA:  00:00:00
Director task 15
  Started extracting release > Extracting release. Done (00:00:00)

  Started verifying manifest > Verifying manifest. Done (00:00:00)

  Started resolving package dependencies > Resolving package dependencies. Done (00:00:00)

  Started processing 59 existing packages > Processing 59 existing packages. Done (00:00:00)

  Started processing 40 existing jobs > Processing 40 existing jobs. Done (00:00:00)

  Started release has been created > baseCF/0+dev.3. Done (00:00:00)

Task 15 done

Started         2016-07-05 08:27:55 UTC
Finished        2016-07-05 08:27:56 UTC
Duration        00:00:01
release.tgz:    96% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo   | 182.9KB  53.4KB/s Time: 00:00:03

Release uploaded
root@bosh-lite:/home/vagrant/contribute/cf-release# bosh deploy
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Getting deployment properties from director...
Unable to get properties list from director, trying without it...
**Release 'cf' not found on director. Unable to resolve 'latest' alias in manifest.**
root@bosh-lite:/home/vagrant/contribute/cf-release#

**Comment by voelzmo** [comment]
It seems like you put in `baseCF` as a name when creating the release, but your deployment manifest references a release called `cf`. As a solution, you could just keep `cf` as a name when asked by `bosh create release` or adapt the release's name in your deployment manifest used in `bosh deploy`.

**Comment by YuPengZTE** [comment]
Thank you @voelzmo
