### ISSUE TITLE
Bosh_cli should use host when available not ip for requests

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bosh#1338]
We've got 15 or so boshes we need to deploy and we'd like to uaa enable them all.  To UAA enable bosh it requires ssl enabling bosh as well as uaa.  The current instructions [0] for enabling bosh ssl imply the use of an ip address for the subject of the cert.

We'd like to use a wildcard cert that we can apply to all of our boshes instead of creating a set of ip address certs for each bosh.  However, this doesn't work since it appears bosh_cli always uses the ip address in director requests [1] [2].

Any thoughts on changing this behavior so that bosh will simply use the url provided at target time so that wildcard certs will work?

Thanks.

[0] https://bosh.io/docs/director-certs.html
[1] https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/client/director.rb#L32
[2] https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/client/director.rb#L763

**Comment by cppforlife** [comment]
@youngm seems reasonable.

**Comment by youngm** [comment]
@cppforlife Great!  Unfortunately we've already worked around the problem.  So, I may not have time to contribute a fix for a while.  In the meantime I'll let you decide if you want to leave the issue open or close it.  

Thanks,
Mike

**Comment by dpb587-pivotal** [comment]
Nowadays, the new [bosh CLI](https://github.com/cloudfoundry/bosh-cli) will respect the original target, so wildcard certs should work as expected. Hopefully you can give it a try, and feel free to open a new issue in that repo if you run into any issues. Since the ruby CLI is frozen, I'm going to close this issue.
