### ISSUE TITLE
Stemcell: Increase root_maxkeys and maxkeys

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1340]
In the current 3262.2 stemcell, `root_maxkeys` and `maxkeys` are set to 500 (you can see the values in `/proc/sys/kernel/keys/root_maxkeys`). This number is fairly low if you want to use stemcell as base for concourse worker, which can launch a lot of containers. Most of them are quite small, short lived or could be even no-op (just started and then shut down), but there's a lot of them. The low `root_maxkeys` combined with large number of containers then hits this docker issue: https://github.com/docker/docker/issues/22865

Which interferes with concourse worker functionality (as it is unable to import containers for tasks).

I am not 100% sure what the good value is. In the docker issue thread they suggest numbers as high as 1 million. I'd say that for now 10K would seem OK...

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/127320133

**Comment by dpb587-pivotal** [comment]
Committed to develop via 3e7d904b7b478c5d1762d2faf372e96ecec2167a

**Comment by mtekel** [comment]
Indeed this is now present in the recent stemcells.
