### ISSUE TITLE
Instructions for SSL setup work on mac only, not on linux

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1349]
The scripts provided at http://bosh.io/docs/director-certs.html only provide working private keys for the certificates, if executed on Mac OS. If you execute it on Linux, it doesn't produce correct keys. You have to run `openssl rsa -in uaa-web.key -out uaa-web.rsa.key` and `openssl rsa -in uaa-sp.key -out uaa-sp.rsa.key` to convert them properly.

This is probably due to different versions of openssl on both Operating Systems. Maybe we can find scripts working on both envs?

**Comment by cppforlife** [comment]
@voelzmo PR?

**Comment by mfine30** [comment]
@voelzmo I believe this was before vars so the CLI can dynamically generate its own certs. I'm going to close this issue.
