### ISSUE TITLE
upload stemcell with --skip-if-exists gives 'name and version unique' error during race condition

### ISSUE THREAD

**Issue by sax** [cloudfoundry/bosh#1358]
I have a Concourse pipeline where I have two bosh deployments onto the same director. They could be run in parallel, except that they both try to upload the same stemcell. When either deployment checks for the existence of the stemcell, it does not exist. One of them then succeeds in uploading the stemcell, and the other errors out with 'name and version unique'.

When the `--skip-if-exists` flag is passed, my expectation is that this case would be fine. My expectation is that both uploads would succeed, perhaps with a warning for the second one (though not necessary).

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/118979067

**Comment by sax** [comment]
Awesome, thank you for the link. I searched around before filing, but obviously not enough. I'll close this issue in favor of #1169.
