### ISSUE TITLE
Bosh doesn't upload releases specified in runtime config

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1364]
When you specify a release in runtime config, including URL and SHA, bosh doesn't download the release. If you copy-paste same release specification into a manifest, bosh does download the release.

It would be nice if bosh preserved release fetch functionality for runtime config as well.

Bosh version 1.3215.3.0

**Comment by cppforlife** [comment]
sounds like a good consistent thing to implement.

**Comment by cppforlife** [comment]
@mtekel any opinion on "version" key behavior of runtime config. currently it doesnt support latest. do you think we should support it? should it be resolved at `update runtime config` time?

**Comment by mtekel** [comment]
Hi,

I am not sure about the "latest". We don't use it much (...at all). I don't have insight into BOSH internals to say how much effort it would be to implement it. From the user point of view it would be nice if things were consistent (that is, I can copy-paste my release specification from manifest into runtime for things I deploy on each VM). 

Also, it would be nice if there were no issues for versions that are numbers (that is, to handle them explicitly as string, to avoid things like https://github.com/cloudfoundry/bosh/issues/1180 - we have experienced this for collectd version in runtime config).

**Comment by jfmyers9** [comment]
Hi all,

This appears to have been implemented. If you include a `url:` in the release block, the release will be uploaded to the director when running `bosh update-runtime-config`.

Best,

@jfmyers9
