### ISSUE TITLE
suggestion: allow packages to opt out of compilation

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1368]
Some packages don't really need a compilation phase, and are essentially forced to write a packaging script which simply copies files.  On some IaaSes, this could mean 8 minutes end-to-end to spin up a VM, download and untar the package, have the packaging script run `cp` to move things from the untarred package to the `${BOSH_INSTALL_TARGET}`, tar and upload the compiled package, and tear down the VM.

Could BOSH support a way of opting out of this?  As a strawman proposal, a package without a packaging script could skip the compilation stage, and the package tarball created by the CLI could go straight to being considered a compiled package for purposes of other packages that depend on it for compilation, or jobs that depend on it.

**Comment by mfine30** [comment]
Closing in favor of #1946
