### ISSUE TITLE
Runtime config can't be removed.

### ISSUE THREAD

**Issue by chrisburrus** [cloudfoundry/bosh#1369]
When I was still learning bosh, I was messing with things, and accidently loaded a runtime-config (meaning to update my cloud-config instead). I realized my mistake and went to fix it, but there is no option to remove a runtime-config, and you can't submit an empty one. So I had to add _something_ to it, so I put in a harmless release. No real damage done, but there should be an option to completely clear runtime-config, or runtime-config should be able to be empty.

**Comment by cppforlife** [comment]
Agreed. We can relax validation constraints to allow empty file.

**Comment by jfmyers9** [comment]
This can now be achieved by running `bosh delete-config`.
