### ISSUE TITLE
Feature Request: Allow team tagging on existing deployments

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloudfoundry/bosh#1371]
For established directors with deployments done by a `bosh.admin` or for folks using concourse pipelines that use the bosh deployment resource as a `bosh.admin` (some pipelines need to upload releases/stemcells - something a `bosh.teams.*.admin` can't do), it would be nice to have a cli based command to tag a deployment with a team.  This would save on work/design of creating numerous IDs for concourse pipelines based on the task role and team deployments.

Thank You

**Comment by cppforlife** [comment]
To clarify, you are proposing to set team during bosh deploy but continue using admin for uploading of releases/stemcells?

**Comment by ChrisMcGowan** [comment]
Correct - either set the team tag during the deployment (a manifest option would work) or via a CLI command executed by someone holding the `bosh.admin` role.  If not, you end up managing numerous users or clients for your pipelines based on the number of teams you have and the needed bosh roles for the pipeline jobs.

Currently the only way I have found to do this (concourse running as `bosh.admin`) is a manual process of doing a ssh into the director, target the bosh db, and update the deployments table for that particular deployment since, at least for using a PG db, the database service is only listening to `127.0.0.1` for security purposes.
