### ISSUE TITLE
Use parallel make by default during compilation

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1377]
It would help to speed up package compilation, at least for packages relying on `make`, to add either `MAKEFLAGS="-j{C+1}"` or `MAKEFLAGS="-l{C}"` (where `C` should be replaced by the number of cores) in the system-wide `make.conf`.

This would make all runs of `make` "optimal" use of all available CPU resources.

**Comment by dpb587-pivotal** [comment]
Great idea

**Comment by cppforlife** [comment]
one thing we did notice before is using make with -j configuration introduces a bit of flakiness. may be we could do `... || make`.

**Comment by CAFxX** [comment]
@cppforlife flakiness? meaning, failing `make`s?

**Comment by cppforlife** [comment]
@CAFxX yup. we saw builds fail 1/50 times -- we assume that there might be race conditions in project's make configurations.
