### ISSUE TITLE
Incorrect update order

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh#1378]
I have two jobs in `app` instance group. 

```
  Started creating missing vms
  Started creating missing vms > app/2 (3017e908-962e-4306-b98b-d1b875a18a3b)
  Started creating missing vms > app/3 (a07c2bce-c57c-4033-b10f-c56ea041703d)
  Started creating missing vms > router/1 (5eb01d9f-ec13-4ce2-92c8-a0202a54fdd7). Done (00:00:09)
     Done creating missing vms > app/3 (a07c2bce-c57c-4033-b10f-c56ea041703d) (00:00:09)
     Done creating missing vms > app/2 (3017e908-962e-4306-b98b-d1b875a18a3b) (00:00:11)
     Done creating missing vms (00:00:11)

  Started deleting unneeded instances app
  Started deleting unneeded instances app > app/0 (60f46ce2-bd2f-4c4e-9162-316e8a411e38)
  Started deleting unneeded instances app > app/1 (242c50a6-fff4-45ca-8c4d-e6e438187a09)
     Done deleting unneeded instances app > app/0 (60f46ce2-bd2f-4c4e-9162-316e8a411e38) (00:00:01)
     Done deleting unneeded instances app > app/1 (242c50a6-fff4-45ca-8c4d-e6e438187a09) (00:00:02)
     Done deleting unneeded instances app (00:00:02)

  Started updating job app
  Started updating job app > app/2 (3017e908-962e-4306-b98b-d1b875a18a3b) (canary)
```

During update BOSH correctly creates two new instances of `app` vms but then deletes original vms! New vms are not yet provisioned and I get `app` downtime.

The proper behavior is to delete vm instances only after job updated and healthy. My config below.

```
update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

$ bosh version
BOSH 1.3262.4.0
```

**Comment by cppforlife** [comment]
@lexsys27 will look into this.

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/127824033

**Comment by dpb587-pivotal** [comment]
@lexsys27, based on code, I'm guessing you switched `app` from one availability zone to another. Any chance you recall and can confirm that was the scenario (or perhaps you had a different scenario that we should consider)? Thanks!

**Comment by lexsys27** [comment]
@dpb587-pivotal you are almost right. I added two `azs` to the cloud-config and allocate two instances of `app` to these zones.

**Comment by lexsys27** [comment]
Here is the app-related manifest part:

```
instance_groups:
- name: app
  instances: 2
  azs: [z1, z2]
  jobs:
  - name: app
    release: sinatra
    properties:
      port: 8002
  vm_type: small
  stemcell: warden
  networks:
  - name: main
```

**Comment by cppforlife** [comment]
@lexsys27 were you migrating from non-azs configuration to azs configuration?

**Comment by lexsys27** [comment]
@cppforlife yes

**Comment by cppforlife** [comment]
@lexsys27 in that case I believe migrated_from directive would have solved the problem: http://bosh.io/docs/migrated-from.html. it would have considered "renamed" instances and done a standard instance group update cycle instead of considering them as separate instance groups.

**Comment by lexsys27** [comment]
@cppforlife Didn't know about this option, will try it soon. Thank you for the link!

**Comment by cppforlife** [comment]
@lexsys27 im going to close this issue since i think it behaves as expected if you use migrated_from. feel free to reopen if you observe otherwise.
