### ISSUE TITLE
Feature request: bosh should read AWS creds from env. variables

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1384]
When uploading a final release or blobs, BOSH should be able to read `final.yml` to find out blobstore information and for credentials, if `private.yml` is missing or doesn't contain credentials, it should use standard AWS way of providing credentials (supported by many AWS libraries) - via environment variables:
AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID

I was a bit surprised that the library bosh cli uses doesn't already support that...

bosh cli version `BOSH 1.3262.0`

**Comment by combor** [comment]
https://github.com/cloudfoundry/bosh/pull/1402 will fix this.

**Comment by dpb587-pivotal** [comment]
Closing - the new golang [bosh CLI](https://github.com/cloudfoundry/bosh-cli) supports this behavior by configuring `credentials_source` as `env_or_profile`.
