### ISSUE TITLE
Feature request: Release and blobstore delete/retire

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1386]
Currently a blobstore S3 bucket looks similarly to `.blobs` directory - a list of uuid named files. If you use a shared bucket for multiple releases it's hard to tell which files belong to which versions of which releases.

It would be great if bosh had some option to
1. delete a blob. Say I have updated my release to use different blob and the old blob is not used any more. Currently I have to find out `object_id` by hand in `blobs.yml` and then delete it from bucket and `blobs.yml` file.
2. delete a release version. Say I have some old versions of release that I don't want to support any more or I know that they don't work any more - and I don't want to keep them. I would like to remove them and all associated artifacts that are not used by any other releases (mainly blobs).

**Comment by cppforlife** [comment]
@mtekel if you delete the blob when you dont need it, it would mean that you wouldn't be able to recreate your release from prev versions -- useful when making patches. may be that's something you are less concerned about given a specific release workflows (for example when always moving forward). i think new commend `delete-blob` makes sense. you would give it a path and it will update blobs.yml and delete the blob from the blobstore.

**Comment by tjvman** [comment]
Closing this issue - [The v2 bosh CLI](https://github.com/cloudfoundry/bosh-cli) supports `delete-release`, `remove-blob`, and `clean-up` commands that I believe accomplish most of what you're looking for. However, bosh will not clean up blobs from a configured s3 blobstore for the reason mentioned above - don't want to break historical releases.

If those commands don't give you the functionality you need, please feel free to open an issue in the v2 CLI repo.
