### ISSUE TITLE
Feature request: Set ephemeral disk type on vsphere

### ISSUE THREAD

**Issue by penrod** [cloudfoundry/bosh#1391]
Our vmware hosts have been using NFS datastores that did not previously have HW acceleration, so our disks were being provisioned thin. New hosts are being introduced that are connected to a new NFS datastore that does support HW acceleration, so when our cf vms get deployed on these, the disk are getting provisioned thick. If I understand correctly, the thick disk type is the bosh_cpi default. We are able to set the persistent disk as thin provisioned. I have not been able to find a way to set the ephemeral disk type as you can do with an aws deploy.

**Comment by cppforlife** [comment]
cc @ljfranklin

**Comment by cppforlife** [comment]
@penrod seems like a reasonable change to https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release, though naming of the key might be a bit weird since we just have `disk` as a key for the size.

**Comment by youngm** [comment]
@cppforlife Instead of submitting a PR to make the disk type configurable for each vm type can we instead allows you to configure the default disk type in the vcenter configuration?  Or possibly even just set the type to thin always so it doesn't differ from host to host?

Seems like either of those would be a good first step, simpler, and adequate for our needs.  Perhaps someone else can contribute individual vmtype config in the future?

Mike

**Comment by cppforlife** [comment]
@youngm global configuration makes sense from an operator perspective. Story: https://www.pivotaltracker.com/story/show/128521917

**Comment by youngm** [comment]
@cppforlife So, I found the API call for making ephemeral disks thin:

FlatVer2BackingInfo.thin_provisioned = true/false

Since it seems creation of ephemeral disks is done quite different from persistent disks how would you feel about dividing the story into 2 stories.  One for global config for persistent disk and one for global config of ephemeral disk.  For ephemeral global config I'll probably present a "thin_provision_ephemeral_disk" config default to false.

Thoughts?

**Comment by ljfranklin** [comment]
@youngm nice detective work! We've updated [this story](https://www.pivotaltracker.com/story/show/128521917) to reflect that finding. We're currently planning on adding the following property:

```yaml
properties:
  vsphere:
    default_disk_type: 'thin' # defaults to 'thick', only supported values are 'thick' and 'thin'
```

This would be used as the default for both ephemeral and persistent disks. However, the default persistent disk type could still be overridden by specifying [disk_pools.cloud_properties.type](http://bosh.io/docs/vsphere-cpi.html#disk-pools).

Sound okay?

**Comment by youngm** [comment]
@ljfranklin Yeah, that sounds better.  Because the options are `preallocated` and `thin` should we also set `eagerlyScrub` to true as well in either case?

https://www.vmware.com/support/developer/converter-sdk/conv51_apireference/vim.vm.device.VirtualDisk.FlatVer2BackingInfo.html

**Comment by ljfranklin** [comment]
@youngm I think we should keep `eagerlyScrub` to `false` for now. Scrubbing doesn't apply to `thin` disks as they are not allocated up front, and `preallocated` disks are not zero-ed out in advance to make disk creation faster. Seems like the only advantage to `eagerlyScrub` is to enable vSphere [fault tolerance](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1013428), but if you're already using BOSH you can deploy multiple instances across different AZs (Datacenter or cluster) to get the same redundancy.

What worries us is the long time to bring up a VM if `eagerlyScrub` is `true`. For example, let's assume a Concourse CI VM with a 100GB disk that's backed by magnetic media with a throughput of 50MB/s — it would take ~33 minutes to zero-out the disk before we could bring the VM.

**Comment by youngm** [comment]
@ljfranklin Ah, I mis-read the pre-allocated definition.  Missed that it says it zeros out "on demand".  Sounds good.

**Comment by youngm** [comment]
@ljfranklin Great work on this issue.  However, looking at the main commit for this fix: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/commit/26983129e258d90f3fc636b2e64ff0048fea1516 it appears to me that this commit only currently applies a default to persistent disks and not ephemeral.  Am I seeing it correctly?

**Comment by ljfranklin** [comment]
@youngm we were a little messy when we squashed our commits. Ephemeral disk change is in the next commit: https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/commit/77f14a29c14ced0c68036d678e1bab255f24354e

**Comment by youngm** [comment]
@ljfranklin Ah, thanks.  We're trying to verify the change.  But having some trouble I'll keep digging.

**Comment by youngm** [comment]
@ljfranklin Found the problem I was having.  The config hasn't yet been added to the job spec yet.  Thanks.

**Comment by ljfranklin** [comment]
@youngm :( that's a little embarrassing, sorry about that. Ping @cppforlife and @cunnie to prioritize the fix.

**Comment by youngm** [comment]
@ljfranklin no need to feel embarrassed.  We caught it pre-release right? :)

**Comment by cppforlife** [comment]
Seems like we can consider this closed.
