### ISSUE TITLE
Ability to see hm.resurrector_enabled state

### ISSUE THREAD

**Issue by dcarley** [cloudfoundry/bosh#1398]
If you disable the resurrector with the property `hm.resurrector_enabled: false` ([docs reference](https://bosh.io/docs/resurrector.html#disable)) then it's not possible to see from `bosh_cli` that it's been disabled.

Some ideas about how I think this would be visible:
1. `bosh vms --details` should list something other than `active` in the `Resurrection` column for each VM
2. `bosh vm resurrection` (with no other arguments) could list the global status
3. `bosh status` could also list the global status for the `Director` in the same way it lists `snapshots`

I think that in all these cases, the state shown should take `hm.resurrector_enabled: false` in precedence over individual `bosh vm resurrection` states.

**Comment by cppforlife** [comment]
@dcarley I think we can expose this info through /info endpoint so that status shows the info.

**Comment by pivotal-mark-higuera** [comment]
This feature is needed. Customers should be able to see the resurrection status without having to change it, especially in a production environment.

**Comment by mrosecrance** [comment]
We are now publishing this metric with prometheus. As of this story: https://www.pivotaltracker.com/story/show/168964490
