### ISSUE TITLE
Unable to ssh-in to GCE deployments `Connection closed by foreign host` when Project name is 13 characters or longer

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh#1399]
[firstboot.sh](https://github.com/cloudfoundry/bosh/blob/afe7a27e51430f275a7bb1489efc8c5ffca11a9b/stemcell_builder/stages/base_ubuntu_firstboot/assets/root/firstboot.sh#L5) fails intermittently on  GCE, which causes the VM's ssh keys not to be generated, which in turn prevents sshd from allowing inbound connections.

The problem is caused by the `dpkg-reconfigure -fnoninteractive -pcritical openssh-server` line, which fails as follows:

```
Creating SSH2 RSA key; this may take some time ...gethostname: File name too long
```

The hostname is often something cryptic, e.g. `vm-0eb85710-a7e5-4079-59d0-7fff6f3bf16d.c.blabbertabber.internal` (a 65-character hostname).

Within ~5 seconds, the hostname will be set to a name that's not too long, e.g. `ab12aa79-f2f6-4833-95ad-e86141c2db6c`, at which point `dpkg-reconfigure` will succeed.
#### I plan to submit a PR to fix by looping repeatedly until the command succeeds

I have attached the output from specially-instrumented `firstboot.sh`'s

[firstboot.0.758.txt](https://github.com/cloudfoundry/bosh/files/420576/firstboot.0.758.txt)

[firstboot.0.sh.txt](https://github.com/cloudfoundry/bosh/files/420580/firstboot.0.sh.txt)

[firstboot.1.757.txt](https://github.com/cloudfoundry/bosh/files/420575/firstboot.1.757.txt)

[firstboot.1.sh.txt](https://github.com/cloudfoundry/bosh/files/420581/firstboot.1.sh.txt)

/cc @evandbrown @cppforlife

**Comment by voelzmo** [comment]
@cunnie I recently saw https://github.com/cloudfoundry/bosh/pull/1389
Is the stemcell you're testing this with already having that fix? Supposedly that could solve some problems around it...

**Comment by cunnie** [comment]
@voelzmo thanks. I'm not quite sure #1389 will fix the problem, but I'll follow up with Dmitriy & Evan and close out the ticket if that's that case.

**Comment by cunnie** [comment]
Per @cppforlife :

> Build a custom stemcell with a modified `/etc/dhcp/dhclient.conf` that does *not* request `host-name`. If that fixes the problem, submit a PR to BOSH.

**Comment by cunnie** [comment]
Timeline:

| Time | Event |
|------|--------|
| 15:00:10 | `/var/log/syslog` reports dhclient sends ack/receives reply |
| 15:00:10 | audispd reports `/bin/hostname` |
| 15:00:11 | `/var/log/syslog` reports dhclient sets IP addr |
| 15:00:16 | `firstboot.sh` starts |
| 15:00:19 | bosh-agent re-writes `dhclient.conf` |
| 15:00:19 | audispd reports `/bin/hostname` |
| 15:00:19 | `/var/log/syslog` reports dhclient sends ack/receives reply |
| 15:00:24 | ¿bosh-agent? sets short-enough hostname |

* Built stemcell with modified `/etc/dhcp/dhclient.conf`
* Failure, log file (`/root/firstboot.758`) showed too-long hostname:
```
Creating SSH2 RSA key; this may take some time ...gethostname: File name too long
+ RECONFIGURED=1
+ hostname
vm-95203f50-b480-437b-7eab-793d7521c883.c.blabbertabber.internal
```
* within 8 seconds it received a workable (shorter hostname).
* the timestamp on the log file was 2016-08-17 15:00:24.039833000 (via `stat`)
* the "bad" hostname was set at 15:00:16 or earlier
* the dhclient file was re-written by `bosh-agent` at 15:00:19 (`stat /etc/dhcp/dhclient.conf`); this indicates that the bosh-agent's "new" file with "host-name"

**Comment by cunnie** [comment]
| Time | Provenance | Event |
|---|---|---|
| 21:53:31 | /root/firstboot.760 | firstboot.sh starts |
| 21:53:31 | /var/log/syslog | dhclient receives IP address |
| 21:53:31 | /root/firstboot.760 | `gethostname: File name too long` |
| 21:53:40.017 | stat /etc/dhcpd/dhclient.conf | bosh-agent rewrites `dhclient.conf` |
| 21:53:40.017 | stat /etc/hostname | /etc/hostname is rewritten |
| 21:53:40 | /root/firstboot.760 | hostname is not too long |
| 21:53:40 | /var/log/syslog | dhclient receives IP address |
| 21:53:42 | /root/firstboot.760 | firstboot.sh finishes |

**Comment by cunnie** [comment]
### Failure: attempt to fix by setting `/etc/dhcp/dhclient.conf` to `bosh-agent`'s version

I attempted to fix by modifying `dhclient.conf` to match `bosh-agents`'s. There were subtle differences, but apparently those differences were not terribly important: 

```diff
< #send host-name "andare.fugue.com";
< send host-name = gethostname();
< #send dhcp-client-identifier 1:0:a0:24:ab:fb:9c;
< #send dhcp-lease-time 3600;
< #supersede domain-name "fugue.com home.vix.com";
< #prepend domain-name-servers 127.0.0.1;
---
> option rfc3442-classless-static-routes code 121 = array of unsigned integer 8;
>
> send host-name "<hostname>";
>
23,27c21,24
<      	domain-name, domain-name-servers, domain-search, host-name,
<      	dhcp6.name-servers, dhcp6.domain-search,
<      	netbios-name-servers, netbios-scope, interface-mtu,
<      	rfc3442-classless-static-routes, ntp-servers,
<      	dhcp6.fqdn, dhcp6.sntp-servers;
---
>              	domain-name, domain-name-servers, domain-search, host-name,
>              	netbios-name-servers, netbios-scope, interface-mtu,
>              	rfc3442-classless-static-routes, ntp-servers;
>
```
[firstboot.758.txt](https://github.com/cloudfoundry/bosh/files/426866/firstboot.758.txt)

**Comment by cunnie** [comment]
### Success: Attempt to fix by setting a DHCP exit hook

Setting a DHCP exit hook seems to fix the problem almost all the time (**99%**). Note that this problem only seems to occur if the Google Project's name is 12 characters or longer (e.g. "BlabberTabber") (the project name is appended to the dhclient-assigned hostname, which can push the hostname past the 63-character limit) (e.g. `vm-bad62ff1-640a-40b0-43b8-7467b78ee9b1.c.blabbertabber.internal`)

Google's _compute-images-packages_ on occasion [will set](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/97ec9d47da88ab0d93cc3fdf3b8f6a86b03f1142/google_configs/build_packages.sh#L49-L64) a DHCP exit hook to [specifically deal with this problem](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/c98f0c89330f547d772d2c25883fe4a8f152b95c/google_configs/bin/set_hostname#L29-L31).

I manually set in the stemcell:
```
cd /etc/dhcp/dhclient-exit-hooks.d
curl -OL https://raw.githubusercontent.com/GoogleCloudPlatform/compute-image-packages/c98f0c89330f547d772d2c25883fe4a8f152b95c/google_configs/bin/set_hostname
chmod +x set_hostname
```
Although the deploy command exited non-zero, the deployment was a success:
```
Updating deployment:
  Getting task state:
    Performing request GET 'https://bosh-gce.nono.io:25555/tasks/66':
      Performing GET request:
        Get https://admin:SwiftCat_1998@bosh-gce.nono.io:25555/tasks/66: dial tcp 104.154.39.128:25555: i/o timeout

Exit code 1
```
`firstboot.sh` completed on its first try because the dhclient exit hook had truncated the hostname to 40 characters (this means that we don't need to change `firstboot.sh`).

We can see that there's a 50-90 millisecond window between `dhclient` setting the hostname and the subsequent dhclient-hook truncating the hostname (`dhclient` is invoked twice: once at startup, and once by `bosh-agent` (?), and each invocation sets the hostname twice, for a total of four times):

```
# grep bin/hostname /var/log/audit/audit.log
type=SYSCALL msg=audit(1471610279.524:61): arch=c000003e syscall=170 success=yes exit=0 a0=194d010 a1=40 a2=10 a3=7ffcf2bc4690 items=0 ppid=848 pid=851 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="hostname" exe="/bin/hostname" key="system-locale"
type=SYSCALL msg=audit(1471610279.576:65): arch=c000003e syscall=170 success=yes exit=0 a0=c3e010 a1=27 a2=fffff88000000000 a3=7ffe47f7b0e0 items=0 ppid=848 pid=889 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="hostname" exe="/bin/hostname" key="system-locale"
type=SYSCALL msg=audit(1471610286.488:136): arch=c000003e syscall=170 success=yes exit=0 a0=17f8010 a1=24 a2=fffff8f000000000 a3=7ffeb8479220 items=0 ppid=784 pid=1207 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="hostname" exe="/bin/hostname" key="system-locale"
type=SYSCALL msg=audit(1471610286.572:142): arch=c000003e syscall=170 success=yes exit=0 a0=1cd5010 a1=27 a2=fffff88000000000 a3=7fff4ac00800 items=0 ppid=1262 pid=1302 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="hostname" exe="/bin/hostname" key="system-locale"
```

In this particular example, there was **6.964** seconds between the 2 invocations of `dhclient`, which means there was **6.964** seconds of a too-long hostname. By adding the dhclient-exit-hook, we reduced that window to **0.052** milliseconds, a **99.2%** reduction. By extrapolating the number of failures we were seeing before this modification (i.e. 87.5%  machine would come up without ssh keys) we could project that the failures would be reduced to ( 87.5% * 0.008 &rarr; ) **0.7%**.

**Comment by cunnie** [comment]
### Problems in Paradise: DHCP exit-hook may have unforeseen consequences

I am not able to upload stemcells to a freshly-redeployed BOSH director with a stemcell with an exit hook. The BOSH director doesn't have the expect `bosh-agent`-set hostname `92d9ffc9-c1cd-4a7b-509b-7ceac872d02a`; instead, it has the hostname set by the exit hook: `vm-01acbd50-062d-4c55-6f0d-a9895affbe3a`

Thirty five minutes have elapsed since the stemcell was uploaded, and no progress is shown (time of command is 13:57):
```
bosh task 72 --debug
Using environment 'bosh-gce.nono.io' as user 'admin'

Task 72

I, [2016-08-20T13:22:17.551486 #10289] [0x2b27c1bb911c]  INFO -- TaskHelper: Director Version: 1.3262.3.0
I, [2016-08-20T13:22:17.551582 #10289] [0x2b27c1bb911c]  INFO -- TaskHelper: Enqueuing task: 72
```

Here is `/etc/hosts`:
```
127.0.0.1 localhost 92d9ffc9-c1cd-4a7b-509b-7ceac872d02a

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback 92d9ffc9-c1cd-4a7b-509b-7ceac872d02a
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.128.0.2 vm-01acbd50-062d-4c55-6f0d-a9895affbe3a.c.blabbertabber.internal vm-01acbd50-062d-4c55-6f0d-a9895affbe3a  # Added by Google
```

Try setting the hostname manually & uploading stemcell. Not a hang this time, but a failure nonetheless:

```
Uploading stemcell file:
  Getting task state:
    Performing request GET 'https://bosh-gce.nono.io:25555/tasks/73':
      Performing GET request:
        Get https://admin:xxxx@bosh-gce.nono.io:25555/tasks/73: dial tcp 104.154.39.128:25555: i/o timeout

Exit code 1
```

This time I did a `monit restart all` and kicked off another stemcell upload [darn: I should have done a `monit restart all` without fixing the hostname — that would have been a good control subject].

Stemcell upload completed.

Test:
* set hostname back to old one (`vm-01acbd50-062d-4c55-6f0d-a9895affbe3a`)
* `monit restart all`
* attempt to upload stemcell again

And it worked. Hmmm, not the result I expected.

```
sudo hostname `cat /etc/hostname`
hostname
   92d9ffc9-c1cd-4a7b-509b-7ceac872d02a
```
```

**Comment by cunnie** [comment]
### Problems in Paradise: DHCP exit-hook may have unforeseen consequences

I am not able to upload stemcells to a freshly-redeployed BOSH director with a stemcell with an exit hook. The BOSH director doesn't have the expect `bosh-agent`-set hostname `92d9ffc9-c1cd-4a7b-509b-7ceac872d02a`; instead, it has the hostname set by the exit hook: `vm-01acbd50-062d-4c55-6f0d-a9895affbe3a`

Thirty five minutes have elapsed since the stemcell was uploaded, and no progress is shown (time of command is 13:57):
```
bosh task 72 --debug
Using environment 'bosh-gce.nono.io' as user 'admin'

Task 72

I, [2016-08-20T13:22:17.551486 #10289] [0x2b27c1bb911c]  INFO -- TaskHelper: Director Version: 1.3262.3.0
I, [2016-08-20T13:22:17.551582 #10289] [0x2b27c1bb911c]  INFO -- TaskHelper: Enqueuing task: 72
```

Here is `/etc/hosts`:
```
127.0.0.1 localhost 92d9ffc9-c1cd-4a7b-509b-7ceac872d02a

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback 92d9ffc9-c1cd-4a7b-509b-7ceac872d02a
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
10.128.0.2 vm-01acbd50-062d-4c55-6f0d-a9895affbe3a.c.blabbertabber.internal vm-01acbd50-062d-4c55-6f0d-a9895affbe3a  # Added by Google
```

Try setting the hostname manually & uploading stemcell. Not a hang this time, but a failure nonetheless:

```
Uploading stemcell file:
  Getting task state:
    Performing request GET 'https://bosh-gce.nono.io:25555/tasks/73':
      Performing GET request:
        Get https://admin:xxxx@bosh-gce.nono.io:25555/tasks/73: dial tcp 104.154.39.128:25555: i/o timeout

Exit code 1
```

This time I did a `monit restart all` and kicked off another stemcell upload [darn: I should have done a `monit restart all` without fixing the hostname — that would have been a good control subject].

Stemcell upload completed.

Test:
* set hostname back to old one (`vm-01acbd50-062d-4c55-6f0d-a9895affbe3a`)
* `monit restart all`
* attempt to upload stemcell again

And it worked. Hmmm, not the result I expected.

```
sudo hostname `cat /etc/hostname`
hostname
   92d9ffc9-c1cd-4a7b-509b-7ceac872d02a
```

**Comment by cunnie** [comment]
## Setting /etc/hostname to `bosh-stemcell` fixes the problem

Setting `/etc/hostname` to `bosh-stemcell` (instead of `localhost`) in the stemcell image fixes the problem of GCE stemcells not booting.

This works because `/sbin/dhclient-script` will set the hostname _only if_ the hostname is set to "localhost" or [something else](https://github.com/mcr/isc-dhcp/blob/3012673b55749313fbed63dfcc9a67c98e54d2f0/client/scripts/linux#L132-L139).

* no DHCP exit hook necessary: ~~`/etc/dhcp/dhclient-exit-hooks.d/set_hostname`~~
* no need to obscure/hide `/bin/hostname` to prevent `/sbin/dhclient-script` from setting it.
* hostname is quickly set to the one BOSH expects:
```
# hostname
cbd46fc8-9bad-4235-aac0-5e9c6a0730b7
```
* hostname is only set once (by `bosh-agent`?):
```
# grep bin/hostname /var/log/audit/audit.log
type=SYSCALL msg=audit(1472000504.370:130): arch=c000003e syscall=170 success=yes exit=0 a0=e71010 a1=24 a2=fffff8f000000000 a3=7fff6869bb50 items=0 ppid=765 pid=1204 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="hostname" exe="/bin/hostname" key="system-locale"
```
* firstboot sequence:

| Time | Event | Provenance |
|---|---|---|
| 01:01:35 | dhclient receives IP address | `/var/log/daemon.log` |
| 01:01:37 | `firstboot.sh` begins execution | `firstboot.sh` output |
| 01:01:44.370 | hostname set | `/var/log/audit/audit.log` |

**Comment by cunnie** [comment]
For posterity, here is the `/sbin/dhclient-script` output. The take-away: setting `/etc/hostname` to `bosh-stemcell` in the image prevents dhclient-script from overwriting the hostname with a too-long name:

first run: hostname is `bosh-stemcell`
```
+(/sbin/dhclient-script:251): main(): set_hostname
+(/sbin/dhclient-script:140): set_hostname(): set -x
+(/sbin/dhclient-script:141): set_hostname(): local current_hostname
+(/sbin/dhclient-script:143): set_hostname(): '[' -n vm-cfefbb40-8ca6-4a9e-728d-d238b1f1f171.c.blabbertabber.internal ']'
++(/sbin/dhclient-script:144): set_hostname(): hostname
+(/sbin/dhclient-script:144): set_hostname(): current_hostname=bosh-stemcell
+(/sbin/dhclient-script:147): set_hostname(): '[' -z bosh-stemcell ']'
+(/sbin/dhclient-script:148): set_hostname(): '[' bosh-stemcell = '(none)' ']'
+(/sbin/dhclient-script:149): set_hostname(): '[' bosh-stemcell = localhost ']'
+(/sbin/dhclient-script:150): set_hostname(): '[' bosh-stemcell = '' ']'
```

second run: bosh-agent has updated hostname to `ac64eff4-6c67-414e-a776-10713e0fcf91`
```
+(/sbin/dhclient-script:251): main(): set_hostname
+(/sbin/dhclient-script:140): set_hostname(): set -x
+(/sbin/dhclient-script:141): set_hostname(): local current_hostname
+(/sbin/dhclient-script:143): set_hostname(): '[' -n vm-cfefbb40-8ca6-4a9e-728d-d238b1f1f171.c.blabbertabber.internal ']'
++(/sbin/dhclient-script:144): set_hostname(): hostname
+(/sbin/dhclient-script:144): set_hostname(): current_hostname=ac64eff4-6c67-414e-a776-10713e0fcf91
+(/sbin/dhclient-script:147): set_hostname(): '[' -z ac64eff4-6c67-414e-a776-10713e0fcf91 ']'
+(/sbin/dhclient-script:148): set_hostname(): '[' ac64eff4-6c67-414e-a776-10713e0fcf91 = '(none)' ']'
+(/sbin/dhclient-script:149): set_hostname(): '[' ac64eff4-6c67-414e-a776-10713e0fcf91 = localhost ']'
+(/sbin/dhclient-script:150): set_hostname(): '[' ac64eff4-6c67-414e-a776-10713e0fcf91 = vm-cfefbb40-8ca6-4a9e-728d-d238b1f1f171.c.blabbertabber.internal ']'
```

Files (I have *no idea* why dhclient-scripts is called 5 times, but only 2 times of those 5 does it try to set the hostname):

[dhclient-script.816.txt](https://github.com/cloudfoundry/bosh/files/443087/dhclient-script.816.txt)
[dhclient-script.821.txt](https://github.com/cloudfoundry/bosh/files/443084/dhclient-script.821.txt)
[dhclient-script.1244.txt](https://github.com/cloudfoundry/bosh/files/443088/dhclient-script.1244.txt)
[dhclient-script.1224.txt](https://github.com/cloudfoundry/bosh/files/443086/dhclient-script.1224.txt)
[dhclient-script.1240.txt](https://github.com/cloudfoundry/bosh/files/443085/dhclient-script.1240.txt)

**Comment by ljfranklin** [comment]
Turns out we do need to remove `/etc/dhcp/dhclient-exit-hooks.d/set_hostname` as this hook causes `dhclient` to override the hostname (which should be the agent ID) with the VM name.

**Comment by cunnie** [comment]
Closing (I don't know why it's still open — it was fixed a while ago).
