### ISSUE TITLE
Bosh silently ignores unknown fields

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/bosh#1404]
If you specify a deployment job field that doesn't exist, such as `jobs.*.disk_type` instead of `jobs.*.persistent_disk_type`, Bosh will not fail or even warn you of a non-existent field being used. In our use case this has led to Bosh not deploying as expected (it picked up the underlying ephemeral disk defined in the `vm_type`). 

It seems there should be some kind of schema of known fields (that are not under any extensible namespace, such as `properties`) to provide warnings of potential typos. This will help prevent Bosh (potentially silently) failing to do what is expected.

**Comment by cppforlife** [comment]
+1000. we are definitely planning to get to this.

**Comment by mrosecrance** [comment]
Closing this one as https://github.com/cloudfoundry/bosh/issues/1568 seems to be a duplicate with a bit more context
