### ISSUE TITLE
Error 30006: Release version 'service-monitor/latest' doesn't exist

### ISSUE THREAD

**Issue by willwillgo** [cloudfoundry/bosh#1408]
I'm developing bosh development with bosh-lite. When I update the bosh version from 1.3012.0 to 1.3262.4.0, I get this message when run "bosh deploy" commond:

Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 19

  Started preparing deployment > Preparing deployment. Failed: Release version 'service-monitor/latest' doesn't exist (00:00:00)

Error 30006: Release version 'service-monitor/latest' doesn't exist
---------
The release section is defined in my manifest file as：
release: {name: service-monitor, version: latest}
When I changed the ‘latest’ to actual  version ：
release: {name: service-monitor, version: 0+dev.37}
It works fine.  But I should change the manifest file every time when I update the release, it's hard to use in developing.

**Comment by cppforlife** [comment]
@willwillgo should use `releases` (plural) key instead of `release` in your manifest.
