### ISSUE TITLE
bosh.io not synchronized with bosh releases

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1412]
The [list of bosh releases on bosh.io](http://bosh.io/releases/github.com/cloudfoundry/bosh?version=257.3) only contains 257.3 as latest version.
[Here on github](https://github.com/cloudfoundry/bosh/releases) you can see that there exist releases up to 257.8.

Did bosh.io git stuck or is there a reason why those releases are not shown there?

**Comment by cppforlife** [comment]
there is no bosh release 257.8. there is though 3262.8. because bosh repo is used to keep track of stemcells and bosh releases numbering bit weird. plan is to separate this out into two.
