### ISSUE TITLE
Can not upgrade Ubuntu 14.04 stemcell kernel

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/bosh#1413]
This issue appeared over at the https://github.com/openwhisk/openwhisk project.

We need to constantly update our kernels to keep up with latest Docker releases.

We use the stemcell as a base layer which is then upgraded constantly using an agent that basically does your ol' `apt-get install linux-image-xxx`.

I have noticed that even though the kernels get installed on the system, they are not actually loaded after reboot. 

During debugging I found the `/boot/grub/menu.lst` did not get updated and kept and old hard-coded 3.19-something kernel as a static stanza. (Is this by design?)
I know there is a bug in grub that sometimes prevents automagic kernel list creation:  https://ubuntuforums.org/showthread.php?t=873448

When I deleted `/boot/grub/menu.lst` and ran `update-grub` the new kernels were added as expected.

Questions: Is this by design? Is the stemcell not meant to be auto-upgradeable?
Otherwise I would deem this a bug.

**Comment by cppforlife** [comment]
> Is the stemcell not meant to be auto-upgradeable?

yup. stemcells are not updated via apt-get. we produce new stemcell with necessary dependencies bumped over time (typically when cve come out). we typically follow ubuntu lts releases for current 14.04 series.

3262.5 was produced with 4.4 kernel if that helps. within next few weeks we'll completely switch over to 4.4 kernels for the latest stemcells.

**Comment by mattcui** [comment]
@cppforlife We tried some versions of recent stemcell from 3262.4 to 3262.8, the kenerl is always 3.19.0-66

```
# uname -a
Linux ad1ff727-d5cd-49f8-8e48-37a02cfe544f 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
I also checked the stemcell_dpkg_l.txt of the latest aws stemcell, there listed 3.19.0-66 also

Why isn't the kernel upgraded to 4.4? Thanks.

**Comment by cppforlife** [comment]
@mattcui 3262.5 was produced with 4.4 kernel.

**Comment by mattcui** [comment]
@cppforlife only this version was upgraded to 4.4? All subsequent versions were rolled back to 3.19? Thanks.

**Comment by mattcui** [comment]
@domdom82 I checked, only 3262.5 has 4.4 kernel
```
# uname -a
Linux test-kernel-version-3262-5.softlayer.com 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by domdom82** [comment]
I can confirm that 3262.5 contains kernel 4.4.0-31.
I think I will use that one for now. I just wonder why later versions switched back to the older kernel 3.19?
