### ISSUE TITLE
bosh snapshot tasks failing with ruby error

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/bosh#1415]
After upgrading to bosh release 257.3 and stemcell 3262.4 we noticed that every day there were two snapshot tasks stuck in queued state.  Tracing the issue, we see the following:

directory scheduler will create task in database tasks table:
INSERT INTO "tasks" ("username", "type", "description", "state", "deployment_name", "timestamp", "checkpoint_time") VALUES ('scheduler', 'snapshot_self', 'scheduled SnapshotSelf', 'queued', NULL, '2016-08-26 06:00:00.068774+0000', '2016-08-26 06:00:00.068777+0000')

then, inserts job into delayed_jobs table:
INSERT INTO "delayed_jobs" ("handler", "priority", "queue", "run_at") VALUES ('--- !ruby/object:Bosh::Director::Jobs::DBJob
job_class: !ruby/class ''Bosh::Director::Jobs::SnapshotSelf''
task_id: 558
args:
', 0, 'normal', '2016-08-26 06:00:00.097922+0000')

When a worker picks up the job in the delayed_jobs table it fails on following ruby error:
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/json_pure-1.8.1/lib/json/common.rb:223:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/json_pure-1.8.1/lib/json/common.rb:223:in `generate'
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/db_job.rb:50:in `encode'
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/db_job.rb:24:in `block in perform'
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/jobs/db_job.rb:72:in `block (3 levels) in run'
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
        from /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

It removes entry from delayed_jobs table, but the task remains in task table in queued state forever until its manually cancelled.

We did notice that if we dropped stemcell version back down to 3232.3 the problem goes away.  So seems to be related to the stemcell.  The strange thing is we have another deployment that is on this same version of bosh and using stemcell 3262.4 that does not have the issue.  I'm wondering if its a combination of stemcell version and configuration/cpi or something.

**Comment by dpb587-pivotal** [comment]
I believe this is the same issue as: https://www.pivotaltracker.com/story/show/127000967

**Comment by voelzmo** [comment]
Saw that as well when we had over 200000 tasks queued up on a dev system recently

**Comment by cppforlife** [comment]
Interesting. Story: https://www.pivotaltracker.com/story/show/129164119

**Comment by dpb587-pivotal** [comment]
Ah, yeah, I guess it is a different issue than the one I posted. Nevermind.

**Comment by dpb587-pivotal** [comment]
Closing - fixed in [v257.9](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262.9).
