### ISSUE TITLE
bosh_cli still shows the deprecated `logs --all` flag

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry/bosh#1423]
`
Usage: logs <job> <index_or_id> [--agent] [--job] [--only filter1,filter2,...] [--dir destination_directory] [--all]
`

It also gives the following message when you use the flag 
`Warning: --all flag is deprecated and has no effect.`

/cc @tushar-dadlani

**Comment by dpb587-pivotal** [comment]
Probably kept it historically to maintain backwards compatibility with existing tooling, so it probably won't be changed. Doesn't look like the new CLI supports `--all`, so that's good!

```
$ gobosh logs -h
...
[logs command options]
          --dir=            Destination directory (default: .)
      -f, --follow          Follow logs via SSH
          --num=            Last number of lines
      -q, --quiet           Suppresses printing of headers when multiple files are being examined.
          --job=            Limit to only specific jobs
          --only=           Filter logs (comma-separated)
          --agent           Include only agent logs
```

**Comment by dpb587-pivotal** [comment]
Closing - ruby cli is deprecated in favor of [bosh-cli](https://github.com/cloudfoundry/bosh-cli).
