### ISSUE TITLE
Release version gets updated on unsuccessful deployment update

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1426]
We've done an update for release A from version 1.1.17 to 1.1.18. The update failed, but `bosh deployments` still showed version 1.1.18 for release A – and no indication that this was never deployed successfully.
### Steps to reproduce
- deploy a release in version 1.0
- create a failure in the release, e.g. by making the startup script fail on purpose
- create a dev release and deploy
- see it fail
- do `bosh deployments`
### Expected
- Either release version is still on 1.0
- Or release version is on 1.0+dev.1 _and_ some indication that this wasn't actually deployed successfully
### Actual
- Release version is on 1.0+dev.1 and it looks like all is fine

This is especially confusing when the next `bosh deploy` tells you the diff is a release version update to 1.0+dev.1

**Comment by cppforlife** [comment]
Currently we track releases on per deployment basis (instead of per instance for example) for the sake of simplicity. Until deploy succeeds bosh will consider any releases referenced by the manifest and DB are active since they may have been deployed partially.

**Comment by voelzmo** [comment]
@cppforlife Thanks for the explanation. Still, current behavior is unexpected. What about my above suggestions in the **Expected** section?

**Comment by mfine30** [comment]
@voelzmo is this still a concern?
