### ISSUE TITLE
Stemcells version gets updated on unsuccessful deployment update

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1427]
We've done a stemcell update for release A from version 3232 to 3262. The update failed, but bosh deployments still showed stemcell version 3262 for release A – and no indication that this was never deployed successfully.
### Steps to reproduce
- deploy a release with stemcell version 3232
- update stemcell version in the manifest to 3262
- create a failure in the release, e.g. by making the startup script fail on purpose
- create a dev release and deploy
- see it fail
- do `bosh deployments`
### Expected
- Either stemcell version is still on 3232
- Or stemcell version is on 3262 _and_ some indication that this wasn't actually deployed successfully
### Actual
- Release version is on 3232 and it looks like all is fine

This is especially confusing, when the next `bosh deploy` tells you that the diff is a stemcell update to 3262.

**Comment by jfmyers9** [comment]
Validated that this is an issue. Created [a story](https://www.pivotaltracker.com/story/show/159864892) to track this.
