### ISSUE TITLE
Better error logging around --gateway_identity_file

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/bosh#1429]
Doing a `bosh ssh` with a non-existent identity file, as below:

```
bosh ssh --gateway_user=vcap --gateway_host=52.202.215.104 --gateway_identity_file=/i/dont/exist
```

Gives a non-intuitive error:

```
Task 10497 done
Authentication failed with gateway 52.202.215.104 and user vcap.
```

Perhaps we should do a check for `gateway_identity_file` existence before attempting the ssh.

**Comment by dpb587-pivotal** [comment]
Closing - this behavior has changed with the [new cli](https://github.com/cloudfoundry/bosh-cli/).
