### ISSUE TITLE
Bosh add blob fails on 'already tracking'

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/bosh#1430]
When I do a `bosh add blob smoke_tests.test`, I get this message `Already tracking the same version of 'smoke_tests.test`. I'm fine with this message, but the exit code for this is 1 instead of 0, which causes things in my flow to fail because it gets treated as an error.

We think this might be better treated as an informational message + skip, or warning at worst.

**Comment by dpb587-pivotal** [comment]
From [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/bosh/p1473372747000422) for posterity...

> might be able to use ﻿⁠⁠⁠⁠`cmp﻿⁠⁠⁠⁠` and only run it if the file is different; maybe something like `﻿⁠⁠⁠⁠cmp --silent smoke_tests.test blobs/smoke_tests.test || bosh add blob smoke_tests.test﻿⁠⁠⁠⁠`

Relevant piece of code is [here](https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh_cli/lib/cli/blob_manager.rb#L132). Seems reasonable to make it a warning though.

It seems like the new CLI treats it as a brand new blob and completely replaces it in blobs.yml, resulting in duplicate blobs in the blobstore. (/cc @cppforlife)

**Comment by jadekler** [comment]
@dpb587-pivotal Thanks for the reply. We did end up with something like that (`diff` instead of `cmp`), but agreed that a warning makes sense.

**Comment by dpb587-pivotal** [comment]
Closing - the ruby CLI is no longer maintained, and the [new CLI](https://github.com/cloudfoundry/bosh-cli) has different expectations with blobs. Feel free to create an issue in the CLI repo with other bugs or concerns.
