### ISSUE TITLE
Need to upgrade postgreSQL to 9.4.9 (or later version) due to security issues

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1431]
There are 2 vulnerability issues requiring to upgrade postgreSQL to 9.4.9 or later version:

https://exchange.xforce.ibmcloud.com/vulnerabilities/116075
https://exchange.xforce.ibmcloud.com/vulnerabilities/116082

Thanks.

**Comment by mattcui** [comment]
Possible to give a due date? Our security team asked me for it. Thanks.

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/130847907

**Comment by cppforlife** [comment]
Fixed in v257.15 bosh release.
