### ISSUE TITLE
What is the difference between staging-security-group, running-security-group & security-group ?

### ISSUE THREAD

**Issue by Niranjana-5588** [cloudfoundry/bosh#1432]
The command `cf bind-security-group SECURITY-GROUP ORG SPACE` binds security group to ORG and SPACE. Already security-group bind with ORG and SPACE then what is the use of `bind-staging-security-group` and `bind-running-security-group`. 

It make sense that different security groups for app staging and running, what is use of `bind-security-group` when running security group applied to app.

Commands
```
cf bind-staging-security-group SECURITY-GROUP
cf bind-running-security-group SECURITY-GROUP
```
not mentioned ORG and SPACE. With what it is binding ORG or SPACE or container ?

**Comment by tylerschultz** [comment]
Hi @Niranjana-5588, 

This is not a question about BOSH. I'm sorry, I don't know of a better place to ask your question. You may want to try joining https://cloudfoundry.slack.com and asking in the #cf-users channel. Someone should be able to direct you to someone who can help.

**Comment by cppforlife** [comment]
better place for cf issues is cloudfoundry/cf-release github repo or slack channel.
