### ISSUE TITLE
Process in monit file failed to get killed

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1435]
Hi all,

We had an instance group with a release job whose monit file defined 1 process (consul) which bound to port 53.  We changed the release job to have two processes, the original process binding to 8600 and the new process (dnsmasq) binding to 53.  We deployed, and this worked as expected -- stopped consul which was binding to 53, and then started consul bound to 8600 and dnsmasq bound to 53.  We then reverted this change to the release, updated manifest to use the new release, and redeployed.  We expected that this would stop both consul and dnsmasq, and then start up consul binding to 53.  Instead, deploy failed because dnsmasq was still running bound to 53.
1. Why didn’t dnsmasq get killed? Does anything look wrong with https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/dnsmasq_ctl.erb#L22-L25?
2. To remediate this without having to SSH onto every vm and kill the dnsmasq process, I wanted to `bosh -d old-manifest.yml stop` to stop all processes, then `bosh -d new-manifest.yml deploy --recreate`.  Does this seem like the best way to do it?

Thanks

/cc @cloudfoundry/cf-infrastructure @cloudfoundry/cf-release-integration @cloudfoundry/cf-capi

**Comment by Amit-PivotalLabs** [comment]
@tylerschultz wrote:

> I believe this can be explained by a bug that has been present for a long time.  When director tells monit to stop, it may take a while for monit to get around to actually running the ctl stop command. Monit may be busy doing other things, stopping other jobs, daydreaming... whatever it does. Unfortunately, the agent believes stopping is complete because it has issued the monit stop foo command. The agent reports back to director that the job is stopped. Director moves on and then issues an apply call. This call will result in the new job templates replacing the old templates (the templates that would stop dnsmasq are now replaced.) Monit now finnaly gets around to issuing the ctl stop command and the stop *runs against the replaced templates*!!!!  
> 
> Alas, there is a fix:
> 
> Now I can't find the job property on a quick search, hopefully it has been released. Enabling the property will cause agent and director to wait for the stop command to complete, within a timeout, before moving on to the apply step. This seems like something that should be turned on by default, but there is concern that there are many jobs that don't stop well, and it'd be a breaking change for many releases.
> 
> Looking at tracker, it appears the fix may not yet be released. Thinking about it more, it also occurs to me that it's odd that all of the instances suffered from this problem. This leads me to believe something else may be going on.

[[source](https://cloudfoundry.slack.com/archives/bosh/p1473730500000645)]

Thanks.  Yeah, my suspicions are the same.  We know about the race that can happen around stop, but this happened on many VMs in many different environments.  So it's kinda mysterious.  Let me know if you have any further thoughts on that first question.

As for the second question, does that sound like a reasonable approach?  Note that I believe I had to do the deploy with the `--recreate` since a simple `bosh deploy` left the VMs in a stopped state, and `bosh start` didn't start the VMs back up in the correct order (according to the manifest).

**Comment by cppforlife** [comment]
does this happen consistently? can you throw in links to releases i can use to repro in my env?

**Comment by Amit-PivotalLabs** [comment]
I'll close this old issue of mine.

/cc @mfine30 @dpb587 @jfmyers9
