### ISSUE TITLE
Can someone explain to me why this is better than X?

### ISSUE THREAD

**Issue by Freyert** [cloudfoundry/bosh#1437]
This doesn't exist in the documentation, and I have not been able to figure out why I should prefer something like BOSH over something mature like Chef, Puppet, or Ansible.

I've watched several talks, and I don't see what it's doing better or differently, or how the things it does differently could not be done better by something else.

For example, I can't figure out how to do a Blue Green deployment, or a deployment that requires a _specific_ ordering of tasks without writing _copious_ amounts of fair to middling bash scripts with BOSH. Whereas Ansible I could whip something up in a matter of hours. Is BOSH not the right use case for that?

I feel like I'm missing out here. Why do people enjoy using BOSH?

**Comment by poblin-orange** [comment]
Hello,
i guess these pres will help you grasp the value https://www.infoq.com/presentations/bosh-cloud-foundry

The aspects i like most :
1 declarative complex architecture description (analog to puppet, plus inter-service links with bosh 2)
2 end to end support, built in iaas vm provisionning
3 health management / auto repair
4 strong end to end versionning (bosh releases are self sufficient, iaas and os agnostic)
clean externalized configuration
5 best practices built-in. (for example: distinct disk for data and root disk, enabling smooth vm recreation)

Agreed that the declarative approach is not adapted for strong imperative orchestration. Id say its usually an  error to put too much logic in deployment. Microservices architectures tend to have robust small components, able to deal with transient communication failure. Ie, no point in starting the db before the front end, provided the front is able to reconnect on the fly to the db.

**Comment by Freyert** [comment]
@poblin-orange do you manage the VMs with BOSH? There seem to be so many things that the notion of a "job" does not cover. To me it seems like they've gone a "one size fits all route" which is probably more of a reflection on the CPIs.

And BOSH SSH & SCP are a bit worrying to me.

The agents also go unresponsive _all_ the time. Can't every really figure out why from the logs.

**Comment by poblin-orange** [comment]
@Freyert  Sure, Bosh creates and manages all our vms (few hundreds vms)

You have the concept of job/instance groups, and for one-off action, the errands. Bosh ssh is quite a nice feature (sets the private key on the fly on the target vms, let ssh access, then remove when logging off).

Agreed the bootstrap sequence is bit complex, and logs could be improved.
Dont hesitate to ask for help on slack to bootstrap your deployment
https://cloudfoundry.slack.com/messages/bosh/

**Comment by CAFxX** [comment]
@Freyert we also use bosh for all of our VMs and the beauty of bosh is that it manages the full lifecycle of your nodes (VM provisioning, configuration management, rolling updates, recovery). You don't have to mix and mash stuff together: everything is already integrated and works together. 
We migrated from Chef plus something similar to terraform (albeit older and less feature complete) and, even though there are some rough edges here and there, I wouldn't go back for all the money in the world. Obviously, YMMV: if the other tools are good enough for you, there's little to no point in changing.

**Comment by dpb587-pivotal** [comment]
Closing - thanks @poblin-orange + @CAFxX for jumping in!
