### ISSUE TITLE
atp-get update && upt-get install rsyslog commands break the rsyslog dependencies 

### ISSUE THREAD

**Issue by rfreddi** [cloudfoundry/bosh#1438]
Could you help to solve this issue, please?
Thanks in advance

$apt-get update 
$apt-cache policy rsyslog
rsyslog:
  Installed: 8.20.0-0adiscon3trusty1
  Candidate: 8.21.0-0adiscon1trusty1
  Version table:
     8.21.0-0adiscon1trusty1 0
        500 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main amd64 Packages
 **\* 8.20.0-0adiscon3trusty1 0
        100 /var/lib/dpkg/status
     7.4.4-1ubuntu2.6 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
     7.4.4-1ubuntu2.3 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     7.4.4-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages 

> rsyslogd -v
> rsyslogd 8.20.0, compiled with:
>         PLATFORM:                               x86_64-pc-linux-gnu
>         PLATFORM (lsb_release -d):
>         FEATURE_REGEXP:                         Yes
>         GSSAPI Kerberos 5 support:              No
>         FEATURE_DEBUG (debug build, slow code): No
>         32bit Atomic operations supported:      Yes
>         64bit Atomic operations supported:      Yes
>         memory allocator:                       system default
>         Runtime Instrumentation (slow code):    No
>         uuid support:                           Yes
>         Number of Bits in RainerScript integers: 64 
> $ apt-get install rsyslog
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following extra packages will be installed:
>   rsyslog-gnutls rsyslog-mmjsonparse rsyslog-relp
> Suggested packages:
>   rsyslog-mysql rsyslog-pgsql rsyslog-doc rsyslog-gssapi rsyslog-elasticsearch
>   rsyslog-imptcp rsyslog-udpspoof rsyslog-kafka gnutls-bin
> The following packages will be upgraded:
>   rsyslog rsyslog-gnutls rsyslog-mmjsonparse rsyslog-relp
> 4 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.
> Need to get 679 kB of archives.
> After this operation, 3,072 B of additional disk space will be used.
> Do you want to continue? [Y/n] Y
> Get:1 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main rsyslog-gnutls amd64 8.21.0-0adiscon1trusty1 [29.2 kB]
> Get:2 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main rsyslog-relp amd64 8.21.0-0adiscon1trusty1 [29.1 kB]
> Get:3 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main rsyslog-mmjsonparse amd64 8.21.0-0adiscon1trusty1 [22.2 kB]
> Get:4 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu/ trusty/main rsyslog amd64 8.21.0-0adiscon1trusty1 [599 kB]
> Fetched 679 kB in 0s (3,578 kB/s)
> (Reading database ... 66384 files and directories currently installed.)
> Preparing to unpack .../rsyslog-gnutls_8.21.0-0adiscon1trusty1_amd64.deb ...
> Unpacking rsyslog-gnutls (8.21.0-0adiscon1trusty1) over (8.20.0-0adiscon3trusty1) ...
> Preparing to unpack .../rsyslog-relp_8.21.0-0adiscon1trusty1_amd64.deb ...
> Unpacking rsyslog-relp (8.21.0-0adiscon1trusty1) over (8.20.0-0adiscon3trusty1) ...
> Preparing to unpack .../rsyslog-mmjsonparse_8.21.0-0adiscon1trusty1_amd64.deb ...
> Unpacking rsyslog-mmjsonparse (8.21.0-0adiscon1trusty1) over (8.20.0-0adiscon3trusty1) ...
> Preparing to unpack .../rsyslog_8.21.0-0adiscon1trusty1_amd64.deb ...
> Unpacking rsyslog (8.21.0-0adiscon1trusty1) over (8.20.0-0adiscon3trusty1) ...
> Processing triggers for ureadahead (0.100.0-16) ...
> Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
> Setting up rsyslog (8.21.0-0adiscon1trusty1) ...
> Skipping profile in /etc/apparmor.d/disable: usr.sbin.rsyslogd
> invoke-rc.d: dangling symlink: /etc/rc2.d/S20rsyslog
> dpkg: error processing package rsyslog (--configure):
>  subprocess installed post-installation script returned error exit status 102
> dpkg: dependency problems prevent configuration of rsyslog-gnutls:
>  rsyslog-gnutls depends on rsyslog (= 8.21.0-0adiscon1trusty1); however:
>   Package rsyslog is not configured yet.

dpkg: error processing package rsyslog-gnutls (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of rsyslog-relp:
 rsyslog-relp depends on rsyslog (= 8.21.0-0adiscon1trusty1); however:
  Package rsyslog is not configured yet.

dpkg: error processing package rsyslog-relp (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of rsyslog-mmjsonparse:
 rsyslog-mmjsonparse depends on rsyslog (= 8.21.0-0adiscon1trusty1); however:
  Package rsyslog is not configured yet.

dpkg: error processing package rsyslog-mmjsonparse (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 rsyslog
 rsyslog-gnutls
 rsyslog-relp
 rsyslog-mmjsonparse
E: Sub-process /usr/bin/dpkg returned an error code (1) 

Best Regards
Remo

**Comment by dpb587-pivotal** [comment]
Which stemcell are you using? Possibly 3262.9? If so, you might want to try on 3262.12. The `invoke-rc.d: dangling symlink: /etc/rc2.d/S20rsyslog` message is suspicious and may have been due to improper rsyslog upstart configuration which was fixed in 3262.12.

Otherwise, the post-installation script of rsyslog failed - perhaps investigate why that script failed and see what the output is which may make it easier to diagnose.

**Comment by mattcui** [comment]
@rfreddi We are waiting BOSH community for publishing a new base image which includes the latest fixes of bosh agent, once it's available, we will build a new version of stemcell for your test again. Thanks.

**Comment by rfreddi** [comment]
@dpb587-pivotal 
we are using the following stemcell:
| bosh-softlayer-esxi-ubuntu-trusty-go_agent | ubuntu-trusty | 3262.7* | 1282653 |
Thanks a lot for the information!

@mattcui, please when the new stemcell is available could you update the test environment?
Thanks in advance.
