### ISSUE TITLE
bosh vms --dns return two dns name for a vm

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry/bosh#1439]
I am using bosh-init,bosh-257.9.tgz and cf-233 .Stemcell 3262.2

DNS host name is not resolving while deploying cloud foundry.On exploring I get two entry for cloud controller and other vm in powerdns db postgres.

95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh
0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh

**In horizone**

95a07d80-3fb8-40db-8a13-3c295755b066 is not VM instance ID ,but it is present in metdata section of
of the VM
NAME cloud_controller/95a07d80-3fb8-40db-8a13-3c295755b066
DEPLOYMENT cf-installer-team-test
ID 95a07d80-3fb8-40db-8a13-3c295755b066

![image](https://cloud.githubusercontent.com/assets/16615487/18511320/b4ba3e0e-7aa0-11e6-9398-8a220ae8991c.png)

These two host name is not pingable in director and in respective also.
0.consul.ccc-bosh-net.cf-installer-team-test.microbosh
0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh

**bosh vms --dns**

| cloud_controller/0              | starting | large                             | 10.20.0.231 | 95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh |
|                                 |          |                                   |             | 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh                                    |

| consul/0                        | running  | small                             | 10.20.0.232 | 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.microbosh           |
|                                 |          |                                   |             | 0.consul.ccc-bosh-net.cf-installer-team-test.microbosh                  

**powerdns entry in postgres DB.**

  4 | 0.consul.ccc-bosh-net.cf-installer-team-test.microbosh                                              | A    | 10.20.0.232

  5 | 0.20.10.in-addr.arpa                                                                                | SOA  | localhost hostmaster@localhost 0 10800 604800 30

  6 | 0.20.10.in-addr.arpa                                                                                | NS   | ns.microbosh

  7 | 232.0.20.10.in-addr.arpa                                                                            | PTR  | 0.consul.ccc-bosh-net.cf-installer-team-test.microbosh

  8 | 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.microbosh           | A    | 10.20.0.232

  9 | 232.0.20.10.in-addr.arpa                                                                            | PTR  | 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.mi
crobosh

 **10 | 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh                                    | A    | 10.20.0.231

 11 | 231.0.20.10.in-addr.arpa                                                                            | PTR  | 0.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh

 12 | 95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-team-test.microbosh | A    | 10.20.0.231

 13 | 231.0.20.10.in-addr.arpa                                                                            | PTR  | 95a07d80-3fb8-40db-8a13-3c295755b066.cloud-controller.ccc-bosh-net.cf-installer-te**
am-test.microbosh
  1 | microbosh                                                                                           | SOA  | localhost hostmaster@localhost 0 10800 604800 30
  2 | microbosh                                                                                           | NS   | ns.microbosh
  3 | ns.microbosh                                                                                        | A    |

-------------------------------
**bosh-init.yml**
----------------

`<%
      load 'bosh-init/bosh-init.rb'
%>

name: <%= $os_tenant %>

releases:
- name: bosh
  url: '<%= $bosh_director_release_url %>'
  sha1: <%= $bosh_director_sha %>
- name: bosh-openstack-cpi
  url: <%= $bosh_openstack_cpi %>
  sha1: <%= $bosh_openstack_cpi_sha %>

resource_pools:
- name: vms
  network: private
  stemcell:
    url: <%= $stemcell_path %>
    sha1: <%= $stemcell_sha1 %>
  cloud_properties:
    instance_type: <%= $bosh_flavor %>
    #availability_zone: soltes2

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range: <%= $cidr %> # <--- Replace with a private subnet CIDR
    gateway: <%= $gateway_ip %> # <--- Replace with a private subnet's gateway
    dns: [10.20.0.3] # <--- Replace with your DNS
    cloud_properties: {net_id: <%= $net_id %>} # <--- # Replace with private network UUID
- name: public
  type: vip

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: powerdns, release: bosh}
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: openstack_cpi, release: bosh-openstack-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - name: private
    static_ips: [<%= $bosh_director_ip %>] # <--- Replace with a private IP
    default: [dns, gateway]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: <%= $bosh_director_ip %> # <--- Replace with a private IP
      host: <%= $bosh_director_ip %> # <--- Replace with a private IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: <%= $bosh_director_ip %> # <--- Replace with a private IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: openstack_cpi
      max_threads: 3
      user_management:
        provider: local
        local:
          users:
          - {name: <%= $bosh_username %>, password: <%= $bosh_password %>}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    dns:
      address: "127.0.0.1"
      domain_name: "microbosh"
      db: *db

    openstack: &openstack
      auth_url: "<%= $os_auth_url%>" # <--- Replace with OpenStack Identity API endpoint
      project: iwan-soltest # <--- Replace with OpenStack project name
      domain: VMS # <--- Replace with OpenStack domain name
      username: "<%= $os_username %>" # <--- Replace with OpenStack username
      api_key: "<%= $os_password %>" # <--- Replace with OpenStack password
      tenant:  "<%= $os_tenant%>"
      default_key_name: <%= $key_name %>
      default_security_groups: [vms-security-group]
      ignore_server_availability_zone: true

    agent: {mbus: "nats://nats:nats-password@<%=$bosh_director_ip %>:4222"} # <--- Replace with a private IP

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: openstack_cpi, release: bosh-openstack-cpi}

  ssh_tunnel:
    host: <%=$bosh_director_ip %> # <--- Replace with a floating IP
    port: 22
    user: vcap
    private_key: <%= $key_file %> # Path relative to this manifest file

  mbus: "https://mbus:mbus-password@<%=$bosh_director_ip %>:6868" # <--- Replace with a floating IP

  properties:
    openstack: *openstack
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
`

**Comment by tylerschultz** [comment]
What are the dns addresses specified in the network subnet for the deployed cf instances? It needs to include the director's ip address.

**Comment by chrisrana** [comment]
I didnt get you .Just to inform you same cf 233 works fine with microbosh.
 I am facing this issue in bosh-init.But problem here is why we have two host entry is mapped with single IP in postgres DB  for a vm instance.I having feeling that because  of this host name is not resolving.PLease refer image pasted there it show bosh vms output

**Comment by tylerschultz** [comment]
The 2 dns entries are expected behavior. One address is the index based address. The other address is the instance uuid based address. The index is something that we'd like to eventually hide away and not expose, as a long term goal. Can you explain why you think having 2 DNS entries is a problem?

What is the contents of `/etc/resolf.conf` in one of the deployed vms? Does it contain the director's ip address?

What happens when you run `dig @<director-ip-address> 48d2b0a4-8533-4b7d-a3c5-b11ab463e910.consul.ccc-bosh-net.cf-installer-team-test.microbosh` from inside one of the deployed vms?

The cf manifest should have a networks section that the jobs reference. There is likely a dns key/value on each subnet. What is the value seen there?

**Comment by chrisrana** [comment]
I was not aware about 2dns entries thanks for info.
I checked /etc/resolv.conf It doesnot contain bosh director IP.

**Comment by tylerschultz** [comment]
I think I see the problem. I followed the code through and it automatically adds the power dns server address to the configuration on each instance. I see that your dns.address is 127.0.0.1. This should be the private address of your director.

**Comment by chrisrana** [comment]
Thanks tylers. It worked like a charm.
