### ISSUE TITLE
Director uuid check for cloud-config

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/bosh#1441]
In the current workflow updating the cloud-config there is no way to specify that the cloud config belongs to a particular director. Like in the case of deployment the cloud-config.yml doesn't support the `director_uuid` tag. This has lead to accidental uploading of cloud-config's to a different director due to manual error. 

Can we add an optional `director_uuid` check for the cloud-config as well?

**Comment by cppforlife** [comment]
we are planning to require users to enter --target (-t) in the new bosh cli for every command since we are removing director_uuid altogether.
