### ISSUE TITLE
BOSH DEPLOY Error 100 uaa.yml.erb

### ISSUE THREAD

**Issue by swilliamsvi** [cloudfoundry/bosh#1444]
Used cf-stub at: https://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html
bosh create release and bosh upload work. bosh deploy creates the following error:

**NOTE:** Revised admin passwords to NOT have special characters.

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'uaa_z1'. Errors are:
     - Unable to render templates for job 'uaa'. Errors are:
       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)
   - Unable to render jobs for instance group 'uaa_z2'. Errors are:
     - Unable to render templates for job 'uaa'. Errors are:
       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)

Bosh Debug output:

D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:WHCF uid: 1a6b31bf-49b8-4852-9149-8dda4ca0b9f4
I, [2016-09-22 02:36:41 #13569] [task:20]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"85958601-2a90-4180-8c45-72c56abe3b09","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'WHCF' against Director 'bf9e34d8-325f-47f5-85bd-0b48d6f854ed': #<RuntimeError: Unable to render instance groups for deployment. Errors are:\n   - Unable to render jobs for instance group 'uaa_z1'. Errors are:\n     - Unable to render templates for job 'uaa'. Errors are:\n       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)\n   - Unable to render jobs for instance group 'uaa_z2'. Errors are:\n     - Unable to render templates for job 'uaa'. Errors are:\n       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)>","created_at":1474511801}
E, [2016-09-22 02:36:41 #13569] [task:20] ERROR -- DirectorJobRunner: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'uaa_z1'. Errors are:
     - Unable to render templates for job 'uaa'. Errors are:
       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)
   - Unable to render jobs for instance group 'uaa_z2'. Errors are:
     - Unable to render templates for job 'uaa'. Errors are:
       - Error filling in template 'uaa.yml.erb' (line 236: undefined method `+' for nil:NilClass)
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/update_deployment.rb:175:in `render_job_templates'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/update_deployment.rb:84:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/update_deployment.rb:64:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/job_runner.rb:94:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/job_runner.rb:32:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.9.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/job_runner.rb:32:in `run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/db_job.rb:30:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.9.0/lib/bosh/director/jobs/db_job.rb:78:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: (0.000080s) SELECT NULL
D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: (0.000052s) BEGIN
D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: (0.000237s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-09-22 02:36:41.085044+0000', "description" = 'create deployment', "result" = 'Unable to render instance groups for deployment. Errors
   - Unable to render jobs for instance group ''uaa_z1''. Errors...', "output" = '/var/vcap/store/director/tasks/20', "checkpoint_time" = '2016-09-22 02:36:37.831866+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'WHCF', "started_at" = '2016-09-22 02:36:37.831809+0000' WHERE ("id" = 20)
D, [2016-09-22 02:36:41 #13569] [task:20] DEBUG -- DirectorJobRunner: (0.000806s) COMMIT
I, [2016-09-22 02:36:41 #13569] []  INFO -- DirectorJobRunner: Task took 3.257565093 seconds to process.

**Comment by tylerschultz** [comment]
I suspect this is a bug in the uaa release, or a bug in the documentation. Bosh director has supplied a set of variables, from your deployment manifest, to the uaa.yml.erb template found in the uaa release, and the erb template threw a nil reference error when it was evaluated. You may have better luck opening an issue in [uaa release repo](https://github.com/cloudfoundry/uaa-release). You may also find help in the [uaa](https://cloudfoundry.slack.com/messages/uaa/) slack channel, or in the [cf-users](https://cloudfoundry.slack.com/messages/cf-users/) slack channel.

**Comment by cppforlife** [comment]
@swilliamsvi yup. looks like uaa release configuration.
