### ISSUE TITLE
Getting a timeout issue to S3 blobstore deploying cf to AWS

### ISSUE THREAD

**Issue by blade2005** [cloudfoundry/bosh#1445]
Attempting to deploy to cf to AWS. Getting a timeout issue to S3 blobstore.

```
   Failed compiling packages > haproxy/f5d89b125a66892628a8cd61d23be7f9b0d31171: Action Failed get_task: Task e0810322-a8c4-45ce-617a-c2d60d9f9a89 result: Compiling package haproxy: Fetching package haproxy: Fetching package blob 6a0fb129-6583-4ef4-81db-f70317b9c68e: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json get 6a0fb129-6583-4ef4-81db-f70317b9c68e /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get123183875', stdout: '', stderr: '2016/09/22 18:15:19 performing operation get: RequestError: send request failed
caused by: Get https://s3-us-west-2.amazonaws.com/pst-cf-wordpress/6a0fb129-6583-4ef4-81db-f70317b9c68e: dial tcp 54.231.168.164:443: i/o timeout
': exit status 1 (00:08:37)
```

security group is outbound
```
HTTP          TCP   80     0.0.0.0/0
All traffic   All   All    0.0.0.0/0
HTTPS         TCP   443    0.0.0.0/0
```

**Comment by cppforlife** [comment]
@blade2005 does your compilation machine has internet access? doesnt look like it's in a subnet that has network connectivity.

**Comment by blade2005** [comment]
Alright for the time being I changed the compilation network to cf_public
```
compilation:
  workers: 6
  network: cf_public
```

This has corrected the issue.

Now I also switched the cf_private subnet setting to autoassing public dns which should force in aws public routing. I will rerun my deploy with cf_private as the subnet once this one completes.

**Comment by cppforlife** [comment]
@blade2005 since you configured director to use s3 blobstore all your machines have to have *outbound* internet access so that they can download/upload blobs necessary during the deploy. typically people use nat gateway/instance to provide outbound access. alternatively you can look up how to use private s3 endpoints.
