### ISSUE TITLE
Wrong fs type while mounting /dev/loop0 on Google Cloud Platform

### ISSUE THREAD

**Issue by FrostLucker** [cloudfoundry/bosh#1448]
I am new with Cloud foundry. I have added cloud foundry for google compute engine platform by this series of guides [Deploying Cloud Foundry on Google Compute Engine](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/cloudfoundry/README.md).

Terraform was used for creating needed infrastructure. It seemed all was fine I didn't get any errors during deployment cloud foundry itself and **bosh cck** command shows that there are no any problems. But when I tried to deploy my hello world app, I got next error message in terminal after cf push command:

Creating container Failed to create container
FAILED
Error restarting application: StagingError.

In logs on garden server I found:

```
{
   "timestamp":"1474637304.026303530",
   "source":"garden-linux",
   "message":"garden-linux.loop-mounter.mount-file.mounting",
   "log_level":2,
   "data":{
      "destPath":"/var/vcap/data/garden/aufs_graph/aufs/diff/08829a3252c1d60729e3b5482b0fb109652c9ab5beff9724e4e4ae756a0bc3ce",
      "error":"exit status 32",
      "filePath":"/var/vcap/data/garden/aufs_graph/backing_stores/08829a3252c1d60729e3b5482b0fb109652c9ab5beff9724e4e4ae756a0bc3ce",
      "output":"mount: wrong fs type, bad option, bad superblock on /dev/loop0,\n       missing codepage or helper program, or other error\n       In some cases useful info is found in syslog - try\n       dmesg | tail  or so\n\n",
      "session":"2.276"
   }
}{
   "timestamp":"1474637304.026949406",
   "source":"garden-linux",
   "message":"garden-linux.pool.acquire.provide-rootfs-failed",
   "log_level":2,
   "data":{
      "error":"mounting file: mounting file: exit status 32",
      "handle":"ec6e7469-0ef0-48a8-bcd0-82f4a2ea173f-5de2e641d9284aeea209ca447ffffb6d",
      "session":"9.545"
   }
}
```

I'm not sure, but I believe that this issue has same solution as [**google compute engine mounting persistant disk issues** ](http://stackoverflow.com/questions/21736369/google-compute-engine-mounting-persistant-disk-issues)

**Comment by dpb587-pivotal** [comment]
Sounds like you may be using the 3263 stemcell version with an older version of garden. Make sure you're on a [recent version](http://bosh.io/releases/github.com/cloudfoundry-incubator/garden-linux-release?all=1) of garden ([v0.340+](https://github.com/cloudfoundry/garden-linux-release/releases/tag/v0.340.0)). There were incompatibilities with the 4.4 kernel which would show this error.

You can also try bumping the stemcell version, there have been a few fixes for GCE stemcells lately.

**Comment by FrostLucker** [comment]
Thanks for answering @dpb587-pivotal , I will give it a try.

**Comment by johnsonj** [comment]
You can also try using a recent release of the 3262 stemcell, eg: `https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3262.19`.

[We've updated](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/commit/960bb37463198a150cd4d83eb2b6ac8e32dc2052) our cloudfoundry docs in the cpi to properly reflect this.
