### ISSUE TITLE
Pre-start scripts fail when erb tags are before shebang

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry/bosh#1452]
When building a release, I noticed the pre-start script was failing with a generic error:

`result: 1 of 1 pre-start scripts failed. Failed Jobs: my_job.`

SSHing onto the machine and running the script manually worked fine. Weird.

The issue seems to be caused by using erb tag markers (`<% ... %>`) before the bash shebang in the script, like this:

```
<%
  my_variable = p('whatever')
%>

#!/usr/bin/env bash
...
```

Not sure if this is a known bug, or if it should be documented somewhere – I couldn't see any mention of this in the docs and it wasn't obvious to me. Happy to PR in a docs edit if that's the right thing to do.

**Comment by cppforlife** [comment]
shebang must be on the first line of the *rendered* template. clarification docs pr would be nice.

**Comment by dpb587-pivotal** [comment]
Thanks for the docs PR! Closing this in favor of that PR.
