### ISSUE TITLE
Enhancement Request:  bosh -d manifest.yml ssh result sorting 

### ISSUE THREAD

**Issue by kitsirota** [cloudfoundry/bosh#1458]
Its rather annoying to have all the cells and instances in the SSH menu to show out of order for each deployment.  

Please add alphanumeric ordering of instances in the SSH menu.

Thank you!

**Comment by dpb587-pivotal** [comment]
I think, in the future, the intention is to use `bosh instances` if you need to identify which specific instance you may want; then pass the `name/id` as the argument to `bosh ssh`. Generally, you already know which specific instance you're interested in before attempting to connect (from logs or alerts), or you're trying to multi-ssh on a full instance group.

If it's important to you, can you describe the use case in which you don't know the instance you want to connect to beforehand and need to rely on `bosh ssh` enumerating them?

**Comment by cppforlife** [comment]
@kitsirota future CLI (https://github.com/cloudfoundry/bosh-cli) doesnt provide interactive menu since it doesnt scale when there are a lot of instances.
