### ISSUE TITLE
Feature Request: bosh "archive" deployment functionality

### ISSUE THREAD

**Issue by kitsirota** [cloudfoundry/bosh#1459]
Sometimes its not clear if one of our deployments is a duplicate or something that was used for testing and is no longer needed.  It would be great if we could archive deployments before completely deleting them.  We are using vSphere, but other environments should be able to do something along these lines.

The proposal is to make bosh archive suspend the VMs in their current state saving everything in memory including containers to disk (vmware does this natively, but other hypervisors offer similar capabilities).  Once all the VMs in the deployment are suspended, the deployment effectively frees up its reserved IP range and enables us to deploy over it.  In the event that we need to bring this environment back, we should be able to free up the subnet block allocated to the archived deployment and start it back up without modifying the runtime config, loosing any data and changing the network config of the deployment.

**Comment by mfine30** [comment]
Hey @kitsirota it doesn't look like this issue has gotten much traction. This isn't a feature which is on our near/mid-term roadmap right now, so I'm going to go ahead and close this. If you or others have more thoughts on how this might work in the future, please let us know.
