### ISSUE TITLE
Bosh deploy: Provide option to only restart changed jobs 

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/bosh#1465]
When bosh deploy, it will stop all monit jobs in vm, even when there is a minor change.

It is reasonable because it keeps the correctness of deployement, however it is pretty annoy sometimes.

For instance, we want to update our collectd configuration, but it restarts nfs/ccdb... everything.

It will be better if bosh offers an option to not restarting every jobs (in the case that admin knows what he is doing)

**Comment by cppforlife** [comment]
i'm still conflicted about introducing this feature. we'll take this into account during discussion of how certain jobs should wait for other jobs to start/stop.

**Comment by liuweichu** [comment]
Looking forward to that 🗡

**Comment by mfine30** [comment]
This isn't a feature which is on our near/mid-term roadmap right now, so I'm going to go ahead and close this.

At scale, our recommendation would be to avoid collocation where possible, and focus on service specific, redundant instance groups.
