### ISSUE TITLE
[cf-release 244] Error 80013: Job `loggregator_trafficcontroller' has invalid spec format: 'provides' needs to be an array of strings

### ISSUE THREAD

**Issue by jerryatge** [cloudfoundry/bosh#1466]
This issue happens to the latest cf-release 244, when running 'bosh upload release https://bosh.io/d/github.com/cloudfoundry/cf-release?v=244', the command fails with an error Error 80013: Job `loggregator_trafficcontroller' has invalid spec format: 'provides' needs to be an array of strings.

Below are the full command line and output:

[root@ip-10-0-0-238 ~]# bosh upload release https://bosh.io/d/github.com/cloudfoundry/cf-release?v=244
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'
Using remote release 'https://bosh.io/d/github.com/cloudfoundry/cf-release?v=244'

Director task 25
  Started downloading remote release > Downloading remote release. Done (00:01:41)

  Started extracting release > Extracting release. Done (00:01:51)

  Started verifying manifest > Verifying manifest. Done (00:00:00)

  Started resolving package dependencies > Resolving package dependencies. Done (00:00:00)

  Started creating new packages
  Started creating new packages > acceptance-tests/268998183343694b709bf69dbb69b969ea3a80a9. Done (00:00:01)
  Started creating new packages > binary-buildpack/fa621a71b4134c3ffc628c63d4ed583a3e193c21. Done (00:00:01)
  Started creating new packages > blobstore_url_signer/09ff302425c2edda6bc8c6275585cc86acffa473. Done (00:00:00)
  Started creating new packages > buildpack_java/1ade0d537179179833411f7497fde535fa7e1600. Done (00:00:00)
  Started creating new packages > buildpack_java_offline/1ef9be52c71df0a41e956ec0abc64954de5faa27. Done (00:00:11)
  Started creating new packages > capi_utils/f0746a954b2d4ab7bf905b8bc742584801e21357. Done (00:00:00)
  Started creating new packages > cc_uploader/649450357682fb4944a193a0a9a19edb54b057b6. Done (00:00:00)
  Started creating new packages > cli/60a741596e7fc803f45c9628364b21d1b247550b. Done (00:00:00)
  Started creating new packages > cloud_controller_ng/c0a03b6873a656c6fd7f3c8c3b28f913937869bd. Done (00:00:00)
  Started creating new packages > collector/9f8dfbcbcfffb124820327ad2ad4fee35e51d236. Done (00:00:01)
  Started creating new packages > common/953ccbc1b39fc972d2b4903beb16af7daf78cc85. Done (00:00:01)
  Started creating new packages > confab/90e1b7a537f8832df36863bf94225e460f94d816. Done (00:00:00)
  Started creating new packages > consul/c114e20968d91e1095d4d3282265cc65ad98d9c6. Done (00:00:00)
  Started creating new packages > dea_logging_agent/6bb21f3a0fb68496973398568c26aae8bc4ee27a. Done (00:00:00)
  Started creating new packages > dea_next/fce27aa39ff2b95342bfdad1813bbc32d5dc05ff. Done (00:00:01)
  Started creating new packages > debian_nfs_server/aac05f22582b2f9faa6840da056084ed15772594. Done (00:00:00)
  Started creating new packages > doppler/e579418676bbd5d1c8b37b12df0c226a1b7156c2. Done (00:00:00)
  Started creating new packages > etcd/015a370c4578c19dd3578329477b1f1a549f0c60. Done (00:00:00)
  Started creating new packages > etcd-common/0f365b3a98184c2a6537efd51f67e8d5e9d2c486. Done (00:00:00)
  Started creating new packages > etcd-dns-checker/9676918944de93dd773b706cc7ecc68073492372. Done (00:00:00)
  Started creating new packages > etcd_metrics_server/e498285a38c9d86eac759e40c05af6ea77fe9456. Done (00:00:00)
  Started creating new packages > gnatsd/81f9a5debd447ad76ad55cae5b558a3a9a1dd1e1. Done (00:00:00)
  Started creating new packages > go-buildpack/a5b00102be424bff50b40929d134a61b147b7dd2. Done (00:00:18)
  Started creating new packages > golang1.6/5dd4024894667ba7f647b883bbff25c04960e5c1. Done (00:00:02)
  Started creating new packages > golang1.7-windows/b179e460d5d151def77ad8cb43c4043736bba984. Done (00:00:03)
  Started creating new packages > golang1.7/48ce7b3927e6f7e6576fff21a7dc9d22b7ba9c62. Done (00:00:02)
  Started creating new packages > gorouter/6d8070291fd5568f0a67dcbe9d5c9316fd0ada6d. Done (00:00:01)
  Started creating new packages > haproxy/f5d89b125a66892628a8cd61d23be7f9b0d31171. Done (00:00:00)
  Started creating new packages > hm9000/7e2701aa5baa845503db0800ffc6f30e7bf90c38. Done (00:00:00)
  Started creating new packages > libmariadb/90d7836132e02bb570d91f08c9e116c394888d75. Done (00:00:01)
  Started creating new packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d. Done (00:00:00)
  Started creating new packages > loggregator_common/6e89e9e4c155576dfc47b5959887807831ddf2df. Done (00:00:00)
  Started creating new packages > loggregator_trafficcontroller/07cfc642ce53b757856fcae45793d92cc4175afa. Done (00:00:00)
  Started creating new packages > metron_agent/c23eac93d8c8780326757d51f26b5ff17c223271. Done (00:00:00)
  Started creating new packages > metron_agent_windows/557e7ddc6c316edd66fb325e2565763411ca48d2. Done (00:00:00)
  Started creating new packages > nats/9da10677048bd8c1237ae5f14ffe6be34ad16def. Done (00:00:00)
  Started creating new packages > nats-common/1f712a21c0b1cbb3b547eccc79eb159aaee48b99. Done (00:00:00)
  Started creating new packages > nginx/b7c8aadb18d53f81a7455e447c5941313872b81d. Done (00:00:00)
  Started creating new packages > nginx_newrelic_plugin/2de1c5ba9dec62be54c9ff4ed3b32a126463e0d8. Done (00:00:01)
  Started creating new packages > nginx_webdav/ee1d48cbce7f78f1395b12837a500c11e5066fa7. Done (00:00:00)
  Started creating new packages > nodejs-buildpack/21a74d94e2f5c62295d64b5b666ae2b7a35fc325. Done (00:00:03)
  Started creating new packages > nsync/cffc4ec5342e1c8166d7ee51d50c7cd40d98f467. Done (00:00:00)
  Started creating new packages > php-buildpack/98c3c2392038d8b1b06a1c071425e2a4abf282e4. Done (00:00:13)
  Started creating new packages > postgres-9.4.9/8a20abd4ccec4d356cc29169d38be561d99bc1ff. Done (00:00:01)
  Started creating new packages > postgres-common/368d38d49a3cc717559ebcdb2390b68882a85053. Done (00:00:00)
  Started creating new packages > python-buildpack/74ea078a8e7084f686cc9c0b16316003cf214890. Done (00:00:11)
  Started creating new packages > rootfs_cflinuxfs2/1ec3248972ea28586329a1cec7fe0907d64c4ca9. Done (00:00:11)
  Started creating new packages > route_registrar/0d3addc06d9d1244f55464033de5d64f1c30bdb7. Done (00:00:00)
  Started creating new packages > routing_utils/5338d023e081fe68ed00d236ec0c335477476ace. Done (00:00:00)
  Started creating new packages > ruby-2.1.8/0a758a4dc3408937b64f89aaa39f8ee25cce5454. Done (00:00:01)
  Started creating new packages > ruby-2.2.5/1471d078219e7aee8cb9c0ab1aefabbec561bfa7. Done (00:00:00)
  Started creating new packages > ruby-2.3/debd726c1edb8dea8654bb3c46539a4ee75bff75. Done (00:00:01)
  Started creating new packages > ruby-buildpack/459732951bdc845306ff0fc95fabfe84f420762d. Done (00:00:11)
  Started creating new packages > smoke-tests/516b0d5de3e0ecf3d135d9f20d90ff357815dab1. Done (00:00:00)
  Started creating new packages > stager/f728cc3daa129cf770cad04a0e55732412e7f8fd. Done (00:00:00)
  Started creating new packages > staticfile-buildpack/bcc484648d025e0570ccb9da6fe6a402ac68ffb0. Done (00:00:00)
  Started creating new packages > statsd-injector/32056a79ed2528b5f307deb6af137a12242bb35a. Done (00:00:00)
  Started creating new packages > syslog_drain_binder/a7ef8a45870b35b2b5d90d947b5441e02ccef02c. Done (00:00:00)
  Started creating new packages > tps/f44fefab3ac67ec502448d8e358b1b48118d4a5d. Done (00:00:00)
  Started creating new packages > uaa/7a8499a14f4376e90d043b3d450e9b5880f36932. Done (00:00:06)
  Started creating new packages > uaa_utils/fc2e416c5af94d6293ac70bb594c984e31097fb7. Done (00:00:00)
  Started creating new packages > warden/7c3205a9b0a66ed816b1d2bd335139c888abb5c0. Done (00:00:00)
     Done creating new packages (00:01:42)

  Started creating new jobs
  Started creating new jobs > acceptance-tests/8d90b7e8fb55a710beb8c4f1d796694504b0f307. Done (00:00:00)
  Started creating new jobs > binary-buildpack/e2753ad7c384717801a27475b99bdea16669685d. Done (00:00:00)
  Started creating new jobs > blobstore/bc2d50c5327c75f73b55d452cbdf13bf287aca4d. Done (00:00:00)
  Started creating new jobs > cc_uploader/424c2f1e9bd5155ac4bca013f516f22217b41e04. Done (00:00:00)
  Started creating new jobs > cloud_controller_clock/7420416758822919d475a6f00ac266f7f1f7c28e. Done (00:00:00)
  Started creating new jobs > cloud_controller_ng/5c02248d969354db2adc01ba3d465baee96404dd. Done (00:00:00)
  Started creating new jobs > cloud_controller_worker/fee0e53ead8cd7fef760262503286db6e1498bd7. Done (00:00:00)
  Started creating new jobs > collector/6c210292f18d129e9a037fe7053836db2d494344. Done (00:00:00)
  Started creating new jobs > consul_agent/93ca8f0119b677b4d92ebda2a2229b4b9ebf3935. Done (00:00:01)
  Started creating new jobs > dea_logging_agent/59de9485646549194e501ce2878449842943020c. Done (00:00:00)
  Started creating new jobs > dea_next/5cecdadcca5d7ecb2c9449921ac7729dda8ca692. Done (00:00:00)
  Started creating new jobs > debian_nfs_server/8c6159eca06f8b8dfbea48f9885340ba2fca6baf. Done (00:00:00)
  Started creating new jobs > doppler/12131dace83a7ad57bc4f327304aaf0d8d419adc. Done (00:00:00)
  Started creating new jobs > etcd/82302ab1804781dd95d1ca42969875c7bd117d4d. Done (00:00:00)
  Started creating new jobs > etcd_metrics_server/bdc92c5015d760d2c8531a6ca1e3539d4beebbe9. Done (00:00:00)
  Started creating new jobs > go-buildpack/6a96c195d72160f64d4624612c235fe0142f0a42. Done (00:00:00)
  Started creating new jobs > gorouter/396d41e7ef1ccc87a9819418b599243d6465683e. Done (00:00:00)
  Started creating new jobs > haproxy/d675c47a91714fc11d4f7b802f187e26e31281bc. Done (00:00:00)
  Started creating new jobs > hm9000/5d6b6e516e641dfcac4884bd0105b8d01481258a. Done (00:00:00)
  Started creating new jobs > java-buildpack/3129e468525792deb8d482d5fea6bed79c585f95. Done (00:00:00)
  Started creating new jobs > java-offline-buildpack/baba85203f19cb43788847dc5b06f4cb594e63fe. Done (00:00:00)
  Started creating new jobs > loggregator_trafficcontroller/08fead00ce93db58a19ad3a13639ec1bdc3a1b5c. Failed: Job `loggregator_trafficcontroller' has invalid spec format: 'provides' needs to be an array of strings (00:00:00)

Error 80013: Job `loggregator_trafficcontroller' has invalid spec format: 'provides' needs to be an array of strings

Task 25 error

For a more detailed error report, run: bosh task 25 --debug

[root@ip-10-0-0-238 ~]# bosh releases
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'

+------+----------+-------------+
| Name | Versions | Commit Hash |
+------+----------+-------------+
| cf   | 244      | e2198e12+   |
+------+----------+-------------+
(+) Uncommitted changes

Releases total: 1

**Comment by dpb587-pivotal** [comment]
Sounds like you have an old director. Upgrade to a recent director which understands the newer release metadata.

**Comment by dennisjbell** [comment]
This is also happening in the latest bosh-lite available (https://github.com/cloudfoundry/bosh-lite.git , commit:566dbe0, last updated Aug 31)

**Comment by voelzmo** [comment]
@dennisjbell Latest bosh-lite works well with links. Make sure you upgrade your vagrant VM after pulling the most recent state from the repo.
```
vagrant destroy -f
vagrant box update
vagrant up --provider virtualbox
```
