### ISSUE TITLE
bosh health manager reports metrics with incomplete names

### ISSUE THREAD

**Issue by holgero** [cloudfoundry/bosh#1468]
Bosh health manager intermittently reports via its graphite plugin metrics with names where the deployment name is missing. These metrics contain usually only one value. This means we have e.g. a metric with the name `CF..cell_z1.22b7cd86-cb63-4599-99b6-9da3b4faf529.0d0e45d8-87ca-420a-a086-d7613f1b6fd1.system_cpu_sys` that contains just one value and another metric with the correct name `CF.cf-diego.cell_z1.22b7cd86-cb63-4599-99b6-9da3b4faf529.0d0e45d8-87ca-420a-a086-d7613f1b6fd1.system_cpu_sys` which contains the expected values (one per minute).

This seems to occur often, but only for a short period of time (during startup of a new VM or at shutdown?).

The effect for us is that we have many useless metric names in the database (which is annoying in the Grafana dashboard editor, it displays a dropdown menu of the metric names). Would it be a good idea to filter out metrics without deployment names set in the health manager graphite plugin? If we created a pull request for that change, would it have a chance to get accepted?

**Comment by holgero** [comment]
I created a pull request anyway: #1473

**Comment by dpb587-pivotal** [comment]
Closing - as of ~v260.1, this should be working properly.
