### ISSUE TITLE
Ability to see why a job/instance was upgraded/deployed/recreated

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1470]
As an operator during a `bosh deploy`, I'd like to be able to view *why* a job/instance is being subjected to `Started updating job...`.

For example, I'm deploying a small manifest change that affects only one job, but several other jobs are being updated; indeed on occasion they are literally being recreated. Is there currently a way to find out why? Could we add such a feature or information into `bosh task --debug` logs?

**Comment by drnic** [comment]
Ok, trawling thru task logs I can see things like:

```
D, [2016-10-11 06:26:31 #11395] [canary_update(cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45))] DEBUG -- DirectorJobRunner: networks_changed? obsolete reservations: [{ip=10.9.1.191, network=etcd1, instance=cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45), reserved=true, type=dynamic}]
D, [2016-10-11 06:26:31 #11395] [canary_update(cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45))] DEBUG -- DirectorJobRunner: networks_changed? desired reservations: [{type=static, ip=10.9.1.191, network=cell2, instance=cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45)}]
D, [2016-10-11 06:26:31 #11395] [canary_update(cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45))] DEBUG -- DirectorJobRunner: Networks have changed. Recreating VM
D, [2016-10-11 06:26:31 #11395] [canary_update(cell_z2/0 (8493a031-31c8-4783-b743-129f78584e45))] DEBUG -- DirectorJobRunner: Failed to update in place. Recreating VM
```

**Comment by voelzmo** [comment]
seems like you renamed the network and made it a static one instead of a dynamic? If you didn't change that in the manifest, I'm wondering what happened inside the Director here...

**Comment by drnic** [comment]
the deployment was sharing an AWS subnet across multiple bosh networks; and there were overlaps of available dynamic ranges between the BOSH networks. Perhaps the issue occurs because of this?

**Comment by cppforlife** [comment]
check out 'bosh events'. it shows why instance is being updated in the context column. 'bosh events --instance blah/blah' will show you only for that instance.

http://bosh.io/docs/events.html

**Comment by drnic** [comment]
@cppforlife awesome; thanks didn't know about that

**Comment by drnic** [comment]
LOL, I need a wider laptop screen:

![](https://cl.ly/3l3G0Z0v0m2q/download/Image%202016-10-12%20at%2010.20.46%20AM.png)
