### ISSUE TITLE
bosh deploy output should reference instance group instead of job

### ISSUE THREAD

**Issue by dreeve** [cloudfoundry/bosh#1475]
BOSH now treats jobs as instance_groups, but the deploy output still references them as jobs

```
Started updating job web > web/0 (d632b49f-1bd7-4cc9-a807-750bc90d7fd1) (canary)
  Started updating job db > db/1 (02a75713-3aa9-4306-976e-aad8b2aac4ba) (canary)
  Started updating job worker
```

it should call them `instance_group`  instead of job.

/cc @tushar-dadlani

**Comment by cppforlife** [comment]
To confirm you are saying it should be "Started updating instance group web"?

**Comment by tushar-dadlani** [comment]
Yes. Sorry for the confusion.

**Comment by dpb587-pivotal** [comment]
Closing - changed via f6ab97d7953b11d019c5c9a9fcf6ab6598ce737a and available in [v258+](https://github.com/cloudfoundry/bosh/releases/tag/v258).
