### ISSUE TITLE
Add blobstore location and backend to 'bosh status' output

### ISSUE THREAD

**Issue by kitsirota** [cloudfoundry/bosh#1481]
Currently there is no way to tell (from a jumpbox) what a bosh director is configured to use for a blobstore without SSHing into the director and inspecting the settings.json configs.

Currently only the compilation cache configs are listed.  For example, our bosh status outputs like something like this:

Director
  Name       som-staging-bosh
  URL          https://<director-ip>:25555
  Version    00000000
  User         ***
  UUID       c0f1b55c-90a7-4507-bc39-73476e21d7b0
  CPI        vsphere_cpi
  dns        disabled
  compiled_package_cache enabled (provider: s3cli)
  snapshots  enabled

It would be great to add a some rows similar to compiled_package_cache output
Something like this:
blobstore provider: s3cli
blobstore location: <bucket-name> or path to local blobstore

**Comment by dpb587-pivotal** [comment]
Generally I don't think users should be caring about where director is storing off blobs, so it does seem like more debugging information where SSH'ing or reviewing the manifest are acceptable. The other fields are describing functionality, and this seems more like configuration. Can you describe a bit more about why adding it would be helpful?

**Comment by kitsirota** [comment]
This was particularly painful when we were transitioning all of our directors from a local blobstore to an S3-backed one.  There is no clear migration path for blobstores, we ran into a few cases where a director had been migrated but the deployments still had out of date bosh agent settings which pointed to the director for the blobstore.  Thinking back on this, listing the blobstore provider on the director wouldnt actually address the issue of outdated bosh agent configs on cells.
