### ISSUE TITLE
BOSH retains VM state after stopping an errand

### ISSUE THREAD

**Issue by freynca** [cloudfoundry/bosh#1484]
BOSH 1.3262.15.0

To reproduce:
- set up a deployment with an errand
- launch the errand with keep-alive and wait for it to complete: `bosh run errand <errand-name> --keep-alive`
- stop the errand job: `bosh stop <errand-name> <index> --hard --force`
- observe that neither `bosh vms` not `bosh instances` list the deleted VM
- once the VM is removed, attempt to re-run the errand, as before

Observe the director respond with an error: `Failed: <errand-name>/<index> (<guid>) doesn't reference a VM`

Inspecting the director's database, the `instances`, `ip_addresses`, `rendered_template_archives`, and `instance_templates` tables contain records for the removed instance.

**Comment by dpb587-pivotal** [comment]
@tushar-dadlani was running into this yesterday as well.

**Comment by tushar-dadlani** [comment]
We managed to recover from this by commenting the errand job, running `bosh deploy` and then uncommenting the errand job and then `bosh deploy`

**Comment by geofffranks** [comment]
+1 ran into this today, it's still a problem.

**Comment by geofffranks** [comment]
Tried using the `delete-vm` command from the bosh2 cli, and that did not fail, but it also did not help my errand to be able to run. Also tried `start` and `unignore` with no luck.

**Comment by giner** [comment]
Same here. How to clean up safely?

**Comment by jfmyers9** [comment]
Validated that this is still an issue. Closing and reopening this story so that gitbot will create a corresponding tracker story.

**Comment by luan** [comment]
The commit above fixes `bosh start` on errand instances. The described issue will still occur unless you `bosh start` your errand. That will be the supported way to get out of this state on the next version of BOSH.

The reason for this is that we found it to be surprising for a user who has `bosh stop --hard` an errand instance to see that same instance run the errand later with `bosh run-errand`. Especially when the errand is located in multiple instances. The behavior when you `bosh stop --hard` is to not re-create that instance on a deploy, so it's natural that we wouldn't do that when `bosh run-errand` either.
