### ISSUE TITLE
BOSH CLI will accept `--version` as a release name 

### ISSUE THREAD

**Issue by RochesterinNYC** [cloudfoundry/bosh#1489]
In our Concourse, one of our jobs runs:
`bosh create release --force --with-tarball --name $ROOTFS_RELEASE --version 212.0.$(date +"%s")`

This was ran with the `$ROOTFS_RELEASE` env var not set and a release called `--version` was created. 

https://buildpacks.ci.cf-app.com/teams/main/pipelines/stacks/jobs/deploy-rootfs-to-stacks/builds/31

```
Generated /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.tgz

Release name: --version
Release version: 0+dev.1
Release manifest: /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.yml
Release tarball (258.4M): /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.tgz
```

BOSH CLI version:

```
bash-4.3# bosh --version
BOSH 1.3262.4.0
```

**Comment by cppforlife** [comment]
@RochesterinNYC I would recommend switching over to `github.com/cloudfoundry/bosh-cli` at this point to avoid this problem. We are unlikely to fix *this existing* behaviour in the Ruby CLI.

**Comment by drnic** [comment]
One option to protect from unset vars is to use:
${ROOTFS:?required}
This will fail if the car is unset or empty.






On Mon, Oct 24, 2016 at 11:42 PM +1000, "James Wen" <notifications@github.com> wrote:












In our Concourse, one of our jobs runs:

bosh create release --force --with-tarball --name $ROOTFS_RELEASE --version 212.0.$(date +"%s")



This was ran with the $ROOTFS_RELEASE env var not set and a release called --version was created. 



https://buildpacks.ci.cf-app.com/teams/main/pipelines/stacks/jobs/deploy-rootfs-to-stacks/builds/31

Generated /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.tgz

Release name: --version
Release version: 0+dev.1
Release manifest: /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.yml
Release tarball (258.4M): /tmp/build/395d4d9d/cflinuxfs2-rootfs-release/dev_releases/--version/--version-0+dev.1.tgz




BOSH CLI version:

bash-4.3# bosh --version
BOSH 1.3262.4.0
