### ISSUE TITLE
unclear output after resolving "Delete disk reference" with detached & destroyed AWS EBS volume

### ISSUE THREAD

**Issue by cjcjameson** [cloudfoundry/bosh#1493]
We had a deployment with a VM that had an attached ephemeral EBS volume in AWS. We wanted to totally destroy the volume & disk and start fresh. We first "force detach"ed the volume through the AWS EBS console GUI, and then followed by deleting the volume (also through the GUI).

Then we ran `bosh cck` to resolve the link references that were now invalid. It correctly noted that the disk was missing, and gave us the option "2. Delete disk reference (DANGEROUS!)". We took that option.

<details>
  <summary>The rest of the cloudcheck output looked like:</summary>

```
  1. Disk `vol-8a77773c' (db/af89e7fb-7777-48a0-8266-8a8f87775723, 50000M) is missing
     Delete disk reference (DANGEROUS!)

Apply resolutions? (type 'yes' to continue): yes
Applying resolutions...

Director task 16349
  Started applying problem resolutions > missing_disk 1: Delete disk reference (DANGEROUS!). Done (00:00:00)

Task 16349 done

Started		2016-10-31 22:10:20 UTC
Finished	2016-10-31 22:10:20 UTC
Duration	00:00:00
Cloudcheck is finished
```

</details>

We then sought to recreate the VM and have bosh bring up an appropriate new volume. It succeeded at this, reporting:

<details>
  <summary>`bosh deploy` command output:</summary>

```
Getting deployment properties from director...

Detecting deployment changes
----------------------------
Please review all changes carefully

Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 16350
  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started creating missing vms > db/0 (af87e3fb-2031-7777-8266-8a8f8ce57723). Done (00:01:37)

  Started updating job db > db/0 (af79e3fb-2031-4770-8266-878f8ce55723) (canary). Done (00:00:38)

Task 16350 done

Started		2016-10-31 22:10:36 UTC
Finished	2016-10-31 22:12:53 UTC
Duration	00:02:17

Deployed 'shared_concourse' to '10.77.7.7'
```

</details>

**Our issue:** These outputs didn't clearly describe when or why the DB vm was recreated -- why did it say "Started creating missing vms" when it was only the attached disk that was missing?

**Comment by cppforlife** [comment]
@cjcjameson are you sure that VM wasnt missing as well? you can check out few things in debug log:

```
bosh task 16350 --debug|grep changes # shows why instance is considered changed
bosh task 16350 --debug|grep create_vm # confirms that vm is created
```

**Comment by cjcjameson** [comment]
I suppose we aren't sure. We didn't do anything to delete the VM, so we assumed it was still there. Thanks for pointing out that method of searching the logs -- that will be helpful in future situations. For this case, we had:

```
$:→ bosh task 16350 --debug | grep changes
Acting as user 'admin' on 'my-bosh'
D, [2016-10-31 22:12:15 #31826] [] DEBUG -- DirectorJobRunner: Need to update instance 'db/0 (af89e3fb-2031-48a0-8266-8a8f8ce55723)', changes: "packages, persistent_disk, configuration, state"
I, [2016-10-31 22:12:15 #31826] [canary_update(db/0 (af89e3fb-2031-48a0-8266-8a8f8ce55723))]  INFO -- DirectorJobRunner: Updating instance db/0 (af89e3fb-2031-48a0-8266-8a8f8ce55723), changes: "packages, persistent_disk, configuration, state"

$:→ bosh task 16350 --debug | grep create_vm
Acting as user 'admin' on 'my-bosh'
D, [2016-10-31 22:10:37 #31826] [create_missing_vm(db/0 (af89e3fb-2031-48a0-8266-8a8f8ce55723)/1)] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"create_vm","arguments":["3011fd28-75fa-40a2-aae7-5bb3f1668a98","ami-1bfe5a7b light",{"availability_zone":"us-west-2b","instance_type":"c4.large","ephemeral_disk":{"size":30000,"type":"gp2"}},{"private":{"ip":"10.32.120.12","netmask":"255.255.255.240","cloud_properties":{"subnet":"subnet-b1f977d5","security_groups":["sg-3d439c5b"]},"default":["dns","gateway"],"dns":["10.32.120.202"],"gateway":"10.32.120.1"}},[],{}],"context":{"director_uuid":"6aaaf9cc-dcd1-4dd3-8890-62cfb3e0b05e"}} with command: /var/vcap/jobs/aws_cpi/bin/cpi
```

If that means that this is a non-issue, feel free to close the issue. Thanks!

**Comment by dpb587-pivotal** [comment]
Closing - ephemeral disk configuration changes cause a VM to be recreated. It seems odd to be attempting to relocate an ephemeral disk - the data on it is intended to be temporary. Feel free to reopen if this is a misunderstanding.

**Comment by cjcjameson** [comment]
Oh, I think it was a persistent disk -- I probably said the wrong thing.
