### ISSUE TITLE
bosh-init doesn't work with stemcell 3306 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1500]
Our OpenStack pipelines are failing with stemcell `3306`. [Here](https://bosh-cpi.ci.cf-app.com/teams/main/pipelines/bosh-openstack-cpi/jobs/bats-centos-manual/builds/1576) is one failing job with `3306`. `bosh-init` fails to open the SSH tunnel in order to make registry available.
This [commit](https://github.com/cloudfoundry/bosh-agent/commit/f846c7f703582a12a1f10f54b4de9aa0ee7d6fe5) changed the order of `boot.settingsService.PublicSSHKeyForUsername` and `boot.settingsService.LoadSettings`. Settings are loaded now before ssh setup. This doesn't work with `bosh-init` because it needs to have the `authorized_keys` available before the registry information is retrieved as described [here](https://github.com/cloudfoundry/bosh-init/blob/master/docs/cli_workflow.md). In `agent` log we see following error:

```
2016-11-09_10:21:38.55729 [settingsService] 2016/11/09 10:21:38 ERROR - Failed loading settings via fetcher: Getting settings from url: Get http://127.0.0.1:6901/instances/vm-6d3e1a6f-dbdb-4c81-baa3-cdc1b8b6ecdb/settings: dial tcp 127.0.0.1:6901: getsockopt: connection refused
```

`127.0.0.1:6901` is not available as `bosh-init` could not open the reverse tunnel.

Also booting a VM with this BOSH stemcell directly via Horizon works but after that you can't login with the configured SSH key. There is of course a different reason why the `loadSettings` call fails, but it's the reason why the ssh key never gets placed into authorized_keys.

**Comment by cppforlife** [comment]
we ll take a look at it today. thanks.

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/134017149

**Comment by cppforlife** [comment]
Resolved in 3308.
