### ISSUE TITLE
Make AWS stemcells use gp2 volume type

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1508]
Hi,

it looks like all the stemcells for AWS currently use 'standard' EBS volume type. This is an older volume type based on spinning disks. AWS recommends all new EBS volumes default to gp2 type, which is SSD based and can burst to 3000 I/O regardless of the volume size. It is made for making instance boots faster (the volumes receive initial I/O boost specifically for making boots faster). Switching stemcells to this (currently default) gp2 volume type would make deploying VMs faster, as they would boot faster due to improved root disk performance. On large deployment, this can save considerable amounts of time...

**Comment by cppforlife** [comment]
@mtekel sounds good. story: https://www.pivotaltracker.com/story/show/134188243

**Comment by cppforlife** [comment]
@mtekel Done: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/releases/tag/v61

**Comment by mtekel** [comment]
I confirm this works. Thanks!
