### ISSUE TITLE
[question/QOL improvement] bosh target set to 'xxx'

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/bosh#1509]
```
 2016-11-12 15:26:56 ☆  |2.3.0| DEN_Recently_Imaged in ~
○ → bosh target openstack
Target set to 'my-bosh'
```

Why would it not say `Target set to 'openstack'`? This is quite against what my user expectation is.

edit: I believe it's using `jobs[0].properties.director.name` (`name: my-bosh`), so I'm sure it's no bug. Maybe another alternative could be:

`Target set to 'openstack' whose director name is 'my-bosh'`, or perhaps some less verbose form of that.

**Comment by cppforlife** [comment]
new cli (https://github.com/cloudfoundry/bosh-cli) fixes this inconsistency matching your expectation.

**Comment by jadekler** [comment]
Thanks @cppforlife
