### ISSUE TITLE
bosh deployment don't really restart all monit jobs

### ISSUE THREAD

**Issue by goupeng212** [cloudfoundry/bosh#1510]
We have one bosh deployment which deploying more than 20 monit jobs into one VM.
When we dong bosh deployment, we found part of jobs not really restart
Here is the monit.log:
[monit.log.log.txt](https://github.com/cloudfoundry/bosh/files/588918/monit.log.log.txt)
You can find the jobs from line 69 - line 113, the jobs not really stopped succesfully. The old process still running. However, the jobs from line 115-131, the jobs did the really restart.

**Comment by cppforlife** [comment]
@goupeng212 sounds like stop script for that job is not killing old process hard enough.

**Comment by goupeng212** [comment]
I don't think so.
From the log shown, the job stopped succesfullly will have one entry which seems call the control file correctly. But the failed to stop jobs don't have such log entry. 
**JOB_NAME stop: /var/vcap/jobs/unbound/bin/unbound_ctl**

And we found such problem on many envs ( we are using the bosh to deploy the same jobs on many different envs). The jobs failed to stop happened randomly, although the different env are using the same deployment codes.  For example , the job failed to stop are job 1,2,3 on env1. But the failed on env2 are job 4,5,6

**Comment by cppforlife** [comment]
@goupeng212 we'll dig in further.

**Comment by tylerschultz** [comment]
Hi @goupeng212, would you please tell us the director version and stemcell version that you were using when you saw this problem?

**Comment by cppforlife** [comment]
@goupeng212 bump. can you provide director and stemcell versions.

**Comment by goupeng212** [comment]
Director version:  Version    1.3153.0 (00000000)
Stemcell version : 3169.1

**Comment by dpb587-pivotal** [comment]
@goupeng212, are you still experiencing this on recent director/stemcells?
