### ISSUE TITLE
Feature request: Add support to add additional tags to datadog integration

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh#1512]
It would be great be able to add additional tags to the metrics sent to datadog.

This can be done by adding an additional property `datadog.extra_tags` which would receive a hash of `tagname => value`.

**Comment by cppforlife** [comment]
@keymon agreen. i wonder if we should add generic extra tags and apply them to as many places as possible.

**Comment by dpb587-pivotal** [comment]
Should plugins be inheriting the tags configured by deployments+runtime-config?

**Comment by mfine30** [comment]
Hey @keymon is this still of interest to you? If so, are you interested in chatting about submitting a PR for it?

**Comment by keymon** [comment]
Yes, it shall be interesting. I IIRC we ended workingaround this by using other tags like the deployment name and write some more complex monitors queries. 

In order to do a PR, I will have a look to it and come back to you.
