### ISSUE TITLE
Failed cck'ing unresponsive VM: private method 'select' called for #<String:...>

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1516]
On a fairly standard concourse deployment (without config server, without interpolation, without explicit linking), cck recreating a manually terminated VM failed. From the `--debug`...

Error Message...

    Error resolving problem 'id': private method `select' called for #<String:0x0055e77c7367e8>

Backtrace (in `/var/vcap/packages/director/gem_home/ruby/2.3.0/gems`)...

    bosh-director-260.0.0/lib/bosh/director/deployment_plan/instance_spec.rb:131:in `block in spec'
    bosh-director-260.0.0/lib/bosh/director/deployment_plan/instance_spec.rb:129:in `each'
    bosh-director-260.0.0/lib/bosh/director/deployment_plan/instance_spec.rb:129:in `spec'
    bosh-director-260.0.0/lib/bosh/director/deployment_plan/instance_spec.rb:56:in `as_template_spec'
    bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:118:in `apply_initial_vm_state'
    bosh-director-260.0.0/lib/bosh/director/vm_creator.rb:90:in `create_for_instance_plan'
    bosh-director-260.0.0/lib/bosh/director/cloudcheck_helper.rb:70:in `recreate_vm'
    bosh-director-260.0.0/lib/bosh/director/problem_handlers/unresponsive_agent.rb:47:in `block (2 levels) in <class:UnresponsiveAgent>'
    bosh-director-260.0.0/lib/bosh/director/problem_handlers/base.rb:83:in `instance_eval'
    bosh-director-260.0.0/lib/bosh/director/problem_handlers/base.rb:83:in `apply_resolution'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:65:in `block in apply_resolution'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:24:in `block in track_and_log'
    bosh-director-260.0.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:22:in `track_and_log'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:64:in `apply_resolution'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:43:in `block in apply_resolutions'
    sequel-4.32.0/lib/sequel/dataset/actions.rb:139:in `block in each'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:669:in `block (2 levels) in fetch_rows'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:861:in `block in yield_hash_rows'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:855:in `times'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:855:in `yield_hash_rows'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:669:in `block in fetch_rows'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:175:in `execute'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
    sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
    sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
    sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `execute'
    sequel-4.32.0/lib/sequel/dataset/actions.rb:952:in `execute'
    sequel-4.32.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
    sequel-4.32.0/lib/sequel/dataset/actions.rb:139:in `each'
    bosh-director-260.0.0/lib/bosh/director/problem_resolver.rb:34:in `apply_resolutions'
    bosh-director-260.0.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:38:in `block in perform'
    bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
    bosh-director-260.0.0/lib/bosh/director/lock.rb:53:in `lock'
    bosh-director-260.0.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
    bosh-director-260.0.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:37:in `perform'
    bosh-director-260.0.0/lib/bosh/director/job_runner.rb:106:in `perform_job'
    bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `block in run'
    bosh_common-260.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
    bosh-director-260.0.0/lib/bosh/director/job_runner.rb:32:in `run'
    bosh-director-260.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
    bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
    bosh-director-260.0.0/lib/bosh/director/jobs/db_job.rb:80:in `block (3 levels) in run'
    eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
    logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

Environment...

    $ bosh deployment | cat
    concourse        garden-runc/1.0.1        bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3263.8        latest
                     concourse/2.4.0
    $ bosh env | grep Version
    Version         260.0.0 (00000000)

Attempted...

    $ bosh cck
    11  unresponsive_agent  VM for 'concourse/uuid (0)' with cloud ID 'cid' is not responding.
    4. Recreate VM and wait for processes to start

**Comment by dpb587** [comment]
Reran and added...

   puts "====>#{interpolated_values.inspect}<===="

Results in...

    ====>"#<struct Bosh::Director::DeploymentPlan::LinkInfo deployment_name=\"concourse\", spec={\"networks\"=>[\"private\"], \"properties\"=>{\"bind_port\"=>5432, \"databases\"=>[{\"name\"=>\"concourse\", \"role\"=>\"{{snip}}\", \"password\"=>\"{{snip}}\"}]}, \"instances\"=>[{\"name\"=>\"concourse\", \"index\"=>0, \"bootstrap\"=>true, \"id\"=>\"8a344708-3e77-413f-8ea4-5ed99e2ecbc3\", \"az\"=>\"b\", \"address\"=>\"{{snip}}\"}]}>"<====

Which looks almost normal except for the maybe the fact that it's quoted.

**Comment by dpb587** [comment]
Slightly different error than, but same incorrect, serialized `LinkInfo` spec in the database as, https://www.pivotaltracker.com/story/show/133642697.

    # puts JSON.parse(Bosh::Director::Models::Instance.find(:job => "concourse").spec_json)
    {
      "deployment": "concourse",
      "job": {
        "name": "concourse",
        ...
      "links": {
        "db": "#<struct Bosh::Director::DeploymentPlan::LinkInfo deployment_name=\"concourse\", spec={\"networks\"=>[\"private\"], \"properties\"=>{\"bind_port\"=>5432, \"databases\"=>[{\"name\"=>\"concourse\", \"role\"=>\"XXXXXXXX\", \"password\"=>\"XXXXXXXX\"}]}, \"instances\"=>[{\"name\"=>\"concourse\", \"index\"=>0, \"bootstrap\"=>true, \"id\"=>\"8a344708-3e77-413f-8ea4-5ed99e2ecbc3\", \"az\"=>\"b\", \"address\"=>\"192.0.2.1\"}]}>",
        "tsa": "#<struct Bosh::Director::DeploymentPlan::LinkInfo deployment_name=\"concourse\", spec={\"networks\"=>[\"private\"], \"properties\"=>{\"bind_port\"=>2222, \"host_public_key\"=>\"\"}, \"instances\"=>[{\"name\"=>\"concourse\", \"index\"=>0, \"bootstrap\"=>true, \"id\"=>\"8a344708-3e77-413f-8ea4-5ed99e2ecbc3\", \"az\"=>\"b\", \"address\"=>\"192.0.2.1\"}]}>",
        "baggageclaim": "#<struct Bosh::Director::DeploymentPlan::LinkInfo deployment_name=\"concourse\", spec={\"networks\"=>[\"private\"], \"properties\"=>{\"bind_port\"=>\"7788\"}, \"instances\"=>[{\"name\"=>\"concourse\", \"index\"=>0, \"bootstrap\"=>true, \"id\"=>\"8a344708-3e77-413f-8ea4-5ed99e2ecbc3\", \"az\"=>\"b\", \"address\"=>\"192.0.2.1\"}]}>",
        "atc": "#<struct Bosh::Director::DeploymentPlan::LinkInfo deployment_name=\"concourse\", spec={\"networks\"=>[\"private\"], \"properties\"=>{\"bind_port\"=>8080, \"tls_bind_port\"=>4443}, \"instances\"=>[{\"name\"=>\"concourse\", \"index\"=>0, \"bootstrap\"=>true, \"id\"=>\"8a344708-3e77-413f-8ea4-5ed99e2ecbc3\", \"az\"=>\"b\", \"address\"=>\"192.0.2.1\"}]}>"
      },
      ...
    }

Data in the database was still corrupted even after it was upgraded to v260.

Manually running `bosh recreate` was successful and corrected the bad spec in the database.

**Comment by tylerschultz** [comment]
Maybe we should add a migration?

**Comment by dpb587-pivotal** [comment]
Not sure how widespread the issue was/is, nor how practical it would be to try and write a migration for deserializing an `.inspect`'d object.

@cppforlife, prioritize a story for that if it's important.
