### ISSUE TITLE
Feature request: `bosh locks` shows the id of the task holding the lock.

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry/bosh#1526]
It would be great to be able to see which task is holding the lock, especially when different teams is sharing the same bosh director running different errands/deployments at the same time.

**Comment by cppforlife** [comment]
@Kaixiang yeah that's would be great!

**Comment by dpb587-pivotal** [comment]
Related story [#146034015](https://www.pivotaltracker.com/story/show/146034015) / PR #1702

**Comment by dpb587-pivotal** [comment]
Related functionality has been merged and will be in the next director release.

**Comment by Kaixiang** [comment]
awesome! Thanks!
