### ISSUE TITLE
how to migrate deployments with persistent disks from single to multiple zones

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/bosh#1527]
We're trying to move bosh deployments with persistent disks from a single-zone setup (i.e. 3 instances in z0) to a multi-zone setup (i.e. 3 instances stretched over z1-z3).

Since persistent disks are zone-local (and thus can't be moved to other zones), we understand that the BOSH director does not touch existing instances with persistent disks.

Our instances with persistent disks run cluster software (i.e. Redis HA) which ensure by themselves that every instance has all the data. So in order to move the deployment from one zone to another, we don't need the persistent disk's content, but we only need **at least one instance** running. 

To achieve this, we tried the following scenarios:
Initial state: 3 instances w/ one persistent disk deployed & running in z0

- a.) Update instance groups' `azs:` from `[z0]`to `[z0, z1, z2]` and redeploy (in the hope that BOSH balances the instances to the new zones). Then remove z0 and add z3. This does not work since BOSH does not touch the instances in z0 because they have persistent disks. Makes sense.
- b.) Update instance groups' `azs:` from `[z0]`to `[z0, z1, z2, z3]`, increase instance count to 6 and redeploy. BOSH creates new instances in the new zones. Then, reduce instance count to 3. **We expect that BOSH now keeps 1 instance per zone. Instead, it only keeps the 3 instances in z0 and removes the instances in the other zones.**

Is b.) expected behaviour or a bug?

I created an additional spec that illustrates this (it's failing at the moment): https://github.com/MatthiasWinzeler/bosh/commit/d1b795178f3b686343bb44aeb3eb578573527f8d

I guess we can work around this by not only reducing instance count to 3, but also remove z0 altogether. Then BOSH removes the instances in z0.

Is there maybe another way to move the instances without disruption? We'd like to migrate without having to increase the instance count to 6.

**Comment by cppforlife** [comment]
Desired behavior that you describe makes sense. We'll look into this and thanks for the test to demonstrate it. This might be the case of just us doing slightly different "rebalancing" (not balancing) for persistent disks where we just remove machines with higher indices.

**Comment by cppforlife** [comment]
@tylerschultz what do you think?

**Comment by tylerschultz** [comment]
Ya, this all makes sense. I think the current balancing behavior is wrong too (scenario b). 

Thanks for writing the test, that is super helpful.

I don't think there is a way to move the instances without going through these incantations. Bosh does not move the instances, favoring the prevention of data loss.

**Comment by cppforlife** [comment]
@MatthiasWinzeler depending how your deployed software behaves you could shrink to 1 and then scale up to 3 again and that should place them into new azs.

**Comment by Lafunamor** [comment]
since @MatthiasWinzeler is on vacation I'll answer here.
When shrinking down to one instance and increasing back up to 3 instances BOSH will behave as expected.
Nevertheless (as you mentioned) this is depending on the deployed software and not always possible.

**Comment by mfine30** [comment]
Hey @Lafunamor @MatthiasWinzeler is balancing across AZs in this case this still an issue for you? Is this something you'd be interested in chatting about submitting a PR?

**Comment by MatthiasWinzeler** [comment]
@mfine30 this is not longer an issue for us, since we were able to migrate it by scaling down/up before. Feel free to close it if it's ok for you.
