### ISSUE TITLE
Deployments with dynamic network fail unless `director.local_dns.enabled` is `true`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1528]
After upgrading my BOSH Director to v260, my Concourse deployment started failing on the next redeploy. The relevant error from the failing Concourse job was `dial tcp: lookup f90b8b87-da14-4f2b-aa6c-8b70eea63f61.concourse.public-concourse.conco
urse.bosh on 169.254.169.254:53: no such host`. Because my deployment used a `dynamic` network, BOSH decided to return a DNS record when one of the Concourse templates asked for `spec.address`. This is unexpected as I had not opted in to the new `local_dns` feature and these DNS records are all invalid. I would have expected the old `spec.address` behavior to be preserved if `local_dns` was not enabled, or an error message that prevented me from deploying with a dynamic network unless `local_dns` was enabled.

**Comment by cppforlife** [comment]
we are not yet ready to enable local_dns by default; however, i also do not want us to use IPs for links on dynamic networks since that's getting us farther from where we want to end up.

**Comment by voelzmo** [comment]
@cppforlife still, that's a breaking change – I don't think you should just do it like that.

**Comment by cppforlife** [comment]
this was always links behaviour for dynamic networks.

**Comment by voelzmo** [comment]
Then I maybe misunderstood @ljfranklin's statement. Lyle, did this work before?

**Comment by ljfranklin** [comment]
> this was always links behaviour for dynamic networks.

Maybe I jumped the gun a bit on the title. More specifically, I have Concourse deployed to a single VM so a bunch of jobs are all co-located. I used a dynamic network to deploy this VM as I didn't require any fixed internal IPs. Prior to the latest BOSH director release (v260), the Concourse templates were able to resolve `spec.address` correctly, e.g. [here](https://github.com/concourse/concourse/blob/acce26581502145b714e399b34a5bcbfc151d76b/jobs/groundcrew/templates/beacon_ctl.erb#L16). I'm not sure if `spec.address` was returning `localhost` or similar before, but the Concourse deployment was definitely working. Maybe this issue only affects single VM deployments that use links and dynamic networks?

**Comment by cppforlife** [comment]
@ljfranklin im pretty sure we werent using dynamic networks.

**Comment by ljfranklin** [comment]
@cppforlife this was for my personal Concourse deployment.

**Comment by sykesm** [comment]
I'm having the same issue with bosh and dynamic networks.  In my case, I'm using dynamic networks but bosh *knows* the IP addresses associated with the jobs and I *do not* have BOSH DNS enabled.  In a situation like this, I don't understand why links would generate DNS names instead of using the IP. Without BOSH DNS, there's little hope of resolving the addresses out of band - even if it is _possible_.

To me, this is behavior that should be configurable at the director level. There should be a small bit of configuration that says to prefer IP addresses (when known) to DNS names - even when using a dynamic network.

**Comment by sykesm** [comment]
I'll also add that the user experience here is pretty awful. In the case of concourse, the my deployment was successful but ATC never started because the link to the postgres pointed to a black hole.

/cc @vito

**Comment by frodenas** [comment]
I was also bitten by this, and the [documentation](http://bosh.io/docs/links.html#templates) is not clear:

```
Available instance object methods:
* address [String, non-empty]: IPv4, IPv6 or DNS record
```

**Comment by jfmyers9** [comment]
Hi all,

Seeing as bosh-dns is post v1, this seems like less of an issue. We don't have plans to fix the underlying behavior because of this.

We're going to close this issue, but please feel free to reopen if you have any other concerns.

Best,

@jfmyers9 && @belinda-liu, CF BOSH
