### ISSUE TITLE
Supply `required` attribute in spec file

### ISSUE THREAD

**Issue by fhanik** [cloudfoundry/bosh#1532]
Right now, to validate if properties have to be supplied, one has to deploy the release, and the release has to run the ERB templates and throw an error.

It would be nice if the spec had a `required:` just like it has `example:` and `default:`

**Comment by cppforlife** [comment]
@fhanik we've thought about adding this before, however, there are interesting cases that don't make this entirely consistent -- specifying some properties makes additional properties required. any thoughts on that?

**Comment by liuweichu** [comment]
IMO, BOSH should provide a way that user can get rendered templates without actually deploying.

Rendering and deploying should be decoupled so that release developers/BOSH admins can get a much faster feedback. (actually I don't know why BOSH haven't provided this yet)

**Comment by cppforlife** [comment]
there is a --dry-run flag on deploy. i dont remember if its only available in the new cli though.

**Comment by liuweichu** [comment]
Didn't find `--dry-run` on `BOSH 1.3262.24.0`. Maybe I should switch to new client.

By the way, I'm sure `--dry-run` can help users to find their templating errors. Does it also provide the rendered results to user? I think that should be very useful.

**Comment by mfine30** [comment]
Closing in favor of #1686 if you have other concerns/comments to add, please do so there.
