### ISSUE TITLE
Allow the 'spec' file to be 'spec.yml'

### ISSUE THREAD

**Issue by stickfigure** [cloudfoundry/bosh#1545]
It would be nice if IDEs just did the right thing out of the box. 

This could be backwards-compatible so either form works.

**Comment by cppforlife** [comment]
@dpb587-pivotal what do you think?

**Comment by cppforlife** [comment]
could be a cli level translation to avoid changes to internal format

**Comment by dpb587-pivotal** [comment]
I've gotten used to it; but I do think it would make for a better UX, so I think it's a good idea.

CLI translation is a good idea. Assuming we won't be going to a world where director supports only `spec.yml`.
