### ISSUE TITLE
When monit fails to return good status on one instance, it causes "bosh vms" to fail

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/bosh#1549]
We are running running bosh cli version 1.3262.24.0 bosh v257.1 with a cf v245 deployment.
We've noticed occasionally when running "bosh vms DEPLOYMENT" that if monit on one instance fails to return status, we will get this error in the cli:
Error 450001: Action Failed get_state: Getting processes status: Getting service status: Unmarshalling Monit status: read tcp 127.0.0.1:43670->127.0.0.1:2822: read: connection reset by peer

We see a similar error about "unmarshaling monit" in the director logs.

In this case it appears that sometimes hm9000_analyzer is passing a status back to monit which monit can't handle. Monit returns "status failed" which seems to not be handled well  by the director.

**Comment by pusherofbrooms** [comment]
https://github.com/cloudfoundry/hm9000/issues/23 is the related hm9000 bug

**Comment by pusherofbrooms** [comment]
The error in monit on the hm9000 instance is:
[UTC Dec 20 15:37:12] error    : monit: cannot read status from the monit daemon
and 
[UTC Dec 20 15:38:14] error    : monit: error receiving data -- Connection reset by peer

I seem to be mistaken about director logs. I'm struggling to find the monit errors returned to the director though I'm certain I saw them at some point.

**Comment by poblin-orange** [comment]
Hitting the same issue no one of our deployment (logsearch).
bosh 261.4 stemcell 3421.4
This blocks bosh deploy.
```
Deploying
---------

Director task 609483
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Failed: Action Failed get_state: Getting processes status: Getting service status: Unmarshalling Monit status: read tcp 127.0.0.1:44350->127.0.0.1:2822: read: connection reset by peer (00:00:03)

Error 450001: Action Failed get_state: Getting processes status: Getting service status: Unmarshalling Monit status: read tcp 127.0.0.1:44350->127.0.0.1:2822: read: connection reset by peer

Task 609483 error

For a more detailed error report, run: bosh task 609483 --debug
command 'bosh -n --color -t https://192.168.116.158:25555 -d /tmp/bosh_manifest20170714-7-1goekym deploy' failed!
```

This might be related to highload on target deployments vms. Is there a configurable setting (timeout) or workaround to force a correct deploy ?

**Comment by mfine30** [comment]
This error happens when the VM is under very high load. The recommended solution would be to scale to a larger VM if you're consistently seeing this issue. Unfortunately, there isn't much we can do besides cleaning up the error message which is pretty low on our priority list right now.
