### ISSUE TITLE
New gem release (1.33 series)?

### ISSUE THREAD

**Issue by crunchyjohn** [cloudfoundry/bosh#1550]
Hello,  
  
My apologies if this is the wrong place to ask, but I couldn't figure out where else to enquire.  Feel free to point me in the right direction.  

There was a bugfix that went into the 1.33 line awhile back (September, actually) that we'd like to take advantage of.  Unfortunately, all I see on the rubygems page for bosh is the 1.32 for now:  
https://rubygems.org/gems/bosh-release/versions/

I'm assuming the 1.33 line is planned for a rubygem release sometime in the future?  We can build the gem locally with the fix, but I was curious if it's worth waiting on an official release.

Thank you for your time.
  -John

**Comment by tjvman** [comment]
What was the bugfix?

**Comment by crunchyjohn** [comment]
Hello @tjvman  
  
The fix that we need was this one:  
https://github.com/cloudfoundry/bosh/pull/1421  
  
The issue as stated in the PR says that it impacts Concourse builds, but today we found out it also impacts our jenkins builds (i.e. we have a jenkins node that SSH's into a PCF machine, and in doing so, we get that error).  This may seem trivial, but it's annoying enough that we had to build our own bosh_cli gem with the updated progressbar version to proceed.  We're unblocked at the moment with this specially built version of the gem, but if it were possible, it would be a useful fix to make sure that CI tools don't give a "negative argument" error and fail to finish.

For reference, a more detailed explanation of the error and its resolution can be seen here:  https://www.pivotaltracker.com/n/projects/1158420/stories/128710767
The conclusion is the same-- that the progressbar dependency version is too old and had an important fix that allows for CI tools to work properly without error.  
  
We would really like to see if we could get the updated progressbar gem dependency in an official way besides doing our own source builds of the project.  I'm not sure if this is possible.

**Comment by tjvman** [comment]
@crunchyjohn It looks like https://github.com/cloudfoundry/bosh/pull/1383 is related to what you're describing. As was stated there, the ruby CLI has been frozen and we do not intend to update it or publish a new gem. 

I would recommend switching over to the new Go CLI beta if that seems preferable to maintaining a custom version of the Ruby CLI.
- [Linux binary](https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.139-linux-amd64)
- [Darwin binary](https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.139-darwin-amd64).
It doesn't have the problem with progressbar, and it will be the supported CLI going forward. 

If you encounter the same issue (or any others) after making the switch, please feel free to open an issue in the [GoCLI repo](https://github.com/cloudfoundry/bosh-cli).
