### ISSUE TITLE
Confusing error message when config server cannot talk to director

### ISSUE THREAD

**Issue by drich10** [cloudfoundry/bosh#1552]
Ran into this issue earlier when we typo'd a variable in our manifest, which unintentionally triggered the communication attempt between the config server and the director. 

Error message:
```
...
Task 1161
19:45:33 | Preparing deployment: Preparing deployment (00:00:00)

19:45:33 | Error: Unable to render instance groups for deployment. Errors are:
   - Failed to obtain valid token from UAA: #<CF::UAA::SSLException: Invalid SSL Cert for https://director.host.name:8443/oauth/token. Use '--skip-ssl-validation' to continue with an insecure target>

Started  Tue Jan  3 19:45:30 UTC 2017
Finished Tue Jan  3 19:45:33 UTC 2017
Duration 00:00:03

Task 1161 error

Updating deployment:
  Expected task '1161' to succeed but was state is 'error'

Exit code 1
```

It would be helpful if the error message had given information about:
1) What component was communicating with the director.
1) Template/property that was being rendered at the time of the error.

- Derek & @wendorf

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/136994491

**Comment by dpb587-pivotal** [comment]
This was fixed in [v261](https://github.com/cloudfoundry/bosh/releases/tag/v261).
