### ISSUE TITLE
hi,using bosh api

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/bosh#1553]
i use java request bosh api,but i donw not know how to auth,  i request info, response auth way is uaa,an give me a address ,example https://11.11.11.11:8443,  i donw not how to request or how to use cert request for java, can you tell me? thanks

**Comment by cppforlife** [comment]
please see uaa docs for how to use its api: https://github.com/cloudfoundry/uaa#co-ordinates. you should be able to use standard oauth client with uaa to get a token. once you have a token it's standard oauth token usage (authorization header, token refreshing on 401s, etc.).

you can also refer to provided director client library (golang; includes mini-uaa client) in the bosh cli v2: https://github.com/cloudfoundry/bosh-cli#client-library.

ill augment http://bosh.io/docs/director-api-v1.html with above information.

**Comment by geekyzk** [comment]
sorry,i did not time to see these days, you have to use example for java?
