### ISSUE TITLE
uaa Authentication

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/bosh#1555]
I am sorry,in deployment manifest,i config uaa authentication,and config a uaa url https://192.168.12.11,
and config cert ,but i try use uaa api to authentication,example  https://192.168.12.11:8443/oauth/token,but it do not,  i use java httpclient to connect, i use same code to authentication cloudfoundry uaa is success,but bosh failure, can you tell me how to use java to authentication ,or use cert to connect.
thanks

**Comment by cppforlife** [comment]
@geekyzk please open issue regarding uaa on https://github.com/cloudfoundry/uaa.

**Comment by allomov** [comment]
hey @geekyzk.

I created a sample project with UAA token retrieval in java. You might find it useful to check it out: https://github.com/allomov/bosh-uaa-client-test

**Comment by geekyzk** [comment]
thanks,i try 






On 01/12/2017 02:16， Alexander Lomov<notifications@github.com>wrote：

hey @geekyzk.

I created a sample project with UAA token retrieval in java. You might find it useful to check it out: https://github.com/allomov/bosh-uaa-client-test

**Comment by geekyzk** [comment]
@allomov thinks, it is successful
