### ISSUE TITLE
[Feature request] bosh deploy --recreate --resume

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry/bosh#1556]
We are trying to work through a large --recreate deploy in BOSH, and it's very painful to see it fail due to some transient error on AWS, and have to restart the whole thing again.

It would be nice if BOSH could resume a previous task under some circumstances, if it failed for some reason like timeouts and other transient failures. This would prevent us from spending hours recreating VMs that had already been recreated in the previous run.

**Comment by cppforlife** [comment]
@Kaixiang bosh doesnt recreate recreated VMs, so something must be going on wrong with the env. can take a look.

**Comment by cppforlife** [comment]
Talked in person. Consider using `ignore instance` command. Will wait for your usage feedback.
