### ISSUE TITLE
Allow users to configure value for VM timeout when deploying

### ISSUE THREAD

**Issue by landesherr** [cloudfoundry/bosh#1557]
There is a hard-coded value of 600 seconds that bosh will wait when trying to spin up a VM. It happens reasonably often that a VM simply takes more time than this to come up, so it would be nice to configure this value to prevent large deployments from stopping halfway through due to a timeout.

It appears that the hard-coded 600s value is in [agent_client.rb](https://github.com/cloudfoundry/bosh/blob/c6c419f9eff844c35c8c7307e977427f05a23a51/src/bosh-director/lib/bosh/director/agent_client.rb#L194)

**Comment by cppforlife** [comment]
@landesherr we've yet to find an iaas that takes >10 mins. which iaas are you using?

**Comment by cppforlife** [comment]
Talked in person. Waiting for stats on failure rate on AWS from this env. This is most likely related to booting problems observed at a fairly low rate. Potentially will add retry logic around `create_vm`.
