### ISSUE TITLE
Bosh deploy Timed out pinging to

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry/bosh#1558]
Hi @ all,

I'm facing a problem to deploying CF240.  Bosh starts the deployment. Accepts the manifest and start to create the compilation VM in OpenStack (Liberty). But, then it is running in a timeout.

> RSA 1024 bit CA certificates are loaded due to old openssl compatibility
> Acting as user 'admin' on 'director-de-cloudlab'
> 
> Director task 219
> Error 10000: Task 219 not found
> ubuntu@cf-launcher:~/cf-openstack-validator$ bosh task 129
> RSA 1024 bit CA certificates are loaded due to old openssl compatibility
> Acting as user 'admin' on 'director-de-cloudlab'
> 
> Director task 129
>   Started preparing deployment > Preparing deployment. Done (00:00:01)
> 
>   Started preparing package compilation > Finding packages to compile. Done (00:00:01)
> 
>   Started compiling packages
>   Started compiling packages > windows_app_lifecycle/f0d1a97facb664da270ec290e135c9644bca17a8
>   Started compiling packages > docker/00a534d3a876a90b1c9654b25ce572c102092efc
>   Started compiling packages > cflinuxfs2/cb6c32d89521f5b3193c4dd72f42c06dd1bb8a46
>   Started compiling packages > tar/cfd0d2ff9e0773446e403cef583e0f01cd61f592
>   Started compiling packages > busybox/1593c41beb57c12d7f2b82dff61b47d4d119913d. Failed: Timed out pinging to e1553100-4dcd-406b-b581-7de656071ccf after 600 seconds (00:12:32)
>    Failed compiling packages > tar/cfd0d2ff9e0773446e403cef583e0f01cd61f592: Timed out pinging to f6ae4698-767b-4b73-8a85-399967a59793 after 600 seconds (00:12:32)
>    Failed compiling packages > cflinuxfs2/cb6c32d89521f5b3193c4dd72f42c06dd1bb8a46: Timed out pinging to c593831d-1610-4106-9307-fd7b2fcd5251 after 600 seconds (00:12:35)
>    Failed compiling packages > docker/00a534d3a876a90b1c9654b25ce572c102092efc: Timed out pinging to 82b19e71-cd5a-4f18-8473-7d9c41fac96a after 600 seconds (00:12:36)
>    Failed compiling packages > windows_app_lifecycle/f0d1a97facb664da270ec290e135c9644bca17a8: Timed out pinging to d32c791f-7604-49ad-b44f-375a3b7516ca after 600 seconds (00:12:36)
> 
> Error 450002: Timed out pinging to e1553100-4dcd-406b-b581-7de656071ccf after 600 seconds

I'm able to ssh into the vms. In the Task Debug Log is nothing special. 
Do you have any clue?

**Comment by allomov** [comment]
bosh director talks to bosh agent using nats messaging bus. possible problem is that you have different networks for BOSH and CF, and VMs in CF network does not have access to BOSH network. could you check it?

**Comment by cppforlife** [comment]
@StBurcher please see for debugging intstructions: http://bosh.io/docs/tips#unreachable-agent. running `grep -i error /var/vcap/bosh/log/current` typically will point to the error.

**Comment by StBurcher** [comment]
Hi,

we found out that the problem is in the IAAS level. A solution is not found yet. So, I will close this issue.

**Comment by StBurcher** [comment]
I'm facing a problem again deploying CF240. During the perparing package compilation, the error Timing out pinging to <UUID> occurs. 

I'm able to ssh into the VMs. The agent log is full of the following messages. 

    > 2017-01-16_15:13:52.76117 [ConfigDriveMetadataService] 2017/01/16 15:13:52 WARN - Failed to load config from /dev/disk/by-label/CONFIG-2 - Reading files on config drive: Failed to get file contents, disk path '/dev/disk/by-label/CONFIG-2' does not exist
    
    > 2017-01-16_15:13:52.76117 [ConfigDriveMetadataService] 2017/01/16 15:13:52 WARN - Failed to load config from /dev/disk/by-label/config-2 - Reading files on config drive: Failed to get file contents, disk path '/dev/disk/by-label/config-2' does not exist

and

    > 2017-01-16_15:13:49.14392 [File System] 2017/01/16 15:13:49 DEBUG - Checking if file exists /sys/class/net/lo/device
    
    > 2017-01-16_15:13:49.14395 [File System] 2017/01/16 15:13:49 DEBUG - Stat '/sys/class/net/lo/device' 2017-01-16_15:13:49.14396 [Cmd Runner]
    
    > 2017/01/16 15:13:49 DEBUG - Running command 'ifup --no-act eth0'
    
    > 2017-01-16_15:13:49.14550 [Cmd Runner] 2017/01/16 15:13:49 DEBUG -> Stdout: 2017-01-16_15:13:49.14552 [Cmd Runner] 2017/01/16 15:13:49 DEBUG - Stderr: ifup: interface eth0 already configured
    
    > 2017-01-16_15:13:49.14553 [Cmd Runner] 2017/01/16 15:13:49 DEBUG - Successful: true (0) 2017-01-16_15:13:49.14554 [attemptRetryStrategy]
    
    > 2017/01/16 15:13:49 DEBUG - Making attempt #0
    
    > 2017-01-16_15:13:49.14554 [clientRetryable] 2017/01/16 15:13:49 DEBUG - [requestID=515d5afb-4b24-4cf3-63e4-399f1e1ef2d7] Requesting (attempt=1): Request{ Method: 'GET', URL: 'http://169.254.169.254/latest/user-data' } 2017-01-16_15:13:49.32663 
    
    > [clientRetryable] 2017/01/16 15:13:49 DEBUG - [requestID=515d5afb-4b24-4cf3-63e4-399f1e1ef2d7] Request succeeded (attempts=1), response: Response{ StatusCode: 200, Status: '200 OK' }
    
    > 2017-01-16_15:13:49.90153 [settingsService] 2017/01/16 15:13:49 ERROR - Failed loading settings via fetcher: Unmarshalling settings wrapper: invalid character '<' looking for beginning of value
    
    > 2017-01-16_15:13:49.90162 [File System] 2017/01/16 15:13:49 DEBUG - Reading file /var/vcap/bosh/settings.json 2017-01-16_15:13:49.90163
    
    > [settingsService] 2017/01/16 15:13:49 ERROR - Failed reading settings from file Opening file /var/vcap/bosh/settings.json: open /var/vcap/bosh/settings.json: no such file or directory
    
    > 2017-01-16_15:13:49.90164 [main] 2017/01/16 15:13:49 ERROR - App setup Running bootstrap: Fetching settings: Invoking settings fetcher: Unmarshalling settings wrapper: invalid character '<' looking for beginning of value 2017-01-16_15:13:49.90175 [main] 2017/01/16
    
    > 15:13:49 ERROR - Agent exited with error: Running bootstrap: Fetching settings: Invoking settings fetcher: Unmarshalling settings wrapper: invalid character '<' looking for beginning of value
    > 2017-01-16_15:13:50.91835 [main] 2017/01/16 15:13:50 DEBUG - Starting agent

Any Idea?

Update:
If I using only 2 works, bosh compiles more packages as with 5 workers. 

Update 2:
One agent is there on not???

    > +-------------------------------------------------------------------------------------------+--------------------+-------+---------+-----------+ | VM                                                                  
    > | State              | AZ    | VM Type | IPs       |
    > +-------------------------------------------------------------------------------------------+--------------------+-------+---------+-----------+ | compilation-66f44067-17cd-4d87-9a0d-568edf77dfa5/0
    > (34a657ad-9273-4856-92d1-3e82aa5f78f6) | running            | INDIA |
    > xlarge  | 10.0.0.47 | |
    > compilation-f03b6ee0-02f3-4e14-b320-1b9439daa937/0
    > (9df21f0e-8cb7-4bbd-84c9-c664e86717eb) | unresponsive agent | INDIA | 
    > |           |
    > +-------------------------------------------------------------------------------------------+--------------------+-------+---------+-----------+

The IaaS was not the problem.

**Comment by cppforlife** [comment]
@StBurcher potentially looks like registry problem. cc @voelzmo is that right?

**Comment by voelzmo** [comment]
Yup, that seems like an issue with the registry. @StBurcher I remember you had some proxy issues earlier on. Could it be that `2017-01-16_15:13:49.90153 [settingsService] 2017/01/16 15:13:49 ERROR - Failed loading settings via fetcher: Unmarshalling settings wrapper: invalid character '<' looking for beginning of value` is reading some answer from the proxy?

You can try the following:
* Access a VM that got 'timed out pinging...' with the OpenStack console
* execute `curl http://169.254.169.254/latest/user-data -vv` and look for `registry.endpoint` and `server.name` in the json returned
* execute `http://<registry.endpoint>/instances/<server.name>/settings -vv`

You should see a json, but the above error indicates that you might see something else.

**Comment by StBurcher** [comment]
@voelzmo  Thank you for the tip. I found the problem in the manifest. The registration endpoint was not correct configured
