### ISSUE TITLE
bosh deploy Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201])

### ISSUE THREAD

**Issue by harshalk91** [cloudfoundry/bosh#1561]
Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201]) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"NeutronError\": {\"message\": \"The resource could not be found.\", \"type\": \"HTTPNotFound\", \"detail\": \"\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "103"
    "Content-Type"           => "application/json; charset=UTF-8"
    "Date"                   => "Fri, 13 Jan 2017 19:47:31 GMT"
    "X-Openstack-Request-Id" => "req-74cee047-9a6b-4db9-a7ec-96fe16861618"
  }
  :host          => "xxx.xxx.com"
  :local_address => "192.168.1.14"
  :local_port    => 42626
  :path          => "/v2.0/ports"
  :port          => 9696
  :reason_phrase => "Not Found"
  :remote_ip     => "10.104.68.18"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"

**curl https://my-openstack-host:9696 --insecure**
{"versions": [{"status": "CURRENT", "id": "v2.0", "links": [{"href": "http://my-openstack-host:9696/v2.0**
**curl https://my-openstack-host:5000/v2.0 --insecure**

{"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "https://my-openstack-host:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}}

**curl https://my-openstack-host:9292 --insecure
{"versions": [{"status": "CURRENT", "id": "v2.3", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://my-openstack-host:/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.1", "links": [{"href": "http://my-openstack-host:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://my-openstack-host:9292/v1/", "rel": "self"}]}]}**

**Comment by cppforlife** [comment]
cc @voelzmo

**Comment by voelzmo** [comment]
Closing this as conversation is already happening in https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/issues/59. @harshalk91 please refrain from cross-posting your issue without linking it in the future.
