### ISSUE TITLE
cat: /var/vcap/instance/name: No such file or directory

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1562]
```
$ bosh ssh --gateway_host 10.58.111.45 --gateway_user vcap --gateway_identity_file ~/Projects/bosh_deployments/bosh-lites/sshkeys/bosh-lites.pem
...
cat: /var/vcap/instance/name: No such file or directory
cat: /var/vcap/instance/id: No such file or directory
```

I've upgraded my bosh-lite to v260.3, I've uploaded the latest warden stemcell, and I'm using the latest bosh v1 cli. What else is required for `/var/vcap/instance/name` and `/var/vcap/instance/id` files to be created for the `PS1` to be setup correctly? (there is no `/var/vcap/instance/` folder created)

*Update:* I see `You are using CLI > 1.2579.0 with a director that doesn't support the new version format you are using. Upgrade your director to match the version of your CLI or downgrade your CLI to 1.2579.0 to avoid versioning mismatch issues.` during a deployment. But looking at the parent director which deploys the bosh-lite I see that its the latest v260.3:

```
| bosh-lite-45              | bosh-warden-cpi/30            | bosh-vsphere-esxi-ubuntu-trusty-go_agent/3262.7  | none         |
|                           | bosh/260.3                    |                                                  |              |
|                           | garden-runc/1.0.0             |                                                  |              |
|                           | port-forwarding/5             |                                                  |              |
```

**Comment by cppforlife** [comment]
@drnic yup. that's the result (cosmetic) of warden stemcells having older agent temporarily. there is a story to address that: https://www.pivotaltracker.com/story/show/134182747.

**Comment by drnic** [comment]
Ok cool thx






On Mon, Jan 16, 2017 at 3:24 PM -0800, "Dmitriy Kalinin" <notifications@github.com> wrote:












@drnic yup. that's the result (cosmetic) of warden stemcells having older agent temporarily. there is a story to address that: https://www.pivotaltracker.com/story/show/134182747.

**Comment by dpb587-pivotal** [comment]
I believe this was fixed by https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/c7b403b0aced4785cb8261fa2ecf525448bfc689.
