### ISSUE TITLE
Unable to start stopped job on a bosh-lite after reboot

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1566]
I recently had a bosh-lite instance which had some issues. I ran `bosh stop <job> --hard` on two instances, and and tried starting one back up. It was still having problems, so I restarted my bosh-lite. When the bosh-lite came back up, all VMs were unresponsive, as expected. After `bosh cck` ran a few times, everything was running except the two VMs that I had previously `bosh stop`ed.  `bosh cck` ignored them completely, as it thought they should be stopped, and they weren't running. However, `bosh vms` reported them in an unresponsive state (rather than `stopped`). 

When I tried to `bosh deploy` or `bosh start <job>` to rectify, I got errors during the `Preparing deployment` phase such as this: `Failed: Timed out sending 'get_state' to 104d1263-0e9f-4c47-beb4-fd77dfa7811e after 45 seconds`. I tried `bosh ignore instance` on the two VMs, but it still would not get past the `Prepare deployment` phase. In order to work through this, I had to go into the BOSH database, and run `update instances set state='started' where state='detached';` in order to trick `bosh cck` into thinking they should be checked. Then I needed to `bosh unignore instance` each of them, so that `bosh cck` would actually resolve their lack of existing.

It would be awesome if any of the following could be done to improve the user experience:
- Have `bosh vms` display `stopped` for instances that it thinks are detached, and aren't responding anymore (since they were turned off intentionally)
- Have the `Prepare deployment` phase ignore `unresponsive agents` that were intentionally stopped

**Comment by cppforlife** [comment]
> Have bosh vms display stopped for instances that it thinks are detached, and aren't responding anymore (since they were turned off intentionally)

In cli v2: `bosh -e root-bosh is -i` shows state in a separate column from process state.

> Have the Prepare deployment phase ignore unresponsive agents that were intentionally stopped

we are going to soon do some work to make bosh deploy be a bit more granular. i will see how much we can get away with when we compute desired configuration.

**Comment by cppforlife** [comment]
we also fixed resurrector/director interplay bug (in 261+) that possibly got you in this case in the first place.

**Comment by mfine30** [comment]
Hey @geofffranks, sounds like this issue has been resolved in more recent versions of the director, and there hasn't been much activity in the last year. If you're still concerned, feel free to re-open and let us know.
