### ISSUE TITLE
Bosh should (optionally?) warn about unused properties

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1568]
The bosh CLI should print (during deploy or when explicitly asked) the list of unused properties defined in the current manifest.

Specifically:
- if the value of a global property `GP` is not used by any job during erb rendering, bosh should emit a warning saying `global property GP is unused` (this should apply also if the value of `GP` is always overridden by job properties)
- if the value of a job property `JP` is not used during erb rendering on the job `J` where it's defined, bosh should emit a warning saying `job property JP is unused by job J`

**Comment by cnelson** [comment]
+100. I'd love to see this plus an option (--strict ?) that would cause a failure if unused properties exist so it could be used to lint manifests
