### ISSUE TITLE
Bosh could be smarter about persistent disk resizing

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1569]
Currently bosh, when asked to resize a persistent disk, does something like the following (at least with the vsphere CPI):

1. stop all jobs on the vm
2. creates a new empty volume with the desired final capacity
3. attaches the new volume to the vm
4. copies all data from old volume to new volume
5. detaches the old volume from the vm
6. deletes the old volume
7. start all jobs on the vm

While this has the neat property that it works both for expanding and shrinking the disk, it has a few downsides:
- step 4 can be very slow (hours) if the amount of data to be copied is big
- it temporarily requires additional storage (for both old volume and new volume) while resizing: this can be problematic if the volume is big

On platforms that support it, it could be ideal to instead do the following (for extending):

1. (optional) stop all jobs on the VM
2. ask the CPI to extend the volume (vsphere supports online extend)
3. ask the OS to rescan the block devices (or restart the VM if online rescan is not possible)
4. ask the FS to extend itself to fill the volume (ext4 supports online extend)
5. start all jobs on the VM

(for shrinking):

1. stop all jobs on the VM
2. unmount the FS (ext4 can't be shrunk online)
3. shrink the FS
4. ask the CPI to shrink the volume
5. ask the OS to rescan the block devices (or restart the VM)
6. mount the FS
7. start all jobs on the VM

**Comment by voelzmo** [comment]
+1, also thought about doing this on OpenStack before

**Comment by cppforlife** [comment]
Interesting data point: vsphere does not allow >2TB extension from the iaas pespective.

**Comment by CAFxX** [comment]
so maybe something like this?

1. stop all jobs on the VM
2. (if shrinking) unmount and shrink the FS
3. shutdown VM
4. ask the CPI to resize volume
5. start VM
6. (if extending) extend the FS
7. start all jobs on the VM

it may be less than ideal (requires a VM restart in all cases), but it should still solve the major pain points listed in my first message

**Comment by cnelson** [comment]
AWS EBS now supports online resizing.  it would be great if bosh made use of this:  http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-expand-volume.html

**Comment by giner** [comment]
I'm here with another suggestion. How about the following approach?

1. Create a new disk and attach to a VM.
2. rsync (with `--bwlimit` set to something reasonable) all files from the current disk to a new one
3. Stop all jobs
4. rsync once again with `--delete` option
5. Unmount both disks -> mount the new one to the right place -> delete the old one
6. Start all  jobs

**Comment by voelzmo** [comment]
current state:
* OpenStack CPI supports this with https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/cpi-resize-disk.yml
* we deliberately didn't do this for AWS, as there's a ridiculous rate limit of *once every 6 hours*
* not sure about other IaaS layers and their options/rate limits on native disk resizing

**Comment by dpb587-pivotal** [comment]
Related current state... we recently heard that, when opting in to both `enable_cpi_resize_disk` and `xfs` persistent disks, filesystems are not being resized from the OS perspective and requires a manual `xfs-growfs` after. Tracked in [#159212614](https://www.pivotaltracker.com/story/show/159212614).

**Comment by CAFxX** [comment]
Btw, related to @cppforlife comment about vSphere (https://github.com/cloudfoundry/bosh/issues/1569#issuecomment-277114859) it seems that the 2TB limitation is gone starting from ESXi 6.5

**Comment by CAFxX** [comment]
@voelzmo about the 6 hours rate limit on EBS, my understanding is that it is [per-volume](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/limitations.html). Coupled with the fact you are still going to support a fallback for things like shrinking, or for the IaaSes that don't support volume extension, it seems to me it would be still valuable to have (unless you want to resize the same disks multiple times per day - in which case #2021 may come in handy anyway).
