### ISSUE TITLE
Recent commit broke verify_multidigest 

### ISSUE THREAD

**Issue by ishustava** [cloudfoundry/bosh#1573]
Renaming package `verify-multidigest` to `verify_multidigest` breaks because Director still expects the binary in a path with `verify-multidigest`: https://github.com/cloudfoundry/bosh/blob/0774b5473302a89685cb6037905f23f98e3ff9a2/jobs/director/templates/director.yml.erb.erb#L176

/cc @cppforlife 

When deploying a manifest that references remote URLs, the `Verifying remote release` step fails with

```
05:20:57 | Downloading remote release: Downloading remote release (00:00:02)
05:20:59 | Verifying remote release: Verifying remote release (00:00:00)
            L Error: sh: 1: /var/vcap/packages/verify-multidigest/bin/verify-multidigest: not found
```

**Comment by cppforlife** [comment]
Fixed in e89c8222c8d73292b04c6c6c917af134abe18ce5.
