### ISSUE TITLE
BOSH should be able to use a non-writable bosh_config

### ISSUE THREAD

**Issue by liuweichu** [cloudfoundry/bosh#1576]
Use case:
We have several BOSH directors and we use several .bosh_config_xxx files to point to each director. For this reason we would like to store these files in version control along with our configuration, but to do so bosh-cli should avoid writing to them.
Currently we set the permission of these .bosh_config_xxx files to 400 to avoid files being modified, but bosh-cli would crash when trying to save the config.

Proposal:
if the config file in use is not writable bosh-cli should only print a warning instead of crashing

**Comment by liuweichu** [comment]
Would also be nice if new bosh-cli could apply this proposal

**Comment by tjvman** [comment]
@liuweichu Out of curiosity, what commands is the CLI crashing on? For commands whose primary purpose is to store information about the director/deployment (eg. `target` or `alias-env`), at least, failing seems like the correct behavior to me. If commands that only need read access are also failing that'd be concerning.

**Comment by mfine30** [comment]
As Tom pointed out, this file contains information, much of which we need to keep up to date for authentication. I don't think this is something that we are planning to add to the cli. I'd suggest looking to modify how the version control interplays with the CLI.
