### ISSUE TITLE
Docs refer to removed `existing_micro` rake task

### ISSUE THREAD

**Issue by camelpunch** [cloudfoundry/bosh#1580]
https://github.com/cloudfoundry/bosh/blob/develop/docs/running_bats_using_rake_tasks.md suggests using the `spec:system:existing_micro` rake task, which was removed in 961e2eeb6578f34f9104a7edd64c3bc6fc2f7877.

**Comment by cppforlife** [comment]
@monkeyherder any relation to bats switching to cli v2?

**Comment by dpb587-pivotal** [comment]
Closing - BATS docs were removed from this repo as part of d37203b446a9a1fc1c3dee9aec14ad555a6045bd; and related docs can now be found in the [cloudfoundry/bosh-acceptance-tests](https://github.com/cloudfoundry/bosh-acceptance-tests) repository.
