### ISSUE TITLE
upload release failed with error 500 - bosh with Azure-cpi

### ISSUE THREAD

**Issue by ntdt** [cloudfoundry/bosh#1581]
My bosh director has the following version of release and CPI
- Bosh
https://bosh.io/d/github.com/cloudfoundry/bosh?v=260.6
  sha1: 1506526f39f7406d97ac6edc7601e1c29fce5df5
- Azure CPI
 https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-azure-cpi-release?v=20
  sha1: fb0180c685714d064b5a467eb6f2b34388fadf0a

When  I upload a new release:

`bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease
Acting as user 'admin' on 'bosh'
Using remote release 'https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease'
HTTP 500: `

On bosh director, /var/vcap/data/sys/log/director/director.debug.log

> D, [2017-02-09 17:02:54 #53888] [] DEBUG -- Director: (0.000079s) SELECT NULL
> D, [2017-02-09 17:02:54 #53888] [] DEBUG -- Director: (0.000124s) SELECT * FROM "deployments" ORDER BY "name" ASC
> D, [2017-02-09 17:03:54 #53888] [] DEBUG -- Director: (0.000201s) SELECT NULL
> D, [2017-02-09 17:03:54 #53888] [] DEBUG -- Director: (0.000174s) SELECT * FROM "cloud_configs" ORDER BY "id" DESC LIMIT 1
> D, [2017-02-09 17:03:54 #53888] [] DEBUG -- Director: (0.000079s) SELECT NULL
> D, [2017-02-09 17:03:54 #53888] [] DEBUG -- Director: (0.000135s) SELECT * FROM "deployments" ORDER BY "name" ASC
> D, [2017-02-09 17:04:54 #53888] [] DEBUG -- Director: (0.000209s) SELECT NULL
> D, [2017-02-09 17:04:54 #53888] [] DEBUG -- Director: (0.000172s) SELECT * FROM "cloud_configs" ORDER BY "id" DESC LIMIT 1
> D, [2017-02-09 17:04:54 #53888] [] DEBUG -- Director: (0.000077s) SELECT NULL
> D, [2017-02-09 17:04:54 #53888] [] DEBUG -- Director: (0.000119s) SELECT * FROM "deployments" ORDER BY "name" ASC
> D, [2017-02-09 17:05:24 #53888] [] DEBUG -- Director: (0.000206s) SELECT NULL
> D, [2017-02-09 17:05:24 #53888] [] DEBUG -- Director: (0.000108s) BEGIN
> D, [2017-02-09 17:05:24 #53888] [] DEBUG -- Director: (0.000280s) INSERT INTO "tasks" ("username", "type", "description", "state", "deployment_name", "timestamp", "checkpoint_time") VALUES ('admin', 'update_release', 'create release', 'queued', NULL, '2017-02-09 17:05:24.001634+0000', '2017-02-09 17:05:24.001637+0000') RETURNING *
> D, [2017-02-09 17:05:24 #53888] [] DEBUG -- Director: (0.004212s) COMMIT
> E, [2017-02-09 17:05:24 #53888] [] ERROR -- Director: Errno::EACCES - Permission denied @ dir_s_mkdir - /var/vcap/store/director/tasks:
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:211:in `each'
> /var/vcap/packages/ruby/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/job_queue.rb:34:in `create_task'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/job_queue.rb:9:in `enqueue'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/api/release_manager.rb:81:in `create_release_from_url'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/lib/bosh/director/api/controllers/releases_controller.rb:21:in `block in <class:ReleasesController>'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
> /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-260.6.0/bin/bosh-director:37:in `<top (required)>'
> /var/vcap/packages/director/bin/bosh-director:16:in `load'
> /var/vcap/packages/director/bin/bosh-director:16:in `<main>'

I have to create manually this folder
`mkdir -p /var/vcap/store/director/tasks && chown vcap.vcap /var/vcap/store/director/tasks`
before able to upload a release.

**Comment by cppforlife** [comment]
i suspect you are using older version of bosh-init cli to deploy your director. rerun bosh-init deploy with newer version.

**Comment by ntdt** [comment]
Good guess, my bosh-init was out dated. Update to new version of bosh-init fix this problem.
