### ISSUE TITLE
SSL Private Keys on director disk should not be world-readable

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1584]
Seen on bosh v260.0.0 (00000000)

At the very least, the director.key file should be chmodded 0400.

```
/:/var/vcap/store/director/nginx# ls -l
total 12
-rw-r--r-- 1 vcap vcap  899 Feb  7 14:41 director.csr
-rw-r--r-- 1 vcap vcap 1704 Feb  7 14:41 director.key
-rw-r--r-- 1 vcap vcap  997 Feb  7 14:41 director.pem
```

**Comment by dpb587-pivotal** [comment]
Fixed in [v262](https://github.com/cloudfoundry/bosh/releases/tag/v262) via story [#139906531](https://www.pivotaltracker.com/story/show/139906531).
