### ISSUE TITLE
Access to job's properties inside of addon

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry/bosh#1585]
Hi there!

It would be very nice to have access to job's properties inside of addon (http://bosh.io/docs/runtime-config.html#addons).

For example, I have an agent that I want to deploy on each VM, and inside this agent I want to determine where my agent is running and depending on this I want my agent to run certain modules.

So inside my agent I want to store loadable config files, like
```
<% if p("consul.agent.mode") == 'server' %>
some_code_to_load_consul_module
<% end %>
```

Could you please consider adding this feature to the BOSH?

Thank you in advance!

**Comment by pivotal-jamil-shamy** [comment]
@antonsoroko could this be achieved through [BOSH links](http://bosh.io/docs/links.html) ?

**Comment by antonsoroko** [comment]
@pivotal-jamil-shamy 
Hi.
Thank you for your response.

I'm afraid not.
Even if bosh links work for bosh addons, I need access to a large number of properties, so I will need to create a lot of `provides` properties for every interesting job (and then maintain these new properties, for example, for `cf-release`; furthermore in case of PCF this is even impossible, I believe) and then add all these properties as `consumes` to bosh agent. And I guess I will need to mark all these links as `optional` even if they aren't mine, otherwise, the agent cannot be deployed everywhere (as I understand).

**Comment by cppforlife** [comment]
> I need access to a large number of properties

what exactly is your job doing?

**Comment by antonsoroko** [comment]
@cppforlife 
Hi.

>what exactly is your job doing?

Monitoring :-)

I want to deploy my agent everywhere, and then dynamically load necessary modules depending on environment.
e.g.
```
<% if p("consul.agent.mode") == 'server' %>
some_code_to_load_consul_module
<% end %>
```

**Comment by hkumarmk** [comment]
+1

I would probably add consul-agent as runtime config with a list of consul-services which would be populated depending upon the releases an instance is loaded. This would be a nice feature to support bunch of other scenarios where we would need customized runtime config according to the releases/applications installed on instances.

**Comment by mfine30** [comment]
This isn't something that we are likely to add to BOSH. While tedious, links and a strong contract between various jobs/releases is still our recommended to ensure release authors are explicit in the behavior that they intend to support.

**Comment by antonsoroko** [comment]
@mfine30 
Hi.
I am not sure that links are useful in this particular case, but okay.
