### ISSUE TITLE
BOSH addons can't deploy same/different release of job

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry/bosh#1586]
Hi.

I added my job as a BOSH agent, and then I tried to add the same job to templates of VM and I got this error:
```
Error 100: Colocated job 'xxx' is already added to the instance group 'dedicated-node'.
```
Just to clarify - I used `version: latest`, if instead of `latest` I write version from `bosh runtime config` - bosh will not complain. But please note that in this case `latest`==version from `bosh runtime config`.

Then I tried to add newer release version and I got this error:
```
Error 530003: Runtime manifest specifies release 'xxx' with version as '9.2'. This conflicts with version '9.2+dev.1' specified in the deployment manifest.
```
In this case it does not matter how I specify the version - neither `latest` nor `9.2+dev.1` does not work.

BOSH version is 260.0.0.

I guess that these issues are similar to #1180 .

Could you please help me with these issues?

Thank you in advance.

**Comment by antonsoroko** [comment]
The same for 261.

**Comment by antonsoroko** [comment]
@cppforlife 
Thus, there is no way to upgrade version of my agent other than through `bosh rutime config`?

And if I want to add my agent explicitly to VM - I must to specify the same version as in `bosh rutime config`, right?

**Comment by cppforlife** [comment]
@antonsoroko correct, we are planning to add deployment level addons which might be something that may fit your use case better (add a job to all vms in current deployment?)

**Comment by antonsoroko** [comment]
@cppforlife 
Hi.
Thank you for your response.

My case is more connected with #1585 - I want to install agent to all VMs, so but becasue of #1585 I started thinking about possible workarounds. So in this case I was thinking about adding new version of my agent to some specific VM (via releases and templates sections) so that my agent will have access to properties of this VM (and to its own custom properties, defined in `properties` section of `job`).

**Comment by antonsoroko** [comment]
@cppforlife 
Hi.
Actually, `deployment level addons` feature sounds interesting for me too. Is there any ETA for it?)

**Comment by antonsoroko** [comment]
@cppforlife 
Hi.
As I understand you talked about this story https://www.pivotaltracker.com/n/projects/956238/stories/118799931, right?

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/n/projects/1954971/stories/139612921 (the story you found looks like it was the original and lost between projects; will probably delete that one).

Related PR: https://github.com/cloudfoundry/bosh/pull/1628

**Comment by antonsoroko** [comment]
@dpb587-pivotal 
@cppforlife 

Hi. 
Unfortunately, "deployment level addons" feature does not solve this issue because we are talking about "top level" addons (in this particular case).
Also `exclude` section in addons also does not solve this issue, because release versions check is triggered before `exclude` rules.

Also we have discussed this issue with @barthy1 , and she have some tech ideas/details.

Thanks in advance.

**Comment by mrosecrance** [comment]
Closing, as it's very stale. If this is still an issue, we can always reopen it.
