### ISSUE TITLE
BOSH status for failed errands should show `error` instead of `done`

### ISSUE THREAD

**Issue by avade** [cloudfoundry/bosh#1592]
For an errand that returns a non-zero exit code bosh returns `done` rather than `error`. To find out the result of an errand we will have to call GET /tasks/{id}/output?type=result to get programmatic access to the exit code.
```
 curl https://<secret:stuff>@104.199.47.211:25555/tasks/7330/output?type=result -k
{
  "exit_code": 0,
  "stdout": "[upgrade-all-service-instances] 2017/02/16 19:05:09 Service instance upgrades completed\n",
  "stderr": "",
  "logs": {
    "blobstore_id": "22baed01-47fc-4510-7844-88568c7edd73"
  }
}
```

@cppforlife wdyt of adding more granular status to errands?

cc @Samze

**Comment by dk** [comment]
wrong number?

**Comment by avade** [comment]
Do you mean the errand is exiting with the wrong exit code?

**Comment by dk** [comment]
sorry I meant you're probably dialing the wrong 'dk' here

**Comment by avade** [comment]
Ahh sorry fixed it :D

**Comment by cppforlife** [comment]
@avade hmm interesting; didnt notice this before.

the act of running an errand completed successfully (done state) but one of errands within run-errand task may have resulted in non-0 code. currently client is responsible for evaluation of exit code(s). this further extends to running multiple copies of an errand on multiple instances, hence it may return multiple results ( `{...}{...}{...}` ) with different exit codes.

i think this is also inline with bosh vms for example. even though some agent may return errors for communication bosh vms task did succeed completing without task level errors.

changing this though would be a backwards incompatible change...

cc @voelzmo @tjvman i think you guys may also have opinions on this (semi related to bosh task returning an error).

**Comment by mfine30** [comment]
@kieron-pivotal I'm guessing that Alex opened this on behalf of ODB last year. Do you know if this is an issue that you all are interested in?

**Comment by kieron-pivotal** [comment]
@mfine30 We've switched to using the BOSH CLI go library now, so this is no longer an issue for us. Thanks.

**Comment by mfine30** [comment]
Great. I'm going to close this issue - thanks!
