### ISSUE TITLE
How to create a bosh account with readonly access on director?

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/bosh#1594]
By following `Adding/removing Users and Permissions`(https://bosh.io/docs/director-users-uaa.html#uaac), it said the newly added user has readonly access but I was able to `run bosh recreate job index 0` command after I login as this newly added user.

I tried to remove this newly added user from bosh.admin group but failed.

```
ubuntu@pivotal-ops-manager:~$ uaac member delete bosh.admin david

RuntimeError: no existing users to delete

ubuntu@pivotal-ops-manager:~$
```

From the output of command uaac user get user_name it turned out the newly added user `david` was the exact the same with default user, `director`.

<img width="1036" alt="screen shot 2017-02-20 at 1 14 51 pm" src="https://cloud.githubusercontent.com/assets/17395452/23152533/aada2b68-f83d-11e6-8db1-86e450d6fc75.png">

**Comment by cppforlife** [comment]
@David-Pivotal i think it really depends on how you configure UAA. cc @sreetummidi @fhanik

**Comment by David-Pivotal** [comment]
Thank you for your comments. Could you suggest how I can configure UAA to eliminate bosh.admin?

**Comment by mfine30** [comment]
We recently updated the docs here: https://bosh.io/docs/director-users-uaa-perms/#full-read. Given the limited activity, I'm going to close this due to age.
