### ISSUE TITLE
With Ubuntu stemcell 3363 or 3363.1, there is decreased network performance

### ISSUE THREAD

**Issue by flawedmatrix** [cloudfoundry/bosh#1596]
IAAS: AWS
Stemcell versions: 3363 or 3363.1 (Both AWS Xen-HVM and AWS Xen-HVM Light)
OS: Ubuntu Trusty
VM Types: c3.large

VMs are deployed in the same placement group for maximum networking performance and stability.

Test setup (using elements of https://github.com/cloudfoundry-incubator/routing-perf-release):
Static web server (`gostatic`) running in a c3.large VM.
HAProxy configured to forward TCP traffic on designated ports the static web server (`tcp-router` from CF Routing Release)
Performance testing errand running in a c3.large VM.

This errand essentially runs a load testing tool (https://github.com/rakyll/hey) on HAProxy to measure HAProxy's performance when forwarding HTTP traffic using TCP proxying.

Running the load testing tool:
`hey -c 64 -n 1500160 http://HAPROXY-ADDRESS:PORT`

With stemcell version 3312.18:
```
Summary:
  Total:	31.7902 secs
  Slowest:	0.2035 secs
  Fastest:	0.0003 secs
  Average:	0.0014 secs
  Requests/sec:	47189.3936
  Total data:	1536163840 bytes
  Size/request:	1024 bytes

Status code distribution:
  [200]	1500160 responses

Response time histogram:
  0.000 [1]	|
  0.021 [1499097]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.041 [901]	|
  0.061 [153]	|
  0.082 [7]	|
  0.102 [0]	|
  0.122 [0]	|
  0.143 [0]	|
  0.163 [0]	|
  0.183 [0]	|
  0.204 [1]	|

Latency distribution:
  10% in 0.0011 secs
  25% in 0.0012 secs
  50% in 0.0013 secs
  75% in 0.0014 secs
  90% in 0.0015 secs
  95% in 0.0015 secs
  99% in 0.0031 secs

requests_per_sec: 47189.3936
90% of response times: 0.0015 secs
95% of response times: 0.0015 secs
99% of response times: 0.0031 secs
```

With stemcell version 3363+:
```
Summary:
  Total:	46.9886 secs
  Slowest:	0.0830 secs
  Fastest:	0.0002 secs
  Average:	0.0020 secs
  Requests/sec:	31926.0268
  Total data:	1536163840 bytes
  Size/request:	1024 bytes

Status code distribution:
  [200]	1500160 responses

Response time histogram:
  0.000 [1]	|
  0.009 [1495006]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.017 [3038]	|
  0.025 [1476]	|
  0.033 [315]	|
  0.042 [100]	|
  0.050 [95]	|
  0.058 [47]	|
  0.066 [49]	|
  0.075 [21]	|
  0.083 [12]	|

Latency distribution:
  10% in 0.0014 secs
  25% in 0.0019 secs
  50% in 0.0020 secs
  75% in 0.0020 secs
  90% in 0.0022 secs
  95% in 0.0024 secs
  99% in 0.0036 secs

requests_per_sec: 31926.0268
90% of response times: 0.0022 secs
95% of response times: 0.0024 secs
99% of response times: 0.0036 secs
```

We have consistent results with the old stemcell (~44000 requests per second) vs the new stemcell (~32000 requests per second), so it seems like there is something in the new stemcells that causes this performance regression.

You might be able to reproduce the same issue without HAProxy and directly generating load to the static web server.

Please look into this issue.

Thanks,
Edwin and @swetharepakula

**Comment by shalako** [comment]
cc @dsboulder @richardsalloum

**Comment by tjvman** [comment]
This was investigated in https://www.pivotaltracker.com/story/show/140452723 and concluded to not be caused by 3363 stemcell (the issue was reproduced in earlier lines).
