### ISSUE TITLE
bosh tasks should have a type

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/bosh#1597]
As a consumer of the bosh director API
I want to know that a task is an errand (without grepping the description)
So that I know when to retrieve the output result

Suggestion:
Add `"type": "<errand|deployment|vms|etc...>"` to the response from `GET /tasks/{id}`.

Context:
When we query tasks by context ID we want to differentiate between deployment and errand tasks.

cc @cppforlife @avade

**Comment by cppforlife** [comment]
so effectively splitting off type and description columns.

**Comment by cppforlife** [comment]
cc @frodenas

**Comment by aclevername** [comment]
Bump
