### ISSUE TITLE
Migrate some bosh deployments to a different bosh instance

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/bosh#1601]
Has anyone ever tried this kind of migration?  

I suppose we have to extract from the database all records related to the specific deployments and then run on the new bosh a ```bosh upload release --fix``` and a re-deploy to fix the director uuid and the agents.

Am I missing something? Do you have any suggestion?

Thanks,
Michael

**Comment by cppforlife** [comment]
@tyyko never tried it myself. i would recommend if you are going to do that to potentially consider copying over entire database and then deleting things that are not relevant (foreign keys should help here). 

as a more general question, why are you trying to do this?

**Comment by tyyko** [comment]
You mean that if I delete a certain deployment postgres will do some kind of CASCADE delete and take with him all related info? 
If not, what is the advantage of finding all info to delete or finding all info to extract?

The reason is we started with 'one bosh for everything' (infrastructure deployment and on-demand cloud foundry services) and now we would like to have one bosh only for infrastructure deployment and one only for services created by our service broker but we need to move out all services from the first bosh to the second.

**Comment by emirozer** [comment]
@tyyko Hi, I am also curious, have you actually attemted to do this?

**Comment by tyyko** [comment]
Yes, but not in production due to shift of priorities.


This is what was done with a starting point of one bosh director with deployments X and Y: 
- deploy a second bosh
- clone disk and database of the first, attach them to the new one to have 2 copies of the same director
- from one DB delete deployment X, from the other DB delete deployment Y (*)
- redeploy Y with the new target to 'tell' Y to send/fetch data from the second director

(*) [draft of the database query](https://gist.github.com/tyyko/578349314f696f563845e7b5ff21d284) (NOTE: logs/events from deleted deployments remain there, did not spent effort to delete them. Also keep in mind the query  is from serveral weeks ago, db structure might have changed) 

best,
Michael

**Comment by emirozer** [comment]
Thank you very much Michael!

**Comment by dpb587-pivotal** [comment]
Closing since discussion seems to have provided some unofficial workarounds.

**Comment by emirozer** [comment]
Just out of curiosity is there an official way of doing this migration?

**Comment by tyyko** [comment]
Unfortunately not that I am aware of :(
