### ISSUE TITLE
Confusing error message: "Error 190014: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config."

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/bosh#1604]
I don't need help debugging the problem, but I wanted to ask for an improved error message.

To reproduce it, deploy a v2-schema manifest (specifically, with a `stemcells` section) to a director that doesn't have a cloud-config uploaded. The error message says:
```
Error 190014: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config.
```
Originally, the error message made it sound like the `stemcells` section was supposed to be in the cloud-config instead of the manifest. Eventually, we figured out that you can only deploy a manifest with a `stemcells` section if your director had a cloud-config present already.

Could the error message say something like, "Deploy manifest contains 'stemcells' section, which is valid only if you've already uploaded a cloud-config to your director."

**Comment by domdom82** [comment]
hi I just stumbled over this exact issue. Confused the heck out of me until I realized it had nothing to do with my stemcells section but with missing  cloud-config upload to director. The message should really point that out.

**Comment by drnic** [comment]
I saw this error message today and misinterpreted it too and had to go Googling (and found this ticket).

Perhaps alternate error: "Your deployment manifest contains 'stemcells' section, but your director does not yet have a cloud-config."

**Comment by domdom82** [comment]
@drnic feel free to update my PR :)

**Comment by freddesbiens** [comment]
This has been fixed and will appear in our next release. The revised error message is: 

`Error: Deployment manifest contains 'stemcells' section, but it can only be used with cloud-config enabled on your bosh director.`

Thank you for your patience!
