### ISSUE TITLE
bundle install not working on master

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh#1609]
Checkout origin/master and run `bundle install` at the `src` folder.
This results in error: `Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'blobstore_client'`

https://github.com/cloudfoundry/bosh/commit/4120d12fe501fb6a2a8c1f0f4e6ba8d578101bb9 removed the `blobstore_client` from the Gemfile

**Comment by Kiemes** [comment]
The dependency comes via https://rubygems.org/gems/bosh_cli/

**Comment by cppforlife** [comment]
@Kiemes are you changing gemfile in any way? our ci seems to be passing and there is no blobstore_client in the Gemfile/Gemfile.lock

**Comment by tylerschultz** [comment]
I think you'll need to `gem uninstall bosh_cli` for bundle install to work.

**Comment by Kiemes** [comment]
@tylerschultz thx, that helped. I had an old bosh_cli gem 0.0.0 installed which was just reused by bundler. @cppforlife pipelines were green because you start with a clean gemset.
