### ISSUE TITLE
Ability for bosh addons to exclude errand VMs

### ISSUE THREAD

**Issue by oozie** [cloudfoundry/bosh#1613]
Per [bosh runtime-config doc](https://bosh.io/docs/runtime-config.html) an include option exists. Word has it the latest bosh also supports `exclude` keyword. We'd like for the `exclude` keyword to allow for exclusion of errand VMs. 

Problem: one of our bosh addons has a pretty expensive init step, i.e. it downloads a database locally. This is a pointless operation on an errand VM because the VM goes away. Additionally, that particular errand runs on a nano instance with only 512mb of RAM and causes the CF deployment to fail.

**Comment by cppforlife** [comment]
i think you could do that via exclude jobs configuration.

**Comment by cppforlife** [comment]
@oozie does that work for you?

**Comment by oozie** [comment]
Apologies for a delay in responding @cppforlife 
I've been trying to figure out how to `exclude:` only from errand machines, rather than particular jobs/deployments. What I want to avoid is maintaining a blacklist of errands under exclude.
If you have any hints on how to accomplish excluding from errands that would be great.

**Comment by jfmyers9** [comment]
This has been implemented as of https://github.com/cloudfoundry/bosh/pull/1902.
