### ISSUE TITLE
Removing an AZ in cloud-config and cpi-config should not be possible if there are instances in that AZ

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1614]
## Setup
* have a cloud-config with 2 AZs
* use multi-cpi to have each AZ with a different CPI configuration
* deploy something with instances in 2 AZs: z1 and z2

After the successful deployment:
* upload a new cloud-config which *removes* z2
* upload a cpi-config which *removes* z2

## Expectation
That shouldn't be possible. It is impossible to delete resource in those other AZs and you'll end in a world of pain if you try dealing with resources for which the director "doesn't know" in which AZ they are.

## Actual
BOSH allows me to update all these configurations without an error. There even is explicit logic included that iterates over all configured CPIs for that case apparently, see story https://www.pivotaltracker.com/story/show/134542183. 

## Why is this a problem?
Let me now update my deployment manifest, removing z2 and scaling down instances accordingly. 
* BOSH *cannot* delete those instances, they will just hang around forever. 
* `bosh deploy` won't even fail, it completes successfully
* resurrection in that AZ doesn't work
* executing a command for all CPIs is potentially dangerous
* the difference between https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/cloud_factory.rb#L47 and https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/cloud_factory.rb#L60 is very subtle and unclear when to actually use those two things properly.

## Propsal
* Always return a single CPI in cloud_factory
* Don't allow removing AZs from cloud-config or cpi-config when there are resources in there

wdyt?

**Comment by cppforlife** [comment]
@voelzmo this is a tough one since preventing people from modifying cloud and cpi configs by correlating to kept state is possible, but im not sure worth of additional complexity introduced.

**Comment by jfmyers9** [comment]
Closing and reopening to generate a github story.
