### ISSUE TITLE
https://main.bosh-ci.cf-app.com/ not working for me

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1616]
I'm sure if its down for core team they'll notice too; but just dropping a note.

FYI I was hunting down the secret-ish pre-compiled bosh releases. bosh-deployment's bosh.yml has a link to an older bosh 260.x

**Comment by cppforlife** [comment]
@drnic this was done on purpose to further isolate our CI (that produces final releases and stemcells) from) from potential malicious actors. we currently have no plans to expand access. all pipeline to my knowledge should be checked in our public repos.

**Comment by dpb587** [comment]
Personally, I wish this was still public. As an open source repo, I think it's important to be able to refer people to what the builds are and what tests should look like. Particularly when contributors are interested in running tests locally and looking for a baseline. I also tend to trust repos more if they're able to show me their "continuous"ness, even if it may be a bit superficial.

If security is a concern for that, we should have a separate, super-restricted deployment for stemcells in a dedicated account.

**Comment by dpb587-pivotal** [comment]
Closing - there are still no plans to expand access to Concourse. All CI-related tasks should be committed in the [`ci/`](https://github.com/cloudfoundry/bosh/tree/master/ci) directory so others can run it against their own Concourse or Concourse lite installations.
