### ISSUE TITLE
Publish pre-compiled bosh release publicly

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1617]
bosh-deployment repo has a `bosh.yml` with a not-well-known URL to a precompiled version of bosh.

OMG OMG OMG it makes `bosh create-env`/`bosh-init` so much faster.

I didn't know until Friday that the whole implementation of precompiled releases was changed - that they are now embedded inside a normal release. This is awesome.

Could we please link to these pre-compiled URLs in bosh.io/releases?

Really, I have so many excited questions that follow on from this - can bosh.io/releases include pre-compiled releases (for latest stemcell) rather than just src release? 

Does `bosh finalize-release` work on compiled releases? If I export a compiled release during my pipeline and `finalize-release` it will I get what I expect? I assume so since the compiled bits are referenced by package guids not by version numbers.

I'm so excited for a pre-compiled-by-default future.

**Comment by cppforlife** [comment]
@drnic i was just chatting with @tylerschultz last week about having finalize release work with compiled releases. that way consumption of releases continues to work via official ways (git repo with yaml receipts).

**Comment by drnic** [comment]
Ok lovely

**Comment by drnic** [comment]
Closing as the various questions are answered/covered above or in other tickets.
