### ISSUE TITLE
Include original src packages in export-package output

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1623]
Currently exported/compiled packages include the jobs + compiled packages, but not the original src packages.

This means you can get deployment errors:

```
Can't use release 'bosh/261.4'. It references packages without source code and are not compiled against stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3312.17':
 - 'director/a6bbfcee2c7cf65840ec525b6e3181da6cf59598'
 - 'health_monitor/3f862a244cfd5e81067300543a537757cb590b7e'
 - 'registry/7751f332d697c84b5137bdbc7a6cea78fffde75d'
```

The workaround is to upgrade/downgrade the stemcell - but this might not be sufficient for all situations. It's also not possible to re-upload a compiled nor src release for a new stemcell https://github.com/cloudfoundry/bosh/issues/1620

An uploaded compiled release could support any stemcell by having included the original src packages.

**Comment by voelzmo** [comment]
I keep arguing about this since forever. @cppforlife, can we have this now? Would solve so many problems, even compiled releases for cpis in create-env would only be half of a problem then...

**Comment by cppforlife** [comment]
@drnic @voelzmo we are purposefully avoiding including source because:

- producers of compiled releases want to obfuscate source of the release
- additional size consideration -- sometimes it's almost double the size if source is included

we also have plans to strip packages from compiled releases that are only necessary for compilation.

**Comment by drnic** [comment]
I think I've covered my discovered issue - new stemcells but with old releases - in the other ticket. If the solution isn't via flexible releases; then we'll need a way to re-upload releases to inject new compiled packages (as per other ticket).
