### ISSUE TITLE
Stemcell 3363.12  root password

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry/bosh#1624]
Hi, 

I ssh to bosh Vm as vcap user, but i couldn t switch to root user, since the old password `c1oudc0w` doesn t work. 

Can any one tell me please, what is the new password. 

Thank you,
Fadhel

**Comment by drnic** [comment]
To set the vcap password try:

resource_pools:
- name: bosh
  env:
    bosh:
      password: (( param "Please generate a SHA-512 crypted password the
vcap system user" ))

**Comment by dpb587-pivotal** [comment]
^ the `(( param ... ))` syntax is *not* standard

You may want to use `mkpasswd -s -m sha-512` to generate the value you need.

Passwords are auto-generated in recent stemcells.

**Comment by cppforlife** [comment]
@fghorbel we recommend that you dont use vcap for ssh access. consider colocating os-conf's user_add job for additional user configuration: https://github.com/cloudfoundry/os-conf-release/blob/master/jobs/user_add/spec

**Comment by fghorbel** [comment]
Thanks!

**Comment by fghorbel** [comment]
Hi guys, 

I tried this

```
resource_pools:
- name: bosh
  env:
    bosh:
      password: jihngfur;gtweurhpgtiorehwterouthnrwepteironh

```
I saw the password got changed in /etc/shadow but when i try to do `su vcap` and enter the password. it got `permission denied`

**Comment by dpb587-pivotal** [comment]
Make sure you use `mkpasswd` to generate a crypt-format `password` value.

Password should look something like...

    $6$GyY390IOH$DxiX1ai81ZYAbCR8JY7Re8EF92PpzsxUeXF1R.C.y6.Vzg7lk3x9B6e1daPD/rwVfXud86k4iPbh7oMFvVfvF0

**Comment by fghorbel** [comment]
Yes i used `mkpasswd -s -m sha-512`. As i said, i saw the password got changed in /etc/shadow, but i can not still access.

**Comment by dpb587-pivotal** [comment]
Okay, because I was confused to see `jihngfur...` in your snippet when I expected to see something like `$6$...`. Was the password in `/etc/shadow` in the crypt format?

**Comment by fghorbel** [comment]
yes.
