### ISSUE TITLE
If BOSH could tell me which job is having trouble with my links, it would be more helpful

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh#1632]
# I find the "ambiguous link" error message to be very confusing since it tells me which instance group but not which job is failing:

```
Error 100: Unable to process links for deployment. Errors are:
   - "Multiple instance groups provide links of type 'baggageclaim'. Cannot decide which one to use for instance group 'worker'.
     concourse.worker.baggageclaim.baggageclaim
     concourse.bosh-lite-aws-worker.baggageclaim.aws-bosh-lite-baggageclaim"
```

# This is especially confusing since it is challenging to discover all the links provided and consumed by your deployment.

If you dig into your releases you can find spec files that show all the links available and consumed by your jobs, but it can be confusing to figure out which jobs are providing links and which are consuming them.  

For example, when we tried to deploy an additional concourse worker instance group we had to disambiguate the `baggageclaim` link.  It was consumed (optionally) via its type by the `groundcrew` job in both instance groups.  The `baggageclaim` job itself did not require its own link, but that was not obvious to us at first.  We followed this process to fix the problem:

1. We first assumed that `baggageclaim` was consuming its own link and renamed the link within the second worker instance group (which did not change our error messages at all).
2. We discovered the `groundcrew` spec optionally consumes the link and consumed the disambiguated `baggageclaim` link, which got rid of one error.
3. We noticed that the link was being consumed by its type and thus renaming would not solve the problem for the preexisting concourse worker instance group, so we had to disambiguate the preexisting concourse worker's `baggageclaim` link as well.
4. We discovered a new error message indicating that the `baggageclaim` job could not consumer a link `baggageclaim`, and removed that link's consumption from the deployment manifest, which resolved our error.

# Two suggestions:
1. Provide some way to discover all the links being provided and consumed by a deployment, grouped by instance groups.
2. Provide feedback on exactly which job is failing to fill-in the link (rather than just on the instance group)

**Comment by jfmyers9** [comment]
Seems like this has probably been addressed as of [this story](https://www.pivotaltracker.com/n/projects/2132440/stories/158077990). Feel free to reopen if this is still an issue.
