### ISSUE TITLE
Unable to redeploy an existing VM with static IP to include availability zone info

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1633]
I'm trying to take a deployment using cloud config that did not make use of `azs`, and migrate it to use `azs`. I updated the azs in cloud config under `azs`, and `networks.[0].subnets.[0].azs`. I updated the azs list in `instance_groups.myjob.azs`. When deploying, I get the following error:

```
Director task 1076
  Started preparing deployment > Preparing deployment. Failed: Existing instance 'haproxy/0' is using IP '10.0.1.48' in availability zone '' (00:00:01)

Error 130010: Existing instance 'haproxy/0' is using IP '10.0.1.48' in availability zone ''

Task 1076 error
```

**Comment by dpb587** [comment]
I've run into this, too. Wasn't sure the correct workaround and ended up patching director code to ignore the specific address where it would have raised. Was able to continue the deploy since it deleted the existing VM first. I don't recommend patching director code though :)

**Comment by ronakbanka** [comment]
@geofffranks we are a facing similar issue, any proper way to tackle this error?

**Comment by geofffranks** [comment]
@ronakbanka I *believe* you just need to specify `migrated_from` on the job. Keep the name the same, and set the `migrated_from.az` to the AZ you want the VM to be placed in when bosh recreates it.
