### ISSUE TITLE
Deploying when using cloud config should not show irrelevant changes

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1634]
Can we make it so the diff displayed by bosh for a deploy does not show cloud-config changes that do not apply to the current deployment?

For example, if I change my `vm_type: redis` to have a bigger instance size, it would be nice to not see that as a change when deploying rabbitmq, or cloudfoundry.

**Comment by geofffranks** [comment]
Can this also be done for runtime-config? (Don't need to see that you're adding releases/jobs to all my VMs if it's not actually being included in this deployment)

**Comment by jfmyers9** [comment]
After a few attempts, I was not able to recreate this issue with cloud configs. There is a chance that this has been fixed at some point in the last year.

However this doesn't appear to be done for runtime configs. If this is still an issue, feel free to create a new issue.

Thanks!
