### ISSUE TITLE
Display changes to (cloud|runtime)-config when running update-(cloud|runtime)-config

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1636]
I'd love to see `bosh update-cloud-config` and `bosh update-cloud-config`show you a diff of the runtime/cloud-config changes when updating it, similar to the diff you see when doing a `bosh deploy`.

**Comment by dpb587-pivotal** [comment]
Related CLI issue: https://github.com/cloudfoundry/bosh-cli/issues/7

**Comment by tjvman** [comment]
Closing - Config diffing is available with CLI v2, starting with [v.2.0.30](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.30)
