### ISSUE TITLE
After bosh update cloud-config, deploying failed at subnet overlaps in 'create_vm' CPI method

### ISSUE THREAD

**Issue by xiujiao** [cloudfoundry/bosh#1638]
I upload cloud config using `10.244.0.0/24` subnet in https://github.com/cloudfoundry/bosh-deployment/blob/master/warden/cloud-config.yml and deployed a deployment called `zookeeper` as in https://raw.githubusercontent.com/cppforlife/zookeeper-release/master/manifests/zookeeper.yml; then I updated cloud config using https://github.com/cloudfoundry/cf-deployment/tree/master/bosh-lite, and deploy cf on bosh- lite following https://github.com/cloudfoundry/cf-deployment. It says ` Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '088d75b3-eebc-4800-a1ad-639de487ece3': Creating container: the requested subnet (10.244.0.0/22) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method`. I changed `zookeeper.yml` to use the setting in the new cloud config, it still did not solve any problem. Ideally, when we upgrade cloud config, we should be able to redeploy successfully.

**Comment by dpb587-pivotal** [comment]
The cloud-config from cf-deployment uses `10.244.0.0/22`, but the cloud-config from bosh-deployment has already configured `10.244.0.0/24` (and has existing VMs there). Currently BOSH does not support shrinking the network size, particularly if there are existing VMs running.

To fix, you'll either want to recreate your bosh-lite and avoid testing the zookeeper config, or you'll want to...

1. delete the zookeeper deployment
1. update cloud-config from cf-deployment
1. deploy cf

Note: you can redeploy zookeeper alongside cf, just don't try to resize the network.
