### ISSUE TITLE
Error 100: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<NoMethodError: undefined method `[]' for nil:NilClass>

### ISSUE THREAD

**Issue by subhashgunda** [cloudfoundry/bosh#1642]
Deploying
---------

Director task 835
  Started preparing deployment > Preparing deployment. Done (00:00:02)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started creating missing vms
  Started creating missing vms > consul_server/fcae467f-7c97-498c-84f1-c981d28ab094 (0)
  Started creating missing vms > nats/5e3a1e14-0bc6-446e-91b3-d758e6abd9de (0)
  Started creating missing vms > etcd_tls_server/6d9d7a50-5069-4098-87df-0f63d894c848 (0)
  Started creating missing vms > nfs_server/429c9792-9a5b-401a-89ec-b1a79e918e60 (0)
  Started creating missing vms > mysql_proxy/a7ddb8b2-31ad-46b6-86a4-0cf4339c8efc (0)
  Started creating missing vms > etcd_server/0c5f56ae-3fb6-4114-9cd4-dd5a148b02ee (0)
  Started creating missing vms > mysql/3c628b13-8269-482a-a27a-2777026acc77 (0)
  Started creating missing vms > uaa/e311151b-5586-4bf0-af09-16f2cffd5103 (0)
  Started creating missing vms > cloud_controller/b8f1a4ad-b501-4c2c-8f88-321712ec0f30 (0)
  Started creating missing vms > ha_proxy/c177861b-893f-487f-9eae-befc913f824f (0)
     Done creating missing vms > mysql_proxy/a7ddb8b2-31ad-46b6-86a4-0cf4339c8efc (0) (00:02:22)
  Started creating missing vms > router/122f3868-463a-45d5-8866-d679f1bf6c88 (0)
     Done creating missing vms > nats/5e3a1e14-0bc6-446e-91b3-d758e6abd9de (0) (00:02:25)
  Started creating missing vms > mysql_monitor/72e218a1-004e-4d8a-9df6-e670eeae8d17 (0)
     Done creating missing vms > uaa/e311151b-5586-4bf0-af09-16f2cffd5103 (0) (00:02:29)
  Started creating missing vms > clock_global/2da3b484-6170-429e-af41-6a975c7e9e3c (0)
   Failed creating missing vms > router/122f3868-463a-45d5-8866-d679f1bf6c88 (0): CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<NoMethodError: undefined method `[]' for nil:NilClass>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:712:in `get_load_balancer'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:691:in `get_load_balancer_by_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:183:in `get_load_balancer'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:191:in `create_network_interfaces'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:28:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:113:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:106:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method (00:00:07)
     Done creating missing vms > nfs_server/429c9792-9a5b-401a-89ec-b1a79e918e60 (0) (00:02:34)
     Done creating missing vms > etcd_server/0c5f56ae-3fb6-4114-9cd4-dd5a148b02ee (0) (00:02:36)
     Done creating missing vms > mysql/3c628b13-8269-482a-a27a-2777026acc77 (0) (00:02:38)
     Done creating missing vms > consul_server/fcae467f-7c97-498c-84f1-c981d28ab094 (0) (00:02:41)
     Done creating missing vms > cloud_controller/b8f1a4ad-b501-4c2c-8f88-321712ec0f30 (0) (00:02:47)
     Done creating missing vms > etcd_tls_server/6d9d7a50-5069-4098-87df-0f63d894c848 (0) (00:02:48)
     Done creating missing vms > ha_proxy/c177861b-893f-487f-9eae-befc913f824f (0) (00:02:51)
     Done creating missing vms > mysql_monitor/72e218a1-004e-4d8a-9df6-e670eeae8d17 (0) (00:02:11)
     Done creating missing vms > clock_global/2da3b484-6170-429e-af41-6a975c7e9e3c (0) (00:02:15)

Error 100: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<NoMethodError: undefined method `[]' for nil:NilClass>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:712:in `get_load_balancer'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:691:in `get_load_balancer_by_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:183:in `get_load_balancer'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:191:in `create_network_interfaces'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:28:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:113:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:106:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-1.3262.4.0/lib/bosh/cpi/cli.rb:70:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:35:in `<main>'' in 'create_vm' CPI method

Task 835 error

For a more detailed error report, run: bosh task 835 --debug
===== 2017-03-30 02:20:17 UTC Finished "bundle exec bosh -n deploy"; Duration: 311s; Exit Status: 1
{"type": "step_finished", "id": "bosh.deploying.cf-da60b13143ed35df7487"}
Exited with 1.
could not execute "apply-changes": installation was unsuccessful

**Comment by subhashgunda** [comment]
pl help me on this..i can't get around this issue.

**Comment by dpb587-pivotal** [comment]
Hi - couple things...

1. It sounds like you may be trying to configure a load balancer for your compilation VMs - I don't think that's intentional.
1. You may also want to double check your load balancer configuration in general to ensure you're using the correct properties. Also make sure the load balancers already exist.
1. It would be helpful if you could include the azure and director version number in your report since code changes over time.
1. You might find the the [bosh-azure-cpi-release Issues](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues) helpful for more context or to see if anyone else has experienced this issue.

**Comment by subhashgunda** [comment]
I ended up by removing the quotes in elb_names of router which was a point of entry (not haproxy) 
 "router": {"instance_type": {"id": "automatic"},"instances": 1,"internet_connected": false,"elb_names": [""]},

I am not sure how i missed that.  removing quotes fixed the issue.

thanks for you reply though. appreciate it.

**Comment by dpb587-pivotal** [comment]
Closing - thanks for following up with how you resolved.
