### ISSUE TITLE
Metrics about resurrector activity

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh#1646]
Does BOSH emit metrics about its resurrection activity? If so, how can they be consumed / where are they documented?

The idea is, that by emitting a counter every time a VM is resurrected, one could set up alarms that only trigger when a certain threshold of resurrection is reached. This should help to separate true random hardware failures (which BOSH is supposed to take care of) from systematic issues (which BOSH should not hide from the operator).

**Comment by cppforlife** [comment]
we now have a rich events feed (bosh events) that has fairly detailed info about activity.

bosh.io/docs/events

you should be able to pull out necessary info out of this feed based ok user/object type/etc

**Comment by cppforlife** [comment]
> It requires an additional failsafe process somewhere (which is not a trivial thing to solve).

just colocate it with the director. i've been slowly working on https://github.com/cppforlife/bosh-stats-release to export some of stats for general director info. 

not sure what you mean by "failsafe".

> It adds more load on the director.

not too much additional load from my tests and even so can just bump director vm size.

**Comment by petergtz** [comment]
> just colocate it with the director. i've been slowly working on https://github.com/cppforlife/bosh-stats-release to export some of stats for general director info.

> not sure what you mean by "failsafe".

Well, if you colocate it with the director, what if the director VM dies? You could argue that you don't need metrics anymore. But let's assume you have a director HA setup, where your elastic IP automatically points to a different director VM once the first one dies, and you have the DB and blobstore as external. That way your director survives, but the metrics job doesn't. If the same metrics job runs on all stand-in directors than you'd get metrics multiple times and add up to wrong values.

It's a solvable problem, sure, but that's what I meant with "it's not trivial". Unless I'm missing something here.

**Comment by cppforlife** [comment]
> If the same metrics job runs on all stand-in directors than you'd get metrics multiple times and add up to wrong values.

that would be the case if you have HM produce metrics. all three HMs would be producing metrics then.

**Comment by petergtz** [comment]
> that would be the case if you have HM produce metrics. all three HMs would be producing metrics then.

True. Okay, bottom line is there is no out of the box solution for resurrection metrics yet. Polling would be a possible solution.

Since that answers my original question, feel free to close.

**Comment by jfmyers9** [comment]
Going to close this due to inactivity. Feel free to reopen / create a new issue if you have further questions.
