### ISSUE TITLE
[feature] Auto-scaling of instances

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry/bosh#1652]
Auto-scaling of bosh deployed instances in AWS or Azure.

## Scaling up
Based on resource load.
Our use case is to scale concourse workers based on load. We come across this often.

**Benefits:** High-availability, Reliability

## Scale down
Based on low activity periods (dynamic or on-schedule)
Dynamic: If instances stay idle for a long period
On-schedule: during weekends or at night.

**Benefits:** Saving costs

## Suggestion
Use whatever the cloud provider offers: **auto-scaling groups** in `AWS`, **availability sets** in `Azure` and the equivalent for others.

**Comment by cppforlife** [comment]
@vito btw is there functionality in concourse to keep on retrying work until at least one worker is available?

**Comment by dmlemos** [comment]
In fact today we hit DB limits. Although state servers it is a totally different story, there is plenty of use cases out there :)

**Comment by dmlemos** [comment]
I have updated the comments with benefits and suggest to use the cloud provider *offer*.

**Comment by vito** [comment]
@cppforlife Not at the moment, no.

**Comment by smahesh3** [comment]
Any update on this? Any plans to include this feature in your roadmap?

**Comment by anoop2811** [comment]
Would be great feature to add to scale out deployments and keep the operators happy. Any updates or plans of doing this feature?

**Comment by gavinbunney** [comment]
This would be a huge help with CI systems as well, so we could scale out Concourse as needed for larger automation suites and scale it back down automatically.

For operating K8S, being able to use the ClusterAutoscaler would be great as well: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md

Perhaps BOSH could manage/use an AutoscalingGroup (in AWS' case) rather than individual instances?

**Comment by bloeys** [comment]
We are also interested in this for automatically scaling our CF deployment. Something similar to the app autoscaler would be amazing for deployments.

Any news so far? If not, maybe pointers to what bosh APIs might be useful to build such a thing?
