### ISSUE TITLE
Unable to run tcpdump on bosh-lite

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1654]
Hi Boshers,

Hit a weird issue today when trying to use `tcpdump` on a bosh-lite running warden stemcell version 3363.15. When trying to run `tcpdump` I get:

```
tcpdump: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: Permission denied
```

After googling around, there are several docker threads around the same error when running `tcpdump` in docker containers, makes sense as I'm using the runc bosh-lite. The [accepted hack](https://github.com/docker/docker/issues/14140#issuecomment-114898486) that got the command working was:

```
mv /usr/sbin/tcpdump /usr/bin/tcpdump
ln -s /usr/bin/tcpdump /usr/sbin/tcpdump
```

I didn't dig into what was special about `sbin` vs `bin`, but this does avoid the error. Figured I'd open an issue in case others hit this problem or maybe y'all could add an actual fix in the stemcell.

**Comment by dpb587-pivotal** [comment]
Nice find and thanks for reporting it - for what it's worth, the symlink should be unnecessary. At least this works for me on 3363.15, but curious if you saw different...

    $ sudo mv /usr/{s,}bin/tcpdump
    $ sudo tcpdump -i wd5ka5icqaed-1

**Comment by ljfranklin** [comment]
Yeah, symlink is not strictly necessary. I assumed they were just being defensive around people using absolute paths and expecting tcpdump to be at its canonical path.

**Comment by dpb587-pivotal** [comment]
Turns out this is a long-standing issue - https://github.com/cloudfoundry/bosh-lite/issues/256

**Comment by jfmyers9** [comment]
Just tested this on the new xenial stemcells on bosh-lite and it appears to work!

```
bpm/b8d1c785-7915-41e9-aff7-6dff4560952b:~# tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wktiahlqvvh0-1, link-type EN10MB (Ethernet), capture size 262144 bytes
02:58:05.116772 IP b8d1c785-7915-41e9-aff7-6dff4560952b.bpm.bpm.bpm.bosh.ssh > 192.168.50.1.46434: Flags [P.], seq 2630760462:2630760658, ack 2799067615, win 293, options [nop,nop,TS val 1968243993 ecr 3513736840], length 196
02:58:05.117411 IP 192.168.50.1.46434 > b8d1c785-7915-41e9-aff7-6dff4560952b.bpm.bpm.bpm.bosh.ssh: Flags [.], ack 196, win 1444, options [nop,nop,TS val 3513737085 ecr 1968243993], length 0
```

Going to close this issue as we likely will not be addressing this on trusty stemcells due to the upcoming EOL.
