### ISSUE TITLE
Remove `provides.type` from spec

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1657]
In Links we have a two-part type system. 

First, a spec has an explicit `provides.type: servicebroker` declaration that is detached from "what is a 'servicebroker'?". Second, a spec will publish a list of `provides.properties`.

A consumer of a spec can only link based on the first part of the type system - it needs to hard-code that it will consume `type: servicebroker`. But really, a consumer never cares about the name of the provided link. What it cares about is that the provided link provides a set of required properties (say `port`, `username`, `password`). And it is the deployment manifest that takes responsibility for actually linking two things that make sense together.

I'd like to propose that we ditch `type: servicebroker` as unhelpful in the typing system; and only negative if there is not a globally de facto agreement on what the types are.

My evidence is https://github.com/cloudfoundry/cf-mysql-release/issues/153 - an attempt to converse about converging on a defacto `type: servicebroker` type label; but participants have died off.

I don't feel that `provides.type: xyz` provides extra value. Instead, `consumes.properties` would be more appropriate - a consumer declares "I need to link to something with `port`, `username`, `password`, and/or some optional properties).

**Comment by cppforlife** [comment]
@drnic `type` is necessary for implicit linking. additionally it's meant to encourage necessary conversations and some type of consistency between releases.

> an attempt to converse about converging on a defacto type: servicebroker type label; but participants have died off.

that's unfortunate. might be an indicator that it's not something that people are ready to commit to yet. from that discussion, i think this is extremely valuable:

> I would like to propose a convention for how service broker jobs provide/describe their link...

**Comment by jfmyers9** [comment]
Going to close and reopen this issue to generate a tracker story.
