### ISSUE TITLE
bosh.io aws stemcell link silently redirects to light stemcell 

### ISSUE THREAD

**Issue by tyyko** [cloudfoundry/bosh#1659]
http://bosh.io/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent Contains the link to the latest stemcells and states you can download the stemcell tarball with the command

```
wget --content-disposition https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3363.20
```
But with that link you get the light stemcell

I think it should be more explicit that the link gives you the *light* stemcell, and if you use it in a bosh manifest, you should use the *sha1 of the light one*.

**Comment by cppforlife** [comment]
you can throw in `&light=false` to get a download for a full stemcell.

**Comment by dpb587-pivotal** [comment]
Ooh, that's good to know. I didn't realize that.
