### ISSUE TITLE
When resurrector fails to attach persistent disk, everything is considered fine afterwards

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1660]
## Problem Description
* a VM failed
* resurrector kicked in
* attach_disk failed, due to a timeout in the infrastructure

## Expected
* Health Monitor schedules a new resurrection

## Actual
* agent sends heartbeats from the new VM
* BOSH DB seems to have this agent ID already in the DB for the instance?
* no further resurrection happens, everything is considered fine afterwards

Don't know if anything changed since the investigation in https://www.pivotaltracker.com/story/show/79810782 but it seems to be still the same behavior.

**Comment by jfmyers9** [comment]
Closing and reopening to generate a github story.
