### ISSUE TITLE
BOSH release should not include Postgres version that is no longer supported

### ISSUE THREAD

**Issue by pivotal-danjahner** [cloudfoundry/bosh#1662]
The default<sup>1</sup> version of postgres from the BOSH release is version 9.0.23. This release was last updated on 2015-10-08 and has been at end of life since Sept 2015. We should not include end-of-life software in our releases. 

<sup>1</sup> I assert that this is the default version because including the release by name "postgres" will install this version. A user has to know to change the release to "postgres-9.4" to install a supported version.

**Comment by cppforlife** [comment]
we are planning to remove `postgres` job in the next bosh release.

**Comment by pivotal-danjahner** [comment]
Is that plan going forward to require an explicit job name that includes a version, e.g. postgres-9.4, postgres-9.6, etc.?

**Comment by cppforlife** [comment]
@pivotal-danjahner probably.

**Comment by iredelmeier** [comment]
Now that 04ab60854 has gone through, can the postgres release also be removed?

**Comment by dpb587-pivotal** [comment]
For what it's worth, the [upgrader](https://github.com/cloudfoundry/bosh/blob/9b177760976f943a565ef4c1d8f8264075a85472/jobs/postgres-9.4/templates/postgres_db_upgrade.sh.erb) from <9.4 to 9.4 utilizes the older 9.0 package. Might take longer to fully remove the older package.

**Comment by dpb587-pivotal** [comment]
Closing - since [v262](https://github.com/cloudfoundry/bosh/releases/v262)+ the `postgres` job was removed in favor of `postgres-9.4`. We continue to package the older version, but only for the purposes of migrating the database of older director databases.
