### ISSUE TITLE
[feature] Snapshot cleaning

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry/bosh#1664]
Option to do regular cleaning of non-orphaned snapshots. After a while it gets pricey.
Similar to `disks.cleanup_schedule`

**Comment by cppforlife** [comment]
@voelzmo do you all run into this problem?

**Comment by voelzmo** [comment]
Didn't hear any complaints from operations so far. Need to check back and see how many snapshots we currently have and if that is an issue.

**Comment by dmlemos** [comment]
I wonder if it is possible to check the status for the bosh director snapshots. Those are also unmaintainable.

**Comment by dpb587** [comment]
A couple years ago I couldn't find a good solution for this and ended up writing an external, scheduled task to regularly cleanup with the needed retention periods. I agree it would be nice if something around snapshot cleanup was built-in.

**Comment by jfmyers9** [comment]
Closing and reopening this to create a github story.
