### ISSUE TITLE
Issue while running bosh deploy command

### ISSUE THREAD

**Issue by dipneeta** [cloudfoundry/bosh#1666]
While deploying cloud foundry receiving error 

Started compiling packages
  Started compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc
  Started compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > rootfs_cflinuxfs2/50f50dbf95a40f0d0091f7d48616030abf7e52f9
  Started compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2
  Started compiling packages > nginx/31a4f3d6f880b63a097af7a462339410ca0156bc
   Failed compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c: Timed out pinging to 30522044-c688-4aec-b870-972729e01994 after 600 seconds (00:11:25)
   Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: Timed out pinging to 88c1f7f7-91cf-4bc9-af52-d6e7b5153d38 after 600 seconds (00:11:51)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: Timed out pinging to 2f866e45-4cd2-4800-9fe1-540e8d77495b after 600 seconds (00:11:55)
   Failed compiling packages > rootfs_cflinuxfs2/50f50dbf95a40f0d0091f7d48616030abf7e52f9: Timed out pinging to d84a5935-38c6-4287-820e-956b2489c103 after 600 seconds (00:11:56)
   Failed compiling packages > nginx/31a4f3d6f880b63a097af7a462339410ca0156bc: Timed out pinging to 69f98103-9260-4b2f-947c-6b2ef35a97bb after 600 seconds (00:11:57)
   Failed compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc: Timed out pinging to a4c9c875-82fb-420f-a3d2-1ff3714ec10d after 600 seconds (00:12:01)

Error 450002: Timed out pinging to 30522044-c688-4aec-b870-972729e01994 after 600 seconds

I have uploaded my configuration file. Pls help
[bosh.txt](https://github.com/cloudfoundry/bosh/files/972571/bosh.txt)
[cf-stub.txt](https://github.com/cloudfoundry/bosh/files/972572/cf-stub.txt)
[cf-deployment.txt](https://github.com/cloudfoundry/bosh/files/972573/cf-deployment.txt)

**Comment by bxlkm** [comment]
I am also the same problem, the current I set the configuration works is one, openstack VMS has been successful.
04:36:31 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
04:36:37 | Preparing deployment: Preparing deployment (00:00:52)
04:46:11 | Preparing package compilation: Finding packages to compile (00:00:19)
04:46:30 | Compiling packages: cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc (00:15:10)
            L Error: Timed out pinging to 78b5b3e9-ee5d-40cc-b117-9e7ee18a6a6d after 600 seconds

05:01:41 | Error: Timed out pinging to 78b5b3e9-ee5d-40cc-b117-9e7ee18a6a6d after 600 seconds

logs：
ERROR -- DirectorJobRunner: Worker thread raised exception: Timed out pinging to bf8f9250-2cfd-4b09-8b66-4e127182242b after 600 seconds - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:211:in `rescue in wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:217:in `wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:66:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 bosh/src/bosh-director/lib/bosh/director/agent_client.rb--source code:
 line 198:   def wait_until_ready(deadline = 600) ...
If the VMS boot time is longer, is this parameter set externally？

**Comment by dpb587-pivotal** [comment]
These "timed out pinging" errors are typically due to misconfiguration of
the IaaS environment. Take a look at the suggestions documented here for a
few things to double check and how to find more details:
http://bosh.io/docs/tips#unreachable-agent.
-- 
Danny Berger
