### ISSUE TITLE
how can I use putty to login to bosh director?

### ISSUE THREAD

**Issue by jacko1118** [cloudfoundry/bosh#1669]
Dear all,

could you pls tell me how to login to bosh director? I use putty and input BOSH director's ip, enter admin/admin, but cannot logins.
I want to have a look at the content's in director, pls help.

Thanks.
regards.
Jacko

login as: admin
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
admin@10.1.1.149's password:
Access denied
admin@10.1.1.149's password:
Access denied
admin@10.1.1.149's password:

login as: root
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
root@10.1.1.149's password:
Access denied
root@10.1.1.149's password:

**Comment by dpb587-pivotal** [comment]
Note that the only shared/potentially usable login on the stemcell is `vcap` (but it depends on which IaaS you're using for whether or not you can SSH into it directly). With AWS you can SSH with the original SSH Key used to create the VM, with Google you could add a key for the `vcap` user, and with vSphere there's no key used and the `vcap` password is randomly set; but the recommended way is to add a dedicated local user if you need it for testing and manual intervention (see [`jumpbox-user.yml`](https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml) from the bosh-deployment configurations for an example).

For what it's worth, to view details about a specific failed task, there's also the `--debug` option that you can pass to `bosh task`. For example, `bosh task --debug 5`.

**Comment by jacko1118** [comment]
dear dpb587-pivotal,

thanks so much for your reply, I go thru my bosh.yml file and use the default password to login to director with user vcap.

The main purpose to login to director is to see if it can access the new created VMs during running command bosh deploy.
I also have a look at the  bosh task --debug 5  result but cannot find any valuable information.
I will keep you update with my finding.
Thanks so much for your help!!
regards
Jacko

resource_pools:
- name: test_pool
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3363.15
    sha1: d5571cd8e13d1daca99dc821e4fb751f4cdd42f8
  cloud_properties:
    cpu: 2
    ram: 8_192
    disk: 80_000
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"

vcap@10.1.1.159's password:
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Last failed login: Fri May  5 01:09:33 UTC 2017 from 10.1.1.104 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Fri May  5 01:09:41 2017 from 10.1.1.104
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

/:~$
/:~$
/:~$
/:~$ df -h
