### ISSUE TITLE
Deploying Cloud Foundry  error, time out pinging error.

### ISSUE THREAD

**Issue by jacko1118** [cloudfoundry/bosh#1670]
Dear all,

could you pls help with below issue?

I dont know how to fix it.

Thanks.

Regards.
Jacko

Please review all changes carefully

Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 5
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > rootfs_cflinuxfs2/db8b8575d6f9fc57d470e1a8f0172f4f39e84d2b
  Started compiling packages > nginx/31a4f3d6f880b63a097af7a462339410ca0156bc
  Started compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2
  Started compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d
  Started compiling packages > libmariadb/90d7836132e02bb570d91f08c9e116c394888d75
   Failed compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d: Timed out pinging to 4876fd6f-7e93-4cb8-8068-25185945ad2e after 600 seconds (00:11:04)
   Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: Timed out pinging to dd24dc48-fdd9-445c-80c5-f0ee9d7c98eb after 600 seconds (00:11:05)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: Timed out pinging to ca7e8a34-bdc6-4eb5-bf64-da56c27abd33 after 600 seconds (00:11:26)
   Failed compiling packages > rootfs_cflinuxfs2/db8b8575d6f9fc57d470e1a8f0172f4f39e84d2b: Timed out pinging to d5477b08-6bce-4f98-b341-7fff579fd90a after 600 seconds (00:11:30)
   Failed compiling packages > libmariadb/90d7836132e02bb570d91f08c9e116c394888d75: Timed out pinging to 25cf5700-716d-4f64-b95a-44cf16439d53 after 600 seconds (00:11:30)
   Failed compiling packages > nginx/31a4f3d6f880b63a097af7a462339410ca0156bc: Timed out pinging to 660ae8c5-64d0-4a04-82e2-05a2845b04fe after 600 seconds (00:12:49)

**Comment by dpb587-pivotal** [comment]
Hi - this is usually due to firewall misconfiguration. Take a look at https://bosh.io/docs/tips#unreachable-agent for some specific suggestions on how to investigate this issue.

**Comment by dpb587-pivotal** [comment]
Related to your other comment, if you're expecting your VMs to be created using IaaS-managed network IPs, you should make sure you're using a [dynamic network](http://bosh.io/docs/networks.html#dynamic).

**Comment by jacko1118** [comment]
Dear dpb587,
during the temperary Vm creation, I saw the VM's ip from vsphere console is 10.1.1.1 to 10.1.1.6.
but the hostname /dns name of these vms are unreachable, error is the log we saw in my post.
So the problem is the director cannot access the hostname of the vm , even they are in the same VLAN.
Pls advise.
thanks.
regards
jacko

**Comment by jacko1118** [comment]
by the way , you mentioned dynamic network, where shall I config this? during create bosh director or create CF?

Thanks.

**Comment by jacko1118** [comment]
Hi,
I would like to ssh to the temporary VM duing deployment and have a look at the log, but I cannot access it via director;

/:~# ssh 10.1.1.2
The authenticity of host '10.1.1.2 (10.1.1.2)' can't be established.
ECDSA key fingerprint is 69:6a:e7:be:f5:26:dd:ed:d2:3f:8b:da:5e:5b:d8:02.
Are you sure you want to continue connecting (yes/no)? no
Host key verification failed.
/:~# ssh 10.1.1.2
The authenticity of host '10.1.1.2 (10.1.1.2)' can't be established.
ECDSA key fingerprint is 69:6a:e7:be:f5:26:dd:ed:d2:3f:8b:da:5e:5b:d8:02.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.1.1.2' (ECDSA) to the list of known hosts.
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
root@10.1.1.2's password:


pls advise.

thanks.

**Comment by jacko1118** [comment]
It’s recommended to start a deploy again and SSH into one of the VMs and look at the Agent logs while the Director waits for VMs to become accessible. See director.debug.keep_unreachable_vms property to let Director know to leave unreachable VMs for easier debugging.

could you tell me how to access the VM via SSH?
