### ISSUE TITLE
Job Template documentation updates

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1673]
Can we get the feature for calling `p("my-property", default-value)` added to the docs for job templates + links? It's a super awesome feature, and I had no idea it existed.

https://github.com/cloudfoundry/bosh/blob/master/src/bosh-template/lib/bosh/template/evaluation_context.rb#L65-L70

http://bosh.io/docs/reference/jobs.html
https://bosh.io/docs/links-properties.html

**Comment by dpb587** [comment]
I've wondered if this functionality should be removed. Personally I avoid it because it introduces a third place where settings are coming from (in addition to manifest and spec defaults). I prefer the spec because it is more consolidated and static, so it can be rendered in docs (as opposed to having to parse or grok ERB).

**Comment by geofffranks** [comment]
In my case it was `my_link.p("property-that-links-might-provide", p("property-from-spec-to-default-to")`, to be able to work around when some things providing a link  provide a property, and some don't.

**Comment by cppforlife** [comment]
@geofffranks 
> my_link.p("property-that-links-might-provide", p("property-from-spec-to-default-to")

how come is that case? is it for transition period?

**Comment by drnic** [comment]
@cppforlife there are many cases where you're consuming a link from an arbitrary other bosh release (say sql job) and you want to consume properties - but there isn't a requirement for providers to follow any pattern/style, so you might need to support a range of possible properties from many known or future provider jobs.

At this point I'd like to also ask that we get rid of "type: some-restrictive-label" from links. They are devaluing links from allowing reuse amongst independently developed releases.

**Comment by jfmyers9** [comment]
This seems to be documented by following the [template accessor](https://bosh.io/docs/jobs/#properties) link on the [link properties documentation](https://bosh.io/docs/links-properties/). Going to close this issue. Feel free to reopen if you have further questions.
