### ISSUE TITLE
Bosh-deployment AWS

### ISSUE THREAD

**Issue by venkatramana1** [cloudfoundry/bosh#1674]
Started validating
  Downloading release 'bosh'... Finished (00:00:09)
  Validating release 'bosh'... Finished (00:00:03)
  Downloading release 'bosh-aws-cpi'... Finished (00:00:01)
  Validating release 'bosh-aws-cpi'... Finished (00:00:05)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Finished (00:00:01)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:23)

Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Failed (00:00:05)
Failed installing CPI (00:00:05)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Installing yaml
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... no
checking for cc... no
checking for cl.exe... no
', stderr: '+ set -e -x
++ PATH=/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin
++ openssl version
+ openssl_version='OpenSSL 1.0.1e-fips 11 Feb 2013'
++ cut -f2 '-d '
++ cut -f1 -d.
++ echo OpenSSL 1.0.1e-fips 11 Feb 2013
+ openssl_major_version=1
+ '[' 1 == 0 ']'
+ echo 'Installing yaml'
+ tar xzf ruby_aws_cpi/yaml-0.1.5.tar.gz
+ pushd yaml-0.1.5
+ CFLAGS=-fPIC
+ ./configure --prefix=/root/.bosh/installations/9e065bd9-474c-4fb0-70ea-c5049d42ff02/packages/ruby_aws_cpi --disable-shared
configure: error: in `/root/.bosh/installations/9e065bd9-474c-4fb0-70ea-c5049d42ff02/tmp/bosh-release-pkg138648697/yaml-0.1.5':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
':
          exit status 1

Exit code 1

Please help me with this issue

**Comment by cppforlife** [comment]
See http://bosh.io/docs/cli-env-deps.html for additional cli dependencies.

**Comment by Deekshit51** [comment]
I am having the same issue can you please check?
