### ISSUE TITLE
set_disk_metadata should set instance_group instead of job

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh#1676]
since job is only now used externally for release jobs. we'll eventually change all references in the code base to instance group.

```
metadata['job'] = disk.instance.job
```

https://github.com/cloudfoundry/bosh/blob/968d9caacbee07b13c96414c747ec1fed07c063a/src/bosh-director/lib/bosh/director/metadata_updater.rb#L37

**Comment by voelzmo** [comment]
sure, we can do that. For now, I wanted to keep it in sync with the tags on VMs. We probably should  change both occurrences, right?

**Comment by dpb587-pivotal** [comment]
PR #1739
