### ISSUE TITLE
how can I use putty to login to the VM which created during running command bosh deploy

### ISSUE THREAD

**Issue by jacko1118** [cloudfoundry/bosh#1678]
Dear all,

due to I got the timeout error during running command bosh deploy, so I would like to check the log in the new create vms which based on the guide:

Agent logs

Agent logs contain configuration and runtime information from the Agent running on a VM. Review these logs if the Director sees VM as unresponsive or the Director fails to contact it during its creation.

The Agent stores logs in /var/vcap/bosh/log/ and outputs most recent content to /var/vcap/bosh/log/current.

But unfortunnly I cannot use bosh ssh to login to the vm, even I know the ip of the server.

also I don't know the root password for this new create vm.
pls help.
thanks.
Regards
Jacko

**Comment by jacko1118** [comment]
Check the Agent log on the VM that timed out for a “handshake” connection between the BOSH Director and the Agent

1.Use your IaaS virtualization console to open a terminal window on the VM that timed out and log in as root.

do you know what is the root password?

Thanks.

Regards
Jacko

**Comment by dpb587-pivotal** [comment]
The default account is username  `vcap` and password `c1oudc0w`, but it depends on the IaaS you're using. For vSphere, you'd use that login; for AWS, you'd use the username `vcap` and SSH key you created the VM with; for GCP, you'd add your SSH key for the `vcap` user.

**Comment by dpb587-pivotal** [comment]
But note, once the VM comes up and communicates with director, it may change the default `c1oudc0w` password to a random one for improved security.

**Comment by jacko1118** [comment]
Last login: Thu May 11 17:16:35 2017 from 10.1.1.104
root@ubuntu6:~# bosh target 10.1.1.159
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Target set to 'my-bosh'
root@ubuntu6:~# bosh vms
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'
Deployment 'sodec-vsphere-demo'

Director task 14

Task 14 done

+-------------------------------------------------------------------------------------------+--------------------+-----+---------+-----+
| VM                                                                                        | State              | AZ  | VM Type | IPs |
+-------------------------------------------------------------------------------------------+--------------------+-----+---------+-----+
| compilation-04c149c3-78ea-4d8d-ae2b-0294e5480a71/0 (98b36b67-cc0c-439b-aef6-1fa55ec769de) | unresponsive agent | n/a |         |     |
| compilation-1bca6bc7-8bd4-4d57-9f1b-d75b6558f14c/0 (838ad2a5-b624-4793-bb92-f4e6511f340f) | unresponsive agent | n/a |         |     |
| compilation-3c94e779-4044-4190-bc18-65d637134e32/0 (e0f2fe95-d1c5-4217-9d78-63296c2a0d87) | unresponsive agent | n/a |         |     |
| compilation-7201bbfb-1884-466e-a06b-8ed9d67b7fd6/0 (00d2b54b-c8e8-4694-9bab-b408a93c5658) | unresponsive agent | n/a |         |     |
| compilation-b781632f-7fb9-4d02-bb80-dda2be0b0e78/0 (ccb6e3dc-a518-43b6-859d-9fdd10c1ef89) | unresponsive agent | n/a |         |     |
| compilation-c88c3c53-c691-40d4-9303-8e09e409c2c4/0 (b33ec5d4-00fa-4312-8cc2-af57a95d9213) | unresponsive agent | n/a |         |     |
+-------------------------------------------------------------------------------------------+--------------------+-----+---------+-----+

VMs total: 6

I still get the sameerror.

**Comment by dpb587-pivotal** [comment]
This is typically due to a misconfiguration on your security groups or director configuration - take a look at the suggestions in https://bosh.io/docs/tips.html#unreachable-agent for tracking down more information. For vsphere, you may want to deploy your director with a local user so you can connect - see [jumpbox-user.yml](https://github.com/cloudfoundry/bosh-deployment/blob/01bf99ccda147f7925ef935010dd9124b9f90cc1/jumpbox-user.yml) for an example. For the compilation VMs, you should be able to use the user/password mentioned earlier.
