### ISSUE TITLE
 Compiling CF packages error issue

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/bosh#1683]
04:55:46 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
04:55:51 | Preparing deployment: Preparing deployment (00:00:52)
05:02:08 | Preparing package compilation: Finding packages to compile (00:00:06)
05:02:14 | Compiling packages: cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc (00:14:32)
            L Error: Action Failed get_task: Task 7099f87d-d782-4add-6594-4e8f92588819 result: Updating certificates with retries

05:16:47 | Error: Action Failed get_task: Task 7099f87d-d782-4add-6594-4e8f92588819 result: Updating certificates with retries

Started  Thu May 11 04:55:46 UTC 2017
Finished Thu May 11 05:16:47 UTC 2017
Duration 00:21:01

Task 4 error

Capturing task '4' output:
  Expected task '4' to succeed but was state is 'error'

Exit code 1
////////////////////////////////////////////////////////////////////////

**Comment by ivandavidov** [comment]
Hi @bxlkm,

This looks very much like a performance issue. I had [similar problem](https://github.com/cloudfoundry/bosh-lite/issues/429) on my laptop which is an almost entry level machine (8GB RAM, Pentium N3700 CPU).

What are the specs on the machine where you do your deployment?

**Comment by bxlkm** [comment]
I adjusted the machine to 8 core 16G memory does not exist this problem, I deployed above the openstack, but the following error occurred:

[2017-05-11 08:05:02 [task:11] ERROR - DirectorJobRunner: out pinging 937620d4-b525-4808-b9a1-c53586d77256 after 600 seconds #30097] Timed (to)

/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:211:in `rescue in wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/agent_client.rb:217:in `wait_until_ready'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:66:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:144:in `create_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:185:in `instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/compilation_instance_pool.rb:16:in `with_reused_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:115:in `prepare_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:66:in `block in compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock_helper.rb:48:in `block in with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock.rb:53:in `lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/lock_helper.rb:48:in `with_compile_lock'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:59:in `compile_package'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:204:in `block (2 levels) in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:202:in `block in process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:198:in `process_task'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/deployment_plan/steps/package_compile_step.rb:162:in `block (4 levels) in compile_packages'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

**Comment by dpb587-pivotal** [comment]
The "timed out pinging" errors typically mean there's a misconfiguration of security groups or NATS credentials. Check out the tips given on https://bosh.io/docs/tips.html#unreachable-agent for a few other suggestions.

(and good suggestion, @ivandavidov - thanks!)
