### ISSUE TITLE
IP address reservation doesn't respect VMs that will be deleted

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1685]
## What's the situation?

It seems that IP address reservation during a `bosh deploy` doesn't mark IPs of already existing VMs as reserved when building the instance_plan. This is possibly an optimization, because the assumption was that VMs will always be deleted before new ones are created.

## Why is this an issue

This can lead to "IP Address in use" errors, when your `bosh deploy` also needs to spin up compilation VMs. Compiling happens even before VM deletion happens, so *if* you have your compilation VMs in the same network as your bosh-deployed VMs, BOSH will try to assign an IP of a VM that will be deleted only afterwards.

## Possible solutions

* Documenting that having compilation VMs and bosh-deployed VMs in the same network is not supported. Not sure if that's a good solution, given that our standard cloud-configs in bosh-deployment currently do this: https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/cloud-config.yml#L47
* Moving VM deletion above compilation. Not sure if that's good either, because this causes major troubles when compilation fails but you've already deleted your crap. Also increases downtime by the time it takes to compile
* Considering *all* currently taken IPs in IP reservation process. Not sure how nice this solution is, as potentially more IPs are required now in a network. (existing + new ones)

PS: If it matters, this happened on a non-cloud-config Deployment

What do you think?

**Comment by jraqula** [comment]
We have concluded that this issue only appears in pre-cloud-config deployments, and therefore doesn't require a fix as we expect general migration to cloud config manifests. 

This issue occurs particularly when compilation VMs are required for a deploy which at the same time expects to remove existing instances.

Possible workarounds for who is hitting the issue on their non-cloud-config deployments are:
- Move compilation VMs into a different network (as suggested by @voelzmo).
- Deploy in two steps, where the first one compiles any new packages without deleting existing instances, then remove old instances in separate step.
