### ISSUE TITLE
Manifest "strict" validation mode

### ISSUE THREAD

**Issue by avade** [cloudfoundry/bosh#1686]
#### Use case 

An operator mistypes an optional property or adds an unsupported property for a job and once deployed is expecting the system to have a certain behaviour. 

#### Todays solution

Today we can add logic into the templates to check for unexpected properties and throw an error. 

This is resulting in a lot of boilerplate code that gets written. 

#### Bonus points

Release authors should be able to write spec files for repeating structures. This is a major shortfall in spec files today.

**Comment by dpb587-pivotal** [comment]
Duplicate/semi-related to #1568

**Comment by mfine30** [comment]
Closing in favor of #1568
