### ISSUE TITLE
does Consul  is a mandatory component during CF deployment?

### ISSUE THREAD

**Issue by jacko1118** [cloudfoundry/bosh#1690]
Dear all,

I just follow the cf template from website:
http://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html

During the deployment, I just got error in the phase:
 Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started updating instance consul_z1
  Started updating instance consul_z1 > consul_z1/090de112-a0e4-4310-b63f-2e17f888c34b (0) (canary)
 Started updating instance consul_z1
  Started updating instance consul_z1 > consul_z1/090de112-a0e4-4310-b63f-2e17f. Failed: 'consul_z1/0 (090de112-a0e4-4310-b63f-2e17f888c34b)' is not running after update. Review logs for failed jobs: consul_agent, metron_agent (00:10:44)

Error 400007: 'consul_z1/0 (090de112-a0e4-4310-b63f-2e17f888c34b)' is not running after update. Review logs for failed jobs: consul_agent, metron_agent

Task 190 error

For a more detailed error report, run: bosh task 190 --debug

I am wondering there is something wrong with the cert generation but cannot confirm.
Can I just remove this part ?
Or how can I check the log for   consul ? I can ssh into the VM.

Thanks.
Regards
jacko

consul:
    encrypt_keys:
      - CONSUL_ENCRYPT_KEY
    ca_cert: CONSUL_CA_CERT
    server_cert: CONSUL_SERVER_CERT
    server_key: CONSUL_SERVER_KEY
    agent_cert: CONSUL_AGENT_CERT
    agent_key: CONSUL_AGENT_KEY
    
 See the Security Configuration for Consul topic.

**Comment by drnic** [comment]
Perhaps https://github.com/cloudfoundry/cf-release or https://github.com/cloudfoundry/cf-deployment projects are good ones to discuss consul-in-cf.
