### ISSUE TITLE
aws tagging problem with values of 'no'

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/bosh#1691]
We recently started using one of the new features of bosh that lets you add aws tags to your resources.  We have a tag with a value string of "no".  when we bosh deploy, that string is getting changed to the word "false".   We are on bosh release 261.4

To reproduce:

Add following to manifest:
tags:
  mytag: no

After deploy, you end up with a tag on the resources of:

mytag: false

**Comment by cppforlife** [comment]
@rwwohl this is an artifact of using YAML. In YAML no is a shorthand for `false`. Dont think there is a way to turn this off in a ruby YAML library.

**Comment by rwwohl** [comment]
Gotcha.  Yeah, that makes sense.  I did some googling, and turns out if I quote the word 'no' , then it does not convert and goes in there as intended.  Thanks for giving clarity on the issue.
