### ISSUE TITLE
Changing  IaaS resources out-of-band requires manually recreating VMs

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#1693]
Small usability gotcha. We had to recreate our GCP load balancers as we changed our DNS domain, but we keep the GCP Backend Service name the same. Since our Cloud Config didn't have to change, the next `bosh deploy` did not re-add the router VMs to the backend instance group. We had to run `bosh recreate` in order to have BOSH re-add the VMs to the backend instance group.

Seems like this is the expected current behavior for BOSH, but if a CPI v2 ever comes around a "check-vm" call that ensures the desired `cloud_properties` match the actual IaaS resources would be helpful.

**Comment by dmlemos** [comment]
I would like to see this as well. We changed load balancers in AWS and `bosh cck` didn't detect the changes.

**Comment by mfine30** [comment]
Closing and re-opening so we have a tracker story.
