### ISSUE TITLE
Broken unit test: bosh-director/.../deployments_controller_spec

### ISSUE THREAD

**Issue by Everlag** [cloudfoundry/bosh#1699]
[c3ca096feecc9e0b3e460dd8504e06c24d6233c5](https://github.com/cloudfoundry/bosh/commit/c3ca096feecc9e0b3e460dd8504e06c24d6233c5#diff-e9b3025052b630fc6c93ba2273241185R740) introduced what appears to be invalid syntax into a unit test. This is [in master](https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/spec/unit/api/controllers/deployments_controller_spec.rb#L741) and is causing my local unit tests to fail.

As an aside, this is the kind of thing that #1616 makes more difficult to confirm.

**Comment by cppforlife** [comment]
@Everlag i think you are running old ruby version. im pretty sure ruby 2+ introduces that syntax

```
irb(main):001:0> { 'instance_id': 123}
=> {:instance_id=>123}
```

> As an aside, this is the kind of thing that #1616 makes more difficult to confirm.

i could see us may be tagging git repo with such info.

**Comment by Everlag** [comment]
My bad, I misinterpreted the documentation. Sorry about that.
