### ISSUE TITLE
bosh deploy leads to CPI error 'Bosh::Clouds::CloudError'

### ISSUE THREAD

**Issue by magnetnoc** [cloudfoundry/bosh#1700]
```
$ bosh deploy
Acting as user 'admin' on deployment 'maxserverenv' on 'gcp-director'
Getting deployment properties from director...

Detecting deployment changes
----------------------------
stemcells:
- alias: bosh-warden-boshlite-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3421.4'
- alias: bosh-warden-boshlite-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: '3363.15'

releases:
- name: maxserverenv
  version: 0+dev.23
  version: 0+dev.25
Please review all changes carefully

Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 371
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > oraclejdk18/81d06de35e74e0d17771ade75581ecf442d98145
  Started compiling packages > maxserver/0cd697cbe10e8a2119a8cb741fd095928bc3b7a5
   Failed compiling packages > oraclejdk18/81d06de35e74e0d17771ade75581ecf442d98145: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '9eb29bda-ef6d-480f-b954-e4ec57d6b5b9': Updating container's agent env: Streaming in tar: error streaming in: exit status 1. Output: getpwnam: No such file or directory
' in 'create_vm' CPI method (00:00:17)
   Failed compiling packages > maxserver/0cd697cbe10e8a2119a8cb741fd095928bc3b7a5: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID 'e9268c74-7fe7-4ec6-92f9-f70b126889e9': Updating container's agent env: Streaming in tar: error streaming in: exit status 1. Output: getpwnam: No such file or directory
' in 'create_vm' CPI method (00:00:18)
   Failed compiling packages (00:00:18)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '9eb29bda-ef6d-480f-b954-e4ec57d6b5b9': Updating container's agent env: Streaming in tar: error streaming in: exit status 1. Output: getpwnam: No such file or directory
' in 'create_vm' CPI method

Task 371 error
```

**Comment by dpb587-pivotal** [comment]
A similar issue was brought up on the [mailing list](https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/thread/F33RU56CMZUB7LFHIYXYG66NLUG72P4N/) a while ago. You may want to try re-downloading the stemcell (and verify the sha1 from bosh.io to ensure it wasn't corrupted during transfer), and trying again.

**Comment by magnetnoc** [comment]
Thank you for your response.

I re-did the upload command like this:

bosh upload-stemcell https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.6

So that it would be retrieved directly, so there would be no download issues (on my side anyway)

same error occurs ...

**Comment by dpb587-pivotal** [comment]
Your deployment manifests suggests your `gcp-director` is a bosh-lite VM. If that's the case, you should be uploading the warden stemcells (it looks like you're currently uploading stemcells meant for AWS).

    bosh upload-stemcell \
      --sha1= 54579945657c9be309523d6b93bc90d7c443956e \
      https://s3.amazonaws.com/bosh-core-stemcells/warden/bosh-stemcell-3421.6-warden-boshlite-ubuntu-trusty-go_agent.tgz

I'd also encourage you to use sha1 verification, even if it's happening directly.

**Comment by magnetnoc** [comment]
Ok I think you may have hit on the primary issue.  I am trying to install the Cloud Foundry system onto AWS, and I am not making it past this step - I'm not sure how to fix the issue you mentioned above, but I am definitely trying to deploy on AWS.  I have been following the docs at https://docs.cloudfoundry.org/deploying/aws/deploy-aws.html but after a few tries I am unable to progress, so any help would be appreciated.

**Comment by dpb587-pivotal** [comment]
Looks like you might be combining a few different documentation instructions given the director name, listed stemcells, and AWS environment. If you're new to BOSH+CF, you may want to get started with a newer tool, [cf-deployment](https://github.com/cloudfoundry/cf-deployment) which can more easily generate your Cloud Foundry deployment manifest.

To continue with the docs from the docs site, I'd recommend revisiting the [Customizing the Cloud Foundry Deployment Manifest for AWS](https://docs.cloudfoundry.org/deploying/aws/cf-stub.html) to make sure you're using a valid manifest.

It kind of looks like you're trying to deploy something other than CF (which is perfectly fine! just want to make sure I'm giving you the correct pointers). Whatever manifest you're using in the snippet above, it looks like it's using the [newer style](http://bosh.io/docs/manifest-v2.html) manifest which is definitely going to look different than the manifest from the docs.cloudfoundry.org site right now (but possibly similar to other sites/docs using the newer manifest style). Just good to keep in mind there are two different manifest styles as you refer to snippets from various sites.
