### ISSUE TITLE
BOSH : Achieving zero downtime (eg: OS upgrades) using Canary in real world 

### ISSUE THREAD

**Issue by jaikanthm** [cloudfoundry/bosh#1701]
Canaries is a very useful feature that can really stop a big mess. When using Bosh in conjunction with vsphere (IAAS), I had a question on canary approach. If for example I deploy a mysql (no of instances =1 ) and canary parameter set as "1". Can a failed OS upgrade be stopped? because in this case for mysql we are using only one VM for deployment. How can failed OS upgrade be saved, by using canaries as the line of defence ? Does using canary by which bosh instructs the deployment to happen in the first VM and then pass on the changes to the remaining VM if it is successful ?

Any information would be very helpful

**Comment by schmidtsv** [comment]
The OS upgrade is not an "upgrade" in the sense of using apt-get. When upgrading a stemcell, the Director will stop the Jobs on the Instance, detach the persistent disk, if present, then terminate the vm. It will then create a new VM with the new image, attach the disk, copy over the Jobs and tries to start them. 
The Canary in this case is the first VM to be upgraded, and if it runs all other machines of those instance groups go through the same process, this time the amount of instances that do that is limited by max_in_flight.

**Comment by jaikanthm** [comment]
Thanks @schmidtsv 

So in this case Canary, is also dependent on the original number (number of instances) of VMs or containers.
For canary to actually be effective, there  must be more than one instance deployed right ?

**Comment by schmidtsv** [comment]
If you want a no-downtime upgrade you always need to use something with either Clustering or Replication. In case of MySQL, you need a cluster which fails over when the master shuts down for upgrade. If you just have 1 instance in an instance group the whole group will be down during upgrade. (You should also consider, that a node may fail, so for production you should always have some form of failover/duplication)

**Comment by jaikanthm** [comment]
Thanks again for the prompt response. 

One last question, you mentioned that when we do a OS/stemcell upgrade the persistent disk gets detached and a new VM gets created with the upgraded stemcell. Does the same process happen when we do a Application release upgrade ? say if mysql is getting an upgrade, are the steps similar ?

**Comment by dpb587-pivotal** [comment]
There are generally two types of changes in a VM's lifecycle...

1. network/VM/stemcell/IaaS-related which will result in a VM being recreated
2. software/persistent disk-related which will keep the existing VM (I think this is the "application release upgrade" you're referring to)

In both cases, there will be downtime due to processes being stopped during the update; but in the first case there will generally be a longer delay due to the underlying VM also being recreated by the IaaS.

**Comment by cppforlife** [comment]
>  In both cases, there will be downtime due to processes being stopped during the update

to clarify danny's note, downtime will happen in bosh of these cases if you just have 1 instance in an instance group.

**Comment by jaikanthm** [comment]
Thank you very much guys. That was very helpful

**Comment by dpb587-pivotal** [comment]
oops. you snuck in an edit with another question :)

From the ["glossary"](https://bosh.io/docs/terminology.html#canary)...

 > Canary instances are first instances updated within an instance group. Any update error in a canary instance causes the deployment to stop. Since only canaries are affected before an update stops, problem jobs and packages are prevented from taking over all instances.

There aren't explicit test scripts to determine canary success - it's more: are all processes running successfully by the time we expect them to be up and running, and did the [post-start](https://bosh.io/docs/post-start.html) scripts run successfully?
