### ISSUE TITLE
Error 130011:  for manual network 'compilation_network': no more available

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/bosh#1704]
I am getting following error message for v2 schema manifest on vSphere environment. I have tried multiple options to sort it out, like allocating more number of IP addresses, increasing number of workers, free up whole network pool for compilation network, changing reserve range, static range etc. but no luck.

Error 130011: Failed to reserve IP for 'compilation-9473d4e9-718f-475e-9e87-21faeef190f7/a9ac3b1a-709c-431f-870b-703355405973 (0)' for manual network 'compilation_network': no more available.

BOSH v260 and vSphere CPI v35 are used. 

Following is my cloud-config.yml file
--------------------------------------
azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: DC 
      clusters:
      - {Dummy: {resource_pool}}

compilation:
  workers: 2
  network: compilation_network 
  reuse_compilation_vms: true
  az: z1 
  cloud_properties:
    cpu: 2
    disk: 40960
    ram: 16384

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    disk: 40960
    ram: 8192
- name: large
  cloud_properties:
    cpu: 2
    disk: 40960
    ram: 16384
- name: tiny
  cloud_properties:
    cpu: 1
    disk: 10240
    ram: 1024

networks:
- name: bosh_services_network1
  type: manual
  subnets:
  - range: 10.124.101.0/24
    dns:
    - 10.124.101.10 
    - 10.xx.xx.xx
    - 10.xx.xx.xx
    gateway: 10.124.101.1
    az: z1 
    reserved:
    - 10.124.101.2 - 10.124.101.125
    static:
    - 10.124.101.126 - 10.124.101.252
    cloud_properties:
      name: network1
- name: bosh_services_network2 
  type: manual
  subnets:
  - range: 10.123.38.0/23
    dns:
    - 10.124.101.10 
    - 10.xx.xx.xx
    - 10.xx.xx.xx
    gateway: 10.123.38.1
    az: z1 
    reserved:
    - 10.123.38.2 - 10.123.38.10
    - 10.123.38.231 - 10.123.38.240
    static:
    - 10.123.38.11 - 10.123.38.230
    - 10.123.39.1 - 10.123.39.254
    cloud_properties:
      name: network2
- name: compilation_network
  type: manual
  subnets:
  - range: 10.123.38.0/23
    dns:
    - 10.124.101.10 
    - 10.xx.xx.xx
    - 10.xx.xx.xx
    gateway: 10.123.38.1
    az: z1 
    reserved:
    - 10.123.38.2 - 10.123.38.230
    - 10.123.39.1 - 10.123.39.254
    static:
    - 10.123.38.231 - 10.123.38.240
    cloud_properties:
      name: network2
----------------------------------------------

Thanks,
Prashant

**Comment by dpb587-pivotal** [comment]
Do you have other legacy deployments which are also using the same network space as `compilation_network`? Director excludes IPs of old-style deployment manifests and may be a factor here.

Although less likely, this could also happen if you have numerous deploys happening in parallel, all trying to compile different things. You should have ~24 IPs available for compilation.

Next time, please use [code fences](https://guides.github.com/features/mastering-markdown/) for your snippets to ensure it is readable by others.

**Comment by prashantgnet** [comment]
Yes, I have schema v1 based deployments which uses the same network which are also assigned to compilation_network. so issue is due to this. Thanks a lot Danny!
