### ISSUE TITLE
"ssh: handshake failed" when deploying latest Director

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry/bosh#1710]
Deploying BOSH Director v262.1 with bosh-google-cpi v25.9.0, we see the following error:

```
Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Starting SSH tunnel:
        Starting SSH tunnel:
          Failed to connect to remote server:
            ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

If we remove the `cloud_provider.ssh_tunnel` section of the deployment manifest, the deployment succeeds but we can't SSH onto it (even using a projectwide SSH key defined in the GCP console).

**Comment by henryaj** [comment]
cc @kirederik

**Comment by cppforlife** [comment]
@henryaj see how to configure additional user on the director vm: https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/jumpbox-user.md

**Comment by henryaj** [comment]
I don't think that addresses our issue. Configuring the `ssh_tunnel` cause shouldn't cause the deployment to fail (and this wasn't happening on previous versions of the Director + CPI).

**Comment by henryaj** [comment]
Ah, okay - thanks @dpb587-pivotal, that makes sense.
