### ISSUE TITLE
v262 release notes edit

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1711]
Currently the v262 release notes say:

> [breaking] Required Director SSL certificates to be always specified `director.ssl.certificate` and `director.ssl.private_key` properties

But I think it should say:

> [breaking] Required Director SSL certificates to be always specified `director.ssl.cert` and `director.ssl.key` properties

**Comment by cppforlife** [comment]
@drnic fixed. much appreciated.
