### ISSUE TITLE
How can I install and use Bosh director on my local computer without using bosh-lite?

### ISSUE THREAD

**Issue by ivandavidov** [cloudfoundry/bosh#1714]
Hello,

Is there a documentation which explains what I need to do in order to install the minimum required Bosh infrastructure on just one physical machine?

What I'm trying to achieve is to cut the "middle man" which in my case is the VirtualBox image and as result I'd like to work directly with the Bosh environment on my local machine.

I understand it's not just one software piece and the actual installation process may (and most probably will) include the installation of other software pieces. Yet I'm interested to achieve that in order to reduce the additional CPU load which I get when I run another VM (bosh-lite) on my local nachine.

Your help on this matter is highly appreciated! Thank you!

Regards,
Ivan Davidov

**Comment by allomov** [comment]
Hey, @ivandavidov.

BOSH uses a special environment (that is provided by stemcell image) to run its jobs. It is quite uncommon task to run BOSH jobs out of cloud/container environment. You can run all BOSH components on VM, but it is going to be hard to handle everything. To do so you need to run all components listed in manifest generated by [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) for warden iaas.

There is [a project](https://github.com/cppforlife/bosh-provisioner) that helps to make any VM to behave like BOSH vm, but I am not sure it is suitable in your case.

Also you can try using [docker image of BOSH](https://hub.docker.com/r/bosh/bosh-lite/), it may probably satisfy your needs to avoid using Virtualbox.

**Comment by ivandavidov** [comment]
Thank you, @allomov!

Currently the Docker image is the closest and fastest thing to what I'm trying to achieve.

From what I see, the Docker image versions are following the same pattern as the Vagrant based bosh-lite VM. I know for sure that bosh-lite is not going to have new updates (in favor of the new bosh 2 CLI which manages the VM), which makes me think that the Docker image won't get updates either. Nevertheless, this Docker image might be just what I need.

I consider the issue resolved since I got the initial "push" which I need in order to investigate this area further.

**Comment by cppforlife** [comment]
ivan: if you have docker daemon running you can just use docker/cpi.yml in bosh-deployment. here is how it would look: https://github.com/cloudfoundry/bosh-deployment/blob/master/test.sh#L435.it uses docker cpi to run director and uses same cpi to run other containers.

**Comment by ivandavidov** [comment]
@cppforlife - thank you for the additional information.

I already ran into trouble with the bosh v1 docker image. Seems like I have to explicitly configure the docker environment to use non-default network because I got these errors while I tried to deploy cf-release:

```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 4
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc
  Started compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > nginx/e77a07866c05979b49389fe36d66846411ba08a2
  Started compiling packages > ruby-2.3/3a224c0fb813a20b92de640ac779e1754a2748b4
  Started compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d
   Failed compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID 'a7c7d25b-ecd6-48a3-ab96-943d446e8a90': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)
   Failed compiling packages > nginx/e77a07866c05979b49389fe36d66846411ba08a2: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '01d5b66b-f929-476c-8e67-e8ff484a2501': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)
   Failed compiling packages > libpq/7e51aa75bcabc47002eccc38be269de63fc6df7d: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '2ab2a6ae-6047-4640-802e-7e008ceee570': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)
   Failed compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID 'd0f930af-4d6b-4355-aa83-e2c28d15489e': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '9b2bf8e0-52e4-4f1e-98c5-be3e51e0f737': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)
   Failed compiling packages > ruby-2.3/3a224c0fb813a20b92de640ac779e1754a2748b4: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID 'f21a1f1f-87eb-4bec-bb61-0a7075a81070': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method (00:00:00)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID 'a7c7d25b-ecd6-48a3-ab96-943d446e8a90': Creating container: Post http://api/containers: dial tcp 127.0.0.1:7777: getsockopt: connection refused' in 'create_vm' CPI method

Task 4 error

For a more detailed error report, run: bosh task 4 --debug
```

I'm pretty sure the above error is due to some docker misconfiguration. I ran the docker container like this:

```
sudo docker run --privileged=true --publish 25555:25555 -i -t bosh/bosh-lite bash
/usr/bin/start-bosh
```
Since there is active Docker support in the bosh v2 infrastructure, I guess it is better for me to focus my efforts in this direction instead of trying to figure out what the problem is with my local machine/docker.

Once again - thank you for the hint! It is really useful!
