### ISSUE TITLE
This is not issue, its a query regarding full-bosh

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/bosh#1715]
Hi is any-one deploy full bosh using any kind of cpi. I mean i create the full bosh yaml file to deploy on openstack using openstack cpi. but i am getting this error  {Command 'deploy' failed:    Validating deployment manifest:    jobs must be of size 1 }. Is any one have idea about full bosh deployment. For your reference i am attaching my yaml file.
[full-bosh-init.txt](https://github.com/cloudfoundry/bosh/files/1096452/full-bosh-init.txt)

**Comment by penrod** [comment]
I've seen this when trying to deploy using the bosh create-env command. The
deploy is expecting only one job, so the parser throws an error.

What is the deploy command you are using when you get this error?

**Comment by dpb587-pivotal** [comment]
Agreed with @penrod - to deploy a multi-VM BOSH, you'll want to deploy from an existing director. The `bosh-init`/`bosh create-env` commands are designed to only deploy a single VM.

Typically, a single VM director will be more than sufficient. I'd strongly recommend starting with a single VM and only distributing jobs when it's specifically required.

**Comment by abhilash07** [comment]
hi @penrod @dpb587-pivotal , thanks for your reply, i use bosh-init deploy --.yml.  Bt the problem is as we all know micro-bosh vm is single vm, which take take cares release engineering and auto-recovery etc, of deployment vm's. But the problem is some times director vms goes down it is difficult to manage the deployment vms. Is there any solutions to deploy bosh-init vm in to multi vm's ?

**Comment by cppforlife** [comment]
@abhilash07 another option is to just use one director to deploy another single vm director.
