### ISSUE TITLE
Does delete-deployment reach out to the VMs?

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/bosh#1716]
While trying to delete a deployment with several unresponsive agents, we noticed that the delete often failed on the unhealthy instance groups. 

Does this imply to delete the deployment the director reaches out to the VM before deleting it?

**Comment by cppforlife** [comment]
delete deployment tries to drain machines where possible. there is --force flag available that will ignore failures to contact agents.

**Comment by apoydence** [comment]
@cppforlife We actually did try the `--force` flag and still experienced errors. We resolved the problem by running the `delete-deployment` several times and each time more VMs were successfully deleted.

That being said, there does not appear to be an option to skip the drain (much like the available flag `--skip-drain` in the deploy command). Should there not be one?

**Comment by jfmyers9** [comment]
I'm going to close this issue as the original question has been answered.

The secondary feature request is currently being tracked by this issue: https://github.com/cloudfoundry/bosh/issues/1958
