### ISSUE TITLE
wget/curl returns incorrect version for 3421.9

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry/bosh#1720]
I am using wget and curl to try to retrieve 
bosh-stemcell-3421.9-aws-xen-hvm-ubuntu-trusty-go_agent.tgz

Using HTTPS, or the following curl and wget commands provided by http://bosh.cloudfoundry.org/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent returns light-bosh-stemcell-3421.9-aws-xen-hvm-ubuntu-trusty-go_agent.tgz instead.

curl -L -J -O https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.9

wget --content-disposition https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.9

**Comment by dpb587-pivotal** [comment]
Hi - when light stemcells are available, bosh.io will provide them by default at that download URL. If you specifically need a heavy for some reason, here are a couple options...

 * you can append the query string `light=false` to the URL (e.g. [`?v=3421.9&light=false`](https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3421.9&light=false))
 * use the direct links from the "All Versions" section

Separately, is there a reason that light AWS stemcells don't work for you? They're generally interchangeable.
