### ISSUE TITLE
can the resurrector be enabled/disabled per deployment

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/bosh#1724]
If a single director has several different deployments, is there a way to disable the resurrection for specific deployments?

**Comment by cppforlife** [comment]
@apoydence not currently, however, we have a coming up feature about resurrection config that will allow to specify resurrection granularity more or less arbitrarily.

**Comment by gerhard** [comment]
I believe that this is already addressed via the `bosh update-resurrection` command: https://bosh.io/docs/resurrector.html

**Comment by jfmyers9** [comment]
The [resurrection config](https://bosh.io/docs/resurrector/#enable-with-resurrection-config) has been released in the latest BOSH releases. Closing this issue.
