### ISSUE TITLE
Unable to deploy director

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry/bosh#1733]
Trying to deploy director to vsphere as per this doc:

https://bosh.io/docs/init-vsphere.html

I kick off the Bosh create-env and eventually get the following error:

/.bosh/installations/854fc253-f926-4c90-6bd5-7c48e857e5bd/packages/vsphere_cpi_ruby/bin/gem install vsphere_cpi_ruby/bundler-1.14.6.gem --local --no-ri --no-rdoc
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
':
          exit status 1

Exit code 1

Completely new to all this so I don't even know where to start much thanks to anyone who reaches out.

**Comment by cppforlife** [comment]
@cwb124 have you run through http://bosh.io/docs/cli-env-deps.html?
