### ISSUE TITLE
Deploying BOSH CLI give x509 error

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry/bosh#1740]
I tried to deploy a BOSH Director from a box that was not on the same subnet as the the target director, so I changed the `internal_ip` to a ip that was on the same subnet as the box i was running the `bosh create-env` command. I also changed the `internal_cidr` and `internal_gw` values appropriately. However, now I get this message:`Post https://mbus:<redacted>@172.31.80.29:6868/agent: x509: certificate is valid for 172.31.80.36, not 172.31.80.29`
The .36 address was the ip i WAS using. now I am using .29 which is on another /27 subnet.

where is this bloody x509 cert, and how do i change it?  (can i just remove it? it seems like it created itself.)

**Comment by ematpl** [comment]
Hi, @DonBower, I'm assuming you're using [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) to deploy the Director, based on the variable names you're referring to. That cert comes from the [`mbus_bootstrap_ssl` variable](https://github.com/cloudfoundry/bosh-deployment/blob/857c8ba7520fe0c1c9686c98b215abc516a63a01/bosh.yml#L133-L138) in the bosh.yml base manifest, and [this line](https://github.com/cloudfoundry/bosh-deployment/blob/857c8ba7520fe0c1c9686c98b215abc516a63a01/bosh.yml#L17) configures the VM's agent to present it. So if you delete that `mbus_bootstrap_ssl` variable from the vars store and let the BOSH CLI regenerate it with the new `internal_ip` value, that should resolve the IP SAN mismatch error.

**Comment by DonBower** [comment]
Hello @ematpl Eric;
I removed the creds.yml file (the file called out in the --vars-store flag, and viola!
Thanks for your help.
on to configuring stuff...

**Comment by dpb587-pivotal** [comment]
Great answer @ematpl, thanks!
