### ISSUE TITLE
How to SSH to director with vsphere deployment

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry/bosh#1742]
Straight forward.  I have successfully deployed my director to vsphere 6.5.  I am logged into it with bosh and can see the environment, deployments, etc etc.  I cannot however SSH to it.  Where is the vcap password stored/generated and how do I find it?  Do I have to edit the bosh.yml in some way to create a user/password so I can SSH to troubleshoot as I go through this process?  Going around in circles with this one...

**Comment by schmidtsv** [comment]
If you did not manually assign a password, the password will be random (beginning on stemcell 3363). You should take a look at https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml to create a jumpbox user with ssh key auth.

**Comment by martjarvi** [comment]
Hi. In the bosh.yml vmware manifest I have this:
resource_pools:
 env:
  bosh:
   password: "yourhash"

**Comment by cwb124** [comment]
Here is what my resource_pools section looks like:

resource_pools:
- name: vms
  network: default
  env:
    bosh:
      password: password
      mbus:
        cert: ((mbus_bootstrap_ssl))

I assume this sets the vcap password to 'password'?  I have done this but can't ssh vcap@director_ip using that password.

**Comment by martjarvi** [comment]
The password in the manifest must be a sha-512 hash. Check https://lists.cloudfoundry.org/archives/list/cf-bosh@lists.cloudfoundry.org/thread/RT6MCSF2PF2DMHCTTCKXQIW7IAZO3URY/

**Comment by dpb587-pivotal** [comment]
Closing - sounds like the crypt suggestion is the correct answer.
