### ISSUE TITLE
unable to change the bosh vm's mtu setting

### ISSUE THREAD

**Issue by huangered** [cloudfoundry/bosh#1743]
Does bosh support change the stemcell's mtu setting, sometime we want to change the default mtu for eth0 from 1500 to lower or bigger, 
can we do this?

**Comment by voelzmo** [comment]
@huangered Out of curiosity: Which IaaS are you running on and what is your use-case for this?

**Comment by huangered** [comment]
@voelzmo hi, we are use the VMware vCenter and VMware NSX to create our cloud foundry.
we find in some special environment, we need to adjust the network interface's MTU.

**Comment by dpb587-pivotal** [comment]
That sounds like an incorrect networking configuration or discovery somewhere with that setup, but for experimenting to learn more about the issue, you might want to try the [`set_mtu`](http://bosh.io/jobs/set_mtu?source=github.com/cloudfoundry/networking-release&version=9) job from the `networking` release.

**Comment by huangered** [comment]
@dpb587-pivotal great, thanks, let me have a try.
