### ISSUE TITLE
cloud-config deployment with many VMs runs into 'task cancelled/timout' state

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1744]
Steps to reproduce:
* Install a clean director with 15 workers and 32 threads each
* use local postgres-9.4, set max DB connections to 1000 (just to be safe)
* install cf-release with multiple AZs and some additional runners

Deployment will try to create ~23 VMs in parallel. The task fails after ~1 minute with state `timeout`, because it got `cancelled`. In the debug log, we find this:
```
E, [2017-07-27 09:15:51 #15233] [task:74289] ERROR -- DirectorJobRunner: PG::Error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.: SELECT NULL
```

`netstat` on the Director says the Postgres DB never gets more than 40 concurrent connections, `htop` says memory has always ~4GB free and only one of the four CPUs is actually at 99% load.

At the same time: a non cloud-config deployment of CF of the same size succeeds.

Any ideas/suggestions what is going on here?

**Comment by paolostivanin** [comment]
PS: this is happening on OpenStack, Azure and GCP (postgres within the director vm). Now I'll try on Amazon where we are using RDS.

**Comment by voelzmo** [comment]
Seems like there is a connection to [`pool_timeout` ](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=262.3#p=director.db.connection_options) on the director db connections options – not really sure why that seems to only be relevant in the cloud-config case and otherwise works fine?

**Comment by cppforlife** [comment]
what is the size of the director? (instance type, disk type, etc)

**Comment by paolostivanin** [comment]
We are using 4 VCPUs, 8GB ram machines on all IaaSes (more or less, it's 7.5 on amazon and gcp).

**Comment by paolostivanin** [comment]
@cppforlife After multiple tries, I can confirm that setting pgpool to 80 solved our issue on Azure, OpenStack and GCP.
```
            L Error: timeout: 60.0, elapsed: 63.44875963
14:16:02 | Creating missing vms: consul_z2/d533090f-cbba-49ef-bea2-4fb1b1fa1658 (0) (00:01:35)
            L Error: timeout: 60.0, elapsed: 61.342340354
14:15:47 | Creating missing vms: doppler_z1/2a95cd3a-5a9b-447e-a441-2fcafa5f9a4e (0) (00:01:20)
            L Error: timeout: 60.0, elapsed: 63.651453009
14:16:26 | Creating missing vms: router_z1/511d5279-71e2-4f1e-8130-26876246fab0 (0) (00:01:59)
```

**Comment by cppforlife** [comment]
when you reference "pgpool", what do you mean by it?

**Comment by paolostivanin** [comment]
@cppforlife pool_timeout defined here: https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=262.3#p=director.db.connection_options

**Comment by voelzmo** [comment]
Still seeing issues now, although timeout for the postgres connection pool is set to 80

**Comment by paolostivanin** [comment]
timeout of 160, the issue is still happening

```
Director: PG::Error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.: SELECT NULL
```

**Comment by paolostivanin** [comment]
@cppforlife we were able to solve the issue by increasing the task checkpoint interval.
[Here](https://github.com/cloudfoundry/bosh/blob/201f9999f442634e8668e5c4c65c297d1fda0bd2/src/bosh-director/lib/bosh/director/api/controllers/tasks_controller.rb#L173) the task is sent into timeout if the lock is not renews after 90s. We patched the director, and set the sentinel value to 300s. This solved our issue.

Before the change:
{code}
Task 86352 Started  Tue Sep 19 14:43:17 UTC 2017
Task 86352 Finished Tue Sep 19 14:44:22 UTC 2017
Task 86352 Duration 00:01:05Updating deployment:
  Expected task '86352' to succeed but state is 'timeout'
Exit code 1

debug:3004:D, [2017-09-19 14:43:17 #12123] [task:86352] DEBUG -- DirectorJobRunner: Acquiring lock: lock:deployment:cf

debug:12459:D, [2017-09-19 14:45:18 #12123] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
{code}

After the change (Openstack):
{code}
4046:D, [2017-09-20 07:18:38 #30286] [task:86486] DEBUG -- DirectorJobRunner: Acquired lock: lock:release:cf
9687:D, [2017-09-20 07:20:19 #30286] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
10707:D, [2017-09-20 07:22:45 #30286] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
17724:D, [2017-09-20 07:25:15 #30286] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
27038:D, [2017-09-20 07:27:16 #30286] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
{code}

After the change (Azure):
{code}
2783:D, [2017-09-20 08:58:29 #49720] [task:22428] DEBUG -- DirectorJobRunner: Acquired lock: lock:deployment:cf
3849:D, [2017-09-20 08:59:00 #49720] [task:22428] DEBUG -- DirectorJobRunner: Deleted lock: lock:release:cf uid: 0d37cb9b-093e-41cb-a823-b80cbbac4ba4
10451:D, [2017-09-20 09:00:30 #49720] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
20439:D, [2017-09-20 09:03:51 #49720] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:cf
{code}

**Comment by voelzmo** [comment]
@cppforlife @dpb587-pivotal how do you feel about exposing the checkpoint timeout as a property with default 30 seconds? Seems like for some reason we currently need to adapt this – not sure how long digging into root causes might take.

**Comment by prashantgnet** [comment]
I am facing this issue on vSphere environment, getting following error messages under log file
`
D, [2017-11-14 11:16:02 #26383] [task:151] DEBUG -- DirectorJobRunner: (0.000184s) COMMIT
D, [2017-11-14 11:16:02 #26383] [task:151] DEBUG -- DirectorJobRunner: [network-configuration] Reserved ip '10.122.51.205' for bosh_services_network as static
D, [2017-11-14 11:16:02 #26383] [task:151] DEBUG -- DirectorJobRunner: [network-configuration] Found subnet with azs 'z1' for 10.122.51.205. Reserved as static network reservation.
E, [2017-11-14 11:16:02 #26383] [task:151] ERROR -- DirectorJobRunner: PG::Error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.: SELECT NULL
D, [2017-11-14 11:16:02 #26383] [task:151] DEBUG -- DirectorJobRunner: (0.000158s) SET standard_conforming_strings = ON
`

**Comment by voelzmo** [comment]
@dpb587-pivotal I feel like commit https://github.com/cloudfoundry/bosh/commit/61a6991e5812a33fec3839379122462c1ec47029 tried to solve an issue with similar symptoms, as described in https://github.com/cloudfoundry/bosh/issues/1778

**Comment by KaiHofstetter** [comment]
We found an easy way to reproduce this issue. See the commit here: https://github.com/cloudfoundry/bosh/commit/7c25f7cdb8d2a9b3e1d9dd0a4eef740d7529f617

This commit adds high cpu usage to the `bosh vms` endpoint, which is executed by the BOSH [threadpool](https://github.com/cloudfoundry/bosh/blob/d7b6570ae08772c40138dbd9b1114599bd3e084b/src/bosh_common/lib/common/thread_pool.rb#L4). We saw the following:
* When task threads from the BOSH threadpool generate high cpu load:
  * the [TaskCheckPointer](https://github.com/cloudfoundry/bosh/blob/d7b6570ae08772c40138dbd9b1114599bd3e084b/src/bosh-director/lib/bosh/director/job_runner.rb#L122) thread, which updates the checkpoint time in the DB, is scheduled infrequently
  * SQL requests to update the checkpoint time are very slow 
  * this can cause the task timeout

## Interpretation
* the `TaskCheckPointer` thread uses a lot of IO (e.g. db calls, log outputs), which means it passes control back to the scheduler
* the task threads from the `threadpool` on the other hand use rarely or don't use IO, which means they rarely pass control back to the scheduler and rely on the scheduler to pause them

## Observation
When we modify the commit mentioned above to `100_000_000.times { |i| i * i; Thread.pass }`, the checkpoint column is updated in time and much faster. This means that the `TaskCheckPointer` thread doesn't get enough CPU time.

## With `Thread.pass`
```
D, [2018-02-05T09:14:08 #465] [task:1915-checkpoint] DEBUG -- DirectorJobRunner: (0.002087s) (conn: 47260528670420) SELECT NULL              
D, [2018-02-05T09:14:08 #465] [task:1915-checkpoint] DEBUG -- DirectorJobRunner: (0.000827s) (conn: 47260528670420) BEGIN          
D, [2018-02-05T09:14:08 #465] [task:1915-checkpoint] DEBUG -- DirectorJobRunner: (0.001032s) (conn: 47260528670420) UPDATE "tasks" SET "checkpoint_time" = '2018-02-05 09:14:08.348115+0000' WHERE ("id" = 1915)                                                                        
D, [2018-02-05T09:14:08 #465] [task:1915-checkpoint] DEBUG -- DirectorJobRunner: (0.003577s) (conn: 47260528670420) COMMIT                                    
```
## Without `Thread.pass`
```
D, [2018-02-02T16:40:32 #31869] [task:1914-checkpoint] DEBUG -- DirectorJobRunner: (2.604226s) (conn: 47338503403260) SELECT NULL
D, [2018-02-02T16:40:35 #31869] [task:1914-checkpoint] DEBUG -- DirectorJobRunner: (1.101875s) (conn: 47338503403260) BEGIN
D, [2018-02-02T16:40:37 #31869] [task:1914-checkpoint] DEBUG -- DirectorJobRunner: (1.301775s) (conn: 47338503403260) UPDATE "tasks" SET "checkpoint_time" = '2018-02-02 16:40:30.165886+0000' WHERE ("id" = 1914)
D, [2018-02-02T16:40:41 #31869] [task:1914-checkpoint] DEBUG -- DirectorJobRunner: (2.604388s) (conn: 47338503403260) COMMIT
```

The `bosh deployments` task generates high cpu usage e.g. in this case https://github.com/cloudfoundry/bosh/issues/1847 which ends with task cancelled because of timeout.
Although `Thread.pass` is not the desirable solution, it shows that there is an thread scheduling issue and not a thread locking problem.

Do you have any better ideas on how to approach the issue?

**Comment by ionphractal** [comment]
```
==> worker_8.debug.log <==
E, [2018-02-28 13:28:50 #4049] [] ERROR -- Director: PG::Error: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.: SELECT NULL
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.001629s) SET standard_conforming_strings = ON
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.000973s) SET client_min_messages = 'WARNING'
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.000883s) SET DateStyle = 'ISO'
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.000920s) BEGIN
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.002164s) UPDATE "tasks" SET "state" = 'processing' WHERE (("id" = 4352358) AND ("state" = 'queued'))
D, [2018-02-28 13:28:50 #4049] [] DEBUG -- Director: (0.002487s) COMMIT
```
I observed these messages before (above is on AWS with RDS, bosh/262.3, bosh-aws-cpi/66) and they're happening regardless of the CPU load like on almost every single internal task. Pretty strange that on Azure (bosh/264.7.0, bosh-azure-cpi/35.0.0) with a local PG instance the error is different yet similar in a way:
```
==> worker_2.debug.log <==
E, [2018-02-28T13:24:16 #6179] [] ERROR -- Director: *PG::ConnectionBad: PQconsumeInput()* server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.: SELECT NULL
D, [2018-02-28T13:24:16 #6179] [] DEBUG -- Director: (0.001755s) SET standard_conforming_strings = ON
D, [2018-02-28T13:24:16 #6179] [] DEBUG -- Director: (0.003836s) SET client_min_messages = 'WARNING'
D, [2018-02-28T13:24:16 #6179] [] DEBUG -- Director: (0.002990s) SET DateStyle = 'ISO'
D, [2018-02-28T13:24:16 #6179] [] DEBUG -- Director: (0.000501s) BEGIN
D, [2018-02-28T13:24:16 #6179] [] DEBUG -- Director: (0.007962s) UPDATE "tasks" SET "state" = 'processing', "checkpoint_time" = '2018-02-28 13:24:16.825979+0000' WHERE (("id" = 198927) AND ("state" = 'queued'))
```

However I can't relate these messages to deployment abortions in our case...

**Comment by dpb587-pivotal** [comment]
:link: Pivotal Tracker Story: [bump checkpoint interval to avoid task timeouts](https://www.pivotaltracker.com/story/show/155752015)

**Comment by jfmyers9** [comment]
The above story has been accepted and released in the latest BOSH director releases. I'm going to close this issue due to inactivity. If this above solution hasn't fixed your problem, please feel free to reopen this issue.

Thanks,

@jfmyers9, CF BOSH
