### ISSUE TITLE
BOSH should support IPv6 for workloads and for its own communications

### ISSUE THREAD

**Issue by DRuggeri** [cloudfoundry/bosh#1747]
As we've worked with BOSH, we've come across situations where we have exhausted IPv4 address space on some of our networks. Given that IPv6 is the successor to IPv4 and is indeed the path forward for the IP stack, it would be important for BOSH to support IPv6 in the following ways:

 - Workloads: Managing the network and available IP addresses should support both IPv4 AND IPv6 networks as well as only manage IPv6 network definitions
 - BOSH communications: The agent communications, SSH (which should be readily supported) and NATS should support being deployed on an IPv6 network with no IPv4 addresses

**Comment by cppforlife** [comment]
@DRuggeri happy to hear that there is more demand for ipv6. @cunnie and i are working for getting ipv6 working for vsphere and aws. we have a prototype that we've seen work on virtualbox (same as vsphere setup) and aws and hoping to start submitting prs shortly.

**Comment by dpb587-pivotal** [comment]
Some related PRs: #1774, cloudfoundry/bosh-agent#129, cloudfoundry/bosh-cli#307, cloudfoundry/bosh-linux-stemcell-builder#6

**Comment by hwinkel** [comment]
how far we are with IPv6 now? We have the need to Deploy IPv6 kubernetes Applications.Therefore the whole chain BOSH, CFCR (k8s) and IaaS must support IPv6.

**Comment by cppforlife** [comment]
progress is good. we actually have deployed zookeeper release on vsphere
with everything (cli, director, vms) ipv6 recently. we've used latest
director and stemcell to do so.

we are currently writing up a guide how to get that going:
https://github.com/cloudfoundry/docs-bosh/commit/af488501c5d7131c28dc05a743412933205349da
(ipv6 branch of docs-bosh)

which iaas are you looking for support? we currently handle manual
networking without dhcp (typical configuration for vshere for example). our
next task is to get manual networking with dhcp (aws, some openstacks)
working.

**Comment by hwinkel** [comment]
@cppforlife Thanks for the feedback. Currently on the IaaS shortlist are a vSphere based Deployment, or eventually Softlayer. There was Azure Planned as well, but seems there is still no IPv6 tin VNET these days.

**Comment by cunnie** [comment]
@DRuggeri @hwinkel : We've published http://engineering.pivotal.io/post/bosh-on-ipv6-2/ , the first of several blog posts to describe using IPv6 with BOSH.

@DRuggeri : Before you get too excited, this blog post describes deploying VMs with _both_ IPv4 & IPv6 addresses, which doesn't address your problem of IPv4 address-exhaustion. We hope to address that in a subsequent post (VMs deployed solely with IPv6).

@hwinkel : It doesn't address the full chain (BOSH + CFCR), merely BOSH, and only on vSphere. We're still making progress — stay tuned.
