### ISSUE TITLE
send mail from bosh created vms

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry/bosh#1749]
Hi Colleagues,

I am trying to send a mail from bosh created vms but it gives me an error stating mailx command not found. by default mailx wont be installed? 
steps to reproduce:
1. bosh ssh <vm ip>
2.echo "something" | mailx -s "subject" recipient@somewhere.com

Actual result: mailx not found.

we need to install mailx ?

BRs,Gowrisankar

**Comment by dpb587-pivotal** [comment]
Hi - the base stemcell only installs a minimal number of packages (to keep it small and maintainable). When releases have dependencies on particular tools not available in the stemcell, they should include them in their release's packages.

We're not planning on adding the `mailx` command by default, so you might want to add it to your release. In case you hadn't found it yet, here's a link to [creating packages](http://bosh.io/docs/packages.html) which may be useful.

Hope that's helpful, but feel free to follow up if you have a question about it.
