### ISSUE TITLE
Credhub has stopped supporting spaces in credential names

### ISSUE THREAD

**Issue by akshaymankar** [cloudfoundry/bosh#1750]
The credential that bosh director creates in credhub looks like: <DIRECTOR_NAME>/<DEPLOYMENT_NAME>/<CREDENTIAL_NAME>. If there is a space in any of those, the bosh deployment fails.

**Comment by jfmyers9** [comment]
The only two values that are able to have white spaces in them are the director name and the credential name.

For the director name, we could probably do some amount of validation in the director itself to error out if users provide a name that contains invalid characters.

For the credential name, I think the manner in which it fails (credhub variable generation failure) seems appropriate for the time being.

For deployment names, there is currently validation to ensure that they do not contain spaces at the moment.

I'm going to close and reopen this story to generate a github story.

**Comment by dpb587-pivotal** [comment]
Semi-relevant... at one point there was discussion of using the director UUID instead of name. It would help in this sort of thing, but I think some of the original concern for using name was so that it could be predictable for some use case.
