### ISSUE TITLE
 Failed: 'consul_z1/0 (xxxxxxxx)' is not running after update. Review logs for failed jobs: consul_agent, metron_agent (00:10:32)

### ISSUE THREAD

**Issue by asmonter** [cloudfoundry/bosh#1751]
Hi evryone
I have a issue in bosh deploy.
I can  deploy all the instances but i have this problem.

Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:01)

  Started updating instance consul_z1 > consul_z1/6b67631f-0beb-4143-bfed-16b97910041b (0) (canary). Failed: 'consul_z1/0 (6b67631f-0beb-4143-bfed-16b97910041b)' is not running after update. Review logs for failed jobs: consul_agent, metron_agent (00:10:32)

Error 400007: 'consul_z1/0 (6b67631f-0beb-4143-bfed-16b97910041b)' is not running after update. Review logs for failed jobs: consul_agent, metron_agent

Task 41 error

consul_z1/0 (6b67631f-0beb-4143-bfed-16b97910041b)*           failing
consul_agent                                                                                  failing 
metron_agent                                                                                 failing 

consul_z1/6b67631f-0beb-4143-bfed-16b97910041b:/var/vcap/data/sys/log# tail -f metron_agent/metron.log
2017/08/04 23:47:35 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/04 23:54:23 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/04 23:56:03 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/04 23:57:51 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/04 23:59:21 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/05 00:01:01 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/05 00:02:41 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input
2017/08/05 00:04:21 Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input

consul_z1/65d2eb14-b072-49e9-9b31-46daac3cb863:/var/vcap/sys/log# tail -f consul_agent/consul_agent.stderr.log
error during start: timeout exceeded: "Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused"
error during start: timeout exceeded: "Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused"
error during start: timeout exceeded: "Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused"
error during start: timeout exceeded: "Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused"
error during start: timeout exceeded: "Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused"

Can anyone can help me?

**Comment by cppforlife** [comment]
@asmonter i would recommend asking for help in cloudfoundry-incubator/consul-release
