### ISSUE TITLE
Error message suggestion: Link disambiguation should describe which job, rather than which instance group, cannot resolve a link

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/bosh#1753]
We just ran up against a pretty confusing error message. There's a job called `scheduler` that consumes link whose name and type are both `doppler`. The `scheduler` job is located on an instance_group called `loggregator_trafficcontroller_z1`, which has other jobs colocated on it.

When we failed to override the implicit link (in our case, with manual linking), we got the following error message:
```
Error 100: Unable to process links for deployment. Errors are:
  - Multiple instance groups provide links of type 'doppler'. Cannot decide which one to use for instance group 'loggregator_trafficcontroller_z1'.
     cf-a1.loggregator_z1.doppler.doppler
     cf-a1.loggregator_z2.doppler.doppler
     cf-a1.doppler_z1.doppler.doppler
     cf-a1.doppler_z2.doppler.doppler
...
```

The error message doesn't say which job was having issues with the link. It could say something like "Cannot decide which one to use for job 'scheduler' on instance group 'loggregator_trafficcontroller_z1'."

**Comment by dpb587-pivotal** [comment]
Agreed, I think this is confusing as well. Particular in the scenario where a new operator might not realize multiple jobs need the same link. Including job would help them realize it rather than spending time quadruple checking the configuration of the job they know and expect.

**Comment by jfmyers9** [comment]
This appears to be a duplicate issue of https://github.com/cloudfoundry/bosh/issues/1632. As mentioned, this has hopefully been fixed as of [this story](https://www.pivotaltracker.com/n/projects/2132440/stories/158077990). Feel free to reopen this issue if you have further questions or find the new output insufficient.
