### ISSUE TITLE
Errands to invoke `stop` on collocated job templates

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#1755]
It is possible to collocated job templates on an errand (the errand job template has to be first in the list), for example https://github.com/cloudfoundry-community/docker-boshrelease/blob/master/manifests/broker/docker-broker.yml#L64-L78 (`sanity-test` delegates its behavior to a dynamically configured docker container)

But currently when the errand completes and is about to be deleted, the collocated job templates (e.g. `docker` above) do not have `monit stop`invoked upon them, which denies them the opportunity to clean up prior to their persistent disk being detached. This can mean that running an errand will fail because it cannot detach the persistent disk, and thus not delete the vm.

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.
