### ISSUE TITLE
How to disable syslog messages to appear in `bosh events`

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh#1759]
Is there a way to disable automatic syslog messages in the bosh events table?

On systems where there is e.g. external monitoring set up that uses frequent ssh logins, that table easily gets spammed with entries like: `| 163841 | Fri Aug 11 09:41:52 UTC 2017 | admin | create | alert       | 60363514-3db5-1234-435f-fb53cf15059b | -    | deployment_name             | vm/888e4fdb-aaaa-4f06-9fd2-c4fb3a82662c       | message: SSH Login. Alert @ 2017-08-11 09:41:52 UTC, severity 4: Accepted password for ssh_user from 1.2.3.4 port 57114 ssh2 |`

That makes the DB grow quickly and less useful to use it as audit log for other events like deployments, updating instances etc.

Any suggestions are welcome.

Thanks,
Peter

**Comment by dpb587-pivotal** [comment]
This is not currently configurable - a select few VM-system events (namely SSH logins and monit service status changes) are forwarded to the agent/health monitor/events. As an alternative, you might be interested in increasing [`director.events.max_events`](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=263#p=director.events.max_events) from the default `10000` events if they're filling up too quickly.

Would increasing the retention count be sufficient for you? Do you use any other source for monitoring SSH login events?

**Comment by petergtz** [comment]
> Would increasing the retention count be sufficient for you?

Not sure. My idea was to increase that value anyway, because I think for events to serve as a proper audit log, it should contain the complete history of past events. My biggest concern with that though is, that it will slow down the overall DB performance, because of its size and eventually slow down the director. And obviously that problem will be worse, when a lot of data is generated by the syslog messages. Do you think that concern is justified?

> Do you use any other source for monitoring SSH login events?

I believe we do. But would have to look into how.

**Comment by petergtz** [comment]
@dpb587-pivotal 

So we've observed this and found that it's unmanageable. When we increase the retention count, the size of the database quickly grows to tens of GBs which then causes a lot of other issues down the line.

Would you accept a PR that introduces a config value to enable/disable syslog messages from going into the events table?

**Comment by voelzmo** [comment]
+1 we also have a few automated scripts which SSH regularly into VMs. `bosh events` is pretty much useless for us right now.

**Comment by petergtz** [comment]
@dpb587-pivotal Any thoughts on this?

**Comment by petergtz** [comment]
@cppforlife do you see issues with introducing a `suppress_ssh_events` config? It could be defaulted to false.

**Comment by petergtz** [comment]
@cppforlife After discussing this with @voelzmo it seems that we rather want a generic way to specify which events to keep and which ones to drop. So my suggestion with `suppress_ssh_events` seems obsolete.

OTOH, the more I think about this, the more I wonder if we should provide a way to stream these events into a different drain altogether. If we want this as audit log, it'll grow indefinitely and we might not want to keep it in the director's DB then. I found there is `log_access_events_to_syslog`, but it's purpose is slightly different than `bosh events`. Any opinions on making `bosh events` more pluggable, @cppforlife?

**Comment by voelzmo** [comment]
on a side note: events are also logged to syslog by default, without specifying a property: https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/api/event_manager.rb#L55

So if you want a stream that gives you everything: syslog forward from the director to an auditlog endpoint.

**Comment by petergtz** [comment]
Ah, didn't find that one. Thanks, @voelzmo.

@cppforlife Any thoughts on a general filter property for events?

**Comment by dpb587-pivotal** [comment]
We plan to stop forwarding system SSH events via agent to the director in a future stemcell. This should fix the issue around too many events being tracked. Existing `bosh tasks` auditing will be unaffected and still show `setup ssh`/user requests.

Story: https://www.pivotaltracker.com/story/show/154424559

**Comment by jfmyers9** [comment]
Closing this issue as the referenced story has been accepted and released in recent versions. Please feel free to reopen if you have more questions.
