### ISSUE TITLE
support instance locally scoped links

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh#1760]
some links only makes sense to be consumed within a context of each instance (local agent). by having some links be locally scoped implicit linking could automatically connect consumers and providers without running into multiple providers error.

**Comment by cnelson** [comment]
This would be very useful for having jobs know if other jobs like metron are locally installed and available for use!

Dreaming about bosh providing unix sockets for jobs on the same host to communicate with each other :)
