### ISSUE TITLE
Manifest diff doesn't show 'tags' as changed

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh#1764]
Having a deployment with tags and redeploying it with changed tags, does not result in any diff.

Response from director's `/:deployment/diff`:
```
{"context":{"cloud_config_id":1,"runtime_config_ids":[1]},"diff":[]}
```

**Comment by mfine30** [comment]
Hey @Kiemes do you know what version you saw this on? Is it still a problem?

**Comment by Kiemes** [comment]
@mfine30 sorry. But if you know which version was latest on 23 of August last year, I am pretty sure that it was that version as I am mostly up to date :)

**Comment by dpb587-pivotal** [comment]
Current implementation doesn't track `tags` for the resources so it doesn't know when they've changed. Similar behavior to changing properties on the CPI releases - they're not taken into affect until a [re]create.

**Comment by mrosecrance** [comment]
Fixed in https://www.pivotaltracker.com/story/show/168917397.
