### ISSUE TITLE
`bosh upload release` commands on https://bosh.io/releases don't work as is after copy-paste

### ISSUE THREAD

**Issue by goutamtadi1** [cloudfoundry/bosh#1765]
There's a space between "upload" and "release", when there should be a dash. For example:

https://bosh.io/releases/github.com/cloudfoundry/grootfs-release

```
0.25.0 — Details / Download sha1: 9e517f58669c5a4e6d368d607843749b1e10654d

# Upload latest version, currently 0.25.0
$ bosh upload release https://bosh.io/d/github.com/cloudfoundry/grootfs-release

# Upload specific version
$ bosh upload release https://bosh.io/d/github.com/cloudfoundry/grootfs-release?v=0.25.0
0.24.0 — Details / Download sha1: b342db5da3a7bd7bb2e81c2f6456d75cf38e9e0c

$ bosh upload release https://bosh.io/d/github.com/cloudfoundry/grootfs-release?v=0.24.0
```

cc/ @cjcjameson; sorry if it's a duplicate

**Comment by cppforlife** [comment]
will be fixed up in next bosh.io update.

**Comment by cjcjameson** [comment]
Ok -- we assume that website might be closed source, so it's reasonable that we wouldn't see that code anywhere, right?

**Comment by drnic** [comment]
https://github.com/cppforlife/bosh-hub

@cppforlife - perhaps this can be moved into a cloudfoundry* org so its
more findable?

**Comment by tjvman** [comment]
Closing, bosh.io now shows the correct command. For reference, https://github.com/bosh-io/ org is the new place to look for bosh.io related code.
