### ISSUE TITLE
Ability to trigger monit reload

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry/bosh#1772]
In some releases, after changing persistent storage (ex: config files), I need to reload the processes. Most of the times I end up doing a `bosh deploy --recreate`.

I would prefer to issue a _monit_ reload with bosh as it would take a lot less time.

**Comment by jfmyers9** [comment]
Hi @dmlemos,

`monit reload` is used for reloading the configuration for the `monit` daemon which lives in `/var/vcap/monit`. This should not be tied to changing persistent storage. If you want to restart the processes that `monit` is managing, you can use `bosh restart` to do so.

I'm going to close this issue. Please feel free to reopen this issue if you have any further questions.

Best,

@jfmyers9, CF BOSH
