### ISSUE TITLE
CPI error 'Bosh::Clouds::CloudError' with message 'Cannot update settings for 'i-00ad94507e70fbb1a', got HTTP 500' in 'create_vm' CPI method

### ISSUE THREAD

**Issue by nitish29** [cloudfoundry/bosh#1773]
Hi, 

I'm getting this particular error when trying to deploy a buildpack on a PCF instance. 

#### CPI error 'Bosh::Clouds::CloudError' with message 'Cannot update settings for 'i-00ad94507e70fbb1a', got HTTP 500' in 'create_vm' CPI method

More details:
```sh
Director task 1341
  Started preparing deployment > Preparing deployment. Done (00:00:01)
  Started preparing package compilation > Finding packages to compile. Done (00:00:00)
  Started compiling packages
  Started compiling packages > bwce_231_buildpack/deb68123d40fc62b2ff7918337aec8ab9d977529
  Started compiling packages > cf_cli/8263e71ad745c6e072ceafb62f944bcd0590db95. Done (00:01:15)
   Failed compiling packages > bwce_231_buildpack/deb68123d40fc62b2ff7918337aec8ab9d977529: CPI error 'Bosh::Clouds::CloudError' with message 'Cannot update settings for 'i-00ad94507e70fbb1a', got HTTP 500' in 'create_vm' CPI method (00:03:01)
   Failed compiling packages (00:03:01)
   
Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Cannot update settings for 'i-00ad94507e70fbb1a', got HTTP 500' in 'create_vm' CPI method
Task 1341 error
```
Any idea how do I go about resolving this error? What does HTTP 500 indicate over here - is it a server issue?

Any kind of help would be much appreciated. Thanks.

**Comment by dpb587-pivotal** [comment]
If this is happening on AWS, can you take a look at `/var/vcap/sys/log/registry/*.log` logs? They may contain more information about what went wrong in the registry service. You may also want to double check that the registry is using the correct AWS credentials and database configuration.

**Comment by nitish29** [comment]
Hi @dpb587-pivotal, apparently in our case it was a space quota issue. We ran out of space. Thanks for the help, much appreciated.
