### ISSUE TITLE
bosh cli v2 deploy error 

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/bosh#1779]
I use boshcli v2 deploy but the following errors occurs:

Task 52 | 14:29:13 | Preparing deployment: Preparing deployment (00:00:00)
Task 52 | 14:29:14 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 52 | 14:29:14 | Compiling packages: golang1.7/68bf640dfc11e3a933a0bffe8d83a682c799eb6f
Task 52 | 14:29:14 | Compiling packages: java/d218a774ebc054edc87c5af700fb31e5689fe0df
Task 52 | 14:29:14 | Compiling packages: nodejs/bb2675d0152e3bb7f8488bc0f6adc33f71628000
Task 52 | 14:29:27 | Compiling packages: java/d218a774ebc054edc87c5af700fb31e5689fe0df (00:00:13)
                   L Error: Action Failed get_task: Task 003bc561-5991-4070-503e-93f3527c1603 result: Compiling package java: Running packaging script: Running packaging script: Command exited with 2; Stdout: , Stderr: + export PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
+ PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
++ uname
+ '[' Linux = Darwin ']'
++ uname
+ '[' Linux = Linux ']'
+ mkdir java
+ pushd java
+ tar xvf ../openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
tar: ../openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Task 52 | 14:29:27 | Compiling packages: golang1.7/68bf640dfc11e3a933a0bffe8d83a682c799eb6f (00:00:13)
                   L Error: Action Failed get_task: Task 51311380-d6d0-4bc9-55b6-2d3681604258 result: Compiling package golang1.7: Running packaging script: Running packaging script: Command exited with 2; Stdout: , Stderr: + tar xzf golang/go1.7.4.linux-amd64.tar.gz
tar (child): golang/go1.7.4.linux-amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Task 52 | 14:29:28 | Compiling packages: nodejs/bb2675d0152e3bb7f8488bc0f6adc33f71628000 (00:00:14)
                   L Error: Action Failed get_task: Task df0df54d-880a-4f64-784c-5e82cc90a860 result: Compiling package nodejs: Running packaging script: Running packaging script: Command exited with 2; Stdout: , Stderr: + export PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
+ PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
++ uname
+ '[' Linux = Darwin ']'
++ uname
+ '[' Linux = Linux ']'
+ mkdir -p node
+ pushd node
+ tar xvf ../nodejs/node-v6.9.2-linux-x64.tar.xz --strip-components=1
tar: ../nodejs/node-v6.9.2-linux-x64.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Task 52 | 14:29:28 | Error: Action Failed get_task: Task 003bc561-5991-4070-503e-93f3527c1603 result: Compiling package java: Running packaging script: Running packaging script: Command exited with 2; Stdout: , Stderr: + export PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
+ PATH=/var/vcap/bosh/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/bin:/usr/bin
++ uname
+ '[' Linux = Darwin ']'
++ uname
+ '[' Linux = Linux ']'
+ mkdir java
+ pushd java
+ tar xvf ../openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz
tar: ../openjdk/openjdk-1.8.0_101-x86_64-trusty.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Task 52 Started  Sun Sep 10 14:29:13 UTC 2017
Task 52 Finished Sun Sep 10 14:29:28 UTC 2017
Task 52 Duration 00:00:15
Task 52 error

Updating deployment:
  Expected task '52' to succeed but state is 'error'

Exit code 1

**Comment by dpb587-pivotal** [comment]
You may have switched between the ruby CLI and an older version of the golang CLI. If so, try the `bosh reset-release` and then upload a new version of the release again.
