### ISSUE TITLE
Bosh deploy - Failed compiling packages

### ISSUE THREAD

**Issue by sabz19** [cloudfoundry/bosh#1780]
Kind of ignored pasting some manifest information just before  the word *Deprecation* below

bosh deploy
Acting as user 'admin' on deployment 'cf-warden' on 'Bosh Lite Director'
Getting deployment properties from director...

Detecting deployment changes

Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment. Done (00:00:01)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c
  Started compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc
  Started compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf
  Started compiling packages > mariadb_connector_c/c53a5e4fdddcfdc41c427352ccfe9172f6397c01
  Started compiling packages > nginx/2f6ac4678d6c4bee5df717c030acf5c2c90c5eae
  Started compiling packages > ruby-2.3/de0e32fdb5507dfe2dd649cf8636f237f261b940
   Failed compiling packages > cli-network-policy-plugin/330209a6db78c64b3983e94a46b2586c05087bcc: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{1b0c67a9-5183-4043-a0c2-d9a31288733a}}': Creating container: the requested subnet (10.244.0.152/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)
   Failed compiling packages > nginx/2f6ac4678d6c4bee5df717c030acf5c2c90c5eae: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{5cbf38f8-f1b4-41c4-a569-f1b55bb5dbaa}}': Creating container: the requested subnet (10.244.0.156/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)
   Failed compiling packages > ruby-2.3/de0e32fdb5507dfe2dd649cf8636f237f261b940: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{0335a560-e465-4e66-a10b-237666f4566b}}': Creating container: the requested subnet (10.244.0.168/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)
   Failed compiling packages > cli/6e22370bfb380059b856a1b397bc14ae9ec1633c: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{808f39ca-a6ad-4be4-9981-01048ed3d4ca}}': Creating container: the requested subnet (10.244.0.148/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)
   Failed compiling packages > mariadb_connector_c/c53a5e4fdddcfdc41c427352ccfe9172f6397c01: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{c9420418-caa1-47d3-9922-f53071859426}}': Creating container: the requested subnet (10.244.0.160/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)
   Failed compiling packages > haproxy/ad6e9e08a6d7a0f8951322f9a2ce394105df7fcf: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{07b3f413-5ba8-4ac7-a809-7a3d2d7fe2d6}}': Creating container: the requested subnet (10.244.0.164/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method (00:00:13)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Creating VM with agent ID '{{1b0c67a9-5183-4043-a0c2-d9a31288733a}}': Creating container: the requested subnet (10.244.0.152/30) overlaps an existing subnet (10.244.0.0/24)' in 'create_vm' CPI method

**Comment by dpb587-pivotal** [comment]
Sorry we lost track of this one. This error usually happens when you have multiple deployments on your bosh-lite which have overlapping network configuration. You should update your network space to avoid overlap; or delete other deployments if they are no longer needed.
