### ISSUE TITLE
Bosh loses connectivity after vm reboot

### ISSUE THREAD

**Issue by sabz19** [cloudfoundry/bosh#1783]
bosh login
Expected non-empty Director URL

bosh -e 192.168.50.6 --ca-cert <(bosh int ~/deployments/vbox/creds.yml --path /director_ssl/ca) alias-env vbox
Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: dial tcp 192.168.50.6:25555: getsockopt: connection refused

Exit code 1

**Comment by dpb587-pivotal** [comment]
You'll need to rerun the `create-env` and `route` commands if your VM reboots. See the recommendation [here](http://bosh.io/docs/bosh-lite#tips).

 > * In case VirtualBox VM shuts down or reboots, you will have to re-run `create-env` command from above. (You will have to remove `current_manifest_sha` line from `state.json` to force a redeploy.) The containers will be lost after a VM restart, but you can restore your deployment with `bosh cck` command. Alternatively *Pause* the VM from the VirtualBox UI before shutting down VirtualBox host, or making your computer sleep.

**Comment by suhlig** [comment]
I have this problem all the time (with the most recent VirtualBox). Whenever my laptop goes to sleep, the director not unaccessible anymore afterwards.

Having to go through a `create-env` after I closed the lid is really annoying and definitely a huge degradation compared to the Vagrant solution we had before (which was rock-solid).

**Comment by cppforlife** [comment]
> Having to go through a create-env after I closed the lid is really
annoying and definitely a huge degradation compared to the Vagrant solution
we had before (which was rock-solid).

interesting, when im putting laptop to sleep and bring it up after, it
continues to work. did you configure virtualbox to shut off vms on sleep?
dont we are doing anything differently from vagrant.

**Comment by suhlig** [comment]
Just checking in to say that the problem remains with the latest VirtualBox:

```
$ VBoxManage --version
5.2.2r119230
```
