### ISSUE TITLE
Bosh Director deploy issue on Ubuntu 16.04 

### ISSUE THREAD

**Issue by nohealy** [cloudfoundry/bosh#1785]
[Bosh Director install failure.txt](https://github.com/cloudfoundry/bosh/files/1314495/Bosh.Director.install.failure.txt)

Hi Folks, 

I'm seeing an issue on Ubuntu 16.04 with the deployment of bosh director on a Ubuntu 16.04 VM. 
The deployment is for a vSphere environment. The attached doc had details steps on producing the issue and the environment used. 

I am not a ruby/rails expert in any ways so if there is any troubleshooting needed in these areas please keep it simple to follow. 

Many thanks, Noel/

**Comment by tjvman** [comment]
What infrastructure were you trying to use when you ran the `create-env`?

**Comment by tjvman** [comment]
Can you paste the full `bosh create-env` command that you ran (minus any credentials, of course)?

**Comment by nohealy** [comment]
Hi 

thanks or the reply, we have stalled this project and started looking at alternatives due to the large gaps in the documentation.
