### ISSUE TITLE
bosh create-env does not honor stemcell OS for compiled releases?

### ISSUE THREAD

**Issue by manno** [cloudfoundry/bosh#1786]
We're deploying with bosh-deployment onto the openSUSE stemcell. Deployment fails with 

```
  Waiting for instance 'bosh/0' to be running... Failed (00:05:07)
Failed deploying (00:06:52)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Received non-running job state: 'starting'
```
This is due a ruby gem which depends on libssl (see attached screenshot). 

![error-cpi](https://user-images.githubusercontent.com/393653/30605920-344efaea-9d70-11e7-8d7a-b35abc0616d0.png)

After switching to a custom BOSH release, create-env does work.

I would have expected create-env to error out earlier, as the stemcell os does not match the compiled release used in bosh-deployment. Is this missing from BOSH or is our stemcell missing metadata?

**Comment by dpb587-pivotal** [comment]
The `create-env` does not currently verify the stemcell os/version which compiled release tarballs include.

Does compiling the director from source work?

**Comment by manno** [comment]
@dpb587-pivotal Thanks for the quick reply. Yes, compiling from source works fine, so we're just using the [local bosh release ops file](https://github.com/cloudfoundry/bosh-deployment/blob/master/local-bosh-release.yml) for now.

**Comment by dpb587-pivotal** [comment]
Closing - this is a UX issue, at the very least, but it's more to do with [cloudfoundry/bosh-cli](https://github.com/cloudfoundry/bosh-cli). Feel free to raise an issue or pull request there if this is still important to you. I agree it would be nice fix, but it's a low priority for us, at this point.
