### ISSUE TITLE
Powerdns packaged with BOSH is 4 years out of date

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh#1790]
The current PowerDNS job uses a static deb from 2013:
```
Built on 20131217140531
```

https://github.com/cloudfoundry/bosh/blob/c6c419f9eff844c35c8c7307e977427f05a23a51/packages/powerdns/spec#L4

This release has a minimum of 8 CVEs which have been which are resolved in newer versions.

**Comment by cppforlife** [comment]
@sharms we havent seen any high cves related to powerdns that compromise the system and hence it was not proactively bumped. is there specific cve you are concerned about? we are also on the verge of replacing powerdns with bosh-dns which should simplify this mgmt.

**Comment by mfine30** [comment]
Given the overall product shift towards bosh-dns, I'm going to close this issue. If you'd like to continue the discussion, feel free to re-open it.
