### ISSUE TITLE
Bosh upload stemcell fails with error - task 28 - Error

### ISSUE THREAD

**Issue by ramyasg** [cloudfoundry/bosh#1791]
We have created a Windows Stemcell and when we try to upload it to bosh-director, getting error. 
Following is the error message - 
Task 28
Error: Relative paths are not allowed in this context. The following must be switched to use absolute paths: 'internal_gw', 'internal_cidr' 

Task 28 Error
Uploading Stemcell file:
  Expected task '28' to succeed but state is 'error' 
Exit code 1

Can anyone guide us with steps to upload a stemcell to director.

**Comment by pranaybakre** [comment]
Please check the yml file which gets generated while executing _bosh int_ . Update the 'gateway' and 'range' sections in it. Update the cloud config again with this updated yml file. Upload the stemcell again and it should pick up the values.

**Comment by ramyasg** [comment]
Thanks for your reply. We were able to resolve the issue. Closing the issue.
