### ISSUE TITLE
When multiple named runtime-configs bosh detects difference on deploy sproadically

### ISSUE THREAD

**Issue by calebwashburn** [cloudfoundry/bosh#1792]
Appears that when there are multiple named runtime-configs bosh thinks there is a difference so updates every VM in a deployment even though there has been no changes.  Looks like it might be ordering issue on the compare.  Created on bosh 263.2 with 3 named runtime-configs

FROM:
``
{
	"name" => "consul", "templates" => [{
		"name" => "consul_agent",
		"version" => "f34a73812d8c94d1fb194ec76b10053ba42f0b8d",
		"sha1" => "sha256:69f741d1c863598112f81b04b1fcadd3856284b12595edd1cd324e0354e0f157",
		"blobstore_id" => "bb35a2be-5307-4c4c-b732-97059d72f4f2"
	}, {
		"name" => "metron_agent",
		"version" => "247f9e857f4199f5331188d3d0d0e9b7ad000b52",
		"sha1" => "sha256:de706f2986ad8dc0777c6d9e61a28f48273c4abc7bfee35dc65c4fd12974b872",
		"blobstore_id" => "962c7897-40e7-410d-9f23-e981e15efef0"
	}, {
		"name" => "fim",
		"version" => "177d1ec1b17888133a8d840f4737ecd15c16603c",
		"sha1" => "c5acc6329803bd69d599cee28cbc9610a2200027",
		"blobstore_id" => "2eb3623b-5434-4d34-8e6d-f8ecbd832fb0"
	}, {
		"name" => "node_exporter",
		"version" => "68f611e1d444d5bf073ec975a2d9c6aa71dc8647",
		"sha1" => "f9e0ba9d6b12251638ef1dee2b5d2bbea77f9486",
		"blobstore_id" => "9228915a-cdee-4f7e-91c0-4a9737f4cc2f"
	}, {
		"name" => "ipsec",
		"version" => "82f987a522199700006420a29663ff629905e994",
		"sha1" => "e0fe19208768780c8202f1035c15b3d340bf2e9a",
		"blobstore_id" => "e9ad4c16-53d8-45e5-815e-c37fef3ca01c"
	}], "template" => "consul_agent", "version" => "f34a73812d8c94d1fb194ec76b10053ba42f0b8d", "sha1" => "sha256:69f741d1c863598112f81b04b1fcadd3856284b12595edd1cd324e0354e0f157", "blobstore_id" => "bb35a2be-5307-4c4c-b732-97059d72f4f2"
}
``

TO:
``
{
	"name" => "consul", "templates" => [{
		"name" => "consul_agent",
		"version" => "f34a73812d8c94d1fb194ec76b10053ba42f0b8d",
		"sha1" => "sha256:69f741d1c863598112f81b04b1fcadd3856284b12595edd1cd324e0354e0f157",
		"blobstore_id" => "bb35a2be-5307-4c4c-b732-97059d72f4f2"
	}, {
		"name" => "metron_agent",
		"version" => "247f9e857f4199f5331188d3d0d0e9b7ad000b52",
		"sha1" => "sha256:de706f2986ad8dc0777c6d9e61a28f48273c4abc7bfee35dc65c4fd12974b872",
		"blobstore_id" => "962c7897-40e7-410d-9f23-e981e15efef0"
	}, {
		"name" => "fim",
		"version" => "177d1ec1b17888133a8d840f4737ecd15c16603c",
		"sha1" => "c5acc6329803bd69d599cee28cbc9610a2200027",
		"blobstore_id" => "2eb3623b-5434-4d34-8e6d-f8ecbd832fb0"
	}, {
		"name" => "ipsec",
		"version" => "82f987a522199700006420a29663ff629905e994",
		"sha1" => "e0fe19208768780c8202f1035c15b3d340bf2e9a",
		"blobstore_id" => "e9ad4c16-53d8-45e5-815e-c37fef3ca01c"
	}, {
		"name" => "node_exporter",
		"version" => "68f611e1d444d5bf073ec975a2d9c6aa71dc8647",
		"sha1" => "f9e0ba9d6b12251638ef1dee2b5d2bbea77f9486",
		"blobstore_id" => "9228915a-cdee-4f7e-91c0-4a9737f4cc2f"
	}], "template" => "consul_agent", "version" => "f34a73812d8c94d1fb194ec76b10053ba42f0b8d", "sha1" => "sha256:69f741d1c863598112f81b04b1fcadd3856284b12595edd1cd324e0354e0f157", "blobstore_id" => "bb35a2be-5307-4c4c-b732-97059d72f4f2"
}
``

**Comment by calebwashburn** [comment]
Looks as if this line might be source of different ordering.

https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/models/runtime_config.rb#L18

**Comment by dpb587-pivotal** [comment]
Interesting find (and thanks for digging into some code). This seems like it would indeed be an issue, particularly noticeable on PostgreSQL.

**Comment by dpb587-pivotal** [comment]
Also interesting is that there are multiple entries of `consul_agent` listed here. Perhaps some code is doing a `uniq` vs non-unique and seeing a difference.

**Comment by dpb587-pivotal** [comment]
I think this may have been fixed as part of [268.0.1](https://github.com/cloudfoundry/bosh/releases/tag/v268.0.1) and the [related story](https://www.pivotaltracker.com/story/show/159492735) around ensuring packages are installed in a deterministic way when there are multiple possibilities.

Can you give the new version a try and see if you're still seeing issues?

**Comment by mrosecrance** [comment]
I'm going to close this at it may be fixed. Feel free to re-open if you do still see the issue
