### ISSUE TITLE
Make it easy to always use SHA256 checksums

### ISSUE THREAD

**Issue by lisamcho** [cloudfoundry/bosh#1801]
Cloud Controller team wants to follow best practices by always adding blobs with sha2, but it doesn't look like there's an environment variable we can set, and it's very easy to forget the `--sha2` option on `bosh add-blob`. 

Feature request: we want sha2 to be the default, or else we would like an environment variable to always use it, such as `BOSH_USE_SHA2`. This would affect `bosh add-blob`, `bosh create-release`, and any other commands that accept the --sha2 option.

**Comment by dpb587-pivotal** [comment]
Closing - [v2.0.44](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.44) supports the `BOSH_SHA2` environment variable.
