### ISSUE TITLE
Data in local_dns_records referenced compilation instances (local_dns_records_instance_id_fkey)

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh#1804]
Error message from a `bosh deploy`...

    Error: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "local_dns_records_instance_id_fkey" on table "local_dns_records"

Scenario...

 * task 1 failed during compilation (director ran out of disk space) and abandoned a VM
    * I wasn't able to resolve at the time, so I manually deleted the compilation VM from the IaaS
 * I redeployed director with a larger disk (and upgraded director from 259 to 263.3)
 * I retried the originally failed deploy; compilation succeeded, but it failed to delete the ghosted compilation instance with the above error between compilation and updating instances

Analysis...

 * seems like director optimistically does not remove local dns records for compilation vms [instance_deleter.rb:29](https://github.com/cloudfoundry/bosh/blob/43f6768945428f6a84f43297f06f8d807c09b4f1/src/bosh-director/lib/bosh/director/instance_deleter.rb#L29).
 * I vaguely recall compilation vms are not sent to DNS now, but it seems like the same compilation check existed on [v259](https://github.com/cloudfoundry/bosh/blob/283792ff7354096f50763dcae9df75feefd5971d/bosh-director/lib/bosh/director/instance_deleter.rb#L29), so maybe that was old behavior, too.
 * This might just be an unlikely edge case which isn't worth worrying about; created an issue for documentation at the very least.
 * Maybe a migration script was creating records for compilation instances.

Recovery...

 * Probably not recommended, but I manually deleted the affected records with `BEGIN; DELETE FROM local_dns_records WHERE instance_id IN (SELECT id FROM instances WHERE compilation = TRUE);`

From the debug logs...

    E, [2017-10-07 04:35:08 #25221] [task:68874] ERROR -- DirectorJobRunner: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "local_dns_records_instance_id_fkey" on table "local_dns_records"
    DETAIL:  Key (id)=(589) is still referenced from table "local_dns_records".

    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `exec'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/logging.rb:39:in `log_yield'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `execute_query'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `block in execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:101:in `hold'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `execute'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/query.rb:52:in `execute_dui'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:963:in `execute_dui'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:823:in `with_sql_delete'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1806:in `_delete_without_checking'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1788:in `_delete'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1265:in `delete'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1834:in `_destroy_delete'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1821:in `block in _destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1124:in `around_destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1818:in `_destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1280:in `block (2 levels) in destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:2053:in `block in checked_transaction'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:136:in `_transaction'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:110:in `block in transaction'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:99:in `transaction'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:2053:in `checked_transaction'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1280:in `block in destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:2041:in `checked_save_failure'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:1280:in `destroy'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_deleter.rb:53:in `block in delete_instance_plan'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_deleter.rb:22:in `delete_instance_plan'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_deleter.rb:65:in `block (3 levels) in delete_instance_plans'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
    /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'

The event output looked like...

    Task 68874

    Task 68874 | 04:30:11 | Preparing deployment: Preparing deployment (00:00:01)
    Task 68874 | 04:30:13 | Preparing package compilation: Finding packages to compile (00:00:00)
    Task 68874 | 04:30:13 | Compiling packages: legacy/3fd140d44e34dea640e551aed03d4bce4a5f3b42 (00:04:45)
    Task 68874 | 04:34:58 | Deleting unneeded instances: compilation-b82783da-f7a1-4c31-b7fc-35e6e06ae79e/ad855e83-35a8-43b3-b119-0c760fe9b5ea (0) (00:00:10)
                          L Error: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "local_dns_records_instance_id_fkey" on table "local_dns_records"
    DETAIL:  Key (id)=(589) is still referenced from table "local_dns_records".

    Task 68874 | 04:35:08 | Error: PG::Error: ERROR:  update or delete on table "instances" violates foreign key constraint "local_dns_records_instance_id_fkey" on table "local_dns_records"
    DETAIL:  Key (id)=(589) is still referenced from table "local_dns_records".

    Task 68874 Started  Sat Oct  7 04:30:11 UTC 2017
    Task 68874 Finished Sat Oct  7 04:35:08 UTC 2017
    Task 68874 Duration 00:04:57
    Task 68874 error

**Comment by cppforlife** [comment]
story: https://www.pivotaltracker.com/story/show/151854582

**Comment by dpb587-pivotal** [comment]
Fixed via 1614a6b5cfed81b6e7e89bd554098dca6902e680
