### ISSUE TITLE
health_monitor failing without error message when not able to connect to UAA

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh#1806]
Deploying a director with UAA and health_monitor not being able to reach UAA will fail with non-descriptive error.

`/var/vcap/monit/monit.log` shows `[UTC Oct 10 08:32:13] error    : 'health_monitor' failed protocol test [HTTP] at INET[localhost:25923/healthz] via TCP`

This endpoint does not return in the monit timeouts so monit restarts health_monitor before it can return the real reason.

The real reason is that health_monitor cannot connect to UAA. This can be observed when starting `health_monitor_ctl start` manually:
```
E, [2017-10-10T08:37:29.520932 #3993] ERROR : Cannot get deployments from director at https://127.0.0.1:25555/deployments:
E, [2017-10-10T08:37:29.521008 #3993] ERROR : /var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/director.rb:16:in `get_deployments'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:152:in `fetch_deployments'
/var/vcap/packages/health_monitor/gem_home/ruby/2.3.0/gems/bosh-monitor-0.0.0/lib/bosh/monitor/runner.rb:99:in `block in poll_director'
I, [2017-10-10T08
E, [2017-10-10T08:38:29.524040 #3993] ERROR : Failed to obtain token from UAA: #<Net::OpenTimeout: execution expired>
```

**Comment by cppforlife** [comment]
@Kiemes dont think we can improve monits error.

**Comment by dpb587-pivotal** [comment]
Perhaps we can do a better job on redirecting the error output so it shows up in /var/vcap/sys/log/health_monitor/* rather than monit.log?

**Comment by mfine30** [comment]
Closing and re-opening to trigger a gitbot story

**Comment by geofffranks** [comment]
Ran into this today, but had no error messages anywhere to go off of. Enabling debugging and digging through health monitor code finally clued us into the fact the health monitor was connecting to the UAA. Eventually found this issue when trying to submit a new one for what we found.
