### ISSUE TITLE
Bosh::Template::Test does not support link.address

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh#1808]
When trying to write a test around our bosh template we get the following error:
```
1) Metron Agent JSON Bosh DNS is enabled uses bosh links to populate DopplerAddr and DopplerAddrWithAZ
     # Links are not supported by bosh-template
     Failure/Error: rendered = template.render(properties, spec: spec, consumes: links)

     NotImplementedError:
       link.address requires bosh director
     # /home/pivotal/.gem/ruby/2.4.2/gems/bosh-template-2.0.0/lib/bosh/template/evaluation_link.rb:45:in `address'
     # (erb):7:in `get_binding'
     # /home/pivotal/.gem/ruby/2.4.2/gems/bosh-template-2.0.0/lib/bosh/template/test/template.rb:22:in `render'
     # ./spec/metron_agent/templates/metron_agent.json.erb_spec.rb:227:in `render_template'
     # ./spec/metron_agent/templates/metron_agent.json.erb_spec.rb:215:in `block (3 levels) in <top (required)>'
```

We are seeing this when using the new link property `address`:
```
link("doppler").address(azs: [spec.az])
```

**Comment by dpb587-pivotal** [comment]
Agreed, perhaps we can implement some fake value generator. Typically it's a very derived value from the director, but we could probably approximate it for tests.

Would you expect to be able to test that `spec.az` was actually embedded into the returned address? That will diverge from actual director behavior and DNS name generation, but would retain testability.

**Comment by apoydence** [comment]
@dpb587-pivotal I don't think we have an opinion `spec.az` being embedded.

**Comment by jfmyers9** [comment]
Going to close and reopen this issue to create a tracker story.
