### ISSUE TITLE
Tail errand logs

### ISSUE THREAD

**Issue by glyn** [cloudfoundry/bosh#1811]
For errands which take more than a few seconds to complete, it would be very helpful to be able to stream the logs.

**Comment by cppforlife** [comment]
@glyn would you be ok if it would be streamed with a delay, eg every 10s?

**Comment by glyn** [comment]
@cppforlife Yes, that would be fine. Thanks.

**Comment by mfine30** [comment]
Hey @glyn, adding first class support to `bosh run-errand <ERRAND>` so that it immediately streams logs is not something that we are likely to get to in the short term. 

That being said, there is an alternative flow you could try:

### In Shell 1
```
$ bosh run-errand <ERRAND>
```

### In Shell 2
```
$ bosh logs -f <ERRAND-JOB>/0
```
