### ISSUE TITLE
Installing opsmanager manually 

### ISSUE THREAD

**Issue by Jagarnath123** [cloudfoundry/bosh#1814]
Please review my logs . I am not able to deploy opsmanager .

===== 2017-10-21 11:46:59 UTC Running "bosh2 --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'

Started validating
  Validating release 'bosh-google-cpi'... Finished (00:00:03)
  Validating release 'uaa'... Finished (00:00:01)
  Validating release 'credhub'... Finished (00:00:01)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:08)

Started installing CPI
  Compiling package 'golang/b1d1bd861b0fc14b92e2a88fed01de017037f242'... Finished (00:00:00)
  Compiling package 'bosh-google-cpi/cfef428d33a02305b52fad4345fd817b7a545128'... Finished (00:00:00)
  Installing packages... Finished (00:00:06)
  Rendering job templates... Finished (00:00:02)
  Installing job 'google_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:10)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-google-kvm-ubuntu-trusty-go_agent/3445.11'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'vm-e9fdde35-b57e-4733-4f58-a6643346faed'... Failed (00:00:30)

**Comment by Jagarnath123** [comment]
===== 2017-10-21 11:46:59 UTC Running "bosh2 --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'

Started validating
  Validating release 'bosh-google-cpi'... Finished (00:00:03)
  Validating release 'uaa'... Finished (00:00:01)
  Validating release 'credhub'... Finished (00:00:01)
  Validating release 'os-conf'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:08)

Started installing CPI
  Compiling package 'golang/b1d1bd861b0fc14b92e2a88fed01de017037f242'... Finished (00:00:00)
  Compiling package 'bosh-google-cpi/cfef428d33a02305b52fad4345fd817b7a545128'... Finished (00:00:00)
  Installing packages... Finished (00:00:06)
  Rendering job templates... Finished (00:00:02)
  Installing job 'google_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:10)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-google-kvm-ubuntu-trusty-go_agent/3445.11'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM 'vm-e9fdde35-b57e-4733-4f58-a6643346faed'... Failed (00:00:30)
  Deleting VM 'vm-e9fdde35-b57e-4733-4f58-a6643346faed'... Finished (00:02:48)
  Creating VM for instance 'bosh/0' from stemcell 'stemcell-69f3690e-0260-4abf-7452-7a817a934696'... Finished (00:00:43)


Please assist me how to fix the above issue.  I am trying to install OPSmanager in GCP.

**Comment by cppforlife** [comment]
@Jagarnath123 please reach our to pivotal support for help with ospmgr.
