### ISSUE TITLE
create-release fails with the latest repo. ruby2.4 packaging and spec file is missing?

### ISSUE THREAD

**Issue by parthasarathi204** [cloudfoundry/bosh#1816]
bosh create-release --force --tarball /tmp/bosh.tgz
-----------------------------------------------
Blob download 'verify-multidigest/verify-multidigest-0.0.29-linux-amd64' (id: e5925f0e-d420-4759-4c4e-9b964183efc1) finished

Building a release from directory '/home/ubuntu/partha/bosh':
  - Constructing packages from directory:
      - Reading package from '/home/ubuntu/partha/bosh/packages/ruby-2.4':
          Collecting package files:
            Reading package spec '/home/ubuntu/partha/bosh/packages/ruby-2.4/spec':
              Opening file /home/ubuntu/partha/bosh/packages/ruby-2.4/spec:
                open /home/ubuntu/partha/bosh/packages/ruby-2.4/spec: no such file or directory
      - Expected to find package 'ruby-2.4' since it's a dependency of package 'director'
      - Expected to find package 'ruby-2.4' since it's a dependency of package 'health_monitor'
      - Expected to find package 'ruby-2.4' since it's a dependency of package 'registry'
  - Constructing jobs from manifest:
      - Expected to find package 'nginx' since it's a dependency of job 'blobstore'
      - Expected to find package 'director' since it's a dependency of job 'director'
      - Expected to find package 'health_monitor' since it's a dependency of job 'health_monitor'
      - Expected to find package 'gonats' since it's a dependency of job 'nats'
      - Expected to find package 'postgres' since it's a dependency of job 'postgres-9.4'
      - Expected to find package 'powerdns' since it's a dependency of job 'powerdns'
      - Expected to find package 'registry' since it's a dependency of job 'registry'

Exit code 1
------------------------------------

**Comment by friegger** [comment]
BOSH now uses [package vendoring](https://bosh.io/docs/package-vendoring.html). The vendored ruby package should be automatically resolved by a bosh-cli version v2.0.36 or higher.
