### ISSUE TITLE
trying to upload stemcell fails

### ISSUE THREAD

**Issue by csaunders-pivotal** [cloudfoundry/bosh#1817]
The hostname it is referencing is the hostname of my esxi host. Not sure why it needs that vs vcenter, regardless I can browse to that site without 443. 

$ bosh -e bosh-1 upload-stemcell /Users/xxxxx/downloads/bosh-stemcell-3468-vsphere-esxi-ubuntu-trusty-go_agent.tgz
Using environment '10.193.54.200' as client 'admin'

######################################################## 100.00% 1.88 MB/s 3m38s
Task 6

Task 6 | 13:46:20 | Update stemcell: Extracting stemcell archive (00:00:04)
Task 6 | 13:46:24 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 6 | 13:46:26 | Update stemcell: Checking if this stemcell already exists (00:00:00)
Task 6 | 13:46:26 | Update stemcell: Uploading stemcell bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468 to the cloud (00:00:08)
                   L Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxi:443)' in 'create_stemcell' CPI method
Task 6 | 13:46:34 | Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esxi:443)' in 'create_stemcell' CPI method

Task 6 Started  Mon Oct 23 13:46:20 UTC 2017
Task 6 Finished Mon Oct 23 13:46:34 UTC 2017
Task 6 Duration 00:00:14
Task 6 error

Uploading stemcell file:
  Expected task '6' to succeed but state is 'error'

Exit code 1

**Comment by jleavers** [comment]
Bosh will need to resolve the hostname of your ESXi host (and connect to it directly) - you can pass in DNS servers with your `create-env`, e.g.

```
bosh create-env bosh-deployment/bosh.yml \
    -o bosh-deployment/misc/dns.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v internal_dns=[x.x.x.x,x.x.x.x] \
    etc.
```
