### ISSUE TITLE
[Feature Request/Bug?] bosh recreate -n <non-existent-instance-group> should give the user an error instead of doing nothing.

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry/bosh#1818]
Hi:

I try to use `bosh recreate -n diego-cell` in a script to recreate all the diego cells, it runs without an error (exit 0) but doing nothing.

It turns out the Ops manager is using `diego_cell` as instance group name instead of `diego-cell` like cf-deployment, and bosh just ignore it since instance group `diego-cell` doesn't exist.

I think it would make the user experience better if bosh gives an error like `instance group diego-cell doesn't exist` and exit with an error, instead of just running successfully and returns 0, so that way the user can know something goes wrong and fix the error in their script.

Thoughts?

Regards
Kai

**Comment by dpb587-pivotal** [comment]
Agreed for improved UX. If a hard error is undesired, could emit a warning as part of the task output. Something along the lines of "No instances matched the requested filter".

**Comment by mrosecrance** [comment]
Closing and reopening for story
