### ISSUE TITLE
creating stemcell timedout

### ISSUE THREAD

**Issue by manojRy** [cloudfoundry/bosh#1820]
Hello, 
I have been trying to create a bosh directory on openstack. I am having a manifest file and I tried to deploy it and ended up with an error while creating the stemcell.
<img width="945" alt="stem" src="https://user-images.githubusercontent.com/16360625/31997480-6844bc80-b98c-11e7-8e70-548658f8acb1.PNG">

P:S: I can see the stemcell or partially created stem cell under private images in the cloud.
Thanks

**Comment by dpb587-pivotal** [comment]
I believe this can happen if your OpenStack environment is slower than typical. You may want to try increasing the [`openstack.state_timeout`](http://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry-incubator/bosh-openstack-cpi-release&version=35#p=openstack.state_timeout) property of your director.

**Comment by manojRy** [comment]
thanks @dpb587-pivotal I had something similar in my .yml file before but I have also tried with your property but still, I have the similar error.
<img width="329" alt="timeout" src="https://user-images.githubusercontent.com/16360625/32096293-4eec9ba6-bb06-11e7-9372-3bb7bc49d260.PNG">
Also, I have tried to modify code in openstack.rb file but I got to know that while compiling it would change the parameters back to the actual state i.e., 300. Anyother way I could accomplish this?

**Comment by dpb587-pivotal** [comment]
Looks like the `state_timeout` was placed at the wrong level. It should be a sibling of `default_security_groups` (not a child of `connection_options`). For example...

    openstack:
      default_security_groups: [default]
      state_timeout: 3600
      wait_resource_poll_interval: 15
      connection_options:
        ssl_verify_peer: false
        connect_timeout: 60
    ...
