### ISSUE TITLE
 CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"cannot load such file -- openssl"

### ISSUE THREAD

**Issue by jiaoyan2017** [cloudfoundry/bosh#1826]
I need to set up concourse cluster with BOSH. So I followed https://bosh.io/docs/init-aws.html.
[root@ip-172-31-20-93 bosh-1]# bosh create-env bosh-deployment/bosh.yml \\
    --state=state.json \\
    --vars-store=creds.yml \\
    -o bosh-deployment/aws/cpi.yml \\
    -v director_name=bosh-1 \\
    -v internal_cidr=172.31.16.0/20 \\
    -v internal_gw=172.31.16.1 \\
    -v internal_ip=172.31.28.222 \\
    -v access_key_id=mykey \\
    -v secret_access_key=mysecret \\
    -v region=ap-southeast-1 \\
    -v az=ap-southeast-1b \\
    -v default_key_name=bosh \\
    -v default_security_groups=[bosh] \\
    --var-file private_key=~/bosh.pem \\
    -v subnet_id=subnet-8593a9ec
Deployment manifest: '/root/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/8fdc24f9ef724e7ea5204464eb64803ca851a97a'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'aws_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:00)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3468.1'... Failed (00:00:00)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3468.1):
  **CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"cannot load such file -- openssl","ok_to_retry":false}**

Exit code 1

But openssl is installed in my instance.
[root@ip-172-31-20-93 bosh-1]# rpm -qa | grep openssl
openssl-devel-1.0.2k-8.105.amzn1.x86_64
openssl-1.0.2k-8.105.amzn1.x86_64

I have no idea of which openssl BOSH wants.

**Comment by cppforlife** [comment]
@jiaoyan2017 did you end up installing deps from https://bosh.io/docs/cli-env-deps?

**Comment by jiaoyan2017** [comment]
@cppforlife yes, I did.
[root@ip-172-31-20-93 ~]# history | grep yajl-ruby
   97  gem install yajl-ruby
  182  history | grep yajl-ruby
[root@ip-172-31-20-93 ~]# history | grep "yum install gcc gcc-c++ ruby"         
   96  yum install gcc gcc-c++ ruby ruby-devel mysql-devel postgresql-devel postgresql-libs sqlite-devel libxslt-devel libxml2-devel patch openssl
  183  history | grep "yum install gcc gcc-c++ ruby"

**Comment by xyloman** [comment]
On a new Ubuntu 16.04 (ami-1ee65166) spun up on AWS.  Installed the dependencies ```sudo apt-get install -y build-essential zlibc zlib1g-dev ruby ruby-dev openssl libxslt-dev libxml2-dev libssl-dev libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3``` and received the following error ```creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3468.13):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"cannot load such file -- openssl","ok_to_retry":false}``` However, when I leverage a Ubuntu 14.04 (ami-0c9f2974) I am able to successfully perform the bosh create-env such as https://github.com/cloudfoundry/bosh-deployment/ ```bosh create-env /tmp/bosh-deployment/bosh.yml \
    --state=bosh-state.json \
    --vars-store=bosh-creds.yml \
    -o /tmp/bosh-deployment/aws/cpi.yml \
    -o /tmp/bosh-deployment/aws/iam-instance-profile.yml \
    -o /tmp/bosh-deployment/uaa.yml \
    -o /tmp/bosh-deployment/credhub.yml \
    -o /tmp/bosh-deployment/jumpbox-user.yml \
    -v iam_instance_profile=${iam_instance_profile} \
    -v access_key_id=${access_key_id} \
    -v secret_access_key=${secret_access_key} \
    -v director_name=bosh \
    -v internal_cidr=${internal_cidr} \
    -v internal_gw=${internal_gw} \
    -v internal_ip=${internal_ip} \
    -v region=${region} \
    -v az=${az} \
    -v default_key_name=${default_key_name} \
    -v default_security_groups=[${default_security_groups}] \
    --var-file private_key=bosh.pem \
    -v subnet_id=${subnet_id} \
    -v credhub_encryption_password=${credhub_encryption_password}```

**Comment by dpb587-pivotal** [comment]
That is curious. Have you figured anything else out since?

If you run that command with the environment variable `BOSH_LOG_LEVEL=debug`, can you provide the stacktrace which should be present near that error? Please don't post the whole log since it contains sensitive information; just the stacktrace which will probably be near `cannot load such file`.

**Comment by eljuanchosf** [comment]
Hey guys! I think is some sort of ncompatibility between Ruby 2.3.x and the OpenSSL version in Ubuntu 16.04. I suffered this condition and tried Ruby 2.2 and it worked.

**Comment by saedalav** [comment]
It's not an incompatibility, but rather the fact that openssl-devel (or equivalent in apt-get) needs to be installed before ruby is installed. Either remove ruby, install openssl-devel, and reinstall ruby, or follow documentaion on how to resolve this issue without having to remove ruby.

**Comment by dpb587-pivotal** [comment]
Closing - sounds like it's a local dependency issue. If someone has more-correct information that will help others who run into this, please feel free to send a pull request to the [additional dependencies](https://bosh.io/docs/cli-v2-install/#additional-dependencies) docs.
