### ISSUE TITLE
director call set_vm_metadata failed to IaaS character limits

### ISSUE THREAD

**Issue by EdwardStudy** [cloudfoundry/bosh#1829]
When director generates tags of instances such as `{"method":"set_vm_metadata","arguments":["43787091",{"director":"ed-demo-director","deployment":"my-redis-deployment","id":"899a9411-a08b-4d31-8dc6-cb2712c608dc","job":"redis-master","index":"0","name":"redis-master/899a9411-a08b-4d31-8dc6-cb2712c608dc","created_at":"2017-11-09T07:19:43Z"}],"context":{"director_uuid":"000b04f8-b55a-4503-a853-04bde9db1914","request_id":"367037"}}`. These tags are generated by the director. But I think it is should more considering limits of IaaS. 

For example, the SoftLayer would return error response:  `{"error":"Invalid value provided for 'tags'. Invalid tag names: name: redis-master\/899a9411-a08b-4d31-8dc6-cb2712c608dc.","code":"SoftLayer_Exception_InvalidValue"}`. It is that the character '/' cause the error. But I don't know if other IaaS have limts. 

Please consider this situation.
Thank you.

**Comment by cppforlife** [comment]
@EdwardStudy i would open this issue against softlayer cpi repo (https://github.com/cloudfoundry/bosh-softlayer-cpi-release). since this is a softlayer specific limit, cpi should make sure that values set are truncated. (may be also include `...` if it's truncated). google cpi i believe does something similar.

**Comment by EdwardStudy** [comment]
@cppforlife Thank you. I asked about the limitations of the SoftLayer tags. The characters of tags string permitted are A-Z, 0-9, whitespace, _ (underscore), - (hypen), . (period), and : (colon), therefore It is not able to use tag names with other characters than the permitted. We are developing CPI so I do not think you need to open an issue again. If the truncation is taken into account, I think that we should improve the softlayer cpi.

Best regard.
