### ISSUE TITLE
As a bosh user, I'd like to filter addon installation based on the type of a VM: errand, service, compilation

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1833]
Some addons shouldn't be installed on certain types of VMs or should only be installed on certain types. So, in my runtime config and manifest filter for addon installation, I'd like to do this based on a VM's type. Types I'd like to distinguish: errand, service, compilation. Wdyt?

**Comment by pivotal-jamil-shamy** [comment]
@voelzmo interesting idea
One comment though: Maybe it can be renamed to be filter by instance type rather than VM type, so that it will not be mistaken for VM types defined in the cloud config(s), wdyt ?

**Comment by dpb587-pivotal** [comment]
Related: https://github.com/cloudfoundry/bosh/issues/1613

@voelzmo do you have an example of a release type which should be installed on compilation vms?

**Comment by cppforlife** [comment]
@voelzmo can you please add examples of each type of colocation you have in mind?

**Comment by voelzmo** [comment]
Ah, sorry, I completely missed this, thanks for the reminder.

* compilation VMs:
  * e.g. Virus scan. I only want virus scanning for sources and their dependencies, don't need Virus scanning during runtime (be is long-lived service or short-lived errands)
  * I'm also thinking about some license or CVE scan that could enforce that nobody installs stuff that doesn't match company policy. There are also other means to achieve this, if you e.g. limit the location from which you can install bosh-releases (i.e. only company-vetted releases are available)
* Service VMs: 
  * Something like Turbulence or log-forwarding agents. I don't need those (or in a very different configuration) for compilation VMs or errands
* Errand VMs:
  * Not sure what those VMs specifically need. It seems to me, that they would *not* need most of the stuff I'd like to install on the other two types of VMs.

**Comment by voelzmo** [comment]
@cppforlife @dpb587-pivotal opinions about the use-cases?

**Comment by dpb587-pivotal** [comment]
The include-compilation use cases sound a bit weird - both of those use cases sound racy to me. There's no guarantee the addons may have finished scanning by the time compilation was finished. For completeness though, I think it might make sense regardless.

**Comment by voelzmo** [comment]
Ah, good point. I guess you’d also come up with cases where you want to exclude those scanning tools from compilation VMs then.

I guess what I was looking for with the compilation cases above was something similar to multi buildpacks where I can include some scanning tool before my actual code is compiled. Thanks for the race condition reminder.

On 21. Dec 2017, at 07:49, Danny Berger <notifications@github.com<mailto:notifications@github.com>> wrote:


The include-compilation use cases sound a bit weird - both of those use cases sound racy to me. There's no guarantee the addons may have finished scanning by the time compilation was finished. For completeness though, I think it might make sense regardless.

**Comment by cppforlife** [comment]
story to address errands at least: https://www.pivotaltracker.com/story/show/155197799

**Comment by dpb587-pivotal** [comment]
Pull request for lifecycle filtering: https://github.com/cloudfoundry/bosh/pull/1902

**Comment by voelzmo** [comment]
Awesome, thanks!

**Comment by jfmyers9** [comment]
This has been implemented as of https://github.com/cloudfoundry/bosh/pull/1902
