### ISSUE TITLE
As a dev of CPI, I want to know if we have considered the SPOF of bosh-registry.

### ISSUE THREAD

**Issue by EdwardStudy** [cloudfoundry/bosh#1834]
Hi, I am a dev of CPI. And we stored instance's settings in every VM not bosh-registry for the convenience in the past. And we want to switch bosh-registry for some reasons. I noticed that bosh-registry is deployed in director and thers is a risk of SPOF if registry/director crush. 

My question is that if we have considered the SPOF of bosh-registry, or did we have some best practices with bosh-registry.

**Comment by pivotal-jamil-shamy** [comment]
@EdwardStudy there is a plan to remove the registry all together from BOSH architecture. We're going to start that work soon, so I would not worry too much about the registry SPOF for now.

**Comment by EdwardStudy** [comment]
@pivotal-jamil-shamy Thank you. I saw https://github.com/cloudfoundry/bosh-notes/blob/master/registry-removal.md in bosh-notes.

**Comment by cppforlife** [comment]
> I want to know if we have considered the SPOF of bosh-registry

it's equivalent to the director today since it's on the same machine.

we will be removing it shortly to simplify overall architecture.
