### ISSUE TITLE
Extend rogue agent logs/events with VM id

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1837]
Rogue agent events/logs need the VM id. In case of a rogue agent the VM should most probably be killed. It's very hard at the moment to figure out the VM of the rogue agent.

**Comment by voelzmo** [comment]
possible solution: could heartbeats contain the CID of the VM and the HM could also contain it in the alert? Currently, it is really hard to figure this out youself.

**Comment by cppforlife** [comment]
only thing that we can really trust from the agent is agent id. all other
info should be pulled in from the director if necessary so that it's coming
from an authoritative source.

**Comment by voelzmo** [comment]
@cppforlife so how would you propose to find out the VM to a rogue agent? All this is about is making that process easier somehow.

**Comment by mfine30** [comment]
Hey @beyhan @voelzmo is this an issue you're still interested in discussing?

**Comment by voelzmo** [comment]
Yes, we're still interested in making it easier to follow-up on `rogue agent` alerts for operators or automation.
