### ISSUE TITLE
BOSH HM floods Director with `alert` events when /deployments is slow

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1838]
**Symptoms**
The BOSH HM was posting alerts about found rogue agents with a frequency of ~1800 events/second to `/events` on the Director. When digging into the BOSH database of deployments, instances, and vms, we found that the agents from those 1800 events were actually well registered for existing deployments and all was okay with them.

**Analysis**
When you have enough deployments (e.g. ~500), the `/deployments` endpoint can become pretty slow (some improvements done in v264.2, see https://github.com/cloudfoundry/bosh/pull/1793 and https://github.com/cloudfoundry/bosh/commit/391e66347870f782964aac7cc5a7e63576b638c3), answering in the order of tens of seconds, rather than 1/10th of a second. This means, on each run of [`analyze_agents`](https://github.com/cloudfoundry/bosh/blob/2ee2b73d7238666185dc61545337d27ec81058be/src/bosh-monitor/lib/bosh/monitor/instance_manager.rb#L98) the HM operates with information from the director which is outdated – the longer the `/deployments` endpoint takes to answer, the worse the situation gets.
In a situation with a high amount of churn, e.g. a stemcell update on several deployments at once, all of the newly started VMs will be considered as rogue agents, leading to even more events being `POST`ed, leading to even higher response times for `/deployments`. Once deployments are finished, this situation resolves itself after a few hours, such that no agents are reported as rogue anymore and the HM doesn't send any events to the Director.

**Mitigations**
* Set the [`rogue_agent_alert`](http://bosh.io/jobs/health_monitor?source=github.com/cloudfoundry/bosh&version=264.2.0#p=hm.intervals.rogue_agent_alert) to some incredibly high number, such that no events are posted to the Director, even if the HM only has outdated information about deployments and instances. 

**Identified Issues**
* It is dangerous when the HM operates with old information from the Director. If for some reason the list of deployments and instances don't contain recent information, it would probably be better to not send events or `scan_and_fix` tasks to the Director?
* Posting many events slows down other synchronous calls, such as `GET /deployments`. It may seem obvious, but not sure how to deal with this finding.
* Rogue agent events don't seem to be very useful, as it is hard to turn them into actionable knowledge, see https://github.com/cloudfoundry/bosh/issues/1837

**Comment by voelzmo** [comment]
@dpb587-pivotal @cppforlife thoughts?

**Comment by cppforlife** [comment]
@voelzmo is this going to be resolved (or improved) thru puma and other perf stories yall been doing?

**Comment by voelzmo** [comment]
our performance improvements work towards making `/deployments` faster, thus and issue like this more unlikely, yes. Switching to puma certainly helps in terms of being able to process more requests.

The underlying issue here, which potentially needs to be tackled in the HM, isn't touched by anything we do.
