### ISSUE TITLE
Director whose CPI config is erased should resume using built-in CPI

### ISSUE THREAD

**Issue by jraqula** [cloudfoundry/bosh#1839]
We deployed a director (264.1) with aws_cpi configured and working, then incorrectly added a CPI config. We can recover from this by uploading a new CPI config that matches the original config, but we would much prefer to be able to simply delete or upload-empty and see our original deploys resume working as they had before.

cc @jaresty

**Comment by voelzmo** [comment]
does `bosh delete-config cpi --name=<config_name>` work for you? This should be possible with bosh >=264 to get rid of all kinds of configuration now.

**Comment by jraqula** [comment]
@voelzmo yep, that'll do -- missed that gem. Thanks!
