### ISSUE TITLE
Downloading of remote stemcells / releases does not use proxy that requires authentication.

### ISSUE THREAD

**Issue by haydonryan** [cloudfoundry/bosh#1842]
Working with a customer who has a large deployment that is behind a proxy server that uses a username and password.  

From the Cloud Foundry slack: 

eve: we defer to the builtin ruby proxy-from-environment logic in our codebase, which intentially does not support loading proxy credentials from the URI. as we don't additionally implement a different way to get the credentials into the bosh director, it looks like authentication-requiring proxies are not supported at this time.

It would be really good to support this so that we could enable remote download of releases/stemcells through an authenticated proxy.

**Comment by cppforlife** [comment]
i could see adding property `env.http_proxy_?` to pass in creds.

**Comment by rkoster** [comment]
would be nice if we could just parse `env.http(s)_proxy` and dynamically set username/password:
```
2.2.3 :005 > uri = URI("https://foo:bar@example.com:8080")
 => #<URI::HTTPS https://foo:bar@example.com:8080>
2.2.3 :006 > uri.user
 => "foo"
2.2.3 :007 > uri.password
 => "bar"
```

This would be more consistent with other bosh releases. For example this already works with concourse.

My personal reason for wanting concourse and bosh to behave the same way with regard to proxy's is the [`--proxy`](https://github.com/starkandwayne/bucc/blob/develop/ops/flags/proxy.yml) flag in bucc.

**Comment by mfine30** [comment]
Closing and re-opening to trigger gitbot story
