### ISSUE TITLE
BOSH uses depreciated Postgres calls

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh#1844]
Bosh director logs using Postgres will show:

```
Called from /var/vcap/packages/director/gem_home/ruby/2.4.0/gems/sequel-4.36.0/lib/sequel/database/connecting.rb:98:in `require'
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
```

**Comment by cppforlife** [comment]
@sharms is this off of master? i think someone was workign on fixing up all of these. cc @pivotal-jamil-shamy @dpb587-pivotal

**Comment by dpb587-pivotal** [comment]
It looks like this is fixed as part of https://github.com/cloudfoundry/bosh/commit/94aef202511d9f351709cefcee80f1110f03443c, and it will probably be released in v266+.

**Comment by voelzmo** [comment]
@dpb587-pivotal the commit you linked is changing migrations with timestamps from 2017. Are you sure that's a thing we can do?

**Comment by mfine30** [comment]
Seems like this was fixed in 266+ which was released several months ago. Closing
