### ISSUE TITLE
Running into Bosh Deployment issues - failing on templates

### ISSUE THREAD

**Issue by jhedman2** [cloudfoundry/bosh#1845]
Looking for any help, very much appreciated.

Working on a completely new deployment using version 264.3.0 using the vsphere CPI.  It's properly deploying the template and director VM, but failing after the VM is working properly and connected.  During the deploy phase, here are the errors i'm getting.

Started deploying
  Waiting for the agent on VM 'vm-fe5e9a6d-6d7d-4f82-9cf9-a1876d34d9ae'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Unmounting disk 'disk-a063a8ba-d30c-45b3-8d8e-f9b2ab31ef33'... Finished (00:00:01)
  Deleting VM 'vm-fe5e9a6d-6d7d-4f82-9cf9-a1876d34d9ae'... Finished (00:00:11)
  Creating VM for instance 'bosh/0' from stemcell 'sc-b02e8f5b-a6f9-4118-a139-ddb0c0b660aa'... Finished (00:00:10)
  Waiting for the agent on VM 'vm-3181a2b5-5f8f-4088-8597-daad4bd3e0b4' to be ready... Finished (00:00:28)
  Attaching disk 'disk-a063a8ba-d30c-45b3-8d8e-f9b2ab31ef33' to VM 'vm-3181a2b5-5f8f-4088-8597-daad4bd3e0b4'... Finished (00:00:18)
  Rendering job templates... Failed (00:00:00)
Failed deploying (00:01:17)

Command 'deploy' failed:
  Deploying:
    Building state for instance 'bosh/0':
      Rendering job templates for instance 'bosh/0':
        Rendering templates for job 'nats/ff834d1313884d71dd4b44e80e75d62ce3b0fd92':
          Rendering template src: nats_client_ca.pem.erb, dst: config/nats_client_ca.pem:
            Rendering template src: /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/bosh-init-release139701585/extracted_jobs/nats/templates/nats_client_ca.pem.erb, dst: /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/rendered-jobs363797514/config/nats_client_ca.pem:
              Running ruby to render templates:
                Running command: 'ruby /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/erb-renderer563962555/erb-render.rb /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/erb-renderer563962555/erb-context.json /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/bosh-init-release139701585/extracted_jobs/nats/templates/nats_client_ca.pem.erb /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/rendered-jobs363797514/config/nats_client_ca.pem', stdout: '', stderr: '/home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/erb-renderer563962555/erb-render.rb:189:in `rescue in render': Error filling in template '/home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/bosh-init-release139701585/extracted_jobs/nats/templates/nats_client_ca.pem.erb' for nats/0 (line 1: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'nats.tls.ca'>) (RuntimeError)
        from /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/erb-renderer563962555/erb-render.rb:175:in `render'
        from /home/jaredh/.bosh_init/installations/f08e4ff2-ed98-401c-536e-4f9e269b042a/tmp/erb-renderer563962555/erb-render.rb:200:in `<main>'

Looks to me like it's a certificate issue, specifically the self signed cert may not be working properly for the NATS service/template?

Thanks again.

**Comment by cppforlife** [comment]
> TemplateEvaluationContext::UnknownProperty: Can't find property 'nats.tls.ca'

bosh expects several tls certificates to start. please use https://github.com/cloudfoundry/bosh-deployment to start up your director. it will generate necessary configuration.

**Comment by jhedman2** [comment]
Thank you, i'm learning as i go, so i appreciate the response!
