### ISSUE TITLE
Duplicate `scan and fix` tasks for the same issue 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1846]
**Symptoms**
Many `scan and fix` tasks for the same deployment in the BOSH director queue.

**Analysis**
The BOSH director is busy with other tasks and is not able to process the `scan and fix` tasks. In this case the Health Monitor will generate alerts depending on the `analyze_*` interval and this will trigger `scan and fix` tasks generated by the resurrector. The `scan and fix` tasks get faster generated by the Health Monitor than they get executed by the BOSH director.

**Mitigations**
Reconfigure the `analyze_*` interval.

**Identified Issues**
Director is under load and the duplicated `scan and fix` tasks add additional load. 

**Possible Solution**
Director is able to identify duplicate tasks and doesn't add them to the queue. This could be just a solution for `scan and fix` tasks or a general solution for all tasks.

**Comment by jfmyers9** [comment]
I'm going to close this issue and reopen it to generate a tracker story.

This does not appear to be an immediate priority for the BOSH team to fix, but it is something that we would be open to accepting contributions for.

**Comment by voelzmo** [comment]
@jfmyers9 Are you saying the way that @beyhan proposed above would be the one you'd like to see a contribution for?
> Possible Solution: Director is able to identify duplicate tasks and doesn't add them to the queue. This could be just a solution for scan and fix tasks or a general solution for all tasks.

If so: should this be a generic mechanism for all kinds of tasks or just scoped towards `scan_and_fix`?

**Comment by h4xnoodle** [comment]
Ideally any 'problems' for a deployment are collapsed into one scan & fix, given we lock the entire deployment, and we can potentially fix all problems at once in a deployment. 

Would another mitigation here have been to increase the director resources? It's unclear to me whether the director was under an abnormal amount of stress for the amount of deployments compared with VM allocation, or normal load.

**Comment by beyhan** [comment]
May wish was to fix/reduce the duplicate `san and fix` tasks. Nothing general for director. I'm actually OK with the resurrection improvements https://github.com/cloudfoundry/bosh/pull/2144, which will reduce the duplicate `san and fix` tasks a lot. I'm going to close this and will reopened it in case we still observe issue with the new approach.
