### ISSUE TITLE
Over-provisioning during deployment

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh#1860]
We were recently discussing migrating user workloads during an upgrade deployment of [CFCR][kubo-release]. If a user is close to being fully utilized (for instance having enough pods to fill 4.5 out of 5 worker nodes), even if `max_in_flight` is set to `1`, there is still potential downtime with a single instance being out of service.

To do this without losing capacity I believe you would have to:

1. Increase the `instances` count to over-provision. This value should be `current_instances + max_in_flight`.
2. Do the upgrade deploy.
3. Decrease `instances` to the original amount.

Doing three deploys is tedious and can lead to error. I don't know if there is any interest in making this workflow better.

The way [k8s handles this][k8s-rolling-update] is they have `maxSurge` and `maxUnavailable` settings. `maxUnavailable` sets a floor to prevent available capacity from going too low. For our situation this could be set to `0` to prevent any loss of capacity. `maxSurge` allows for over-provisioning. New instances are brought up to start handling workloads. Once these instances are up old instances can then be brought down.

It would be awesome if bosh supported this strategy for rollout.

[kubo-release]: https://github.com/cloudfoundry-incubator/kubo-release
[k8s-rolling-update]: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment

**Comment by pivotal-jamil-shamy** [comment]
There is a track of work currently in progress that is somehow related but not quite the same. We would be interested in any feedback.

https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/update-strategy-create.md

cc @GarfieldIsAPhilosopher @monkeyherder
________________________________

**Comment by jasonkeene** [comment]
The create strategy would work for us if the old instances get deleted after the deploy is finished. That said, I imagine creating and deleting all these VMs will take considerable time over simply shipping new bits to existing VMs and rolling them.

**Comment by cppforlife** [comment]
> The create strategy would work for us if the old instances get deleted after the deploy is finished.

i dont think above strategy will work since vms that are being replaced are not added temporarily to available resources. (ie only 1 active vm per each instance). 

i think this would be a nice additional strategy to support though.

@monkeyherder @GarfieldIsAPhilosopher while you are on the current track, i think it would be interesting to discuss briefly how would this other strategy affect things (if at all).

**Comment by cppforlife** [comment]
(added to bosh notes: https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/update-strategy-surge.md)

**Comment by jfmyers9** [comment]
This is something that we are unlikely to fix in the near future. Even with the changes to the update strategy, this would still stop an instances work loads before starting them on other instances.

Our current recommendation would be for users to manually plan for these situations in their instance counts of a cluster.
