### ISSUE TITLE
Confusing "dns disabled" in "bosh env"

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [cloudfoundry/bosh#1862]
When a user turns on the new BOSH DNS feature through `bosh-deployment/local-dns.yml`, `bosh env` shows `dns: disabled`.

Although `dns: disabled` shows the status of powerDNS, it is confusing to the user who does not know that hidden detail.

One option could be to explicitly state `PowerDNS: disabled` in `bosh env` output.

**Comment by dpb587-pivotal** [comment]
I agree, this is confusing. This has come up a few times on Slack.

**Comment by dpb587-pivotal** [comment]
Recent confusions...

🔗 [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1525215421000171)

 > interestingly enough our bosh director has `local_dns: true` yet `bosh env` reports dns is disabled

🔗 [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1526401826000002)

 > and when I check the env, it says dns is disabled even though i thought the dns was supposed to be enabled by default now.

:link: [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1522110968000150)

 > `bosh env` still reports DNS as disabled, and I'm unable to resolve routes within CF

**Comment by mfine30** [comment]
Closing and re-opening for gitbot story creation

**Comment by voelzmo** [comment]
This is my Director's `bosh env` output, which shows now that `local_dns: enabled` and `power_dns: disabled`

```
$ bosh env
Using environment '10.0.1.10' as client 'admin'

Name               bosh
UUID               70332b59-24b0-4a11-95b2-1cc0ed83c240
Version            268.4.0 (00000000)
Director Stemcell  ubuntu-xenial/170.9
CPI                openstack_cpi
Features           compiled_package_cache: disabled
                   config_server: enabled
                   local_dns: enabled
                   power_dns: disabled
                   snapshots: disabled
User               admin

Succeeded
```
