### ISSUE TITLE
Bosh director is giving an error "Unknown CPI error 'Unknown' with message 'undefined method `length' for nil:NilClass' in 'create_vm' CPI method"

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry/bosh#1864]
Hi,
We are deploying Mysql with following release.
Mysql version 32 - https://github.com/cloudfoundry/cf-mysql-release/tree/master/

But while deploying only proxy_z1 is failing ,rest all vms are running fine 
Bosh director is giving error : DirectorJobRunner: error creating vm: Unknown CPI error 'Unknown' with message 'undefined method `length' for nil:NilClass' in 'create_vm' CPI method 
for proxy_z1 VM while deploying Mysql.

Stemcell Name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
               Version: '3421.4'

we are getting following log :-
I, [2017-12-18 11:15:22 #16242] [task:8646654]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2017-12-18 11:15:22 #16242] [task:8646654] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"3345ec16-e81c-4b13-b805-371fdf2a6061","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'oscf-mysql' against Director 'f0b719ad-022f-4457-aa57-a18e3b488fe3': #<Bosh::Clouds::ExternalCpi::UnknownError: Unknown CPI error 'Unknown' with message 'undefined method `length' for nil:NilClass' in 'create_vm' CPI method>","created_at":1513595722,"deployment":"oscf-mysql"}
E, [2017-12-18 11:15:22 #16242] [task:8646654] ERROR -- DirectorJobRunner: Unknown CPI error 'Unknown' with message 'undefined method `length' for nil:NilClass' in 'create_vm' CPI method
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/cloud/external_cpi.rb:144:in `handle_error'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/cloud/external_cpi.rb:93:in `invoke_cpi_method'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/cloud/external_cpi.rb:52:in `create_vm'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:163:in `create'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:54:in `create_for_instance_plan'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:34:in `block (5 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:31:in `block (4 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-261.4.0/lib/bosh/director/vm_creator.rb:30:in `block (3 levels) in create_for_instance_plans'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-261.4.0/lib/common/thread_pool.rb:63:in `block in create_thread'

Any suggestions?

**Comment by dpb587-pivotal** [comment]
Sorry, we seemed to have dropped this issue. Are you still experiencing this, or were you able to figure out what a solution was?
