### ISSUE TITLE
`attach_disk` failures result in corrupt state

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1869]
When BOSH creates a disk it also creates the corresponding disk model with the disk CID. https://github.com/cloudfoundry/bosh/blob/dbe2e8a4bb41901b51ae350d73db34d12d6246d5/src/bosh-director/lib/bosh/director/disk_manager.rb#L183-L191 Afterwards BOSH tries to attach the disk to the VM. If it's successful the CPI updates at the end the registry with the disk CID. If it's not successful the registry will not contain a CID but the model will still contain the CID . This is a mismatch which results in the following error when redeploying:
```
Task 30 | 12:09:50 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
Task 30 | 12:09:50 | Preparing deployment: Preparing deployment (00:00:00)
Task 30 | 12:09:50 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 30 | 12:09:50 | Updating instance dummy: dummy/4d0ee51a-7881-4719-95fc-1035bebff3a3 (0) (canary) (00:00:05)
                   L Error: 'dummy/4d0ee51a-7881-4719-95fc-1035bebff3a3 (0)' has invalid disks: agent reports '' while director record shows '29d1dced-d008-4301-8c44-385871381751'
Task 30 | 12:09:55 | Error: 'dummy/4d0ee51a-7881-4719-95fc-1035bebff3a3 (0)' has invalid disks: agent reports '' while director record shows '29d1dced-d008-4301-8c44-385871381751'
```

Even if the CPI `attach_disk` call is successful and agent `mount_disk` call fails, we end up in the same situation because `unmount_disk` call is executed. https://github.com/cloudfoundry/bosh/blob/dbe2e8a4bb41901b51ae350d73db34d12d6246d5/src/bosh-director/lib/bosh/director/disk_manager.rb#L137

**Comment by damzog** [comment]
Did you find a way to repair the bosh config?

**Comment by voelzmo** [comment]
@damzog I think we default to calling `bosh delete-vm` followed by `bosh deploy` to fix these issues.

**Comment by mfine30** [comment]
@voelzmo @beyhan it seems like this bug is directly related because of the registry? Since we're working on removing it, do you think this bug will still exist? 

I'm going to close it, but if you believe it will, please re-open.

**Comment by voelzmo** [comment]
I'm not sure all aspects of this bug are related to the registry. The first part, where `attach_disk` can fail to update the registry, should be gone, correct.

The second part though, where a failure in the `mount_disk` call to the agent errors out, might still produce the same mismatch between agent and director. I think this case isn't handled properly on the director side.

**Comment by beyhan** [comment]
Steps to reproduce the issue on OpenStack:

1. Deploy a dummy deployment with persistent disk
2. Modify the `attach_vm` method on the director VM to raise an error.
3. Redeploy the dummy deployment with `--recreate`. This will fail with the error specified in step 2.
4. Reset the changes in the CPI from step 2
5. Redeploy the dummy deployment. This will fail with the error from the description in this issue.

We reproduced the issue on both, CPI api v1 and v2.

@beyhan && @s4heid

**Comment by s4heid** [comment]
We created this [spike](https://github.com/cloudfoundry/bosh/commit/f4be4f8ac3f827eff6d342fc94b4ce48e378319b) to fix the issue. The idea is to reattach the persistent disk in case the agent has no information about the disk (`agent_disk_cid=nil`) and the instance model has an active disk attached.

After reproducing it on an OpenStack environment, we verified that the [criteria in the tracker story](https://www.pivotaltracker.com/story/show/162780889/comments/198948122) are working.

@dpb587-pivotal @jfmyers9 any thoughts on this approach?

Best Regards,
@beyhan && @s4heid, CF BOSH Europe

**Comment by dpb587-pivotal** [comment]
Conceptually, the resolution steps make sense to me -- re-attach if needed. The spike implemented it in the `update_persistent_disk` method which is a little bit odd to me since I think of that as "verify director and agent have the same settings" and less "make changes so the director and agent have the same settings". That's probably minor, but if you have other ideas where we can keep the call agent-focused I'd be interested. I'm not sure if there's a separate place where it makes more sense to reconcile IaaS-related stuff.

This fixes the expected-to-be-attached case. Is there still an issue in detach edge cases that could be fixed with this, too? I think I saw something mentioned about that scenario in this issue or story. Or does this essentially cause the disk to be re-attached later to an already failing mount (e.g. #2128)?

This seems similar to possible `cck` workflows of disks; are they affected by this in any way? Or end up overlapping?

@jfmyers9 might have more thoughts.

**Comment by beyhan** [comment]
* We couldn't find a reasonable way to avoid the disk mismatch situation. When attach disk fails during a deployment, there is no way to fail the deployment,  in such a state, so that it is resumed from the right place during the next deploy.
* [Bosh cck](https://github.com/cloudfoundry/bosh/blob/029ce7eea096fb5e731f5a81bbe9dbc62e5eec7a/src/bosh-director/lib/bosh/director/problem_scanner/disk_scan_stage.rb#L40-L81) has the same logic [as deploy](https://github.com/cloudfoundry/bosh/blob/029ce7eea096fb5e731f5a81bbe9dbc62e5eec7a/src/bosh-director/lib/bosh/director/disk_manager.rb#L116-L121) to find out whether there is a disk mismatch or not. Instances disk information is compared with agents disk information. The logic to fix the situation is like `attach_disk_step`. Bosh cck calls [`attach_disk` function](https://github.com/cloudfoundry/bosh/blob/ddc63d675dd212ac890e37c3965d3ec08adf75dc/src/bosh-director/lib/bosh/director/problem_handlers/mount_info_mismatch.rb#L62) of a cpi in order to fix the mismatch information. [Here](https://github.com/cloudfoundry/bosh/blob/ddc63d675dd212ac890e37c3965d3ec08adf75dc/src/bosh-director/lib/bosh/director/deployment_plan/steps/attach_disk_step.rb#L20) is the `attach_disk_step` which is called during update.

* We also tried to move the handling somewhere else more agent-focused, but we couldn't find such a place, which is better than the current proposed fix.

We don't have a better proposal at the moment as the proposed fix. @dpb587-pivotal do you have any other ides based on our findings?

**Comment by dpb587-pivotal** [comment]
Okay, sounds like you've covered it; I don't have any other ideas.

Is [this code](https://github.com/cloudfoundry/bosh/commit/f4be4f8ac3f827eff6d342fc94b4ce48e378319b#diff-73e471bd87f06984800593ca584e486cR55) correct? It's at least confusing to me to read, but I think it might also not be the case we want.

```
return unless agent_disk_cid.nil? || agent_disk_cid != instance.model.managed_persistent_disk_cid
```

**Comment by beyhan** [comment]
This is just a spike for discussion. We will definitely reimplement this after we have agreed on the place/way to implement it. The situation in which we need to reattach the disk is:
1. instance model have a persistent disk cid
2. instance still requires a persistent disk `instance_plan.needs_disk?` (the spike doesn't check this)
3. agent doesn't know anything about persistent disk.
