### ISSUE TITLE
As an operator, I would like to reduce the amount of tasks already in the database

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#1871]
### Current Behavior 

If we have a director with a certain amount of tasks already in the database and we redeploy with `max_tasks` set to a value significantly lower (per type), only two tasks are removed the next time a task of that type is created.

The behavior seems to be intentional:
https://github.com/cloudfoundry/bosh/blob/5c6d2c903d8d4b28c83c3be85303b791be656650/src/bosh-director/spec/unit/api/task_remover_spec.rb#L80

### Expected Behavior

Our expectation was, that the next time a task is created all tasks of that type above the `max_tasks` limit are removed.

Is there a reason why only two tasks are removed? Could this be changed? Is there any other way an operator can remove old tasks without doing it in the database directly?

**Comment by cppforlife** [comment]
@friegger yup, looks like a bug.

**Comment by voelzmo** [comment]
story: https://www.pivotaltracker.com/story/show/155320835

**Comment by mfine30** [comment]
Marking as triaged since it looks like there's a story that @voelzmo made.

**Comment by friegger** [comment]
@mfine30 @jfmyers9 For reference, some work related to this has also been done in https://www.pivotaltracker.com/n/projects/956238/stories/163150850. This keeps the current approach where tasks are removed (was 2, now 10) when a new task is scheduled. While I understand that the goal is to keep the amount of kept tasks at a steady level, this becomes weird when the director is re-deployed with a significantly lower `max_tasks` configuration.
Instead we would propose to clean-up tasks in a similar manner as it is done for `events` where this is a scheduled job: https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=268.7.0#p%3ddirector.events 

What do you think?

https://github.com/cloudfoundry/bosh/blob/fa930224404d3f000aeff8631ff7a08b6b0dba09/src/bosh-director/lib/bosh/director/jobs/scheduled_events_cleanup.rb#L3.
