### ISSUE TITLE
bosh-vsphere-esxi-centos-7-go_agent image guestOS value incorrect

### ISSUE THREAD

**Issue by jantonacci** [cloudfoundry/bosh#1873]
Stemcell bosh-vsphere-esxi-centos-7-go_agent version 3468.16 has value guestOS = "ubuntu-64" incorrectly assigned in the .vmx file.  This results in ESXi Web Client displaying error message:

> The configured guest OS (Ubuntu Linux (64-bit)) for this virtual machine does not match the guest that is currently running (CentOS 7 (64-bit)). You should specify the correct guest OS to allow for guest-specific optimizations.

Not certain if this has impact beyond cosmetic.  Confirmed this is the correct image from the 'bosh create-env [...]'  results:

>Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-centos-7-go_agent/3468.16'... Skipped [Stemcell already uploaded] (00:00:00)

![untitled](https://user-images.githubusercontent.com/12749853/34805360-f5d1c0da-f63a-11e7-9eda-81ca652e9834.png)

**Comment by cppforlife** [comment]
> Not certain if this has impact beyond cosmetic.

i believe it's only cosmetic impact at this point.

im going to keep track of this request in https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/centos-stemcells-improvements-v1.md.
