### ISSUE TITLE
Updated CentOS stemcell for Openstack and vSphere with Meltdown and Spectre fix for 3445 series

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/bosh#1875]
Hello,

I would like to know when we will get updated CentOS stemcell for Openstack and vSphere with Meltdown and Spectre fix for 3445 series? 

Thanks,
Prashant

**Comment by fatbearinc** [comment]
For **both** Meltdown and Spectre, I am very much interested in knowing when the stemcells will be available for:

- [bosh-openstack-kvm-centos-7-go_agent](https://bosh.io/stemcells/bosh-openstack-kvm-centos-7-go_agent)
- [bosh-vsphere-esxi-centos-7-go_agent](https://bosh.io/stemcells/bosh-vsphere-esxi-centos-7-go_agent)

Is there any goal date for this?

**Comment by cppforlife** [comment]
@prashantgnet only latest versions of CentOS stemcells are maintained (currently CentOS 7 3468.x). we believe they contain latest available fixes from upstream.

do let us know if you think we are missing any package updates for CentOS.
