### ISSUE TITLE
Support for full bosh director - multi vm

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/bosh#1878]
Hello,

Any plan to add support for full bosh director (multi-vm) using BOSH CLI v2? 

Thanks,
Prashant

**Comment by cppforlife** [comment]
we have some plans to add ha director support, however, it would be different from what was known as multi vm director. 

ha director would involve running multiple copies of the director backed by the same db. in case of one director becoming unhealthy, other director would be able to take over. 

is there particular scenario you are trying to cover by mutli vm director?

**Comment by prashantgnet** [comment]
ha director support will be helpful for us. we are looking for "multi vm director" for performance perspective.

Thanks,
Prashant

**Comment by cppforlife** [comment]
> we are looking for "multi vm director" for performance perspective.

interesting, do tell more. do you want to scale out number of workers, or
some other component?

**Comment by prashantgnet** [comment]
We are right now creating full bosh environment (using normal deployment, YML file) under single-vm bosh-init based director. Full bosh environment contains following six vms with respective jobs under it along with max threads set to 32 and workers set to 8.

full-bosh-1-blobstore
full-bosh-1-director
full-bosh-1-health_monitor
full-bosh-1-nats
full-bosh-1-postgres
full-bosh-1-registry

Due to https://github.com/cloudfoundry/bosh/issues/1715 issue we are not able to place jobs on separate vms.

**Comment by cppforlife** [comment]
right, but what performance limitations are you seeing with a single vm
director such that you have to use multi-vm configuration. for example, for
one of our production envs we are running 10 workers, 32 threads
configuration and it seems to work fine.

**Comment by prashantgnet** [comment]
hmm...I might be wrong! I am thinking, we will get good performance if we place each job on separate vm along with max threads and workers. I have not compare the actual performance between single vm and multi vm bosh director but you may close this issue as we can fine tune any performance parameters using single vm bosh director. ha support looks very good.

Thanks,
Prashant

**Comment by cppforlife** [comment]
i would recommend following standard single vm configuration (
https://github.com/cloudfoundry/bosh-deployment) and see if you hit any
problems. feel free to open new issues regarding any perf concerns.

**Comment by prashantgnet** [comment]
Yes, right now we are using https://github.com/cloudfoundry/bosh-deployment based bosh director and will update any performance issue, if any.

**Comment by andrearagao** [comment]
What happens if that single director crashes?
