### ISSUE TITLE
'Failed to connect to remote server: dial tcp …: getsockopt: connection timed out' when initializing BOSH environment on AWS

### ISSUE THREAD

**Issue by chirangaalwis** [cloudfoundry/bosh#1880]
I followed the [documentation](https://bosh.io/docs/init-aws.html) which provides instructions to create a BOSH environment on AWS.

After setting up the necessary [AWS resources](https://bosh.io/docs/init-aws.html#prepare-aws) as defined in the documentation, when creating the BOSH environment (using bosh create-env bosh-deployment/bosh.yml...), I am encountering the following issue.

```
Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'ami-1974417c light'... Finished (00:00:37)
  Waiting for the agent on VM 'i-00a10b77ed4c4083d' to be ready... Failed (00:08:43)
Failed deploying (00:09:20)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Starting SSH tunnel:
        Starting SSH tunnel:
          Failed to connect to remote server:
            dial tcp 10.0.0.6:22: getsockopt: connection timed out

Exit code 1
```
In my AWS account, I find the `bosh/0` VM successfully created although, it fails while waiting for the agent on the created VM.

My BOSH CLI command to create the environment is as follows:

```
bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/aws/cpi.yml \
    -v director_name=aws \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.6 \
    -v access_key_id=<some_value> \
    -v secret_access_key=<some_value> \
    -v region=us-east-2 \
    -v az=us-east-2a \
    -v default_key_name=bosh \
    -v default_security_groups=[bosh] \
    --var-file private_key=<path>/bosh.pem \
    -v subnet_id=subnet-xxxxxxxx
```

Any help and suggestions are highly appreciated.

**Comment by cppforlife** [comment]
@chirangaalwis are you running bosh create-env from a jumpbox or from outside of this vpc?

**Comment by chirangaalwis** [comment]
@cppforlife I am running create-env from outside of this vpc. I am not using a jumpbox, in this case.

**Comment by chirangaalwis** [comment]
@cppforlife I got it working. Missed out on the documentation related to [exposing environment on a public IP](https://bosh.io/docs/init-external-ip.html). Yet, I would like to suggest minor improvements to the original [documentation](https://bosh.io/docs/init-aws.html).

The command used is as follows:
```
bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/aws/cpi.yml \
    -o bosh-deployment/external-ip-with-registry-not-recommended.yml \
    -v director_name=aws \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.6 \
    -v access_key_id=<some_value> \
    -v secret_access_key=<some_value> \
    -v region=us-east-2 \
    -v az=us-east-2a \
    -v default_key_name=bosh \
    -v default_security_groups=[bosh] \
    --var-file private_key=<path>/bosh.pem \
    -v subnet_id=subnet-xxxxxxxx \
    -v external_ip=<AWS_Elastic_IP>
```

In section **Step 2: Deploy**, it would be better if a mapping is provided in terms the terminology (e.g. the created AWS Elastic IP is referred as the external-ip in [this](https://bosh.io/docs/init-aws.html) documentation. And better if explanations are provided in terms of what is happening as a 'dumb' user may wonder what exactly happens to the AWS resources they create in **Step 1**.
