### ISSUE TITLE
Mount shared network volume between BOSH instances using a BOSH Release

### ISSUE THREAD

**Issue by chirangaalwis** [cloudfoundry/bosh#1881]
Currently, it has been understood that that there is no known concept in BOSH for sharing volumes between BOSH instances ([reference 1](https://ultimateguidetobosh.com/instances/#persistent-volumes)).

Upon research it was learnt that if needed to share volumes, the deployment is required to include a Network File System (NFS) or a similar network files system service running on top of the BOSH instances.

Is there a better solution provided for sharing network volumes between BOSH instances via a BOSH Release?

**Comment by cppforlife** [comment]
> Is there a better solution provided for sharing network volumes between BOSH instances via a BOSH Release?

shared volumes isnt something that typical iaases provided. your best bet would be to make a job that configures nfs or some other shared fs.
