### ISSUE TITLE
Setup shared Network File System (NFS) volume between BOSH instances using BOSH Lite

### ISSUE THREAD

**Issue by chirangaalwis** [cloudfoundry/bosh#1882]
I've been attempting to share a directory which resides within my local machine using NFS with BOSH instances. I am using [BOSH Lite](https://bosh.io/docs/bosh-lite) as the Director VM.

I have setup NFS in my local machine (which uses Ubuntu) using [this](https://help.ubuntu.com/community/SettingUpNFSHowTo) guide. I have created the following directory structure in my local machine.

```
chiranga@chiranga-ThinkPad-X1-Carbon-5th:/$ ls -la /export/
total 12
drwxrwxrwx  3 root     root     4096 ජන   29 16:30 .
drwxr-xr-x 29 root     root     4096 ජන   29 16:33 ..
drwxrwxrwx  2 chiranga chiranga 4096 ජන   29 18:03 users
chiranga@chiranga-ThinkPad-X1-Carbon-5th:/$ tree export/
export/
└── users
    └── file

1 directory, 1 file
```
I have provided 777 permissions to the /export and /export/users directories. This is how my /etc/exports file looks like.
```
/export       10.244.15.2(rw,fsid=0,insecure,no_subtree_check,async)
/export/users 10.244.15.2(rw,nohide,insecure,no_subtree_check,async)
```
Please note that `10.244.15.2` is the IP address of one of my job VMs. Also, I install `nfs-common` package in my job control script.

After logging into the job VM, I attempt to manually mount the directory to my job VM.

```
job_1/5b721203-b05b-46e9-bb99-e3faff5fbbd6:~$ sudo mount -v -t nfs -o proto=tcp,port=2049 192.168.50.1:/users /mnt
mount.nfs: timeout set for Mon Jan 29 13:28:26 2018
mount.nfs: trying text-based options 'proto=tcp,port=2049,vers=4,addr=192.168.50.1,clientaddr=10.244.15.2'
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting 192.168.50.1:/users
```
But I tend to get an `mount.nfs: access denied by server while mounting 192.168.50.1:/users`. When checking the mount information of the host machine from the job VM, it shows up the export list as follows:
```
job_1/5b721203-b05b-46e9-bb99-e3faff5fbbd6:~$ showmount -e 192.168.50.1
Export list for 192.168.50.1:
/export/users 10.244.15.2
/export       10.244.15.2
```
I tried manual mounting of the same directory to an Ubuntu 16.04 machine spawned using Vagrant and it mounted successfully.

Please correct me if I am wrong but, which permissions are required here? If not, how can I achieve my target?

**Comment by cppforlife** [comment]
is it trying to auth based on an ip? since 10.244... is a container ip,
your host machine will not see it.

**Comment by chirangaalwis** [comment]
@cppforlife is there any alternative way to achieve this?

**Comment by cppforlife** [comment]
i believe you want to allow vm's ip address instead of a container's ip as container ip is not meaningful outside of the vm. if you ran create-env with `internal_ip=192.168.50.6`, try using 192.168.50.6 for allowing access.

**Comment by chirangaalwis** [comment]
@cppforlife my effort is to share the directory across the job VMs (**cloud servers**). A **cloud server** could be a container, VM or even a physical machine (as defined [here](https://ultimateguidetobosh.com/instances/)), depending on the infrastructure. In the case of BOSH Lite, we get containers.

Hence, I don't see how I can achieve the target by simply mounting the directory to the Director VM in the case of BOSH Lite. Please correct me if I am wrong.

**Comment by cppforlife** [comment]
> A cloud server could be a container, VM or even a physical machine (as defined here), depending on the infrastructure.

yup

> Hence, I don't see how I can achieve the target by simply mounting the directory to the Director VM in the case of BOSH Lite.

im not suggesting to mount it to the director vm. you still have to mount it in the container (via a job); however, you have to consider network topology thats particular to each "iaas". in bosh-lite case everything is nat-ed hence nfs server will not see container ip, but will see "bosh-lite" vm ip as the client. for authentication reasons i believe you have to configure server to allow director vm ip to access mount even though client runs in a container.
