### ISSUE TITLE
Auto_assign_public_ip only works for true

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry/bosh#1885]
In AWS, given a subnet that maps public IPs to all new instances:
```hcl
resource "aws_subnet" "bosh-services" {
  count                   = "${length(data.aws_availability_zones.available.names)}"
  vpc_id                  = "${aws_vpc.bosh-base.id}"
  cidr_block              = "10.0.${count.index + 1}.0/24"
  availability_zone       = "${data.aws_availability_zones.available.names[count.index]}"
  map_public_ip_on_launch = true

  tags {
    Name    = "${var.env_name}${var.prefix}bosh-services-${count.index + 1}"
    Cluster = "${var.env_name}"
  }
}
```

Before I was able to disable public IP per instance, using a `vm_extension`:
```yaml
cloud_properties:
  auto_assign_public_ip: 'false'
```

I know this should be the default value anyways, however it didn't work unless specified. The instance with this property would **not have a public IP** assigned to it. 

Since BOSH was upgraded, the property stopped having the effect desired.
Not sure what version of BOSH caused this. The reason I think it's not the CPI, is because I rolled back `aws-cpi` from `69` to `63` with no effect.

BOSH version: `263.6.0`
CLI: `version 2.0.48-e94aeeb-2018-01-09T23:08:08Z`

## Question

- What is the desired behaviour?
- Does BOSH intentionally ignore the value when `false` is specified? And what about when it's omitted? Right now it only seems to work to active the public IP, not the opposite.

I think it's useful to have the setting override whatever the subnet is configured with. Certain subnets that are exposed to the world, where most of the instances need a public IP, there is value in this setting to provide a way to handle exceptions.

**Comment by cdutra** [comment]
@dmlemos That's actually a CPI issue on starting on v63. We did a refactor and it caused a regression to only override if `auto_assign_public_ip` is true. In your case you're using string but you should use boolean instead.
The working version you mentioned is most likely AWS CPI v62 or earlier.

We added a [bug in our backlog]() to fix that.

cc @jaresty

**Comment by dmlemos** [comment]
Thanks. Please free to move the issue.

**Comment by dmlemos** [comment]
@cdutra Just for you to know I have tested `v62` with reached the same result. I don't remember the problem being this old.
