### ISSUE TITLE
How can I increase Disk Size of Bosh VM ?

### ISSUE THREAD

**Issue by K7king** [cloudfoundry/bosh#1887]
I am using AWS VMs of storage type EBS. I want to increase my root disk size.When I increase persistent disk size in manifest and deploy, It affects in other disks, but the Root disk remains the same 3GB. 
Is there a way to increase root disk size in bosh ?

**Comment by tjvman** [comment]
For AWS, you can set the `root_disk` cloud property in your `resource_pools` or `vm_types` section. [See docs](http://bosh.io/docs/aws-cpi.html#resource-pools).

**Comment by K7king** [comment]
Thank You.
