### ISSUE TITLE
BOSH Release upload failure: Seeking to beginning of seekable request body during attempt 0: seek...: bad file descriptor

### ISSUE THREAD

**Issue by chirangaalwis** [cloudfoundry/bosh#1888]
I've been encountering the following issue when uploading a BOSH Release when using AWS as the IaaS. 

```
chiranga@chiranga-ThinkPad-X1-Carbon-5th:~/wso2/repositories/pcf/pivotal-cf-is/pattern-1/bosh-release$ bosh -e aws-demo upload-release
Using environment '18.218.240.11' as client 'admin'

######################################################## 100.00% 1.08 MB/s 8m13s

Uploading release file:
  Performing request POST 'https://18.218.240.11:25555/releases?':
    Performing POST request:
      Seeking to beginning of seekable request body during attempt 0: seek /home/chiranga/.bosh/tmp/bosh-platform-disk-TarballCompressor-CompressSpecificFilesInDir475259787: bad file descriptor

Exit code 1
```
I managed to successfully upload the exact same release to a local BOSH environment (BOSH Lite as Director VM).

I came across a [reference](https://github.com/cloudfoundry/bosh-cli/issues/140) to the same issue under BOSH CLI issues. But in the discussed issue, the user is not logged on to the BOSH environment unlike in my case where I have successfully logged on to the AWS BOSH environment.

What causes this issue? How can I fix it?

**Comment by dpb587-pivotal** [comment]
Can you double-check what `bosh env` tells you for your authentication username?

**Comment by benmoss** [comment]
Yep, we just ran into the same issue and we realized we didn't have `BOSH_CLIENT` / `BOSH_CLIENT_SECRET` in our environment for the director we were targeting.

**Comment by chirangaalwis** [comment]
@dpb587-pivotal, @benmoss I got this working. I was misguided by the `Using environment '18.218.240.11' as client 'admin'` thinking that I had already logged in. Realized that I was not logged out when checked with `bosh env`.

BTW, sorry for the late response.
