### ISSUE TITLE
bbr blobs restore with clean bosh environment fails

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh#1890]
if you backup a bosh with no blobs added (so just installed clean env)
the bbr restore will tell you that it succeeded.

but the problem arises when you want to upload a release/stemcell/ etc
this is due to that `/var/vcap/store/blobstore/store` is created with `root:root` priveleges
instead of `vcap:vcap

i know this scenario should never happen. stumbled on this in some of my tests

**Comment by voelzmo** [comment]
Probably was fixed with https://github.com/cloudfoundry/bosh/pull/1874?
