### ISSUE TITLE
Need API spec of bosh disk attach

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry/bosh#1894]
Found API spec of bosh director in https://bosh.io/docs/director-api-v1.html#instances 
Need api spec for corresponding following command 
`
 bosh -e vbox -d cf attach-disk postgres/209c42e5-3c1a-432a-8445-ab8d7c9f69b0 vol-shw8f293f2f2
`

**Comment by cppforlife** [comment]
Moved to here: https://github.com/cloudfoundry/docs-bosh/issues/470
