### ISSUE TITLE
Drain script doesn't always properly fail on non zero exit code

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry/bosh#1896]
The [bosh.io docs](https://bosh.io/docs/drain.html) say:

> You must ensure that your drain script exits in one of following ways:
> - exit with a non-0 exit code to indicate drain script failed
> - exit with 0 exit code and also print an integer followed by a newline to stdout (nothing else must be printed to stdout)

When the drain script echo's a positive number to stdout, the director moves on to stopping processes regardless of the exit code.

You can test this by running the following as your drain script:
```bash
#!/bin/bash
echo 1
exit 1
```

Best,

@jfmyers9 && @akshaymankar

**Comment by voelzmo** [comment]
See also this discussion on the mailing list https://lists.cloudfoundry.org/g/cf-bosh/topic/6331977#2438

I think currently the only fail to make your drain fail is echoing a non-integer: https://github.com/cloudfoundry/bosh-agent/blob/7d965883bd85c5297dda9015cfe63d67937327e1/agent/script/drain/concrete_script.go#L157

**Comment by cppforlife** [comment]
todo: need to figure out how to make this change in a backwards compatible manner.

**Comment by jfmyers9** [comment]
Could you update the documentation in the mean time?

**Comment by xtreme-andrew-su** [comment]
Closing as there was documentation updates

> You must ensure that your drain script exits in one of following ways:
> 
> - exit with a non-0 exit code to indicate drain script failed
> 
> - exit with 0 exit code and also print an integer followed by a newline to stdout (nothing else must be printed to stdout):
> 
> static draining: If the drain script prints a zero or a positive integer, BOSH sleeps for that many seconds before continuing.
> 
> dynamic draining: If the drain script prints a negative integer, BOSH sleeps for that many seconds, then calls the drain script again.

**Comment by jfmyers9** [comment]
@xtreme-andrew-su I don't believe the documentation has been updated. That is the same documentation that was referenced in the original comment:

The [bosh.io docs](https://bosh.io/docs/drain.html) say:

> You must ensure that your drain script exits in one of following ways:
> - exit with a non-0 exit code to indicate drain script failed
> - exit with 0 exit code and also print an integer followed by a newline to stdout (nothing else must be printed to stdout)

The issue here is that when you exit with a non-0 exit code, if you also output an integer to stdout it will not properly fail. There are 2 potential solutions:

* We always respect the exit code and fail when it is non-0 (preferable)
* We update the documentation to say something along the lines of: `exit with a non-0 exit code to indicate drain script failed and do not output any numeric characters to stdout`

I would much prefer us to tackle this issue by following the first solution, but it hasn't been a priority in the past.

**Comment by h4xnoodle** [comment]
Hi @jfmyers9 thanks for raising this issue!

You may benefit from using `pre-stop` introduced in 269.0.0! This hook allows you to run graceful shutdown tasks like with `drain` and you can now determine if the VM/instance will be deleted or not, allowing for optimized shutdown.

While this bug still likely exists, we haven't see any issues with this behaviour since this filing. Closing for now. If you think this should remain open, please open again.

:)
