### ISSUE TITLE
Bosh create-env (vSphere) always failing

### ISSUE THREAD

**Issue by VincenzoDo** [cloudfoundry/bosh#1898]
Hello,

On four different machines running Ubuntu 16.04 and CentOS 7 I get the following result every time I run the create-env command:

`creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3468.21):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"403","ok_to_retry":false}
`

I've followed these instructions: https://bosh.io/docs/init-vsphere.html
And installed all needed packages listed here: https://bosh.io/docs/cli-env-deps

Debug log can be found here: https://paste.ubuntu.com/p/6WDPJdVPj5/

Any suggestions?

**Comment by cppforlife** [comment]
@VincenzoDo that's a really weird error (just `403`). it appears that that portion of the code is trying to login into vcenter [1]. may be you have wrong creds?

[1] https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/vcenter_client.rb#L19

**Comment by VincenzoDo** [comment]
@cppforlife I've tried with different users (ldap user and local administrator) and still get the same error. And as you mentioned, the error isn't clear at all.

**Comment by cppforlife** [comment]
@ktchen14 any ideas?

**Comment by ktchen14** [comment]
The debug log is no longer available. @VincenzoDo would you mind uploading them again? Thanks.

**Comment by VincenzoDo** [comment]
@ktchen14 here you go: https://pastebin.ubuntu.com/p/NNJqyKbQnR/

**Comment by ktchen14** [comment]
@VincenzoDo according to the logs vCenter is returning a 403 Forbidden when we attempt to connect to it and issue the `RetrieveServiceContent` call. This is the first call that any vCenter client must issue when connecting to vCenter.

Can I see the exact `bosh create-env` command that you're issuing? Make sure that if you're passing the vSphere username and password as variables to be interpolated (using `-v`) that they're properly quoted so that `bash` isn't mangling them.

**Comment by VincenzoDo** [comment]
@ktchen14 this is the create-env (it's the default taken form the official tutorial):
`bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.2 \
    -v network_name="MyNet" \
    -v vcenter_dc=datacenter1 \
    -v vcenter_ds=disk_1 \
    -v vcenter_ip=vcenterIP \
    -v vcenter_user='administrator'\
    -v vcenter_password='xxxxxx' \
    -v vcenter_templates=bosh-1-templates \
    -v vcenter_vms=bosh-1-vms \
    -v vcenter_disks=bosh-1-disks \
    -v vcenter_cluster=Compute `

Values are adapted to my environment. I've tried to put quotes (single and double) around both vcenter_user and password but nothing changed, I've also tried different formats of usernames (local and ldap) for example: 'administrator', 'administrator@vsphere.local' or 'domain\\domainuser' nothing seems to work. As for the password I tried escaping the special characters, still nothing.

Do you have any other suggestion? I'm I doing something wrong? Is there a way to test just user auth.?

**Comment by dpb587-pivotal** [comment]
@VincenzoDo, is this still an issue? It sounds like a general authentication misconfiguration or character escaping issue. Trying a simpler password for testing may be helpful to confirm.

**Comment by VincenzoDo** [comment]
Not really since I stopped using bosh. What I can say is that it wasn't a password problem because I've tried with simpler ones and it still failed.

**Comment by zhangrl-mark** [comment]
if you want deploy bosh on vsphere.6.5 , you need create new account [my eg: bosh] within vsphere.local field , and add  the account into  administrator group,  through vSphere Client/VCSA.
[SystemMange->Single Sign On->User&Group->Create Account:yourAccount -> Group->Add member.].
my deploy cmd on vSphere scceeded.

bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=bosh-creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -o bosh-deployment/uaa.yml \
    -o bosh-deployment/credhub.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=192.168.22.0/24 \
    -v internal_gw=192.168.22.1 \
    -v internal_ip=192.168.22.85 \
    -v network_name="VM Network" \
    -v vcenter_dc=Datacenter \
    -v vcenter_ds=datastore2-4T \
    -v vcenter_ip=192.168.22.86 \
    -v vcenter_user=bosh@vsphere.local \
    -v vcenter_password=Bosh1234! \
    -v vcenter_templates=bosh-1-templates \
    -v vcenter_vms=bosh-1-vms \
    -v vcenter_disks=bosh-1-disks \
    -v vcenter_cluster=HA-Cluster
