### ISSUE TITLE
API endpoint issue.

### ISSUE THREAD

**Issue by spunky11** [cloudfoundry/bosh#1899]
I have installed cf-cli, BOSH CLI v2 and VirtualBox in my computer. My aim is to build a private cloud and push an app to cloud using Cloud Foundry but its asking for an API endpoint. Kindly help me in setting up the cloud environment using BOSH and VirtualBox and then push an app using cf.
What I feel is there's an issue regarding the connection between my computer and VM created in VirtualBox. But I'm not sure.

**Comment by cppforlife** [comment]
@spunky11 wihtout a more concrete error message its hard to help. i would recommend following http://bosh.io/docs/bosh-lite to get a feel for it and then extending it to cf.

**Comment by spunky11** [comment]
@cppforlife 
I have completed all the steps given in the doc i.e. installation of bosh-lite and zookeeper deployment (even the smoke test was successful); but I really do not have an idea as to how to set up the cloud environment with the help of BOSH and VirtualBox.

**Comment by cppforlife** [comment]
> I have completed all the steps given in the doc i.e. installation of bosh-lite and zookeeper deployment (even the smoke test was successful)

http://bosh.io/docs/bosh-lite#install step 7 specifies how to add route from your machine so that you can access IPs where (zookeeper or other software can run). hoping @dsabeti can point to bosh-lite cf installation guide.

**Comment by dsabeti** [comment]
@spunky11, you can follow [these directions](https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/bosh-lite) to deploy Cloud Foundry to bosh-lite. You'll probably want to start at step 4, since the first few steps have to do with setting up a bosh-lite on a public cloud like AWS or GCP, and you're using you're local VirtualBox instead.

**Comment by dpb587-pivotal** [comment]
Closing - thanks @dsabeti for the assist. Feel free to follow up if you are continuing to see issues around the routing to VMs.
