### ISSUE TITLE
attach_disk sets disk size as 1

### ISSUE THREAD

**Issue by muralisc** [cloudfoundry/bosh#1900]
`attach_disk` currently sets the size of [attached disk as 1](https://github.com/cloudfoundry/bosh/blob/8b375db201031c3256570d39df9d435d61a0a6c3/src/bosh-director/lib/bosh/director/jobs/attach_disk.rb#L74) and the cloud_properties empty.
This leads to a disk copy every time a `bosh start` follows a disk attach operation on a deployment, even when the disk size of the newly attached disk is same as that of the existing disk.

For disks with data already filled the `bosh start` operation takes time as long as the copy.
This leads to the deployment being unavailable for so long.

In cases where the newly attached disk is of same size and user expects a copy,
`bosh attach` could have a flag `--copy` or `--no-copy` which decides weather to copy the data or just attach the disk as is.

**Comment by cppforlife** [comment]
@muralisc yup, i agree, we could probably copy over and persistent cloud properties to avoid unnecessary copy operation on restore.

**Comment by muralisc** [comment]
@cppforlife Took a stab at this issue. Can you take a look and let me know the comments.

**Comment by cppforlife** [comment]
@muralisc returning this information from cpi is not necessary, since director should already know what it sends to the cpi. you should be able to grab it from persistent disk model (holds disk size, and disk cloud properties in its db table)

**Comment by muralisc** [comment]
@cppforlife The issue we are trying to address is not only for an orphaned disk, but any arbitrary disk created by infrastructure.
Initial solution was to read the details of the new disk from the infrastructure and create persistent_disk entry.
The issue link with the AWS CPI pull reqs and comments : https://github.com/cloudfoundry/bosh/issues/1900

**Comment by voelzmo** [comment]
Closing in favor of #2015

**Comment by muralisc** [comment]
@voelzmo opened #2037
