### ISSUE TITLE
Ability to give warnings during deploy

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/bosh#1904]
Bosh deploys tend to be rather binary, you fail to deploy and look at the logs, or you succeed and nobody looks at the logs. Would it be possible to have a channel of communication during bosh deploys that is a little louder then success, but without the detrement of failing? During runtime? During pre-start?

For example, in syslog thr user could setup a custom rule, however it seems like we are trapped into either failing the deploy(for something as important and widespread as syslog, not really possible) or leaving the user with the impression everything deployed fine. What we would like would be a method to have the deploy succeed but with a warning that their custom rules did not apply? 

This channel would generally be intended to either tell the user that some of their settings were malformed or invalid, but could be deployed in a partially or mostly functional state. This channel could also be used to deliver other useful warnings such as eol and deprecation notices, discouraged configurations, security notices, ect.

Any thoughts?

**Comment by xtreme-andrew-su** [comment]
Hi @Benjamintf1 you can take a look at https://bosh.io/docs/pre-start/ for doing malformed and invalid setting checks. This provides authors of their own releases to manage the preconditions of their application. The logs would still live on the machine and it should be the operator's choice to check these for more information. They can also leverage `bosh logs` command to get the logs back.

**Comment by Benjamintf1** [comment]
Stale issue, still a problem.
