### ISSUE TITLE
Create custom release problem

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/bosh#1906]
Hi team:
 I custom a  simple release, but when update instance , it  always faild.
 I use ssh to instances, use `netstat -lntp `，it show tomcat server is running
![image](https://user-images.githubusercontent.com/21106445/36798156-c7ef38ca-1ce4-11e8-9c73-20ba42b677bb.png)
 In bosh-init vm. use  `curl`, the release instance response info:
![image](https://user-images.githubusercontent.com/21106445/36795821-f34c7984-1cde-11e8-965c-9a1233f14c0c.png)

`bosh -d web instances`:
![image](https://user-images.githubusercontent.com/21106445/36796158-e0549036-1cdf-11e8-9eb6-3722abdb7677.png)
Release tree:
```
├── blobs
│   ├── jre1.8
│   │   └── jre-8u161-linux-x64.tar.gz
│   ├── tomcat
│   │   └── apache-tomcat-9.0.5.tar.gz
│   └── web
│       └── web.war
├── config
│   ├── blobs.yml
│   └── final.yml
├── deployment.yml
├── dev_releases
│   └── web
│       ├── index.yml
│       ├── web-0+dev.1519863314.yml
│       └── web-0+dev.1.yml
├── jobs
│   └── web
│       ├── monit
│       ├── spec
│       └── templates
│           └── ctl.erb
├── packages
│   ├── jre1.8
│   │   ├── packaging
│   │   └── spec
│   ├── tomcat
│   │   ├── packaging
│   │   └── spec
│   └── web
│       ├── packaging
│       └── spec
└── src
```

Controller script:
```
#!/bin/bash

RUN_DIR=/var/vcap/sys/run/web
PIDFILE=${RUN_DIR}/pid

case $1 in

  start)
    mkdir -p $RUN_DIR 
    chown -R vcap:vcap $RUN_DIR
    echo $$ > $PIDFILE
    export JAVA_HOME=/var/vcap/packages/jre1.8
    export  PATH=${JAVA_HOME}/bin:$PATH
    exec /var/vcap/packages/tomcat/bin/catalina.sh start

    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;
  *)
    echo "Usage: ctl {start|stop}" ;;

esac
```
Job monit : 
```
check process web
  with pidfile /var/vcap/sys/run/web/pid
  start program "/var/vcap/jobs/web/bin/ctl start"
  stop program "/var/vcap/jobs/web/bin/ctl stop"
  group vcap
```

**Comment by dpb587-pivotal** [comment]
The `failing` status typically means `monit` considers a process unhealthy. You may want to start by going onto the VM and running `monit status` within a `sudo` shell.

If the process is running (as `netstat` seems to show), you might want to start by checking if the PID files match what you, tomcat, and monit expect.

**Comment by geekyzk** [comment]
@dpb587-pivotal I see tomcat logs. it start many times tomcat,but not stop. use `ps aux | grep tomcat` ,show  multiple records for tomcat. ` cat PID files` the number not match `ps aux | grep tomcat` 
In realease deploy? How many times will he run the script?

**Comment by dpb587-pivotal** [comment]
Since `monit` manages the process, it will repeatedly try to start the process if the PID it reads from /var/vcap/sys/run/web/pid does not exist.

**Comment by dpb587-pivotal** [comment]
Closing - feel free to reply if this is still an issue.
