### ISSUE TITLE
update resolv.conf with rotate options.

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/bosh#1910]
When we deploy cloudfoundry or any other software using bosh on AWS ,following entries are updated in resolv.conf of the newly created VM .

cat /etc/resolv.conf

nameserver x.x.x.x
nameserver x.x.x.x
search x.x.x.x

We would like to add "options rotate timeout:1 retries:1" in resolv.conf during bosh VM creation process .

cat /etc/resolv.conf

options rotate timeout:1 retries:1
nameserver x.x.x.x
nameserver x.x.x.x
search x.x.x.x

How can we achieve this ?

Regards,
Naresh Sharma

**Comment by cppforlife** [comment]
@nsharmacovs rotation is done by cloudfoundry/bosh-dns-release out of the box. retries i believe are also done.

**Comment by dpb587-pivotal** [comment]
This should be possible with the [`resolvconf`](https://github.com/cloudfoundry/os-conf-release/tree/master/jobs/resolv) job from the [`os-conf`](https://github.com/cloudfoundry/os-conf-release) release. Although, as already mentioned, if you're using `bosh-dns`, retries and timeouts are already being handled automatically and this configuration should not generally be necessary.
