### ISSUE TITLE
create bosh team from CLI

### ISSUE THREAD

**Issue by challa** [cloudfoundry/bosh#1912]
In Bosh database i see that there is teams table but from Bosh Cli i am not finding way to create team entry into this database.

https://bosh.io/docs/director-users-uaa-perms.html
to make teams concept work with uaa/director i had to manually create entry in the team table of bosh database and could work with them

but is there a way to create bosh team from Bosh CLI

**Comment by dpb587-pivotal** [comment]
Hello - teams are automatically created within the director when they are necessary. You should never need to manually change the director database. In this case, when you create a deployment or config using a client/user with a team-specific scope (documented by the link you mentioned), the director will automatically create the necessary records. You'll then be able to verify by running the `bosh deployments` command to see the team listed in the Teams column.

Does that help?

**Comment by challa** [comment]
thanks for quick reply.

when you say "teams are automatically created within the director when they are necessary"  how does bosh know when to create a team and with what name.

say i want to create  teams "team1", "team2", "Team3", how do i create that. is it possible to create this way.

but for me once teams are created (in my local set up i update in DB directly) i am able create deployments into a certain team by setting the corresponding team scope to the UAA client.

Still i am not able to figure out how to create teams with my preferred name.

**Comment by cppforlife** [comment]
@challa team creation is based on UAA scopes (`bosh.teams.X.admin` where X is a team name). as long as you provision UAA users/clients with scope in that format (or formats listed above) Director will create a team.

**Comment by challa** [comment]
@cppforlife  Thanks for the providing the necessary steps
