### ISSUE TITLE
[Feature] Add ignoring possibility for ops file for "replace" mode when object don't exist 

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry/bosh#1918]
Hello,

this issue refer to  : https://github.com/cloudfoundry/cf-deployment/issues/444

We can have problem with ops files when we use  2 (or more) ops file at same time  when 1 ops file delete a object while  the other want  modify it. (see example on the cf-deployment issue) 

Unfortunately, we only have possibility  to tag this object  "optionnal" (with ?) but , when used in the  "replace" mode, bosh will recreate this object instead just ignore it. 
Can we add a ignore case for "replace" mode for be able to bypass this problem ? 

thanks :)

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.
