### ISSUE TITLE
Backing up our BOSH Director

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry/bosh#1919]
Hello,
If this is the wrong location for such queries, please let me know.

We'd like to backup our data from our director.
It looks like BBR is the way to go here.  Is that the preferred option?  I've seen references to `bosh backup` but this option doesn't seem to be available in bosh v 2.0.48

Thank you, in advance

**Comment by MattSurabian** [comment]
I'm a little behind the times and haven't used BBR yet. I've had success rebuilding directors using only a backup of the director's postgres database and `bosh cck`. 

Your mileage may vary on that since I'm also not using UAA or CredHub though. Curious to see what Bosh maintainers have to say.

**Comment by keithkroeger** [comment]
Hi @MattSurabian I assume you're using the bosh v1 cli `bosh backup` [https://bosh.io/docs/director-backup.html] for this work, correct.

We are attempting bbr, but receiving `finding scripts failed on bosh/0: sudo: no tty present and no askpass program specified - exit code 1`  in response to `./bbr director --key openstack/id_rsa  --username vcap --host $BOSH_ENVIRONMENT pre-backup-check`

Our bosh director was deployed using create-env

**Comment by MattSurabian** [comment]
Yah I wouldn't want to add NOPASSWD sudo on the director. Unfortunately I've not been using `bosh backup` so my experience won't be of any use on that error. I've only connected to postgres and dumped the database used by the director. So doing a backup totally out of band. Like I said, probably not what you should be looking at doing, but it has worked, so there's that as a last resort.

**Comment by MattSurabian** [comment]
I should also mention that I've moved all statefull things off the director like the registry so the director has nothing locally to persist.

**Comment by drnic** [comment]
If you'd like to explore using `bbr backup`, perhaps try deploying BOSH via https://github.com/starkandwayne/bucc which will pre-configure BBR within your director VM to be ready to go.

* https://www.starkandwayne.com/blog/bucc-bbr-finally/
* https://www.starkandwayne.com/blog/is-bucc-is-better-than-raw-bosh-cli/

Then either continue with BUCC; or borrow/explore the operator files in `state/manifests` that add BBR to your VM.

**Comment by cppforlife** [comment]
@keithkroeger 

> It looks like BBR is the way to go here. Is that the preferred option? I've seen references to bosh backup but this option doesn't seem to be available in bosh v 2.0.48

yup, bbr is the preferred option. we have opted into not keeping `bosh backup` command as it was not anythign else on top of bbr functionality.

**Comment by keithkroeger** [comment]
Thank you @cppforlife 

In that case, do you see a solution to our error `finding scripts failed on bosh/0: sudo: no tty present and no askpass program specified - exit code 1`?

It appears we have to edit the SUDOERS to not require a password for vcap.

We've done this manually to get a backup to run, but this isn't sustainable as we'd need to do this every time the bosh director is re-created.

**Comment by mfine30** [comment]
@keithkroeger `bbr` has two options for how you execute a backup/restore - for a bootstrapped VM like director, or for VMs which are part of a BOSH deployment. It sounds like you may be backing up a boostrapped VM like director, and in this case you need to be sure to provision a sudo, passwordless user for backup purposes. The [user_add job](https://github.com/cloudfoundry/os-conf-release) might be useful to you.

**Comment by keithkroeger** [comment]
Thank you, @mfine30.  That helps a lot!
