### ISSUE TITLE
Support for ESXI Free edition

### ISSUE THREAD

**Issue by whgibbo** [cloudfoundry/bosh#1920]
Hi,
Was wondering if ESXI free edition was support and if so is there any documentation for it ?
As all references I've seen refer to VCenter.

Thanks

**Comment by cppforlife** [comment]
@whgibbo we currently only support vcenter api via vsphere cpi (https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/). one could write a pure esxi cpi, but im not aware of anyone who's done it already.

**Comment by cppforlife** [comment]
closing for now. feel free to reopen.
