### ISSUE TITLE
Utilise all space when formatting persistent and ephemeral disks

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry/bosh#1922]
When disks get formatted, `5%` of the blocks are left reserved. This is a safe default if the partition is used for the OS, but it's wasteful for large disks used solely for storage: e.g. ~50GB is wasted when using 1TB persistent disks.

This has been on my mind for many years now, couldn't find an issue for it. Feel free to close if it's not relevant or interesting.

**Comment by voelzmo** [comment]
See also: https://github.com/cloudfoundry/bosh-agent/issues/89

**Comment by gerhard** [comment]
Thanks! Dupe, closing.
