### ISSUE TITLE
"Error: name and version and cpi unique" on concurrent deployments

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/bosh#1924]
We trigger several BOSH deployments on new stemcell versions. When multiple deployments run at close to the same time and try to upload stemcells, all but one fail with `Error: name and version and cpi unique`. I think we can do better: if a deployment wants to upload a stemcell that already exists, it should just use the existing stemcell.

This might be a race condition in `UpdateStemcell.perform` at https://github.com/cloudfoundry/bosh/blob/b5dbaaa5a2cb20f26cf0a5b5ec0a2cf12505ceb4/src/bosh-director/lib/bosh/director/jobs/update_stemcell.rb#L92-L104. It looks like we look up the stemcell, then attempt to create if it doesn't exist. Instead, we might want to attempt to create the stemcell, then rescue on uniqueness violations.

**Comment by cppforlife** [comment]
@jmcarp is this from master?

**Comment by jmcarp** [comment]
@cppforlife we're using bosh 265.2.0 from bosh.io, but I think we've been seeing this behavior for a while.

**Comment by voelzmo** [comment]
@cppforlife  Hasn't this been an error ever since? I remember we encountered https://github.com/cloudfoundry/bosh/issues/1169 quite a while ago (and even had some proposed fix up for discussion, which was never merged)

**Comment by cppforlife** [comment]
@jmcarp i would recommend working around it for now. it's in the queue to be solved but not going to happen in next few weeks.

**Comment by jfmyers9** [comment]
Closing this as a duplicate of #1169. Please feel free to reopen if you have further questions.

Best,

@jfmyers9 && @jaresty, CF BOSH
