### ISSUE TITLE
Deploying bosh Environment in aws

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/bosh#1927]
1) I have create a base OS in aws.
2) From the Base OS bosh environment has been boot strapped.
3) Two Vm has been created bosh/0 and jumpbox, through
4) For Deploying Clound foundry components i have executed  the following command on the base OS in aws
bosh -e YOUR-ENV log-in
5) Then Cloud foundry environment has been created, i have executed all command we is used to created the cloudfoundry environment on the base OS.

My Question.
What is the use of the bosh environment(bosh/0 and jumpbox), because all the apps are deployed on cloud foundry

**Comment by drnic** [comment]
In this video is an explanation of a jumpbox vs bosh vs deployments like CF https://youtu.be/aDg9kuv6hjg

**Comment by wilfredwilly** [comment]
yes thanks a lot
