### ISSUE TITLE
Unable to stop CF EC2 instances on AWS using bosh

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/bosh#1931]
Hi,

We have deployed CF on AWS using BBL and cf-deployment. It works fine and we are able to deploy applications as well. Now we would like to stop the CF AWS instances when not in use. But this doesnt work.

Steps we follow are

1) Stop the instance using bosh stop (without the --hard option). The instance state changes to stopped when we try 'bosh instances'
2) This does not change the AWS state and it shows the EC2 instance as running. Probably this is expected behavior?
3) We then try to stop the Ec2 instance from AWS console. While it stops the instance, it spins up a new one. And during this time, the bosh instance that was earlier in 'stopped' state changes from 'stopped' to 'unresponsive agent' to 'running'

What is a clean way to stop the CF EC2 instances, so we dont incur cost when these instances are not in use.

**Comment by apsraps** [comment]
Thanks for the response. Yes, this is a development environment. And we had run into some issues with hard stop few days ago and could not resurrect with bosh start, bosh cck etc and had to do the setup all over again. We can try this again now and see if we run into that issue again.

**Comment by cppforlife** [comment]
bosh start --hard as jamil mentioned is the official way for temporarily stopping vms. i would recommend  opening issue with a particular release or deployment (like cf-deployment) if it doesnt gracefully stop. 

feel free to also reopen this issue if you have more info about trouble with stop --hard.
