### ISSUE TITLE
HealthMonitor generates scan and fix tasks which do not get fixed 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#1936]
BOSH version 265.1.0

During a deployment the director waits for all agents to start. If at this point a timeout happens the deployment fails. For such a deployment HM will generate resurrection alerts (see [here](https://github.com/cloudfoundry/bosh/blob/2dc13229f42e96eca9f6abb85437fbb9fd10a1ae/src/bosh-monitor/lib/bosh/monitor/instance_manager.rb#L117)). The resurrector creates `scan and fix` jobs for these alerts. The `scan and fix` jobs can't the issue because at this [line](https://github.com/cloudfoundry/bosh/blob/2dc13229f42e96eca9f6abb85437fbb9fd10a1ae/src/bosh-director/lib/bosh/director/problem_scanner/vm_scan_stage.rb#L25) [`expects_vm?`](https://github.com/cloudfoundry/bosh/blob/2dc13229f42e96eca9f6abb85437fbb9fd10a1ae/src/bosh-director/lib/bosh/director/models/instance.rb#L169) returns `false` and all VMs are filtered out. It returns `false` because the `lifecycle` of the job is `nil`.  

Is there a reason why the [`analyze_agent`](https://github.com/cloudfoundry/bosh/blob/2dc13229f42e96eca9f6abb85437fbb9fd10a1ae/src/bosh-monitor/lib/bosh/monitor/instance_manager.rb#L106) doesn't check the `expects_vm?` state like [`analyze_instance`](https://github.com/cloudfoundry/bosh/blob/2dc13229f42e96eca9f6abb85437fbb9fd10a1ae/src/bosh-monitor/lib/bosh/monitor/instance_manager.rb#L157) does?

**Comment by cppforlife** [comment]
> Is there a reason why the analyze_agent doesn't check the expects_vm? state like analyze_instance does?

if that information is available i dont see a reason why not.

**Comment by mfine30** [comment]
Closing/re-opening to make a github story. @voelzmo is this something you all are interested in owning?

**Comment by jfmyers9** [comment]
Hi @beyhan,

Is this still an issue on the latest version of the BOSH director? If so, could you give us some specific steps to reproduce this issue? 

We've tried recreating this on initial deploys, upgrade deploys, etc and still haven't been able to see the HM create a large number of alerts.

Let us know if you have any other questions.

Best,

@jfmyers9 && @jaresty, CF BOSH

**Comment by pivotal-mp** [comment]
We'll close this for now. Please let us know if you want to re-open it.

Best,
@pivotal-mp && @dpb587-pivotal

**Comment by beyhan** [comment]
Hi @jfmyers9,

Sorry, I couldn't get back to this issue. It's OK to close it and will reopen it if needed. I still think that the issue exists but didn't observed it for a while.
