### ISSUE TITLE
The director's nginx is unable to write to /var/vcap/packages/nginx/logs/error.log

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/bosh#1941]
I found the following error message in `/var/vcap/sys/log/director/nginx.stderr.log`:

```
nginx: [alert] could not open error log file: open() "/var/vcap/packages/nginx/logs/error.log" failed (13: Permission denied)
```

I suspect this error happens because of the permission hardening in the 3541.x stemcells.

```
# ls -la /var/vcap/packages/nginx/logs/
total 8
drwxr-xr-x 2 root root 4096 Apr  7 05:01 .
drwxr-xr-x 6 root vcap 4096 Apr 24 14:14 ..
```

Versions:
BOSH: 265.2.0
Stemcell: 3541.12

I'm not sure whether this is a problem with the Nginx package or how BOSH configures it.

**Comment by bandesz** [comment]
I did some digging and the Nginx error log file is configured as `/var/vcap/sys/log/director/error.log` and Nginx is able to write to it. I wasn't able to find why is the other error.log being created.

**Comment by cppforlife** [comment]
on master we've switched to bpm. i see:

```
bosh/0:/home/jumpbox# cat /var/vcap/sys/log/director/nginx.err.log
nginx: [alert] could not open error log file: open() "/var/vcap/packages/nginx/logs/error.log" failed (30: Read-only file system)
```

it's probably some default configuration of nginx before it gets reconfigured to use `error_log`. @cunnie do you know if this is a similar problem in nginx-release?

**Comment by cunnie** [comment]
I had a similar problem with stemcell hardening on the community release, but it was about reading the server root (nginx returned 403 forbidden). Fixed by running as group `vcap`:

https://github.com/cloudfoundry-community/nginx-release/commit/42934d20de046d992f317245fda72dbdd07ff3fe

**Comment by voelzmo** [comment]
@cppforlife is correct. IIRC, this was even researched by the BOSH team by looking at the nginx code some time ago. All log messages make it to the correctly configured error.log, it is just that nginx tries to open the default error log before reading the configuration about a error.log location different from the default.

**Comment by cunnie** [comment]
For the record, I don't see `nginx: [alert] could not open error log file: open() "/var/vcap/packages/nginx/logs/error.log" failed (30: Read-only file system)` in my community nginx logs:
```
sudo grep "could not" /var/vcap/sys/log/nginx/*
# no output
```
