### ISSUE TITLE
CIDs may exceed 255 chars

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh#1942]
it appears that sometimes CIDs may exceed 255 chars which then will be truncated by the DB.

https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/77

**Comment by Lafunamor** [comment]
Can this be fixed using a schema migration?

**Comment by cppforlife** [comment]
@Lafunamor yup, it could. it would probably involve altering tables to change column type.

**Comment by mfine30** [comment]
Closing and re-opening to trigger a github issue

**Comment by Lafunamor** [comment]
This issue should not be closed if it's not fixed. Please remove reconfigure the bot to not just auto close all issues.
