### ISSUE TITLE
BOSH's plan for non-xenial stemcell support

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/bosh#1944]
Hi BOSH team,

What is the current plan for supporting non-xenial stemcells once the xenial line is released? The Garden team is trying to figure out whether or not we will have customers using non-xenial stemcells at some point in the future (i.e. will customers have an *option* to opt in to using non-xenial stemcells and if so how long for?)

Thanks!
CF Garden Team

**Comment by cppforlife** [comment]
@BooleanCat we are planning to continue to support ubuntu trusty stemcells for some time (at least 6 months) hopefully giving enough time to migrate.

**Comment by BooleanCat** [comment]
Thanks.
