### ISSUE TITLE
The director name should be exposed to Bosh jobs

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/bosh#1945]
We have received a request to differentiate between Bosh directors based on the director name. It would be ideal if that differentiation could take place without operators having to re-define it in every manifest that uses it. Ideally this would be taken from the 'spec' object is spec.director_name.

**Comment by cppforlife** [comment]
need to decide whether it's director name or director guid that we would want to use here. cc @emalm @coreyti

**Comment by Benjamintf1** [comment]
Any reason not to do both?

**Comment by emalm** [comment]
Is either value mutable for a given director?

**Comment by cppforlife** [comment]
@emalm director uuid isnt not changeable, but director name could be changed, though it has some downstream side effects (like renaming credhub entries, etc.)

**Comment by emalm** [comment]
This feature plus adoption by existing components that forward BOSH VM metrics could help operators distinguish between VM metrics when aggregated from several different directors (as happens in the Diego CI accounts), but for that we'd really just like the director UUID and/or name tagged on the metrics when they come out of the health monitor.

/cc @cloudfoundry/cf-diego

**Comment by mfine30** [comment]
Closing and re-opening to make a tracker story

**Comment by mfine30** [comment]
Seems related to: #2077

**Comment by Benjamintf1** [comment]
@mfine30 This isn't actually really related. If you have a field in various deployments for the director name, you're still required to enter it into multiple manifests. There IS a source of truth for the director name, but the bosh director is not giving releases or deployments access to this information without redundancy. As on demand service brokers become more and more relevant, this is even more necessary.
