### ISSUE TITLE
Should the bosh-agent have a higher CPU priority than BOSH release jobs?

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry/bosh#1949]
`monit` gets started with `exec nice -n -10` which results in all processes started by monit inheriting this priority, meaning all release jobs.

`bosh-agent` also gets started with `exec nice -n -10`, meaning that it has the same CPU priority as all release jobs.

In the context of cf-rabbitmq-release, it has been observed via https://www.pivotaltracker.com/story/show/157422399 that VMs under load result in the `bosh-agent` becoming unresponsive and HM re-creating the VM. This is bad, because the CPU is genuinely contended. Re-creating the VM makes matters worse, especially for distributed stateful systems such as RabbitMQ.

What are your thoughts @cppforlife on using `exec nice -n -15` for `bosh-agent`?

cc @dlresende @michaelklishin @dumbbell

**Comment by cppforlife** [comment]
i agree with above assessment.

**Comment by luan** [comment]
closing this since cloudfoundry/bosh-linux-stemcell-builder#70 was merged.
