### ISSUE TITLE
Improve Heartbeat Reporting - Green, Red, Orange

### ISSUE THREAD

**Issue by sauravmndl** [cloudfoundry/bosh#1951]
Now BOSH Health Monitor reports two metrics : `system.healthy = 1` for success and `system.healthy = 0` for failure. And status of bosh vms become

- "stopped"
- "starting"
- "running"
- "failing"
- "unknown"

Suppose, there are two jobs running inside vm
1.  A: Web Server --> Serves the actual requests from customers.
2. B: Monitoring or reporting agent --> Send some metrics to an event server.

At the time of bosh deployment if job B fails (may be event server is not reachable or due to some reason it crashed), the whole vm is flagged as failing and so is whole deployment.
So, even though core functionality of the bosh deployment works perfectly fine, for an insignificant or less significant job, whole deployment is marked as failed.

This behaviour of bosh deployment sometime halts production shipment as it doesn't pass the Q-gate.
**Proposed solution:**
In addition to above mentioned state, another state can be introduced: 'warning' or equivalent.
And in deployment manifest in the jobs which are less significant or okay to fail can be marked, then agent can report the status as 'warning' and `system.healthy = 1`. So, deployment status can be flagged as passed and a warning message can be shown or printed below saying  job B is failing with error description, please take care of it.

**Comment by voelzmo** [comment]
/cc @coreyti
We talked about more granular health metrics at some point, do you remember?

**Comment by cppforlife** [comment]
@voelzmo how can we better integrate with external systems (such as prometheus/grafana) to delegate most of the monitoring responsibility.

**Comment by mfine30** [comment]
This might be an upcoming track of work in the next few months. Could you provide more information about use cases so we can help include those when making decisions?
