### ISSUE TITLE
Validate Cloud Config Networks Before updating cloud config

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1952]
We had a bad network definition added to our cloud config, and then uploaded, related to a new network being added in a new deployment. A second track of work then tried to deploy a separate deployment unrelated to that network, but got the error message 
`Error: Invalid gateway for network 'bad-network-definition': can't be the network id` when trying to deploy.

It would be nice if the cloud config could be validated for things like this prior to accepting it in the `bosh update-cloud-config` call.

**Comment by cppforlife** [comment]
i wonder if some additional validation logic could be added based on a type of a config server side such that it would prevent saving of particular config types. for custom configs i could imagine adding a webhook of some sort (may be via its own config type).

cc @voelzmo

**Comment by mfine30** [comment]
This does seem like something that would be valuable. Unfortunately it also has quite a lot of nuances as I start to think about it more. As a result, we're unlikely to get to it in the near future so I'm going to close this issue. If you are interested in continuing the conversation, feel free to re-open.
