### ISSUE TITLE
config_server urls get truncated when they don't end in trailing slashes

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/bosh#1953]
We encountered a bug recently where a user configured their director with a config server URL like `https://localhost:80/api`. BOSH then uses URL join to add on `/v1/data` and was ending up with `https://localhost:80/v1/data`. It seems like it should have ended up with `https://localhost:80/api/v1/data`.

This seems to be the relevant code: https://github.com/cloudfoundry/bosh/blob/0a827060abf5361decf44e64a3fdacec6cc45bd7/src/bosh-director/lib/bosh/director/config_server/config_server_http_client.rb#L13

**Comment by dpb587-pivotal** [comment]
It does seem like we default to [`/api/`](https://github.com/cloudfoundry/bosh-deployment/blob/90bac489919fd4512bc9bb4d24070d71b07cd586/credhub.yml#L49) in bosh-deployment. I think it makes sense for director to suffix with a `/` if it's not already there.

**Comment by mfine30** [comment]
Makes sense, seems pretty straightforward. Closing/re-opening to trigger a tracker story.
