### ISSUE TITLE
[GARDEN] Development xenial stemcell for bosh lite

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/bosh#1956]
We at the garden team are trying to ensure xenial compatibility. However we only have a full scale xenial stemcell for gcp. It will be very convenient for us if we had a bosh lite xenial stemcell as well. Can you give us the one you are using for development?

Thanks :)

**Comment by drnic** [comment]
Try:

bosh upload-stemcell
https://s3.amazonaws.com/bosh-core-stemcells-candidate/warden/bosh-stemcell-1.102-warden-boshlite-ubuntu-xenial-go_agent.tgz

**Comment by georgethebeatle** [comment]
Thanks for the link, but is this the latest release? How do we know when there is a new one?

**Comment by cppforlife** [comment]
xenial v40 is on bosh.io
