### ISSUE TITLE
Should we remove default number of workers in monit scripts

### ISSUE THREAD

**Issue by degaurab** [cloudfoundry/bosh#1960]
We have default value for workers in spec, do we need to hardcode number of workers again in monit script.

spec: https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L74-L76
monit script: https://github.com/cloudfoundry/bosh/blob/master/jobs/director/monit#L7

**Comment by cppforlife** [comment]
yup, should just be in the spec.
