### ISSUE TITLE
How to update settings.json in the managed vm

### ISSUE THREAD

**Issue by aad** [cloudfoundry/bosh#1961]
Hi,

Not sure whether it should be raised here or bosh-agent.

We are trying to migrate our director compiled_package_cache s3-compatible bucket (not only the name but also the endpoint etc) from current one to a new one.

After bosh director updated successfully, we found that below settings in the managed vms are still the old ones - which results in issue when there is a need to do the s3 upload (for instances a new release with new compiled packages). We did another test by spinning up a new vm without any other changes, the result shows that the new vm has the updated settings.

- /var/vcap/bosh/settings.json
- /var/vcap/bosh/etc/blobstore-s3.json

I want to confirm whether this is the expected behaviour and what's the practice the update these setting after a compiled_package_cache settings change (seems restart agent can regenerate the blobstore-s3.json if settings.json has been updated in advance)?

Thanks!

**Comment by cppforlife** [comment]
@aad you ll have to recreate vms.

**Comment by aad** [comment]
Thanks!
