### ISSUE TITLE
Update nginx to new 'mainline' version, as current one is 'deprecated'

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1964]
Let's update nginx to 1.13.x or 1.14.x. The currently used version 1.12.x is deprecated and hasn't been updated since October 2017: http://nginx.org/en/download.html

Without even mentioning security fixes: looking at the changelogs of 1.13 or 1.14 and grepping for `segmentation fault` shows a few fixes that we'd want to have, I guess.

/cc @cppforlife @dpb587-pivotal

**Comment by dpb587-pivotal** [comment]
Switching to 1.13.x mainline makes sense to me. I don't recall hearing about issues with segfaults, but doesn't hurt to have fixes for them.

**Comment by dpb587-pivotal** [comment]
🔗 Pivotal Tracker: [Story #158016488](https://www.pivotaltracker.com/story/show/158016488)

**Comment by voelzmo** [comment]
Seems like nginx has been updated to 1.14 with https://github.com/cloudfoundry/bosh/commit/37156d3851824509069872eb0209f74d4606cc1f
