### ISSUE TITLE
bosh deploy --dry-run changes deployment releases

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/bosh#1966]
Hi,

we use `bosh deploy --dry-run` to validate that our BOSH deployments, which are executed by our CI/CD system, are working in a pre run. This pre-run will always be executed against our next version of deployment-manifests and should validate if there are incompatibilities in our operation files.

Our expectation of `bosh deploy --dry-run` was that the deploy command will be executed under realistic circumstances (applying ops files and checking if variables can resolve) but without changing the _upstream deployments_. The last requirement is very important since we are running `bosh deploy --dry-run` against production environment, which can not be changed without customers permission.

We observed that after the execution of `bosh deploy --dry-run` the deployments referenced double release version.

Every `bosh deploy --dry-run` which would update a deployment release version, added this release version to the deployment next to the old release version.

This can lead to a critical problem in production environments considering the following use case:
[1] The CI/CD deploys deployment manifest versions v1.0.0
[2] The CI/CD calls `bosh deploy --dry-run` with manifest version v2.0.0 in order to validate that the next update does not contain incompatibilities concerning the operation files or variables.
[3] The configuration of the deployments is adjusted and the CI/CD deploys deployment manifest versions v1.0.0 again to apply the config changes.

Step [3] potentially yields unintended migrations since we can have double release versions after [2] in the upstream bosh deployments of manifest version v1.0.0.

If a manifest in version v1.0.0 does reference a release using the version constraint `latest`, an update of this release version will happen upon [3] which can cause downtime on production environments and inconsistent state of the environment.

 _upstream deployments_ - deployments that are currently deployed on our productive environments

**Comment by mfine30** [comment]
@gdenn thanks for the verbose problem statement. We're actively looking into ways of addressing this and improving it. Hopefully you'll start seeing some improvements in this area in future releases of the BOSH director. I'm going to close it for now since it's an active stream for the team, but feel free to re-open if you have additional thoughts.

**Comment by julweber** [comment]
Hi guys,

Is there a possibility to add a real dry-run feature to only check what would be deployed using the given manifest?

For CI scripting this would be very handy. In principle the same as a terraform plan for BOSH.

Cheers,
Julian
