### ISSUE TITLE
As a release author I am unable to refactor common ruby logic in my erb templates.

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh#1972]
I encountered a situation where I have five templates all having similar ERB logic.

ie.
```
<%
def format(s)
  ....
end
%>
<%= format(some-property) %>
```

I'd like the ability to place this `format` function into a separate helper file? for the purposes of reducing duplication in my templates.

**Comment by cppforlife** [comment]
@dprotaso i could see adding a way to do so. not currently possible since each template is being rendered in isolation in memory.

**Comment by mfine30** [comment]
This does seem like a nice one to add, but would be pretty low priority. I'll close/re-open the issue to trigger a story, but we're probably not going to get to it super soon. 

If the community is interested in this functionality, someone could propose an interface/solution and potentially it in.
