### ISSUE TITLE
Deploying BOSH with Stemcell in Windows environment. ( Windows2012R2 )

### ISSUE THREAD

**Issue by JY-Lee** [cloudfoundry/bosh#1973]
Hi,

I have some issues **deploying BOSH with Stemcell in Windows environment**.

This manifest file have successfully deployed BOSH with Stemcell on Ubuntu environment.
#########################
name: bosh

releases:
- name: bosh
  url: file:////home/cloud/boshtest/release/bosh-264.7.0.tgz
- name: bosh-azure-cpi
  url: file:////home/cloud/boshtest/release/bosh-azure-cpi-release-35.0.0.tgz

resource_pools:
- name: vms
  network: public
  stemcell: 
    url: file:////home/cloud/boshtest/stemcell/bosh-stemcell-3468.21-azure-hyperv-ubuntu-trusty-go_agent.tgz
  cloud_properties: 
    instance_type: Standard_A2
  env:
    bosh:
      password: $6$zifKNbTYvL$WlAtqYa....

disk_pools:
- name: disks
  disk_size: 40960

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    static: [10.0.0.6]
    dns: [8.8.8.8]
    cloud_properties: 
      virtual_network_name: virtual-net
      subnet_name: bosh-net
- name: public
  type: vip

instance_groups:
- name: bosh
  instances: 1
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: azure_cpi, release: bosh-azure-cpi}
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: private
    static_ips: [10.0.0.6]
    default: [dns, gateway]
  - name: public
    static_ips: [((external_ip))]
  properties:
    nats:
      address: 10.0.0.6
      user: nats
      password: nats-password
      tls:
        ca: ((nats_server_tls.ca))
        client_ca:
          certificate: ((nats_ca.certificate))
          private_key: ((nats_ca.private_key))
        server:
          certificate: ((nats_server_tls.certificate))
          private_key: ((nats_server_tls.private_key))
        director:
          certificate: ((nats_clients_director_tls.certificate))
          private_key: ((nats_clients_director_tls.private_key))
        health_monitor:
          certificate: ((nats_clients_health_monitor_tls.certificate))
          private_key: ((nats_clients_health_monitor_tls.private_key))
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres
    blobstore:
      address: 10.0.0.6
      port: 25250
      provider: dav
      director:
        user: director
        password: director-password
      agent:
        user: agent
        password: agent-password
    director:
      default_ssh_options:
        gateway_host: ((external_ip))
      address: 127.0.0.1
      name: bosh
      db: *db
      flush_arp: true
      enable_post_deploy: true
      generate_vm_passwords: true
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      workers: 4
      local_dns:
        enabled: true
      events:
        record_events: true
      ssl:
        key: ((director_ssl.private_key))
        cert: ((director_ssl.certificate))
      user_management:
        provider: local
        local:
          users:
          - name: admin
            password: admin
          - name: hm
            password: hm-password
      cpi_job: azure_cpi
    hm:
      director_account:
        user: hm
        password: hm-password
        ca_cert: ((director_ssl.ca))
      resurrector_enabled: true
    ntp: &ntp
    - 0.pool.ntp.org
    agent:
      mbus: nats://nats:nats-password@10.0.0.6:4222
    registry:
      address: 10.0.0.6
      host: 10.0.0.6
      db: # todo remove
        host: 127.0.0.1
        user: postgres
        password: postgres-password
        database: bosh
        adapter: postgres
      http:
        user: registry
        password: registry-password
        port: 25777
      username: registry
      password: registry-password
      port: 25777
    azure: &cpi_conf
      environment: AzureCloud
      subscription_id: XXXXX-XXXX-XXXXX-XXXXX
      tenant_id: XXXXX-XXXX-XXXXX-XXXXX
      client_id: XXXXX-XXXX-XXXXX-XXXXX
      client_secret: XXXXX-XXXX-XXXXX-XXXXX
      resource_group_name: azure-resoureceGorup
      storage_account_name: windowts
      default_security_group: bosh-security
      ssh_user: vcap
      ssh_public_key: ssh-rsa AAA.....

cloud_provider:
  mbus: https://mbus:mbus-password@((external_ip)):6868
  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
    azure: *cpi_conf
  template:
    name: azure_cpi
    release: bosh-azure-cpi
  ssh_tunnel:
    host: ((external_ip))
    port: 22
    user: vcap
    private_key: /home/cloud/.ssh/azure_pub
#########################

However, 
if i deploy after editing the path from
    url: file:////home/cloud/boshtest/stemcell/bosh-stemcell-3468.21-azure-hyperv-**ubuntu-trusty**-go_agent.tgz 

to
    url: file:////home/cloud/boshtest/stemcell/light-bosh-stemcell-1200.19-azure-hyperv-**windows2012R2**-go_agent.tgz

An error occurs as below.
#########################

Started validating
  Validating release 'bosh'... Finished (00:00:01)
  Validating release 'bosh-azure-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:02)

Started installing CPI
  Compiling package 'ruby-2.4-r3/8471dec5da9ecc321686b8990a5ad2cc84529254'... Finished (00:01:31)
  Compiling package 'bosh_azure_cpi/ceb90b730e4e350787d1be2b81bb97b433549f3f'... Finished (00:00:34)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'azure_cpi'... Finished (00:00:00)
Finished installing CPI (00:02:06)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-azure-hyperv-windows2012R2-go_agent/1200.19'... Finished (00:00:20)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'bosh-light-stemcell-e391a89e-1953-4f64-b0da-d02cc13caed4'... Finished (00:04:25)
  Waiting for the agent on VM 'agent_id:117a4d15-c2bd-4725-7ce1-d48fa3f1ee0a;resource_group_name:azure-resoureceGorup;storage_account_name:windowts' to be ready... Failed (00:08:30)
Failed deploying (00:12:56)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Starting SSH tunnel:
        Starting SSH tunnel:
          Failed to connect to remote server:
            dial tcp ((external_ip)):22: getsockopt: connection timed out

Exit code 1

#########################

I could not find any solutions from offical website or Git Guide docuemnts on this issue regarding **BOSH deployment with Stemcell in Windows2012R2** .

Also,
Is deploying windows stemcell supported in any other IaaS env like AWS or GCP?
also, if this is not  supported by 'create-env', is it supported by 'bosh-init'?

and,
Is it possible to deploy CF & Deigo by installing BOSH in Ubuntu Stemcell and have Window Stemcell uploaded?

Your comments would be appreciated.  Thank you in advance.

**Comment by dpb587-pivotal** [comment]
Hello - some notes in response to your questions...

First, the BOSH director is only supported on Ubuntu stemcells (Windows will not work work). You'll need to switch back to using Ubuntu to get BOSH started. Once you have BOSH running, you can use it to deploy VMs using whichever operating system you prefer.

More specifically, I would strongly recommend deploying BOSH with [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment). It is a good, recent, secure starting point for your director. It looks like you are using an older manifest, and not sure where it came from.

Regarding Windows stemcell on other IaaSes, yes, Windows 2012R2 is currently published on Amazon Web Services, Google Cloud Platform, and Microsoft Azure ([see here](http://bosh.io/stemcells#windows2012R2)). Due to licensing constraints, if you're interested in using it on other IaaSes (such as VMware vSphere), you can build the stemcell yourself in your environment. Instructions for this are [documented here](https://github.com/cloudfoundry-incubator/bosh-windows-stemcell-builder/wiki/Creating-a-vSphere-Stemcell-by-Hand).

Regarding Diego and Windows, yes, you can deploy CloudFoundry with cells using multiple stemcells such as Ubuntu and Windows. For some examples of that, I'd recommend checking out [cloudfoundry/cf-deployment](https://github.com/cloudfoundry/cf-deployment), specifically the [windows2016-cell.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/windows2016-cell.yml) ops file.

**Comment by mfine30** [comment]
Hi again,

Looks like this issue has been open for a little while now. I'm going to go ahead and close it. If it's still an issue, feel free to re-open.
