### ISSUE TITLE
Retain bosh manifest from create-env actions

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1974]
Would it be possible to add a feature to create-env that would stick the manifest used to deploy via `create-env` onto the VM/VMs that was/were deployed? This would make it a lot easier to sanity-check overhauls to ops files, deployment pipelines, or major upgrades, via a diff of old manifest vs new (a poor man's deployment diff for create-env based deploys).

**Comment by cppforlife** [comment]
@geofffranks im not too hot about adding such feature as it would mean we would have to keep sensitive info in state file. you can already do something like this yourself but using bosh interpolate to generate manifest, saving it somewhere safe (dependent on your environment), and then using it with bosh create-env.

**Comment by geofffranks** [comment]
That’s what we ended up doing as a stop gap. No worries.

**Comment by freddesbiens** [comment]
Closing this issue as the proposed workaround was useful and the new feature requested could have been a security risk.
