### ISSUE TITLE
Large BOSH deployments failing with latest director version 266.2.0, possible DB schema problem?

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/bosh#1975]
BOSH version: `266.2.0`
Deployment: `Cloud Foundry`

We just upgraded our BOSH director from 265.2.0 to the latest version 266.2.0. But since this upgrade it is not possible anymore to deploy or modify our Cloud Foundry deployment.
Upon trying to deploy we get the following error message:
```
Task 6993 | 13:59:25 | Preparing deployment: Preparing deployment (00:02:31)
                     L Error: 765: unexpected token at '{"mapped_properties":{"consul":{"agent_cert":"-----BEGIN CERTIFICATE-----\nMIIEKTCCAhGgAwIBAgIRANOnpq2Z73OldyoTTlykphkwDQYJKoZIhvcNAQELBQAw\nFjEUMBIGA1UEAwwLYW1jX3Jvb3RfY2EwHhcNMTcxMjA1MTI0MzA4WhcNMzcxMjA1\nMTI0MzI4WjAXMRUwEwYDVQQDDAxjb25zdWxfYWdlbnQwggEi'
Task 6993 | 14:01:56 | Error: 765: unexpected token at '{"mapped_properties":{"consul":{"agent_cert":"-----BEGIN CERTIFICATE-----\nMIIEKTCCAhGgAwIBAgIRANOnpq2Z73OldyoTTlykphkwDQYJKoZIhvcNAQELBQAw\nFjEUMBIGA1UEAwwLYW1jX3Jvb3RfY2EwHhcNMTcxMjA1MTI0MzA4WhcNMzcxMjA1\nMTI0MzI4WjAXMRUwEwYDVQQDDAxjb25zdWxfYWdlbnQwggEi'

Task 111926 Started  Wed Jun 13 14:07:51 UTC 2018
Task 111926 Finished Wed Jun 13 14:08:06 UTC 2018
Task 111926 Duration 00:00:15
Task 111926 error

Updating deployment:
  Expected task '111926' to succeed but state is 'error'
```

It doesn't matter if it's a completely new deployment, or redeploying an existing deployment manifest that was just downloaded from the director with `bosh -d cloudfoundry manifest > test.yml; bosh -d cloudfoundry deploy test.yml`.
It will show the same error.
The exact same deployment manifest on v265.2.0 works!

My suspicion is that one of the new tables/columns that came with the upgrade & db migrations from 265.2.0 to 266.2.0 is too small to hold all necessary json/yml manifest data.
We are using MySQL as BOSH database backend, and I've seen issues with cloudfoundry/* based software in the past where the assumption about text column sizes in MySQL vs. PostgreSQL was wrong.

Any hints on where to look at, what to fix?

**Comment by JamesClonk** [comment]
It seems to have something to do with the changed links handling inside BOSH.

**Comment by JamesClonk** [comment]
Just confirmed it through testing, it is because of the `link_provider_intents.metadata` column.
The current db schema migration only creates/sets it as a varchar(255), but it needs to be bigger.

I manually solved the problem by running `alter table link_provider_intents modify metadata longtext;` on the BOSH database.

Should probably be added to the db migrations like this:
```
if [:mysql, :mysql2].include? adapter_scheme
      set_column_type :link_provider_intents, :metadata, 'longtext'
end
```
Please add to db schema migrations. 👍

**Comment by Lafunamor** [comment]
this issue is similar to #1942 .
Maybe both can be resolved at the same time

**Comment by dpb587-pivotal** [comment]
Thank you for reporting this! And investigating. We have created a Pivotal Tracker story to [fix this](https://www.pivotaltracker.com/story/show/158330404) and [backport to 266.x](https://www.pivotaltracker.com/story/show/158330426), with a subsequent release.

@Lafunamor, #1942 will probably require a similar change, but for the sake of minimizing the impact of changes and backports, we will resolve that issue separately from this.

**Comment by JamesClonk** [comment]
Thanks, works now! 👍
