### ISSUE TITLE
Deploy fails when bootstrap instance is ignored

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1980]
This line:

https://github.com/cloudfoundry/bosh/blob/9a50fd6753f3ef74d5b2cd4dd310a85374b9f540/src/bosh-director/lib/bosh/director/deployment_plan/instance_plan_sorter.rb#L16

causes `bosh deploy` to fail when `bootstrap_instance_plan` is `nil`, which seems to happen when it has been ignored via `bosh ignore`.

Is it important to retain the deterministic update order where instances in the same AZ as the bootstrap instance get updated before other instances, even when the bootstrap instance itself is ignored? If so, then this method would need another way to know what the bootstrap AZ is since it can't determine it the way it does now by trying to find the bootstrap instance in the argument to `sort`.

**Comment by pivotal-jamil-shamy** [comment]
> Is it important to retain the deterministic update order where instances in the same AZ as the bootstrap instance get updated before other instances, even when the bootstrap instance itself is ignored?
I think it should keep the order of update.

[Reference Tracker Story](https://www.pivotaltracker.com/story/show/158460727)

**Comment by mfine30** [comment]
Thanks for the update @Amit-PivotalLabs. We're tracking the changes for this issue in [this story](https://www.pivotaltracker.com/story/show/158460727)

**Comment by mfine30** [comment]
As @ndhanushkodi said: "THE BOSH IGNORE BUG FOR INSTANCE 0 HAS BEEN FIXED IN DIRECTOR VERSION 266.12, 267.07, and 268!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

Closing
