### ISSUE TITLE
BOSH `ssh -c` fails to add ssh user

### ISSUE THREAD

**Issue by ndhanushkodi** [cloudfoundry/bosh#1983]
We have a script that runs several `bosh ssh -c` commands in a row. We saw this failure twice so far where it fails to create the ssh user because it can't lock `/etc/passwd`. We've seen this script pass as well, so it's an intermittent failure. We were running this test against a bosh-lite. One other `bosh ssh -c` commands runs directly before this failing command, so we are curious if the previous command failed to release the lock before exiting, causing this command to fail?

Director version: `266.2.0`
CLI version: v4.0.1

```
+ bosh -d cf-mysql ssh mysql/0 -c 'sudo rm /tmp/mysql-backup.tar'
Using environment '35.232.215.96' as client 'admin'

Using deployment 'cf-mysql'

Task 17

Task 17 | 00:25:59 | Error: Action Failed ssh: Creating user: Shelling out to useradd: Running command: 'useradd -m -b /var/vcap/bosh_ssh -s /bin/bash bosh_5046e7df006a477', stdout: '', stderr: 'useradd: cannot lock /etc/passwd; try again later.
': exit status 1

Task 17 Started  Tue Jun 19 00:25:59 UTC 2018
Task 17 Finished Tue Jun 19 00:25:59 UTC 2018
Task 17 Duration 00:00:00
Task 17 error

Setting up SSH in deployment 'cf-mysql':
  Expected task '17' to succeed but state is 'error'

Exit code 1
```

- @ctaymor and Nitya

**Comment by belinda-liu** [comment]
Hi @ndhanushkodi,

This theoretically can happen when multiple `useradd` commands run in parallel. We tried to reproduce this in various ways but couldn't get an error. Are you still seeing this happen?

Thanks,
@belinda-liu && @jfmyers9, CF BOSH

**Comment by mrosecrance** [comment]
Closing as stale
