### ISSUE TITLE
Missing "metadata.google.internal" in /etc/hosts on ubuntu-xenial stemcell on Google

### ISSUE THREAD

**Issue by mikomraz** [cloudfoundry/bosh#1984]
For newly created VM instances on GCP, there seems to be a
`169.254.169.254 metadata.google.internal  # Added by Google`
record in `/etc/hosts`.

The same line is missing in `/etc/hosts` on a freshly instantiated `ubuntu-xenial` (google) VM created by the BOSH director for the purpose of running jobs. Saying said that, it *does* appear after a manual reboot of the machine.

This issue, among other things, prevents running `kubeadm` as it silently fails to resolve the domain and fails to spin required kubernetes-api containers.

**Comment by pivotal-jamil-shamy** [comment]
@mikomraz have you only seen the issue on `ubuntu-xenial` or did it happen also on `ubuntu-trusty` stemcells ?

**Comment by alex-slynko** [comment]
@mikomraz In CFCR we use 169.254.169.254 or <gateway-ip> as DNS in cloud config. It resolves `metadata.google.internal` correctly.

**Comment by mikomraz** [comment]
@pivotal-jamil-shamy I haven't got the chance to check on `ubuntu-trusty`.

@alex-slynko I understand. But in this case I haven't used CFCR, but installed `kubeadm` separately.
So it may be worth to update the default cloud-config in `bosh-deployment`, or better yet, check why the daemons haven't done their job.

**Comment by pivotal-jamil-shamy** [comment]
@mikomraz any new update on this issue ?

**Comment by mikomraz** [comment]
Yes. I confirmed the issue on `ubuntu-trusty` too.

**Comment by freddesbiens** [comment]
Hi @mikomraz.

Normally, the contents of the VM metadata records are meant to be consumed by the BOSH agent. The agent will use the IP address (169.254.169.254) directly in order to bootstrap the VM. What's the use case for the DNS name in your situation?

**Comment by mikomraz** [comment]
Hello @freddesbiens,

The use case is that the package `kubeadm` looks for `metadata.google.internal` and fails to resolve it, consecutively failing to start a cluster.

I am under the impression that the record `169.254.169.254 metadata.google.internal # Added by Google` is standard on GCP compute machines, meant to be consumed by everybody - and not BOSH agent specific. Note that on standard provisioned GCP compute the record always exists, and also that on BOSH stemcells after rebooting (allowing `kubeadm` to succeed in starting a cluster).

Therefore I think it's a bug that the record is missing in the first place.
