### ISSUE TITLE
Team admins should be able to manage disks + delete VMs

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh#1988]
Right now, users with `bosh.teams.myteam.admin` scopes don't have permission to run `bosh disks`, `bosh delete-vm`, `bosh attach-disk`, `bosh delete-disk`, or `bosh orphan-disk` for vms/disks related to deployments owned by their team. It would be nice if they had these abilities

Thanks ❤️

**Comment by freddesbiens** [comment]
Closing and re-opening to get a Tracker story created.
