### ISSUE TITLE
Openstack: Bosh doesn't try to create a new port for the VM when previously used port exists

### ISSUE THREAD

**Issue by kayrus** [cloudfoundry/bosh#1991]
`bosh cck` option doesn't work when an Openstack VM was removed, but the port that was assigned to this VM still exists. In this case bosh complains on:

`Unable to complete operation for network foo. The IP address bar is in use.`

I see two cases:
* Identify whether port is attached and used, if not - recreate.
* Create a new port with a new IP address.

**Comment by voelzmo** [comment]
You are correct, this is the current behavior. We could try to implement option 1 (removing or re-using the port if it is currently not attached to a vm) in https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release. I think the current implementation is still from back in the days, when ports were not a separate entity managed by neutron.

Creating a new port could be an option when dynamic networking relying on OpenStack DHCP is used. In the cases of manual networking, I'd rather not get into picking a new IP address during cck/resurrection.

/cc @cppforlife wdyt?

**Comment by voelzmo** [comment]
Story to make the openstack CPI more resilient against already existing ports: https://www.pivotaltracker.com/story/show/159498851

**Comment by voelzmo** [comment]
Thanks for the reminder, @freddesbiens! The re-use existing ports feature has been released with v40 of the openstack-cpi-release: https://github.com/cloudfoundry/bosh-openstack-cpi-release/releases/tag/v40

Please give the release a try and let us know when this doesn't work for you, @kayrus
