### ISSUE TITLE
Independent deployments fail due to lock on common release

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh#1995]
Two simultaneous deployments were being run that both required the "latest" version of the same bosh-release.

The second deployment failed with 
```
Task 26845 | 20:24:10 | Preparing deployment: Preparing deployment (00:00:41)
                     L Error: Failed to acquire lock for lock:release:ipsec uid: 48601f91-eb20-42e9-ae15-cd02bd0cbe92. Locking task id is 26844
Task 26845 | 20:24:53 | Error: Failed to acquire lock for lock:release:ipsec uid: 48601f91-eb20-42e9-ae15-cd02bd0cbe92. Locking task id is 26844
```
The referenced task 26844 had description `create deployment` and state `processing`.

Desired Behaviour:

1) If the first deployment needed to compile the release, I would expect the second deployment to queue until compilation completed (though https://github.com/cloudfoundry/bosh/issues/1440 referred to a `lock:compile` instead of `lock:release`).

2) If the release was already compiled, I would expect both deployments to continue with non-exclusive read locks on the bosh-release.

**Comment by freddesbiens** [comment]
Closing and reopening for the bot to create a Tracker story.
