### ISSUE TITLE
BOSH deployment diff mistakenly shows interpolated CredHub variables in variables section

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh#1996]
In the `variables` section, the BOSH Director will mistakenly show the uninterpolated CredHub variables as different even though there has been no change.

The remaining sections of the manifests (`azs`, `instance_groups`) are not affected by this bug.

Below is a recurring example from our PWS deployment

```diff
  variables:
  - name: router_ssl
    options:
      alternative_names:
+     - "((system_domain))"
+     - "*.((system_domain))"
-     - run.pivotal.io
-     - "*.run.pivotal.io"
  - name: credhub_tls
    options:
      alternative_names:
+     - credhub.((system_domain))
-     - credhub.run.pivotal.io
-     common_name: credhub.run.pivotal.io
+     common_name: credhub.((system_domain))
  - name: bits_service_ssl
    options:
      alternative_names:
+     - "((system_domain))"
+     - "*.((system_domain))"
-     - run.pivotal.io
-     - "*.run.pivotal.io"
```

This isn't urgent; we have a workaround: we don't use CredHub variable for `((system_domain))` anymore; instead, we place it in a vars file.

/cc @jrussett @jaresty

**Comment by pivotal-jamil-shamy** [comment]
Hey @cunnie , thanks for submitting the issue.
BOSH will not interpolate the variables before displaying the diff (for security reasons); I am a bit surprised that it is showing the diff.
Quick question to understand the flow: did you supply `run.pivotal.io` variable through the CLI `-v option` before, and know you changed it to be supplied by credhub through BOSH ?

**Comment by xtreme-bozhidar-lenchov** [comment]
Sorry about the delay @pivotal-jamil-shamy; Brian rolled off a team a few weeks ago and we've forgotten to follow up on his issue. Spoke with Jesse a bit and we agree, it was surprising to see the diff shown.

We did not provide `run.pivotal.io` as a variable through CLI flags. We are loading a few other variables from credhub into a vars-file, but these do not include ((system_domain)). 

We do a deploy dry-run with the `no-redact` flag to get a deployment diff (to verify manually and put in our communication), before kicking off the deployment itself. The deployment gets kicked off by a `bosh-deployment-resource` in CI, and we don't seem to provide any properties other than `target`, `client`, `client_secret`, `ca_cert`, `deployment` and `manifest`.

Mentioning dry-run in case it's the damp run rearing its head again.

**Comment by cunnie** [comment]
@pivotal-jamil-shamy Sorry, only seeing this now — what Boz said.

**Comment by freddesbiens** [comment]
Closing and re-opening this issue to have a Tracker story created.

**Comment by cunnie** [comment]
Closing. I'm not feeling passionate about this anymore.
