### ISSUE TITLE
How to change the default `.bosh` and `.bosh_virtualbox_cpi` install folders for Bosh Lite

### ISSUE THREAD

**Issue by antonioaguilar** [cloudfoundry/bosh#1997]
This might be an easy one but couldn't find any info on the Bosh docs. I'm running out of space on my linux server and would like to move (or re-install) bosh to a different default folder. Is there an env called $BOSH_HOME or something similar?

**Comment by dpb587-pivotal** [comment]
There is not currently a `BOSH_HOME` environment variable. It does respect the generic `HOME` environment variable, if you want to give that a try. Would that work for you?

**Comment by antonioaguilar** [comment]
@dpb587-pivotal I'm using bosh-lite to do a cf-deployment and unfortunately the `$HOME` environment variable only works for the `.bosh` folder but not for the `.bosh_virtualbox_cpi`. The `.bosh_virtualbox_cpi` is the folder that actually grows larger when doing multiple installs of CF locally. Any suggestions on how to get Bosh to respect the `$HOME` variable for both `.bosh` and  `.bosh_virtualbox_cpi` folders?

**Comment by dpb587-pivotal** [comment]
@antonioaguilar that `.bosh_virtualbox_cpi` path is managed by the underlying CPI. I'd recommend raising an issue in [cppforlife/bosh-virtualbox-cpi-release](https://github.com/cppforlife/bosh-virtualbox-cpi-release) for guidance or to request that feature.
