### ISSUE TITLE
Bosh doesn't show changes to manifest-specific addons in the deployment diff

### ISSUE THREAD

**Issue by henrytk** [cloudfoundry/bosh#2006]
When running `bosh deploy` Bosh prints the diff of the manifest changes. However, when there are changes to manfiest-specific addons (specifically not runtime-config changes) they do not show in the diff. 

I don't know if this is by design, but it breaks my expectation of what I should be seeing, so I am raising it as an issue.

**Comment by voelzmo** [comment]
I guess this is most likely the same issue as described in https://github.com/cloudfoundry/bosh-cli/issues/360

**Comment by henrytk** [comment]
@voelzmo ah yes, good spot. Closing.
