### ISSUE TITLE
BOSH should not recover vms in deployment planned for deletion

### ISSUE THREAD

**Issue by dmitry-bakaleinik-sap** [cloudfoundry/bosh#2008]
Hi,

I've found some behavior in bosh that seems can be improved. When I tried deleting a deployment (with many vms), I got a timeout error from the IaaS that one of the vm removal operation took more time than expected and due to this error the task failed.

```
Task 577

Task 577 | 03:18:18 | Deleting instances: mongodb/38ac2ed9-6224-4bf8-8454-b3c2051662ab (0)
Task 577 | 03:18:18 | Deleting instances: mongodb/c144b289-ac1a-4e16-a43c-e9ba81560b49 (1)
Task 577 | 03:18:18 | Deleting instances: mongodb/3d45b995-5d8d-4c91-874d-8a932def39ef (2)
Task 577 | 03:18:37 | Deleting instances: mongodb/c144b289-ac1a-4e16-a43c-e9ba81560b49 (1) (00:00:19)
Task 577 | 03:18:44 | Deleting instances: mongodb/38ac2ed9-6224-4bf8-8454-b3c2051662ab (0) (00:00:26)
Task 577 | 03:23:43 | Deleting instances: mongodb/3d45b995-5d8d-4c91-874d-8a932def39ef (2) (00:05:25)
                    L Error: CPI error 'Bosh::Clouds::CloudError' with message 'delete i-uf62se1kgt575dzoi2vn failed when stop it: change instance i-uf62se1kgt575dzoi2vn to Stopped timeout' in 'delete_vm' CPI method
Task 577 | 03:23:43 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'delete i-uf62se1kgt575dzoi2vn failed when stop it: change instance i-uf62se1kgt575dzoi2vn to Stopped timeout' in 'delete_vm' CPI method

Task 577 Started  Thu Jul 19 03:18:18 UTC 2018
Task 577 Finished Thu Jul 19 03:23:43 UTC 2018
Task 577 Duration 00:05:25
Task 577 error
```

When I tried to delete deployment again, I've found that it was locked by scan and fix process. The fix process deleted the failed VM and created a new one. So here is the problem. I don't want to get recovery process running for the deployment intended for deletion if something failed. The reasons are simple - it is unnecessary and redundant and may slow down manual removal when it is needed.

Thanks

**Comment by pivotal-jamil-shamy** [comment]
@ninja-at-work there is currently no concept in BOSH where we mark a deployment state for deletion.

For the situation you posted, I see the benefit of telling BOSH to stop the resurrection of VMs in a deployment upon request. There is currently no way to tell BOSH to stop resurrection for a particular deployment through the CLI; there is a way to stop resurrection for all deployments globally, but that would be an overkill/not recommended for a similar situation as the one you posted.

There is a plan to add a resurrection configuration for BOSH that will contain granular controls over resurrection (I think the work on that is in progress). You can check this note containing more details about this new feature https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/resurrection-config.md
