### ISSUE TITLE
BOSH Tasks fail with 502s on Azure

### ISSUE THREAD

**Issue by thisisnotashwin** [cloudfoundry/bosh#2010]
Hey Team. We on the Bosh-windows team have started seeing 502s on some of bosh tasks that we have been running against a newly BBLed BOSH director. This happens particularly often on long running tasks such as uploading heavy stemcells on Azure (The size of a heavy Windows stemcell is about 120GB). We think we started seeing these issues after we upgraded our director from Bosh 265.x version to the Bosh 266.x, but we aren't entirely certain.
While the director does respond with a 502, we have observed the task continuing to work in the background and always succeed as well. We looking into the director logs and found an entry in the `error.log` that corresponds to each `502` response.

```
2018/07/20 19:42:18 [error] 6#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /info HTTP/1.1", upstream: "http://127.0.0.1:25556/info", host: "127.0.0.1:25555"
2018/07/20 19:42:18 [error] 6#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /info HTTP/1.1", upstream: "http://127.0.0.1:25556/info", host: "127.0.0.1:25555"
2018/07/21 16:37:42 [error] 5#0: *69996 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: , request: "GET /tasks/21 HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/21", host: "10.0.0.6:25555"
2018/07/22 14:49:46 [error] 5#0: *90399 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: , request: "GET /tasks/25/output?type=event HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/25/output?type=event", host: "10.0.0.6:25555"
2018/07/22 21:31:20 [error] 5#0: *105463 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: , request: "GET /tasks/26/output?type=event HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/26/output?type=event", host: "10.0.0.6:25555"
2018/07/25 08:29:24 [error] 5#0: *169035 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: , request: "GET /tasks/37/output?type=event HTTP/1.1", upstream: "http://127.0.0.1:25556/tasks/37/output?type=event", host: "10.0.0.6:25555"
2018/07/25 08:34:40 [error] 5#0: *169051 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.5, server: , request: "POST /stemcells?fix=true HTTP/1.1", upstream: "http://127.0.0.1:25556/stemcells?fix=true", host: "10.0.0.6:25555"
```

There seem to be no `ERROR` entries in the director stdout or stderr logs. The only file which shows the 502 response code is the `access.log` as follows:

```
access.log:10.0.0.5 - - [22/Jul/2018:20:49:03 +0000] "POST /stemcells?fix=true HTTP/1.1" 302 0 "-" "Go-http-client/1.1" 286.900 0.970 .
access.log:10.0.0.5 - - [24/Jul/2018:15:18:49 +0000] "POST /stemcells?fix=true HTTP/1.1" 302 0 "-" "Go-http-client/1.1" 392.281 9.437 .
access.log:10.0.0.5 - - [25/Jul/2018:08:14:11 +0000] "POST /stemcells?fix=true HTTP/1.1" 302 0 "-" "Go-http-client/1.1" 84.909 68.201 .
access.log:10.0.0.5 - - [25/Jul/2018:08:34:55 +0000] "POST /stemcells?fix=true HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 266.577 107.849 .
```

As can be seen above, there seems the response times for the requests that 502 are on the eye-wateringly high side. We have seen high `$request_times` with previous successful heavy-stemcell uploads but the `$upstream_response_time`.

Let us know if there is any more data that we can provide that might help debug this.

/cc @zanadar

Cheers,
Your friendly neighborhood BOSH Windows team

**Comment by ashwin-venkatesh** [comment]
More examples from `access.log`:

```
10.0.0.5 - - [20/Jul/2018:20:46:40 +0000] "GET /tasks/15/output?type=event HTTP/1.1" 206 502 "-" "Go-http-client/1.1" 0.006 0.006 .
10.0.0.5 - - [21/Jul/2018:16:37:42 +0000] "GET /tasks/21 HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 81.716 81.716 .
10.0.0.5 - - [22/Jul/2018:14:49:46 +0000] "GET /tasks/25/output?type=event HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 188.190 188.190 .
10.0.0.5 - - [22/Jul/2018:21:31:20 +0000] "GET /tasks/26/output?type=event HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 438.182 438.182 .
10.0.0.5 - - [25/Jul/2018:08:29:24 +0000] "GET /tasks/37/output?type=event HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 74.330 74.330 .
10.0.0.5 - - [25/Jul/2018:08:34:55 +0000] "POST /stemcells?fix=true HTTP/1.1" 502 166 "-" "Go-http-client/1.1" 266.577 107.849 .
```

**Comment by xtreme-jason-smith** [comment]
Hey,

So we spent some more time trying to get to the bottom of this, and I think this might be a problem with resource sharing of sorts. When we try to upload our ~120GB heavy azure stemcell, `tar -d` and `gzip` start running in the director VM which are CPU intensive and can ensure other processes get throttled for the CPU resource. This led to the `puma` webserver seemingly dropping request. Bumping our director VM from a 2 core to an 8 core seemed to rid us of this problem. 

Maybe ensuring the puma process has a high priority might have helped. This might be a problem unique to our team considering the size of the stemcells we have to work with on Azure, but we figured this would be helpful to know in general and it might be something others observe if they run CPU intensive tasks on the director VM.

Feel free to close this issue if that does not seem like as much of a concern.

/cc @ashwin-venkatesh @jfmyers9 @dpb587 @mfine30 

Cheers!!

**Comment by bingosummer** [comment]
I also hit a similar issue. But my case is linux stemcell (3GB). BTW, bosh.io doesn't have heavy stemcell for windows. Is it a new feature?

**Comment by dpb587-pivotal** [comment]
In general, this typically comes down to resource constraints on the VM, and increasing the VM resources (like CPU or disk speed) is typically the cheapest solution. If someone is interested in doing more research about this to narrow it down to disk/CPU/Puma threads/nginx timeouts, please feel free to discuss your findings - there may be better default configurations we can provide.

From this particular case, it seems there were not additional error messages aside from the 502s and upstream closed errors which makes it more difficult. If looking `BOSH_LOG_LEVEL=debug bosh ...` may be useful, or you may want to try playing with some of the pre-defined [director properties](https://github.com/cloudfoundry/bosh/blob/f47dbfb93694d45e1fff370a7a95b55e526e1626/jobs/director/spec#L72-L101). Logs in `/var/vcap/sys/log/director/*` may be useful, or tweaking configs in `/var/vcap/jobs/director/*` might be helpful.

@bingosummer Windows are a bit newer, but the public images only support light stemcells due to the additional licensing requirements being handled by the IaaS.
