### ISSUE TITLE
Feature Request: Filter add-ons at the instance group level

### ISSUE THREAD

**Issue by johannasmith** [cloudfoundry/bosh#2013]
Bosh add-ons can currently only be included or removed at the job level. I would like to be able to include or exclude an add-on based on instance group concerns (e.g. name).

Example:
I have a `loggregator_agent` bosh add-on. I want to write an operations file that will deploy an isolated loggregator, including isolated agents. At the current time, I can only add `loggregator_agent` to every instance group, not selected ones. I would like to be able to add my agent add-on to only to the instance groups I want, so that I'm free to add a separate, isolated agent, to my isolated instance groups (as another filterable add-on).

**Comment by dpb587-pivotal** [comment]
🔗 [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1532549958000483) - original discussion on this

**Comment by dpb587-pivotal** [comment]
🔗 [Story #159376982](https://www.pivotaltracker.com/story/show/159376982)

**Comment by mfine30** [comment]
This was implemented in August, per upstream comments that Danny provided. Closing
