### ISSUE TITLE
Trouble with `vcap` password on AWS stemcells

### ISSUE THREAD

**Issue by aleliaert** [cloudfoundry/bosh#2018]
I wanted to do some troubleshooting on a bosh director in AWS and noticed that I can't get the 'ol `c1oudc0w` to work when sudo-ing on the director as user `vcap`, or by trying to `su - vcap` as a test.  Is the barometric bovine in the AWS stemcells?  Have tried light stemcells 3468.54 and 3586.26.

I also tried to override the password on our director by following [https://starkandwayne.com/blog/hardening-the-vcap-users-password-on-bosh-vms/ ](https://starkandwayne.com/blog/hardening-the-vcap-users-password-on-bosh-vms/) to set a different known password and no luck. 

To override the director vcap password, here are the contents of the ops file being fed to `bosh create-env`:
```
- type: replace
  path: /instance_groups/name=bosh/env?/bosh/password
  value: ((bosh_vcap_password_hashed))
```
And `bosh_vcap_password_hashed` is coming from the output of `echo ${BOSH_VCAP_PASSWORD} | mkpasswd -s -m sha-512`.  Have set `BOSH_VCAP_PASSWORD` to a variety of password options and none have worked.

Any leads?  This might help me m0000ve closer to solving another issue.  I might be at a tipping point.  Sorry I won't try to milk any more puns from this topic.

Thanks!

**Comment by dpb587-pivotal** [comment]
Hi there - I herd I might be able to help with this issue. You're on the right trail with the `env?/bosh/password` approach... but `create-env` is needs a slightly different manifest format. You'll want to steer clear of `instance_groups`, and instead try mooving it into `resource_pools`. Rerun the `create-env` and, after ruminating, you should be able to `sudo apt moo` with your password. Hope this helps you stay upright.

**Comment by aleliaert** [comment]
@dpb587-pivotal - Your tip certainly helped us put this issue out to pasture.  We no longer have a beef with our vcap account.  Farewell cow.  Thanks!
