### ISSUE TITLE
SSH private key format for OpenStack vm needs to be standardized

### ISSUE THREAD

**Issue by JunoJunho** [cloudfoundry/bosh#2020]
When bosh tried to deploy, in OpenStack, director accesses created vms using ssh-private key.

The key director used is normally rsa format because default linux `ssh-keygen` command generates keypair using rsa algorithm.

The result key file format is as follows:

```
-----BEGIN SOMETHING KEY -----
key file length is 65
...
...
-----END OF SOMETHING KEY -----
```

When I tried to use not normalized key, which is all key contents is one line, director cannot access each generated vm. I think bosh needs to standardize key file.

**Comment by dpb587-pivotal** [comment]
@JunoJunho are you referring to [this common error](https://bosh.io/docs/openstack-cpi-errors/#invalid-private-key-file)?

**Comment by dpb587-pivotal** [comment]
This may be fixed by https://github.com/cloudfoundry/bosh-cli/commit/aa7ed25e6cbbe6b07fe6414d5a7993489f5a312d

**Comment by freddesbiens** [comment]
@dpb587-pivotal The change we implemented is to support more recent key formats, but we do nothing to normalize the inputs. @JunoJunho Normally, our recommendation would be to normalize the key yourself before passing it to BOSH. Is there any particular reason why you are using those "one liner" keys?
