### ISSUE TITLE
Bosh with UAA, Credhub, and BOSH for cfcr

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry/bosh#2022]
do we have general manifest for deploying A BOSH Director configured with UAA, Credhub, and BOSH DNS or we have to configure one after another

**Comment by drnic** [comment]
Full walk thru of bosh/uaa/credhub (bucc) and cfcr at https://github.com/starkandwayne/cfcr-compiled-deployment

**Comment by techie20122018** [comment]
why i am getting the cluster ip as 10.100.200.1  , even I am getting the same

$ kubectl get all
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.200.1   <none>        443/TCP   17m

**Comment by h4xnoodle** [comment]
I think the answer above by @drnic is sufficient, and more references for deploying cfcr can be found here https://github.com/cloudfoundry-incubator/kubo-release and here https://github.com/cloudfoundry-incubator/kubo-deployment.
