### ISSUE TITLE
Package blob upload failure leaves bosh director in inconsistent state

### ISSUE THREAD

**Issue by NautiluX** [cloudfoundry/bosh#2023]
During `bosh deploy` we see the following issue:
* If an error happens during release upload (package upload to the blobstore fails) the deployment is cancelled
* Subsequent deployments will assume the release is successfully uploaded, skip the release upload and fail in a later step, as follows
```
Task 55

Task 55 | 19:15:41 | Preparing deployment: Preparing deployment (00:00:17)
                   L Error: Job 'route_registrar' not found in Template table
Task 55 | 19:15:58 | Error: Job 'route_registrar' not found in Template tableUpdating deployment:
  Expected task '55' to succeed but state is 'error'
Exit code 1


Task 55 Started  Wed Aug  8 19:15:41 UTC 2018
Task 55 Finished Wed Aug  8 19:15:58 UTC 2018
Task 55 Duration 00:00:17
Task 55 error
```

As a workaround, the release can be uploaded manually with `bosh upload-release --fix` skip the check for already existing releases and versions.

**Comment by dpb587-pivotal** [comment]
Just to note here, we chatted a bit about this in one of our calls this week. One suggestion was to use a `dirty` flag to indicate a version may not have finished being uploaded. A couple caveats would be around this being a new field in the HTTP API and possible complications around how to handle the situation that source and/or compiled releases for multiple stemcells could be uploaded in parallel.

@voelzmo mentioned he'd start a story about this to discuss.

**Comment by utako** [comment]
This is introducing quite a bit of flakiness into our CI pipelines. Will this be prioritized at some point?

Thanks.

**Comment by BeckerMax** [comment]
Fixed with https://github.com/cloudfoundry/bosh/commit/eb59b8678f2cb98a87c494628acc0f9086ffafc5

**Comment by beyhan** [comment]
We noticed that we have this failure more often on GCP, because the root disk partition uses the ephemeral disk. When you upload a release to bosh the ephemeral disk is used to temporarily store the uploaded artifacts. Also with a local blobstore setup the ephemeral disk is used by the blobstore as temporary storage during the blob upload. If the ephemeral disk is not big enough you will end up with failures described in this issue.

**Comment by voelzmo** [comment]
related: I guess that might be why bosh-deployment specifies a 40GB root disk on GCP: https://github.com/cloudfoundry/bosh-deployment/blob/master/gcp/cpi.yml#L18
