### ISSUE TITLE
All jobs are forced to be reinstalled after upgrading bosh release

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#2027]
After we upgraded bosh release from `263.3` to `267.2`, there forced to update all jobs in all deployments, found a change `"logs"=>[]` in debug log, it's really painful to have to update all jobs since we have many deployments and thousands fo jobs managed by one director. Any workaround to bypassing it? Thanks.
```
changed FROM: 
{"name"=>"dummy_with_package", "templates"=>[{"name"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b"}], "template"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b"} TO: 
{"name"=>"dummy_with_package", "templates"=>[{"name"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b", "logs"=>[]}], "template"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b", "logs"=>[]} on instance dummy_with_package/40bc03b8-32bd-44ff-9a6e-4ea7e4e71c6d (0)
```

**Comment by mattcui** [comment]
It's due to the db migration change in https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/db/migrations/director/20171201153629_remove_unused_template_columns.rb

**Comment by jfmyers9** [comment]
Hey @mattcui,

Can you provide us with the output of `bosh task <task-number> --debug | grep "changes"`? This should give us a good idea of what is causing all of these VMs to update.

Best,

@jfmyers9 && @GarfieldIsAPhilosopher, CF BOSH

**Comment by mattcui** [comment]
@jfmyers9 I think it should grep `changed`, right? Below are msgs for `changed`:

D, [2018-08-13T03:41:42.348254 #18003] [] DEBUG -- DirectorJobRunner: job_changed? changed FROM: {"name"=>"dummy_with_properties", "templates"=>[{"name"=>"dummy_with_properties", "version"=>"4130de1cabfe9c169f0209c195ce7533fb5e5e7f", "sha1"=>"93a18da183df6aea459f7a648445d8f20152bfbc", "blobstore_id"=>"201f610b-6acc-4df8-917e-986cbdf42e01"}], "template"=>"dummy_with_properties", "version"=>"4130de1cabfe9c169f0209c195ce7533fb5e5e7f", "sha1"=>"93a18da183df6aea459f7a648445d8f20152bfbc", "blobstore_id"=>"201f610b-6acc-4df8-917e-986cbdf42e01"} TO: {"name"=>"dummy_with_properties", "templates"=>[{"name"=>"dummy_with_properties", "version"=>"4130de1cabfe9c169f0209c195ce7533fb5e5e7f", "sha1"=>"93a18da183df6aea459f7a648445d8f20152bfbc", "blobstore_id"=>"201f610b-6acc-4df8-917e-986cbdf42e01", "logs"=>[]}], "template"=>"dummy_with_properties", "version"=>"4130de1cabfe9c169f0209c195ce7533fb5e5e7f", "sha1"=>"93a18da183df6aea459f7a648445d8f20152bfbc", "blobstore_id"=>"201f610b-6acc-4df8-917e-986cbdf42e01", "logs"=>[]} on instance dummy_with_properties/993428d3-85ee-4170-bcb8-092aecf4bd46 (0)
D, [2018-08-13T03:41:42.352907 #18003] [] DEBUG -- DirectorJobRunner: job_changed? changed FROM: {"name"=>"dummy_with_package", "templates"=>[{"name"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b"}], "template"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b"} TO: {"name"=>"dummy_with_package", "templates"=>[{"name"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b", "logs"=>[]}], "template"=>"dummy_with_package", "version"=>"b819fee41c8e2c461e26f338bc0a510841d65c48", "sha1"=>"273f4a84da8ee73362d1c9cc2a25aec212eeae44", "blobstore_id"=>"edf86999-e32d-4d37-b547-3f7c350e741b", "logs"=>[]} on instance dummy_with_package/40bc03b8-32bd-44ff-9a6e-4ea7e4e71c6d (0)
D, [2018-08-13T03:41:42.356680 #18003] [] DEBUG -- DirectorJobRunner: job_changed? changed FROM: {"name"=>"dummy", "templates"=>[{"name"=>"dummy", "version"=>"289ecbf3fa7359e84d84e5d7c5edd22689ad81d4", "sha1"=>"4f8454e2984dd439c890d8d398facd48f0617141", "blobstore_id"=>"5423c0b6-3d50-4bfe-9880-2351c38d6ff1"}], "template"=>"dummy", "version"=>"289ecbf3fa7359e84d84e5d7c5edd22689ad81d4", "sha1"=>"4f8454e2984dd439c890d8d398facd48f0617141", "blobstore_id"=>"5423c0b6-3d50-4bfe-9880-2351c38d6ff1"} TO: {"name"=>"dummy", "templates"=>[{"name"=>"dummy", "version"=>"289ecbf3fa7359e84d84e5d7c5edd22689ad81d4", "sha1"=>"4f8454e2984dd439c890d8d398facd48f0617141", "blobstore_id"=>"5423c0b6-3d50-4bfe-9880-2351c38d6ff1", "logs"=>[]}], "template"=>"dummy", "version"=>"289ecbf3fa7359e84d84e5d7c5edd22689ad81d4", "sha1"=>"4f8454e2984dd439c890d8d398facd48f0617141", "blobstore_id"=>"5423c0b6-3d50-4bfe-9880-2351c38d6ff1", "logs"=>[]} on instance dummy/c7b8d0e6-bcef-4fd4-b607-9c0e634608ec (0)
D, [2018-08-13T03:41:42.415398 #18003] [] DEBUG -- DirectorJobRunner: packages_changed? changed FROM:  TO: {} on instance dummy/c8c28a8b-6f30-4ac1-9b5a-4986e0298e40 (1)
D, [2018-08-13T03:41:42.416390 #18003] [] DEBUG -- DirectorJobRunner: configuration_changed? changed FROM:  TO: b5bfc5773d6e563f242666a92ed638dcfe41f3dd on instance dummy/c8c28a8b-6f30-4ac1-9b5a-4986e0298e40 (1)
D, [2018-08-13T03:41:42.440139 #18003] [] DEBUG -- DirectorJobRunner: dns_changed? The requested dns record with name '1.dummy.default.gubin-slcpi-dummy.microbosh' and ip '10.112.116.16' was not found in the db.
D, [2018-08-13T03:42:32.190772 #18003] [instance_update(dummy/c8c28a8b-6f30-4ac1-9b5a-4986e0298e40 (1))] DEBUG -- DirectorJobRunner: dns_changed? The requested dns record with name '1.dummy.default.gubin-slcpi-dummy.microbosh' and ip '10.112.116.16' was not found in the db.

**Comment by luan** [comment]
Hi @mattcui,

While we haven't specifically seen this happen, it seems like that change would potentially cause what you're seeing. But even though that's true, we expect users of BOSH to be upgrading their stemcells more often than their directors. Moreover, going from 263 to 267 is a huge leap and it will often contain enough changes that making guarantees about not updating the jobs interface becomes really hard.

So, while we agree that this is something that caused all your jobs to be updated, we don't intend to focus efforts on guaranteeing that this isn't going to happen on this version or in the future. Thanks for reporting!

Best,

@luan && @jfmyers9, CF BOSH Team
