### ISSUE TITLE
can we deploy bosh-director with multiple interfaces in vpshere

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry/bosh#2029]
can we deploy bosh-director with multiple interfaces in vpshere ?

How to do that?

**Comment by jfmyers9** [comment]
Hi @techie20122018,

It looks like your (or a similar users) question was answered here: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1534305747000100. 

Feel free to reopen this issue and let us know if you have any other questions if it is still unclear.

Best,

@jfmyers9 && @mikexuu, CF BOSH
