### ISSUE TITLE
[Feature Request] Property to enable/disable blobstore backup/restore

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2032]
**Is your feature request related to a problem? Please describe.**
When using bbr for backup/restore there is no way to only backup the database, which makes backups very slow and the artifacts very big. We want to trade faster and smaller backups with having a different process to restore the blobstore (i.e. upload everything with `--fix`).

**Describe the solution you'd like**
I'd like a way to selectively only backup/restore the database. Currently, this decision is solely based on if a job provides a `backup` and `restore` script for bbr. If it does, it is executed. The low-cost solution for this is [a property that enables/disables the backup/restore for a job](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/develop/jobs/s3-versioned-blobstore-backup-restorer/spec#L30), resulting in the respective scripts to be [rendered with content/empty](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/blob/develop/jobs/s3-versioned-blobstore-backup-restorer/templates/backup.erb#L5).

This has several advantages: 
* It is easy to implement
* If we set the default to `true` nothing changes for users who don't care
* It can be chosen per-deployment, regardless of what the release choses to do in terms of backup/restore scripts
* It is a pattern that even the bbr-colleagues use – @glestaris referenced this in a slack conversation to me

**Describe alternatives you've considered**
* a switch in bbr to not backup blobstores
* a switch in bbr to selectively (not) backup indivdual jobs
Discussion happened with @glestaris in https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/18 and on slack. I've understood that they're investigating making blobstore backups less painful with https://www.pivotaltracker.com/epic/show/4027472 and are not in favor of providing a more generic selection mechanism for jobs.

**Comment by dpb587-pivotal** [comment]
I have mixed feelings about this. From one perspective, I see the desire/need for disabling BBR on specific job configurations. From another perspective, I think it's an easy trap for someone to disable the backups, forget about it, see it being listed in the `bbr` status output, and assume it's all working as they desire. I think, currently, the `bbr.enabled`-type approach quietly skips without any informational/warning messages to the user.

Adding flags to `bbr` during the backup/restore operation to explicitly limit behaviors leads to a very clear definition on what's happening. It does require the backup/restore operator to be a bit more familiar with the setup (to know which to enable/disable), and requires documenting/repeating those args during invocations though. More generally, it would also help the situation of someone trying to do a partial restore, or partial restores for different jobs from different backup times.

If flags aren't an option, I'd wish `bbr` had more official support for default flagging backup/restore of a job as disabled. If there was a file somewhere that it checks for enabled/disabled/other configs, it could handle some of this duplicate logic *and* be explicit in output when it's intentionally skipping a job.

**Comment by voelzmo** [comment]
Hey Danny, thanks for sharing your thoughts! I completely agree that having it explicitly in bbr is the desired way, that's why I ended up asking them first. From what I've heard in the conversations, they don't plan to add any work to provide a generic way to not run bbr for certain jobs, even though a script is present.

Given the current situation, what should we do here? Currently, this is blocking teams from adopting bbr and using hand-crafted backup/restore scripts, which is what we'd like to avoid.

How would you feel about a marker file in the artifact directory for the blobstore, indicating that the backup is disabled? We could empty the script, but have https://github.com/cloudfoundry/bosh/blob/master/jobs/blobstore/templates/bbr_backup#L16 write a file like `backup_disabled.marker`, if you want to have it more explicitly. Also potentially interesting: can bbr scripts stream some logs to the client? This would be a different option.

**Comment by jhvhs** [comment]
At Cloudops EU, we're also struggling with director backups including the blobstore. In our case this renders the backup useless. We are running continuous upgrades, and very quickly, a PCF foundation with CF/redis/mysql and a few other tiles produces a 130Gb encrypted tarball within about 10 hours. And it takes longer just to download, extract and decrypt the backup, let alone it, longer than it takes to re-create this whole foundation from scratch, given that we have separate backups for cf and opsman.

We were wondering about the reasoning behind including the blobstore. As we understand it, it's just an ephemeral cache that does not belong to the backup altogether. Is there any particular reason for including it?

**Comment by dpb587-pivotal** [comment]
Revisiting this, I'm still of the opinion that "what" gets backed up should be the responsibility of the backup agent/tool/operator. In environments where business continuity and standard provisioning may be separate teams, I think it's too risky to introduce job-level properties to disable backup support - that configuration is too far from where and how the backup is actually executed. Even if they're not separate teams, it seems to easy to disable job(s) in a development configuration without realizing the change gets promoted to production until it's too late.

But, let's see what thoughts the BBR team have on this scenario. This seems like it'd be a typical request, so I'd be interested to hear what discussions may already be out there. @glestaris, any thoughts or references for us to continue the discussion?

**Comment by dpb587-pivotal** [comment]
I guess I forgot that you already mentioned `s3-versioned-blobstore-backup-restorer.enabled` is a thing. Although I think it's unfortunate, it's a worthwhile precedent to mention.

I do agree that it's a bit weird that external use requires specifically including an extra backup-restorer job that you don't want to forget. Optimally that gets encoded in an ops file to avoid most people needing to worry about it.

I'll be a bit sad, but from a practicality perspective, I suppose we can easily-enough introduce a per-job `bbr.enabled` flag defaulting to `true` that we then remove if/when BBR supports better automation/selection options. I don't have a better idea right now.

@mfine30 I leave this to you for further discussion and prioritization with whomever is best.

**Comment by voelzmo** [comment]
In the meanwhile, cf-deployment released this: https://github.com/cloudfoundry/cf-deployment/blob/master/operations/backup-and-restore/skip-backup-restore-droplets-and-packages.yml

It even removes the respective directories from the backup for the internal blobstore: https://github.com/cloudfoundry/cf-deployment/blob/4eb08d924b77dd0ce492ece5fc18d3afd4dec827/operations/backup-and-restore/skip-backup-restore-droplets-and-packages.yml#L26-L28

Would this be an approach we'd be willing to take for BOSH? I feel we're now discussing this for quite a few months without a clear path forward. This is effectively stopping us from using bbr for regular backups, as the blobstore backups take too long and are too big on production directors.

**Comment by mrosecrance** [comment]
We've gone forward with introducing a job property on the blobstore job called `blobstore.bbr.enabled`. We've also taken your suggestion and put in a marker file in the backup artifact when it's disabled.

**Comment by mfine30** [comment]
@voelzmo I think we forgot to close the issue as part of the aforementioned tracker story: https://www.pivotaltracker.com/n/projects/956238/stories/159826426. I'm going to close the issue, since it seems like it should be resolved. If I skimmed too quickly and you think it should still be open, please do so!
