### ISSUE TITLE
Attempting to re-deploy with insufficient creds fails with an irrelevant error 

### ISSUE THREAD

**Issue by hdub2** [cloudfoundry/bosh#2036]
**Describe the bug**
We deployed to a BOSH director using a comprehensive admin user, then tried to deploy over that authenticated as a more fine-grained user (CI Bot). The resultant error message does not in any way indicate that the issue is permissions-based.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy (anything) using the root admin user.
2. Attempt to re-deploy while authenticated as a user with permissions to create deployments.
3. Observe the error:
```
Fetching diff result:
  Performing request POST 'https://director-host:25555/deployments/depl-name/diff?redact=true':
    Performing POST request:
      Retry: Post https://director-host:25555/deployments/depl-name/diff?redact=true: http: ContentLength=7485 with Body length 0
```

**Expected behavior**
Consistent with trying to `delete-deployment` with the same creds. Http response code 401 indicating insufficient authorization.

**Versions (please complete the following information):**
 - BOSH version 266.7
 - BOSH CLI version 5.1.1

**Comment by dpb587-pivotal** [comment]
Thanks - this should be fixed as of [v5.3.1](https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.3.1).
