### ISSUE TITLE
All Xenial VMs fail because BOSH can't 'ping' them

### ISSUE THREAD

**Issue by bloeys** [cloudfoundry/bosh#2044]
**Problem**:
When deploying anything that uses a Xenial stemcell the deployment fails because the director times out trying to ping (protocol 3) the VMs to confirm that they have been created. It fails on compilation if there is something to be compiled, otherwise it fails on the actual final VM.

The VMs are actually created successfully on OpenStack and can be accessed through SSH, but the Bosh director thinks they failed. All our other deployments (using Ubuntu Trusty) compile and work just fine, it only happens with the Xenial stemcells. We have tested with Xenial stemcells versions 97.15, 97.12, 97 and 87.3, and they all have the same problem.

**How to reproduce it**:
Deploy on OpenStack with BOSH V 266.4.0 using a Xenial stemcell.

**Versions:**
* Infrastructure: OpenStack
* BOSH version: 266.4.0
* BOSH CLI: 5.2.2
* BOSH dns: 1.8.0
* Stemcell: Any Xenial stemcell (V 87.3+ tested)

**Notes**:
* The problem we described is from us looking at the task debug logs, but the actual returned error from the deployment is misleading: 
`Error: Attempt to delete object did not result in a single row modification (Rows Deleted: 0, SQL: DELETE FROM "vms" WHERE ("id" = xxx))`
* We have BOSH dns enabled using runtime config
* BOSH was deployed using BOSH-bootloader V 6.9.0

**Comment by voelzmo** [comment]
Cross-posted from https://github.com/cloudfoundry-incubator/kubo-deployment/issues/339

**Comment by voelzmo** [comment]
The contents of the agent log would be helpful, as described in https://bosh.io/docs/tips/#unreachable-agent

Also: could you ssh into one of the VMs and see which ntp servers are configured? The configuration lives in `/var/vcap/bosh/etc/ntpserver`. Others have reported issues on Xenial where the ntp servers couldn't be reached – I think this should have been fixed, but just to double-check.

**Comment by bloeys** [comment]
Thank you @voelzmo for your reply. I am sadly away for this week and won't be able to update until next week.

However, I wanted to clarify how to gain sudo access on these machines. As far as I have tried, I'm unable to view the logs of a compilation machine or if the machine didn't start correctly (as in this case)

**Comment by voelzmo** [comment]
> However, I wanted to clarify how to gain sudo access on these machines. As far as I have tried, I'm unable to view the logs of a compilation machine or if the machine didn't start correctly (as in this case)

Given that your VMs error out with `timout pinging`, I guess you have two choices
* [setting a password for the `vcap` user in the `compilation` block of your cloud config via `env.bosh.password`](https://bosh.io/docs/cloud-config/#compilation) and try to access the VM with normal `ssh` using the configured default ssh key. Depending on where the agent fails, the password for obtaining superuser rights is either `c1oudc0w` or your configured password
* accessing the VM via the OpenStack VPN console in Horizon. The vcap password should be `c1oudc0w` or your configured password

Hope that helps.

**Comment by bloeys** [comment]
Okay so setting the password, SSH into a compilation Xenial VM, I found the following set on the `ntpserver` file: `time1.google.com time2.google.com time3.google.com time4.google.com`

This is the same as is set on working Trusty stemcells, and can be reached as I tested using curl, where a 302 "The document has moved" response is returned.

I got the logs which you can find (removed repetitive parts) [here](https://gist.github.com/bloeys/267b4b769dd3d5e46a181e4702a82eb3). The main error seems to be here:
```
[PartedPartitioner] 2018/09/17 11:19:30 ERROR - Failed with an error: Running command: 'parted -s /dev/vdb unit B mkpart bosh-partition-0 1048576 3872391167', stdout: '', stderr: 'parted: invalid token: bosh-partition-0
2018-09-17_11:19:30.15345 Error: Expecting a file system type.
```
It fails when trying to create a partition. Any ideas on this one?

**Comment by voelzmo** [comment]
@bloeys Thanks, that helped! I was able to reproduce this on our OpenStack.

For now, this seems to happen reliably, if you are using a flavor which has an ephemeral device configured. If it is possible, I recommend for now the workaround to not configure an ephemeral device and increase the size of your root device accordingly. The agent will partition the root device into root and ephemeral – this should be transparent for your installed releases.

We will follow-up next week with https://www.pivotaltracker.com/story/show/160688556

**Comment by bloeys** [comment]
Sounds good then!
Thank you for the help. I'll keep the issue open for any updates and can close once its resolved.

**Comment by voelzmo** [comment]
Seems like this is related to the way how OpenStack recycles ephemeral devices. Apparently, those are not completely nulled-out by default, therefore parted thinks there is still data on it and reports a partition table of type `loop`: https://www.pivotaltracker.com/story/show/160688556/comments/195477876

The linked commit in the agent makes it treat `loop` partition tables as if there was no partition table and fixes your issue. Now waiting for a stemcell to be released which contains the fix in the agent.

**Comment by bloeys** [comment]
This makes sense, thanks for the work. I will really be looking forward to the coming release as it has been keeping us from updating some things.

**Comment by voelzmo** [comment]
This is fixed with the most recent Xenial stemcells >= 170.3
Thanks again for raising this!
