### ISSUE TITLE
Add support for deleting credhub namespaced entries when deleting a bosh deployment

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh#2045]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I delete a bosh deployment becuase associated credhub entries in the [bosh director namespacing prefix](https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/bosh-config-server.md#namespacing) don't get deleted. 

This results into:
* leaks in credhub as more and more bosh deployments gets created and deleted 
* potentially unexpected reuse of old credentials in new deployment with same name. This may be bad if the credentials from the old deleted deployment were disclosed

**Describe the solution you'd like**

Bosh director support for deleting the credhub entries that director created for a bosh deployment (see related #2047), likely along with the request to delete the associated bosh deployment.

The bosh cli could surface with an opt-in option such as ``bosh delete-deployment --delete-credentials`` 

**Describe alternatives you've considered**

Invoke the credhub cli following the ``bosh delete-deployment`` to delete the associated leaking credhub entries, however lack of #2047 makes this tedious

**Comment by mfine30** [comment]
Hey @gberche-orange thanks for bringing this up. Definitely agree on the pain point here. There are a few potential ways we're considering addressing this and making it easier to clean up credentials after deleting a deployment. 

However, it's in reality more of a mid to long term roadmap item, since as you mentioned there is an alternative, albeit a bit of a tedious one.

**Comment by gberche-orange** [comment]
thanks @mfine30 

> There are a few potential ways we're considering addressing this

Out of curiosity (as this isn't for short term), can you share some of your thoughts, or pointers to related story/bosh-note if they exist already ?

**Comment by RMeharg** [comment]
I have a few customers who are also interested in this, to make audit, cleanup and repaving easier

**Comment by gberche-orange** [comment]
@bosh-admin-bot please reopen this issue open as I believe it is still relevant

**Comment by JanKraut** [comment]
We have now run into this issue, because of this related issue in credhub https://github.com/cloudfoundry/credhub/issues/340. 

Is there an update here? We cannot query or rotate expiring certificates anymore.
