### ISSUE TITLE
Blobstore fails to start with `Address already in use`

### ISSUE THREAD

**Issue by s4heid** [cloudfoundry/bosh#2052]
**Describe the bug**
Monit constantly tries to start the Blobstore, but it fails with unix socket `unix:/var/vcap/data/blobstore/backend.sock` is already in use. The socket file of the Blobstore process did not get deleted correctly. This caused the failing binding during the Blobstore process startup. 

**To Reproduce**
The above error is not reproducible. It is unclear why the `backend.sock` file did not get deleted correctly during shutdown of the Blobstore process.

**Expected behavior**
The unix socket file `/var/vcap/data/blobstore/backend.sock` is getting cleaned up.

**Logs**
In `/var/vcap/sys/log/blobstore/blobstore.stderr.log` we see the following errors:
```
nginx: [alert] could not open error log file: open() "/var/vcap/packages/nginx/logs/error.log" failed (30: Read-only file system)
nginx: [emerg] bind() to unix:/var/vcap/data/blobstore/backend.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/var/vcap/data/blobstore/backend.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/var/vcap/data/blobstore/backend.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/var/vcap/data/blobstore/backend.sock failed (98: Address already in use)
nginx: [emerg] bind() to unix:/var/vcap/data/blobstore/backend.sock failed (98: Address already in use)
nginx: [emerg] still could not bind()
```

**Versions**
 - Infrastructure: OpenStack
 - BOSH version: 267.3.0
 - BOSH CLI version: 4.0.1
 - Stemcell version: ubuntu-trusty/3586.36
 - BPM version: 0.8.0

**Additional context/Workaround**
After deleting the file `/var/vcap/data/blobstore/backend.sock`, the Blobstore started again successfully.

**Comment by pivotal-jamil-shamy** [comment]
@s4heid thanks for reporting the issue. This [recent commit](https://github.com/cloudfoundry/bosh/commit/075222d25c028e7e828394a45633e30bbbc7c127) should potentially fix this bug

**Comment by mfine30** [comment]
This should be fixed in [v267.7.0](https://github.com/cloudfoundry/bosh/releases/tag/v267.7.0) of the Director.

**Comment by voelzmo** [comment]
@mfine30 Are you also releasing a new 268 version with that fix?

**Comment by mfine30** [comment]
@voelzmo Yes, it should be fixed in: https://github.com/cloudfoundry/bosh/commit/075222d25. I was planning to cut a new minor next week, but if you think this is more urgent we can release a patch more quickly

**Comment by voelzmo** [comment]
That's all good, thanks! I guess I got confused as I expected a commit to happen on some 268.x branch. I'm currently not clear what the policy for bringing fixes into the latest version is: master vs. release branch.

**Comment by dpb587-pivotal** [comment]
Tentatively, the policy is that we continually release new major or minor versions of bosh from master, per semantic versioning rules. This differs from our previous approach of creating majors occasionally, and then patching those long-running releases with minor versions. For some of the PCF/LTS-type releases, they would end up as patch releases on whatever major/minor version ended up in those distributions.
