### ISSUE TITLE
Delete deployment doesn't validate the available deployments before deletion

### ISSUE THREAD

**Issue by shausy** [cloudfoundry/bosh#2053]
Delete deployment doesn't validate the available deployments before deletion

Trying to delete the deployment which is not exist in the bosh env

Actual behaviour:
Report succeeded irrespective of no deployment exists

Expected behaviour:
Should validate the deployment availability and go for deletion

`root@New-PksCli:~# bosh delete-deployment -d sservice-insta
Using environment '172.28.248.101' as client 'ops_manager'
Using deployment 'sservice-insta'
Continue? [yN]: y
Succeeded
root@New-PksCli:~#`

BOSH - vSphere - 2.1 Build 326 from PKS

**Comment by h4xnoodle** [comment]
Hi @shausy thanks for filing this issue. At this time, there are people who depend on deleting the deployment to succeed regardless of the deployment existing. There are other pieces of software like the ODB https://github.com/pivotal-cf/on-demand-service-broker that may break if we were to fail. I will look at the effort to at least show a message that the deployment didn't exist.  Another line of thinking is: a deletion should be idempotent and never fail.
