### ISSUE TITLE
Stop instances fails with "no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by shausy** [cloudfoundry/bosh#2054]
Stop instances fails with "no implicit conversion of nil into String"

BOSH - vSphere - 2.2 Build 319 from PKS

Trying to stop the instances in  the deployment but the stop operation failed with below error 

Actual behaviour:
Stop operation failed with unknown error

Expected behaviour:
Stop should work successfully.

```
root@New-PksCli:~/wavefront# bosh -d service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1 stop worker/d2c38f67-756b-4b07-b41f-069028f030b1
Using environment '172.28.248.101' as client 'ops_manager'

Using deployment 'service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1'

Continue? [yN]: y

Task 23191

Task 23191 | 12:34:10 | Error: no implicit conversion of nil into String

Task 23191 Started  Fri Sep 21 12:34:10 UTC 2018
Task 23191 Finished Fri Sep 21 12:34:10 UTC 2018
Task 23191 Duration 00:00:00
Task 23191 error

Changing state:
  Expected task '23191' to succeed but state is 'error'

Exit code 1
root@New-PksCli:~/wavefront#
```

**Comment by pivotal-mp** [comment]
Hi @shausy,

Have you ever successfully deployed this deployment? There's a known behavior where an instance operation (e.g. stop, start, recreate) will fail for deployments that have never succeeded. See also: https://github.com/cloudfoundry/bosh/issues/1854.

Let us know if that helps,

@pivotal-mp && @jfmyers9, CF BOSH

**Comment by shausy** [comment]
Yes the deployment is successful. Im trying to created failure scenarios for kubernetes cluster during that operation this issue been observed.

**Comment by shausy** [comment]
@luan Deployment is taken care internally using the PKS as part of cluster creation.

Post cluster creation, I have tried to do this operation and it fails

`Cli:/home/pksadmin# bosh task 23191 --debug
Using environment '172.28.248.101' as client 'ops_manager'

Task 23191

I, [2018-09-21T12:34:10.278142 #28] [0x2b10e6dc568c]  INFO -- TaskHelper: Director Version: 266.11.0
I, [2018-09-21T12:34:10.278191 #28] [0x2b10e6dc568c]  INFO -- TaskHelper: Enqueuing task: 23191
I, [2018-09-21T12:34:10.608792 #23837] []  INFO -- DirectorJobRunner: Looking for task with task id 23191
D, [2018-09-21T12:34:10.609743 #23837] [] DEBUG -- DirectorJobRunner: (0.000264s) (conn: 47042397571780) SELECT * FROM "tasks" WHERE "id" = 23191
I, [2018-09-21T12:34:10.610735 #23837] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>23191, :state=>"processing", :timestamp=>2018-09-21 12:34:10 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/23191", :checkpoint_time=>2018-09-21 12:34:10 UTC, :type=>"update_deployment", :username=>"ops_manager", :deployment_name=>"service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2018-09-21T12:34:10.610808 #23837] []  INFO -- DirectorJobRunner: Running from worker 'worker_4' on director/39cc9961-2a18-47ab-7748-d8a26e5832e8 (127.0.0.1)
I, [2018-09-21T12:34:10.610865 #23837] []  INFO -- DirectorJobRunner: Starting task: 23191
I, [2018-09-21T12:34:10.610931 #23837] [task:23191]  INFO -- DirectorJobRunner: Creating job
D, [2018-09-21T12:34:10.611404 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000168s) (conn: 47042397571780) SELECT * FROM "tasks" WHERE "id" = 23191
D, [2018-09-21T12:34:10.612298 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000177s) (conn: 47042397571780) SELECT * FROM "tasks" WHERE "id" = 23191
I, [2018-09-21T12:34:10.615072 #23837] [task:23191]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>23191, :state=>"processing", :timestamp=>2018-09-21 12:34:10 UTC, :description=>"create deployment", :result=>nil, :output=>"/var/vcap/store/director/tasks/23191", :checkpoint_time=>2018-09-21 12:34:10 UTC, :type=>"update_deployment", :username=>"ops_manager", :deployment_name=>"service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1", :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2018-09-21T12:34:10.615982 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000083s) (conn: 47042397571780) BEGIN
D, [2018-09-21T12:34:10.617491 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000322s) (conn: 47042397571780) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2018-09-21 12:34:10.615163+0000', "description" = 'create deployment', "result" = NULL, "output" = '/var/vcap/store/director/tasks/23191', "checkpoint_time" = '2018-09-21 12:34:10.615396+0000', "type" = 'update_deployment', "username" = 'ops_manager', "deployment_name" = 'service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1', "started_at" = '2018-09-21 12:34:10.615293+0000', "event_output" = '', "result_output" = '', "context_id" = '' WHERE ("id" = 23191)
D, [2018-09-21T12:34:10.618292 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000659s) (conn: 47042397571780) COMMIT
I, [2018-09-21T12:34:10.618411 #23837] [task:23191]  INFO -- DirectorJobRunner: Reading deployment manifest
D, [2018-09-21T12:34:10.618989 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000167s) (conn: 47042397571780) SELECT * FROM "tasks" WHERE "id" = 23191
D, [2018-09-21T12:34:10.620258 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000074s) (conn: 47042397571780) BEGIN
D, [2018-09-21T12:34:10.621227 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000492s) (conn: 47042397571780) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-09-21 12:34:10.619593+0000', 'ops_manager', 'update', 'deployment', NULL, 'no implicit conversion of nil into String', '23191', NULL, NULL, '{}') RETURNING *
D, [2018-09-21T12:34:10.625738 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.004195s) (conn: 47042397571780) COMMIT
D, [2018-09-21T12:34:10.626630 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000064s) (conn: 47042397571780) BEGIN
D, [2018-09-21T12:34:10.627311 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000285s) (conn: 47042397571780) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1537533250,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
') WHERE ("id" = 23191)
D, [2018-09-21T12:34:10.628045 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000615s) (conn: 47042397571780) COMMIT
E, [2018-09-21T12:34:10.628206 #23837] [task:23191] ERROR -- DirectorJobRunner: no implicit conversion of nil into String
/var/vcap/data/packages/ruby-2.4-r4/5fa1496fb6d4278aa2e385cf20602f54872fc6a4/lib/ruby/2.4.0/psych.rb:377:in `parse'
/var/vcap/data/packages/ruby-2.4-r4/5fa1496fb6d4278aa2e385cf20602f54872fc6a4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
/var/vcap/data/packages/ruby-2.4-r4/5fa1496fb6d4278aa2e385cf20602f54872fc6a4/lib/ruby/2.4.0/psych.rb:325:in `parse'
/var/vcap/data/packages/ruby-2.4-r4/5fa1496fb6d4278aa2e385cf20602f54872fc6a4/lib/ruby/2.4.0/psych.rb:252:in `load'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:28:in `perform'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:52:in `with_thread_name'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/data/packages/director/3a8a83074d698ec5bd1b812bb5bee53ebcfe87ae/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-09-21T12:34:10.628769 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000191s) (conn: 47042397571780) SELECT * FROM "tasks" WHERE "id" = 23191
D, [2018-09-21T12:34:10.629798 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000064s) (conn: 47042397571780) BEGIN
D, [2018-09-21T12:34:10.630590 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000260s) (conn: 47042397571780) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-09-21 12:34:10.629423+0000', "description" = 'create deployment', "result" = 'no implicit conversion of nil into String', "output" = '/var/vcap/store/director/tasks/23191', "checkpoint_time" = '2018-09-21 12:34:10.615396+0000', "type" = 'update_deployment', "username" = 'ops_manager', "deployment_name" = 'service-instance_f0ef4e53-2a6f-4b6f-a854-b67c4d1894f1', "started_at" = '2018-09-21 12:34:10.615293+0000', "event_output" = '{"time":1537533250,"error":{"code":100,"message":"no implicit conversion of nil into String"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 23191)
D, [2018-09-21T12:34:10.631264 #23837] [task:23191] DEBUG -- DirectorJobRunner: (0.000554s) (conn: 47042397571780) COMMIT
I, [2018-09-21T12:34:10.631420 #23837] []  INFO -- DirectorJobRunner: Task took 0.020464458 seconds to process.

Task 23191 error

Capturing task '23191' output:
  Expected task '23191' to succeed but state is 'error'

Exit code 1
root@New-PksCli:/home/pksadmin# bosh task 23191 --debug`

**Comment by belinda-liu** [comment]
Hi @shausy,

Is this still an issue? If not, we are going to close this due to inactivity.

Thanks,
@belinda-liu && @langered, CF BOSH

**Comment by belinda-liu** [comment]
Hi @shausy,

We are closing this issue for now. Feel free to reopen if necessary.

Thanks,

@belinda-liu && @s4heid, CF BOSH
