### ISSUE TITLE
[UX issue] Uploading a release with version containing `v` prefix causes unexpected sorting

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh#2056]
**Describe the bug**

Normally when you create a BOSH release, you give it a semver version like `1.0.2`. However, it seems like BOSH will also accept things that are not quite semver, like the Minio release uses `2018-07-31T02-11-47Z` as its version. Is this case BOSH will sort lexicographically rather than a semver sort. Let's say we accidentally cut one BOSH release with version `v1.0.2` (note the leading `v`) and the next version we realize our mistake and go with `1.0.3`. BOSH will always sort `v1.0.2` as higher than `1.0.3` as the `v` kicks Ruby into lexicographical sorting mode rather than numerical.

**To Reproduce**

Steps to reproduce the behavior (example):
1. `bosh create-release --version 1.0.0 --tarball /tmp/release-1.0.0.tgz` && `bosh upload-release /tmp/release-1.0.0.tgz`
1. `bosh create-release --version v2.0.0 --tarball /tmp/release-v2.0.0.tgz` && `bosh upload-release /tmp/release-v2.0.0.tgz`
1. `bosh create-release --version 3.0.0 --tarball /tmp/release-3.0.0.tgz` && `bosh upload-release /tmp/release-3.0.0.tgz`
1. `bosh releases`

```
Name           Version       Commit Hash
my-release  v2.0.0       b2c97303
~           3.0.0        b2c97303
~ .         1.0.0        b2c97303
```

**Expected behavior**

While it makes sense to support lexicographical sorting for non-semver version numbers, the leading `v` is probably always a mistake and should be ignored in favor of a semver sort. A warning at the CLI on `create-release` that you probably didn't mean to specify the leading `v` would also help.

**Versions (please complete the following information):**
- CLI version 5.2.2

Slack convo [here](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1537832458000100)

**Comment by dpb587-pivotal** [comment]
I'm not sure a warning would do much at the CLI level. It's easy to misconfigure in automation, and that is likely to be ignored. In theory, if people really want a v*, might as well allow them, albeit I think it's an odd decision, too.

I do think director's ordering is bad. I think semver versions should have precedence, sorted correctly, and then any remaining ones sorted lexicographically. This makes it clear that semver is the recommendation, but continues to support releases needing other lex-based strategies, and happens to fix this sort of accidental, always-latest. Semver should definitely be the preferred way to version releases.
