### ISSUE TITLE
Release version commit mismatch shows newer commit hash

### ISSUE THREAD

**Issue by acrmp** [cloudfoundry/bosh#2057]
**Describe the bug**
Uploading a release with the same version but a different commit hash raises an error:

```
Error: release 'example/1.0.0' has already been uploaded with commit_hash as 'abc12345' and uncommitted_changes as 'false'
```

Based on the wording I'd expect the commit hash shown to be the hash of the earlier uploaded release. However it seems to be the commit hash of the new duplicate release you are attempting to upload.

https://github.com/cloudfoundry/bosh/blob/2443735de6df5d03343430f58879c1d17a5f3cf0/src/bosh-director/lib/bosh/director/jobs/update_release.rb#L147-L149

**To Reproduce**
Steps to reproduce the behavior (example):
1. Create a BOSH release with a given version and upload it `bosh create-release --version 1.0.0 && bosh upload-release`
2. Create a new commit `git commit --allow-empty`
3. Re-create and upload the release with the same version: `bosh create-release --version 1.0.0 && bosh upload-release`

**Expected behavior**
I expected the hash of the earlier uploaded release to be shown (rather than the hash of the new release).

**Comment by mikexuu** [comment]
Hi @acrmp ,

Thanks for the issue. We've addressed the hash mismatch in [this commit](https://github.com/cloudfoundry/bosh/commit/f3c8ac9c34ad624c3379f6a68597f2bf041705b9). Closing the issue for now, feel free to reopen if there are any other concerns.

Best,
@jaresty && @mikexuu , CF BOSH Team
