### ISSUE TITLE
line 1: cannot unmarshal !!str `<%!`(MISSING) into director.Manifest

### ISSUE THREAD

**Issue by srikanth19** [cloudfoundry/bosh#2060]
Hi,
I am try to deploy sas on cloudfoundry and I am facing the below error.

ERROR:

#bosh -e bosh-2 -d sas-viya deploy SAS-Viya-manifest.yml

Using environment '10.0.0.6' as client 'admin'

Using deployment 'sas-viya'

Parsing manifest:

Unmarshalling manifest:

yaml: unmarshal errors:

line 1: cannot unmarshal !!str `<%!`(MISSING) into director.Manifest

Exit code 1

Can anyone help with this. Your help will be much appreciated.

Below are the details of bosh CLI and director.

Bosh CLI Details :

#bosh --version

version 5.1.2-14b04789-2018-08-17T15:15:17Z

Bosh Director details :

#bosh -e bosh-2 environment

Using environment '10.0.0.6' as client 'admin'

Name bosh-bbl-env-winnipeg-2018-09-27t21-06z

UUID 7404a17f-d938-432c-ae33-00575bcffcb2

Version 267.5.0 (00000000)

CPI aws_cpi

Features compiled_package_cache: disabled

config_server: enabled

dns: disabled

snapshots: disabled

User admin

Succeeded

Regards,
Srikanth

**Comment by dpb587-pivotal** [comment]
It looks like you're trying to use a very old manifest which is using ERB-style interpolation. ERB interpolation is no longer supported with recent versions of the CLI. I'd recommend you take a look at this [interpolation](https://bosh.io/docs/cli-int/) doc to learn more and, as a reminder, you no longer need to specify `director_uuid` in your manifest.

**Comment by srikanth19** [comment]
Thanks for the information.

I have deployed the bosh director using the bosh bootloader and I am able to connect using bosh CLIV2 and deployed CF, but now I cannot change the SAS Manifest file so I have to go with it.   
I have now installed the bosh CLIV1
[root@bosh bbl]# boshv1 --version
BOSH 1.3262.26.0

but when I try to connect to bosh director using CLIV1 commands, I am facing below error.

[root@bosh bbl]# boshv1 target https://34.203.223.237:25555
Target set to 'bosh-bbl-env-winnipeg-2018-09-27t21-06z'
/usr/local/share/gems/gems/cf-uaa-lib-3.2.5/lib/uaa/http.rb:173:in `rescue in net_http_request': error: Connection timed out - connect(2) (CF::UAA::BadTarget)
        from /usr/local/share/gems/gems/cf-uaa-lib-3.2.5/lib/uaa/http.rb:159:in `net_http_request'
        from /usr/local/share/gems/gems/cf-uaa-lib-3.2.5/lib/uaa/http.rb:147:in `request'
        from /usr/local/share/gems/gems/cf-uaa-lib-3.2.5/lib/uaa/token_issuer.rb:77:in `request_token'
        from /usr/local/share/gems/gems/cf-uaa-lib-3.2.5/lib/uaa/token_issuer.rb:264:in `client_credentials_grant'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/client_token_issuer.rb:18:in `access_info'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/client.rb:34:in `block in access_info'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/client.rb:50:in `with_save'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/client.rb:34:in `access_info'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/token_provider.rb:47:in `client_access_info'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/token_provider.rb:33:in `get_access_info'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/uaa/token_provider.rb:16:in `token'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/client/credentials.rb:14:in `authorization_header'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/base_command.rb:72:in `logged_in?'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/commands/misc.rb:119:in `set_target'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/command_handler.rb:57:in `run'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/lib/cli/runner.rb:59:in `run'
        from /usr/local/share/gems/gems/bosh_cli-1.3262.26.0/bin/bosh:19:in `<top (required)>'
        from /usr/local/bin/boshv1:23:in `load'
        from /usr/local/bin/boshv1:23:in `<main>'
 
Can you help me to connect to bosh director using the CLI1 commands.

**Comment by dpb587-pivotal** [comment]
Unfortunately, CLIv1 is no longer supported (CLIv2+ has been available and stable for about a year and a half). I'd recommend investing some time to migrate. There should be minimal changes needed, and some command-specific migration notes can be found [here](https://bosh.io/docs/cli-v2-diff/).

In your specific case, the environment `bbl` creates causes you to rely on `bosh`'s v2 capabilities for tunneling traffic to your VMs. This is not something that the v1 CLI supports. Once you have upgraded your tools and manifests, you should be able to get further. If, after upgrading, you experience new errors, please feel free to open a new issue.

**Comment by srikanth19** [comment]
Hi,
Now I am using cliv2 supported Manifest file but I am facing the below error. I have attached manifest and bosh release output command file.

Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'cas_controller'. Errors are:
    - Unable to render templates for job 'cas_controller'. Errors are:
      - Error filling in template 'cas_grid_vars' (line 14: undefined method `ip' for nil:NilClass)
      - Error filling in template 'properties.sh.erb' (line 29: undefined method `ip' for nil:NilClass)
  - Unable to render jobs for instance group 'microservices'. Errors are:
    - Unable to render templates for job 'sas-microservices-deploy'. Errors are:
      - Failed to find variable '/bosh-bbl-env-winnipeg-2018-09-27t21-06z/sas-vdmml-ubuntu/sas' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'

Thanks in advance.

[manifest.txt](https://github.com/cloudfoundry/bosh/files/2453044/manifest.txt)
[releases.txt](https://github.com/cloudfoundry/bosh/files/2453046/releases.txt)
