### ISSUE TITLE
BOSH fails to create a vm with default CPI when cpi-config is in use

### ISSUE THREAD

**Issue by sunshineperi** [cloudfoundry/bosh#2066]
**Describe the bug**
bosh recreate failed with error:  if the target az is not specified with cpi
`Error 100: CPI '' not found in cpi-config`

**To Reproduce**
1. You already have bosh director and deployment running.
2. You use external cpi-config,  for multiple cpis.
3. Bosh recreate a vm,  target az of which is to use default cpi,  the cpi is not explicitly defined in cloud_properties of the az.

**Expected behavior**
vm can be successfully recreated.

**Logs**
`Started updating instance networking_db > networking_db/ebd43510-37e1-4ac0-86d4-79266a1dddc0 (0) (canary). Failed: CPI '' not found in cpi-config (00:00:40)`

**Versions (please complete the following information):**
 - Infrastructure: [vsphere]
 - BOSH version [268.1.0]
 - BOSH CLI version [4.0.1]
 - Stemcell version [bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.47]

**Additional context**
This can be fixed by modifying here:
https://github.com/cloudfoundry/bosh/blob/v268.1.0/src/bosh-director/lib/bosh/director/deployment_plan/stemcell.rb#L100
with the following:
`return model_for_default_cpi if cpi_name.nil? || cpi_name.empty?`

**Comment by sunshineperi** [comment]
This is the thread on slack:
https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1540190522000100
https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1539845673000100

peri [1 day ago]
@h4xnoodle, from the code, it seems that default cpi should be used, cpi_name is nil or empty is checked almost everywhere, except the stemcell.rb,  after adding the check,  it worked! So I assume this is something that is missing?  You can find the code fix at the bottom of the issue.

h4xnoodle [14 hours ago]
if we do end up checking elsewhere, we'll make sure this still makes sense. Do you have insight on how your CPI config had an empty CPI defined? How come the CPI was not defined in cloud_properties of the az?

emm,   `do you have insight?  how come? `

**Comment by freddesbiens** [comment]
Thank you for your patience. After careful consideration, we decided not to implement a fix for this. However, we will update our documentation to mention that operators using `cpi-config` must explicitly define a default CPI for each of their availability zones.
