### ISSUE TITLE
ls: cannot access /var/vcap/packages/*/lib: No such file or directory ls: cannot access /var/vcap/packages/*/*/*.jar: No such file or directory /var/vcap/jobs/cas_controller/bin/cas_controller_ctl: line 34: hash: numactl: not found  

### ISSUE THREAD

**Issue by srikanth19** [cloudfoundry/bosh#2067]
Hi, 

I am facing this issue. Can you please help me out.

**Comment by s4heid** [comment]
@srikanth19 thanks for submitting this issue. Unfortunately we need more details in order to help you. If this is a bug, please close and reopen this as a bug report, and follow the template.

**Comment by srikanth19** [comment]
Hi,
Thanks for responding.

I am trying to deploy SAS Viya on cloud foundry. The deployment has started and has thrown the below error:

_Error: 'cas_controller/6f220e5f-f2ac-4fbf-8c78-d41538c6dc02 (0)' is not running after update. Review logs for failed jobs: java, numa, dpkg-installer, cas_controller, tmp_chmod, bosh-dns, bosh-dns-resolvconf, bosh-dns-healthcheck
Task 137 | 12:24:47 | Error: 'cas_controller/6f220e5f-f2ac-4fbf-8c78-d41538c6dc02 (0)' is not running after update. Review logs for failed jobs: java, numa, dpkg-installer, cas_controller, tmp_chmod, bosh-dns, bosh-dns-resolvconf, bosh-dns-healthcheck_

I logged in the cas_controller and checked the /var/vcap logs and found below error(not sure if this is the real culprit) in the logs monit/cas-controller.err.log 

_**ls: cannot access /var/vcap/packages/*/lib: No such file or directory
ls: cannot access /var/vcap/packages/*/*/*.jar: No such file or directory
/var/vcap/jobs/cas_controller/bin/cas_controller_ctl: line 34: hash: numactl: not found**_
But I was able to locate numactl in /var/vcap/packages folder.

I am not sure if this could help or not, I have also observed diego cell was in failing state after the above error was encountered.

Thanks in advance.

**Comment by dpb587-pivotal** [comment]
This error typically suggests a misconfiguration in the release job - either by referring to incorrect paths to the `/var/vcap/packages/{name}/{file}` it needs, or by forgetting to have the job depend on that package to make sure it gets installed.

I'd recommend you look into the `cas_controller` job and verify it's `spec` file and `cas_controller_ctl` template.

**Comment by h4xnoodle** [comment]
@srikanth19 has your issue been resolved? If not, please reopen and we can look into it further. Closing for now.
