### ISSUE TITLE
Adding another diego cell to existing cf deployment

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/bosh#2074]
I have an existing cf deployment, and it only has one diego-cell. How do I add an additional diego-cell to the deployment? Thanks

**Comment by mfine30** [comment]
You should be able to change the number of instances via the `instances` key for the appropriate instance group. You can see an example manifest here: https://bosh.io/docs/deployment-basics/

**Comment by betht1220** [comment]
Please let me know if follows are correct if I want to add an additional instance for a group. Thanks
1. delete the existing deployment, change the instance key for the group, set the deployment, and bosh deploy?
2. This means all data for this deployment will be lost?

**Comment by aemengo** [comment]
Hi again^^ @betht1220. You're correct, deleting the existing deployment will mean that all the data will get lost. But you **don't** need to delete it. BOSH allows you to make these kinds of changes without losing your data.

Simply download the manifest, edit the appropriate key and then redeploy and BOSH should be able to identity that you only want the number of instances changed.

**Comment by betht1220** [comment]
Is this how to download the manifest "bosh manifest -d cf"? 
I've used that and modify the instances and do "bosh deploy", I got error with "file not found".
I've deleted all url in releases, and "bosh deploy", I run in the same error.
Looks like my way of getting manifest is not correct. Thanks for the comments aemengo.

**Comment by aemengo** [comment]
@betht1220 I suspect that there might be a syntax issue. Try the following:

```
$ bosh -d cf manifest > ./cf.yml
# Edit the ./cf.yml in place, remove all the urls
$ bosh -d cf deploy ./cf.yml
```
