### ISSUE TITLE
NATS password and user should be optional

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2075]
**Describe the bug**
When `allow legacy clients` is set to `false`, NATS doesn't use username and password anymore: https://github.com/cloudfoundry/bosh/blob/master/jobs/nats/templates/nats.cfg.erb#L9-L10

We should make this optional in the spec file, such that I don't need to care about credentials which aren't needed. It leads to confusion around operators in terms of rotation and maintenance of those credentials.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director with [`allow_legacy_clients: false`](https://github.com/cloudfoundry/bosh/blob/master/jobs/nats/spec#L46)
2. Don't specify `nats.username` and `nats.password`. More specifically, I can apply the following ops-file to bosh-deployment.
```
---
- type: remove
  path: /variables/name=nats_password

- type: remove
  path: /instance_groups/name=bosh/properties/agent/mbus

- type: remove
  path: /instance_groups/name=bosh/properties/nats/user

- type: remove
  path: /instance_groups/name=bosh/properties/nats/password
```
3. Deployment fails because you didn't specify necessary properties – they don't have a default value

**Expected behavior**
It works. All clients connect to NATS via certificates and don't need username or password. Ideally, the ops-file pasted above should be part of https://github.com/cloudfoundry/bosh-deployment/blob/04c85a5c79a9fa6b92775386a334104b9a165013/misc/nats-strict-tls.yml

**Logs**
```
Task 1025

Task 1025 | 15:50:39 | Preparing deployment: Preparing deployment (00:00:06)
Task 1025 | 15:50:52 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'bosh'. Errors are:
    - Unable to render templates for job 'openstack_cpi'. Errors are:
      - Error filling in template 'cpi.json.erb' (line 101: Can't find property '["nats.user"]')
```

**Versions (please complete the following information):**
 - Infrastructure: all
 - BOSH version 268.2.0

**Deployment info:**
bosh-deployment

**Comment by voelzmo** [comment]
Turns out, once I made the properties in the CPI optional, template rendering went through smoothly, thanks @xtreme-andrew-su!

Now: should we make the removal of the nats properties an additional ops-file in bosh-deployments such that you can use it when the CPI supports it?

**Comment by xtreme-andrew-su** [comment]
I think that's the next step once we have the appropriate stemcell defined in the cpi.yml
afaik, version xenial 170.2+ of heavy stemcells is registry-less ready, the light stemcells will be any version after 170.6+. Once those are out, I'm all for adding a new ops-file.

Going to close this issue for now. Added a story: https://www.pivotaltracker.com/story/show/162017526
