### ISSUE TITLE
Retry compilation if VM disappears

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh#2076]
**Is your feature request related to a problem? Please describe.**
I mark compilation VMs as Preemptible to save money. Sometimes they get preempted (as expected) and bosh returns the error `Error: Timed out sending 'get_task' to 52e0fb9c-35c4-40f1-92f1-1e7c98286c11 after 45 seconds`. 

**Describe the solution you'd like**
I would like BOSH to spin up a new compilation VM and retry if a compilation VM unexpectedly disappears.

**Describe alternatives you've considered**
Using non-preemptible VMs for compilation.

**Comment by dpb587-pivotal** [comment]
Hi - technically this may be a possibility, however, it would likely be very difficult to differentiate between genuine IaaS issues, terrible compilation/package practices, and preempted/spot termination. Typically compilations are relatively quick and, given most IaaSes have even started minutely billing, the cost savings are minimal compared to the day-to-day operations.

Given the higher implementation cost and lower value for this edge case, it's not something that will be coming up in our roadmap anytime soon. I'm going to close this - if this is something you're passionate about, feel free to investigate it a bit more and reopen if you're looking to start a pull request.
