### ISSUE TITLE
Getting error while migrating bosh manifest version v1 to manifest version v2

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/bosh#2082]
Hi,
We have following bosh director v1 manifest-deploy and running. 
 name: bosh 
 version: '261.4'
 name: bosh-aws-cpi
 version: '64'
 name:  stemcell
 version: '3421.9'  
 we have upgraded bosh directory to 264 as bellow a with manifest file v1.
  name: bosh
  version: '264.7.0'
  name: bosh-aws-cpi
  version: '69'
  name: stemcell  
  version: '3468.21' 
  
Now we are upgrading bosh director manifest version2 using bosh-deployment repository: https://github.com/cloudfoundry/bosh-deployment/blob/v1.0.0/bosh.yml and also try from master branch.
but We are getting following error.
Task 2597 | 07:32:10 | Preparing deployment: Preparing deployment (00:00:00)
                    L Error: Existing instance 'bosh/0' is using IP '10.1.40.5' in availability zone ''
Task 2597 | 07:32:10 | Error: Existing instance 'bosh/0' is using IP '10.1.40.5' in availability zone ''
Exit code 1 

Some Backgroud: in term of upgrading our bosh director and manifest file, we want to have same naming convenstion including ip address of bosh director.

Also analysing the following source code lines:
https://github.com/cloudfoundry/bosh/blob/83b1650f88323f5f35ed2bca3059d2bc27642f36/src/bosh-director/lib/bosh/director/deployment_plan/placement_planner/static_ips_availability_zone_picker.rb#L194

At L196- if ip_az_names.include?(existing_instance_model.availability_zone)
what we understood is that -> V1 bosh manifest file doesnt have any availability zones
whereas the V2 bosh  leverage config and manifest file to upgrade it (via availability zones or is introduced )
Now how do we process - to pass the availability zone info in the manifest files or via which manifest file ?

I have attached bosh debug logs here.
[bosh-debug.txt](https://github.com/cloudfoundry/bosh/files/2580903/bosh-debug.txt)

**Comment by dpb587-pivotal** [comment]
Hello - please avoid closing and reopening issues (and creating duplicate issues). If we have not had a chance to review your issue, feel free to ping with another comment and feel free to mention how/why this is important to you to better help us prioritize concerns.

This looks like the exact same error as https://github.com/cloudfoundry/bosh/issues/1633 - have you had a chance to search previous issues and try the resolution recommended there? Please give `migrated_from` a try and let us know how it goes.

**Comment by lordcf** [comment]
@dpb587 : Thanks for response. After adding 'migrated_from' in bosh.yml , The Error is resolve and bosh update successfully but we loose our previous deployment which was running on bosh .All deployment went to orphaned now. any suggestion for this..

**Comment by dpb587-pivotal** [comment]
It sounds like you're suggesting that BOSH lost its database? Assuming you were updating your existing deployment which was using the `10.1.40.5` IP, `migrated_from` should have used your existing persistent disk that has your BOSH database. Perhaps you can double check your before and after manifests to ensure they were configured correctly.

Otherwise, please clarify what "all deployment went to orphaned" means in your case.

**Comment by h4xnoodle** [comment]
Do you have any orphaned disks that could potentially be the lost database?

Try `bosh disks --orphaned` on your parent bosh. If there is an orphaned disk, this could be your child bosh's disk. Then you could try `bosh attach-disk` to reattach it.

**Comment by dpb587-pivotal** [comment]
@h4xnoodle has a good suggestion, but before you do that it's probably worth investigating why BOSH did not think you wanted a persistent disk. Typically that means you are missing one of the persistent disk options in your manifest. If you don't resolve this, the next time BOSH recreates the VM your persistent disk will be missing again.

Double check that first and ensure you have a persistent disk attached, then you can follow those `attach-disk` steps to swap out the disk with the prior disk.

**Comment by lordcf** [comment]
@dpb587 and @h4xnoodle : Thanks for suggestion there was an persistence disc misconfiguration in manifest. after correct, it worked.
