### ISSUE TITLE
Bosh should be able to recreate one VM without triggering the deployment or affecting other VMs

### ISSUE THREAD

**Issue by XuejiaoZhang** [cloudfoundry/bosh#2086]
**Is your feature request related to a problem? Please describe.**
When we increased disk sizes on 6 VMs, the first VM succeeded and the second one failed, the whole deploy stopped here. 
We would like to roll back. Say the VMs are databases or Kafka, they don't permit to have two nodes down at the same time. So, it's not possible to roll back by deploy with the previous deployment, we were thinking to recreate the second VM to bring it back running, then deploy with the previous deployment. But `bosh recreate` will trigger the deployment, which means it will update the first VM first, as we said, it's not acceptable to have two nodes not running at the same time.

**Describe the solution you'd like**
`bosh recreate ${VM} --without-trigger-deployment`
Provide a parameter to make it possible to recreate one VM only, without triggering the whole deployment or affecting other VMs.

**Comment by giner** [comment]
We worked around the problem by making the second node unresponsive and running `bosh cck` afterwards. BOSH should allow doing this without non-obvious magic involved.

**Comment by mfine30** [comment]
This should be solved now as of BOSH v270.4.0 and the CLI v6.0.0. You can run `bosh recreate <INSTANCE/INDEX> --no-converge` to only recreate the existing instance without updating the entire deployment.
