### ISSUE TITLE
[Feature] Provide API to cancel all queued tasks at once

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#2087]
**Is your feature request related to a problem? Please describe.**
In situation where you want to execute an important task and the job queue is full with other tasks, it can take quite a long time to cancel all of them and execute the important task.

**Describe the solution you'd like**
Bosh director should provide an API which can cancel all queued tasks at once.

**Describe alternatives you've considered**
An alternative could be to implement priorities for tasks. In this way users can put important task in front of other tasks. I think this feature requires much bigger implementation effort. That is why implementing a fast cancel could be the first step to improve the situation. 

**Additional context**
Bosh CLI uses [his](https://github.com/cloudfoundry/bosh/blob/d91550719081220dbdc7c0489d160b07bee203e9/src/bosh-director/lib/bosh/director/api/controllers/task_controller.rb#L6-L17) API to cancel a single task.

**Comment by friegger** [comment]
Implemented with https://github.com/cloudfoundry/bosh/commit/37fef5c3bf52efbcad8ebeeb4dc16835a61a33ee and previous commits.
