### ISSUE TITLE
Bosh level Autoscaling of component

### ISSUE THREAD

**Issue by ashwithahn** [cloudfoundry/bosh#2092]
Hi Team, 
Is there a way to get cpu utilization/ metric of cf components and spin up an instance through bosh?

**Comment by dpb587-pivotal** [comment]
The core BOSH director does not currently have functionality for reactive scaling based on that information. Some basic metrics (e.g. CPU, memory, disk) are emitted by health monitor which you can [forward to external systems](https://bosh.io/docs/hm-config/), and you may be able to respond to those metrics within those systems; but no, there's not built-in support for this.

**Comment by mrosecrance** [comment]
Closing as stale
