### ISSUE TITLE
Getting BOSH director VM vitals

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/bosh#2096]
**Is your feature request related to a problem? Please describe.**
As an operator, I do not have a view into the current state of the BOSH director's VM.

**Describe the solution you'd like**
In order to evaluate BOSH director VM vitals, I would like to use `--vitals` for the director itself.

**Describe alternatives you've considered**
Using prometheus with a `node_exporter` (not ideal), using the IaaS console to view performance of the director VM (also not ideal)

**Additional context**

When running something like `bosh vms --vitals`, you'll see a number of VM stats (VM CID, VM Type,Uptime, CPU, memory, disk, etc.), like so:

```
bosh -d credhub vms --vitals

Deployment 'credhub'

Instance                                      Process State  AZ  IPs           VM CID               VM Type    Active  VM Created At                 Uptime           Load              CPU    CPU   CPU   CPU   Memory       Swap      System      Ephemeral   Persistent
                                                                                                                                                                      (1m, 5m, 15m)     Total  User  Sys   Wait  Usage        Usage     Disk Usage  Disk Usage  Disk Usage
credhub/9539bd38-a6da-410a-91f0-cc9247c8b1a4  running        z2  redacted  i-0b85972ed8be3a389  m4.xlarge  true    Mon Sep  3 03:00:22 UTC 2018  93d 15h 36m 29s  0.05, 0.12, 0.14  -      0.5%  0.0%  0.0%  8% (1.3 GB)  0% (0 B)  40% (31i%)  1% (0i%)    -
credhub/958583aa-a375-46a1-9f65-70be639085ac  running        z1  redacted  i-02ae227e97fd60745  m4.xlarge  true    Mon Sep  3 03:26:20 UTC 2018  93d 15h 10m 37s  0.11, 0.23, 0.16  -      0.4%  0.1%  0.0%  9% (1.4 GB)  0% (0 B)  40% (31i%)  1% (0i%)    -

2 vms

Succeeded
```

But I can't get this same data about the BOSH director VM itself. Getting access to these stats are helpful during debugging, and are important for determining whether the director needs more resources.

`bosh env` only displays the following information:

```
bosh env
Using environment 'redacted' as client 'admin'

Name      bosh
UUID      aa5d0410-2ed3-4cfe-8ae8-08c22a562b3b
Version   268.2.0 (00000000)
CPI       aws_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          local_dns: enabled
          power_dns: disabled
          snapshots: disabled
User      admin

Succeeded
```

Perhaps I'm missing a command? If the director is able to get all these stats from the VMs in deployments it manages using BOSH agent deployed on them, would it not be possible to get the VM vitals from the director itself?

**Comment by mfine30** [comment]
Thanks Aaron (and hey BK). I believe the BOSH Toronto team is actively looking into this or something very similar. I'll connect you all over email in case Frédéric (Toronto PM) has any questions.

ping @freddesbiens @xtreme-andrew-su this seems very related to one of your active stories
https://www.pivotaltracker.com/story/show/161762467

**Comment by freddesbiens** [comment]
Hi @aegershman.

While working on this, we have realized it would be difficult for the director itself to expose metrics in the way you suggest. This is because the various processes making up the director run under [BPM](https://github.com/cloudfoundry-incubator/bpm-release). We cannot easily access hardware properties from a process running inside BPM. 

We will report director VM metrics through Health Monitor in the future. Our engineers are currently working on the implementation and you can follow their progress in this Tracker story: https://www.pivotaltracker.com/story/show/161762467

Generally speaking, you should leverage Health Monitor for anything that has to do with the healthiness of your BOSH environment. While you can obtain some information through the APIs, doing so will have an influence on the director's performance and resource usage. 

We may eventually give operators a way to access metrics through the command line. What is  your specific use case? Most production environments use Prometheus or Healthwatch...

**Comment by aegershman** [comment]
We do use both Prometheus and PCF healthwatch in our critical systems, and so will presumably be ready to ingest that information if the metrics are accessible/reported through health monitor. 

But to your question about specific CLI use case-- it would be the same rationale for why any other VM's vitals in a bosh deployment are accessible via the `--vitals` flag: 

- some (hopefully non-critical) environments aren't hooked up to third-party monitoring systems
- it's more convenient when triaging/debugging is necessary (e.g., especially if third-party support needs a convenient way to request the customer to share the status of their foundation using CLI commands)
- if the information is present (and doesn't incur needless code complex to implement), why not make it accessible via the CLI as it is for other VMs?

Thanks for your time

**Comment by Alexvianet** [comment]
@aegershman @freddesbiens so what is the solution to monitor bosh director vm?

**Comment by stdesantiago** [comment]
You can get this information from going to the ops manager, selecting the bosh director tile and go to the stats tab

**Comment by lrstanley** [comment]
@stdesantiago, that's not a solution though.. what if you're not using opsman? We have many clusters external to opsman. Even if we were for everything, am I expecting engineers to login to 10 different opsmans every day to check the status? That throws out and proactive monitoring too.

I agree with @aegershman, this is something that should be very similarly provided by the cli, and thus also the api, in the same exact way deployment `vms --vitals` exist today -- to the end user anyway, I'm not sure how this is fetched internally. IMO, if BPM is used, I'm not sure why that type of isolation needs to exist on the director, especially if it's only the code that was wrote in the bosh release. In addition, even of such an isolation existed, providing cpu/mem/disk/load data from the kernel is something that should exist through the isolation, is very low risk, and is likely easy to add.

**Comment by lrstanley** [comment]
@aegershman, did you find a solution to this?
