### ISSUE TITLE
stemcell - Ubuntu 18.04.1 LTS (Bionic Beaver) 

### ISSUE THREAD

**Issue by kmacpher67** [cloudfoundry/bosh#2098]
**Is your feature request related to a problem? Please describe.**
Newest version of the Ubuntu 18.04.1 LTS (Bionic Beaver) as stemcell for /bosh-warden-boshlite
https://bosh.io/stemcells

**Describe the solution you'd like**
A stemcell for Ubuntu 18.04.1 LTS (Bionic Beaver) for deployment on bosh-warden-boshlite

**Describe alternatives you've considered**
Building own custom one. 

**Additional context**
Said it would come quicker next release: https://github.com/cloudfoundry/bosh/issues/1249
. (next lts version based stemcell - 18.04 - may come a bit quicker though).

**Comment by JellevdK** [comment]
Please give this LTS release a higher priority, there is already a new one released:
Ubuntu 20.04 LTS (Focal Fossa) https://wiki.ubuntu.com/Releases

**Comment by voelzmo** [comment]
Just leaving this here for documentation: The current state of the BOSH PMC is that it adopted the distributed committer model. There is currently no work done towards creating Bionic stemcells. More context can be found in the announcement on the BOSH mailing list: https://lists.cloudfoundry.org/g/cf-bosh/message/2707

If you're willing to help out creating these stemcells, please reach out to me or Rupa as stated in the announcement.

**Comment by JellevdK** [comment]
@voelzmo yes I will contact you :)
