### ISSUE TITLE
 Timed out pinging to the VMs agent after 600 seconds

### ISSUE THREAD

**Issue by gaurav987654321** [cloudfoundry/bosh#2110]
Hi all,
I am encountering an error during deployment of vm 
Subnet is different but network is same Task 5

Task 5 | 06:07:43 | Preparing deployment: Preparing deployment (00:00:01) Task 5 | 06:07:44 | Preparing package compilation: Finding packages to compile (00:00:00) Task 5 | 06:07:44 | Compiling packages: ruby/aeb9acaed6ce2aa86ce1ce9f4017528be0e2041e (00:11:32) L Error: Timed out pinging to 15fc1ac9-b00d-4190-b828-34efc93382f3 after 600 seconds Task 5 | 06:19:16 | Error: Timed out pinging to 15fc1ac9-b00d-4190-b828-34efc93382f3 after 600 seconds

Task 5 Started Tue Jan 8 06:07:43 UTC 2019 Task 5 Finished Tue Jan 8 06:19:16 UTC 2019 Task 5 Duration 00:11:33 Task 5 error

Updating deployment: Expected task '5' to succeed but state is 'error'

Exit code 1

**Comment by BeckerMax** [comment]
Hi @gaurav987654321 ,
in general this error means that the director could not communicate with the agent. See here for [troubleshooting pinged out agent](https://bosh.io/docs/tips/#unreachable-agent).
First steps could be to investigate the debug log with `bosh task 5 --debug` or checking for network connectivity between agent and director possibly by ssh'ing onto the deployed VM.

**Comment by gaurav987654321** [comment]
Hi @BeckerMax  
thanks for reply 
I checked into network connectivity now  when i am  trying  a deployment i am getting error (IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590)

Task 10 | 04:57:39 | Preparing deployment: Preparing deployment (00:00:01)
Task 10 | 04:57:40 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 10 | 04:57:41 | Creating missing vms: learn-server/a7a46bdf-05a2-413d-b609-b99dbb1ebd71 (0) (00:00:08)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict Expected([201]) <=> Actual(409 Conflict)
excon.error.response
  :body          => "{\"NeutronError\": {\"message\": \"IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590\", \"type\": \"IpAddressAlreadyAllocated\", \"detail\": \"\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "168"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 09 Jan 2019 04:57:49 GMT"
    "X-Openstack-Request-Id" => "req-e39fc11d-e238-4b0c-bb96-d8bb69fd8158"
  }
  :host          => "public-c02.cni.de.atos.net"
  :local_address => "10.0.1.10"
  :local_port    => 45050
  :path          => "/v2.0/ports"
  :port          => 13696
  :reason_phrase => "Conflict"
  :remote_ip     => "185.60.37.113"
  :status        => 409
  :status_line   => "HTTP/1.1 409 Conflict\r\n"
 (IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590).
Check task debug log for details.' in 'create_vm' CPI method (CPI request ID: 'cpi-254577')
Task 10 | 04:57:50 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict Expected([201]) <=> Actual(409 Conflict)
excon.error.response
  :body          => "{\"NeutronError\": {\"message\": \"IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590\", \"type\": \"IpAddressAlreadyAllocated\", \"detail\": \"\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "168"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 09 Jan 2019 04:57:49 GMT"
    "X-Openstack-Request-Id" => "req-e39fc11d-e238-4b0c-bb96-d8bb69fd8158"
  }
  :host          => "public-c02.cni.de.atos.net"
  :local_address => "10.0.1.10"
  :local_port    => 45050
  :path          => "/v2.0/ports"
  :port          => 13696
  :reason_phrase => "Conflict"
  :remote_ip     => "185.60.37.113"
  :status        => 409
  :status_line   => "HTTP/1.1 409 Conflict\r\n"
 (IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590).
Check task debug log for details.' in 'create_vm' CPI method (CPI request ID: 'cpi-254577')

Task 10 Started  Wed Jan  9 04:57:39 UTC 2019
Task 10 Finished Wed Jan  9 04:57:50 UTC 2019
Task 10 Duration 00:00:11
Task 10 error

Updating deployment:
  Expected task '10' to succeed but state is 'error'

Exit code 1
Task 10 | 04:57:39 | Preparing deployment: Preparing deployment (00:00:01)
Task 10 | 04:57:40 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 10 | 04:57:41 | Creating missing vms: learn-server/a7a46bdf-05a2-413d-b609-b99dbb1ebd71 (0) (00:00:08)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict Expected([201]) <=> Actual(409 Conflict)
excon.error.response
  :body          => "{\"NeutronError\": {\"message\": \"IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590\", \"type\": \"IpAddressAlreadyAllocated\", \"detail\": \"\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "168"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 09 Jan 2019 04:57:49 GMT"
    "X-Openstack-Request-Id" => "req-e39fc11d-e238-4b0c-bb96-d8bb69fd8158"
  }
  :host          => "public-c02.cni.de.atos.net"
  :local_address => "10.0.1.10"
  :local_port    => 45050
  :path          => "/v2.0/ports"
  :port          => 13696
  :reason_phrase => "Conflict"
  :remote_ip     => "185.60.37.113"
  :status        => 409
  :status_line   => "HTTP/1.1 409 Conflict\r\n"
 (IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590).
Check task debug log for details.' in 'create_vm' CPI method (CPI request ID: 'cpi-254577')
Task 10 | 04:57:50 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict Expected([201]) <=> Actual(409 Conflict)
excon.error.response
  :body          => "{\"NeutronError\": {\"message\": \"IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590\", \"type\": \"IpAddressAlreadyAllocated\", \"detail\": \"\"}}"
  :cookies       => [
  ]
  :headers       => {
    "Content-Length"         => "168"
    "Content-Type"           => "application/json"
    "Date"                   => "Wed, 09 Jan 2019 04:57:49 GMT"
    "X-Openstack-Request-Id" => "req-e39fc11d-e238-4b0c-bb96-d8bb69fd8158"
  }
  :host          => "public-c02.cni.de.atos.net"
  :local_address => "10.0.1.10"
  :local_port    => 45050
  :path          => "/v2.0/ports"
  :port          => 13696
  :reason_phrase => "Conflict"
  :remote_ip     => "185.60.37.113"
  :status        => 409
  :status_line   => "HTTP/1.1 409 Conflict\r\n"
 (IP address 10.2.1.2 already allocated in subnet 24b9eb5b-5aeb-4fa0-9ad3-cae7d2593590).
Check task debug log for details.' in 'create_vm' CPI method (CPI request ID: 'cpi-254577')

Task 10 Started  Wed Jan  9 04:57:39 UTC 2019
Task 10 Finished Wed Jan  9 04:57:50 UTC 2019
Task 10 Duration 00:00:11
Task 10 error

Updating deployment:
  Expected task '10' to succeed but state is 'error'

Exit code 1

**Comment by BeckerMax** [comment]
Did you change anything in the manifest or infrastructure that led to the first error go away and the second one to appear?
The error output tells the problem: Bosh wants to use an ip for deploying that is already in use by another vm.
Firstly, you can check in horizon or the openstack cli which server uses this ip currently. Secondly, this could also be a configuration issue of the networks section in your deployment manifest. If you share the redacted deployment manifest/cloud-config this could give more hints.

In general, it seems that your questions are about the general usage of bosh rather than a bug report or feature request. In these cases I think using our official community slack would give you faster responses and allow a more direct communication.

Slack: #bosh on <https://slack.cloudfoundry.org>

**Comment by h4xnoodle** [comment]
Closing as it's an individual's setup issue. We hope it's resolved now :)
