### ISSUE TITLE
Getting error while ssh into bosh created vm 

### ISSUE THREAD

**Issue by gaurav987654321** [cloudfoundry/bosh#2111]
Running SSH:
  1 error occurred:
        * Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/home/cloud-user/.bosh/tmp/ssh-priv-key460041926 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/home/cloud-user/.bosh/tmp/ssh-known-hosts790110061 -o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l jumpbox 185.60.37.175 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 10.2.1.2 -l bosh_cbcb674e4888403', stdout: '', stderr: '': exit status 255

**Comment by mrosecrance** [comment]
Could you please fill out the bug report form? There isn't enough information here for us to see if this is a reproducible issue or something to do with configuration.

**Comment by jan-the-one** [comment]
@mrosecrance Hello, 

I am facing the same issue on the newest BOSH CLI version and BOSH-LITE, and I do not know what the solution was for this issue. Is there some bug-report form I can fill in?
