### ISSUE TITLE
Some persistent disks are not configured to expected CPI in multi-CPIs deployment

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#2119]
**Describe the bug**
We are using multi-CPIs (legacy CPI and new CPI for same infrastructure) to get old deployments (using trusty stemcell, it only can work with legacy CPI) and new deployments (Xenial stemcell, only can work with new CPI) be managed by the same BOSH director. After we configured multi-CPIs in BOSH director, most of thing worked as expected except some persistent disks. We checked `persistent_disks` table in BOSH DB, not all disks are migrated to new CPI, for examples:
```
bosh=> select disk_cid, instance_id, cpi from persistent_disks
;
 disk_cid | instance_id |    cpi
----------+-------------+-----------
 1279xxxx |        1xx|
 1279xxxx |        1xx |
 632xxxx  |         1xx |
 632xxxx  |         3xx |
 990xxxx  |         2xx |
 4017xxxx |        2xx |
 4952xxxx |        2xx | softlayer
 4952xxxx |        2xx | softlayer
 4952xxxx |        2xx | softlayer
 5834xxxx |        2xx | softlayer
 6099xxxx |        2xx | softlayer
```

`softalyer` refers to the new CPI, `softlayer-legacy` refers to legacy CPI, in `cloud-config`, we defined like this:
```
cpis:
- name: softlayer
  type: softlayer
- name: softlayer_legacy
  type: softlayer_legacy
  migrated_from:
  - name: ""
```

I am not sure if it's a bug, but don't understand why some persistent disks are not configured to using new CPI (`softlayer`). It brought a big trouble when updating new Xenial stemcell in the deployment, it uses legacy CPI to detach/attach disk for our Xenial stemcell, it didn't match, always failed. Currently, the work around is to hack `persistent_disks` table in BOSH DB, but it's apparently not a safe way.

**Expected behavior**
All persistent disks are configured to use new CPI after redeploying the BOSH director.

**Comment by mattcui** [comment]
2 more findings:

1. The `cpi` property kept empty for all persistent disks which were created before deploying multiple CPIs.

2. The older version of BOSH (like 263.3) doesn't care much about `cpi` property for persistent disks, there always use the new CPI to detach/attach disks during stemcell update. But the latest version of BOSH (like 268.3.0) cares about it, it used legacy CPI to operate disks without `softlayer` cpi property.

**Comment by dpb587-pivotal** [comment]
Can you provide details and exact error messages from the errors you were seeing? Internally, the `cpi` field may not be backfilled until a new persistent disk replaces the old one.

**Comment by jfmyers9** [comment]
Hi @mattcui,

We are going to close this issue due to inactivity. If this is still a problem, please feel free to reopen this issue or create a new one with the relevant information requested.

Best,

@jfmyers9 && @belinda-liu, CF BOSH
