### ISSUE TITLE
v268.5.0 incorrectly detects configuration change when none occurred

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/bosh#2120]
**Describe the bug**

v268.5.0 bosh director seems to always want to update all instances, even when nothing has changed.

**To Reproduce**

A few days ago one of our CI/CD environments updated to the latest `bosh-deployment` which was a bump to `v268.5.0` of bosh director.

Since then, each time our pipeline runs (which amongst other things, deploys v7.0.0 of cf-deployment) we see it update all instances, even when the manifest has not changed.

**Expected behavior**

It to churn for about 2 minutes, determine nothing has changed, and continue (as it did with previous version of bosh director).

**Logs**

Normal output of deploy task:

```
Using deployment 'cf'

Release 'cf-smoke-tests/40.0.44' for stemcell 'ubuntu-xenial/170.19' already exists.
...
Task 465081 | 06:20:52 | Verifying remote release: Verifying remote release (00:00:00)
Task 465081 | 06:20:52 | Extracting release: Extracting release (00:00:00)
Task 465081 | 06:20:52 | Verifying manifest: Verifying manifest (00:00:00)
Task 465081 | 06:20:52 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 465081 | 06:20:52 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Task 465081 | 06:20:52 | Compiled Release has been created: bosh-dns-aliases/0.0.3 (00:00:00)

Task 465081 Started  Thu Jan 17 06:20:51 UTC 2019
Task 465081 Finished Thu Jan 17 06:20:52 UTC 2019
Task 465081 Duration 00:00:01
Task 465081 done

Task 465082

Task 465082 | 06:20:54 | Preparing deployment: Preparing deployment (00:00:32)
Task 465082 | 06:22:14 | Preparing package compilation: Finding packages to compile (00:00:02)

Task 465082 Started  Thu Jan 17 06:20:54 UTC 2019
Task 465082 Finished Thu Jan 17 06:22:16 UTC 2019
Task 465082 Duration 00:01:22
Task 465082 done
```

Current behavior:

```
Using deployment 'cf'

Release 'cf-smoke-tests/40.0.44' for stemcell 'ubuntu-xenial/170.19' already exists.
...
Task 472091 | 00:39:12 | Downloading remote release: Downloading remote release (00:00:01)
Task 472091 | 00:39:13 | Verifying remote release: Verifying remote release (00:00:00)
Task 472091 | 00:39:13 | Extracting release: Extracting release (00:00:00)
Task 472091 | 00:39:13 | Verifying manifest: Verifying manifest (00:00:00)
Task 472091 | 00:39:13 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 472091 | 00:39:13 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Task 472091 | 00:39:13 | Compiled Release has been created: bosh-dns-aliases/0.0.3 (00:00:00)

Task 472091 Started  Tue Jan 22 00:39:12 UTC 2019
Task 472091 Finished Tue Jan 22 00:39:13 UTC 2019
Task 472091 Duration 00:00:01
Task 472091 done

Task 472092

Task 472092 | 00:39:15 | Preparing deployment: Preparing deployment (00:00:32)
Task 472092 | 00:39:47 | Preparing deployment: Rendering templates (00:00:40)
Task 472092 | 00:40:30 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 472092 | 00:40:32 | Updating instance adapter: adapter/2f34940a-ee7c-42fd-a61c-9b7e649de767 (0) (canary)
... and updates all instances ...
```

**Versions (please complete the following information):**

 - Infrastructure: AWS
 - BOSH version: last bosh-deployment (v268.5.0)
 - BOSH CLI version v5.3.1
 - Stemcell version - which ever ships with bosh-deployment and cf-deployment v7.0.0
 - UAA and credhub from cf-deployment

**Deployment info:**

We can supply more info later if needed - not able to easily provide right now. It's a `cf-deployment` with a heap of operator files on top - we see the same behaviour with other deployments on the same director.

**Additional context**

We rolled our bosh-deployment release back to the previous commit (and manually removed the harmless index add schema migration row from the DB so that it would start).

After doing so we noted that on the first run of our pipeline it wanted to update all instances again, but on subsequent runs it did not.

Looking at debug logs for tasks we noted the following for each instance:

```
D, [2019-01-21T04:40:26.502278 #2536] [] DEBUG -- DirectorJobRunner: configuration_changed? changed FROM: 2bc32930c7fe8bdea64cae0018c9f4238a855677 TO: abc84ea307e6ec1cd0648b96029bd26ff4319494 on instance tls-credhub/ae4213c7-7b7c-4cd4-9c4e-120949edade0 (0)
```

even though so far as we could tell no configuration values are changing.

After rolling back then the last deploy (on the reverted version) produced to the same TO configuration hash as was observed on deployments prior to the bosh director update.

It seems as though v268.5.0 is calculating a different and unpredictable configuration hash each time which makes it think it needs to update the instances unnecessarily. I wish I knew Ruby better to debug further.

**Comment by aeijdenberg** [comment]
It seems as though with each deploy bosh is generating a different `.bosh/links.json` file inside of each job directory.

I ran a successful deploy with v268.5.0 and saved a copy of config for a job, then ran a deploy again and noted the only difference was this file.

It would appear that this file shared the same logical content, however the order of the array elements differs with each deploy.

e.g.

```bash
# Files have different content
$ cat a/.bosh/links.json | shasum
32437ce93d8e583b0c6a9bd2c263ef662512de6e  -
$ cat b/.bosh/links.json | shasum
70fed0b61c23250c8e5d3b558aff00eab2ba18b6  -

# But if you deterministically sort the elements, they are actually the same
$ cat a/.bosh/links.json | jq -c .[] | sort | shasum
9867a2e904ef55702c7c44d7a441dc25c7d0d9d5  -
$ cat b/.bosh/links.json | jq -c .[] | sort | shasum
9867a2e904ef55702c7c44d7a441dc25c7d0d9d5  -
```

**Comment by aeijdenberg** [comment]
I think the bug is that this array isn't sorted before output <https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director-core/lib/bosh/director/core/templates/job_template_renderer.rb#L108>

Looks like it never has been sorted, so technically this bug may have always been present, but perhaps didn't present itself until now because of the way that map was generated changed in <https://github.com/cloudfoundry/bosh/commit/39748765525aa13f084a27f0903c65671f978ff8>?

**Comment by dpb587-pivotal** [comment]
@aeijdenberg, thank you for your quick reporting, investigating, and fixing of this!
