### ISSUE TITLE
Calling `monit stop` on a Director worker leaves forked processes behind

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2123]
**Describe the bug**
When `monit stop` is called for a worker process, it should kill all the forks it created – [which it does for each task picked from the job queue](). I assume, this was the intention of [calling this during `monit stop`](https://github.com/cloudfoundry/bosh/blob/f89d45b13e01892199213218ea0656ede2e78f62/jobs/director/templates/worker_ctl.erb#L55-L57), but due to how [`list_child_processes` is implemented](https://github.com/cloudfoundry/bosh/blob/f89d45b13e01892199213218ea0656ede2e78f62/jobs/director/templates/ps_utils.sh#L25), it doesn't find the existing child process and the task goes on.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director
2. Upload any stemcell and cloud-config
3. Deploy any manifest
4. check the debug log on which worker this task is running
5. `ssh` into bosh director
6. See that there are two processes for the worker that's running the task with `ps -ed pid,command | grep bosh-director-worker`
7. Run `monit stop` on the worker
8. See that only one worker is stopped and the other  still remains

**Expected behavior**

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
  - BOSH v268.5.0 (previous versions as well, ever since we switched away from templating the config file multiple times)

**Comment by mfine30** [comment]
This look good. I'm going to close the story and it should be available/fixed in the next release of BOSH.
