### ISSUE TITLE
Disabling config server causes some very strange behavior

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/bosh#2125]
**Describe the bug**
It appears if you deploy a director with config server, then disable config server, you get into a state where you can't really do anything anymore
**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on bosh-lite with config server
2. Enable bosh dns runtime config
3. Deploy a deployment
4.  Disable config server
5. Deploy a deployment 
6.  Get  ```Error: Failed to generate variable '/dns_healthcheck_tls_ca' from config server: Director is not configured with a config server```
5.  Revert the runtime config to blank 
5.  Deploy a deployment - notice that the bosh dns addon is still applied erroneously in the diff despite `bosh runtime-config` being empty.  The deploys continue to fail  ```Failed to generate variable '/dns_healthcheck_tls_ca' from config server: Director is not configured with a config server``` 

**Expected behavior**
Reverting the runtime config is successful and subsequent deploys do not fail

**Versions (please complete the following information):**
 - Infrastructure: bosh-lite  virtualbox
 - BOSH version 268.4.0
 - BOSH CLI version5.4.0-891ff634-2018-11-14T00:21:14Z
 - Stemcell version xenial-170.12

**Comment by h4xnoodle** [comment]
Hi @scottschulthess 

When you deployed on step #8, were any options like `--skip-drain` used? 

What I suspect could be happening here is that redeploying your deployment would cause the current one to `drain`. The drain process uses job templates, which are rendered again from the current deployment state, not the target deployment state you're aiming for.

Would you be able to give this a try with `--skip-drain` and see what happens?

- Rebecca, BOSH, Pivotal

**Comment by scottschulthess** [comment]
Hey h4xnoodle thank you for the response,

IIRC I tried deleting the deployment and redploying it a few times to try to get out of this and was not able to.   The only way I found to get out was to delete the bosh director (this was on BOSH lite).

**Comment by scottschulthess** [comment]
We tried reproducing this morning and were not able to.   Currently don't have a theory as to why it wasn't working previously. Sorry!
