### ISSUE TITLE
Enable feature flag per deployment to allow keeping failed VM around for debugging

### ISSUE THREAD

**Issue by degaurab** [cloudfoundry/bosh#2127]
**Is your feature request related to a problem? Please describe.**
Currently this is a director level flag (`keep_unreachable_vms`) applicable for all deployment. It will be nice to have it on more granular level per-deployment based. 
Also as a flag on `bosh-cli` flag for `deploy command`

https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p%3ddirector.debug.keep_unreachable_vms

**Describe the solution you'd like**
- Feature is already in BOSH director applicable to all deployments. Should be easy to create granularity at per deployment level feature.
- Also if we can add it as feature flag in bosh-cli deploy command.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Original Requester**: @xtreme-conor-nosal (Conor Nosal)

**Comment by h4xnoodle** [comment]
What is the benefit or problem solved by having it on the deployment level? 

Would this deployment-level flag override the director flag?
