### ISSUE TITLE
Be able to BOSH deploy something when a GCP zone is out of resources

### ISSUE THREAD

**Issue by mjj209** [cloudfoundry/bosh#2129]
**The Problem**

The problem is that GCP resources are finite, and zones will occasionally run out of resources. This issue presents itself to a BOSH user via the message:

`The zone 'projects/********/zones/us-central1-f' does not have enough resources available to fulfill the request.`

This causes the BOSH deploy to fail.

The error message details that the user should try another zone, or wait. There is no visibility into the 'right' zone to use, as the only insight into the problem stated above is to try and create a VM. There is an open bug tracker here: https://issuetracker.google.com/issues/72811715

There also isn't an indication as to when the problem will clear up, as one zone going down on the GCP platform does not impact any SLAs, given other zones are available inside a region. So nothing is posted to the public GCP Status pages.

**A modest proposal for a solution**

The CPI could automatically retry to create the VM on a different zone so that the deploy can be successful. There is a corresponding issue on the BOSH CPI repo: https://github.com/cloudfoundry/bosh-google-cpi-release/issues/304, as the CPI potentially could implement the same logic.

**Describe alternatives you've considered**
We can just wait, but sometimes the wait is 8-18 hours. We can move to a different zone/region, but there's no way to know if that zone/region has capacity.

**Additional context**

**Comment by h4xnoodle** [comment]
@mjj209 

I don't think that bosh should automatically choose another AZ when deploying, if this error occurs. The operator can adjust their manifest easily, and redeploy.

Bosh doesn't intend to automate networking -- that is something the operator is responsible for configuring. As the deployment manifest/cloud-config/runtime-config are the 'source of truth', there would be immediate discrepancies between manifest and what actually happened. This becomes incredibly hard to manage. Now if you were to use the same manifest, Bosh would try to relocate your VM. 

Bosh isn't a networking automation tool, it is a deployment and release management tool. I can understand your thinking, but it would be incredibly difficult to manage for subsequent deployments. This feature would require a lot more work than just selecting a new AZ.

Closing this issue as we will not implement this. Thank you for giving this some thinking and filing the issue. Apologies it took so long to get back to you on this.
