### ISSUE TITLE
Updating from an implicit link to an explicitly-blocked link does not recompute properties

### ISSUE THREAD

**Issue by tvs** [cloudfoundry/bosh#2130]
**Describe the bug**
When transitioning from an implicitly-consumed link to an explicitly blocked link, BOSH does not trigger a update of the affected VMs:

```
  instance_groups:
  - name: worker
    jobs:
    - name: kubelet
+     consumes:
+       cloud-provider: nil

Continue? [yN]: y

Task 23

Task 23 | 01:13:48 | Preparing deployment: Preparing deployment (00:00:10)
Task 23 | 01:14:15 | Preparing package compilation: Finding packages to compile (00:00:00)

Task 23 Started  Thu Jan 31 01:13:48 UTC 2019
Task 23 Finished Thu Jan 31 01:14:15 UTC 2019
Task 23 Duration 00:00:27
Task 23 done

Succeeded
```

In this example, there is a `master` instance group that is providing a `cloud-provider` link which is getting implicitly consumed by the `worker` instance group's `kubelet` job and thus templating data into a file that is intended to be empty.

Additionally, forcing an update event on the VM (either through `bosh recreate` or by modifying a job property) does not cause the link properties to be recomputed and the file continues to be templated with data from the implicit link:

```
  instance_groups:
  - name: worker
    jobs:
    - name: kubelet
      properties:
        kubelet-configuration:
          authentication:
            anonymous:
-             enabled: false
+             enabled: true

## Note that `consumes.cloud-provider: nil` is still true, here ##

Continue? [yN]: y

Task 24

Task 24 | 01:18:42 | Preparing deployment: Preparing deployment (00:00:08)
Task 24 | 01:19:08 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 24 | 01:19:08 | Updating instance worker: worker/35128fd9-5de7-4cab-b0d6-75f923151e15 (0) (canary) (00:01:02)

Task 24 Started  Thu Jan 31 01:18:42 UTC 2019
Task 24 Finished Thu Jan 31 01:20:10 UTC 2019
Task 24 Duration 00:01:28
Task 24 done

Succeeded
$ bosh -d cfcr ssh worker/0 -c "sudo cat /var/vcap/jobs/kubelet/config/cloud-provider.ini"
Using environment '30.0.0.11' as client 'ops_manager'

Using deployment 'cfcr'

Task 35. Done
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stderr | Unauthorized use is strictly prohibited. All access and activity
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stderr | is subject to logging and monitoring.
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stdout |
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stdout | ... some file contents that shouldn't be there...
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stdout |
worker/35128fd9-5de7-4cab-b0d6-75f923151e15: stderr | Connection to 30.0.1.3 closed.
```

**To Reproduce**
Steps to reproduce the behavior (example):
1. Generate a release with two jobs - one that provides a link and another that optionally consumes it for the purpose of putting data into some file.
2. Deploy the two jobs while allowing the second to consume the first through an implicit link.
3. Update the manifest so that the second job explicitly blocks the link, e.g.:

```
- name: consumer
   consumes:
     producer: nil
```

4. `bosh ssh` and `cat` the `consumer` file

**Expected behavior**
Because we are explicitly blocking the link, that should be treated as a link update and cause the properties to be recomputed and the affected job to be re-templated accordingly.

**Versions (please complete the following information):**
 - Infrastructure: vSphere
 - BOSH version: 267.7.0
 - BOSH CLI version 5.3.1
 - Stemcell version: ubuntu/xenial-250.4

**Additional context**
* Explicitly blocking link consumption is defined here: https://bosh.io/docs/links/#consumers

>Optional consumers may be specified as `nil` in the deployment manifest to block consumption of any providers.

* [Kubelet's job spec](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubelet/spec#L63-L66)

**Comment by degaurab** [comment]
/cc @charleshansen 

Hi @tvs 
We think this issue is fixed in latest version of BOSH director. Based on this commit: https://github.com/cloudfoundry/bosh/commit/444de6a2bed256adee98df0695151698a6023378

So please try using 268.6+ release and let us know if the issue persists.

Thanks.

**Comment by belinda-liu** [comment]
Hi @tvs,

Did you try using a newer director? If there's no other problems, we'd like to close this issue.

Thanks,
@belinda-liu && @xtreme-behrouz-soroushian, CF BOSH team

**Comment by belinda-liu** [comment]
Hi @tvs,

We're going to close this issue for now because of inactivity. Feel free to reopen this if you continue to have this issue.

Thanks!
