### ISSUE TITLE
Not able to show the details of specific task

### ISSUE THREAD

**Issue by surazzarus** [cloudfoundry/bosh#2133]
I am using the Director HTTP API to get the list of tasks. However if I tried to get the specific task details as showed on [https://bosh.io/docs/director-api-v1/#get-task-result](url) , I see a blank response with Status 200. 
Also if I check the details of task with only id [https://bosh.io/docs/director-api-v1/#get-task](url) it works and shows only few details.
Am I missing anything in that api call ??

**Comment by h4xnoodle** [comment]
Hi @surazzarus could you please post sanitized output and the curl command you're running? What do you get when you use the CLI for these tasks?

**Comment by belinda-liu** [comment]
Hi @surazzarus,

Are you still experiencing this problem? If not, we'd like to close this issue.

Thanks!

**Comment by belinda-liu** [comment]
Hi @surazzarus,

We're going to close this issue for now due to inactivity. Feel free to reopen if you need to.

Thanks!
