### ISSUE TITLE
`bosh clean-up --all` removes releases referenced by runtime config

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/bosh#2136]
**Describe the bug**
The bosh director deployed by Pivotal Operations Manager (opsman) comes with `bosh-dns` release uploaded and a runtime config that references it. After `bosh clean-up --all` is executed, `bosh-dns` release gets removed since there are no deployments using it.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on any IaaS
1. Upload `bosh-dns` release
1. Create a config that references `bosh-dns`
1. Run `bosh clean-up --all`
1. Run `bosh releases` and `bosh-dns` release is no in the list of releases

**Expected behavior**
I wouldn't expect `bosh clean-up --all` to delete releases that are referenced by a config. Technically, the release is "in use" because there is a config that uses it when a deployment is created.

**Logs**

**Versions (please complete the following information):**
 - Infrastructure: any
 - BOSH version: Noticed in `267.7` but probably in other versions where configs are a feature
 - BOSH CLI version: v5.4.0
 - Stemcell version: any

**Deployment info:**
n/a

**Additional context**
n/a

**Comment by amuessig** [comment]
That also applies for stemcells. I just experienced that. However, for stemcells the stemcell is still shown in `bosh stemcells` and it is also available in vcenter. I had to re-upload it `bosh upload-stemcell <name> --fix`.

**Comment by dpb587-pivotal** [comment]
@amuessig your scenario sounds like a different issue. The `bosh clean-up --all` would try to clean up unused stemcells, but, assuming the cleanup task is successful, would no longer be visible in `bosh stemcells` nor vCenter. Rather than getting into that here, please create a new issue to discuss that separately; and be sure to include the relevant task logs of the `clean-up` which claims to have removed the stemcell, along with the later `stemcells` and `upload-stemcell` output.

**Comment by davewalter** [comment]
Are there any plans to address this issue? It is causing us (Release Integration) pain in our CI pipelines that reuse a pool of BOSH directors for different test scenarios. We would like to be able to delete all deployments and then run `bosh clean-up --all` after the testing is finished to prepare the director for the next test, but this deletes the `bosh-dns` release and `bosh deploy` does not re-upload it, even though the runtime-config specifies a URL for the release.

**Comment by mfine30** [comment]
We have addressed this in https://www.pivotaltracker.com/story/show/167737389. It should be available as soon as we cut a new release, v270.5.0

**Comment by mfine30** [comment]
Cutting v270.5.0 right now so I'm going to close this
