### ISSUE TITLE
Compiled bits for release packages stay in the blobstore, although the compiled-for-stemcell has beem removed

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2143]
**Describe the bug**
After compiling a release's packages for a stemcell, these results are stored in the blobstore. The only point in time when these compiled bits are removed is when the corresponding release version is removed. Our expectation was, that the compiled bits would also be removed when the stemcell they have been compiled for is removed.

This causes the blobstore to grow in an unbound fashion if you have releases which stay on a stable version for a long time, but you happen to bring in new stemcell versions regularly.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director
2. Upload a stemcell and cloud-config
3. Deploy any manifest
4. `bosh inspect-release` on the release, see that it has been compiled for the stemcell/version
5. Update stemcell major version
6. re-deploy the manifest without changing the release version
7. `bosh inspect-release` on the release, see that it has been compiled for both stemcell/versions
8. `bosh clean-up --all` and see that the old stemcell gets removed, because it is no longer used
9. `bosh inspect-release` on the release, see that it *still* shows being compiled for the stemcell/versions which just got removed

**Expected behavior**
The compiled bits for a release are also removed when the stemcell they have been compiled for is removed.

**Versions (please complete the following information):**
 - Infrastructure: any
 - BOSH version v268.6.0

**Additional context**
Related slack thread: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1519245087000581?thread_ts=1519158130.000183&cid=C02HPPYQ2

**Comment by dpb587-pivotal** [comment]
We've touched on this before in some internal discussions a while back. One thing we need to keep in mind is compiled releases which float (e.g. exported release/1.2.3 for xenial/250.7 was uploaded, but it's being used by a deployment running xenial/250.11).

I guess that's mentioned in the Slack thread, but worth calling out here. Especially with respect to some of the [recent discussions](https://docs.google.com/document/d/1XH_9bXYWD2RIiR6OrLUO0Ai2KK4DDn7zty2LuNtt54k/edit) around how director picks the floating compiled release to use.

**Comment by jhvhs** [comment]
@dpb587 @voelzmo 
What we see in a long-running environment is that the blobstore gets really bloated
when running updates in a timely fashion. For example, when inspecting the diego 
release together with engineers from BBR (@aclevername, @terminatingcode),
after performing a `bosh clean-up --all` on our long-running environment we see
the following output:

```
$ bosh stemcells

Name                                    Version   OS
bosh-google-kvm-ubuntu-trusty-go_agent  3541.52*  ubuntu-trusty
~                                       3541.4*   ubuntu-trusty
bosh-google-kvm-ubuntu-xenial-go_agent  170.30*   ubuntu-xenial
~                                       97.57*    ubuntu-xenial
~                                       97.19*    ubuntu-xenial
```

```
$ bosh inspect-release diego/2.22.1
Job
auctioneer/f20aa450b4f682b3af1c636e3403aa02926c9139b3c2ee256e3eadf162efe64f
... more jobs, nothing special ...

12 jobs

Package                                                                                   Compiled for
?>> auctioneer/e935376138903524c5df577fafd1a61f6d5591b4c3e88955ac7f4c6069c0d421           ubuntu-xenial/170.15 <<?
~                                                                                         ubuntu-xenial/170.25
~                                                                                         (source)
... some more packages along the same lines ...
certsplitter/fe1cfa89d614a8438e4cbcff5a7b5d56d333e19278a992a433c596ddad9b737d             (source)
~                                                                                         ubuntu-xenial/170.15
~                                                                                         ubuntu-xenial/170.25
?>> ~                                                                                     ubuntu-xenial/97.53 <<?
... more package with at least two 170 blobs and an optional 97 blob ...
```

We inspected the `compiled_releases` table on the bosh director, and have got the following report:

```
bosh => select count(*), stemcell_version from compiled_packages group by stemcell_version order by stemcell_version;
 count | stemcell_version
-------+------------------
   285 | 170.15
     4 | 170.19
     4 | 170.21
    88 | 170.24
   282 | 170.25
    39 | 170.30
     5 | 3312.20
     6 | 3363.20
     4 | 3363.24
     7 | 3363.25
     6 | 3363.26
     4 | 3363.27
     8 | 3363.29
     7 | 3363.30
     8 | 3363.31
    13 | 3363.37
    10 | 3363.42
    10 | 3363.44
     1 | 3363.53
     1 | 3363.61
     9 | 3421.18
    14 | 3421.19
    14 | 3421.20
     4 | 3421.24
    15 | 3421.26
    15 | 3421.32
    13 | 3421.34
    13 | 3421.35
    11 | 3421.37
    11 | 3421.38
     8 | 3421.44
     8 | 3421.46
    14 | 3421.9
    11 | 3445.11
    14 | 3445.16
     8 | 3445.17
    15 | 3445.19
    11 | 3445.21
    12 | 3445.22
    12 | 3445.23
    11 | 3445.24
     5 | 3445.30
     3 | 3445.32
     8 | 3445.42
     5 | 3445.48
     6 | 3445.51
     2 | 3468.13
     2 | 3468.16
    14 | 3468.21
     2 | 3468.22
    42 | 3468.25
    12 | 3468.27
    31 | 3468.28
    15 | 3468.30
    27 | 3468.42
    14 | 3468.46
    15 | 3468.51
    20 | 3468.54
    29 | 3468.64
    11 | 3468.67
    38 | 3468.69
    11 | 3468.71
    49 | 3468.73
    11 | 3468.78
    40 | 3541.12
    37 | 3541.25
    47 | 3541.30
    78 | 3541.34
    31 | 3541.36
    29 | 3541.37
     9 | 3541.4
    14 | 3541.44
    14 | 3541.46
    14 | 3541.48
    14 | 3541.49
    16 | 3541.52
    10 | 3541.57
    31 | 3541.59
    12 | 3541.60
    10 | 3541.61
     1 | 3586.16
     1 | 3586.24
     2 | 3586.25
    73 | 3586.26
    75 | 3586.27
    23 | 3586.36
    23 | 3586.40
    79 | 3586.42
    95 | 3586.43
    96 | 3586.46
    96 | 3586.52
    24 | 3586.54
    24 | 3586.56
    91 | 3586.57
    17 | 3586.60
     2 | 3586.65
     2 | 3586.66
    11 | 97
     3 | 97.16
    14 | 97.17
    57 | 97.19
    59 | 97.28
    12 | 97.31
    74 | 97.32
    61 | 97.34
   133 | 97.39
    22 | 97.41
    22 | 97.42
    44 | 97.43
    38 | 97.47
    38 | 97.49
   187 | 97.53
    15 | 97.57
(113 rows)
```
We can't help, but notice that the number of compiled packages for 170.15 is almost equal to
the number of compiled packages from 170.25.

Incidentally, seeing the 3363 stemcell stuff lying around, we decided to see if it actually is on the disk
```
bosh => select id, blobstore_id from compiled_packages where stemcell_version='3363.42' limit 3;
  id  |             blobstore_id
------+--------------------------------------
 3276 | 7d316dc8-4f5a-42e9-750c-d10c9d803d24
 3281 | 89c78c9d-545a-4e4f-747c-acd6d6ae0cd8
 3312 | e6e83827-ddfc-4754-76c6-5a04fa10a448
(3 rows)
```

Then we have indeed located the physical files on the director VM:

```
bosh/0:/var/vcap/store/blobstore/store# tree -D | grep 89c78c9d
│   ├── [Dec  5  2017]  89c78c9d-545a-4e4f-747c-acd6d6ae0cd8
```

Our pain point that the blob store on our director VM is bloated up to the 86Gb size with those and similar files,
which prevents us from consistently and regularly backing up the director using BBR.

**Comment by jhvhs** [comment]
The above is an investigation we ran as part of a follow-up of the issues we have mentioned in https://github.com/cloudfoundry/bosh/issues/2032#issuecomment-435469995

**Comment by voelzmo** [comment]
@jhvhs thanks for your data and cross-linking issue #2032 here.

@dpb587-pivotal thanks for the explicit mention of the floating releases complication. On deleting a stemcell, we could still have some delete mechanism for blobs based on major version matching, right?

**Comment by jhvhs** [comment]
According to https://github.com/cloudfoundry/bosh/blob/31e25224d914aa87c6e8bba2e921091356c2a5eb/src/bosh-director/lib/bosh/director/jobs/helpers/stemcell_deleter.rb#L10, the stemcell deletion process only triggers the CPI cleanup, but does not take care of anything else.

**Comment by dpb587-pivotal** [comment]
@voelzmo yeah, probably; just something to keep in mind, at least.

**Comment by charleshansen** [comment]
Looking through this issue myself for the first time. It looks like the core issue is that there is no way to clean up old compiled packages from the blobstore. I'd vote for `bosh clean-up --all` having logic to delete blobs that don't match major versions. I'm more skeptical of directly linking the cleanup to deleting a stemcell. Do you also expect `bosh delete-stemcell` to trigger this cleanup behavior?

**Comment by voelzmo** [comment]
@charleshansen 
> Do you also expect bosh delete-stemcell to trigger this cleanup behavior?

Thanks for having a look at this! By reading my original issue above again, I realized that I should have phrased the `Expected behavior` section a bit differently to make it more clear:
> Expected behavior
The compiled bits for a release are also removed on `bosh clean-up [--all]` when the stemcell they have been compiled for is removed.

I don't expect `bosh delete-stemcell` to delete blobs from the blobstore. Regularly calling `bosh clean-up` is necessary anyways, so it would be perfectly fine to do the work there.

**Comment by cunnie** [comment]
`bosh clean-up --all` fixes this problem as long as you remember to run it frequently.

I ran into this problem today; exhausted the space on `/var/vcap/store`; I expanded the disk size from 64GB to 80GB:
```
df -h /var/vcap/store
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1        79G   60G   15G  81% /var/vcap/store
```
The blobstore accounts for **99.5%** of the disk space:
```
du -m /var/vcap/store | sort -rn | head -3
62227	/var/vcap/store
61943	/var/vcap/store/blobstore/store
61943	/var/vcap/store/blobstore
```
`bosh clean-up --all` cleared up over half the available space:
```
du -m /var/vcap/store | sort -rn | head -3
26492	/var/vcap/store
26177	/var/vcap/store/blobstore/store
26177	/var/vcap/store/blobstore
```
