### ISSUE TITLE
Links cannot be consumed during redeployment of the producer

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#2151]
**Describe the bug**

Deployment A provides a link and deployment B consumes this link. Both get deployed correctly and links get resolved. Then, A and B get redeployed in parallel. We then see the following error:
  ```
- Failed to resolve link 'api' ...
- No link providers found
```

This also happens when the deployment of A is a no-op. 

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a deployment which provides a link
2. Deploy a second deployment which consumes the link
3. Redeploy both deployments in parallel

**Expected behavior**
There are multiple options
* Consumers cannot be deployed during the deployment of the producer, with a proper error message.
* BOSH coordinates the order of the producer/consumer deployment.

More context is available in this slack discussion: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1551694827023100

**Comment by h0nIg** [comment]
one additional expected behaviour: the old producer is resolvable as long as the new one has not been deployed
