### ISSUE TITLE
director_sync_dns is not resilient against postgres downtimes

### ISSUE THREAD

**Issue by NautiluX** [cloudfoundry/bosh#2156]
**Describe the bug**
When the postgres database is down while `director_sync_dns` tries to execute SQL, the following is logged, and the process starts freezing.

```
E, [2019-03-13T13:07:14.029192 #1] [Bosh::Director::SyncDnsScheduler] ERROR -- Director: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.: (conn: 47105553987160) SELECT NULL
```

or, in case of AWS RDS:

```
Director: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly: (conn: 47147911793360) SELECT NULL
```

`director_sync_dns` is unable to recover from this state when the database comes back.
`monit restart director_sync_dns` is necessary to recover from this state.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on VirtualBox (bosh-lite)
2. ssh into the director VM
3. run `monit stop postgres`
4. Observe `/var/vcap/sys/log/director/sync_dns.stdout.log`
5. run `monit start postgres` after the error mentioned above is shown

**Expected behavior**
`director_sync_dns` should recover from the missing database as soon as the database is back, or at least shut down, so `monit` could restart it.

**Versions (please complete the following information):**
 - BOSH version 268.7.0

**Additional context**
* This issue occurs for example when AWS RDS postgres gets updated and hence restarted. The
* BOSH director seems to be resilient against postgres downtimes. It logs similar errors, but recovers as soon as the database comes back.
* To my understanding, [the connection validator plugin](https://github.com/cloudfoundry/bosh/blob/4725403005925606d7ba2b2bcd582d8925be7e9a/src/bosh-director/lib/bosh/director/config.rb#L347) should prevent this situation, but doesn't seem to do so in case of `director_sync_dns`.

**Comment by friegger** [comment]
Fixed with #2154
