### ISSUE TITLE
https://bosh.io/docs/cli-v2/#install shouldn't have the "#install" anchor

### ISSUE THREAD

**Issue by Pivotal-Christopher-Wong** [cloudfoundry/bosh#2158]
**Describe the bug**
When navigating to https://bosh.io/docs/cli-v2/#install, I would expect to find information on how to install CLI v2. However, this page now holds commands, and the actual procedure is found on https://bosh.io/docs/cli-v2-install/

**To Reproduce**
1. Navigate to https://bosh.io/docs/cli-v2/#install

**Expected behavior**
Installation instructions

**Additional context**
Really, this is just an issue to log a chore so that the anchor is renamed.
This is also important because there is also no anchor for #commands for that page.

**Comment by mrosecrance** [comment]
Where did you find the link to bosh.io/docs/cli-v2/#install ? That might be easier to change than restructuring the docs to move usage and installation into the same page (if it even should be done).

**Comment by miguelverissimo** [comment]
the anchor #install does not exist in the cli-v2 page, so it anchors to the top of the page. 
I'll create a story to better name these pages and consolidate the meta information on CLI v2 in one easier to reference page (e.g. https://bosh.io/docs/cli-v2/)
