### ISSUE TITLE
Post-Stop script does not update when redeploying

### ISSUE THREAD

**Issue by carlhejiayu** [cloudfoundry/bosh#2160]
**Describe the bug**
If I update a release's post-stop script and redeploy the release, the post-stop script is not updated.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Create a dummy release with a dummy job that has a post-stop script and upload release to bosh.
2. bosh deploy.
3. Update the post-stop script, recreate and re-upload the release to bosh.
4. Updated the manifest with the new version of the release and redeploy (we do see that bosh notify the user about the change in version of the dummy release)
5. ssh into the vm and find the post stop script for that dummy  job and you see that the post stop script is not updated

**Expected behavior**
We should see the post stop script should be updated and should be the version of the new release.

**Versions (please complete the following information):**
 - BOSH version [268.5.0]
 - BOSH CLI version [5.4.0]
 - Stemcell version [ubuntu-xenial/170.9]

**Comment by simonxca** [comment]
Nevermind, I reverified and this is working.

**Comment by h4xnoodle** [comment]
Closing this now as it works, thanks @simonxca
