### ISSUE TITLE
If snapshots are disabled and taking a snapshot let the user know that it'll be skipped

### ISSUE THREAD

**Issue by s4heid** [cloudfoundry/bosh#2161]
**Is your feature request related to a problem? Please describe.**
When using a director with `snapshots: disabled` and taking a snapshot of an instance, the command succeeds without further notice that taking the snapshot will be skipped.
```
$ bosh take-snapshot -d concourse
Using environment 'https://10.0.0.6:25555' as client 'admin'

Using deployment 'concourse'

Task 2582. Done

Succeeded
```

Only in the task debug log I see the following lines:
```
I, [2019-03-19T15:26:29.029164 #30507] [task:2583]  INFO -- DirectorJobRunner: taking snapshot of: db/0 (i-01df1234567db1234)
I, [2019-03-19T15:26:29.029223 #30507] [task:2583]  INFO -- DirectorJobRunner: Snapshots are disabled; skipping
I, [2019-03-19T15:26:29.029262 #30507] [task:2583]  INFO -- DirectorJobRunner: Done
```

**Describe the solution you'd like**
I'd expect a warning which explains the user that bosh does not take a snapshot, e.g.
```
$ bosh take-snapshot -d concourse
Using environment 'https://10.0.0.6:25555' as client 'admin'

Using deployment 'concourse'

Warning: Snapshots are disabled; skipping.

Task 2582. Done

Succeeded
```

**Comment by dpb587-pivotal** [comment]
If we're going to change this, what would you think of it failing with an error instead? The operator essentially requested an unsupported operation; so it seems weird to pretend it was successful. I'd rather push operators to not making the call at all if it's not something their environment supports.

I remember finding this behavior confusing and concerning when I was first starting to use BOSH.

**Comment by s4heid** [comment]
Good question. Instead of failing with an error I thought about just being more verbose and giving the operator a hint that his actions have no effect. I see your point that in most cases this behavior pretends a false truth and the operator's original intention wouldn't be fulfilled. On the other hand, I'm a bit concerned that some people may use this command in scripts and rely on the current behavior that bosh doesn't fail. Apart from that I totally agree with you and think this should be the correct behavior of bosh.

**Comment by dpb587-pivotal** [comment]
> some people may use this command in scripts and rely on the current behavior that bosh doesn't fail

Agreed this is likely the case and would require teams to update their scripts to explicitly decide if they think snapshots are important. Personally, I think it's fine to break that behavior, so long as it's called out in release notes, probably a major version bump, and possibly a notice to cf-bosh if there's enough concern.

Eventually, there would probably be requests for an easier way to check if it's enabled than `bosh env | grep snapshots | grep enabled`.

But, would be good to hear other opinions on this sort of change.

**Comment by voelzmo** [comment]
see also: https://github.com/cloudfoundry/bosh/issues/1085 which has much less context than this one.

**Comment by jchesterpivotal** [comment]
My opinion, implied in #1085, is that this should be an error.
