### ISSUE TITLE
retrieve manifest of failed deployment

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh#2163]
Followup to https://github.com/cloudfoundry/bosh-cli/issues/497

**Is your feature request related to a problem? Please describe.**
If a deployment fails, I would like to retrieve the manifest of the failed deployment

**Describe the solution you'd like**
In https://github.com/cloudfoundry/bosh-cli/issues/497#issuecomment-450666838 @dpb587 suggested that deployment manifests could be migrated to use the same workflow as configs.

**Describe alternatives you've considered**
In https://github.com/cloudfoundry/bosh-cli/issues/497 I suggested adding a `--current` flag to `bosh manifest` as a smaller, backwards compatible change.

Extracting manifest from debug logs: https://github.com/kkallday/deployment-extractor

**Additional context**
https://github.com/cloudfoundry/bosh/issues/1043

**Comment by pnikonowicz** [comment]
this might work for you:

```
bosh task --debug 207
```

in the logs should be the manifest that was attempted to be deployed
