### ISSUE TITLE
Not all command line options listed in docs 

### ISSUE THREAD

**Issue by dirkjot** [cloudfoundry/bosh#2165]
**Describe the bug**

In the online docs, only some command line options are mentioned and not all. Because the docs do not mention that this is only a subset, options are hard to discover by users.  

To complicate matters, running `bosh --help` will point to the online docs.

Only `bosh <SUBCOMMAND> --help` will list all the options. 

**To Reproduce**

**Part 1:**

When I go to the Bosh docs for, for example, the [deploy command](https://bosh.io/docs/cli-v2/#deploy), there is a nice short write-up on what 'deploy' does.   It lists some options, but does not mention that there is a number of other options available.  From the online docs:
```
bosh -e my-env -d my-dep deploy manifest.yml [-v ...] [-o ...]
```

Missing are options like `--dry-run`, `--max-in-flight` etc etc. 

Even if I know the name of the option, I can search the online docs for `dry-run` all I want, but I will never find that it so much as exists.

**Part 2:** 

When I run `bosh --help` I will be pointed at the online docs, making me think that these are exhaustive and authoritative:

```
± |master ✓| → bosh --help
Usage:
  bosh [OPTIONS] <command>

Application Options:
  -v, --version          Show CLI version
      --config=          Config file path (default: ~/.bosh/config) [$BOSH_CONFIG]

[...]

Available commands:
  add-blob                Add blob                                           https://bosh.io/docs/cli-v2#add-blob
  alias-env               Alias environment to save URL and CA certificate   https://bosh.io/docs/cli-v2#alias-env
  attach-disk             Attach disk to an instance                         https://bosh.io/docs/cli-v2#attach-disk
```

**Part 3:**

I can find that dry-run exists by listing the full options from the command line only: 
```
 bosh deploy --help
Usage:
  bosh [OPTIONS] deploy [deploy-OPTIONS] PATH

Update deployment

https://bosh.io/docs/cli-v2#deploy

Application Options:
  -v, --version                           Show CLI version
      --config=                           Config file path (default: ~/.bosh/config) [$BOSH_CONFIG]

[...]

[deploy command options]
      -v, --var=VAR=VALUE                 Set variable

[..]

          --dry-run                       Renders job templates without altering deployment
```

**Expected behavior**
The online documentation should at least list all the options that exist.  It is the documentation people want to trust.  

**Versions (please complete the following information):**
bosh --version
version 5.4.0-891ff634-2018-11-14T00:21:14Z

bosh.io website as of 2019-03-27

**Additional context**

Real life story: People told me there was a dry-run option and I decided they were mistaken after some online research.  I even ran `bosh --help`.  Only after the third person told me about it did I find it.

**Comment by aashah** [comment]
Hey, we took a look at this issue and think it ought to be discussed with our PM. We gave the story a label (`pre-ipm`) to ensure we discuss it this coming Friday.

Thanks,
Aakash & @jaresty

**Comment by miguelverissimo** [comment]
@dirkjot thanks for reporting this issue. I've just submitted a [PR](https://github.com/cloudfoundry/docs-bosh/pull/681) that synchronizes the docs with the help text you find when doing `bosh <command> -h`.

Closing this issue as it will be resolved by merging that PR.
