### ISSUE TITLE
BOSH release for bosh v268.7.0 seems to be broken

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh#2171]
[The release v268.7.0](https://bosh.io/d/github.com/cloudfoundry/bosh?v=268.7.0) should have the following change included https://github.com/cloudfoundry/bosh/commit/35bb08fa731c84ce7159e0d57b081cce36690006 however it doesn't. The release seems to be inconsistent with the code on github.

**Comment by mrosecrance** [comment]
We've fixed this for future releases however I don't believe we'll change the tag for this or other past releases. The commit you've mentioned will be in the next release
