### ISSUE TITLE
Automatic log archiving to prevent Bosh performance degradation over time

### ISSUE THREAD

**Issue by daniellavoie** [cloudfoundry/bosh#2172]
**Is your feature request related to a problem? Please describe.**
Large Cloud Foundry deployment ends up with directors being constantly running tasks for monitoring or operation purposes. I've witnessed directors with more than 10 000 000 tasks being logged by Bosh over time. Within the director deployment, they are a couple of scripts that scans the bosh folders (`/var/vcap/store/director`) to apply a `chown` command. Bosh has no embedded purge or archiving process. So over time, you are only experiencing a degrading performance of Bosh as the chown is a blocking operation. This degradation can impact bosh releases deployments.

**Describe the solution you'd like**
Maybe Bosh could embed an automatic parameterized archiving process that would move logs out of the `chown` path. File system usage is not a concern as it is typically monitored by operation teams. The side effect caused by this high number of logs files is not really convenient to investigate as all you can observe are tasks that timeout. Operators can implement purging themselves but I think Bosh could be more helpful to all operators by embedding that action and prevent all teams from having to setup custom automation.

**Describe alternatives you've considered**
Custom automation by every operation team that work with bosh.

**Additional context**
[An example of a chown command](https://github.com/cloudfoundry/bosh/blob/687a185b63feb3535d909863b9e7181d4a16332c/jobs/health_monitor/templates/health_monitor_ctl.erb#L35)

**Comment by voelzmo** [comment]
Hey @daniellavoie,

Thanks for raising this issue! To provide some additional context: which versions of BOSH are you running currently? We took a stab at improving the `chown` command executed in `pre-start` with https://github.com/cloudfoundry/bosh/pull/2107. In our example, this improved the runtime of the command from 30 seconds to <1 second with 300k tasks.

As follow-up question: I'm understanding that you're seeing degraded performance of BOSH which you are attributing to these `chown` statements. Could you help me understand in more detail, which specific issues you are seeing? What happens when you're deploying? Can you post some log output as well?

If you're not using a recent version of BOSH yet (as of now, this is 268.7), could you update and try if this fixes your issues, given that we included the above `chown` speedup?

Thanks!

**Comment by ntdt** [comment]
Hi,
With bosh v267.8.0 and 1M of tasks, it takes 2 hours to do chown when I did a change on syslog endpoint.

**Comment by voelzmo** [comment]
@ntdt Thanks for the additional data point! Above question goes also to you: On which Director version is this? Version 268.7 should have significantly faster performance – I would be interested what your timings are there.

**Comment by ntdt** [comment]
Thank you, we'll wait for Pivotal to update the Bosh version it OpsManager.

**Comment by jfmyers9** [comment]
Hi @ntdt,

Due to the fact that this has been improved in the latest version of BOSH, we are going to close this issue. Please feel free to re-open a new issue if you still experience this behavior after your deployment is upgraded to `v268.7+`.

Best,

@jfmyers9, CF BOSH

**Comment by poblin-orange** [comment]
Hello,
still having performance issue with old directors, typically chown the tasks directory.
I think an automated log archiving is required (besides optimizing perf degradation). 

Can this be reopened or shall i open a new issue ?

**Comment by jfmyers9** [comment]
Hi @poblin-orange,

Is this an issue with you on the most recent releases of BOSH?

We don't support older BOSH releases at the moment, so we are unlikely to make any changes to historical releases.

Best,

@jfmyers9

**Comment by poblin-orange** [comment]
Hi @jfmyers9 
Yes, we are using bosh 270.7.0, on an old bosh deployment  (2 years old). I guess the lack of history archival is a genuine global issue.

**Comment by jfmyers9** [comment]
For this specific issue, I believe [this change](https://github.com/cloudfoundry/bosh/blob/2c3ad0339ebc2b0e8ea2ec82f672fcef9af93550/jobs/director/templates/pre-start.erb#L11) solved the problem for most deployments.

If you are seeing degradation after this, I would suggest creating a new issue describing the degradation and the environment that you are seeing it in.

We do archive tasks at a certain point. Currently we keep ~2000 of each task type before removing the tasks from the database and their corresponding task logs from disk. If you are finding that that is still too many tasks to keep around you can try tuning [this property](https://github.com/cloudfoundry/bosh/blob/2c3ad0339ebc2b0e8ea2ec82f672fcef9af93550/jobs/director/spec#L110-L112) to see if that helps.

Best,

@jfmyers9

**Comment by poblin-orange** [comment]
@jfmyers9 thks for the pointer. We will try this, and reopen a separate issue
