### ISSUE TITLE
Support dumping BOSH task logs into syslog

### ISSUE THREAD

**Issue by danniel1205** [cloudfoundry/bosh#2173]
**Is your feature request related to a problem? Please describe.**
BOSH task log is missing from syslog. After some investigation, I found the BOSH task log is stored inside of postgresql db. I am blocked from using any logging analytics services.

**Describe the solution you'd like**
I am expecting to see BOSH task logs from syslog or from local file system instead of DB, which allows me to integrate BOSH with logging analytics service. 

**Describe alternatives you've considered**
Executing a script on BOSH vm to keep pulling DB logs and dump onto local file system. And configure syslog to pick them up.

**Additional context**
![Screen Shot 2019-04-04 at 5 57 25 PM](https://user-images.githubusercontent.com/1971842/55666152-2fb24500-57ff-11e9-9d59-c28e53239bba.png)
![Screen Shot 2019-04-04 at 5 56 58 PM](https://user-images.githubusercontent.com/1971842/55666153-33de6280-57ff-11e9-90bf-c91067a8bcc1.png)

**Comment by mrosecrance** [comment]
Hi @danniel1205,

Could you clarify your use case? By Syslog are you referring to using [the syslog release](https://github.com/cloudfoundry/syslog-release)? Or specifically wanting to see task logs in `/var/vcap/sys/log`?

You can also get the logs by running `bosh task <id> --debug`. Does that help?

**Comment by belinda-liu** [comment]
Hey @danniel1205,

Is this still an issue? If not, we are going to close it due to inactivity.

**Comment by danniel1205** [comment]
@mrosecrance @belinda-liu 
From syslog, we only see bosh director logs. We would like to see more than just bosh director logs, like bosh tasks and bosh job logs. 

To be more specific, if user configures a logging server to collect syslog, user would like to see not only bosh director logs, but also bosh tasks and bosh job logs on their logging server side.

**Comment by belinda-liu** [comment]
Hi @danniel1205,

Understood. This isn't something that we intend to support any time soon. Task logs often contain credentials and other sensitive information, which is not something that we want to be sent over syslog. 
In regards to the job logs, you can colocate the syslog release (mentioned above) to send those to a syslog server.

Thanks for the feedback!

**Comment by belinda-liu** [comment]
We're going to close this issue due to inactivity. Thanks again for the feedback, and feel free to reopen if needed.
