### ISSUE TITLE
Resurrection fail - and worse, creates instances that thinks is healthy but isn't running anything

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry/bosh#2176]
**Describe the bug**

We recently tested bosh resurrection to ensure that VMs would be recreated successfully if an AWS instance was terminated.

We noted that some instances (e.g. uaa) came back up fine, however other instances, such as the CF "api" instances would not.

**To Reproduce**

Steps to reproduce the behavior (example):

1. Deploy a bosh director on AWS with credhub / UAA enabled
2. Upload latest stemcell listed in cf-deployment (v8.0.0, however we think we've seen this in the past with earlier versions).
3. Deploy cf-deployment (v8.0.0)
4. Verify `bosh is -d cf` shows all healthy.
5. Go into AWS console, EC2 and terminate one of the "api" instances.
6. Wait a few minutes for the bosh resurrector to kick in.
7. Note that the "scan and fix" job fails:

```
Task 612636

Task 612636 | 05:33:20 | Scanning 1 VMs: Checking VM states (00:00:14)
Task 612636 | 05:33:34 | Scanning 1 VMs: 0 OK, 0 unresponsive, 1 missing, 0 unbound (00:00:00)
Task 612636 | 05:33:34 | Applying problem resolutions: VM for 'api/67d7a896-d497-4180-b9b3-eeab4d11491f (0)' with cloud ID 'i-0c9f51b63385e88cc' missing. (missing_vm 775): Recreate VM and wait for processes to start (00:01:27)
                      L Error: - Unable to render jobs for instance group 'api'. Errors are:
  - Unable to render templates for job 'route_registrar'. Errors are:
    - Error filling in template 'registrar_settings.json.erb' (line 8: Can't find link 'nats')
  - Unable to render templates for job 'policy-server'. Errors are:
    - Error filling in template 'policy-server.json.erb' (line 55: `cc_hostname` and `cc_port` properties were not supplied as manifest properties, nor were found in `cloud_controller_https_endpoint` link)
  - Unable to render templates for job 'policy-server-internal'. Errors are:
    - Error filling in template 'policy-server-internal.json.erb' (line 27: Can't find link 'dbconn')
    - Error filling in template 'database_ca.crt.erb' (line 1: Can't find link 'dbconn')
  - Unable to render templates for job 'loggregator_agent'. Errors are:
    - Error filling in template 'bpm.yml.erb' (line 7: Can't find link 'doppler')
Task 612636 | 05:35:01 | Error: Error resolving problem '104': - Unable to render jobs for instance group 'api'. Errors are:
  - Unable to render templates for job 'route_registrar'. Errors are:
    - Error filling in template 'registrar_settings.json.erb' (line 8: Can't find link 'nats')
  - Unable to render templates for job 'policy-server'. Errors are:
    - Error filling in template 'policy-server.json.erb' (line 55: `cc_hostname` and `cc_port` properties were not supplied as manifest properties, nor were found in `cloud_controller_https_endpoint` link)
  - Unable to render templates for job 'policy-server-internal'. Errors are:
    - Error filling in template 'policy-server-internal.json.erb' (line 27: Can't find link 'dbconn')
    - Error filling in template 'database_ca.crt.erb' (line 1: Can't find link 'dbconn')
  - Unable to render templates for job 'loggregator_agent'. Errors are:
    - Error filling in template 'bpm.yml.erb' (line 7: Can't find link 'doppler')

Task 612636 Started  Wed Apr 24 05:33:20 UTC 2019
Task 612636 Finished Wed Apr 24 05:35:01 UTC 2019
Task 612636 Duration 00:01:41
Task 612636 error
```

8. Run `bosh is -d cf` and note that the api servers show as healthy and running. However if you run `bosh is -d cf --ps` you will note that no processes are actually running on the API server.

To fix, we disable the resurrector, run `bosh delete-vm -d cf <vm id>`, and the re-run our original deployment script.

**Expected behavior**

Resurrection to succeed, including starting all the jobs on the new API instance.

**Logs**

Can supply specific logs upon request.

**Versions (please complete the following information):**

 - Infrastructure: AWS
 - BOSH version 269.0.0 (00000000)

**Additional context**

May be related to #2175

**Comment by aeijdenberg** [comment]
cc @gordcorp @m-richo

**Comment by voelzmo** [comment]
Potentially related to #2175? Not sure if there's a general issue with templates used or information provided during rendering in resurrection scenarios.

**Comment by charleshansen** [comment]
Thanks for the bug report. 

I have had difficulty reproducing this so far. scan and fix always recreates the VM without problems. 

Did you have any failed deployments after the successful deployment before deleting the VMs? That can cause different behavior. Also, is this problem unique to director 269.0? Do you see it in 268.6? We thought we fixed behavior like this after 268.6, but maybe it just shifted the bugs around.

**Comment by aeijdenberg** [comment]
@charleshansen , pretty sure we did not have any failed deployments before deleting the VMs.

I'm not sure about older versions of bosh director - at this point all of our envs are on 269.0 so I don't have access to an older one to test - but anecdotally I think we may have observed this at least once in the past for the CF api instances.

When you're reproducing - have you verified that you can log into the VM and that the jobs are installed and are actually running?

What we observed is that scan and fix would recreate the VM, and that a listing of bosh instances would show it as healthy, but adding `--ps` would show no jobs actually installed on it.

I'll have a good look in our dev environment today which just successfully installed cf 8.1 and see if I can narrow anything down.

**Comment by aeijdenberg** [comment]
@charleshansen - I also wasn't able to reproduce this this on our dev environment, but was able to in our staging (next in our pipeline).

While the versions are slightly different (dev is cf 8.1, staging is cf 8.0), I suspect that's not significant.

What might a different is that dev is configured to scale to 1, ie only deploy a single API instance. Our staging env has 3. I wonder if that triggers any differences in how the templates render?

**Comment by aeijdenberg** [comment]
So I changed the instance count of our API instances to 2 in our dev environment (via our operator file) and reployed with bosh.

After a successful deploy, I then terminated one API instance `api/0b3d8834-a74e-40f7-9861-8082e6249c81 (1)` via the AWS console, and observed the resurrector happily recreate it successfully:

```
$ bosh task 615603
Using environment 'director.bosh.cld.internal' as client 'admin'

Task 615603

Task 615603 | 04:53:25 | Scanning 1 VMs: Checking VM states (00:00:13)
Task 615603 | 04:53:38 | Scanning 1 VMs: 0 OK, 0 unresponsive, 1 missing, 0 unbound (00:00:00)
Task 615603 | 04:53:38 | Applying problem resolutions: VM for 'api/0b3d8834-a74e-40f7-9861-8082e6249c81 (1)' with cloud ID 'i-00215eac5fe8d1284' missing. (missing_vm 1000): Recreate VM and wait for processes to start (00:03:27)

Task 615603 Started  Fri Apr 26 04:53:25 UTC 2019
Task 615603 Finished Fri Apr 26 04:57:05 UTC 2019
Task 615603 Duration 00:03:40
Task 615603 done

Succeeded
```

I then terminated the other instance (`api/67d7a896-d497-4180-b9b3-eeab4d11491f (0)`) via the AWS console and observed it fail during recreation:

```
$ bosh task 615618
Using environment 'director.bosh.cld.internal' as client 'admin'

Task 615618

Task 615618 | 05:01:25 | Scanning 1 VMs: Checking VM states (00:00:13)
Task 615618 | 05:01:38 | Scanning 1 VMs: 0 OK, 0 unresponsive, 1 missing, 0 unbound (00:00:00)
Task 615618 | 05:01:39 | Applying problem resolutions: VM for 'api/67d7a896-d497-4180-b9b3-eeab4d11491f (0)' with cloud ID 'i-057260565a0ec712e' missing. (missing_vm 775): Recreate VM and wait for processes to start (00:01:26)
                      L Error: - Unable to render jobs for instance group 'api'. Errors are:
  - Unable to render templates for job 'policy-server'. Errors are:
    - Error filling in template 'policy-server.json.erb' (line 55: `cc_hostname` and `cc_port` properties were not supplied as manifest properties, nor were found in `cloud_controller_https_endpoint` link)
  - Unable to render templates for job 'policy-server-internal'. Errors are:
    - Error filling in template 'policy-server-internal.json.erb' (line 27: Can't find link 'dbconn')
    - Error filling in template 'database_ca.crt.erb' (line 1: Can't find link 'dbconn')
Task 615618 | 05:03:05 | Error: Error resolving problem '107': - Unable to render jobs for instance group 'api'. Errors are:
  - Unable to render templates for job 'policy-server'. Errors are:
    - Error filling in template 'policy-server.json.erb' (line 55: `cc_hostname` and `cc_port` properties were not supplied as manifest properties, nor were found in `cloud_controller_https_endpoint` link)
  - Unable to render templates for job 'policy-server-internal'. Errors are:
    - Error filling in template 'policy-server-internal.json.erb' (line 27: Can't find link 'dbconn')
    - Error filling in template 'database_ca.crt.erb' (line 1: Can't find link 'dbconn')

Task 615618 Started  Fri Apr 26 05:01:25 UTC 2019
Task 615618 Finished Fri Apr 26 05:03:05 UTC 2019
Task 615618 Duration 00:01:40
Task 615618 error

Capturing task '615618' output:
  Expected task '615618' to succeed but state is 'error'

Exit code 1
```

I'm curious about the problem resolution code - the one that succeeded said `1000` - the one that failed says `missing_vm 775`...

**Comment by charleshansen** [comment]
I tried again to reproduce with your new steps and can't do it. For context, here is what I have tried.

Bosh 269
CF Deployment 8.1. Just the plain `cf-deployment.yml` with no ops files.

This naturally deploys 2 `api` vms, which include the `policy-server` job. I've tried killing and rekilling both of those vms in lots of different ways, but nothing different happens. All templates are always rendered and all processes are always running.

That said, this looks like a real bug and I would love to reproduce it. I don't know how it could really matter, but what kind of ops files do you have on your cf-deployment? Also, are there any addons that could be causing trouble?

Minor clarification: the number after `missing_vm` is something like a VM ID. `missing_vm 775` means that VM number 775 is missing, it isn't problem resolution code 775. On my new deployment for this investigation, the numbers are much lower.

I also looked into the potentially related issue 2175, I think that is actually a different problem.

Writing down some thoughts here for pickup next week...

Looking at the code a little bit, the line that fails in the dev environment is in the [policy-server](https://github.com/cloudfoundry/cf-networking-release/blob/9d7d16b3863807c62ab9859f786a46c6aeb4e97c/jobs/policy-server/templates/policy-server.json.erb#L51) there is a link that is normally provided by the [cloud_controller_ng job](https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec) in the same instance_group but for some reason it isn't available during your scan and fix.

In the original example, the failure was `route-registrar`, consuming the `nats` link, which is from an entirely different instance group that is hopefully not failing.

The failures are both for links from the same instance group and from a different group. Also, both the `link` function and the `if_link` function are failing (it would be pretty weird if only one failed).

If you didn't already check this, I would really think you somehow had a partially failed deployment that updated the `api` VM but was otherwise a failed deployment. It might be possible that links don't make the same sense in that scenario.

**Comment by aeijdenberg** [comment]
Have been playing around a bit today - increased number of API servers in dev env to 5.

When terminating them one at a time via the AWS console, 4 out of 5 came back fine.

The one with index 1 failed, the next 4 succeeded, then I tried the first one again and it failed (again).

I was about to state that the one which failed was the same one that failed above (ID 775) - but it's not! Rather it's 1000, which succeeded above!

So it seems somewhat arbitrary...  When checking the logs in debug mode, I can see jobs rendering in differing order, but not in such a way which is consistent with success or failure so far as I can tell.

We do have a bunch of operator files, but nothing that seems obvious.

If you wanted to pair on this, I'd be happy to demo in our environment. Ping me on the CF slack (username aeijdenberg) - note I'm based in the Sydney timezone.

**Comment by h4xnoodle** [comment]
We're getting more data from other places with the same output you're experiencing @aeijdenberg, and it seems to be a bit random, as per your last comment. Another way we've seen this reproduced is simply `bosh recreate` over an instance_group with a few instances instead of the resurrector. 

We'll keep you updated on what we find! Any other insights you obtain are also helpful :)

**Comment by aeijdenberg** [comment]
@h4xnoodle - thanks. I think it's important that at least 2 quite separate issues are addressed:

1. **(most important)** If a bosh scan and fix / recreate fails, for any reason, then the resulting instance must not report as healthy. ie in this case, no jobs were scheduled on the instance due to the rendering failure, yet it still shows as green / running via `bosh is` - and via whatever mechanism Prometheus uses to identify the instance as healthy. 

2. Whatever the specific issue is that is causing this particular template rendering failure.

This reminds me a lot of https://github.com/cloudfoundry/capi-release/issues/125 - where the biggest issue identified was in the lifecycle management - bosh thought something was healthy (when it wasn't), and that impedance mismatch eventually caused all apps in a CloudFoundry install to hard fail.

If we fix just issue (1) above, that'll at least mean that operators who pay attention to their AlertManager alerts will at least know that there's an issue to resolve - whereas right now, if an instance unexpected fails, and doesn't come back up again, no one will know in an HA environment, until it's too late.

**Comment by h4xnoodle** [comment]
Absolutely agree @aeijdenberg on fixing issue #1. I'll create a story to prioritize today.

**Comment by h4xnoodle** [comment]
Story to track the direct bug of instances reporting as healthy when they don't have intended jobs https://www.pivotaltracker.com/story/show/165722970
