### ISSUE TITLE
bosh templates are not updated when they are co-located and consume links

### ISSUE THREAD

**Issue by FelisiaM** [cloudfoundry/bosh#2187]
**Describe the bug**
When deploying a VM with a co-located errand that consumes links from a job on the same VM it seems that BOSH _sometimes_ does not propagate changes of properties in the link provider to the link consumers in the errand resulting in improperly rendered templates.

**To Reproduce**
Steps to reproduce the behavior (example):
We were only able to reproduce this on Pivotal deployed Cloud Foundry (PCF 2.4), please reach out to @apshirley if you require access to an environment with which to reproduce this, or help reproducing it. See the steps below:
Steps:
1. Get Pivotal OpsManager env (2.4)
1. deploy Pivotal MySql with 3 plans (1, 2, 3) active (other 2 plans set as inactive in OpsMan and set to `null` in the manifest )
1. Run register-broker (runs as part of the OpsMan apply changes)
1. run `cf service-access`
    shows all the plans (1, 2, 3) with access `all`

-----

1. Set two more plans as inactive (2, 3)
1. Run register broker
1. run `cf service-access`
    shows only one plan (1) with access `all` and no other plans

-----

1. Set one of the plans to active again (2) (and cf_service_access as enabled)
1. Run register broker
1. run `cf service-access`
    shows only one plan with access `all` (1)
    and one plan (2) as access `none`

*Note*:
 The Service Broker's catalog endpoint keeps being updated with the latest changes to the service catalog. The broker gets this config from the manifest, not via a link but directly. However, the `register-broker` errand consumes the very same config via a link.

**Expected behavior**
The link consumer is updated with the latest changes.

**Logs**
From Pivotal Operations Manager:
```
===== 2019-06-05 09:54:24 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=10.0.0.5 --deployment=pivotal-mysql-7da3f27c6129da3c7ff7 deploy /var/tempest/workspaces/default/deployments/pivotal-mysql-7da3f27c6129da3c7ff7.yml"
Using environment '10.0.0.5' as client 'ops_manager'

Using deployment 'pivotal-mysql-7da3f27c6129da3c7ff7'

 instance_groups:
 - name: dedicated-mysql-broker
   jobs:
   - name: broker
     properties:
       service_catalog:
         plans:
+         - cf_service_access: "&lt;redacted&gt;"
+           description: "&lt;redacted&gt;"
+           instance_groups:
+           - azs:
+             - "&lt;redacted&gt;"
+             instances: "&lt;redacted&gt;"
+             name: "&lt;redacted&gt;"
+             networks:
+             - "&lt;redacted&gt;"
+             persistent_disk_type: "&lt;redacted&gt;"
+             vm_extensions: "&lt;redacted&gt;"
+             vm_type: "&lt;redacted&gt;"
+           lifecycle_errands: {}
+           metadata:
+             bullets:
+             - "&lt;redacted&gt;"
+             display_name: "&lt;redacted&gt;"
+           name: "&lt;redacted&gt;"
+           plan_id: "&lt;redacted&gt;"
+           properties:
+             leader_follower:
+               enabled: "&lt;redacted&gt;"
+           quotas:
+             service_instance_limit: "&lt;redacted&gt;"
Task 124

Task 124 | 09:54:25 | Preparing deployment: Preparing deployment (00:00:04)
Task 124 | 09:54:33 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 124 | 09:54:34 | Updating instance dedicated-mysql-broker: dedicated-mysql-broker/dc9ef2bf-c300-4766-b832-27fdee8e0ae4 (0) (canary) (00:00:45)
Task 124 Started  Wed Jun  5 09:54:25 UTC 2019
Task 124 Finished Wed Jun  5 09:55:19 UTC 2019
Task 124 Duration 00:00:54
Task 124 done

Succeeded
===== 2019-06-05 09:55:20 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=10.0.0.5 --deployment=pivotal-mysql-7da3f27c6129da3c7ff7 deploy /var/tempest/workspaces/default/deployments/pivotal-mysql-7da3f27c6129da3c7ff7.yml"; Duration: 55s; Exit Status: 0
```
`bosh task 124 --debug` logs will be sent separately as they contain secrets.

**Versions (please complete the following information):**
 - Infrastructure: `GCP`
 - BOSH version `268.2.5` 
 - BOSH CLI version: `5.5.1-7850ac98-2019-05-21T22:28:36Z`
 - Stemcell version `ubuntu-xenial/97.108`
```
Using environment '10.0.0.5' as client 'ops_manager'

Name      p-bosh
UUID      d5cfff30-2e88-429a-8697-1e1ba38e372d
Version   268.2.5 (00000000)
CPI       google_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          local_dns: enabled
          power_dns: disabled
          snapshots: disabled
User      ops_manager

Succeeded
```

**Comment by jfmyers9** [comment]
Hi @FelisiaM,

I've tried to recreate this issue on both the master of BOSH and the version that you are deploying and have been unsuccessful. Specifically I made an errand that consumed a link and placed the contents of that link into a template. I then co-located this errand on the same instance that was providing it. I used the same structure for the property as the on-demand-service broker i.e. `properties.service_catalog.plans`. 

After every deploy, the template was always successfully updated in the errand templates. I tried removing the plans from the list, I tried disabling the plans, I tried re-adding plans, etc.

Is there anything more specific that you can give us to help us recreate the issue? Could we get access to an environment in question that reproduces this issue? Also could you break down what the `on-demand-service-broker` is actually doing in terms of BOSH actions in the steps to reproduce above?

Best,

Jim

**Comment by jfmyers9** [comment]
I've successfully gotten a reproduction working on my local environment. Hopefully we will have some more definite information on the issue soon.

Best,

Jim

**Comment by jfmyers9** [comment]
Hi all,

This has been delivered in https://github.com/cloudfoundry/bosh/releases/tag/v270.3.0. Closing this issue.

Let us know if you have any other issues,

@jfmyers9, CF BOSH
