### ISSUE TITLE
Source release does not upload when only compiled release has been uploaded 

### ISSUE THREAD

**Issue by xtreme-jesse-malone** [cloudfoundry/bosh#2190]
**Describe the bug**

We encountered something a bit unexpected during a deploy yesterday. Our director had a compiled release of BPM already uploaded, but no source release. We then started a deploy that expected the source release (didn't specify a compiled release) of BPM, and also used a different stemcell than the previously uploaded BPM release was compiled against. BOSH did not upload the source release of BPM, showing `Release 'bpm/1.1.0' already exists.` The deploy subsequently failed with `Can't use release 'bpm/1.1.0'. It references packages without source code and are not compiled against stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/315.36`.  We're on director version 270.11.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on <IaaS> with <configuration options>
2. Upload <stemcell> and <cloud-config>
3. Deploy <manifest>
4. `bosh ssh` to a specific instance
5. Run <commands> on the vm to see the behavior

1. Upload a compiled release for a given release version (e.g. bpm-release-1.1.0-compiled) complied against a given stemcell major line (e.g. 250.x).
2. Deploy a manifest that specifies the following release block:
```
releases:
- name: bpm
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.0
  version: 1.1.0
  sha1: 82e83a5e8ebd6e07f6ca0765e94eb69e03324a19
```
and uses a different major stemcell line (e.g. 315.x).
3. See that the deploy *does not upload* the source release, and that the deploy fails because it could not compile the release for the desired stemcell.

Ex.
```
Can't use release 'bpm/1.1.0'. It references packages without source code and are not compiled against stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/315.36
```

**Expected behavior**
Given the scenario above, bosh should upload the source release..

**Logs**
Logs are always helpful! Add logs to help explain your problem.

```
Release 'cflinuxfs3/0.96.0' already exists.

Release 'bpm/1.1.0' already exists.

Release 'cf-syslog-drain/10.2' already exists.

Release 'cf-networking/2.22.0' already exists.

Release 'capi/1.82.0' already exists.

Release 'credhub/1.9.5' already exists.

Release 'diego/2.31.0' already exists.

Release 'loggregator/105.5' already exists.

Release 'nats/27' already exists.

Release 'routing/0.188.0' already exists.

Release 'loggregator-agent/3.9' already exists.

Release 'log-cache/2.2.2' already exists.

Release 'statsd-injector/1.10.0' already exists.

Release 'uaa/72.0' already exists.

Release 'silk/2.22.0' already exists.

Release 'bits-service/2.27.0' already exists.

Release 'syslog/11.4.0' already exists.

Release 'leadership-election/1.4' already exists.

  stemcells:
+ - alias: default
+   os: ubuntu-xenial
+   version: '315.36'
- - alias: default
-   os: ubuntu-xenial
-   version: '315.34'
  
  releases:
  - name: bpm
-   sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
+   sha1: 82e83a5e8ebd6e07f6ca0765e94eb69e03324a19
-   url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
+   url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.0
-   version: 1.0.4
+   version: 1.1.0
  - name: capi
-   sha1: 8116229c5789dc47cc6ff35d59c8a5c7e363c174
+   sha1: 6840b6a91f919ab4e5410f9d3f76dccdb9b0ad41
-   url: https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.81.0
+   url: https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.82.0
-   version: 1.81.0
+   version: 1.82.0
  - name: cflinuxfs3
-   sha1: df0d580973519cc899e757f1300d6975143872d8
+   sha1: f1aacde1b94293e8fdd128dd77f759254e094252
-   url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=0.93.0
+   url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=0.96.0
-   version: 0.93.0
+   version: 0.96.0
  - name: log-cache
-   sha1: 84b3cb04a61b240b338fd98de80c4fbd9acde080
+   sha1: 634dd3e134d0dac00f3f86beb00c06653579af4b
-   url: https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=2.2.1
+   url: https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=2.2.2
-   version: 2.2.1
+   version: 2.2.2
  - name: bits-service
-   sha1: f6a6598fbbac233f94c4a0cfe914970ec34db7b3
+   sha1: a3817a38a453db44bfed73183fb67addba8009da
-   url: https://bosh.io/d/github.com/cloudfoundry-incubator/bits-service-release?v=2.26.0
+   url: https://bosh.io/d/github.com/cloudfoundry-incubator/bits-service-release?v=2.27.0
-   version: 2.26.0
+   version: 2.27.0
  
- manifest_version: v9.2.0
  
+ manifest_version: v9.3.0
Task 4910593

Task 4910593 | 22:08:43 | Preparing deployment: Preparing deployment (00:02:38)
Task 4910593 | 22:11:22 | Preparing deployment: Rendering templates (00:03:51)
Task 4910593 | 22:15:15 | Error: 
Can't use release 'bpm/1.1.0'. It references packages without source code and are not compiled against stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/315.36':
 - 'bpm/5c2ff257e105bb48d670bfbdb83f39bb58765ae8'
 - 'bpm-runc/7e77f8d491425cfdbd45377f0d5d3ef0c0b766c2'
 - 'golang/408c40bbad364c359e0cdcf3959732f9b0df8469'
 - 'tini/3d7b02f3eeb480b9581bec4a0096dab9ebdfa4bc'


Task 4910593 Started  Tue Jun 18 22:08:43 UTC 2019
Task 4910593 Finished Tue Jun 18 22:15:15 UTC 2019
Task 4910593 Duration 00:06:32
Task 4910593 error
Could not deploy: Updating deployment: Expected task '4910593' to succeed but state is 'error'
```

**Versions (please complete the following information):**
 - Infrastructure: AWS
 - BOSH version: 270.1.1
 - BOSH CLI version: N/A (we do deploys using the [bosh-deployment concourse resource](https://github.com/cloudfoundry/bosh-deployment-resource), which consumes bosh-cli as a library, currently at revision f58b3a1827c1f4359397485d781c16f102e4b430)
 - Stemcell version: Several. Versions involved: 250.29, 315.36
 - Releases involved: bpm-release 1.1.0 

**Deployment info:**
We were deploying a variation of the cf-deployment manifest: https://github.com/cloudfoundry/cf-deployment/blob/0e09c6903465ef59926c7a44e4613dfd098e3a00/cf-deployment.yml

**Comment by jessedye** [comment]
I am also having the same issue right now with deploying concourse.

`Can't use release 'bpm/1.0.3'. It references packages without source code and are not compiled against stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/250.82`

**Comment by mrosecrance** [comment]
At the moment Bosh is name unique on the releases. Thus when a new stemcell line is added and teams create new compiled releases or teams want to move between source and compiled releases they see these errors. For now you can force the behavior you want by adding the `--fix` flag to your upload commands.

**Comment by jfmyers9** [comment]
In this case you actually don't need to use the `--fix` flag. A normal `upload-release` out of band with a path to the local source release tarball and it should successfully upload the source blobs.

It is difficult for us to detect whether or not downloading a remote release is necessary when specified in the `url:` field of the releases block. At the moment we naively just check the version of the release as an optimization. You would probably also see this issue with `bosh upload-release <remote-url>`.

At the moment, if you are constantly switching between source and compiled releases for the same version, I would recommend relying on the `upload-release` command rather than the upload behavior provided by the CLI in `bosh deploy`.
