### ISSUE TITLE
[Proposal] Links API Additions

### ISSUE THREAD

**Issue by tjvman** [cloudfoundry/bosh#2195]
## Abstract
The BOSH links API allows clients to fetch, create, and delete various
link-related resources. While its current behavior works well for the
single-deployment case, it has noticeable limitations when dealing with
multiple deployments; said limitations become more apparent when dealing with
cross-deployment links.

This proposal aims to extend the existing API to enable easier workflows and
tooling for introspecting links in multiple-deployment environments. For
example, as an operator it would be valuable to audit what links exist in a
deployment and what the downstream impact of changes to those links would be.

To the best of my knowledge, the proposed changes are backwards-compatible.

## Example of current workflow
A BOSH operator wishes to know where a shared link is being used in their deployments. They employ the following process:
1. Make a GET request to `/link_providers?deployment=provider_deployment`, where `provider_deployment` is the deployment containing the job that provides the shared link.
1. Filter out the target link provider.
1. For each deployment, make a GET request to `/links` and select any links that have a `link_provider_id` matching the target link provider's ID.
1. For each deployment, make a GET request to `/link_consumers`.
1. Select all link consumers with an ID that matches the `link_consumer_id` field of a link object returned in step 3.
1. Return desired metadata.

While there are small variations on the above workflow that may alter its
efficiency, the necessity of looping over all deployments and fetching down the
entire set of link resources for that deployment is unavoidable.

### Summary
*New endpoint:* `/link_providers/:id` Returns the link provider with the given ID
*New endpoint:* `/link_consumers/:id` Returns the link consumer with the given ID
*New query parameter:* `/links?provider_id={p-id}` Returns all links with `provider_id` equal to the parameter value
*New query parameter:* `/links?consumer_id={c-id}` Returns all links with `consumer_id` equal to the parameter value
*Modification to existing query parameter:* `deployment` is no longer required for `GET` requests to `/links`

#### Get link provider by ID
**Request**
`bosh curl /link_providers/1`

**Response**
```
{
	"owner_object": {
		"info": {
			"instance_group": "zookeeper"
		},
		"name": "zookeeper",
		"type": "job"
	},
	"link_provider_definition": {
		"name": "peers",
		"type": "zookeeper_peers"
	},
	"deployment": "zookeeper",
	"shared": false,
	"name": "peers",
	"id": "1"
}
```

**Permissions**
`bosh.read` scope.

#### Get link consumer by ID
**Request**
`bosh curl /link_consumers/2`

**Response**
```
{
	"owner_object": {
		"info": {
			"instance_group": "zookeeper"
		},
		"name": "zookeeper",
		"type": "job"
	},
	"link_consumer_definition": {
		"type": "zookeeper_peers",
		"name": "peers"
	},
	"deployment": "zookeeper",
	"optional": false,
	"name": "peers",
	"id": "2"
}
```

**Permissions**
`bosh.read` scope.

#### Get links with specific provider ID
**Request**
`bosh curl /links?provider_id=1`

**Response**
```
[
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "1",
		"link_consumer_id": "2",
		"name": "peers",
		"id": "1"
	},
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "1",
		"link_consumer_id": "3",
		"name": "other-peers",
		"id": "2"
	}
]
```

**Permissions**
`bosh.read` scope when the `deployment` query parameter is omitted.

#### Get links with specific consumer ID
**Request**
`bosh curl /links?consumer_id=2`

**Response**
```
[
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "1",
		"link_consumer_id": "2",
		"name": "peers",
		"id": "1"
	},
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "3",
		"link_consumer_id": "2",
		"name": "other-peers",
		"id": "2"
	}
]
```

**Permissions**
`bosh.read` scope when the `deployment` query parameter is omitted.

#### Get links for all deployments
**Request**
`bosh curl /links`

**Response**
```
[
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "1",
		"link_consumer_id": "2",
		"name": "peers",
		"deployment": "zookeeper", # This field is not currently part of the `/links` response. I have included for illustrative purposes, and it may be worthwhile to add it to the response for consistency with the other link endpoints.
		"id": "1"
	},
	{
		"created_at": "2018-09-16 18:00:36 UTC",
		"link_provider_id": "3",
		"link_consumer_id": "4",
		"name": "other-peers",
		"deployment": "zookeeper", # This field is not currently part of the `/links` response. I have included for illustrative purposes, and it may be worthwhile to add it to the response for consistency with the other link endpoints.
		"id": "2"
	}
	{
		"created_at": "2018-09-20 18:00:36 UTC",
		"link_provider_id": "3",
		"link_consumer_id": "5",
		"name": "peers",
		"deployment": "menagerie", # This field is not currently part of the `/links` response. I have included for illustrative purposes, and it may be worthwhile to add it to the response for consistency with the other link endpoints.
		"id": "3"
	}
]
```

**Permissions**
`bosh.read` scope when the `deployment` query parameter is omitted.

## Thoughts and Concerns
* Making the `deployment` query parameter optional for `GET /links` means that an
API consumer could fetch all of the links across all deployments. Since the
BOSH API does not support pagination, requesting all links could strain both
the BOSH Director and the API consumer, due to the potential size of the
response in large environments.

* An alternative to the proposed `/link_consumers/:id` and `/link_providers/:id`
would be to add an `ids` query parameter to each endpoint that accepts a
comma-separated list of ids as its value and returns all links with those ids.

* I did not suggest adding query parameters for other fields (e.g. `shared`,
`link_provider/consumer_definition.name`, `link_provider/consumer_definition.type`)
on the provider, consumer, and link objects (despite the fact that they could,
theoretically, be valuable) in order to keep the proposed changes as small as I
believed possible.

* For similar reasons to the previous point, I did not suggest allowing users
to provide multiple `provider_id` and `consumer_id` parameters.

* While some of the proposed endpoints could work with a less-extensive
permission than `bosh.read`, I felt it would be more straightforward from an
implementation standpoint.

**Comment by charleshansen** [comment]
Looked it over, seems good to me. I mildly prefer the main proposal over your alternate proposals.

Performance for very large deployments could be a thing, but I think we can address that later after some basic validation.

Not really sure what the scopes should be in this case, but `bosh.read` is alright in first pass. This might be a nice opportunity to standardize scopes in the links api and documentation.

Charles and @belinda-liu

**Comment by miguelverissimo** [comment]
For richer information of from where the links originate, it would be beneficial to have `deployments` as part of the `bosh curl /links?provider_id=1` and `bosh curl /links?consumer_id=1` responses. 
Apart from that this seems like a fair proposal.

Miguel and @mrosecrance

**Comment by miguelverissimo** [comment]
Closed by mistake :(

**Comment by tjvman** [comment]
@miguelverissimo I have some questions about adding `deployments` to the `/links?{provider,consumer}_id` response: 
1. Would the response include the provider deployments, consumer deployments, or both?
1. Would the deployments be sub-fields on the individual links objects, or would they be their own top level field(s)? 
1. Would the deployments be included for `/links` and `/links?deployment` as well? If not, how would the inconsistency in responses be addressed?

An example response body would also be useful.

**Comment by miguelverissimo** [comment]
@tjvman thank you for the comment.
I'm going to withdraw from the suggestion that `deployments` should be added to the response, as I believe your original proposal would solve the problem you describe, and there will be opportunity to further extend and enrich the response if the need arises.

Just for clarification/history what we're trying to achieve with the inclusion of `deployments` was to avoid a second call to actually get a human-readable deployment information. 

i.e.

`bosh curl /links?consumer_id=2`
```json
[
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "1",
		"link_consumer_id": "2",
		"provider_deployment": "zookeeper",
		"consumer_deployment": "zookeeper",
		"name": "peers",
		"id": "1"
	},
	{
		"created_at": "2018-08-14 18:00:36 UTC",
		"link_provider_id": "3",
		"link_consumer_id": "2",
		"provider_deployment": "menagerie",
		"consumer_deployment": "zookeeper",
		"name": "other-peers",
		"id": "2"
	}
]
```

This will require a bit more reasoning and customer validation for the actual need of this feature, so to reiterate, the original proposal is good enough to establish customer adhesion.
