### ISSUE TITLE
Unbalanced instance placement results when AZs are added subsequently 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh#2198]
**Describe the bug**
If you start with a count of `n` AZs and a count of `n+1` instances with persistent disks and decrease the instances to `n` you will end up with one instance in each AZ. A different instance placement result is produced, when one AZ and one instance are added subsequently.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Create a deployment with 3 instances with persistent disk and two AZs. The result will be: 
``` 
z1: 2
z2: 1
``` 
2. Add a third AZ and increase the instances to 4. The result will be:
``` 
z1: 2
z2: 1
z3: 1
``` 
3. Delete one instace. The result will be:
``` 
z1: 2
z2: 1
z3: 0
``` 

**Expected behavior**
The expected behavior after instance deletion is:
``` 
z1: 1
z2: 1
z3: 1
``` 
This work as expected if you start from the beginning with tree AZs.

**Versions (please complete the following information):**
 - Infrastructure: any
 - BOSH version: any with AZ support

**Additional context**
BOSH will select the instances to be deleted based on instance index, which doesn't consider the instance AZ. This happens in the [AvailabilityZonePicker#place_instances_that_have_persistent_disk_in_existing_az ](https://github.com/cloudfoundry/bosh/blob/d93de0cc2ec44c6fb306e9d4c39eb920cdfab950/src/bosh-director/lib/bosh/director/deployment_plan/placement_planner/availability_zone_picker.rb#L67). That is why you end up with a different result, when AZs and instances are added subsequently.

**Comment by mrosecrance** [comment]
I wonder how many users of Bosh are running into this and noticing. It's hard for me to reason about how negative an impact this has on end users unless they're scaling up and down frequently. While we could add balancing logic to deletion, it also seems expensive unless we have more validation that this should be fixed. I'm tempted to leave to leave this open for a while and see if more people chime in with their use-cases and frustrations with this pattern.

**Comment by friegger** [comment]
@mrosecrance This is a relevant use case if you have an instance group that requires at least 3 instances for an HA setup deployed and only 2 AZs of the IaaS provider have been used (for example if only 2 were available) and now the three instances should be distributed over 3 IaaS AZs.

Independent of the effort to change this. Is there historic reason, why it has been implemented this way? My understanding is, that the algorithm tries to leave as much persistent disks untouched as possible. Given a HA setup were the deployed software takes care of data replication this would not be necessary. But there might be other use cases where it would be helpful.
