### ISSUE TITLE
One time task with Bosh

### ISSUE THREAD

**Issue by ThilinaManamgoda** [cloudfoundry/bosh#2199]
Is it possible to have a job that does a one-time task and exit(spawn a VM, run the process and exit)?. I know there is a concept called "errands" where you can have a one time task. But is it possible to have a Bosh release which only has errands and no long-running job?.

**Comment by beyhan** [comment]
Hi @ThilinaManamgoda,

yes it is possible. See the documentation about errands https://bosh.io/docs/errands/. Please use `bosh` channel in https://slack.cloudfoundry.org next time for questions.

**Comment by ThilinaManamgoda** [comment]
@beyhan Thanks. I'll use Slack for further questions.
