### ISSUE TITLE
Bosh vm --vitals reports persistent disk usage in absence of persistent disk

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh#2204]
**Describe the bug**

On instance groups without an attached persistent disk, bosh reports persistent disk usage (which exactly equals the system disk usage). This creates confusions for bosh operators using  `bosh vms --vitals` interactively as well as other systems consumming this metrics such as the https://github.com/bosh-prometheus/bosh_exporter#metrics whose derived metric `metrics.namespace_job_persistent_disk_percent` gets invalid content.

```
$ bosh vms --vitals
Using environment '192.168.10.10' as user 'xx' (bosh.read, openid, bosh.admin)

Task 3173140. Done

Deployment 'dns-recursor'

Instance                                           Process State  AZ  IPs              VM CID                                VM Type  Active  VM Created At                 Uptime         Load              CPU    CPU    CPU   CPU   Memory        Swap      System      Ephemeral   Persistent  
                                                                                                                                                                                           (1m, 5m, 15m)     Total  User   Sys   Wait  Usage         Usage     Disk Usage  Disk Usage  Disk Usage  
dns-recursor/1b2c5038-6d56-432f-8172-657cefbbda17  running        z1  192.168.116.156  0788140c-4105-49c7-975f-dab32d08edf8  default  true    Tue Sep  3 16:42:25 UTC 2019  9d 2h 20m 56s  0.94, 0.58, 0.44  -      25.8%  3.5%  0.1%  27% (1.1 GB)  0% (0 B)  52% (35i%)  1% (0i%)    52% (35i%)  
dns-recursor/777ca488-05aa-493c-9fe7-6dcac11d22bc  running        z2  192.168.116.166  cc328ab4-f3a0-4157-bbc5-2243e4fc64c2  default  true    Tue Sep  3 16:45:22 UTC 2019  9d 2h 18m 0s   0.12, 0.25, 0.36  -      25.9%  3.3%  0.0%  26% (1.1 GB)  0% (0 B)  52% (35i%)  1% (0i%)    52% (35i%)  

2 vms

Succeeded
```

**To Reproduce**

Steps to reproduce the behavior (example):
1. Deploy a bosh deployment without a persistent disk attached
2. Run "bosh vms --vitals"

**Expected behavior**

The persistent disk usage column should display "-" (dash) or "N/A" (non applicable) to accurately indicate there is no associated disk size.

**Versions (please complete the following information):**
 - Infrastructure: openstack
 - BOSH version 266.4.0
 - BOSH CLI version version 5.5.1-7850ac98-2019-05-21T22:28:36Z
 - Stemcell version bosh-openstack-kvm-ubuntu-xenial-go_agent/315.83

**Comment by jfmyers9** [comment]
Hi @gberche-orange,

I think I understand this issue. Can you confirm one thing about your current deployment? Is the `/var/vcap/store` directory present on that VM?

This appears to be an issue with how the agent reports vitals. It does not check that the directory is actually a mount point, so if the `/var/vcap/store` directory exists, but a disk is not mounted there, it will report the usage for the system disk.

I noticed this due to the fact that if you deploy a brand new instance with no persistent disk, the usage is reported correctly. If you add the persistent disk the usage is still reported correctly, but if you eventually remove the persistent disk, this issue appears.

Let me know,

@jfmyers9

**Comment by gberche-orange** [comment]
Thanks @jfmyers9 for looking into this. 

> Is the /var/vcap/store directory present on that VM?

Yes, the directory is present and does not corresponds to a volume mount

```bash
$ ls -al /var/vcap/store/
total 12
drwxr-xr-x  3 root root 4096 Sep 12 19:42 .
drwxr-xr-x 11 root root 4096 Sep 16 16:18 ..
drwxr-xr-x  2 root root 4096 Sep 12 19:42 node_exporter

$ mount | grep store
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
```

Also, no previous persistent disk was mounted in the deployment previously.

Instead, it is created by a bosh job, node exporter in our case:

https://github.com/bosh-prometheus/node-exporter-boshrelease/blob/92b1874440ed77590206485bc56970e7dba372ed/jobs/node_exporter/templates/bin/node_exporter_ctl#L5-L9

I finally found the related long-time issue in https://github.com/cloudfoundry/bosh-agent/issues/36 which reported the same issue (in that case the `consul_agent` job was creating the directory).

The issue suggests the following:

> We [i.e. the agent] should probably check if /var/vcap/store is a mountpoint.

**Comment by jfmyers9** [comment]
Sounds good. Seems like its a pretty clear issue. I've reached out to the BOSH Systems team to get their thoughts. I'll keep you updated.
