### ISSUE TITLE
BOSH only delivers one CA certificate even if credhub returns 2

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh#2207]
**Describe the bug**
Recently Credhub introduced a change to make it easier to rotate certificates where you will receive both the CA certificate and the transitional CA certificate when requesting certificate.ca. Unfortunately BOSH seems to ignore the second certificate and only fills out templates with one certificate. 

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director  with credhub.certificates.concatenate_cas set to true (tested on vsphere and bosh-lite)
2. Deploy any manifest containing a certificate using any cloud config and latest stemcell
3. Create a transitional version of the CA certificate and validate with credhub get on the leaf certificate that 2 CA certificates are returned and deploy again.
4. `bosh ssh` to one of the instances
5. Run check the ca.cert file of the specific job to see if one or both CA certificates are on the machine 

**Expected behavior**
The ca.cert file contains 2 ca certs, analog to what happens if I use ((old_ca.certificate))((new_ca.certificate))

**Versions (please complete the following information):**
 - Infrastructure: bosh lite, vsphere
 - BOSH version  269.0.1 and v270.5.0
 - BOSH CLI version 5.4.0-891ff634-2018-11-14T00:21:14Z
 - Stemcell version ubuntu-xenial/315.45 and ubuntu-xenial/456.12
 - https://github.com/cloudfoundry/bosh-deployment/commit/fca68da6d2b42fa2ef713a8549fe22789871d1de

**Deployment info:**
Deployed via the command in this guide with a change to the ops file to set concatenate_cas to true (I checked that this property was set correctly)
https://bosh.io/docs/bosh-lite/

**Additional context**
I talked to Jeremy on the Contributor summit and he said he also encountered this bug

**Comment by jfmyers9** [comment]
Hi @schmidtsv,

I noticed that a [recent release of Credhub](https://github.com/pivotal-cf/credhub-release/releases/tag/2.5.6) describes a bug that sounds very similar to the behavior that you are describing. Is there any chance you could try this again with the most recent version of bosh-deployment to confirm if this is still an issue?

Best,

@jfmyers9

**Comment by schmidtsv** [comment]
Yep that fixed it. Thanks for pointing me to it.
