### ISSUE TITLE
Bosh update-config doesn't upload releases

### ISSUE THREAD

**Issue by mymasse** [cloudfoundry/bosh#2209]
**Describe the bug**
Running `bosh upload-config ... --type-runtime --name=...` doesn't upload releases specified in the configuration. However running the equivalend `bosh upload-runtime-config` does.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Using bosh-deployment provided runtimes config
2. Run `bosh upload-config runtime-configs/dns.yml --type-runtime --name=dns`

**Expected behavior**
The bosh-dns release would get uploaded to the director

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
 - Infrastructure: vSphere
 - BOSH version: 270.1.1
 - BOSH CLI version: 5.5.1
 - Director Stemcell version: 315.36
 - Bosh deployment repo commit: fb6b83c

**Comment by BeckerMax** [comment]
Hi,

it is surprising that both commands end up in different results for you.

Just a quick check before we investigate further: The command `upload-config` does not exist in the current cli version. I suppose you meant `update-config`? 
Can you print the output of `bosh configs` after each command? I would like to know whether the config was uploaded successfully with both commands before deploying.

I tried the following commands and both uploaded a config successfully:
`bosh update-config --type=runtime --name=dns ./dns.yml`
`bosh update-runtime-config ./dns.yml`

Best regards,
Max

**Comment by mymasse** [comment]
Oups I did mean update-config. Configd update fine in both cases the issue is that update-config doesn't upload releases defined in the config while update-runtime-config does. The config I was trying to update was the dns.yml one from bosh deployment but using update-configthe DNS release doesn't get uploaded to the director

**Comment by friegger** [comment]
As far as I remember the following things had been decided in the past:
- the generic `update-config` command should not contain any config type specific special handling (i.e. that is not uploading releases in the case of `update-runtime-config`), but only generically update the config itself
- if there is a config type specific command it shall be used instead of the generic command, i.e. as `update-runtime-config` exists it should be used instead of `update-config --type runtime`.

This is confusing and also not documented. Also there are still things not consistent, e.g. `update-cloud-config` currently does not support the `--name` flag, thus one has to rely on the generic command for this case. @mfine30 What is your take on this?

**Comment by mymasse** [comment]
That explains it and yes this is confusing. My reason for using `update-config` was that `update-runtime-config` doesn't have the `--name` field.  Also if you look at the bosh-deployment/runtime-configs it provides 3 using the `update-runtime-config` cannot support pushing all 3.  Adding support for `--name` would be ideal.

**Comment by friegger** [comment]
Actually `update-runtime-config` does take `--name` in contrast to `update-cloud-config`. Unfortunately this is only revealed by `bosh update-runtime-config --help` and not mentioned at https://bosh.io/docs/cli-v2/#update-runtime-config.

**Comment by mymasse** [comment]
Good to know.  My overall understanding also was that when `update-configs` came out it would replace the other ones completely. So I guess `update-cloud-config` and `update-runtime-config` will keep on living. If this is the case then feel free to close this issue.

**Comment by mfine30** [comment]
@friegger I'm relatively in agreement with your thoughts above. 

* `update-config` is intended to be the generic case where you can specify both `name` and `type` of the config. It is not intended to be as featured for specific use cases as the specific commands like `update-runtime-config`. 
* We do not have any plans to remove either command. `update-configs` can be used to create random config types `bosh update-config --type magic --name dummy-config ...`. 
* The other type specific commands are niceties that define a specific type of config BOSH already knows about and assumes a `name` of `default` and have some benefits baked in such as explicit uploading of releases. 

Sounds like this can be closed, but feel free to re-open or follow along on the other issue @friegger just opened https://github.com/cloudfoundry/bosh-cli/issues/542

I
