### ISSUE TITLE
BOSH DNS filters do not return the documented values

### ISSUE THREAD

**Issue by mariash** [cloudfoundry/bosh#2210]
**Describe the bug**
During stemcell upgrade we noticed that Cloud Controller is failing to talk to one of the doppler instances. We have 4 doppler instances. One of the instances was being updated and Cloud Controller was trying to talk to that IP address. We confirmed that issue by running `dig doppler.service.cf.internal` and it was returning all 4 IPs, even for VMs that were being updated. After bringing the issue with the Bosh team we were suggested to update the doppler host URL to include the healthiness filter. 

But it seems like they don't work. With 4 instances of doppler running `q-s0.doppler.default.cf.bosh` returns 4 instances. But both `dig q-s1.doppler.service.cf.internal` and `dig q-s3.doppler.service.cf.internal` return 0 instances. Documentation states that the `q-s1` should return unhealthy and `q-s3` healthy instances. 

We ran `bosh recreate doppler/<some-guid>` and watched the above commands. The output has not changed.

Cloud controller is configured with doppler service URL as `doppler.service.cf.internal` and we use cf-deployment https://github.com/cloudfoundry/cf-deployment/blob/5f5b327ad6d1e9a4d72f1bc9eeea7e7cd20f51d8/cf-deployment.yml#L172-L178

Slack conversation with bosh team: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1569524830094900

**To Reproduce**
1. Deploy a bosh director on GCP with bbl
2. Deploy cf-deployment https://github.com/cloudfoundry/cf-deployment/blob/7dfd55990ded725ea30127307f373b11e0628c83/cf-deployment.yml and ops-file https://github.com/cloudfoundry/cf-deployment/blob/7dfd55990ded725ea30127307f373b11e0628c83/operations/test/add-datadog-firehose-nozzle.yml
3. `bosh ssh` to a `api/0`
4. Run:
`watch "dig q-s0.doppler.service.cf.internal"`
`watch "dig q-s1.doppler.service.cf.internal"`
`watch "dig q-s3.doppler.service.cf.internal"`
5. Run `bosh recreate doppler/0`

**Expected behavior**
at some point:
`dig q-s0.doppler.service.cf.internal` - should return 3 instances instead of 4
`dig q-s1.doppler.service.cf.internal` - should return 1 instance instead of 0
`dig q-s3.doppler.service.cf.internal` - should return 3 instances instead of 0

**Versions (please complete the following information):**
 - Infrastructure: GCP
 - BOSH version: 270.5.0 (00000000)
 - Stemcell version [e.g. ubuntu-xenial/97.10]
 - cf-deployment version: 7dfd55990ded725ea30127307f373b11e0628c83 

**Deployment info:**
Deployment was deployed with concourse: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/master/bosh-deploy/task.yml
Task config: https://gist.github.com/mariash/612714710a82131b855aeda3b115c3f9

**Comment by h4xnoodle** [comment]
Hi @mariash,

After reading the slack thread, it seems like it could have been certificates causing the problems? Did you see this behaviour still after updating the certs?

> [webdave] We found the culprit. We have a REGENERATE_CREDENTIALS flag in the `bosh-deploy task in cf-de-co-ta that deletes all credentials from credhub before the deploy runs so that you can reuse a bbl env for repetative clean installs.

Was this the ultimate cause?

Thanks,
Rebecca, BOSH

**Comment by aminjam** [comment]
Yes, expired certificates was the ultimate cause of the issue

**Comment by h4xnoodle** [comment]
Okay, thank you for following up. I will close this issue now, as the main issue was certificates and not the DNS filters.

**Comment by mariash** [comment]
@h4xnoodle yes we had an issue with certificates. After we regenerated certificates though we still seeing an issue with cloud controller connecting to the doppler instance that is being stopped and recreated. In bosh-dns logs we see:
```
[healthWatcher] 2019/10/28 18:34:53 DEBUG - State for IP <10.0.1.21> changed from running to unknown
```
Shouldn't bosh remove updating VM from the filter when it is stopped? Basically this results in pushing of applications failing during upgrade even though there are HA instances for all the components.

**Comment by h4xnoodle** [comment]
That makes sense, and I agree that if bosh-dns knows the state changed, there should be no reason to keep returning that IP given your query. 

The current working theory is that there is a cache that should be purged of entries that could produce this unhealthy instance's IP. 

@jaresty also shows that if the check takes a while to perform, the old status is returned until a new status is obtained https://github.com/cloudfoundry/bosh-dns-release/pull/51/files. 

We have the following investigation story https://www.pivotaltracker.com/story/show/169438565 and will likely produce more stories to fix the issue.

**Comment by mariash** [comment]
Just to update, we are seeing the same issue in our uptimer tests, now Cloud Controller fails to talk to the Database while it is being updated. We have 3 instances of database and we use manifest provided by cf-deployment https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L235-L241.

**Comment by xtreme-conor-nosal** [comment]
What is the timing of the DNS lookup vs the VM becoming unhealthy? Because health is polling based, the status of the dopplers will be up to 25 seconds stale (`remote_health_interval`=20s and `local_health_interval`=5s by default). After bosh-dns sees a failing/unknown health update, then lookups should reflect the new state.
