### ISSUE TITLE
bosh clean-up failure when stemcell not found

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry/bosh#2212]
**Describe the bug**
When we delete a VM, if the VM doesn't exist, BOSH just removes the VM reference.
When we delete a disk, if the disk doesn't exist, BOSH just removes the reference to it.
When we clean up, and the stemcell is already deleted from Openstack, we get an error and can never clean this up.

Shouldn't we just ignore the fact that the cleanup activity is already done?

**To Reproduce**
Upload a stemcell.
Delete from Openstack.
Run bosh clean-up

```
Running Bosh clean-up. If there are issues, this will not stop the backup process...

Using environment '10.136.208.79' as client 'admin'


Task 1003000


Task 1003000 | 07:05:02 | Deleting stemcells: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw/3468.22 (00:00:03)

                      L Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict. Check task debug log for details.' in 'delete_stemcell' CPI method (CPI request ID: 'cpi-560014')

Task 1003000 | 07:05:05 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API Conflict. Check task debug log for details.' in 'delete_stemcell' CPI method (CPI request ID: 'cpi-560014')


Task 1003000 Started  Wed Oct  2 07:05:02 UTC 2019

Task 1003000 Finished Wed Oct  2 07:05:05 UTC 2019

Task 1003000 Duration 00:00:03

Task 1003000 error



```

**Expected behavior**
Remove reference as stemcell is already missing

**Versions (please complete the following information):**
 - Infrastructure: Openstack
 - BOSH version 268.2.1
 - BOSH CLI version version 3.0.1-712bfd7-2018-03-13T23:26:43Z

**Comment by xtreme-conor-nosal** [comment]
Looking at https://github.com/cloudfoundry/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/stemcell.rb#L38 the openstack CPI should be skipping the missing image. 

The "OpenStack API Conflict" error might be unrelated. Do you have the debug log it references?

**Comment by keithkroeger** [comment]
Hello,

Thank you for your guidance.

We'll need to follow-up locally

Error was:
  :body          => "{\"message\": \"Image 23c861eb-e736-454e-89f0-72660a00a148 could not be deleted because it is in use: The image cannot be deleted because it is in use through the backend store outside of Glance.<br /><br />\\n\\n\\n\", \"code\": \"409 Conflict\", \"title\": \"Conflict\"}"
