### ISSUE TITLE
Releases endpoint returns releases before upload is completely done

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#2214]
**Describe the bug**
When a bosh release gets uploaded it does appear in the existing releases before the last upload steps are executed and the task is finished. Subsequent deploys assume that the release exists even if the upload is not yet finalized and fail with ` job is not found in the template table`. 
The timeframe in which this can happen increases with the size of the bosh release and may only be problematic with releases of a certain size.

**To Reproduce**
1. Create a huge bosh release > 5 GB
2. Create two manifests, which download and use the bosh release
3. Run the following script

```
bosh deploy <first_manifest>.yml -n
while true; do
  release="$(bosh curl /releases | jq -r '.[] | select(.name == "<release_name>") | .release_versions[] | select(.version == "release_version")')"
  if [[ -n "$release" ]]; then
    break
  fi
  echo "release upload pending"
  sleep 1
done
bosh deploy <second_manifest>.yml -n
```

**Expected behavior**
A release is only returned by the `releases` endpoint after the upload has completely finished and the release is ready to use.

**Versions (please complete the following information):**
 - Infrastructure: does not matter
 - BOSH version 270.x.x
 - BOSH CLI version 6.x
 - Stemcell version xenial 456.x

**Comment by beyhan** [comment]
Hi @mfine30 
this happens regularly with large releases and automated deploys that run in parallel. 

We looked a bit into the code and saw that the releases endpoint
https://github.com/cloudfoundry/bosh/blob/9fd99560a102910d467437aea4f7eec6f8624e5d/src/bosh-director/lib/bosh/director/api/controllers/releases_controller.rb#L35-L39 does not respect the field `update_completed`:
https://github.com/cloudfoundry/bosh/blob/bfc03787a81da98c6fce9086935bf342b142bff8/src/bosh-director/lib/bosh/director/jobs/update_release.rb#L167
We could filter releases out which are `update_completed==false`

Thanks,
@beyhan @BeckerMax

**Comment by xtreme-conor-nosal** [comment]
If many deployments are being done in parallel with common releases, I would recommend manually uploading the releases before starting the deployments. 

Filtering on `update_completed` would shift the problem - the second deploy would think the release isn't being uploaded, and could timeout on the release lock.

**Comment by beyhan** [comment]
The workflow is as follow:
1.  A new release version gets uploaded automatically before starting any deployments.
2. Deployments start in parallel and ask the `releases` endpoint about available releases. 
3. The `releases` endpoint states too early, that there is a new release version available before the last upload steps are executed and the upload task is finished. 
4. In parallel started deployments assume that the new release version exists and start a deploy, which fails with `job is not found in the template table`

The `releases` endpoint should return a release, only when it is ready for consumption. The current behaviour of the `releases` endpoint breaks automations, which is not typical for BOSH. Our proposal with the `update_comleted` looked reasonable for us, but we can also discuss other options.

**Comment by xtreme-conor-nosal** [comment]
Can you prevent 1 and 2 happening in parallel? I'm also wondering why the release lock wouldn't be preventing this.

**Comment by steinri** [comment]
One could obviously implement a different lock logic in the automation on top of bosh to prevent the occurrence of this bug. However this is just a workaround and not really a solution for the problem.

I don't see how this would increase the releases-lock problems, because the duration of the release lock is not changed at all. In this case it just increases the probability for a different deployment to start the release upload *while the files are copied at the very end*.
A second release upload may currently also be triggered during the whole upload process. And if it is triggered, when the first upload is at the very end, it is unlikely (nearly impossible) that the first upload still holds the lock, when the second upload reaches the `process_release` method .

**Comment by xtreme-conor-nosal** [comment]
Can you expand on what you're seeing regarding "there is a new release version available before the last upload steps are executed" and "start the release upload while the files are copied"? Looking at https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/jobs/update_release.rb#L54 it looks like (aside from initial upload and validation) updating a release is protected by a lock, which the deployments _should_ be blocking on https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/deployment_plan/assembler.rb#L120

**Comment by steinri** [comment]
The basic relevant workflow in the cli is as I understand it
1. check whether the release is available it the `/releases` route
2. if it is not available, upload it
3. deploy at bosh

So with "there is a new release version available" we mean, that the `/releases` endpoint returns the release and the bosh cli assumes that it is available and hence does not trigger a second upload.
However 3. fails, because of `job is not found in the template table`. My assumption is that the reason is, that not all files are copied to the correct location. If I understand you correct it should fail with an `Could not require lock for release` error?

**Comment by xtreme-conor-nosal** [comment]
Depending on how long the release takes to process, I would expect the current behaviour to either:
1) uploading release finishes, releases the lock, second deployment acquires the release lock, deployment succeeds
or
2) second deployment to timeout while the release is processing and fail with `Could not acquire lock for release`

If that's not the case, we need to look closer at the lock handling, which I believe is supposed to prevent the failure you're seeing.

**Comment by steinri** [comment]
That was not the case at least when I executed the script the last time. The script written above failed with the error `job is not found in the template table` and I was able to see that the failure of the `deploy` job was approx. one minute before the success of the `upload-release` job.
Retrying the deploy afterwards did succeed (it is not a problem in the manifest or the release).

How long bosh tries to aquire a lock?

**Comment by xtreme-conor-nosal** [comment]
Release lock timeout was bumped from 10 seconds to 5 minutes in 270.8 https://github.com/cloudfoundry/bosh/commit/9fd99560a102910d467437aea4f7eec6f8624e5d#diff-46e631a61c0c829a9d6e84e3869a0946

In the test script I'm assuming the first deploy is meant to be run in the background?

**Comment by steinri** [comment]
yes

**Comment by xtreme-conor-nosal** [comment]
I'm not able to reproduce with a padded zookeeper. In my run, the new version of the release did show up in the `/releases` response when the `create release` job started creating packages:
```
release upload pending
 (00:00:04)
Task 59 | 16:21:08 | Verifying manifest: Verifying manifest (00:00:00)
Task 59 | 16:21:08 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 59 | 16:21:08 | Creating new packages: golang-1.10-linux/48c842421b6f05acf88dc6ec17f7574dade28a86
release uploaded
 (00:00:02)
```
which occurs while the "create release" job is holding the release lock. 

Once the release is finished, the first deployment task starts:
```
Task 59 | 16:21:21 | Release has been created: zookeeper/0.0.13+dev.13 (00:00:00)
Task 60 | 16:21:23 | Preparing deployment: Preparing deployment (00:00:02)
```
And when the second deployment acquires the release lock it sees the release is ready:
```
Task 61 | 16:21:54 | Extracting release: Extracting release (00:00:05)
Task 61 | 16:21:59 | Verifying manifest: Verifying manifest (00:00:00)
Task 61 | 16:21:59 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 61 | 16:21:59 | Processing 6 existing packages: Processing 6 existing packages (00:00:00)
Task 61 | 16:21:59 | Processing 3 existing jobs: Processing 3 existing jobs (00:00:00)
Task 61 | 16:21:59 | Release has been created: zookeeper/0.0.13+dev.13 (00:00:00)
```

**Comment by xtreme-conor-nosal** [comment]
Can you provide your output for the test script? Github search is letting me down looking for where `job is not found in the template table` would be raised.
