### ISSUE TITLE
BOSH strategy on distributing instances to multiple AZs causes outage

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh#2215]
We have a cluster with 2 instances (VM1 and VM2) in AZ1 and need to distribute to 2 AZs (AZ1 and AZ2 together with some updates), each AZ has an instance to make better HA. The current BOSH update strategy on this task is:
1. Delete unneeded VM2 in AZ1
2. Create a new VM3 (with no jobs installed) in AZ2
(The above two steps may be in different order which has the same result - now we have only one working instance VM1)
3. Update VM1 in AZ1 - During the update, there is no working instances and the outage happens!!!
4. Update VM3 in AZ2

Is it possible for BOSH to make better strategy, for example, put the `delete unneeded instance` at the end of the task? So that we always has a working instance to avoid outage.

**Comment by mrosecrance** [comment]
We run deletes intentionally before any creates to avoid hitting quota restrictions. Bosh should not be doing any updates to existing vms unless properties or releases are changing. Does your clustered solution require that the instances know about each other?

Another option is to scale up to 3 instances, leave the two in AZ 1 and add one to AZ2 (in a separate instance group) before removing the extra instance from the AZ1 instance group on a second deploy.
