### ISSUE TITLE
More easier and downtime less way for CA Rotation.

### ISSUE THREAD

**Issue by kkitai** [cloudfoundry/bosh#2216]
I had experienced CA Rotation work at few days ago. I have seven deployments so It had takes 4 hours for this work.. And my some deployments connect to each other. In this case, Each deployment down time will be larger than it looks.

To make this work be easier and downtime less, I need other way to rotate ca except "recreate deployments".

**Comment by mrosecrance** [comment]
You could manually update the ca's on the machines themselves and in credhub. This is unsupported but would allow you to avoid deploys. However if vm's were resurrected they would use the old CAs.

For a supported solution, in regards to the multi deployment issue, you could use 3 stage cert rotations similar to the documented flow https://bosh.io/docs/nats-ca-rotation/ which could decouple the need to roll all your deployments at once. 

Have you also experimented with `max_in_flight` or `create_swap_delete` to speed up deploy times?

**Comment by kkitai** [comment]
@mrosecrance 
yes. I used `max_in_ fligh` at that time. However my deployments has about 50 over vms, so entire time became so long at all.
If it can do without `recreate`, I think that the ca rotation in bosh is no longer hard work to everyone.

**Comment by mrosecrance** [comment]
Configuration changes like switching ca's should not require a full vm recreate unless you're making other changes but the deploy will stop all the jobs on the vm and then start them again. This is because bosh doesn't know what the jobs do and how they might be using CA's, so to be safe, any changes to job configuration results in a restart.

It's not a workflow we're currently planning on changing at the moment.

**Comment by kkitai** [comment]
@mrosecrance Hmm, I understood the situation. I'm wondering if somehow i change [settings.json](https://bosh.io/docs/agent-cpi-interactions/#settings-json), nats rotation would be done without `recreate`...

**Comment by h4xnoodle** [comment]
It's recommended to not change anything in `settings.json`. You then risk breaking your deployed vm and entering into `unresponsive agent` state, if the agent can no longer communicate. There is more to just changing a file in the system as well.

We understand it takes a long time to recreate VMs. This is the only secure way to transfer the new certs over right now. We're actively thinking about a way to make this faster by using the existing NATS connection to transfer new certs. This has security complications. 

We agree it _should_ be faster. At the moment, however, there isn't any harm in it being so slow. You could also time a stemcell update with your rotation, so you would be recreating all your VMs anyways. The act of recreating VMs shouldn't cause unnecessary downtime if your software is quorum/scaling-friendly. 

Closing as this is a common and known issue, that we're already thinking about. Thank you for your feedback.
