### ISSUE TITLE
Add zone awareness to deployments

### ISSUE THREAD

**Issue by antoniocascais** [cloudfoundry/bosh#2221]
**Is your feature request related to a problem? Please describe.**
We have an Elasticsearch cluster being deployed with Bosh and that deployment has a lot of VMs. In order to avoid data loss, we can only deploy 1 VM at a time (because if 2 *random* VMs are down at the same time, we might lose the primary and replica shards at the same time, causing data loss). 
When we're performing some operations, it can take 5/6 minutes per VM... Which will add up to a few hours in total.

**Describe the solution you'd like**
We would like to be able to deploy our ES cluster per zone. ES has settings that introduce zone awareness, so we don't lose data if an entire zone is down.
If we could tell bosh to deploy the VMs per availability zone, then our deployment would be much, much faster.

**Describe alternatives you've considered**
It would also help if bosh would never take down 2 VMs of the same AZ at the same time. Then we could set the `max_in_flight` property to 2 and don't worry about data loss.

**Additional context**
Nothing to add.

Is this a reasonable feature to ask? We searched and we didn't find a way to do this...

**Comment by xtreme-conor-nosal** [comment]
`max_in_flight` is per-AZ. Bosh will update VMs one AZ at a time.

Let me know if I've misunderstood you, but what you describe is already bosh's behaviour.

For example, if `num_canaries`=1, `max_in_flight`=3, and your instance group has 9 VMs across three AZs (a,b,c) then a deployment will:
- update canary instance in zone a
- update the other 2 VMs in zone a in parallel
- update the three VMs in zone b in parallel
- update the three VMs in zone c in parallel

**Comment by antoniocascais** [comment]
Hi @xtreme-conor-nosal !

First of all, thanks for the answer. I always thought it was random :see_no_evil: 

So, in your example, Deployment of VMs in zone B will only start after the deployment of all VMs in zone A is finished? So bosh won't update 1 VM from zone A in parallel with 1 VM from zone B?

**Comment by xtreme-conor-nosal** [comment]
Correct. This should be apparent in the timestamps of the task log as well.

**Comment by antoniocascais** [comment]
Thank you very much!

Then this issue is already solved. I'll close it :)
