### ISSUE TITLE
The disk migration is too slow

### ISSUE THREAD

**Issue by David-Pivotal** [cloudfoundry/bosh#2222]
I'm always frustrated when extending the persistent disk for bosh director. It takes long time to copy the data from the old disk to the new disk. 

This put the foundation in partial unavailable state. For example, I cannot create on-demand service instances when bosh director is not available.

I would like to disk migration time, the shorter the better. 

For example, shall we consider improving the performance by using rsync instead? For example, ```rsync -avz --delete source/ target/ ```

Currently, it uses tar and pipelines to migrate data.
```
/:~$ ps axu | grep tar
root    xxxx 0.0 0.0  xxxx  xxx ?    S<  xx:xx  x:xx sh -c (tar -C /var/vcap/store -cf - .) | (tar -C /var/vcap/store_migration_target -xpf -)
root    xxxx 7.3 0.0 xxxxx xxxx ?    D<  xx:xx  x:xx tar -C /var/vcap/store -cf - .
root    xxxx 7.5 0.0 xxxxx xxxx ?    S<  xx:xx  x:xx tar -C /var/vcap/store_migration_target -xpf -

**Comment by voelzmo** [comment]
Hey @David-Pivotal,

Thanks for the issue!
This is topic which has come up a few times before, so I'm going to leave these two links here and close this issue as duplicate.

https://github.com/cloudfoundry/bosh/issues/2021
https://github.com/cloudfoundry/bosh/issues/1569
