### ISSUE TITLE
Provide indication to a job that is going to be removed from the current VM over pre-stop

### ISSUE THREAD

**Issue by mmanciop** [cloudfoundry/bosh#2224]
**Is your feature request related to a problem? Please describe.**

We ship our functionality (APM monitoring) almost exclusively over BOSH `runtime-configurations`. Currently it is pretty hard for us to know if our jobs are going to be purged from a machine due to the removal of the runtime configuration and the update of the deployment. (We need to look up the deployment manifest.)

**Describe the solution you'd like**

Get a clear indication of "This job won't be here again after being stopped", which is pretty much the semantics I would expect from a `BOSH_JOB_NEXT_STATE = delete` env var in [pre-stop](https://bosh.io/docs/pre-stop/).

**Describe alternatives you've considered**

Over the current `pre-stop`, we look up the runtime configurations listed in the BOSH director over the REST API and, if the one that deploys the current job is no longer listed, we do long-term clean-up. Unfortunately, it requires I/O to the BOSH Rest API and a `bosh.read` token accessible from the VM we'd rather not have there :-)

**Additional context**

N/A

**Comment by xtreme-conor-nosal** [comment]
Can you expand on the "long term cleanup" you would do in response to a hypothetical `BOSH_JOB_NEXT_STATE`?

Keep in mind that the operator can deploy with --skip-drain or forcibly delete the VM when the bosh agent is unresponsive.

**Comment by mmanciop** [comment]
For example, we would delete local MySQL accounts that are added by a post-start job in order for a monitoring agent to collect telemetry.
