### ISSUE TITLE
Unnecessary gzip while deployment of release

### ISSUE THREAD

**Issue by KernelDev** [cloudfoundry/bosh#2225]
**Describe the bug**
When deploying a boshrelease, which is gziped already, the release gets gzip by nginx.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on any IaaS 
2. Upload ubuntu stemcell and use any cloud-config
3. Deploy a big boshrelease > 4gb
4. `bosh ssh` to the director and observe the cpu usage and the gzipping
5. Run top/htop/ps -efH on the vm to see the behavior

**Expected behavior**
Do not zip a zipped file before transfer to the deployment´s vm

**Versions (please complete the following information):**
 - Infrastructure: any
 - BOSH version: any
 - BOSH CLI version: any
 - Stemcell version: ubuntu-xenial

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

**Additional context**

The issue happens, because you did not define the necessary mime type mapping for gzip files. Nginx uses the default mapping, which is text/html in your config. Text/HTML is thought of as compressible, since [this config](https://github.com/cloudfoundry/bosh/blob/master/jobs/director/templates/nginx.conf.erb#L150). 

Files to adjust:
https://github.com/cloudfoundry/bosh/blob/master/jobs/blobstore/templates/mime.types
https://github.com/cloudfoundry/bosh/blob/master/jobs/director/templates/mime.types

the type that must be added is: 
application/gzip for .tgz

**Comment by friegger** [comment]
Thanks for creating such a detailed report that also provides the missing mapping.
@jfmyers9 Adding the mapping should reduce the CPU load on the local blobstore significantly.

**Comment by KernelDev** [comment]
Please take the recommended mapping with a grain of salt and test it thoroughly. When it comes to gzip there is a lot of misleading information out there

**Comment by jfmyers9** [comment]
Pushed a fix for this. Let me know if you have any other questions. For the time being I did not touch the director's nginx server as it does not serve large assets similar to the blobstore. Thank you for pointing this out!

Best,
@jfmyers9
