### ISSUE TITLE
[Feature request]Request newly added diegocells to be updated in the first place among all other diegocells

### ISSUE THREAD

**Issue by taotao20082006** [cloudfoundry/bosh#2227]
**Is your feature request related to a problem? Please describe.**

Currently instance group updating order is supported not individual instances in a group. 
But one of my customer believes It's desirable to have newly added diegocells to be updated in the first place among all other diegocells because they'd prefer those new cells to be ready first so that redundancy to other cells could be increasing during upgrade.

**Describe the solution you'd like**
It's desirable to have newly added diegocells to be updated in the first place among all other diegocells. If possible, we'd like bosh can support updating order of specific instances in an instance group. 

**Additional context**
Slack conversation: https://pivotal.slack.com/archives/C3M0B3TV3/p1575451558373700

**Comment by xtreme-conor-nosal** [comment]
There are different stages to updating VMs during a deployment:
1) VMs are created/destroyed so the desired number exist, without deploying/changing any jobs
2) job are deployed/configurations updated to the new desired state

If a deployment both scales up VMs and changes the job configuration, the new VMs will never have the "old" configuration. This would add overhead to deployments that need to recreate the VM anyway (agent configuration, stemcell bump), and add complexity between the different stages in the deployment (which VMs are new).

If the customer has concerns around redundancy during a deployment, they can:
1) reduce max_in_flight
2) deploy to scale up before deploying to update configuration

**Comment by mrosecrance** [comment]
I'm going to close this as it's not something we're thinking of fixing or changing at this point in time and we have other options for redundancy.
