### ISSUE TITLE
Automated System Certificate Rotation

### ISSUE THREAD

**Issue by h4xnoodle** [cloudfoundry/bosh#2229]
### Problem
Rotating the NATS and blobstore CAs through all of the director and deployed VMs takes an immense amount of time, due to the need for deployed VMs to be recreated to update the certificates. 

The certificates have essentially no meaning to operators, as they're created during `create-env` and distributed as VMs are deployed. 

The only way to transfer new NATS/Blobstore CAs/certs to VMs is via a recreate of the entire VM. 

This is an _optimization_ that can be performed when needing to rotate the CAs. The [three-legged deploy](https://bosh.io/docs/nats-ca-rotation/) should still be performed if operators are concerned about leaked certificates.

### Proposal
Given a healthy director, an operator can execute some CLI command that executes a task that will update director and deployed VM NATS/blobstore certificates without the operator recreating all deployed VM or the director VM.

#### Director
Given a director, execute a bosh cli command that:
1. Starts a task that can be tracked
1. Shows each instance being updated during task execution
1. Handles failing VMs gracefully, allowing idempotent retries
1. Distributes the new CA and leaves to deployed VMs
1. Accepts the `--vars-store` option in order to update the creds.yml file after completion
1. Director reloads gnatsd when appropriate

#### Agents
A deployed VM, with an agent that has successfully checked in recently will:
1. Receive a message over NATS to begin the process
1. Accept a new NATS CA and leaf certificate via message from director
1. Install the new CA, concatenated with the old CA
1. Respond to ping over NATS using the new leaf certificate
1. Clean up unused artifacts from the process

### Problems
1. Security of transferring new credentials over a potentially compromised channel
1. A VM may fail to respond to a ping with the new leaf certificate, for reasons other than TLS
1. The task could be cancelled by operator(s)
1. There could be other tasks going on at once that use NATS (everything)
1. Locking the entire director and deployed VMs may be unreasonable

#### Potential Solutions to above
1. An agent could generate a keypair, and send the public key to the director to encrypt the new CA and generated leaf. If an attacker can respond as the director with a compromised CA, then using the public key could send a replacement certificate to an agent. Operators should default to the recreation-based approach in the event of a compromised NATS CA.
1. Process should be idempotent, and write enough state so the process can be resumed at any time. Old and new CAs are concatenated as the certificate authority. Retry a couple times quickly.
1. If the task is cancelled, then if the process is idempotent in all steps, then the task could be resumed. VMs should still be able to health check.
1. Deployment locks, work on one deployment at a time.
1. Director may need to have a manual 'start' and 'finish' command in order for operators to update deployments at their leisure. Expecting all deployments to be rotated at once is unreasonable.

### Security/Risks
1. What if the NATS CA is compromised? The DH key exchange would help here, but if the attacker has access to the director VM, they could also generate the keypair.
1. At the moment, the recreate is helpful as the channel for credentials is the cloud provider's metadata service. This isn't necessarily secure at all, but at least doesn't use the same channel for its own credential update. Operators concerned about the proposed optimization can still perform the three-step approach.
1. Health monitor and updating the VMs may cause some chaos, if the check intervals and updates are timed in a certain way.
1. The time it takes for gnatsd on the director to reload, and the reload/re-establish connection to NATS server from a VM could result in timeouts and necessitate more retries.

### Performance
Clearly there will be a gain in performance as operators are not required to recreate VMs, and not reinstall/start jobs back up again. Any downtime should also be eradicated. The key exchange shouldn't be that intensive. Concurrency rules like `max_in_flight` can still be honoured. Waiting for gnatsd on the director to reload and agent reconnects could take some time, but much less than a whole recreate would.

#### Accompanying Picture

![Screen Shot 2019-12-27 at 1 56 38 PM](https://user-images.githubusercontent.com/105841/71529035-c0aade00-28b0-11ea-82a5-21d6ff9d411b.png)

**Comment by beyhan** [comment]
An old slack discussion around this topic, which could be helpful: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1553631617308300

**Comment by voelzmo** [comment]
+1000 this would be tremendously helpful to have.
Thanks for the work that went into this, @h4xnoodle!

**Comment by aegershman** [comment]
Forgive this useless comment, I can delete it, but as someone whose currently rotating natsCA for all our environments prior to expiration, boy howdy having this as a more "intentional" and specific workflow that could be more easily reasoned about (which VMs have the new concatenated CA? which still need to be re-deploy/created? etc.) and performed more regularly would be nice. Thanks for all you all do 👍
