### ISSUE TITLE
Remove HM Plugin Connection Retry Limit

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#2231]
**Is your feature request related to a problem? Please describe.**
The [TcpConnection](https://github.com/cloudfoundry/bosh/blob/716ffe2a12fec6b14cd6a7731d40da7bbd586ca7/src/bosh-monitor/lib/bosh/monitor/protocols/tcp_connection.rb#L4) retries 35 times until it gives up. If the service the plugin tries to connect is not available within those retries the plugin just gives up. The only way to resolve this is, to restart the hm job on the BOSH vm.

**Describe the solution you'd like**
Remove the limit and let plugins retry forever. Since it has been configured the plugin should successfully connect as soon as the service is available, even days later. I don't see a scenario where an operator actually want the plugin to give up.

**Describe alternatives you've considered**
Work around this by monitoring for the error and restarting the health monitor job.

**Comment by h4xnoodle** [comment]
Thanks for the feedback!

As we briefly chatted about in our sync up: perhaps we can make this configurable for operators. I see some risk in indefinitely retrying: misconfigured plugin. Though it doesn't cost a lot to retry, having some limit, at least by default, would prevent indefinite retries for when it won't solve the problem.

**Comment by beyhan** [comment]
If we make it configurable we can even stay backwards compatible with a default value, which is the case at the moment. The unlimited retry could be reached with a special value `-1`, if it's needed. In BOSH we don't have this pattern, but in OpenStack is widely used.

**Comment by friegger** [comment]
The TcpConnection is only used by the `graphite` and the `tsdb` plugins. The changes would be very plugin specific.

**Comment by beyhan** [comment]
Hi @h4xnoodle ,

I have created PR: https://github.com/cloudfoundry/bosh/pull/2248, which fixes a missing part for this feature.

**Comment by h4xnoodle** [comment]
@beyhan I figured I was missing something, thanks!
