### ISSUE TITLE
When using boshdns only cannot change the default domain

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bosh#2236]
**Describe the bug**
When we removed all of the powerdns config.  The root_domain cannot be changed for bosh-dns.

**To Reproduce**
1) deploy the bosh director with powerdns configured and set the dns.domain to "newdomain"
2) note that in all vms the /etc/hosts is configured with <instance-id>.<instance-group>.<deployment>.<network>.newdomain
3) update the bosh director to remove all powerdns configuration.
4) note that in all the vms the /etc/hosts is configured with <instance-id>.<instance-group>.<deployment>.<network>.bosh
5) set the dns.domain to "newdomain"
6) note that in all the vms the /etc/hosts is configured with <instance-id>.<instance-group>.<deployment>.<network>.bosh

**Expected behavior**
When setting the dns.domain when using bosh-dns the custom domain is correct.

We could set `"dns":{"domain_name":"microbosh"},` in the director.yml config and this allowed things to work.  But due to the fact that the bosh release does not set this when there is no other powerdns configuration it's not possible to deploy the bosh director and retain this setting.

**Versions (please complete the following information):**
 - Infrastructure: Softlayer
 - BOSH version ???
 - BOSH CLI version 6.2.1
 - Stemcell version [e.g. ubuntu-xenial/621.41.1]

Please see the chat in slack here ...

https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1581347838162800

**Comment by jfmyers9** [comment]
Hi @andrew-edgar,

Thanks for letting us know. I've moved the corresponding tracker story over, so we will eventually get to this. That being said, this isn't the highest priority for us at the moment, and would always be open to receiving a PR that fixes the issue.

Best,

@jfmyers9

**Comment by gu-bin** [comment]
BOSH version: 270.11.0

**Comment by gu-bin** [comment]
This is the PR to fix the issue https://github.com/cloudfoundry/bosh/pull/2246 Please review. Thanks.
