### ISSUE TITLE
Poor performance as number of containers increase on a cell due to Ubuntu issue

### ISSUE THREAD

**Issue by univ0298** [cloudfoundry/bosh#2245]
**Describe the bug**
As we increase the number of containers on a cell, we see a significantly non-linear performance degradation. We see an even more extreme performance problem whenever transparent huge pages are used. We have tracked this down to the following Ubuntu 'bug' with memory management when large numbers of cgroups are present: https://lwn.net/Articles/759329/

**To Reproduce**
Steps to reproduce the behavior (example):
1. Simply provision a VM using the latest Ubuntu stem cell, and then the issue (https://lwn.net/Articles/759329/) has simple recreation steps that show the degrading performance of memory management as cgroups increase

Alternatively, much more difficult, you can setup a Cell and add many containers to it (more than 50, perhaps 100, on a 4-core 32GB RAM machine in our experience) and watch the system CPU increase heavily, and run tools like perf to analyze the CPU usage and see the shrink_slab poor performance.

**Expected behavior**
As described in the Ubuntu issue, the performance should not degrade exponentially like this as containers are added

**Logs**
There are no logs to assist in showing this

**Versions (please complete the following information):**
 - Infrastructure: [e.g. AWS, GCP, etc]: Expected to affect all. We have created it with IBM Cloud (SoftLayer)
 - BOSH version [e.g. 266.7]: 270.11.0
 - BOSH CLI version [e.g. 5.1.1]: version 6.0.0.1-softlayer-edf2488-2019-08-21
 - Stemcell version [e.g. ubuntu-xenial/97.10]: ubuntu-xenial/621.55
 - ... other versions of releases being used (BOSH DNS, Credhub, UAA, BPM, etc)

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.
N/A

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)
N/A

**Additional context**

**Comment by mrosecrance** [comment]
Patching kernels is outside the scope of this team. It looks like the fix is in the kernel that is included in the Focal line of Ubuntu but currently we only support Xenial - which is two supported lines earlier - created circa 2015. It's possible that Canonical may backport this feature to Xenial in which case we'd automatically ingest it, but I can't find any open issues asking for it.

Closing as there isn't anything we can do here.
