### ISSUE TITLE
[Feature request] Support batch function for ignore command

### ISSUE THREAD

**Issue by ginobiliwang** [cloudfoundry/bosh#2247]
**Describe the solution you'd like**
ubuntu@opsmgr-06-haas-59-pez-pivotal-io:~$ bosh -d service-instance_87465682-1da8-4fec-99ea-9863e8555eca vms
Using environment '10.193.71.11' as client 'ops_manager'

Task 53345. Done

Deployment 'service-instance_87465682-1da8-4fec-99ea-9863e8555eca'

Instance Process State AZ IPs VM CID VM Type Active
master/2f24225a-8ef2-4610-b6e6-a9f48df3ec56 running az1 10.193.71.165 vm-4f607b94-733c-461d-a164-21889d9d9543 medium.disk true
worker/8a77d684-4c16-48b5-afba-2e710fa00e20 running az3 10.193.71.169 vm-ce0b4189-152e-49f7-ae21-c41682335eef medium.disk true
worker/94c6863e-b470-4a74-b568-f49d4f451e32 running az2 10.193.71.168 vm-82c48d43-6c9b-4c12-b9c4-9384620cdbdf medium.disk true
worker/9cfb9c67-8c5b-4eb7-871f-1a234e5597a1 running az1 10.193.71.167 vm-b525b25f-16b3-4a52-8c37-8dacb8e37ca0 medium.disk true

4 vms

Succeeded
ubuntu@opsmgr-06-haas-59-pez-pivotal-io:$
ubuntu@opsmgr-06-haas-59-pez-pivotal-io:$ bosh -d service-instance_87465682-1da8-4fec-99ea-9863e8555eca ignore worker/*
Using environment '10.193.71.11' as client 'ops_manager'

Using deployment 'service-instance_87465682-1da8-4fec-99ea-9863e8555eca'

Succeeded
ubuntu@opsmgr-06-haas-59-pez-pivotal-io:~$ bosh -d service-instance_87465682-1da8-4fec-99ea-9863e8555eca unignore worker/*
Using environment '10.193.71.11' as client 'ops_manager'

Using deployment 'service-instance_87465682-1da8-4fec-99ea-9863e8555eca'

Succeeded

**Comment by ginobiliwang** [comment]
this PR has implemented the feature.

https://github.com/cloudfoundry/bosh/pull/2242

**Comment by ginobiliwang** [comment]
Hi Team, can anyone take a look at this feature request and PR, it is from one of customer's request.

**Comment by h4xnoodle** [comment]
Hi @ginobiliwang 

Why is implementing a batch command for ignore solving the issues you have? Ignoring a VM almost never has benefit. The feature is intended for if your VM is quite problematic and needs to be set aside, usually a scale up happening to handle the missing workforce. In failed deploy cases, ignorning a VM is usually never the right way to go -- this further compounds the problems, especially when unignoring. The best way to solve problems is to avoid ignore, and solve the individual deploy issues experienced.

As such, we'd like to avoid adding more mechanisms that may mislead others into making existing problems worse. Additionally, there isn't any motivation or value in this feature request that I can see, beyond just a demo. Why do you think including this feature is a good idea?

Thanks, and closing this now, as we will avoid the ability to ignore even more.

Rebecca

**Comment by ginobiliwang** [comment]
Hi @h4xnoodle 

It depends on you and bosh team. 
I have also explained the background information and case scenario to @mfine30 in bosh jira.

Thanks  

Fenggang
