### ISSUE TITLE
Resurrection of VMs with multiple disk in not working

### ISSUE THREAD

**Issue by rm75** [cloudfoundry/bosh#2253]
Resurrection of VMs with multiple persistent disks are not working.

Seems like it supports only single persistent disk resurrection.
https://github.com/cloudfoundry/bosh/blob/17921ed6431d126f5a029392e0498c9013d26148/src/bosh-director/lib/bosh/director/cloudcheck_helper.rb#L73

Opening this request based on the conversation in the slack channel.

**Comment by voelzmo** [comment]
Assuming this is the slack thread, just for reference and cross-linking: https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1578339832051000

**Comment by h4xnoodle** [comment]
Multiple persistent disks are semi-supported, at best. The feature is there for extreme cases where you absolutely need two classes of persistent disk. In most cases, one disk is enough.

Does your use-case only work with multiple disks attached or is this some kind of convenience? Note that we do not have any documentation on bosh.io for multiple disks, therefore not supporting any complex use-cases. We make no guarantees that multiple persistent disks work in all cases. 

As you've already identified the area of code, we are welcoming contributions :)

Thanks
