### ISSUE TITLE
Bump postgres 10 because of known vulnerabilities

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#2260]
Version 10.9 contains 4 CVEs which have been fixed in the most recent 10.12: https://www.postgresql.org/support/security/10/

Can you please bump the postgres version such that we get rid of these? Thanks!

**Comment by voelzmo** [comment]
Awesome, thanks for the quick change. Can we get a new release with this soon?

**Comment by krutten** [comment]
Hi Marco, the update to 10.12 was released in https://github.com/cloudfoundry/bosh/releases/tag/v271.1.0

**Comment by voelzmo** [comment]
Great, thanks!
