### ISSUE TITLE
S3 blobstore compiled_package_cache mixup

### ISSUE THREAD

**Issue by thelangley** [cloudfoundry/bosh#2264]
**Describe the bug**
Bosh versions newer than v270.10.0 confuse compiled_package_cache and blobstore when using s3 resource.

We attempt to deploy deployments in the same way as with previous Boshes but it says that it cannot find objects in it's blobstore (404 errors) during a deployment.

We have two buckets. One for compiled_package_cache, the other for the agent and the blobstore itself.

Bosh is able to pick up the objects from the compiled_package_cache (see extract below) but then after that it appears to get confused between it's actual blobstore (used by agent) and the compiled_package_cache.

**To Reproduce**
1. Deploy a bosh director on vSphere 6.5 with s3 backed compiled_package_cache, blobstore and agent env
2. Upload a release
3. Deploy a deployment using the release
4. Check the logs

**Expected behavior**
We would expect Bosh to use compiled_package_cache to download anything compiled and ready to go and use the blobstore for everything else

**Logs**
Successful grabbing of stuff from compiled_package_cache:
`{"time":1590145487,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Downloading ''golang-1-linux/f1e8a3f1bc4ef98c4fd7bed15b9e39e24c15cb413f827321da75d82d6bb6ab8c'' from global cache","index":3,"state":"started","progress":0}
{"time":1590145491,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"finished","progress":100}')`

The later steps in the same task show an error when trying to retrieve the package that it's just downloaded from the package cache `performing operation get: NoSuchKey: The specified key does not exist.`

**Versions (please complete the following information):**
 - Infrastructure: vSphere
 - BOSH version: 271.0.0
 - BOSH CLI version: 5.3.1
 - Stemcell version: ubuntu-xenial/621.57
 - BOSH DNS: 1.21.0
 - Credhub: 2.6.0
 - UAA: 74.15.0
 - BPM: 1.1.7

**Deployment info:**
```
...
"blobstore":{"provider":"s3cli","options":{"bucket_name":"env.bucketname","credentials_source":"static","access_key_id":"env_our_amazing_id","secret_access_key":"env_secret_access_key","region":null,"enable_signed_urls":false,"host_style":false,"port":our_port,"host":"fqdn_of_internal_s3_resource","s3cli_config_path":"/var/vcap/data/director/tmp","s3cli_path":"/var/vcap/packages/s3cli/bin/s3cli"}}
...
"compiled_package_cache":{"provider":"s3cli","options":{"bucket_name":"compiled-package-cache","credentials_source":"static","access_key_id":"our_amazing_id","secret_access_key":"our_incredible_key","region":null,"s3cli_config_path":"/var/vcap/data/director/tmp","s3cli_path":"/var/vcap/packages/s3cli/bin/s3cli","port":our_port,"host":"fqdn_of_internal_s3_resource"}}
...
"agent":{"env":{"bosh":{"blobstores":[{"options":{"access_key_id":"env_our_amazing_id","bucket_name":"env.bucketname","credentials_source":"static","host":"fqdn_of_internal_s3_resource","port":our_port,"region":"us-east-1","secret_access_key":"env_secret_access_key"},"provider":"s3"}]
```

We use bosh-deployment manifests then apply our own ops files and interpolate values from various sources

**Additional info**
We've done `bosh upload-release <thing_thats_borked> --fix` and then re-ran but we still get the same errors.

It looks like Bosh is able to grab stuff from compiled_package_cache and then putting the blob for it back into the compiled_package_cache (incorrectly), which is utterly useless. When Bosh then wants to deploy, it looks in the main blobstore for the blob. It's not there. We get 404.

If we check the actual S3 buckets, we can see Bosh writing blobs to the wrong bucket (compiled_package_cache) instead of the actual blobstore.

Not sure what's caused this change in behaviour in more recent versions. If anyone has any Bosh secrets, please let us know.

**Comment by mrosecrance** [comment]
At the moment the plan is to remove the compiled package cache entirely. If you want to weigh in on why you find it valuable, the discussion thread is here: https://lists.cloudfoundry.org/g/cf-bosh/topic/deprecating_global_compiled/71382035?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,71382035

**Comment by combor** [comment]
Hi @mrosecrance, the plan is perfectly fine, however the shared compiled cache is not removed yet and the behaviour that @thelangley described breaks deployments. Is this considered a bug that can be fixed or due to the plan to remove shared cache it's
 not gonna be fixed?

**Comment by mrosecrance** [comment]
I think we'll remove it before wanting to address any bugs related to it.
