### ISSUE TITLE
Runtime config variables are attempting to pull credhub values by ID rather than variable name, and since values have been deleted and added back in credhub, this doesn't work.

### ISSUE THREAD

**Issue by kansberry** [cloudfoundry/bosh#2267]
**Describe the bug**
When running bosh recreate or bosh run-errand against our cf-mysql deployment, we see the errors stating that "Failed to find variable '<varname>' with id '<guid>' from config server.

**To Reproduce**
Steps to reproduce the behavior (example):
1. We are using the dns.yml runtime config from the release in bosh
2. There are certificate variables defined that are to be pulled from credhub.
3. Delete these variable in credhub and recreate them. Variables will now have a new ID
4. Run "bosh -d cf-mysql recreate" (i.e. can really be any deployment using the bosh-dns runtime config)
5. You will see the error and they will be for the original values stored in credhub, not the new IDs
6. If you run "bosh -d cf-mysql vars" I found two variables defined for each "dns" variable, neither of which had the ID of the new value in credhub.

**Expected behavior**
I would expect bosh to use the variable name to lookup a value in credhub, not the ID.

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
 - Infrastructure: Azure
 - BOSH version 269.0.0
 - BOSH CLI version 5.5.1

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)

**Additional context**

**Comment by kansberry** [comment]
By the way, this is very similar to this issue https://github.com/cloudfoundry/bosh/issues/2046.

**Comment by mrosecrance** [comment]
What's the usecase for doing step 3? If it's just forcing expiry, we've seen people do the delete, but let a bosh deploy trigger a variable creation which doesn't have the same id related issues. You can also force a recreation in a manifest with a converge flag on the variable.

**Comment by mrosecrance** [comment]
Closing at there are a few "Bosh" ways to recreate variables. We track id's so we can track versions of variables if people are deploying forwards or reverting to an older manifest
