### ISSUE TITLE
How to increase root disk size (BOSH VMware vSphere deployment)

### ISSUE THREAD

**Issue by Nayak2020** [cloudfoundry/bosh#2269]
Hey There,

The default root disk size, which is 3 Gb is not sufficient, it's getting filled-up while concourse pipeline downloading some blobstore in tmp directory. We followed the bellow steps for increasing the root partition as 10 Gb but there is no result.
Steps Followed:
1) Extracted "https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=621.77"
2) Altered disk size as 10240 in stemcell.MF
3) tarred again 
4) Deleted the existing stemcell and uploaded the modified one.
5) Recreated a bosh instance (root disk size is still 3 Gb)
:(
further, we did repack-stemcell (changing disk size and version number) & uploaded the stemcell and recreated the bosh instance(with new version of stemcell) still we are blocked, no result at all.

Thanks,
Rajat.

**Comment by poblin-orange** [comment]
@Nayak2020 Hello. Cant u just use cloud_properties on vm type to specify the root disk ? see https://bosh.io/docs/vsphere-cpi/#resource-pools

**Comment by Nayak2020** [comment]
Hey @poblin-orange the disk size we define in cloud config, will create a separate EBS volume. It will not increase root partition. Anyway our Engineer team has solved the issue, previously our code was exporting some files under /tmp which was consuming root partition. Now they have exporting in different location under/var/vcap/

**Comment by poblin-orange** [comment]
Notice you can alors change robot  disk size with cloud config vm type.

**Comment by voelzmo** [comment]
On a side note: `/tmp` is not on the root disk. BOSH mounts a folder of the ephemeral disk under `/tmp` after the agent started up. If I understand your issue correctly, a bigger ephemeral disk should do the trick. If you're really running our of root disk space, the culprit might be found elsewhere, but not in `/tmp`.
