### ISSUE TITLE
Disable TLS1.0/1.1 on BlobStore server

### ISSUE THREAD

**Issue by wjun** [cloudfoundry/bosh#2277]
**Describe the bug**
BlobStore server listening on 25250 should disable TLS1.0/TLS 1.1

Currently there is no such configuration option for the blobstore nginx: https://github.com/cloudfoundry/bosh/blob/master/jobs/blobstore/templates/blobstore.conf.erb.
Which means it uses the nginx default "ssl_protocols TLSv1 TLSv1.1 TLSv1.2"  according to: http://nginx.org/en/docs/http/configuring_https_servers.html#:~:text=The%20directives%20ssl_protocols%20and%20ssl_ciphers,1%20TLSv1.

Currently only the director api specifies ssl_protocols in its nginx config. Which defaults to TLSv1.2: https://github.com/cloudfoundry/bosh/blob/master/jobs/director/spec#L94.

**Additional context**
Disable TLS 1.0/1.1 is a security requirement from many customers. Considering this is a simple fix, I would recommend to prioritize it as a critical issue to address.

**Comment by donacarr** [comment]
Hi ,

any chance to fix this issue?
