### ISSUE TITLE
lookup vbox on 127.0.0.53:53: server misbehaving

### ISSUE THREAD

**Issue by mchudinov** [cloudfoundry/bosh#2281]
**Describe the bug**
I follow the installation instructions for bosh-lite from here https://bosh.io/docs/bosh-lite/
After running this command 
`bosh -e vbox env`
I get an error:
```
mikael@CloudFoundry:~$ bosh -e vbox env
Fetching info:
  Performing request GET 'https://vbox:25555/info':
    Performing GET request:
      Retry: Get "https://vbox:25555/info": dial tcp: lookup vbox on 127.0.0.53:53: server misbehaving

Exit code 1
```

**To Reproduce**
Steps to reproduce the behavior (example):
1. A fresh new Ubuntu 18 VM with 32Gb RAM and 8 CPU
2. Just follow instructions.

**Expected behavior**
Running bosh

**Logs**
```
mikael@CloudFoundry:~$ bosh alias-env bosh-1 -e 192.168.50.6 --ca-cert <(bosh int creds.yml --path /director_ssl/ca)
Using environment '192.168.50.6' as client 'admin'

Name               bosh-lite  
UUID               c156bca7-6b52-4d36-8a87-624a4246693c  
Version            271.2.0 (00000000)  
Director Stemcell  ubuntu-xenial/621.84  
CPI                warden_cpi  
Features           compiled_package_cache: disabled  
                   config_server: enabled  
                   local_dns: enabled  
                   power_dns: disabled  
                   snapshots: disabled  
User               admin  

Succeeded
mikael@CloudFoundry:~$ 
mikael@CloudFoundry:~$ bosh -e vbox env
Fetching info:
  Performing request GET 'https://vbox:25555/info':
    Performing GET request:
      Retry: Get "https://vbox:25555/info": dial tcp: lookup vbox on 127.0.0.53:53: server misbehaving
```

**Versions (please complete the following information):**
 - Infrastructure: A VM with Ubuntu server 18 32Gb RAM and 8 CPUs
VirtualBox v 5.2

**Comment by mrosecrance** [comment]
I can't seem to reproduce this. I have used this script - automated version of the bosh.io instructions - to deploy it successfully this week: https://github.com/cloudfoundry/bosh-deployment/blob/master/virtualbox/create-env.sh. Googling this error says it's usually a dns related networking issue.
