### ISSUE TITLE
bosh cck / hm resurrector broken with multi-cpi and different stemcells (eg: vpshere and openstack)

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#2287]
**Describe the bug**
When leveraging bosh multi-cpi feature, targeting 2 different iaas (vsphere iaas, and openstack iaas)
- bosh deploy is ok
- bosh cck is KO if vms are ok
- bosh cck is KO if one vm is KO - directors mismatches stemcell type between cpi-config

**To Reproduce**
Steps to reproduce the behavior :
1. Deploy a bosh director on vsphere iaas, with appropriate cpi-config (multiple iaas backend) and cloud-config (map az to cpis)
2. Upload  vsphere stemcell
2b. Upload  openstack stemcell
3. Deploy a manifest leveraging multiple azs, using the difference cpi and this diffrent iaas type
4. delete a vm in one of the iaas
5. Run bosh cck to try to repair

**Expected behavior**
As bosh deploy is ok with multi CPI on 2 target iaas types, I expect bosh cck to be usable in that context (and also bosh hm resurrector)

**Logs**

see https://github.com/orange-cloudfoundry/paas-templates/issues/840

```
Task 12905289 | 14:22:32 | Scanning 1 VMs: Checking VM states (00:00:16)
Task 12905289 | 14:22:48 | Scanning 1 VMs: 0 OK, 0 unresponsive, 1 missing, 0 unbound (00:00:00)
Task 12905289 | 14:22:49 | Applying problem resolutions: VM for 'mysql/b9af1d12-d120-4dc9-9b8c-b92062a60587 (0)' missing. (missing_vm 3451): Recreate VM and wait for processes to start (00:00:02)
                     L Error: Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-xenial-go_agent", "version"=>"621.69"} not found for cpi region-2, please upload again
Task 12905289 | 14:22:51 | Error: Error resolving problem '19166': Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-xenial-go_agent", "version"=>"621.69"} not found for cpi region-2, please upload again

Task 12905289 Started  Mon Nov  2 14:22:32 UTC 2020
Task 12905289 Finishedon Nov  2 14:22:51 UTC 2020
Task 12905289 Duration 00:00:19
Task 12905289 error
```
==> mismatch, as region 2 is configured as vpshere iaas type

**Versions (please complete the following information):**
 - Infrastructure: vpshere and openstack
 - BOSH version 271.2.0
 - BOSH CLI version version 6.4.0-7e5d8860-2020-08-31T17:09:13Z
 - Stemcell version 621.84 (vsphere and openstack)

**Deployment info:**

Plain bosh deployment, using bosh ops files, with multi cpi az
Deployment:
```
Name                  Release(s)                  Stemcell(s)                                       Config(s)            Team(s)  
01-cf-mysql-extended  bosh-dns/1.17.0             bosh-openstack-kvm-ubuntu-xenial-go_agent/621.84  122 cloud/default    -  
                      bosh-dns-aliases/0.0.3      bosh-vsphere-esxi-ubuntu-xenial-go_agent/621.84   121 runtime/default    
                      bpm/1.1.8                   bosh-vsphere-esxi-ubuntu-xenial-go_agent/621.84                          
                      cf-mysql/37.1.0                                                                                      
                      generic-scripting/3                                                                                  
                      minio/2020-06-18T02-23-35Z                                                                           
                      node-exporter/5.0.0                                                                                  
                      os-conf/22.0.0                                                                                       
                      prometheus/26.2.0                                                                                    
                      routing/0.206.0                                                                                      
                      shield/8.7.2                                                                                         
                      syslog/11.6.0                                                                                        

```

Here is the cpi-config.yml :

```
cpis:
- name: region-1
  properties:
    datacenters:
		xxxx
  type: vsphere
- name: region-2
  properties:
	datacenters:
		xxxx	
  type: vsphere
- name: region-3
  properties:
	xxxx
  type: openstack
```

Here is the cloud-config.yml:
```
azs:
- cpi: region-1
  name: z1
- cpi: region-1
  name: z2
- cpi: region-1
  name: z3
- cpi: region-2
  name: r2-z1
- cloud_properties:
    availability_zone: eu-west-0b
  cpi: region-3
  name: r3-z1
```

**Additional context**

**Comment by poblin-orange** [comment]
@any insight / update on this issue ?

**Comment by gberche-orange** [comment]
Summary of the reverse-engineering performed with @o-orand:

With a manifest file structure as below, and the cpi-config.yml cloud-config.yml described in https://github.com/cloudfoundry/bosh/issues/2287#issue-738984393

```

addons:
- include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
    - os: ubuntu-bionic

instance_groups.jobs
  name: mysql
  networks:
  - name: tf-net-osb-data-plane-dedicated-priv
  persistent_disk_type: large
  stemcell: default
  instances: 1
  azs:
  - z1
  - z2
  - z3

releases:
- exported_from:
  - os: ubuntu-bionic
    version: "1.1"
  name: cf-mysql
  stemcell:
    os: ubuntu-bionic
    version: "1.1"

stemcells:
- alias: default
  os: ubuntu-bionic
  version: "1.1"
```

When the cloud-check command fails, the following stack trace is displayed in bosh debug task

```
E, [2021-06-02T06:41:15.523131 #2760] [task:24935638] ERROR -- DirectorJobRunner: Error resolving problem '62674': 
Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-xenial-go_agent", "version"=>"621.107"}
 not found for cpi region-1, please upload again
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:39:in `block in perform'
[...]/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `block in with_deployment_lock'
[...]/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
[.../bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `with_deployment_lock'
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/cloud_check/apply_resolutions.rb:35:in `perform'
[...]/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
[.../bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
[...]/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'
[...]/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
[.../bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'
[.../eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
[...]/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

We're observing that the `instances.spec_json` database field documented within the [director_schema](https://github.com/cloudfoundry/bosh/tree/master/docs/director_schema) has the incorrect stemcell value `bosh-openstack-kvm-ubuntu-bionic-go_agent` (instead of `bosh-vsphere-esxi-ubuntu-bionic-go_agent`)

We suspect that this `instances.spec_json` database field is assigned during a `bosh deploy` within the incorrect value assigned within https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/src/bosh-director/lib/bosh/director/deployment_plan/stemcell.rb#L60 at the following stack trace, and assigned within the `Bosh::Director::DeploymentPlan::InstancePlan` in its nested `Bosh::Director::DeploymentPlan::Instance.stemcell` field

```
[...]/bosh-director-0.0.0/lib/bosh/director/deployment_plan/stemcell.rb:46:in `bind_model'",
[...]/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:205:in `block in bind_stemcells'",
[...]/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:204:in `each'",
[...]/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:204:in `bind_stemcells'",
[...]/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:34:in `bind_models'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:94:in `block in prepare_deployment'",
[...]/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:87:in `prepare_deployment'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:42:in `block in perform'",
[...]/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `block in with_deployment_lock'",
[...]/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'",
[...]/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:7:in `with_deployment_lock'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:34:in `perform'",
[...]/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'",
[...]/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'",
[...]/bosh_common-0.0.0/lib/common/thread_formatter.rb:50:in `with_thread_name'",
[...]/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:9:in `perform'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:32:in `block in perform'",
[...]/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:98:in `block (3 levels) in run'",
[...]/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'",
[...]/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"]
```

We're suspecting that unlike  a `bosh deploy`, the `bosh cloud-check` and `bosh recreate` don't yet select the instance stemcell from the instance az, but directly use the stemcell from the deployment plan.

This reverse engineering is based on source code analysis as well as adding debugging traces in the local source to dump models and stack traces. 

We will now see if the bosh team could help us finding software architecture documentation, or potentially hint into the direction to contribute a fix.

**Comment by cunnie** [comment]
This is a problem that I'd like to fix, but it's not easy.

I'll try to work on it 1/day per week.

**Comment by gberche-orange** [comment]
thanks a lot @cunnie for your work. We're eager to help testing any fix you might be able to develop in our 3 az lab (2 vsphere and 1 openstack). 

As a stop-gap workaround, we're currently patching our director instances https://github.com/cloudfoundry/bosh/blob/83813f6323c07d49a3af62fcff8e6a94209fadfc/src/bosh-director/lib/bosh/director/deployment_plan/stemcell.rb#L60 with ` model = @models.last`. In  our 3 az environments (2 vsphere and 1 openstack), this should select the vsphere stemcell which is present on more AZs than the openstack one, making it possible after a `bosh deploy --recreate` to use `bosh cloud-check` on vsphere instances part of a multi-cpi deployment.

**Comment by o-orand** [comment]
Hello @cunnie , did you have an opportunity to investigate this issue ?
Thanks !

**Comment by cunnie** [comment]
@o-orand I'll try to look at it tomorrow.

**Comment by cunnie** [comment]
I think I may have a fix. Am testing it now.
