### ISSUE TITLE
x509: certificate has expired. ENV deployment manifest was lost. 

### ISSUE THREAD

**Issue by gtopor** [cloudfoundry/bosh#2293]
Dear Colleagues,

CA certificate has expired. I couldn't execute any commands from bosh cli.
```
Fetching info:
  Performing request GET 'https://x.x.x.x.x.x.x.x/info':
    Performing GET request:
      Retry: Get https://x.x.x.x.x.x.x.x/info: x509: certificate has expired or is not yet valid
Exit code 1
```

```
#bosh --version
version 5.1.2
```

Env deployment manifest was lost, so, I couldn't update the director and other components with new certs with "bosh create-env ..." command. 
Also, I don't have root/vcap password on director VM. 

My questions:

1. Do I have any solutions to get/find/recreate env/director manifest?
2. How can I update CA certs with  the conditions described above.?

Thanks in advance.

**Comment by benjaminguttmann-avtq** [comment]
@gtopor So everything is lost? State file as well secrets file?

**Comment by mrosecrance** [comment]
We don't save the director manifest anywhere. The expected flow is that users should keep track of how it was created and be able to re-run the create env command as needed - like to update the director version. If you don't have a state file you'll probably want to figure out how to refind the director disk. Without the director disk there isn't a way to reconnect this director to your existing vms. If you're using bbr all the state should be stored in their backup file too.
