### ISSUE TITLE
IP address allocations not released on failure while migrating networks of an instance_group with multiple instances

### ISSUE THREAD

**Issue by idoru** [cloudfoundry/bosh#2297]
**Describe the bug**
When updating a deployment to move an instance group to a different network, if the instance_group has multiple instances, then IP address allocations are not correctly released if the canary fails. We observed that the canary instance's allocation is released, but the allocations made for the other instances are not.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on GCP, although we suspect issue is IaaS agnostic with multiple networks
2. Upload ubuntu-xenial/621.99 and a cloud config defining the multiple networks
3. Deploy an instance_group with at least 2 instances to the first network, we used the zookeeper-release
4. Modify the release to have a failing pre-start script
5. Redeploy the modified release, with the instance_group's network set to the second network.
6. Verify this fails.
7. Run `bosh restart` on the deployment, this brings things back to a green state, where the non-modified release is deployed on the first network again.
8. Redeploy the non-modified release to the second network, this should succeed.
9. Note that the canary will have the first IP from the dynamic range, but the additional instances will have skipped IP addresses. In a sufficiently large deployment, this can cause exhaustion of the available IP addresses.

We can additionally verify that there are extra IP address allocations for the instance_groups that aren't being used. See our logs below.

**Expected behavior**
Unused IP address allocations should not remain. Whether this is by steps 8/9 reconsuming the previously allocated IP addresses, or some other cleanup mechanism.

**Logs**
When we log into the bosh console, after step 9, we saw something like this:
```
irb(main):003:0> puts Bosh::Director::Models::IpAddress.map(&:info).grep(/zookeeper-bad/);nil
zookeeper-bad.zookeeper/1 - default2 - 10.10.1.1 (dynamic)    <--- orphaned
zookeeper-bad.zookeeper/2 - default2 - 10.10.1.2 (dynamic)   <--- orphaned
zookeeper-bad.zookeeper/0 - default2 - 10.10.1.0 (dynamic)   <--- canary
zookeeper-bad.zookeeper/1 - default2 - 10.10.1.3 (dynamic)    <--- matches `bosh vms`
zookeeper-bad.zookeeper/2 - default2 - 10.10.1.4 (dynamic)    <--- matches `bosh vms`
```

**Versions (please complete the following information):**
 - Infrastructure: GCP
 - BOSH version 271.2.0
 - BOSH CLI version [e.g. 5.1.1]
 - Stemcell version ubuntu-xenial/621.99

**Comment by jpalermo** [comment]
Fixed with the above commit.
