### ISSUE TITLE
Stemcell does not contain an AMI in region eu-south-1

### ISSUE THREAD

**Issue by matteowiz** [cloudfoundry/bosh#2298]
We are trying to deploy bosh director in AWS region eu-south-1 but cannot find AMI images for bosh stemcell.

Error log:

===== 2021-04-03 08:00:13 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty create-env --skip-drain /var/tempest/workspaces/default/deployments/bosh.yml --recreate-persistent-disks --recreate"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'

Started validating
 Validating release 'bosh'... Finished (00:00:18)
 Validating release 'bosh-aws-cpi'... Finished (00:00:02)
 Validating release 'uaa'... Finished (00:00:37)
 Validating release 'credhub'... Finished (00:00:16)
 Validating release 'bosh-system-metrics-server'... Finished (00:00:16)
 Validating release 'os-conf'... Finished (00:00:00)
 Validating release 'backup-and-restore-sdk'... Finished (00:00:41)
 Validating release 'bpm'... Finished (00:00:16)
 Validating cpi release... Finished (00:00:00)
 Validating deployment manifest... Finished (00:00:00)
 Validating stemcell... Finished (00:00:00)
Finished validating (00:02:28)

Started installing CPI
 Compiling package 'ruby-2.6.5-r0.29.0/269dc54d5306119b0e4f89be04f6c470b4876f552753815586fd1ab8ebeaa70d'... Finished (00:01:46)
 Compiling package 'bosh_aws_cpi/ccaa61cf69883e2068727d64c0ecbba7022e5608f966283ee89bd3782d809c35'... Finished (00:00:02)
 Installing packages... Finished (00:00:00)
 Rendering job templates... Finished (00:00:01)
 Installing job 'aws_cpi'... Finished (00:00:00)
Finished installing CPI (00:01:50)

Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-xenial-go_agent/621.101'... Failed (00:00:03)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-aws-xen-hvm-ubuntu-xenial-go_agent 621.101):
 CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Stemcell does not contain an AMI in region eu-south-1","ok_to_retry":false}

This is from a standard apply changes inside Ops manager deployed on AWS region eu-south-1

Is it possible to build bosh stemcell locally or point to an AMI from a different region?

Regards,

--
matteo

**Comment by mrosecrance** [comment]
Hi @matteowiz, It sounds like you're a VMWare Opsman customer. The best path would be open a looper/support ticket through VMWare channels to get this addressed. Ops manager does not support this region either as far as I know. On the Open source Bosh side, we are open to adding new aws light regions with enough documented need (it does cost us a bit each month to support each region) but a internal support ticket would also help establish that.

**Comment by srik54760** [comment]
I am getting the same error as below . Can you provide what is the with this and how can we resolve it?

Error: CPI error 'Bosh::Clouds::CloudError' with message 'Stemcell does not contain an AMI in region eu-west-1' in 'create_stemcell' CPI method (CPI request ID: 'cpi-626547')
