### ISSUE TITLE
No_Proxy settings getting ignored by Health Monitor

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry/bosh#2331]
**Describe the bug**
Since the update to BOSH version v271.9.0 (we are using the commit 36f5c668b57bc2ebe53fc3404cc72b74bb0beb9e of bosh-deployment) we do not get any metrics from the graphite health_monitor plugin anymore. After checking the logs we can see that the health_monitor gets blocked by the proxy when trying to access localhost:25555. This is strange as localhost as well as 127.0.0.1 are part of the no_proxy config. When switching back to v271.8.0 the issue disappeared again. We also tried the last version at this point v2.13.0 which did not solve the issue. Funny enough as it seems that the proxy setting itself gets applied but not the no_proxy one.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on openstack with a http_proxy configured, the proxy needs to block access to localhost. no_proxy settings need to include localhost and 127.0.0.1
2. Deploy any deployment so that health_monitor has something to check
3. Check the logs of health_monitor on the director VM, it should have an error page from proxy that states that access to https://localhost:25555/info has been blocked.

**Expected behavior**
I would expect that access localhost is possible because no_proxy setting is getting applied.

**Versions (please complete the following information):**
 - Infrastructure: openstack
 - BOSH version 271.9.0 - 271.13.0
 - BOSH CLI version 6.4.5-197a25ae-2021-08-19T18:47:22Z
 - Stemcell version bosh-openstack-kvm-ubuntu-bionic-go_agent-raw 1.1
 - uaa: 75.5.0
 - credhub: 2.9.0
 - bosh-openstack-cpi: 45 
 - bpm: 1.1.12
 - os-conf: 22.1.1

**Deployment info:**
bosh-deployment: 36f5c668b57bc2ebe53fc3404cc72b74bb0beb9e

**Comment by rkoster** [comment]
I'm assuming this ops-file is being used: https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/proxy.yml
```
- type: replace
  path: /instance_groups/name=bosh/properties/env?
  value: &env
    http_proxy: ((http_proxy))
    https_proxy: ((https_proxy))
    no_proxy: ((no_proxy))

- type: replace
  path: /cloud_provider/properties/env?
  value: *env
```

This uses global properties which is why the proxy settings are picked up by the health monitor component.
For this case, I would recommend using job properties like for example so:
```
- type: replace
  path: /instance_groups/name=bosh/jobs/name=director/properties?/env
  value: &env
    http_proxy: ((http_proxy))
    https_proxy: ((https_proxy))
    no_proxy: ((no_proxy))
```

**Comment by combor** [comment]
@rkoster we have tried your solution but now the deployment fails like this:
```
/root/.bosh/installations/7956723b-b993-4b8b-47e2-08506cf51848/tmp/erb-renderer029058794/erb-render.rb:60:in `p': Can't find property 'director.db.password' (TemplateEvaluationContext::UnknownProperty)
```
It looks like enabling properties for a specific job overlaps all global properties.

**Comment by benjaminguttmann-avtq** [comment]
@combor yes that is right, as soon as you configure job level properties, the global properties get ignored. That's the reason we used the pre-start script to remove the proxy settings from health-manager bpm.yml before starting it

**Comment by rkoster** [comment]
Hmm, I thought it did some merge, but maybe that's only when using a director, and not with bosh create-env. @combor apologies for wasting your time.

**Comment by rkoster** [comment]
Last Monday we have prioritized a story to address this issue, so it's now in our backlog.

**Comment by nouseforaname** [comment]
I created a PR that hopefully fixes this. 

https://github.com/cloudfoundry/bosh/pull/2342

**Comment by poblin-orange** [comment]
@rkoster @lnguyen Hello. Hitting this issue. Any chance a new release is cut soon so we can benefit from this fix ?

**Comment by rkoster** [comment]
Have created a chore in our backlog to cut a release, it will probably be picked up somewhere next week.

**Comment by lnguyen** [comment]
@poblin-orange we cut new bosh-release today
