### ISSUE TITLE
Difficult to locate the parent release of a missing blob during a bosh deployment

### ISSUE THREAD

**Issue by cagiti** [cloudfoundry/bosh#2366]
**Describe the bug**
When bosh is unable to locate a blob during deployment the failure message doesn't display which release the missing blob is associated with. This makes it difficult to locate and resolve, especially for large deployments comprising of many releases. Some information about the failure is written to the event table (_visible within the task debug logs_), but it doesn't explicitly point to the affected release.

**Expected behavior**
The log message which alerts the operator of the missing blob displays the release to which the missing blob is associated.

**Logs**
Task 1212000 | 16:11:21 | Compiling packages: golang-1-linux/1ab563903c1f130ca908d3abdbf66650a395d3b77134474bff837aeed3649c06 (00:04:00)
                        L Error: Action Failed get_task: Task 4bfff95d-e109-493e-5ba9-d66f59e364d6 result: Compiling package golang-1-linux: Fetching package golang-1-linux: Fetching package blob : Failed to download blob: Error executing GET, response was 404

**Versions:**
 - Infrastructure: AWS
 - BOSH version: 271.16.0
 - BOSH CLI version: 6.4.17
 - Stemcell version: ubuntu-bionic/1.67

**Additional context**
A possible workaround is to use the missing blob (_in this case: golang-1-linux/1ab563903c1f130ca908d3abdbf66650a395d3b77134474bff837aeed3649c06_) information when inspecting each release outlined in the deployment manifest.

**note: You would need to install [jq](https://stedolan.github.io/jq/) and [yq](https://github.com/mikefarah/yq) as well as the bosh cli**
An example can be seen below:
```sh
deployment="my-deployment"
blob="golang-1-linux/1ab563903c1f130ca908d3abdbf66650a395d3b77134474bff837aeed3649c06"
for release in $(yq r <(bosh -d ${deployment} manifest) 'releases.*.name') #<---you could also just pass a manifest.yml in here
do
	echo "checking release: ${release}"
	for package in $(bosh releases --json | jq --arg release "$release" '.Tables[].Rows[]| select(.name == $release ) | .version|= gsub("[*]"; "") | .name + "/" + .version' --raw-output)
	do
		echo "checking package: ${package}"
		bosh inspect-release "${package}"  --json | jq --arg blob "$blob" '.Tables[] | select(.Content == "packages") | .Rows[] | select(.package | contains($blob))'
	done
done
```

**Comment by rkoster** [comment]
@cagiti Thanks for reporting this, we are happy to review a PR that would improve the error message emitted by the bosh agent.
