### ISSUE TITLE
Question about bosh-template tool and how to convert spec file in a json format

### ISSUE THREAD

**Issue by JCL38-ORANGE** [cloudfoundry/bosh#2368]
Hello,

I would like to use in command line the nice tool bosh-template.
```
bosh-template my-template --context "$(cat my-context.json)"
```
The second argument is a json file. How is it possible to convert easily my spec file in a json format in order to render my job template with bosh-template utility ?  
Thanks and regards,
Jean-Christophe.

**Comment by rkoster** [comment]
Could you provide an example? Also, json should be backward compatible with yaml.
