### ISSUE TITLE
AMIs went missing  in AWS region eu-west-1 for xenial stemcells 621.5 ,170.3,

### ISSUE THREAD

**Issue by Manu2516789** [cloudfoundry/bosh#2388]
Hi all,

Currently We are having issues with our AMIs present in AWS region eu-west-1 for xenial stemcells 621.5 ,170.3,

Suddenly the AWS AMI went missing form our AWS account and when we try to upload the stemcell for that it says it already exists.

But when we use --fix option to fix this it gives below error :

L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Stemcell does not contain an AMI in region eu-west-1' in 'create_stemcell' CPI method (CPI request ID: 'cpi-433859')

Please let us know what is the issue, why the AMI went missing and what could be the cause?

Also we are able to upload any new stemcell and find its AMI on AWS like for version 621.123.

Please let us know how can we resolve this issue.

We raised it with AWS on why the AMIs are missing bt we received the response as we are not owner of this AMIs and to contact the owner of these AMIs 
  
![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/108140249/175562602-6da00423-2221-40ac-a013-8cd5aa7abe08.png)
![MicrosoftTeams-image (29)](https://user-images.githubusercontent.com/108140249/175562665-8cf4957c-b9d7-4c78-b9e6-3bb401f36fc8.png)

**Comment by nouseforaname** [comment]
That's the exact same stemcells that were already handled with the slack thread

**Comment by cpieper78** [comment]
So is there no answer to this issue? I am blocked by this very same problem.

**Comment by Infra-Red** [comment]
> So is there no answer to this issue? I am blocked by this very same problem.

Did you try to upload a full stemcell instead? Heavy stemcells do not depend on AMIs that are published on AWS. 

I’ve checked that the link is still downloadable: https://bosh.io/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent#v621.125
