### ISSUE TITLE
many stale bosh tasks remains in the database (>2000) after using console command line to purge 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [cloudfoundry/bosh#2389]
**Describe the bug**
Many stale bosh tasks remain in the database (>2000, 278613 exactly) after using console command line to purge 

**To Reproduce**
I used the following link to purge stale bosh tasks : 
https://community.pivotal.io/s/article/How-to-clean-up-stale-BOSH-tasks-history-from-console?language=en_US
```
sudo -i
/var/vcap/jobs/director/bin/console
tr=Bosh::Director::Api::TaskRemover.new(2000)
tr.remove('vms')
```

["type: cck_apply count: 5",
 "type: cck_scan count: 5",
 "type: delete_artifacts count: 79",
 "type: delete_deployment count: 85",
 "type: export_release count: 24",
 "type: run_errand count: 53",
 "type: scheduled_dns_blobs_cleanup count: 17",
 "type: scheduled_events_cleanup count: 720",
 "type: scheduled_orphaned_disk_cleanup count: 6",
 "type: scheduled_task_cleanup count: 5",
 "type: snapshot_deployment count: 3587",
 "type: snapshot_deployments count: 31",
 "type: snapshot_self count: 32",
 "type: ssh count: 584",
 "type: update_deployment count: 124",
 "type: update_release count: 457",
 "type: update_stemcell count: 4",
 "type: vms count: 278613"]

**Expected behavior**
I expect that it remains only 2000 tasks in my database.

**Versions (please complete the following information):**
 - Infrastructure: vpshere and openstack
 - BOSH version 271.18.0
 - BOSH CLI version 6.4.11-e5579de9-2022-01-05T23:48:09Z
 - Stemcell version bionic 1.61 (vsphere and openstack)

**Comment by JCL38-ORANGE** [comment]
Some additional informations : 
Extra tasks have been purged by bosh director during the afternoon. What component is in charge of that ?
Many thanks.

**Comment by rkoster** [comment]
Why are you using the console and not configuring the director via: https://github.com/cloudfoundry/bosh/blob/main/jobs/director/spec#L111-L116

**Comment by JCL38-ORANGE** [comment]
Hello,
Thanks for this tip. I will have a look to this alternative.
Regards,
JC.
