### ISSUE TITLE
Bosh internal certs rotation

### ISSUE THREAD

**Issue by Manu2516789** [cloudfoundry/bosh#2402]
Hi,

Our orchestrator bosh related certs and bosh-dns certs will be expiring in Jan 2023 so we are planning to have it rotated in our test environment first.

So which one should be rotated first bosh-dns or bosh?

What is the process ? Does it require downtime for the underlying deployments?

and do we have to recreate all the deployment vms in this process??

Please suggest.

**Comment by beyhan** [comment]
Hi @Manu2516789,

please check the available documentation about credentials rotation in
https://bosh.io/docs/dns/#rotating-dns-certificates
https://bosh.io/docs/credential-rotation/

If you find something missing in the docs please open an issue for [docs-bosh](https://github.com/cloudfoundry/docs-bosh).
