### ISSUE TITLE
Certificates of CF deployment regenerating

### ISSUE THREAD

**Issue by Manubhaskar25** [cloudfoundry/bosh#2411]
Hi all,

 iam  trying to change the certificates of my CF deployment as it will be expiring in January 2023 trying this new method mentioned here instead of going with the old vars-store method of 3 step rotation.

https://github.com/pivotal/credhub-release/blob/main/docs/ca-rotation.md

https://docs.vmware.com/en/Spring-Cloud-Gateway-for-VMware-Tanzu/1.2/spring-cloud-gateway/GUID-rotating-certificates.html

In the step 3 mentioned here in link 1 or the step 4 mentioned in link 2 can we use the

bulk-regenerate --signed-by <CA>
command to regenerate all the leaf certificates present in the credhub signed by their CAs? or will there be any negative impact or issues in case of Cloud Foundry certificates?

Also using this credhub cli while regenerating how can the validity of all the certs and cas be modified ?

**Comment by ramonskie** [comment]
for rotating all the certs i would recommend a tool like https://github.com/starkandwayne/carousel

**Comment by rkoster** [comment]
setting certificates to a transitional state is not supported by the credhub cli, which is why the curl command is shown. There are tools which can automate these types of operations (carousel for OSS and credhub meastro of VMware customers).
