### ISSUE TITLE
monit is not able to start all workers after bumping to v276.1.0+

### ISSUE THREAD

**Issue by Malsourie** [cloudfoundry/bosh#2421]
**Describe the bug**
Our bosh director contains 24 workers and internal postgres job. In the `jobs` block of our bosh-deployment manifest, it is configured as:
```
jobs:
  ... other jobs
  - name: director
    release: bosh
  - name: postgres
    release: bosh
  ... other jobs
```
After we bump the bosh to 276.1.1, we have faced the following error:
```
[bosh][INFO] Task 43 | 16:00:34 | L starting jobs: bosh/c35c9923-351b-46f3-9b07-b54ceff1894c (0) (canary) (00:09:05)
[bosh][INFO]                    L Error: 'bosh/c35c9923-351b-46f3-9b07-b54ceff1894c (0)' is not running after update. Review logs for failed jobs: nats, bosh_nats_sync, blobstore_nginx, director, worker_1, worker_2, worker_3, worker_4, worker_5, worker_6, worker_7, worker_8, worker_9, worker_10, worker_11, worker_12, worker_13, worker_14, worker_15, worker_16, worker_17, worker_18, worker_19, worker_20, worker_21, worker_22, worker_23, worker_24, director_scheduler, director_nginx, health_monitor, blackbox, postgres, cpi, uaa
[bosh][INFO] Task 43 | 16:06:30 | Error: 'bosh/c35c9923-351b-46f3-9b07-b54ceff1894c (0)' is not running after update. Review logs for failed jobs: nats, bosh_nats_sync, blobstore_nginx, director, worker_1, worker_2, worker_3, worker_4, worker_5, worker_6, worker_7, worker_8, worker_9, worker_10, worker_11, worker_12, worker_13, worker_14, worker_15, worker_16, worker_17, worker_18, worker_19, worker_20, worker_21, worker_22, worker_23, worker_24, director_scheduler, director_nginx, health_monitor, blackbox, postgres, cpi, uaa
[bosh][INFO]
[bosh][INFO] Task 43 Started  Tue Dec 20 15:56:26 UTC 2022
[bosh][INFO] Task 43 Finished Tue Dec 20 16:06:30 UTC 2022
[bosh][INFO] Task 43 Duration 00:10:04
[bosh][INFO] Task 43 error
```
We rebump the bosh again and in the meanwhile we ssh to the bosh instance, execute `watch monit summary`. We observed that the process list sequence is the same as what we defined in the manifest,  and monit start all the processes from top to bottom. Since process `bosh_nats_sync` and `worker`s need to connect to the postgres, but postgres will be started after them in this case, the start sequence behaves like:

1. `bosh_nats_sync` stating...
2. `bosh_nats_sync` stating fails...
3. `worker_1` starting ...
4. `worker_1` starting fails...
5. worker_2. 3. 4...24
6. `postgres` starting...
7. `postgres` running
8. all the failed process restarting and running

The starting timeout during bosh deploy is set to 10 minutes, but the whole starting process cannot be done within this limit.

We have also compared the behaviour of v276.0.0 and v276.1.1, the difference is the ruby postgres client `libpq` is compiled by gcc previously and by clang in the new version. And the starting performance of compiled by gcc `libpq` is better than the one compiled by clang. So previously the duration between step 1 and 5 is shorter. The bosh manage to run all the starting steps.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy a bosh director with job block:
```
jobs:
  ... other jobs
  - name: director
    release: bosh
  - name: postgres
    release: bosh
  ... other jobs
```
2. `bosh ssh` to a specific instance
3. Run `watch monit summary` on the vm to see the behavior

**Expected behavior**
All the jobs are started in parallel by monit. The jobs sequence in manifest should not matter, at least it is not documented in [jobs block](https://bosh.io/docs/manifest-v2/#instance-groups).
The performance difference of libpq, which is compiled by gcc and clang, should not be so prominent.

**Logs**
See bug description

**Versions (please complete the following information):**
 - Infrastructure: all IAAS
 - BOSH version: 276.1.1
 - BOSH CLI version version 7.0.1-799538d1-2022-06-01T21:53:20Z
 - Stemcell version ubuntu-jammy/1.71

**Comment by rkoster** [comment]
This seems to be a limitation in monit, given that the bosh-agent is just performing a start per service: https://github.com/cloudfoundry/bosh-agent/blob/main/jobsupervisor/monit_job_supervisor.go#L142
https://github.com/cloudfoundry/bosh-agent/blob/main/jobsupervisor/monit/http_client.go#L71

The observed batching is not something which the bosh-agent is doing. There is no way for us to change the monit behaviour.

Besides the slower libpq start times, did you see any negative consequences in performance from the fact that libpq using clang?

Also are you sure libpq was actually compiled with clang? Given that I did not see any evidence of that in: https://github.com/cloudfoundry/bosh/blob/main/packages/libpq/packaging. Unless make prefers clang over gcc and has automatically picked it up. 

I'm missing something like: https://github.com/bosh-packages/ruby-release/blob/master/packages/ruby-3.2/packaging#L17-L20 for libpq.
