### ISSUE TITLE
bosh lifecycle pre-start/post-start ... not applied on raw vm reboot

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#2426]
**Describe the bug**
On an instable iaas, the vm are sometimes hard rebooted.
In that case, the monit process are restarted, but the bosh lifecycle scripts are not applied, resulting in strange / undetectable issues.
eg: 
- https://github.com/orange-cloudfoundry/paas-templates/issues/1862
- https://github.com/orange-cloudfoundry/networking-release/releases/tag/v10

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director on <IaaS> with <configuration options>
2. Upload <stemcell> and <cloud-config>
3. Deploy <manifest> with a bosh release
4. `bosh ssh` to a specific instance
5. Run `reboot` on the vm to see the behavior
6. `bosh ssh` to the instance
7. observe that the pre-start script is not applied

**Expected behavior**
We expect the bosh director to be notified of raw reboot, and 
- identify the uncorrect state of the bosh deployment
- reapply  a complete bosh lifecycle  (monit stop / pre-start / monit start / post-start / post-deploy)

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
 - Infrastructure: [vsphere, openstack]
 - BOSH version 276.1
 - Stemcell version [bosh-openstack-kvm-ubuntu-bionic-go_agent/1.171]

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)

**Additional context**

**Comment by rkoster** [comment]
Would it be an option to make the network changes in a more persistent matter, as in install some systemd unit file to apply the network changes on startup?

**Comment by gberche-orange** [comment]
Yes, sorry thanks @rkoster 

we made a wrong assumption related to pre-start lifecycle

https://bosh.io/docs/job-lifecycle/#non-bosh-vm-operations
> pre-start, post-start, post-deploy are not executed, since the bosh lifecycle is not invoked. It is recommended that a job's monitrc start program perform all operations required to start a job without depending on pre-start executing.

This issue can be closed, thanks for your review @rkoster !
