### ISSUE TITLE
Multi-cpi with different iaas bosh cpi releases induce ruby package conflict

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh#2471]
**Describe the bug**
When using bosh in muti context with 2 different bosh release (openstack cpi and vsphere cpi), we met a conflict due to different vendored ruby package.

**To Reproduce**

see https://github.com/orange-cloudfoundry/paas-templates/issues/2100
Steps to reproduce the behavior (example):
1. Deploy a bosh director on vsphere
2. Upload jammy 1.207 stemcell and cpi config, targeting vsphere and openstack iaas
3. Deploy bosh director manifest

**Expected behavior**
We would expect isolation between cpis (having no version coupling between bosh releases versions)

**Workaround

align bosh cpis releases versions to use the same vendored ruby package

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**

    stemcell bosh-vsphere-esxi-ubuntu-jammy-go_agent/1.207
    bosh/277.4.3
    bosh-openstack-cpi/51
    bosh-vsphere-cpi/88

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)

**Additional context**

**Comment by ramonskie** [comment]
should be solved now with the new openstack cpi 54 version
