### ISSUE TITLE
Automatically switch "bosh target http://" to https

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#261]
If you try to target a bosh that returns an error "The plain HTTP request was sent to HTTPS port" in its HTML because you used http:// then automatically change the target URL to https:// and try again.

If all boshes are always https to the director; then that's even simpler. Automatically change it to https before trying to contact.

**Comment by dpb587-pivotal** [comment]
Closing - hostnames and IPs automatically default to https and port 25555. Further CLI work is happening in https://github.com/cloudfoundry/bosh-cli.
