### ISSUE TITLE
"bosh upload release" uploads latest final release

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#276]
Current "bosh upload release" without a file argument only works after you just created a release. Instead of failing/doing nothing it should default to uploading the latest final release.

**Comment by dpb587-pivotal** [comment]
Closing - [new dev CLI](https://github.com/cloudfoundry/bosh-cli/) uploads the newest version of dev+final releases ([test](https://github.com/cloudfoundry/bosh-cli/blob/6004019b5f35a217b0b39d3179c74c06c78c2e75/releasedir/fs_release_dir_test.go#L346)). Give that workflow a try and feel free to discuss further in slack.
