### ISSUE TITLE
Do not fail when using colocated jobs that have no spec.properties; instead always update that VM during deploy/apply

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#281]
Currently, it is possible to write a job in a release to include a `properties` section in the job's spec file. For example https://github.com/cloudfoundry/cf-release/blob/master/jobs/cloud_controller_ng/spec#L23-L215. cf-release has only 6 jobs that are using this new system:

```
$ grep '<%= p("' jobs/*/templates/* | awk '{print $1}' | cut -d / -f 2 | uniq        
cloud_controller_ng
dashboard
dea_next
gorouter
servicesmgmt
syslog_aggregator
```

Sadly, currently in bosh it throws an error if you try to colocate one of these jobs with another job that does not include a `properties` section in its spec file.

The purpose of the `properties` section in `spec` is to allow the director to know when that job template should be updated during a `bosh deploy`. That is, if you change `x.y.z` property, but `cloud_controller_ng` doesn't specify `x.y.z` then do not `apply` (update) the cloud_controller_ng job templates throughout the deployment.

That's a great feature.

But currently, if you colocate that job with another job that doesn't specify `properties`; it errors:

```
Error 80010: Job `core' has specs with conflicting property definition styles between its job spec templates.  This may occur if colocating jobs, one of which has a spec file including `properties' and one which doesn't.
```

I do not see a need to error. Instead just do not provide the feature as above. That is, if you colocate a job that does not provide any `properties` specification, then mark the whole jobs as "update always".

Please don't unnecessarily prevent job templates from being colocated.

**Comment by amaltson** [comment]
I just ran into this and was banging my head for a while. In my case the release didn't even have any templates that had properties inside of them. I just had a line that had something like:

```
hostname application.<%= index %>
```

That was the only interpolated aspect of the template.
