### ISSUE TITLE
Display the JOB/INDEX in the ssh terminal prompt.

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#285]
Currently, the ssh terminal prompt is relatively unhelpful:

```
bosh_ogre9wa5e@455a72d5-b2ab-42cb-8585-61fff1185c34:~$
```

Instead, perhaps show the job/index of the vm (plus the path):

```
cloud_controller/0:~$
```

**Comment by dpb587-pivotal** [comment]
Closing - will be in the next stemcell via #1316.
