### ISSUE TITLE
cannot bosh ssh to compiling machines

### ISSUE THREAD

**Issue by msackman** [cloudfoundry/bosh#291]
In AWS, bosh helpfully tags compilation machines so you can see what they're compiling, eg `compiling/bzip2_1.0.6`

However, you can't then do `bosh ssh  compiling/bzip2_1.0.6 --gateway_host micro.msackman.cf-app.com --gateway_user vcap`

This is consistent with the output of `bosh vms` which also suggests these are not actually machine jobs/indices.

However, surely much of the point of **not** shutting down compilation machines after failure is so that you can ssh in and have a poke around to try and figure out what went wrong, if the logs are not enough for you. On that basis, it would be very useful if the `bosh ssh` command would work.

**Comment by cppforlife** [comment]
Closing. `bosh ssh` into compilation VMs was implemented earlier in the year.
