### ISSUE TITLE
cycle detection inconsistent

### ISSUE THREAD

**Issue by msackman** [cloudfoundry/bosh#295]
If you have a cycle in your package dependencies, `bosh create release` will tell you you have a cycle (and nothing more). If you comment out the cycle detection in `bosh_cli-1.5.0.pre.676/lib/cli/dependency_helper.rb` then `create release` will complete normally, and then `upload release` will fail, telling you that you have a cycle. However, this time, it actually tells you what the cycle is, which is extremely helpful.

It is worrying that the cycle detection code has been reinvented rather than abstracted out.

Even more helpful than telling you what the cycle is in **both** places, would be telling you what **all** the cycles are - it's annoying to fix a cycle only for create+upload to fail again on the next one. Obviously, it's more work, but in general, detecting as many errors as possible at once and reporting them all is preferable to stopping and reporting on the first error you find. More info is always better, in general.

**Comment by dpb587-pivotal** [comment]
Closing - [upcoming CLI](https://github.com/cloudfoundry/bosh-cli/) is written in Go so there is no longer potential shared Ruby code that can be refactored. The gobosh CLI does not do any special parsing of package dependencies, so all cyclical dependency checks end up happening on the director and a verbose error is given.
