### ISSUE TITLE
Merge "Creating bound missing VMs" and "Binding instance VMs" stages during deployment

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#315]
During `bosh deploy` there are two stages that I think should be combined. The reason to combine them is that if any instance/VM fails during the "Creating bound missing VMs" stage, it is not immediately possible to run `bosh deploy` again (instead, `bosh cck` is necessary to effectively perform the "Binding instance VMs" stage on the successful VMs).

See https://groups.google.com/a/cloudfoundry.org/forum/?fromgroups#!topic/bosh-users/0iLW7_b7aw8 for an example of an error during "Creating bound missing VMs" stage and the consequence of the next `bosh deploy`.

Instead of two stages, immediately run the "Binding instance VMs" code on each VM as it is created within the  "Creating bound missing VMs" stage.

/cc @pmenglund

**Comment by dpb587-pivotal** [comment]
Closing - the relevant code has changed quite a bit since this was originally brought up and I don't think this is an issue anymore. Feel free to raise a new issue with updated CLI output if this is still an issue.

**Comment by pmenglund** [comment]
Yay for cleanup 😄
