### ISSUE TITLE
When add DNS, DNS are not applyed in existing vms

### ISSUE THREAD

**Issue by TieWei** [cloudfoundry/bosh#316]
Hi, 
   These days I want to point all the bosh deployed vms to our local dns server, so I edit bosh manifest file in networks setting, as bellow: 
networks:

    - name: manual
      type: manual
      subnets:
      - name: private-net
        range: 192.168.20.0/24
        gateway: 192.168.20.1
        dns:
          - 192.168.20.4 ## here it is
        reserved:
          - 192.168.20.2 - 192.168.20.20
        static:
          - 192.168.20.21 - 192.168.20.51
        cloud_properties:
          security_groups:
            - default 
          net_id: 54538dbc-2ea0-45b4-9207-cdef2f7d7211 

All things looks good, so when I add new vm, the new created vms are point to 192.168.20.4 as dns server. But the vms which already existed, dns not changed.
When I look into the code, find below.
1. When director sent "prepare_network_change" message, it will be processed here : https://github.com/cloudfoundry/bosh/blob/master/bosh_agent/lib/bosh_agent/handler.rb#L198
    I believe it will run post_prepare_network_change which will delete setting.json and do `/sbin/halt` without reloading the setting from platform.
    but according to the log seems it do not do the work and do nothing. 
   ok, the network not changed here.
2. Then here is another `apply` message that make agent to apply the network change, it's working in here : https://github.com/cloudfoundry/bosh/blob/master/bosh_agent/lib/bosh_agent/message/apply.rb#L33 
    The `@new_spec["networks"]` is marked as changed here, but the apply work will only change the job in the spec, without do a reloading of the common settings as the spec.
    As a result, the dns of existing vms will not changed.( other change such as ip change will create a new vm)

Have I missed something about the process ? If not,  I believe it's kind of bug to be fixed. And the fix work is easy, adjust code in  `Message::PrepareNetworkChange::process` or `post_prepare_network_change` or `Message::Apply::apply` will all work, and we can discuss which way is more clear.

**Comment by dpb587-pivotal** [comment]
Closing - as of v241, DNS changes (and any other network-related changes) will cause a recreate.
