### ISSUE TITLE
[microbosh] Shouldn't need to pass a stemcell to upgrade persistent disk of microbosh

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#380]
When upgrading/changing properties or persistent disk, I'd like to be able to run:

```
bosh micro deploy --update
```

and not have to find the stemcell or AMI.

The usage infers that the stemcell is optional:

```
micro deploy [<stemcell>] [--update]
    Deploy a micro BOSH instance to the currently selected deployment
    --update          update existing instance
```

But when I run it without the stemcell:

```
$ bosh micro deploy --update
No stemcell provided
```

**Comment by cppforlife** [comment]
Closing in favor of using bosh-init.
