### ISSUE TITLE
bosh vms need their /etc/resolv.conf updated after microbosh recreated/redeployed

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#383]
During `bosh micro deploy --update` a new VM is used for the microbosh, which has a different private IP.

This means that the running deployments now all have an invalid `/etc/resolv.conf` and cannot resolve DNS anymore. This is a bad thing.

All VMs need to have their `/etc/resolv.conf` updated with the microbosh's new IP after microbosh deployment.

**Comment by dpb587-pivotal** [comment]
Closing - microbosh is deprecated and we use `resolv.conf.d` configuration files now.
