### ISSUE TITLE
Show a useful error message if user has no local pub/priv keys for "bosh ssh"

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#389]
Currently, if user has no public/private keys and they try to run `bosh ssh` they get an ssh error that doesn't tell them what to do next. Instead, detect that there are no default public/private keypairs and educate user what to do next.

OR, generate a keypair for them (like Heroku CLI does)

**Comment by cppforlife** [comment]
As of several releases ago CLI generates ephemeral ssh keys every time `bosh ssh` command is executed.
