### ISSUE TITLE
bosh cck restarts jobs in a (random?) order instead of the order of the deployment spec

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#417]
Just when you might be most stressed - your entire production system has been deleted by someone with dashboard access; or you're preparing a screencast for PlatformCF - bosh cck brings back VMs one at a time.

```
Applying problem resolutions
  missing_vm 21: Recreate VM using last known apply spec (00:01:32)                                 
  missing_vm 27: Recreate VM using last known apply spec (00:01:32)                                 
  missing_vm 24: Recreate VM using last known apply spec (00:01:52)                                 
  missing_vm 26: Recreate VM using last known apply spec (00:02:00)                                 
  missing_vm 20: Recreate VM using last known apply spec (00:01:30)                                 
  missing_vm 23: Recreate VM using last known apply spec (00:01:39)                                 
missing_vm 18: Recreate VM using... |oooooooooooooo          | 6/10 00:10:16  ETA: 00:06:31         
```

I think it wants to torture me. It loves me. But the love hurts.

**Comment by cppforlife** [comment]
Closing. We are slowly converging to having bosh deploy --fix having ability to recover deployments in a irregular state. Ultimately we may even turn bosh cck into a command that just reports problems instead of allowing to interactively fix them.
