### ISSUE TITLE
bosh create release [--final] -d ../cf-release-pkg

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#427]
I want to allow cf-release (or any bosh release src project) to store the "final release" files (including config) into a different project. Currently, its not possible for anyone but the config/private.yml person to create final releases.

What I think it will look like is:

```
bosh create release [--final] -d ../cf-release-pkg
```

**Comment by dpb587-pivotal** [comment]
Since this issue has been quiet and there are going to be no more changes and releases to ruby cli, I'm closing this. Feel free to continue discussion on a new issue in [bosh-cli](https://github.com/cloudfoundry/bosh-cli) if this is still a feature of interest.
