### ISSUE TITLE
Spiff templates for microbosh deployments for aws & openstack & vsphere

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#500]

**Comment by Zouuup** [comment]
@tsaleh any news on this?

**Comment by tjvman** [comment]
Closing - Microbosh has been deprecated for a while. If you're looking for a way to spin up initial directors, [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) uses [v2 CLI](https://github.com/cloudfoundry/bosh-cli) functionality to spin up a director, and has templates for AWS, vSphere, OpenStack (and more).
