### ISSUE TITLE
bosh micro deploy failed :create stemcell failed: Field entity is not optional:

### ISSUE THREAD

**Issue by heei3k** [cloudfoundry/bosh#523]
my micro_bosh.yml is as below:

---

name: micro01
network:
  ip: 172.16.71.132     #define ip for micro BOSH
  netmask: 255.255.255.0
  gateway: 172.16.71.1
  dns:
- 172.16.1.90
- 10.135.12.101
  cloud_properties:
    name: VM Network
  resources:
  persistent_disk: 16384
  cloud_properties:
    ram: 4096
    disk: 16384
    cpu: 2
  cloud:
  plugin: vsphere
  properties:
    agent:
      ntp:
       - time.windows.com
       - ntp02.las01.emcatmos.com
    vcenters:
      - host: 172.16.71.197             # ip address of vCenter 
        user: root              #user of vCenter
        password: 1234qwer
        datacenters:
          - name: datacenter    #name of the datacenter you created
            vm_folder: vm_folder        #folder for vms
            template_folder: template_folder    #folder for templates
            disk_path: bosh_deployer            #disk path where VMs are stored.
            datastore_pattern: datastore\*       #name of a datastore or some regular expression matching the datastore name.
            persistent_datastore_pattern: datastore\*    #name of a datastore or some regular expression matching the persistent datastore
            allow_mixed_datastores: true     #true if two datastore patterns are the same
            clusters:
              - test    #name of your cluster in your datacenter

I use ruby 1.9.3-p448 to deploy micro_bosh. The error message is as below:
# bosh micro deploy ~/stemcells/latest-micro-bosh-stemcell-vsphere.tgz

Deploying new micro BOSH instance `micro01/micro_bosh.yml' to`https://172.16.71.132:25555' (type 'yes' to continue): yes

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK
## Stemcell info

Name:    micro-bosh-stemcell
Version: 912

Deploy Micro BOSH
Unpacking stemcell                  |                        | 0/11 00:00:06  ETA: --:--:--at depth 0 - 18: self signed certificate
  unpacking stemcell (00:00:06)  
Uploading stemcell                  |oo                      | 1/11 00:00:15  ETA: 00:00:52create stemcell failed: Field entity is not optional:
/root/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/bosh_vsphere_cpi-1.1975.0/lib/ruby_vim_sdk/soap/serializer.rb:39:in `serialize'

What's wrong with it,is there any other prerequisites? I follow most of steps of :
 http://docs.cloudfoundry.com/docs/running/deployingcf/vsphere/deploying_micro_bosh.html

**Comment by fzhou-pivotal** [comment]
I met same problem, have it been fixed?
