### ISSUE TITLE
[bosh-stemcell] berkshelf failing with vagrant 1.5 - workaround? migrate to something else?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#541]
vagrant 1.5 is desirable for its ability to rsync & re-rsync to an AWS VM. But berkshelf plugin isn't compatible https://github.com/berkshelf/vagrant-berkshelf/issues/156

Is there a known workaround to use berkshelf PRs? (perhaps https://github.com/berkshelf/vagrant-berkshelf/pull/158)

Perhaps switch to librarian-chef? Other options?

Anything working for anyone else?

**Comment by cppforlife** [comment]
Replaced all that complicated chef stuff with few lines of bash: https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/Vagrantfile#L91-L95
