### ISSUE TITLE
Port 111 (portmap/rpc) is open and (seemingly) unneeded in stemcell

### ISSUE THREAD

**Issue by ryantang** [cloudfoundry/bosh#584]
During some exploration today, @dsabeti  and I discovered that port 111 is open in a bare (no job, just excess resource pool) stemcell.  We discovered this in an ubuntu/vSphere environment.  We turned it off on one VM (a DEA job) in that environment as saw no negative consequences.

I did not see any service inherent to the stemcell, such as NFS, that obviously needed portmap turned on by default.  Security best practices state that unused ports should be closed.  Perhaps there's a reason for this open port and I'm not aware of it?

**Comment by ajackson** [comment]
@cppforlife any update on locking down rpcinfo on the stemcell?   The tracker story seems to have been deleted / moved.

**Comment by dpb587-pivotal** [comment]
Story [#152339107](https://www.pivotaltracker.com/story/show/152339107) as part of Xenial stemcell work (won't be applied to ubuntu-trusty).

**Comment by cppforlife** [comment]
xenial v40 is on bosh.io.

**Comment by ryantang** [comment]
Thank you @cppforlife.
