### ISSUE TITLE
Error creating vms in openstack - Multiple security_group matches found 

### ISSUE THREAD

**Issue by neilAitken** [cloudfoundry/bosh#644]
Hi,

We noticed an issue when installing CF to 2 different tenants in the same openstack instance.  Both instances have security groups called 'bosh' which results in a computeFault when bosh tries to create vms:

```
{:body=>"{\"computeFault\": {\"message\": \"The server has either erred or is incapable of performing the requested operation.\", \"code\": 500}}", :headers=>{"Content-Length"=>"128", "Content-Type"=>"application/json; charset=UTF-8", "X-Compute-Request-Id"=>"req-80748518-fe4e-4207-a110-61f3f14993ac", "Date"=>"Wed, 27 Aug 2014 19:51:37 GMT"}, :status=>500, :remote_ip=>"***********"}, @body="{\"computeFault\": {\"message\": \"The server has either erred or is incapable of performing the requested operation.\", \"code\": 500}}", @headers={"Content-Length"=>"128", "Content-Type"=>"application/json; charset=UTF-8", "X-Compute-Request-Id"=>"req-80748518-fe4e-4207-a110-61f3f14993ac", "Date"=>"Wed, 27 Aug 2014 19:51:37 GMT"}, @status=500, @remote_ip="************"> (Excon::Errors::InternalServerError) 
```

Looking in the nova logs, this seems to be due to the ambiguous match on the security group, with the suggested workaround of using ID rather name:

```
2014-08-27 15:51:37.725 8834 ERROR nova.network.security_group.neutron_driver [req-80748518-fe4e-4207-a110-61f3f14993ac 258f961864a94ee9bea44a918909fbef c653d1b70f6045f4a4335c6ff2c77eb5] Neutron Error: Multiple security_group matches found for name 'bosh', use an ID to be more specific.
2014-08-27 15:51:37.727 8834 ERROR nova.api.openstack [req-80748518-fe4e-4207-a110-61f3f14993ac 258f961864a94ee9bea44a918909fbef c653d1b70f6045f4a4335c6ff2c77eb5] Caught error: Multiple security_group matches found for name 'bosh', use an ID to be more specific.
```

For now we're working around this by having unique group names across the open stack instance. Is it possible to tweak the openstack api call used by bosh to use ID rather than name as suggested?

Env info:
BOSH version: 1.2697.0
Stemcell: bosh-openstack-kvm-ubuntu-lucid-go_agent version 2641

thanks,
Neil

**Comment by ronakbanka** [comment]
@neilAitken  Just curious if the user in microbosh deployment cloud property is member or admin of both the tenants (Projects)??

**Comment by dpb587-pivotal** [comment]
Closing - if this is still an issue or you're interested in seeing this change, please feel free to send a PR to the [bosh-openstack-cpi-release repo](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release).
