### ISSUE TITLE
bosh aws create failure

### ISSUE THREAD

**Issue by aladyzhensky** [cloudfoundry/bosh#646]
i'm running bosh aws create command and getting the following output. i've re-run the command multiple times with the same outcome. Please investigate

Regards,
Aleksandr

aladyzhensky$ bosh aws create
Executing migration CreateVpc
creating internet gateway
creating security groups: open, bosh, bat, cf, web
creating subnets: bosh1, bosh_rds1, cf_elb1, cf_rds1, services_rds1,
cf1, services1, bosh_rds2, cf_elb2, cf_rds2, services_rds2
  Making subnet bosh1 10.10.0.0/24:
  Making subnet bosh_rds1 10.10.1.0/24:
  Making subnet cf_elb1 10.10.2.0/24:
  Making subnet cf_rds1 10.10.3.0/24:
  Making subnet services_rds1 10.10.8.0/21:
  Making subnet cf1 10.10.16.0/20:
  Making subnet services1 10.10.32.0/20:
  Making subnet bosh_rds2 10.10.65.0/24:
  Making subnet cf_elb2 10.10.66.0/24:
  Making subnet cf_rds2 10.10.67.0/24:
  Making subnet services_rds2 10.10.72.0/21:
details in S3 receipt: aws_vpc_receipt and file: aws_vpc_receipt.yml
/Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/aws-sdk-1.44.0/lib/aws/core/client.rb:375:in
`return_or_raise': The security group 'sg-0add0e60' does not exist in
VPC 'vpc-d38f3ab6' (AWS::EC2::Errors::InvalidGroup::NotFound)
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/aws-sdk-1.44.0/lib/aws/core/client.rb:476:in
`client_request'
    from (eval):3:in `run_instances'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/aws-sdk-1.44.0/lib/aws/ec2/instance_collection.rb:303:in
`create'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/ec2.rb:71:in
`create_instance'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/ec2.rb:88:in
`create_nat_instance'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/vpc.rb:133:in
`block in create_nat_instances'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/vpc.rb:132:in
`each'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/vpc.rb:132:in
`create_nat_instances'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/migrations/20130412004642_create_vpc.rb:27:in
`execute'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/migration.rb:21:in
`run'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/migrator.rb:75:in
`block in run_migrations'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/migrator.rb:74:in
`each'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/migrator.rb:74:in
`run_migrations'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh_cli_plugin_aws/migrator.rb:13:in
`migrate'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli_plugin_aws-1.2697.0/lib/bosh/cli/commands/aws.rb:130:in
`create'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli-1.2697.0/lib/cli/command_handler.rb:57:in
`run'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli-1.2697.0/lib/cli/runner.rb:56:in
`run'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli-1.2697.0/lib/cli/runner.rb:16:in
`run'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/gems/bosh_cli-1.2697.0/bin/bosh:7:in
`<top (required)>'
    from /Users/aladyzhensky/.rvm/rubies/ruby-1.9.3-p484/bin/bosh:23:in `load'
    from /Users/aladyzhensky/.rvm/rubies/ruby-1.9.3-p484/bin/bosh:23:in `<main>'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/bin/ruby_executable_hooks:15:in
`eval'
    from /Users/aladyzhensky/.rvm/gems/ruby-1.9.3-p484@global/bin/ruby_executable_hooks:15:in
`<main>'

**Comment by cppforlife** [comment]
`bosh aws *` commands were deprecated a few months ago and are not recommended for use.
