### ISSUE TITLE
getting waiting for agent while deploy bosh 

### ISSUE THREAD

**Issue by jai11** [cloudfoundry/bosh#660]
HI , I am using bosh micro to create bosh VM on AWS.

I done all the re-search and change allot stem cell . each one got stuck at same point .

I also tried with bootstrap and it also stuck at same point-

Please find the console output-

root@2d62e55:/microbosh/deployments# bosh micro deploy --update ami-979dc6fe
Updating mybosh/micro_bosh.yml' tohttps://54.210.142.162:25555' (type 'yes' to continue): yes
Will deploy due to stemcell changes
Started prepare for update
Started prepare for update > Preserving stemcell. Done (00:00:00)

Started deploy micro bosh
Started deploy micro bosh > Using existing stemcell. Done (00:00:00)
Started deploy micro bosh > Creating VM from ami-979dc6fe
. Done (00:00:49)
Started deploy micro bosh > Waiting for the agent
Unable to connect to Bosh agent. Check logs for more details.

Output from bootstrap:-

Use bundle show [gemname] to see where a bundled gem is installed.
bundle exec bosh micro deployment firstbosh
fatal: Not a git repository (or any of the parent directories): .git
Deployment set to '/.microbosh/deployments/firstbosh/micro_bosh.yml'
bundle exec bosh -n micro deploy --update-if-exists ami-7017b018
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Started deploy micro bosh
Started deploy micro bosh > Using existing stemcell. Done (00:00:00)
Started deploy micro bosh > Creating VM from ami-7017b018. Done (00:00:30)
Started deploy micro bosh > Waiting for the agentUnable to connect to Bosh agent. Check logs for more details.
/usr/local/lib/ruby/1.9.1/rake/file_utils.rb:53:in block in create_shell_runner': Command failed with status (1): [bundle exec bosh -n micro deploy --update-...](RuntimeError) from /usr/local/lib/ruby/1.9.1/rake/file_utils.rb:45:incall'
from /usr/local/lib/ruby/1.9.1/rake/file_utils.rb:45:in sh' from /usr/local/lib/ruby/gems/1.9.1/gems/bosh-bootstrap-0.13.2/lib/bosh-bootstrap/cli/helpers/bundle.rb:11:inblock in bundle'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.6.5/lib/bundler.rb:235:in block in with_clean_env' from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.6.5/lib/bundler.rb:222:inwith_original_env'
from /usr/local/lib/ruby/gems/1.9.1/gems/bundler-1.6.5/lib/bundler.rb:228:in `with_clean_env'
from /usr/local/lib/ruby/gems/1.9.1/gems/bosh-bootstrap-0.13.2/lib/bosh-bootstrap/cli/helpers/bun

logs:-

I, [2014-09-27T03:14:52.975455 #2252] INFO -- : HTTP server is starting on port 25888...
E, [2014-09-27T03:14:53.420720 #2252] ERROR -- : Sinatra::NotFound
D, [2014-09-27T03:15:42.000862 #2252] DEBUG -- : (0.000234s) PRAGMA foreign_keys = 1
D, [2014-09-27T03:15:42.001000 #2252] DEBUG -- : (0.000032s) PRAGMA case_sensitive_like = 1
D, [2014-09-27T03:15:42.001398 #2252] DEBUG -- : (0.000296s) PRAGMA table_info('registry_instances')
D, [2014-09-27T03:15:42.002487 #2252] DEBUG -- : (0.000207s) SELECT \* FROM registry_instances WHERE (instance_id = 'i-54d84bb9') LIMIT 1
D, [2014-09-27T03:15:42.003390 #2252] DEBUG -- : (0.000125s) SELECT COUNT(*) AS 'count' FROM registry_instances WHERE (instance_id = 'i-54d84bb9') LIMIT 1
D, [2014-09-27T03:15:42.003879 #2252] DEBUG -- : (0.000072s) SELECT sqlite_version() LIMIT 1
D, [2014-09-27T03:15:42.004034 #2252] DEBUG -- : (0.000060s) BEGIN
D, [2014-09-27T03:15:42.004526 #2252] DEBUG -- : (0.000238s) INSERT INTO registry_instances (instance_id, settings) VALUES ('i-54d84bb9', '{"vm":{"name":"vm-d1930349-1b16-4c38-aee0-3f667247420f"},"agent_id":"bm-b92fb0f6-a42a-4a2e-bae7-0c2c59e2c519","networks":{"bosh":{"cloud_properties":{},"netmask":null,"gateway":null,"ip":null,"dns":null,"type":"dynamic","default":["dns","gateway"]},"vip":{"ip":"54.210.142.162","type":"vip","cloud_properties":{}}},"disks":{"system":"/dev/sda1","ephemeral":"/dev/sdb","persistent":{}},"env":{"bosh":{"password":null}},"ntp":[],"blobstore":{"provider":"local","options":{"blobstore_path":"/var/vcap/micro_bosh/data/cache"}},"mbus":"https://vcap:b00tstrap@0.0.0.0:6868"}')
D, [2014-09-27T03:15:42.004971 #2252] DEBUG -- : (0.000121s) SELECT \* FROM registry_instances WHERE (id = 1) LIMIT 1
D, [2014-09-27T03:15:42.007517 #2252] DEBUG -- : (0.002390s) COMMIT
D, [2014-09-27T03:18:57.866806 #2252] DEBUG -- : (0.000314s) SELECT \* FROM registry_instances WHERE (instance_id = 'i-54d84bb9') LIMIT 1
I, [2014-09-27T03:32:36.222613 #2252] INFO -- : BOSH Registry shutting down...

Can you please help me.

And as per the documents they selected non-vpc but now AWS by default gives VPC only no option for non-vpc.

Is this for i am getting stuck every time at same point "waiting for the agent"

**Comment by Dulanjalie** [comment]
Hi all,
I am using MicroBOSH and i am hitting the same issue. I am using the latest stemcells and my security group configs are correct. 

cfoundry@c-foundry:~/micro-deployment$ bosh micro deploy test/light-bosh-stemcell-2986-aws-xen-hvm-ubuntu-trusty-go_agent.tgz

No `bosh-deployments.yml` file found in current directory.

Conventionally, `bosh-deployments.yml` should be saved in /home/cfoundry.
Is /home/cfoundry/micro-deployment a directory where you can save state? (type 'yes' to continue): yes
Deploying new micro BOSH instance `manifest.yml' to `https://52.7.75.44:25555' (type 'yes' to continue): yes

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-hvm-ubuntu-trusty-go_agent
Version: 2986

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:00)
  Started deploy micro bosh > Uploading stemcell. Done (00:00:10)
  Started deploy micro bosh > Creating VM from ami-3742b55c light. Done (00:00:35)
  Started deploy micro bosh > Waiting for the agent

**Comment by tekknikk** [comment]
i ran into the same "waiting for agent" problem and found it consistent across many 3012 builds for AWS. 

Seems to be an issue with the stemcell.

I was succesful when using an older 3000 build stemcell @ https://d26ekeud912fhb.cloudfront.net/bosh-stemcell/aws/light-bosh-stemcell-3000-aws-xen-ubuntu-trusty-go_agent.tgz
