### ISSUE TITLE
Bosh deploy cf: Error 100: undefined method `[]' for false:FalseClass on bosh-template-1.2732.0 property_helper.rb

### ISSUE THREAD

**Issue by damianofalcioni** [cloudfoundry/bosh#669]
Hi,
I'm trying to deploy cf 188 using bosh  and stemcell bosh-stemcell-2732-openstack-kvm-ubuntu-trusty-go_agent.tgz

when I run bosh deploy with my cf manifest i got the followig error:
...
Started preparing deployment > Binding properties. Failed: undefined method `[]' for false:FalseClass (00:00:00)
Error 100: undefined method`[]' for false:FalseClass
For a more detailed error report, run: bosh task 3 --debug
...

Executing bosh task with the debug tag it return the error visible in the log file linked (the manifest used is inside the log).

http://pastebin.com/a3vag6UG

Any solution?
Maybe the code in the stemcell has not be tested with ruby 2.1.0 present inside the stemcell?
Thanks

**Comment by alfredcs** [comment]
Changed diego: false --> diego: disabled resolved the same issue occurred to me.
