### ISSUE TITLE
BOSH stemcell building incompatible with RHEL6

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#670]
Since change [7f2f0f0](https://github.wdf.sap.corp/cloudfoundry/mo-bosh/commit/7f2f0f0affbc2044254bd63c25d2625a0c5801fd) stemcell building relies on the existence of `.git/modules` which was only introduced in git 1.7.8 (see [changelog](https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.8.txt)).

While it is true that this version was released quite some time ago, distributions such as RHEL6, CentOS6, and Fedora20 still do not provide a version newer than 1.7.1 in their official repos and unfortunately RHEL6 is still pretty common.

The Vagrantfile is relying there on git internals (namely the contents and structure of the .git folder), which are specifically not declared as API and are likely to break as it did with moving from 1.7.7 to 1.7.8.

I'm not sure yet what would be a better way to achieve the same result without relying on the internals of the .git folder, but at least I think we should update the requirements to make clear why it isn't working on some machines.

**Comment by dpb587-pivotal** [comment]
Closing - no longer an issue.
