### ISSUE TITLE
"bosh backup"   miss some blobstore packages.

### ISSUE THREAD

**Issue by aalbanes** [cloudfoundry/bosh#716]
Running "bosh backup" command, I got a tarball that  is not containing  blobstore objects included into  "rendered_templates_archives" table.  I also noticed that Director cleaner is not properly managing some exceptions.

Below  some details: 

The scenario we run is the following:
- We  restored the  blobstore content (from scratch) using the tgz obtained via "bosh backup",
- we  run a "bosh deploy"  

This raised the following Director Error:

```
 Could not delete object, 404/<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

/var/vcap/packages/director/gem_home/gems/blobstore_client-1.2549.0/lib/blobstore_client/dav_blobstore_client.rb:57:in `delete_object'
/var/vcap/packages/director/gem_home/gems/blobstore_client-1.2549.0/lib/blobstore_client/base.rb:69:in `delete'
/var/vcap/packages/director/gem_home/gems/bosh-director-1.2549.0/lib/bosh/director/rendered_job_templates_cleaner.rb:10:in `block in clean' 
```

  "bosh backup" need to include also the rendered_templates_archives object
and   cleaner  should manage the exception as well.

Thx Angelo

**Comment by cppforlife** [comment]
Fixed in https://www.pivotaltracker.com/story/show/101724116.
