### ISSUE TITLE
Upgrade nokogiri to v1.6.5

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#719]
To support traveling-ruby (for the traveling-bosh / http://bosh-cli.cfapps.io/ project), we need to upgrade to nokogiri 1.6.5 (its the shipped native version http://traveling-ruby.s3-us-west-2.amazonaws.com/list.html)

Todo items:

* [x] create PR to patch foodcritic https://github.com/acrmp/foodcritic/pull/291
* [x] foodcritic PR accepted; new gem not released yet
* [ ] foodcritic new version released
* [x] create PR for vcloud cpi https://github.com/vchs/bosh_vcloud_cpi/pull/12
* [ ] vcloud PR accepted and new version released
* [ ] PR for BOSH to use new gems (https://github.com/cloudfoundry/bosh/blob/master/bosh_vsphere_cpi/bosh_vsphere_cpi.gemspec#L31) + new jenkins_api_client

**Comment by dpb587-pivotal** [comment]
Closing - nokogiri was upgraded past 1.6.5 to 1.6.6.2 in [April 2015](https://github.com/cloudfoundry/bosh/commit/39c6cdf527f5eb87d4fced499c4b4c2d21996cf7).
