### ISSUE TITLE
Why is vcloud cpi locked to 0.7.2?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#721]
In the gemspec it is locked to 0.7.2 with a link to https://www.pivotaltracker.com/n/projects/956238/stories/84406944

But https://www.pivotaltracker.com/n/projects/956238/stories/84406944 doesn't explain at all why.

In https://github.com/cloudfoundry/bosh/issues/719 we'll need to bump vcloud cpi to get newer nokogiri.

**Comment by dpb587-pivotal** [comment]
Closing - CPIs have been externalized. Nowadays, CPI locked versions in Gemfile.lock are bumped only when mandatory for legacy requirements.
