### ISSUE TITLE
bosh deploy fails with error: undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by pradyutsarma** [cloudfoundry/bosh#723]
Hi,

In the process of deploying a bosh release using the command "bosh deploy" after uploading the release along with the manifest, I get the error stack below,

```
-------------------------------------------------------------------

Processing deployment manifest
------------------------------
Getting deployment properties from director...
Unable to get properties list from director, trying without it...
Compiling deployment manifest...
/usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:215:in `block in latest_release_versions': undefined method `[]' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:206:in `each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:206:in `inject'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:206:in `latest_release_versions'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:229:in `block in resolve_release_aliases'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:227:in `each'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:227:in `resolve_release_aliases'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/deployment_helper.rb:59:in `prepare_deployment_manifest'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/commands/deployment.rb:90:in `perform'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/command_handler.rb:57:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:56:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:16:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/bosh_cli-1.2807.0/bin/bosh:7:in `<top (required)>'
        from /usr/local/bin/bosh:23:in `load'
        from /usr/local/bin/bosh:23:in `<main>'
r
-------------------------------------------------------------------
```

My server runs ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux] as what ruby -v tells me.
Any idea if a different ruby version can fix this or some problem in any portion of my deployment.

Thanks and Regards,
Pradyut.

**Comment by asanramon** [comment]
Any resolution on this. I am getting this error now too. I just changed a couple of passwords on my deployment manifest. When I did bosh deploy, I get the errors above.

**Comment by drnic** [comment]
Which bosh release were you working upon?​

**Comment by cppforlife** [comment]
@asanramon what is the output of `bosh releases`?

**Comment by asanramon** [comment]
Hi drnic/cppforlife,

For some reason I am able to deploy bosh now from microbosh. I didn't change anything on my manifest. The only reason I can think of that cause the issue was that someone else was deploying something when I deploy bosh.

Off topic, is it possible to enable resurrector on microbosh? All our deployments are deployed through microbosh, and we would like to automatically rebuild instances when it goes down.

Thanks for all the reply.

**Comment by drnic** [comment]
There is a page on the resurrector in docs.cloudfoundry.org and how to enable/configure it.

**Comment by dpb587-pivotal** [comment]
Closing - this scenario now shows a more descriptive error as of [v255.4](https://github.com/cloudfoundry/bosh/releases/tag/stable-3213) via [#114891805](https://www.pivotaltracker.com/n/projects/956238/stories/114891805).
