### ISSUE TITLE
When remote upload fails, it leaves temp files in /var/vcap/data/tmp

### ISSUE THREAD

**Issue by Holek** [cloudfoundry/bosh#724]
When remote upload fails, it leaves temp files in /var/vcap/data/tmp, which doesn't get cleaned and might cause subsequent uploads to fail on smaller disks. This has happened for me due to AWS connectivity issues, and I think BOSH should be clever enough to recover from that and not leave any temporary files around.

Essentially, when [`ReleaseInvalidArchive`](https://github.com/cloudfoundry/bosh/blob/2840387d687a44569edd9cdc2e49ecba129634b8/bosh-director/lib/bosh/director/jobs/update_release.rb#L88) is raised temp directory should be cleaned.

**Comment by cppforlife** [comment]
Story filed: https://www.pivotaltracker.com/story/show/85445708

**Comment by dpb587-pivotal** [comment]
Closing - fixed via 1e0d1c12a92346c6edf46368563aa31e5fb7f3a5.
