### ISSUE TITLE
The 'persistent_disk_cloud_properties' seems to be breaking the bosh_vcloud_cpi (0.7.1)

### ISSUE THREAD

**Issue by bahatelos** [cloudfoundry/bosh#727]
Hello,

I tried deploying micro Bosh (cli v 2788)  on vCloud 5.1.
I tried with stemcells:
bosh-stemcell-2811-vcloud-esxi-ubuntu-trusty-go_agent
and
bosh-stemcell-2788-vsphere-esxi-ubuntu-trusty-go_agent

The deployment is failing on creating the persistent disk.

The output looks a lot like this:

Name:    bosh-vcloud-esxi-ubuntu-trusty-go_agent
Version: 2811

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:08)
  Started deploy micro bosh > Uploading stemcell. Done (00:05:20)
  Started deploy micro bosh > Creating VM from urn:vcloud:catalogitem:f7ad8a53-1ef3-479c-8233-6fc136391b4c. Done (00:04:42)
  Started deploy micro bosh > Waiting for the agent. Done (00:00:38)
  Started deploy micro bosh > Updating persistent disk
  Started deploy micro bosh > Create diskUsage: micro deploy [<stemcell>] [--update] [--update-if-exists]

Following the flow of the code I came across the create_disk function in instance_manager.rb
(https://github.com/cloudfoundry/bosh/blob/stable-2811/bosh_cli_plugin_micro/lib/bosh/deployer/instance_manager.rb
Line: 282)

def create_disk
      step 'Create disk' do
        size = config.resources['persistent_disk']
        state.disk_cid = cloud.create_disk(size, persistent_disk_cloud_properties, state.vm_cid)
        save_state
      end
    end

    def persistent_disk_cloud_properties
      config.resources.fetch('persistent_disk_cloud_properties', {})
    end

It looks like the 'persistent_disk_cloud_properties' was introduced as part of:
https://github.com/cloudfoundry/bosh/pull/663

However, i think that the bosh_vcloud_cpi still only expects 2 arguments for the cloud.create_disk.

I guess the right approach would be for the bosh_vcloud_cpi to be updated to ignore this parameter?

**Comment by bosh-ci-push-pull** [comment]
which version of bosh_vcloud_cpi is installed on your machine. we have
fixed this problem long time ago:
https://github.com/cloudfoundry/bosh/blob/master/bosh_cli_plugin_micro/bosh_cli_plugin_micro.gemspec#L32
by locking down to exact version of bosh_vcloud_cpi

**Comment by bahatelos** [comment]
Hello,

Indeed the problem was the bosh_cloud_cpi version, which was 0.7.1.
That is the default cpi for bosh 2788.

I can confirm that Bosh 2811 comes with bosh_cloud_cpi version 0.7.2, which works as expected.

The issue can be closed/cancelled.

Thanks for your help!
