### ISSUE TITLE
[bosh micro][aws] Only preserves stemcell if stemcell_cid and stemcell_name are both the AMI reference

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#729]
[referencing bosh-deployments.yml]

We discovered today in training that only if `stemcell_cid` and `stemcell_name` are both the same AMI label can you run `bosh micro deploy ami-123456 --update` successfully.

If `bosh-deployments.yml` has different values, such as:

```yaml
---
instances:
- :id: 1
  :name: bosh-vpc-f5ba1c90
  :uuid: bm-49f6edf2-7bb1-4e1e-aae8-1b99ebce11f7
  :stemcell_cid: ami-8185dab1
  :stemcell_name: bosh-stemcell-2811-aws-xen-ubuntu-trusty-go_agent
```

Then you cannot run `bosh micro deploy ami-123456 --update` successfully. Tragically, it deletes the ami and then fails to reuse it.

Preserving stemcells should be the default. Recreating them isn't fast and fun :)

I understand bosh-micro-cli is the future and this issue might never be prioritized by BOSH core. I might fix it myself. This weekend. If you're reading this and weeks have pasted, I guess I didn't :)

**Comment by cppforlife** [comment]
Using `bosh micro deploy <AMI>` is not recommended since it bypasses proper stemcell packaging (i.e. light stemcell). We have decided to now implement that in the new bosh micro cli. Does this happen if light stemcell is used?

**Comment by drnic** [comment]
Light stemcells only published for us-east-1.


Is there a tool for promoting a us-west-2 AMI into a light stemcell?

**Comment by bosh-ci-push-pull** [comment]
That sounds like a missing bit here. We currently do not have that tool.
Which regions would you be more interested in or do you want light
stemcells for all regions?

**Comment by drnic** [comment]
us-west-2 is what we use for AWS clients and for training

**Comment by cppforlife** [comment]
Closing in favor of using bosh-init. It correctly reuses stemcells.
