### ISSUE TITLE
bosh deployment state change should check with content-length with 0 rather than nil

### ISSUE THREAD

**Issue by datianshi** [cloudfoundry/bosh#737]
https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L69

The code above would not accept a "Content-Length:0" Header with empty body. However I think it is standard and most user agents would add that header for empty body with a PUT request. 

We found that when working automation of golang work with bosh director rest endpoint. The curl works fine, cause it does not automatically include "Content-Length:0", while in golang http package, it added that up header automatically in very low level.

**Comment by dpb587-pivotal** [comment]
Closing - fixed via #742.
