### ISSUE TITLE
Automatically scale back the compilation VMs total if CPI fails to get VMs

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#738]
```
$ bosh deploy
....
   Failed compiling packages > rootfs_lucid64/ac77386888037b26f4dd2551c633947a112b9313: Your quota allows for 0 more running instance(s). You requested at least 1 (00:00:01)
```

The `bosh deploy` eventually fails. There is no reason for it to stop the deployment.

In this circumstance, perhaps ignore the `compilation.workers` number and continue the deployment using the available pool of compilation workers.

**Comment by cppforlife** [comment]
I am concerned about cases when IaaS fails to create extra VMs and Director would decide to compile everything on a single compilation VM which might take forever. Thoughts?

**Comment by drnic** [comment]
Ideas on an algorithm: 


1. grow a pool of compilation workers upto the number in the manifest

2. If the size is 0 then there's a major issue (creds, networking, etc) and stop

3. If the size is 1+ then compile packages with the pool.

**Comment by drnic** [comment]
If you only have one compilation VM then that's the limit isn't it? Is there a reason to stop because there's only one?

**Comment by cppforlife** [comment]
I meant something like this:
- user requests 6 compilation VMs to compile CF (workers: 6)
- Director only gets 1 compilation VM

**Comment by drnic** [comment]
Is that a problem?

**Comment by drnic** [comment]
The user request is a maximum number. The reality might be I can't have that (quotas hit us all)

**Comment by bosh-ci-push-pull** [comment]
I'll think more about it but it sounds like a thing we can definitely fix.

**Comment by drnic** [comment]
xoxo

**Comment by mfine30** [comment]
We're not actively planning to address this issue as it hasn't come up as a major priority. If it continues to be a problem and you'd like to continue the conversation feel free to reopen this issue.
