### ISSUE TITLE
BOSH Templates does not preserve file permission

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#741]
I have a script that is +x in templates and bosh doesn't preserve this when copying template

**Comment by karlkfi** [comment]
That's correct. The bosh director assumes all templates are erb templates and renders them with ruby. IIRC, the bosh agent, when installing the rendered templates, makes any under 'bin/' executable (+x).

**Comment by longnguyen11288** [comment]
so there is no way to preserve this if it's not in bin/?

**Comment by longnguyen11288** [comment]
Actually this is good for me to know. Thanks @karlkfi
