### ISSUE TITLE
bosh aws create attempts (and fails) to delete default dhcp options set

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/bosh#752]
`bosh aws create` fails with:

```
The dhcpOptions 'dopt-6d28ce08' has dependencies and cannot be deleted.
```

I got it to succeed by commenting out [Bosh.Aws.VPC#create_dhcp_options, line 171](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli_plugin_aws/lib/bosh_cli_plugin_aws/vpc.rb#L171). Attempting to delete the default DHCP options set in AWS console gives following error:

```
We could not delete the following DHCP option set (dopt-6d28ce08)

The dhcpOptions 'dopt-6d28ce08' has dependencies and cannot be deleted.
```

This is a new AWS account, created today.

**Comment by dreammonger** [comment]
Commenting line 171 in vpc.rb solved the problem for me. Thanks a lot.

**Comment by cerdmann** [comment]
I needed to do this as well.

**Comment by bwasmith** [comment]
+1 tyvm

**Comment by gibbsoft** [comment]
I also hit this bug.  Thanks for the workaround.

**Comment by jakubincloud** [comment]
Thanks for the issue. I hope workaround can be pushed to production

**Comment by dignajar** [comment]
I hit the bug too.. commented the line and is work now..

**Comment by dpb587-pivotal** [comment]
Closing - `bosh aws *` commands are no longer supported. Some of this work is functionality is picked up by [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader/tree/develop) - please feel free to give that project a try.

**Comment by eitansuez** [comment]
interesting. does this imply that the official cloudfoundry docs are stale?
http://docs.cloudfoundry.org/deploying/aws/setup_aws.html

**Comment by biolounge** [comment]
Its seems like this change havent pushed to production yet.

Still getting the error:
_/var/lib/gems/2.3.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise': The dhcpOptions 'dopt-2f97754b' has dependencies and cannot be deleted. (AWS::EC2::Errors::DependencyViolation)
	from /var/lib/gems/2.3.0/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `delete_dhcp_options'_

**Comment by jsilberm** [comment]
Is there a workaround, please?

**Comment by rhuiser** [comment]
Dead end... deployment fails later on with MySQL error: 

```
.rvm/gems/ruby-2.2.2/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:375:in `return_or_raise': Cannot find version 5.5.40a for mysql (AWS::RDS::Errors::InvalidParameterCombination)
	from /Users/robinh/.rvm/gems/ruby-2.2.2/gems/aws-sdk-v1-1.60.2/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `create_db_instance'

```
