### ISSUE TITLE
HVM support for light-bosh in other regions

### ISSUE THREAD

**Issue by longnguyen11288** [cloudfoundry/bosh#762]
Can we have HVM support for light bosh in all other regions and not just us-east-1?

**Comment by longnguyen11288** [comment]
Or maybe add bosh stemcell for hvm

**Comment by cppforlife** [comment]
I've prioritized a story this week to start doing so: https://www.pivotaltracker.com/story/show/89044786

**Comment by longnguyen11288** [comment]
thanks Dmitriy!

**Comment by longnguyen11288** [comment]
Any status branch wip-cm-89044786-light-stemcells-for-everyone ?

**Comment by bosh-ci-push-pull** [comment]
We had a hiccup in our pipeline but I expect it to be resolved
today/tomorrow.

**Comment by cppforlife** [comment]
As of 2941 light AWS stemcells are multi-region. Try it out!

**Comment by drnic** [comment]
BOOM!!

**Comment by longnguyen11288** [comment]
Thank you!
