### ISSUE TITLE
[Question | Stemcell] Can't build stemcell for ubuntu. 

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh#763]
Hey, all. 

I don't use Vagrant box to build stemcell, I do it on my own VM due several constrains. 

After I run `rake stemcell:build_os_image[ubuntu,trusty,$HOME/bosh-ubuntu-trusty-os-image.tgz]` tests on a stemcell are failed with an output:
```
rspec ./spec/os_image/ubuntu_trusty_spec.rb:199 # Ubuntu 14.04 OS image installed by system_kernel Package "linux-headers-3.13.0-45" should be installed
rspec ./spec/os_image/ubuntu_trusty_spec.rb:199 # Ubuntu 14.04 OS image installed by system_kernel Package "linux-headers-3.13.0-45-generic" should be installed
rspec ./spec/os_image/ubuntu_trusty_spec.rb:199 # Ubuntu 14.04 OS image installed by system_kernel Package "linux-image-3.13.0-45-generic" should be installed
rspec ./spec/os_image/ubuntu_trusty_spec.rb:199 # Ubuntu 14.04 OS image installed by system_kernel Package "linux-image-extra-3.13.0-45-generic" should be installed
rake aborted!
Command failed with status (1): [cd /home/cloud/bosh/bosh-stemcell; OS_IMAG...]
/home/cloud/bosh/bosh-dev/lib/bosh/dev/tasks/stemcell.rake:46:in `block (2 levels) in <top (required)>'
/home/cloud/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/cloud/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => stemcell:build_os_image
(See full trace by running task with --trace)
```
The failing test declares that there should be libraries with certain versions [link](https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/spec/os_image/ubuntu_trusty_spec.rb#L191-L202).
From a closer sight stemcell builder installs actual version of packages (afaik currently it is 3.13.0.40.47)  [link](https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/system_kernel/apply.sh#L13).

I want to ask why this dependencies are not declared in stemcell builder?

**Comment by mariash** [comment]
Hi @allomov, that is a good point. Currently the OS image builder is getting the latest linux headers. We are going to change the process so that it will specified which version to pull.

**Comment by allomov** [comment]
@mariash thank you for answer. are you going to include `.deb` files to this repo or just specify them in the stage script?

**Comment by cppforlife** [comment]
we will ask apt-get install to install specific version. (no deb files included)
