### ISSUE TITLE
[bosh_cli] RFE: Set "--no-color" by default by configuration

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudfoundry/bosh#769]
It would be very nice to be able to specify "`--no-color`" by configuration, if possible with an environment variable, as we can already define `BOSH_USER` and `BOSH_PASSWORD `.

**Comment by drnic** [comment]
If you're interested in adding support, I think
https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/config.rb
is a good place to start (+ an update to the specs + README)

**Comment by cyrille-leclerc** [comment]
Thanks @drnic, I'll try but I am completely new to Ruby and the learning curve has been stiff fore te moment :-)

Enhancing error message of the CLI may be an easier entry point for me.

Anyway, I'll try, thanks!

**Comment by cppforlife** [comment]
makes sense to make an ENV for it. e.g. BOSH_COLOR=false to make it consistent with cf cli?

**Comment by cyrille-leclerc** [comment]
@cppforlife this looks perfect.

**Comment by filefrog** [comment]
I put in pull request #975 for this.

**Comment by cppforlife** [comment]
In CLI 1.3122.0
