### ISSUE TITLE
vSphere CPI does not support dynamic or vip networks.

### ISSUE THREAD

**Issue by sigusro** [cloudfoundry/bosh#770]
Hello,

Is there an workaround to make vSphere to assign dynamic IPs in a CloudFoundry deployment with BOSH?
We have a DHCP based infrastructure and can't reserve an IP class from DHCP only for the actual test system where I want to test the Cloud Foundry.

Thank you,

**Comment by cppforlife** [comment]
Currently bosh-agent on vsphere stemcells is configured to do manual configuration; however, with recent changes to bosh-agent (stemcell 2865+) it might be possible to use dynamic network. I'm not sure though if micro CLI allows it. It would be awesome if you can confirm!

**Comment by sigusro** [comment]
It didn't worked since it require vApps Optin enabled and a pool of IPs assgined to host. stemcell 2865+ seems to support now dynamic IPs but with this limitation. Meantime I've managed to reserve some fixed IPs and I'll play with them.

**Comment by cppforlife** [comment]
Afaik you should just be able to put a dhcp server on your subnet without configuring anything in vsphere.

**Comment by cppforlife** [comment]
Closing. Feel free to reopen against https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release.
