### ISSUE TITLE
Why does BOSH not allow persistent disks > 1Tib?

### ISSUE THREAD

**Issue by julweber** [cloudfoundry/bosh#776]
Dear BOSH team,

is there a reason why BOSH does not allow persistent disks bigger than 1Tib for created VMs?

This is also documented in the test suite: 
https://github.com/cloudfoundry/bosh/blob/77a6987bcf40ac91ed211e7048cbd8b3fd134d44/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb#L405

We would like to be able to roll out even bigger persistent disks for our customers using BOSH.

Cheers,
Julian Weber

**Comment by cppforlife** [comment]
Probably at some point OpenStack was not happy with >1TB volumes or may be was flaky. Feel free to submit a PR to remove that check.

**Comment by julweber** [comment]
Thanks for the reply.

We will prepare and create a pull request concerning this topic.

Regards,
Julian Weber

--
anynines.com

**Comment by julweber** [comment]
The PR can be found here https://github.com/cloudfoundry/bosh/pull/785.

Cheers,
Julian
