### ISSUE TITLE
bosh cck --auto - recreate missing VMs; instead fails

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#779]
Upon bringing bosh-lite back to life, I need to run `bosh cck`. I'd like to be able to run `bosh cck --auto` - where it chooses to recreate all VMs automatically.

Instead I get the following error:

```
Applying resolutions...

Director task 55
  Started applying problem resolutions
  Started applying problem resolutions > missing_vm 38: no resolution. Failed: Cannot find `' resolution for `Bosh::Director::ProblemHandlers::MissingVM' (00:00:00)
  Started applying problem resolutions > missing_vm 45: no resolution. Failed: Cannot find `' resolution for `Bosh::Director::ProblemHandlers::MissingVM' (00:00:00)
  Started applying problem resolutions > missing_vm 35: no resolution. Failed: Cannot find `' resolution for `Bosh::Director::ProblemHandlers::MissingVM' (00:00:00)
...
```

**Comment by drnic** [comment]
A quick look at `cloudcheck.rb` and I can't quite figure out how the `--auto` feature is supposed to work. Sorry for no PR.

**Comment by cppforlife** [comment]
Agreed, --auto should recreate the vm by default. 

`auto_resolution` is what you are looking for the code e.g. https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/problem_handlers/unbound_instance_vm.rb#L8 so for missing vm it could be `auto_resolution: recreate_vm`

**Comment by cppforlife** [comment]
As of v2915 of stemcell, `bosh cck --auto` will recreate missing vms.

**Comment by drnic** [comment]
Awesome! Thanks!!
