### ISSUE TITLE
Support for Ruby 1.9.3 used in bosh has ended

### ISSUE THREAD

**Issue by jhellan** [cloudfoundry/bosh#780]
On 23 Feb 2015, www.ruby-lang.org announced that support for ruby 1.9.3 has ended. This means that there will bo no security fixes.

https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by cppforlife** [comment]
Is there a particular area of BOSH you are concerned about that uses 1.9? The Director runs on Ruby 2. The CLI currently supports 1.9, 2.x.

**Comment by jhellan** [comment]
On 23. mars 2015 17:25, Dmitriy Kalinin wrote:
>
> Is there a particular area of BOSH you are concerned about that uses 
> 1.9? The Director runs on Ruby 2. The CLI currently supports 1.9, 2.x.
>
stemcell_builder/stages/bosh_ruby/apply.sh installs ruby 1.9.3-p545 in 
the stemcell. Which you can
verify by ssh-ing in and typing 'ruby --version'.
vsphere_cpi_release also refers to ruby 1.9

Jon

**Comment by bosh-ci-push-pull** [comment]
- ruby installed on the stemcell will be pulled out (and is currently /
should not be used by anything outside of stemcell building)
- cpi releases will be updated as part of the "External CPIs" work

Thanks for looking out!

**Comment by blade2005** [comment]
In addition to this building cf-release fails (see https://github.com/cloudfoundry/cf-release/issues/1061 ) I had to uninstall bosh from 1.9.3 and install it on ruby 2.x and the problem went away. I would say that due to this issue bosh cli isn't fully working on 1.9.x

**Comment by dpb587-pivotal** [comment]
Closing - director runs on ruby 2.3.1 and stemcells no longer include any version of ruby.
