### ISSUE TITLE
Bosh - deregister instances fail in AWS shared vpc

### ISSUE THREAD

**Issue by penrod** [cloudfoundry/bosh#781]
When terminating instances from a CF deployment in AWS, Bosh pulls a list of load balancers from the vpc even if they are unrelated to the instances bosh is managing or the user bosh operates with does not have rights to the load balancer in the vpc. Bosh then will try and deregister the instance from the load balancer. Bosh will ignore the error if the instance does not exist on the load balancer, but it fails if it does not have access to the load balancer with the current user. 

Thoughts on adding the 'Access Denied' error to the ignore list so that the bosh deregister action will complete in this situation?

Location:
bosh_aws_cpi/lib/cloud/aws/instance.rb:96

**Comment by cppforlife** [comment]
Interesting. Are you saying that @elb.load_balancers [1] does not limit visibility of the LBs to the current user? If so that I guess makes sense to put that into ignore list. PR?

[1] https://github.com/cloudfoundry/bosh/blob/master/bosh_aws_cpi/lib/cloud/aws/instance.rb#L93

**Comment by cppforlife** [comment]
AWS CPI no longer deregisters instances from ELBs on termination but rather relies on AWS's behavior to automatically remove instances when they are terminated.
