### ISSUE TITLE
the third parameter of VmCreator.create should be resource_pool not compilation 

### ISSUE THREAD

**Issue by qingfuwang** [cloudfoundry/bosh#787]
https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/package_compiler.rb#L153

VmCreator.create(@deployment_plan.model, stemcell,
                            @compilation_resources, network_settings,
                            nil, @compilation_env)

It will eventually turn to cpi call  def create_vm(agent_id, stemcell_id, resource_pool, network_spec, disk_locality = nil, environment = nil)
https://github.com/cloudfoundry/bosh/blob/master/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L85

And cpi think the third parameters should be  resource_pool,   am i understand correctly ?

**Comment by cppforlife** [comment]
third argument to the create_vm CPI call is `cloud_properties` for the VM configuration. during normal deployment that comes from resource pool and during compilation it comes from compilation's config.
