### ISSUE TITLE
"bosh micro deploy" - log writing failed. can't be called from trap context

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#792]
First raised downstream at https://github.com/cloudfoundry-community/bosh-bootstrap/issues/298 by @mkb & @mdcarlson but I've observed it when running `bosh micro deploy` directly.

**Comment by drnic** [comment]
It's not a breaking bug - just an annoying message that looks like an error. If something did break during a deploy then a user might think this is a related cause.

**Comment by drnic** [comment]
Hmm, the bot didn't pick up this ticket /cc @cppforlife

**Comment by cppforlife** [comment]
This error shows up because of Ruby 2 upgrade. It's not happy about using Logger in specific situations. There is no easy way to fix it across the board. Since we are getting very close to publishing new bosh micro cli, we are not planning to fix this issue with the old cli.

**Comment by drnic** [comment]
Ok
