### ISSUE TITLE
Unknown command: micro deployment ./manifest.yml

### ISSUE THREAD

**Issue by jmakanjuola** [cloudfoundry/bosh#798]
I was able to use bosh download public stemcell light-bosh to download the centos image however when I ran the below command I get: 

# bosh micro deployment ./manifest.yml
Unknown command: micro deployment ./manifest.yml

**Comment by drnic** [comment]
For this command you need to install "gem install bosh_cli_plugin_micro"

**Comment by jmakanjuola** [comment]
Thanks drnic!
