### ISSUE TITLE
Issues with compiled_package_cache on non SSL blobstore

### ISSUE THREAD

**Issue by ipolyzos** [cloudfoundry/bosh#800]
Experiencing issues using  _ceph_ in _compiled_package_cache_ configuration that seems to be due to SSL. The current lab _ceph_ setup  has not SSL enabled and even though works fine as a _blobstore_ raise errors in the _compiled_package_cache_. In both _blobstore_ and _compile_packaged_cache_ the _use_ssl_ and _ssl_verify_peer_ are set to false. This configuration has verified to be passed correctly in the bosh director. However during the set of vm metadata in DirectorJobRunner the configuration present s them as enabled and the director attempt to access the blobstore using https.

Below i attached the relevant debug info : 

> D, [2015-04-09 16:01:17 #4181] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: Action Failed get_task: Task 8faf6cdd-8dbc-4f08-736d-2b3eb9d9e4f7 result: Compiling package ruby: Fetching package ruby: Fetching package blob e9adc10a-1123-472c-aac4-ea251c98d1e3: Getting blob from inner blobstore: Getting blob from inner blobstore: Shelling out to bosh-blobstore-s3 cli: Running command: 'bosh-blobstore-s3 -c /var/vcap/bosh/etc/blobstore-s3.json get e9adc10a-1123-472c-aac4-ea251c98d1e3 /var/vcap/data/tmp/bosh-blobstore-externalBlobstore-Get286652511', stdout: 'Error: Get https://**********************_:80/**_**-bosh/e9adc10a-1123-472c-aac4-ea251c98d1e3: EOF

**Comment by ipolyzos** [comment]
The relevant part of the configuration in as been deployed in the director i.e **data/jobs/director/bd1489d7ec55cf261f9b400ebeaa4361b91c3ec4-2b4d82e780fe21714f9b2474cf42789e071df594/config/director.yml**

>compiled_package_cache:
>  provider: s3
>  options:
>    bucket_name: *****-bosh-cache
>    access_key_id: ******
>    secret_access_key: *****
>    port: 80
>    host: d-2d02-u16.us-lab-1.cloudlab.jpmchase.net
>    s3_force_path_style: true
>    use_ssl: false
>    ssl_verify_peer: false

**Comment by cppforlife** [comment]
Errors that begin with "Action Failed get_task" are coming the from agent. It appears that compilation VM is failing to fetch ruby package. How does the bottom part of `config/director.yml` look like? It looks like even though your Director is ok, the agents might be misconfigured.

**Comment by ipolyzos** [comment]
If seems that indeed the agent is misconfigures. Interesting is that even through blobstore and compiled cache are correctly configures agent has
> use_ssl: true
>  ssl_verify_peer: true
something that suggest that configuration has not been copied over and this is probably causing the problem.

Do you think that a configuration such as below in director would solve the issue?
>   properties:
>     agent: 
>        use_ssl: true
>         ssl_verify_peer: true

I have attached the director.yml for your consideration
>---
>name: microbosh-***************
>port: 25556
>encryption: false
>max_tasks: 500
>max_threads: 3
>logging:
>  level: DEBUG
>  file: /var/vcap/sys/log/director/director.debug.log
>redis:
>  host: ***************
>  port: 25255
>  password: redis
>  logging:
>    level: info
>mbus: nats://nats:***************@***************:4222
>dir: /var/vcap/store/director
>db:
>  adapter: postgres
>  user: ***************
>  password: ***************
>  host: ***************
>  port: 5432
>  database: bosh
>  connection_options: {"max_connections":32,"pool_timeout":10}
>snapshots:
>  enabled: false
>max_vm_create_tries: 5
>scheduled_jobs:
>  - command: SnapshotDeployments
>    schedule: 0 0 7 * * * UTC
>  - command: SnapshotSelf
>    schedule: 0 0 6 * * * UTC
>scan_and_fix:
>  auto_fix_stateful_nodes: true
>dns:
>  server: 172.16.0.4
>  domain_name: microbosh
>  db:
>    adapter: postgres
>    user: ***************
>    password: ***************
>    host: ***************
>    port: 5432
>    database: bosh
>    connection_options: {"max_connections":32,"pool_timeout":10}
>blobstore:
>  provider: s3
>  options:
>    bucket_name: ***************
>    bucket_name: ***************
>    access_key_id: ***************
>    secret_access_key: ***************
>    use_ssl: false
>    port: 80
>    host: ***************
>    s3_force_path_style: true
>    ssl_verify_peer: false
>    s3_multipart_threshold: 16777216
>    access_key_id: ***************
>    secret_access_key: user_management:
>cloud:
>  plugin: openstack
>  properties:
>    openstack:
>      auth_url: http://***************:5000/v2.0
>      username: ipdev
>      api_key: ***************
>      tenant: ***************
>      endpoint_type: publicURL
>user_management:
>  provider: local
>cloud:
>  plugin: openstack
>  properties:
>    openstack:
>      auth_url: http://***************:5000/v2.0
>      username: ***************
>      api_key: ***************
>      tenant: ***************
>      endpoint_type: publicURL
>    use_ssl: false
>    port: 80
>    host: ***************
>    s3_force_path_style: true
>    ssl_verify_peer: false
>    s3_multipart_threshold: 16777216
>    ignore_server_availability_zone: true
>      default_key_name: **************
>      default_security_groups: ["***************", "***************"]
>      wait_resource_poll_interval: 5
>    registry:
>      endpoint: http://***************:25777
>      user: admin
>      password: ***************
>    agent:
>      ntp: [***************, ***************]
>      blobstore:
>        provider: s3
>        options:
>          bucket_name: ***************
>          access_key_id: ***************
>          secret_access_key: ***************
>          port: 80
>          host: ***************
>          use_ssl: true
>          ssl_verify_peer: true
>          s3_force_path_style: false
>    s3_multipart_threshold: 16777216
>  mbus: nats://nats:nats@**************:4222

**Comment by cppforlife** [comment]
It's hard to read pasted in config file, but it seems that your agent configuration in director.yml still has use_ssl and ssl_verify_peer set to true which means agent will try to follow that.

**Comment by ipolyzos** [comment]
sorry about this, i have finxes the formating now. Yes indeed this is the case, blobstore and compiled cache https settings are false but agent https is true.

**Comment by ipolyzos** [comment]
It seems that microbosh configuration is not used. Tried passing the following configuration but the director.yml deployedin director has the ssl use and verification true.

```
director:
  properties:
    blobstore:
       use_ssl: false
       ssl_verify_peer: false 
```

**Comment by ipolyzos** [comment]
Going through the floowing configurations seems not to apply changes in director.yml deployed in bosh director:

1. 
```
cloud:
  ...
  properties:
    agent:
      blobstore:
        use_ssl: false
        ssl_verify_peer: false
```


2.
```
apply_spec:
  properties:
    director:
      max_upload_size: "10000m"
      max_threads: 3
	  properties:
      agent:
        blobstore:
          use_ssl: false
          ssl_verify_peer: false
```

**Comment by ipolyzos** [comment]
hey guys, has anyone looked at it?

**Comment by dpb587-pivotal** [comment]
Closing - sounds like your director may not have been correctly re-deployed when testing config changes. Microbosh is now deprecated in favor of bosh-init - please feel free to give that a try ([openstack doc](http://bosh.io/docs/init-openstack.html)) and reopen with updated information if the issue persists.
