### ISSUE TITLE
Allow director behind shared reverse proxy

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/bosh#802]
Currently when referencing a director by hostname, the host portion of the uri is replaced by the [resolved ipaddress](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/client/director.rb#L31) before [making the request](https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/client/director.rb#L634).

This behaviour prevents the reverse proxy usecase because the Host Header is lost.
I would love to create a PR to fix this behaviour but I wanted to first understand the usecase for the current behaviour.

**Comment by cppforlife** [comment]
It seems that following [commit](https://github.com/cloudfoundry/bosh/commit/55699d7b6f61c51ad0f541882111b92b82c7c0d0) introduced it to reduce number of DNS requests made. I'll ask the guys who wrote it...

**Comment by rkoster** [comment]
@cppforlife figured out the simplest solution which would not affect the current behaviour is adding a Host header. I have created a PR which implements that solution #806.

**Comment by cppforlife** [comment]
Fair enough, I'll close this issue and will update the PR when we pull it in.
