### ISSUE TITLE
Wrong/confusing error message for syntax error in Job spec

### ISSUE THREAD

**Issue by TiraO** [cloudfoundry/bosh#804]
When there is a syntax error in the job spec (eg. a missing colon), running ```bosh create release``` results in the error ```Job spec is missing``` even though the job spec exists.

**Comment by Nopik** [comment]
Nice found, I've just got bitten by this bug.

**Comment by tushar-dadlani** [comment]
Nice find. We ran into the same issue and found this helpful. 
+1

**Comment by cyrille-leclerc** [comment]
+1

**Comment by benlaplanche** [comment]
+1, for me it was tabs vs spaces for indentation

**Comment by poblin-orange** [comment]
+1. no idea yet why ..

**Comment by robbig2871** [comment]
for me it was: key <space> : , should be just key:
i found it parsing spec file. 
```
require 'yaml'
thing = YAML.load_file('jobs/vault/spec')
```

**Comment by mtekel** [comment]
+1, I had a missing :

It should really say syntax error, ideally point to the issue....

**Comment by drnic** [comment]
I got bit by this today when a `spec` wasn't valid YAML (although my text editor thought it was) - a value needed `"..."` quotes around it

**Comment by voelzmo** [comment]
Fixed in bosh-v225, aka stable-3138

**Comment by poblin-orange** [comment]
Met this issue again today using bosh create release.
Should the fix be applied also on bosh-cli (using BOSH 1.3068.0)

**Comment by voelzmo** [comment]
@poblin-orange the fix is applied in bosh CLI >=1.3138.0 so please update

**Comment by poblin-orange** [comment]
@voelzmo done, thks
