### ISSUE TITLE
Stage runner requires 1000 as the UID, but my ubuntu user in provisioned vagrant is 900

### ISSUE THREAD

**Issue by dwu-pivotal** [cloudfoundry/bosh#807]
bosh-stemcell/lib/bosh/stemcell/stage_runner.rb
Stage runner requires 1000 as the UID, but my ubuntu user in provisioned vagrant is 900
How to fix it?

**Comment by dthaluru** [comment]
I am also having similar issue. +1

**Comment by voelzmo** [comment]
This seems to happen when you use stemcell building machines created with https://github.com/cloudfoundry/bosh-packer-templates/tree/master/bosh-stemcell - is that what you are doing, @dwu-pivotal and @dthaluru? For now a workaround could be to build the stemcells on AWS with the images provided by pivotal as the readme in https://github.com/cloudfoundry/bosh/tree/master/bosh-stemcell describes.

**Comment by dwu-pivotal** [comment]
Yes I was on my local ubuntu. In AWS, everything works fine.

**Comment by dthaluru** [comment]
Yes I was not able to build stem cell on my Mac but AWS works fine.

**Comment by voelzmo** [comment]
Maybe this is because the virtualbox packer templates create the ubuntu user with uuid 900? https://github.com/cloudfoundry/bosh-packer-templates/blob/master/bosh-stemcell/http/preseed.cfg#L20

I suppose this is UID 1000 for the source-ami in the AWS based build? https://github.com/cloudfoundry/bosh-packer-templates/blob/master/bosh-stemcell/template.json#L15

cc: @cppforlife

**Comment by voelzmo** [comment]
I just provided a PR in the bosh-packer-templates fixing this issue. To have an effect, the virtualbox image referenced in https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/Vagrantfile#L13 would need to updated as well, if you don't want to build your own box :)

**Comment by voelzmo** [comment]
I guess this should only be closed once the Virtualbox images have been re-built.

**Comment by voelzmo** [comment]
*bump* Can we re-build the virtualbox images please, @cppforlife?

**Comment by voelzmo** [comment]
*bump* Can we re-build the virtualbox images please, @cppforlife?

**Comment by dpb587-pivotal** [comment]
@cppforlife, is this still an issue since now supporting container-based building?

**Comment by voelzmo** [comment]
@dpb587-pivotal Haven't tried to build the stemcell from a docker image yet. From https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/docker/Dockerfile#L10 it seems that the UID should be fine. The [README](https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/README.md) could make it maybe clearer what the preferred way to build stemcells is and the [Vagrantfile](https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/Vagrantfile#L9) still contains the option to use the virtualbox image.

**Comment by cppforlife** [comment]
Closing. Switched to using concourse to build all stemcells: https://github.com/cloudfoundry/bosh/tree/master/ci/pipelines/stemcells

**Comment by voelzmo** [comment]
@cppforlife I knew this is was how it would happen. ;)
