### ISSUE TITLE
Allow io1 EBS disk types in AWS

### ISSUE THREAD

**Issue by schwarzmx** [cloudfoundry/bosh#814]
There [a validation](https://github.com/cloudfoundry/bosh/blob/3bf736d2966be501d9ec8bc24b18d0214524652b/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L217-L222) to allow `gp2` and `standard` EBS disk types only, but there is also `io1` available per [AWS product page](http://aws.amazon.com/ebs/details/).

Similarly, the maximum size is set to 1TB when certain types allow up to 16TB.

**Comment by cppforlife** [comment]
Ah you are right. Any chance for a PR?

**Comment by schwarzmx** [comment]
Sure, I haven't touched the bosh code before; what's the fastest way to get up to speed to fix this?

**Comment by cppforlife** [comment]
Since proposed changes are only in the aws CPI, you can:
- clone repo
- `cd bosh_aws_cpi`
- use `bundle install` to install all required gems
- make changes to the aws code & associated tests in spec/unit directory
- run unit tests via `bundle exec rspec spec/unit`
- submit PR
