### ISSUE TITLE
can bosh create vm use diffient certificate？

### ISSUE THREAD

**Issue by Jam-Lin** [cloudfoundry/bosh#818]
hello, i use bosh to deploy cloudfoundry on openstack, i found that when i use bosh to create new node it  use the same  certificate with micro bosh.  i want to create many VM and each Vm use diffient certificate, how to do that?

**Comment by cppforlife** [comment]
@Jam-Lin which certificate are you referring to? Do you mean the ssh key?

**Comment by Jam-Lin** [comment]
yes, i found that the manifest can config the key_name. thank you all the same.
