### ISSUE TITLE
bosh stemcell vcpu limit

### ISSUE THREAD

**Issue by penrod** [cloudfoundry/bosh#823]
The bosh stemcells are created on vmware HW version 7.
HW version 7 is the ESI/ESX 4.x product which has a cpu limit of 8.

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003746
http://www.vmware.com/pdf/vsphere4/r40/vsp_40_config_max.pdf

We recently ran into this limitation trying to increase the vcpu's on our DEA's.
Are there any plans in the works to build stemcell's on the vmware HW version 8?

**Comment by cppforlife** [comment]
vSphere 2972 stemcell is now at hardware version 8.
