### ISSUE TITLE
how to let bosh agent work on root partition not ephemeral disk in centos stemcell

### ISSUE THREAD

**Issue by guanglinlv** [cloudfoundry/bosh#824]
hi,

bosh agent will run at a ephemeral disk not root partition in centos stemcell. how to change that behavior?

@cppforlife 

thanks

**Comment by cppforlife** [comment]
On OpenStack we support re-partitioning of root disk on Ubuntu stemcells if ephemeral disk is missing. Are you on OpenStack? Are you seeing a specific error in the agent log on CentOS? parted is not installed on the CentOS stemcells afaik which would be the first incompatibility [1].

[1] https://github.com/cloudfoundry/bosh-agent/blob/master/platform/disk/root_device_partitioner.go#L77

**Comment by guanglinlv** [comment]
hi @cppforlife ,

yes,i am using openstack. because i got a `pivot_root` failure problem when diego create and start a container,i guess that the ephemeral disk maybe doesnt support `pivot_root`,like a  ramdisk?

<a href=https://github.com/cloudfoundry-incubator/diego-release/issues/38>the pivot_root issue</a>

And, if i install `parted` on centos, is it can work normally?

here is the partition info of my VM with centos

```shell
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  2.0G     0  2.0G   0% /dev
tmpfs          tmpfs     2.0G     0  2.0G   0% /dev/shm
tmpfs          tmpfs     2.0G   41M  1.9G   3% /run
tmpfs          tmpfs     2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1      ext4       38G   12G   25G  32% /
/dev/vdb2      ext4       36G  1.6G   33G   5% /var/vcap/data
tmpfs          tmpfs     1.0M   28K  996K   3% /var/vcap/data/sys/run
/dev/loop0     ext4      120M  1.6M  115M   2% /tmp
cgroup         tmpfs     2.0G   48K  2.0G   1% /tmp/garden-/cgroup
```

thanks

**Comment by guanglinlv** [comment]
hi

`parted` is already there in centos 7.1,i will try it without ephemeral disk.

**Comment by cppforlife** [comment]
garden does not officially support centos/rhel stemcells. there will be future work to fix that. 

i do not believe that pivot_root error relates to the disk partitioning. looking at the df output it looks like bosh-agent did everything as it should have.

**Comment by guanglinlv** [comment]
hi @cppforlife ,

yes,the pivot_root error is not relate to the disk partitioning at all. I have verify that.

and it looks like bosh support re-partitioning of root disk on centos 7 stemcell correctly.<a href=https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/bosh_openstack_agent_settings/apply.sh#L10>the limitation</a> can be removed. 

thanks.

**Comment by cppforlife** [comment]
I've created a story to enable this functionality: https://www.pivotaltracker.com/story/show/94636274
