### ISSUE TITLE
is there a Performance Testing of bosh?

### ISSUE THREAD

**Issue by Jam-Lin** [cloudfoundry/bosh#825]
hello, i want to know how many Vm can bosh manage? is there a Performance Testing of bosh? thank you .

**Comment by cppforlife** [comment]
BOSH has been used to manage hundreds of VMs in a single deployment. We have not tested how many deployments (with how many VMs) will slow the system down. We currently do not run automated simulations to test system limits or performance. We do have plans to do that in the future.
