### ISSUE TITLE
rogue lock - keeps updating its "expires at"

### ISSUE THREAD

**Issue by bobhlo** [cloudfoundry/bosh#827]
```
$ bosh locks

+------------+-----------------+-------------------------+
| Type       | Resource        | Expires at              |
+------------+-----------------+-------------------------+
| deployment | cf-r2-logsearch | 2015-05-18 23:43:33 UTC |
+------------+-----------------+-------------------------+

Locks total: 1
$ bosh locks

+------------+-----------------+-------------------------+
| Type       | Resource        | Expires at              |
+------------+-----------------+-------------------------+
| deployment | cf-r2-logsearch | 2015-05-18 23:43:58 UTC |
+------------+-----------------+-------------------------+

Locks total: 1
$ bosh locks

+------------+-----------------+-------------------------+
| Type       | Resource        | Expires at              |
+------------+-----------------+-------------------------+
| deployment | cf-r2-logsearch | 2015-05-18 23:44:18 UTC |
+------------+-----------------+-------------------------+
```

How do I delete this rogue lock? There are no running tasks (even with `bosh tasks recent --no-filter`)

Ideas on why it is updating its `Expires at` to be just in the future from now?

/cc @drnic

**Comment by bobhlo** [comment]
Not sure what caused this, but we found the lock in redis and deleted it:

```
redis 127.0.0.1:25255> keys "lock:*"
1) "lock:deployment:cf-r2-logsearch"
redis 127.0.0.1:25255> del lock:deployment:cf-r2-logsearch
(integer) 1
```

**Comment by bobhlo** [comment]
Work is done on director, BTW.

**Comment by cppforlife** [comment]
I wonder if somehow there was a runaway worker process?

**Comment by drnic** [comment]
This happened again (same BOSH btw) so I wrote a blog post https://blog.starkandwayne.com/2015/06/08/unlocking-bosh-locks/

**Comment by drnic** [comment]
Actually, same issue happened on two diff boshes - deployments that didn't cancel after 6+ hours.

**Comment by mtekel** [comment]
+1. Same problem on cf210 release. Luckily it goes away after a while...

**Comment by cppforlife** [comment]
Are you sure you don't have tasks running? bosh tasks recent --no-filter. Or bosh tasks --no-filter.

**Comment by mtekel** [comment]
Seems like I had resurrector running in the background...

**Comment by cppforlife** [comment]
It's very likely that resurrector was running in all the of the above scenarios. We have adjusted its behavior such that it does not enqueue a scan_and_fix task when all VMs are paused for resurrection: https://www.pivotaltracker.com/story/show/104036894.
