### ISSUE TITLE
Two issues when building stemcells manually by following the guide bosh/bosh-stemcell/README.md

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/bosh#828]
1. Need to add below line in Line 97 in bosh-stemcell/Vagrantfile
       ( apt-get install -y cmake pkg-config )

2. After executing "vagrant ssh remote", need to add below line as the first line in file /usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/fog-aws-0.2.2/lib/fog/aws/auto_scaling.rb
     require_relative('.')

**Comment by cppforlife** [comment]
Could you provide a bit more info why do we need to make these changes?

**Comment by AbelHu** [comment]
Sure. I will provide more details next week after I come back to work.

Sent by Android Outlook



On Wed, May 20, 2015 at 10:27 AM -0700, "Dmitriy Kalinin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you provide a bit more info why do we need to make these changes?

-

**Comment by AbelHu** [comment]
Issue 1:
Need to add below line in Line 97 in bosh-stemcell/Vagrantfile
( apt-get install -y cmake pkg-config )

1) Below error is thrown without "cmake"
==> remote: Installing rubocop 0.31.0
==> remote: Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
==> remote:
==> remote:         /usr/local/rbenv/versions/1.9.3-p448/bin/ruby extconf.rb
==> remote: checking for gmake... no
==> remote: checking for make... yes
==> remote: checking for cmake... no
==> remote: ERROR: CMake is required to build Rugged.
==> remote: *** extconf.rb failed ***
==> remote: Could not create Makefile due to some reason, probably lack of
==> remote: necessary libraries and/or headers.  Check the mkmf.log file for more
==> remote: details.  You may need configuration options.
==> remote:
==> remote: Provided configuration options:
==> remote:     --with-opt-dir
==> remote:     --without-opt-dir
==> remote:     --with-opt-include
==> remote:     --without-opt-include=${opt-dir}/include
==> remote:     --with-opt-lib
==> remote:     --without-opt-lib=${opt-dir}/lib
==> remote:     --with-make-prog
==> remote:     --without-make-prog
==> remote:     --srcdir=.
==> remote:     --curdir
==> remote:     --ruby=/usr/local/rbenv/versions/1.9.3-p448/bin/ruby
==> remote:     --use-system-libraries
==> remote:
==> remote:
==> remote: Gem files will remain installed in /usr/local/rbenv/versions/1.9.3-p                 448/lib/ruby/gems/1.9.1/gems/rugged-0.22.2 for inspection.
==> remote: Results logged to /usr/local/rbenv/versions/1.9.3-p448/lib/ruby/gems                 /1.9.1/gems/rugged-0.22.2/ext/rugged/gem_make.out
==> remote: An error occurred while installing rugged (0.22.2), and Bundler cannot continue.
==> remote: Make sure that `gem install rugged -v '0.22.2'` succeeds before bundling.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

2) Below error is thrown without pkg-config
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/local/rbenv/versions/1.9.3-p448/bin/ruby extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... yes
checking for pkg-config... no
ERROR: pkg-config is required to build Rugged.
*** extconf.rb failed ***

Issue 2:
vagransh ssh remote and execute command "bundle exec rake stemcell:build_os_image[ubuntu,trusty,/tmp/ubuntu_base_image.tgz]". Below error is thrown.
/bosh$ bundle exec rake stemcell:build_os_image[ubuntu,trusty,/tmp/ubuntu_base_image.tgz]
rake aborted!
NameError: uninitialized constant Fog::AWS::CredentialFetcher
/bosh/bosh-dev/lib/bosh/dev/upload_adapter.rb:1:in `require'
/bosh/bosh-dev/lib/bosh/dev/upload_adapter.rb:1:in `<top (required)>'
/bosh/bosh-dev/lib/bosh/dev/build.rb:5:in `require'
/bosh/bosh-dev/lib/bosh/dev/build.rb:5:in `<top (required)>'
/bosh/bosh-dev/lib/bosh/dev/bat_helper.rb:1:in `require'
/bosh/bosh-dev/lib/bosh/dev/bat_helper.rb:1:in `<top (required)>'
/bosh/bosh-dev/lib/bosh/dev/tasks/spec.rake:4:in `require'
/bosh/bosh-dev/lib/bosh/dev/tasks/spec.rake:4:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by AbelHu** [comment]
Revert Gemfile.lock and it works.
