### ISSUE TITLE
Bosh doesnt allow 2 default gateways to be defined for single vm

### ISSUE THREAD

**Issue by Nopik** [cloudfoundry/bosh#829]
I have a vSphere setup where I have a public network, with public IPs and private network with large pool of private IPs. Most of the vms deployed by bosh are having only private IP address.

But few machines, load balancers, are having 2 NICs and 2 IP addresses. I can configure them properly from bosh, except the default gateways. Basically, I'm looking for bosh to automatically setup such routing:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG    0      0        0 eth0
0.0.0.0         x.y.z.33        0.0.0.0         UG    0      0        0 eth1
10.0.0.0        0.0.0.0         255.255.0.0     U     0      0        0 eth0
x.y.z.32        0.0.0.0         255.255.255.224 U     0      0        0 eth1
```

(where `x.y.z` is part of my public IP of course). Specifically when one or the other default gw is missing, connectivity is broken in one or another way.

When I'm trying to use 'default: [gateway]' on 2 networks for single vm, I'm getting:
`Error 150004: Job 'hub' specified more than one network to contain default gateway` error. So, typically I am using regular deploy with 1 default gw, then ssh to the machine and fixing routing by hand, which isn't a reliable solution, of course.

**Comment by dpb587-pivotal** [comment]
The [`routes`](http://bosh.io/jobs/routes?source=github.com/cloudfoundry/networking-release&version=9) job from the [networking-release](https://github.com/cloudfoundry/networking-release) is a solution to this nowadays. Here's a [blog post](http://engineering.pivotal.io/post/multi-homed-bosh-director/) mentioning a similar, sample scenario.
