### ISSUE TITLE
PowerDNS recursor not working when MicroBosh has multiple IPs

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/bosh#836]
Hello,

we are having an issue with PowerDNS when using a recursor. It doesn't work if the MicroBosh has multiple IPs, e.g. an additional dynamic/elastic IP. PowerDNS may run the query to the recursor with the wrong IP and/or return the response with the wrong IP, which makes the client reject the response with "reply from unexpected source".

The solution is actually already in PowerDNS: local-address and query-local-address. When defined in the PowerDNS configuration, the issue is gone. Unfortunately, it is currently not possible to set it/configure it properly through the MicroBosh PowerDNS job properties.

Cheers, Vedran

**Comment by vlerenc** [comment]
Please see proposal https://github.com/cloudfoundry/bosh/pull/837.

**Comment by cppforlife** [comment]
Fix was merged. Thanks!
