### ISSUE TITLE
[centos stemcell] /var/vcap/bosh/bin not in PATH for root user

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#845]
Unlike ubuntu stemcells, on a centos stemcell, `monit` is not in the path for root user.

Can we add `export PATH=$PATH:/var/vcap/bosh/bin` to the profile for the root user? Thanks!

**Comment by cppforlife** [comment]
I've checked on the centos 7 stemcell and root user has /var/vcap/bosh/bin on the $PATH and I'm able to run `monit summary` without problems.

**Comment by wayneeseguin** [comment]
FYI I just issued [Pull Request 849](https://github.com/cloudfoundry/bosh/pull/849) which addresses this issue. 

Also, this was likely an issue on not just CentOS stemcells because of the behavior however I did not verify other stemcell flavors.

**Comment by voelzmo** [comment]
@wayneeseguin fixing that for all stemcells seems odd - one of the most common workflows I do is
```
bosh ssh <machine>
sudo su -
monit summary
```

which works perfectly fine on ubuntu stemcells for me.

**Comment by cppforlife** [comment]
Fix was included in 2999.
