### ISSUE TITLE
Bosh deploy with an error

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry/bosh#850]
Hi I tried to run Bosh deploy after `bosh create release` & `bosh upload release`. I have verified the release to be accurate with bosh verify and bosh releases.

The problem comes after, when I attempt to `bosh deploy`, the following error returned. I have no idea what went wrong with the deployment file if it was supposed to be generated and merged with spiff.

```text
[root@vmstack-01 cf-release]# bosh deploy

Processing deployment manifest
------------------------------
Getting deployment properties from director...
Compiling deployment manifest...
Please review all changes carefully

Deploying
---------
Deployment name: `cf-deployment.yml'
Director name: `microbosh-centos'
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 8
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

Error 40001: Required property `range' was not specified in object ({"cloud_properties"=>nil, "static"=>["192.168.241.20 - 192.168.241.100"]})

Task 8 error

For a more detailed error report, run: bosh task 8 --debug
```
Please advise.

**Comment by uzzz** [comment]
Looks like this is mistake in your deployment manifest. Take a look at your "networks" section, network with type "manual" (or without type – network without type is a manual by default) – there's a missing required "range" argument in one of subnets. See http://bosh.io/docs/networks.html#manual for details.

**Comment by kennetham** [comment]
@uzzz Right, I fixed that. It is working now, but more errors popping up.
