### ISSUE TITLE
[Improvement] Warn user about planned instance recreations

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry/bosh#859]
### Summary

Warn user about planned instance recreations.
### Details

It may well happen that even though the deployment wasn't touched, bosh will recreate all VMs. That happened to us after we have disabled PowerDNS and redeployed MicroBosh. On the first recreation of a machine, bosh silently decided that it should recreate all VMs with the net effect that the whole landscape was recreated.
### Suggestion

It would be great if the user would be warned/told what will happen next, especially if it involves multiple VM recreations. A hint in the debug log would be also welcome as to why a certain action was taken, e.g. why bosh will recreate a VM.
It would be great if you could consider this suggestion. Thanks in advance.
### Sources

The source that decides about the need for recreation (no logs): https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/deployment_plan/instance.rb

**Comment by cppforlife** [comment]
There is an interesting UX challenge here. Currently simple diff-ing happens in the CLI and the rest on the Director at which point user does not have any input except cancelling the task. Debug log shows a bit more info if you grep for `changes:`. We are moving towards a way where `bosh recreate` will always touch only single VM but currently it's blocked on IP mgmt changes we are making in global-networking epic.

**Comment by vlerenc** [comment]
Ah, sounds good (recreate only focusing on the VM) and thank you for the hint with the log! I missed that somehow.

**Comment by tjvman** [comment]
Closing - The [v2 CLI](https://github.com/cloudfoundry/bosh-cli) has support for both single-instance recreation with `bosh recreate`, as well as a `--dry-run` flag for `deploy` that will show what instances will be affected without actually making any changes.
