### ISSUE TITLE
[stemcell] Missing library when building "bosh_micro_go"

### ISSUE THREAD

**Issue by palvarez89** [cloudfoundry/bosh#868]
If you try to generate a Ubuntu stemcell as following:

    bundle exec rake stemcell:build_os_image[ubuntu,trusty,/tmp/ubuntu_base_image.tgz]
    bundle exec rake stemcell:build_with_local_os_image[openstack,kvm,ubuntu,trusty,go,/tmp/ubuntu_base_image.tgz]

It will fail in the stage `bosh_micro_go`. I have around [the full build log](https://gist.github.com/palvarez89/cc1d772e56d45f60a43a), but this is the relevant part of the log : 

    + mkdir -p /var/vcap/bosh/blob
    + echo 'Starting micro bosh compilation'
    Starting micro bosh compilation
    + cat
    + cat
    + agent_pid=21162
    + echo 'Starting BOSH Agent for compiling micro bosh package, agent pid is 21162'
    Starting BOSH Agent for compiling micro bosh package, agent pid is 21162
    + /var/vcap/bosh/bin/bosh-agent -P dummy -M dummy -C /var/vcap/bosh/agent.json
    + wait_agent localhost 6969
    + for i in '{1..10}'
    + nc -z localhost 6969
    /var/vcap/bosh/bin/bosh-agent: error while loading shared libraries: libgo.so.5: cannot open shared object file: No such file or directory

I assume this is because it's missing a dependency, and actually, after installing  `apt-get install libgo5` in the chroot, the stage `bosh_micro_go` worked fine.

**Comment by cppforlife** [comment]
Did you modify stemcell building or bosh-agent in some way? Are building bosh-agent with gccgo?

**Comment by palvarez89** [comment]
I didn't modify anything yet, just trying to build a Ubuntu stemcell to understand all the process. That might be the issue (gccgo).. I'll try to reproduce this again in a clean environment.

**Comment by palvarez89** [comment]
I assume this problem was caused by my stemcell builder VM using gccgo. Closing.
