### ISSUE TITLE
bosh deploy failed with  ruby compiling

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/bosh#870]
Hi expert,
I have a issue when deploy bosh.
After run "bosh deploy", I get below error:
I try different ruby version, 1.9, 2.0, 2.1.4, 2.2.2 . But the same issue.
bosh version 1.3010. stemcell version 3010.

Can you help to check ,if there is sth wrong with my operation.
////////////////////////////////////////////////////////////
root@cftest01:/home/david# bosh deployment ./bosh2.yml
\Deployment set to `/home/david/bosh2.yml'
root@cftest01:/home/david# bosh deploy
.............................................
..............................................

  Started compiling packages
  Started compiling packages > powerdns/256336d00b1689138490c385c03ad3a8f54b4a9e                                                                     . Done (00:01:25)
  Started compiling packages > genisoimage/008d332ba1471bccf9d9aeb64c258fdd4bf76                                                                     201. Done (00:00:25)
  Started compiling packages > mysql/e5309aed88f5cc662bc77988a31874461f7c4fb8. D                                                                     one (00:00:12)
  Started compiling packages > libpq/f181aa97dd63567e04d897762f0440fb2bef1517. D                                                                     one (00:00:22)
  Started compiling packages > ruby/c28e01e561dd7e1bd4ce44f134970dc9f5d7e8fc. Fa                                                                     iled: Action Failed get_task: Task 5e9aec90-04bc-4aa9-7f11-9eed76bb05df result:                                                                      Compiling package ruby: Running packaging script: Command exited with 1; Truncat                                                                     ed stdout: generating constant definitions
compiling stringio.c
installing default sdbm libraries
generating constant definitions
installing default stringio libraries
linking shared-object -test-/postponed_job.so
checking ../.././parse.y and ../.././ext/ripper/eventids2.c
make[2]: Leaving directory `/var/vcap/data/compile/ruby/ruby-2.1.4/ext/-test-/bu                                                                     g-5832'......
////////////////////////////////////////////////////////////////////////////////////
 
Thanks,
David

**Comment by liuxiaoxi2237** [comment]
The bosh is deployed on vsphere 5.5.

**Comment by liuxiaoxi2237** [comment]
Thank you.
The issue seems caused by deployment.yml. I change to use manual ip address, it works fine.

**Comment by cppforlife** [comment]
That was just a coincidence. You have changed something in the manifest, so had to do a deploy again. On the subsequent deploy make -j succeeded like it typically does.

**Comment by liuxiaoxi2237** [comment]
sure, thanks so much.
