### ISSUE TITLE
Upload stemcell not workgin (bosh-init installation)

### ISSUE THREAD

**Issue by joek** [cloudfoundry/bosh#872]
Hi,
we deployed a new microbosh using bosh-init. The installation works really well, thank you for building this great tool.

After we finished the installation we tried to upload a new stemcell and got the following error:
```
 Started update stemcell > Verifying stemcell manifest. Done (00:00:00)
  Started update stemcell > Checking if this stemcell already exists. Done (00:00:00)
  Started update stemcell > Uploading stemcell bosh-aws-xen-ubuntu-trusty-go_agent/3012 to the cloud. Failed: Unable to copy stemcell root image: command 'sudo -n /var/vcap/packages/bosh_aws_cpi/gem_home/ruby/1.9.1/gems/bosh_aws_cpi-1.2981.0/scripts/stemcell-copy.sh /var/vcap/data/tmp/director/stemcell20150709-25924-fq60fb/image /dev/xvdg 2>&1' failed with exit code 1 (00:00:40)

Error 100: Unable to copy stemcell root image: command 'sudo -n /var/vcap/packages/bosh_aws_cpi/gem_home/ruby/1.9.1/gems/bosh_aws_cpi-1.2981.0/scripts/stemcell-copy.sh /var/vcap/data/tmp/director/stemcell20150709-25924-fq60fb/image /dev/xvdg 2>&1' failed with exit code 1

Task 6 error
```

The problem was, the sudo is requiring a password.
```
$ sudo -l
Matching Defaults entries for vcap on 84bc124e-0c15-45f8-7b08-ed8e72b83a3f:
    !lecture, tty_tickets, !fqdn

User vcap may run the following commands on 84bc124e-0c15-45f8-7b08-ed8e72b83a3f:
    (ALL) ALL
    (root) NOPASSWD: /var/vcap/jobs/director/bin/stemcell-copy
```
Is there already a solution for this issue (except of ssh in to the microbosh and fix sudo)? 
From my perspective it is quiet hard to fix the [sudoers](https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/templates/sudoers) file, since the path to the script is generated including version numbers. Any ideas?

Cheers
Johannes

**Comment by cppforlife** [comment]
Uploading full AWS stemcell currently does not work. We have a story coming up to fixing that: https://www.pivotaltracker.com/story/show/97308026

**Comment by joek** [comment]
@cppforlife I might got a solution on CPI level. I guess this ticket can be closed.

**Comment by camelpunch** [comment]
For the absolute noob, what do I do to get around this? Can I get the stemcell uploaded without using `bosh upload stemcell`?

**Comment by camelpunch** [comment]
Solved this for bosh-init by using the latest AWS CPI release, which includes the fix. Change bosh.yml lines 9 and 10 to use v=28 instead of v=27. Change sha1 to c7ce03393ebedd87a860dc609758ddb9654360fa.
