### ISSUE TITLE
SSL cert error running "bosh create release"

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/bosh#873]
Hi Expert,
I am deploy cf by bosh. 
When running "bosh create release", I got below error
my env: ubunt 14.04LTS / ruby 2.2.2p95 /gem 2.4.8 / bosh 1.3012.0.
Try openssl s_client -connect  www.github.com sslv3  , can not get web server certicate.
Try openssl s_client -connect  www.github.com tls1, can get web server certificate.
Seems github not support sslv3 now. But ruby gem still use ssl v3.
Any suggestoins?
///////////////////////////////////////////
root@cftest01:/home/david/cf-release# bosh create release
Syncing blobs...
postgres/postgres-9.0.3-1.amd64.tar.gz downloading 15.5M (0%)
at depth 1 - 20: unable to get local isdownloading 15.5M (0%)
at depth 1 - 20: unable to get local isdownloading 15.5M (0%)
at depth 1 - 20: unable to get local issuer certificate
/usr/local/rvm/gems/ruby-2.1.6/gems/blobstore_client-1.3012.0/lib/blobstore_client/base.rb:63:in `rescue in get': Failed to fetch object, underlying error: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed> /usr/local/rvm/gems/ruby-2.1.6/gems/httpclient-2.4.0/lib/httpclient/session.rb:303:in `connect' (Bosh::Blobstore::BlobstoreError)
/usr/local/rvm/gems/ruby-2.1.6/gems/httpclient-2.4.0/lib/httpclient/session.rb:303:in `ssl_connect'
/usr/local/rvm/gems/ruby-2.1.6/gems/httpclient-2.4.0/lib/httpclient/session.rb:760:in `block in connect'
/////////////////////////////////////////////////////////////////////////
thanks,
David

**Comment by warroyo** [comment]
was there a work around for this?
