### ISSUE TITLE
Unclear `bosh scp` command documentation

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh#884]
I want to download file from bosh-managed VM. `bosh --help` is not clear about `scp` command usage.

```
# Wrong way; my first guess after reading docs
$ bosh scp --download /tmp/cf-logs.logs ingester/0

# Right way; just guessed
$ bosh scp ingester/0 --download /tmp/cf-logs.logs /tmp
```

Help:
```
scp [--download] [--upload] [--public_key FILE] [--gateway_host HOST]
[--gateway_user USER] [--gateway_identity_file FILE]
    upload/download the source file to the given job. Note: for download /path/to/destination is a
    directory
..
```

1. Tell that `job/index` must go right after scp, than options
2. Tell that  `/path/to/destination` is required for download and it is placed at the end of string without any options.
3. Maybe some symmetrical syntax like --from/--to ?

**Comment by maryoush** [comment]
I spent some time figuring it out how to make it ... -  some nice description would help

**Comment by sslavic** [comment]
+1

**Comment by geofffranks** [comment]
The docs for this really need fixing. Having only 1 api_worker_z1 node, I just tried to bosh scp, getting rather unhelpful output from error messages. 

```
$ bosh scp --upload api_worker_z1 ~/.s3cfg /tmp
Acting as user 'concourse' on deployment 'asv-sb-cloudfoundry' on 'asv-sandbox'
Executing file operations on job api_worker_z1
Target deployment is `asv-sb-cloudfoundry'

Setting up ssh artifacts

Director task 118619
Error 100: undefined method `each' for nil:NilClass

Task 118619 error
Failed to set up SSH: see task 118619 log for details
```

The help message for scp was also not very useful at pointing me in the right direction. Looking up the docs change in #973 was the only way I could figure out the correct incantation to use.  Would be really nice to get this resolved.

**Comment by linsun** [comment]
I struggled for 10+ mins to figure out the 'bosh scp' syntax and failed! Found this git issue, which helped me.  Totally agreed, it is too confusing to use 'bosh scp' based on current doc.
