### ISSUE TITLE
CLI can download stemcell by URL

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh#886]
It would be nice to have a download version of `bosh upload stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent` that lets me cache stemcells locally. I would like to do something like `bosh download stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent` or `bosh download public stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent --full`.

As an aside, the output of `bosh public stemcells` is misleading. "To download use `bosh download public stemcell <stemcell_name>'. For full url use --full." implies that `--full` is allowed in `bosh download public stemcell`, but it is only allowed in `bosh public stemcells`.

**Comment by cppforlife** [comment]
We will be removing `bosh public stemcells` and `bosh download stemcell` commans in favor of using bosh.io. Any reason why you dont want to use curl or wget?

**Comment by wendorf** [comment]
No, curl or wget are fine. Closing.
