### ISSUE TITLE
custom AWS tags using bosh mnifest

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry/bosh#890]
please excuse if I am asking something very simple or should not be here kind of thing .. here as I am new to Bosh 
based on the file https://github.com/cloudfoundry/bosh/blob/master/bosh-director/lib/bosh/director/vm_metadata_updater.rb 

    def update(vm, metadata)
      if @cloud.respond_to?(:set_vm_metadata)
        metadata = metadata.merge(@director_metadata)
        metadata[:deployment] = vm.deployment.name

        if vm.instance
          metadata[:job] = vm.instance.job
          metadata[:index] = vm.instance.index.to_s
        end

it seems bosh can only tag AWS instances with these values, but if I wanted to assign custom tags to AWS instances via Bosh cf manifest .. will that feature already exists or enhancement to this piece of code

**Comment by amulyas** [comment]
I got my answer from @drnic  in person as he was in office and I got his few mins

**Comment by mstrzele** [comment]
@amulyas Can you write here the answer from @drnic? I'm really curious if BOSH is able to tag the resources.

**Comment by ssurenr** [comment]
+1
