### ISSUE TITLE
Bosh AWS CPI Should Tag Primary Volume of Bosh Director

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/bosh#905]
We'd like to be able to programmatically determine which volume is the Bosh Directors' primary volume.  Volumes can have tags attached.  When bosh-init creates the volume for the director it should tag it as well.

**Comment by cppforlife** [comment]
Out of curiosity why do you need to know bosh's volume via tags instead of just looking at what bosh-init recorded in the *-state.json file? It seems that only AWS has tagging support for volumes.
