### ISSUE TITLE
set NTP server in cf-stub.yml or cf-deployment.yml

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/bosh#906]
Hi Expert,
When deploy CF from bosh, where can I set NTP server in cf-stub.yml or cf-deployment.yml?
thanks,
David

**Comment by drnic** [comment]
You setup NTP in your bosh's configuration. Google the bosh.io docs for an example for microbosh.yml

**Comment by liuxiaoxi2237** [comment]
Thanks a lot for your help.
BTW, can NTPserver  of CF VMs be changed after deployment? In my test ,seems it can not be changed.

**Comment by drnic** [comment]
Afaik if you change NTP via your bosh you then need to restart/recreate each individual VM. There is no bulk method for rolling out this change to running VMs.

**Comment by liuxiaoxi2237** [comment]
thanks.
