### ISSUE TITLE
Failed fetching org-users ,status code 500, error code 10001

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/bosh#909]
Hi Expert,
cf login success with --skip-ssl-validation. Create user, space, assigning user role  works fine.
But when run "cf org-users", get below error.
Failed fetching org-users for role ORG MANAGER.
Server error, status code: 500, error code: 10001, message: An unknown error occurred.

Check controller logs, find that
{"timestamp":1438705617.9227388,"message":"Request failed: 500: {\"code\"=>10001, \"description\"=>\"Invalid SSL Cert for https://uaa.10.62.70.82.xip.io/oauth/token. Use '--skip-ssl-validation' to continue with an insecure target\", \"error_code\"=>\"CF-SSLException\", \"backtrace\"=>[\"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/cf-uaa-lib-b1e11235dc6c/lib/uaa/http.rb:169:

I use self signed certificate.
My questions is:
1, Is there away to skip cert validation when run "cf org-users" ? Or some other solution?
2, in cf-deployment.yml, there are 3 components need to input cert(or key pair) - haproxy, router, uaa token. Should I use same key pair for the 3 components? or I need to generate key pair(cert ) for each components?
any experience and suggestions?
thanks,
David

**Comment by bortoelnino** [comment]
@liuxiaoxi2237 - how did you fix this ? I'm seeing it too (on vSphere).

**Comment by dpb587-pivotal** [comment]
@bortoelnino, try the solution mentioned in https://github.com/cloudfoundry/cf-release/issues/766

**Comment by bortoelnino** [comment]
@dpb587-pivotal Thanks! that worked (specifically setting  skip_cert_verify: true)
