### ISSUE TITLE
Add a force flag to bosh upload release

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry/bosh#916]
Trying to run `bosh upload release --rebase` when there are no changes to the release will cause bosh to fail with an error `Error 100: Rebase is attempted without any job or package changes`. This makes it hard to run an automated deploy that uses the latest release, since the release might not have changed since the last run. Ideally, a user should be able to run `bosh upload release --rebase --force` and not get an error back.

**Comment by jvshahid** [comment]
Great, thanks!

**Comment by cppforlife** [comment]
I believe latest bosh release no longer raises this error.
