### ISSUE TITLE
Issue trying to fix a disrupted Microbosh director

### ISSUE THREAD

**Issue by valeriap** [cloudfoundry/bosh#927]
Hi all,
I am working on MicroBosh recovery scenarios. I'm evaluating a recovery approach based on Director DB backup. With this approach in case of disk corruption we would recover the DB from the backup but we would lose the blobstore.
I'm simulating this scenario by deleting objects from the blobstore (this is a follow up scenario of that related to https://github.com/cloudfoundry/bosh/issues/878).

Assuming that epic https://www.pivotaltracker.com/epic/show/1340278 would recover templates, packages, and compiled packages, in my test I've only deleted rendered_templates_archives blobs.

If I run a bosh deploy, it fails in:

```
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.2922.0/lib/bosh/director/rendered_job_templates_cleaner.rb:9:in `clean'
```

because the object cannot be found.

In order to avoid the deployment to fail, would it be possible to catch and ignore the exception?

The same logic should also apply to log_bundles blobs.

Regards,
Valeria.

**Comment by cppforlife** [comment]
Story (https://www.pivotaltracker.com/story/show/101724116) added to the epic.

**Comment by cppforlife** [comment]
Story was completed some time ago.
