### ISSUE TITLE
Ran into issues when trying to deploy CF on OpenStack

### ISSUE THREAD

**Issue by alfredcs** [cloudfoundry/bosh#934]
Tried to deploy CF on OpenStack but encountered following errors. OpenStack works OK and all needed VMs including gorouter (router/0) VM have been spawned off and accessible. 

---------------------------------------------------------------------------------------------------------------------------------
  Started updating job syslog_aggregator > syslog_aggregator/0
  Started updating job nats > nats/0
  Started updating job nfs_server > nfs_server/0
  Started updating job uaa > uaa/0
  Started updating job health_manager > health_manager/0
  Started updating job cloud_controller > cloud_controller/0
  Started updating job router > router/0
  Started updating job postgres > postgres/0
  Started updating job trafficcontroller > trafficcontroller/0
  Started updating job dea
  Started updating job dea > dea/0
  Started updating job dea > dea/1
     Done updating job nfs_server > nfs_server/0 (00:01:09)
     Done updating job syslog_aggregator > syslog_aggregator/0 (00:01:10)
     Done updating job postgres > postgres/0 (00:01:17)
   Failed updating job router > router/0: `router/0' is not running after update (00:10:14)
   Failed updating job trafficcontroller > trafficcontroller/0: `trafficcontroller/0' is not running after update (00:10:15)
   Failed updating job health_manager > health_manager/0: `health_manager/0' is not running after update (00:10:17)
   Failed updating job nats > nats/0: `nats/0' is not running after update (00:10:19)
   Failed updating job dea > dea/0: `dea/0' is not running after update (00:10:34)
   Failed updating job dea > dea/1: `dea/1' is not running after update (00:10:36)
   Failed updating job dea (00:10:36)
   Failed updating job uaa > uaa/0: `uaa/0' is not running after update (00:10:43)
   Failed updating job cloud_controller > cloud_controller/0: `cloud_controller/0' is not running after update (00:12:01)

Error 400007: `router/0' is not running after update

Task 117 error

For a more detailed error report, run: bosh task 117 --debug

---------------------------------------------------------------------------------------------------------------------------------

Debug showed following errors. Not sure  why router/0 stopped running after update. 

---------------------------------------------------------------------------------------------------------------------------------
D, [2015-08-19 21:47:45 #2169] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:openstack
I, [2015-08-19 21:47:48 #2169] [instance_update(router/0)]  INFO -- DirectorJobRunner: Checking if router/0 has been updated after 63.333333333333336 seconds
D, [2015-08-19 21:47:48 #2169] [instance_update(router/0)] DEBUG -- DirectorJobRunner: SENT: agent.501dbe9b-ed13-42cf-b1d5-4ef427eb0aee {"method":"get_state","arguments":[],"reply_to":"director.ff8714d1-162b-4d57-a35e-87f686cc3b54.b7f80045-be76-40e6-8e43-f60ab495a7b9"}
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: RECEIVED: director.ff8714d1-162b-4d57-a35e-87f686cc3b54.b7f80045-be76-40e6-8e43-f60ab495a7b9 {"value":{"properties":{"logging":{"max_log_file_size":""}},"job":{"name":"router","release":"","template":"gorouter","version":"7d2d78b0430a9ae96bbfad17bf75cdda68b9b6e2","sha1":"f296e123a9ac1704c9871ac048d48acf80ceb737","blobstore_id":"286b1660-5dd9-4a80-ae25-2787b021aadb","templates":[{"name":"gorouter","version":"7d2d78b0430a9ae96bbfad17bf75cdda68b9b6e2","sha1":"f296e123a9ac1704c9871ac048d48acf80ceb737","blobstore_id":"286b1660-5dd9-4a80-ae25-2787b021aadb"}]},"packages":{"common":{"name":"common","version":"99c756b71550530632e393f5189220f170a69647.1","sha1":"b74cf960ac26a6d592320a94bf5cbc85ef99d623","blobstore_id":"c33ca66d-bbf2-43e6-6c5f-a960cde17b87"},"gorouter":{"name":"gorouter","version":"c94ae048de57b644222168aea1705f5baa5e7181.1","sha1":"e528b95a0a30fa15b345c9a6064dafb3934ce2d5","blobstore_id":"3d7c3782-c19b-45ba-7fed-25c341668869"}},"configuration_hash":"ddb0c4ccb1b3ecc461b63fd2bbf753f8a8bc28f5","networks":{"external":{"cloud_properties":{"net_id":"332519d7-9504-4f86-bfc4-3d7364467bbf","security_groups":["default","bosh","cf-private","cf-public"]},"default":["dns","gateway"],"dns_record_name":"0.router.external.openstack.bosh","gateway":"192.168.2.1","ip":"192.168.2.61","netmask":"255.255.255.0","type":"dynamic"},"float":{"cloud_properties":{"net_id":"e8e48b3c-fbcf-49a5-9660-74b4abcbaaf4"},"dns_record_name":"0.router.float.openstack.bosh","ip":"3.39.89.235","type":"vip"}},"resource_pool":{"cloud_properties":{"instance_type":"m1.small"},"name":"common","stemcell":{"name":"bosh-openstack-kvm-ubuntu-trusty-go_agent","version":"3012"}},"deployment":"openstack","index":0,"persistent_disk":0,"persistent_disk_pool":null,"rendered_templates_archive":{"sha1":"1cc163cccfe027ae3c81e2bb909937cf9c328701","blobstore_id":"d6e81d5c-21c7-46e4-82d3-cb59d92b4917"},"agent_id":"501dbe9b-ed13-42cf-b1d5-4ef427eb0aee","bosh_protocol":"1","job_state":"failing","vm":{"name":"vm-95857c15-2df4-4c1b-9b7d-ded61f56ec4e"},"ntp":{"message":"bad ntp server"}}}
E, [2015-08-19 21:47:48 #2169] [instance_update(router/0)] ERROR -- DirectorJobRunner: Error updating instance: #<Bosh::Director::AgentJobNotRunning: `router/0' is not running after update>
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/instance_updater.rb:90:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:94:in `block (2 levels) in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:92:in `block in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:91:in `update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:85:in `block (2 levels) in update_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: `router/0' is not running after update - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/instance_updater.rb:90:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:94:in `block (2 levels) in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:92:in `block in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:91:in `update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:85:in `block (2 levels) in update_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: Worker thread raised exception: `router/0' is not running after update - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/instance_updater.rb:90:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:94:in `block (2 levels) in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:92:in `block in update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:91:in `update_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3012.0/lib/bosh/director/job_updater.rb:85:in `block (2 levels) in update_instances'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3012.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2015-08-19 21:47:48 #2169] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2015-08-19 21:47:48 #2169] [task:117] DEBUG -- DirectorJobRunner: Shutting down pool
I, [2015-08-19 21:47:49 #2169] [instance_update(trafficcontroller/0)]  INFO -- DirectorJobRunner: Checking if trafficcontroller/0 has been updated after 63.333333333333336 seconds
D, [2015-08-19 21:47:49 #2169] [instance_update(trafficcontroller/0)] DEBUG -- DirectorJobRunner: SENT: agent.51069a9e-6aec-4bb1-9313-4e7972c853dc {"method":"get_state","arguments":[],"reply_to":"director.ff8714d1-162b-4d57-a35e-87f686cc3b54.39b34eca-df63-44ba-8fdb-d9a8f1ff3860"}

**Comment by cppforlife** [comment]
This seems like cf-release specific issue. Please open an issue in https://github.com/cloudfoundry/cf-release.
