### ISSUE TITLE
Custom Tags in manifest

### ISSUE THREAD

**Issue by squeedee** [cloudfoundry/bosh#936]
The AWS console can be quite painful with multiple depoyments. I can use the [Resource Groups](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/managing-resource-groups.html) to seperate deployments which helps a lot, however, the tagging mechanism for resource groups is 'and' not 'or'. This means that if I use cloudformation or manually deploy non-bosh, but related, resources on AWS, I have to tag them with 'deployment' as well, which can be a little misleading. 

The easiest way to manage complex deployments on a single AWS account is to use tags, but without custom tag support, I am limited in the ways I can take advantage of what AWS provides.

**Comment by cppforlife** [comment]
Would providing a CPI level configuration for tags work for you? e.g. all resources created by the CPI are tagged with some set of same tags.

**Comment by dpb587-pivotal** [comment]
Someone else brought this up in [slack](https://cloudfoundry.slack.com/archives/bosh/p1454025113000259) a few weeks ago.

**Comment by dpb587-pivotal** [comment]
Director [v260+](https://github.com/cloudfoundry/bosh/releases/tag/v260) now supports configuring custom tags via [runtime config](http://bosh.io/docs/runtime-config.html#tags) and [deployment manifests](http://bosh.io/docs/manifest-v2.html#tags).
