### ISSUE TITLE
Keystone v3 support not working for domains other than 'Default'

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#939]
**Problem**
Deploying a bosh director with bosh-init to a keystone v3 enabled openstack environment with a domain name different than 'Default' fails during stemcell upload. The reason is that the used version of fog doesn't implement passing the necessary domain name argument to openstack in the `Fog::Compute` component - so any calls involving nova will fail.

**Analysis**
There is a bug in fog 1.31.0 which leads to [Fog::Compute not knowing about the `openstack_domain_name` parameter](https://github.com/fog/fog/blob/v1.31.0/lib/fog/openstack/compute.rb#L7-L14)
Therefore, the output in the console is `STDERR: '[fog][WARNING] Unrecognized arguments: openstack_domain_name` followed by an HTTP 404
```
D, [2015-08-21T09:15:52.852051 #3870] DEBUG -- : excon.error {:error=>#<Excon::Errors::NotFound: Expected([201]) <=> Actual(404 Not Found)
excon.error.response
  :body          => "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr>
<center>nginx/1.4.4</center>\r\n</body>\r\n</html>\r\n"
  :headers       => {
    "Connection"     => "keep-alive"
    "Content-Length" => "168"
    "Content-Type"   => "text/html"
    "Date"           => "Fri, 21 Aug 2015 09:15:53 GMT"
    "Server"         => "nginx/1.4.4"
  }
  :local_address => "192.168.0.104"
  :local_port    => 41757
  :reason_phrase => "Not Found"
  :remote_ip     => "147.204.8.32"
  :status        => 404
  :status_line   => "HTTP/1.1 404 Not Found\r\n"
>}
E, [2015-08-21T09:15:52.852453 #3870] ERROR -- : Unable to connect to the OpenStack Compute API. Check task debug log for details.
[Cmd Runner] 2015/08/21 09:15:52 DEBUG - Successful: true (0)
[cpiCmdRunner] 2015/08/21 09:15:52 DEBUG - Exit Code 0 when executing external CPI command '/home/vcap/.bosh_init/installations/5ead9388-6a94-45c6-50b1
-75c84a703849/jobs/cpi/bin/cpi'
```

The request body that fog sent to openstack contains ‘Default’ as a domain name, [because that is the hardcoded default if no name is specified](https://github.com/fog/fog/blob/v1.31.0/lib/fog/openstack/compute.rb#L272):
``` 
:body=>"{\"auth\":{\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"name\":\"cloud_foundry\",\"password\":\"start123\",\"domain\":{\"name\":\"Default\"}}}},\"scope\":{\"project\":{\"name\":\"clound_foundry_01\",\"domain\":{\"name\":\"Default\"}}}}}"
```

So this is [fixed in fog 1.32.0](https://github.com/fog/fog/blob/v1.32.0/lib/fog/openstack/compute.rb#L14), but [additional fixes for openstack have been included in fog 1.33.0](https://github.com/fog/fog/blob/master/CHANGELOG.md#openstack) – we probably want to upgrade to that. However, [fog 1.33.0 requires fog-aws >= 0.6.0](https://github.com/fog/fog/blob/v1.33.0/fog.gemspec#L56), which was [fixed in bosh to 0.1.1](https://github.com/cloudfoundry/bosh/commit/84b50fd190973ccb5ae8dcb54963a18b0d2022b7#commitcomment-12646350) by @allomov recently. But if I understood the [original bug](https://github.com/fog/fog-aws/issues/83)  correctle, we only have problems if you require internals of fog-aws which have moved. If you just do `require fog-aws` everything is supposed to be fine.

So updating fog might need some more thorough testing.

**Comment by voelzmo** [comment]
The suggestion by @geemus in https://github.com/fog/fog-aws/issues/83#issuecomment-96719876 was to update fog itself - there might have been issues with older fog verisons referring to details in fog-aws which don't exist anymore. I will try to update fog and remove the lockdown of fog-aws - let's see if I can reproduce the original error seen in https://github.com/cloudfoundry/bosh/pull/834

**Comment by cppforlife** [comment]
Let us know what you find out when gem is updated.

**Comment by voelzmo** [comment]
Found another bug in fog 1.34.0 which prevents me from actually deploying bosh with keystone V3 https://github.com/fog/fog/issues/3687

**Comment by rradecki** [comment]
What is the current status of this problem? I am also having mentioned issue and fog upgrade does not help :)

**Comment by voelzmo** [comment]
@rradecki are you trying to use bosh with a keystone V3 API? Then this currently doesn't work – even after updating fog – due to the mismatch of `tenant` and `project` parameters I mentioned in the [above comment](https://github.com/cloudfoundry/bosh/issues/939#issuecomment-139161278).

Once PR https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/pull/10 gets pulled in, this might actually be fixed in the CPI coding. However, in order for this to be useable, we need additional changes in bosh itself, i.e. something like I proposed with PR https://github.com/cloudfoundry/bosh/pull/950.

We've added a stories to make the necessary changes in bosh-openstack-cpi-release (see https://www.pivotaltracker.com/story/show/104344048 and https://www.pivotaltracker.com/story/show/104344480). One those are done, we can do the remaining changes in bosh.

**Comment by jhiemer** [comment]
Hi @voelzmo,
from the tickets I can't see any timeline for V3 support. Do you have any information here? :-)

**Comment by voelzmo** [comment]
@jhiemer The last remaining item todo is currently https://www.pivotaltracker.com/story/show/105334890
We're currently setting up end-to-end integration tests to verify V3 support. We need to cut a new bosh release for this to be included, so stay tuned for one of the next releases.

**Comment by cppforlife** [comment]
Keystone v3 support is available: http://bosh.io/docs/openstack-keystonev3.html

**Comment by geemus** [comment]
Thanks!
