### ISSUE TITLE
[tasks] Reference which deployment the task applied to

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#940]
If a task runs against a deployment, as most do, please add a column to `bosh tasks` saying which deployment it is running against; plus include it in the `/tasks` and `/tasks/ID` API endpoints. Thanks!

**Comment by cppforlife** [comment]
Makes sense. Btw I'm thinking to introduce an audit log feature with records about which CPI calls made, which agent calls made and of course which resources were affected etc.

**Comment by drnic** [comment]
More audit logs would be lovely

**Comment by dpb587-pivotal** [comment]
Closing - deployment-related tasks now include a deployment field (since [v255.4](https://github.com/cloudfoundry/bosh/releases/tag/stable-3213)).
