### ISSUE TITLE
call to private method power_state when attempting reboot in cck

### ISSUE THREAD

**Issue by Zteve** [cloudfoundry/bosh#944]
Got this message during a reboot attempt for a machine during cck:
```
Started applying problem resolutions > unresponsive_agent 232: Reboot VM. Failed: private method `power_state' called for #<VSphereCloud::Resources::VM:0x007f8ef400a098> (00:00:12)
```

The cck fails to recover the vm.

I see this reference to `power_state` in `bosh/bosh_vsphere_cpi/lib/cloud/vsphere/cloud.rb` line 207:
```
        unless vm.powered_on?
          @logger.info("VM not in POWERED_ON state. Current state : #{vm.power_state}")
        end
```

Could this be a bug?

**Comment by cppforlife** [comment]
Interesting. Seems like a bug. Which version of vcenter are you using?

**Comment by cppforlife** [comment]
Story filed: https://www.pivotaltracker.com/story/show/102611608

**Comment by cppforlife** [comment]
Was fixed in v9 of https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release.
