### ISSUE TITLE
bosh-cli: Add option to not remove compiled packages when deleting stemcell

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#960]
Hi,

it would be useful to have option in bosh-cli to skip deletion of compiled packages on stemcell removal. The use case is when you realize some issue in a stemcell and want to quickly replace it. You can then selectively rebuild/re-create the affected jobs. This saves a lot of time - which can be quite critical in case of downtime. The current process of increasing stemcell version number and applying that to a release would cause a complete rolling update which takes quite some time...

**Comment by bosh-ci-push-pull** [comment]
That's an interesting use case. Thanks for sharing.

We are actually adding some features to the CLI to make recovering Director easier and it may help here. We have a PR coming in to add: bosh upload stemcell X --fix. Typically it would be used for cases when stemcell is somehow corrupted and needs to be replaced in the IaaS with the same version.

**Comment by mtekel** [comment]
Thanks, that `--fix` option would solve/help my use case, as I wouldn't have to delete the stemcell then...

**Comment by cppforlife** [comment]
Story: https://www.pivotaltracker.com/story/show/103218714

**Comment by mtekel** [comment]
The new --fix made it to latest bosh release, closing issue.
