### ISSUE TITLE
Bosh bootstrap should support EC2 roles

### ISSUE THREAD

**Issue by berniedurfee-ge** [cloudfoundry/bosh#962]
It appears that the 'bosh bootstrap' command requires that the AWS key be hardcoded in the settings.yml file. Instead, we would like to run the 'bosh bootstrap' command on an EC2 instance that is assigned an EC2 role, so we don't have to hardcode credentials.

Additionally, 'bosh bootstrap' should support the standard AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.

Looks like there is a 'credentials_source' option that should work, just doesn't seem to be recognized in settings.yml.

Bosh 1.3074.0

**Comment by drnic** [comment]
Thanks for spotting that. My use cases have been via settings.yml only I missed it.




Do you think there's a simple PR you can do to fix?

**Comment by bosh-ci-push-pull** [comment]
We have not officially released this feature yet as it's still going
through our CI pipelines.

**Comment by berniedurfee-ge** [comment]
@drnic Is it even worth it? Isn't bosh-init going to ultimately replace 'bosh bootstrap'?

**Comment by drnic** [comment]
bosh-bootstrap would have the role of asking questions and creating the new larger manifest; then running bosh-init

**Comment by cppforlife** [comment]
Closing issue on bosh. bosh-bootstrap is a [separate project](https://github.com/cloudfoundry-community/bosh-bootstrap).
