### ISSUE TITLE
bosh_cli can't be installed on Ruby 1.9.3

### ISSUE THREAD

**Issue by mstrzele** [cloudfoundry/bosh#965]
New version of `net-ssh`, which is dependency for `bosh_cli`, requires Ruby 2.0. 

```
ERROR:  Error installing bosh_cli:
        net-ssh requires Ruby version >= 2.0.
```

The gemspec line responsible for requiring `net-ssh` should be changed to something like this:
```
  spec.add_dependency 'net-ssh',          '>=2.2.1', '~>2'
```

**Comment by cppforlife** [comment]
Seems like latest net-ssh maintainers decided to stop supporting 1.9.3 (it is a deprecated version). You can try uninstalling net-ssh 3.x and `gem install net-ssh -v 2.9.2` before installing bosh_cli. Any reason you prefer using 1.9.3? Just relying on default ruby on ubuntu?

**Comment by mstrzele** [comment]
Yeah, I did it.

I'm using Ruby 1.9.3 because it's default for Ubuntu 14.04 LTS. According to [documentation](https://bosh.io/docs/bosh-cli.html), `bosh_cli` should have support for this version.

**Comment by mstrzele** [comment]
There's similar problem with `fog-google` gem:

```
ERROR:  Error installing bosh_cli:
	fog-google requires Ruby version >= 2.0.
```

**Comment by mstrzele** [comment]
The prerequisites sections also should be updated.

On Ubuntu Trusty, the `ruby2.0` and `ruby2.0-dev` packages need to be installed and changed to the default version by creating links in `/usr/bin` (there's a [bug](https://bugs.launchpad.net/ubuntu/+source/ruby2.0/+bug/1310292) in Ubuntu for this).

On RHEL/CentOS there's no possibility to install Ruby 2.0 using Yum.

**Comment by mstrzele** [comment]
I still think, that changing `Gemspec` to include so called [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) is better approach. This is the one of common practices.

**Comment by ermikowy** [comment]
+1

**Comment by pmilewsk** [comment]
+1

**Comment by wkielas** [comment]
+1

**Comment by rradecki** [comment]
+1

**Comment by cppforlife** [comment]
Filed a story: https://www.pivotaltracker.com/story/show/105121972

**Comment by cppforlife** [comment]
Fixed in 3100

**Comment by mstrzele** [comment]
What about `fog-google` gem?

```
ERROR:  Error installing bosh_cli:
	fog-google requires Ruby version >= 2.0.
```

Probably other gems without pessimistic version constraint can cause this issue in the future.

**Comment by cppforlife** [comment]
That one was missed. Filed a new story to simplify dependencies: https://www.pivotaltracker.com/story/show/105359266
