### ISSUE TITLE
BOSH reports delete deployment successful when actually some VMs still present

### ISSUE THREAD

**Issue by jamiemonserrate** [cloudfoundry/bosh#966]
We were deleting a tile on AWS ops manager, which was reported as successful. Bosh did not show the deployment after this was done. However, 2 instances of a job were still hanging around at the end.

Looking at the debug log for the task, we discovered that when bosh aws cpi tried to delete the vm, it encountered throttle limit errors, which it logged but did not mark the task as failed.

Github wouldn't let us attach a file, so we put it in a gist: https://gist.github.com/jamiemonserrate/16660b54438cba057933

Jamie & @craigfurman

**Comment by cppforlife** [comment]
"Force deleting is set, ignoring exception" is in the logs which means that --force flag is set. When force flag is set the Director ignores failures and continues on. I believe opsmgr team is aware of this and they will be fixing it in some future build.

cc @mreider
