### ISSUE TITLE
bind cloud-config to existing deployment

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh#972]
I want to extract site specific information from existing bosh deployment and put it to cloud-config. I have moved sections of manifest to `iaas.yml` and run `bosh update cloud-config iaas.yaml`.

But it seems bosh deploy fails to bind new cloud-config to existing deployment. `bosh deploy` fails with error saying that networks section was not found.

What is the proper way of extracting cloud-config from existing deployment?

**Comment by cppforlife** [comment]
Can you include some stack trace? Which versions of CLI and the Director are you using?

**Comment by lexsys27** [comment]
I can't reproduce problem so let's assume it is gone.

Surprisingly bosh deploy started to rebuild vms after extracting config. I expected to just bind new config
