### ISSUE TITLE
Renaming a Deployment

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry/bosh#976]
I've run into a few cases where I've wanted to rename a BOSH deployment, without changing anything else (composition / addressing / etc.).

I've done some experimental hacking and I believe the following things need to be done:
- Change the `deployments.name` field in the database
- Notify all agents of the rename (I did this manually via `sed -i'' -e 's/oldname/newname/' /var/vcap/bosh/spec.json` on each VM)

Are there any landmines to doing this?  Is this something we would want (like a `bosh rename deployment oldname newnme` command?)  If so, I'll gladly work on it.

**Comment by cppforlife** [comment]
Agreed. We've also ran into this.

We are currently in the middle of introducing some long reaching changes into the Director. Once we merge it in (story: https://www.pivotaltracker.com/story/show/100170490) I think it makes sense to do it. We are also trying to stop sending all kinds of unnecessary information to the VM (deployment name is not something agent should care about), so changes would pretty much be change the DB and trigger deploy.

**Comment by geofffranks** [comment]
+1

**Comment by jadekler** [comment]
+1

**Comment by jhunt** [comment]
Any movement on this, @cppforlife ?

**Comment by dsharp-pivotal** [comment]
Since we followed these instructions yesterday: +1
We also changed /var/vcap/instance/deployment

**Comment by keymon** [comment]
+1

**Comment by avade** [comment]
This is something I would be very interested in for the On Demand Broker. 

Users want to specify a deployment prefix, so we would like to rename all existing instances to have this pre-fix.

**Comment by kmacoskey** [comment]
+1

**Comment by doty-pivotal** [comment]
+ 1

**Comment by divyabhargov** [comment]
+1

**Comment by jriguera** [comment]
+1

**Comment by vlad-stoian** [comment]
+1

**Comment by jagadish-kb** [comment]
+1 - This would greatly help in reorganizing / moving around some of our existing deployments.

**Comment by ramonskie** [comment]
+1

**Comment by chrisahl** [comment]
+1

**Comment by mfine30** [comment]
Thanks all for the feedback. I've created story: https://www.pivotaltracker.com/story/show/159605314 to look further into this. Not sure on timelines yet, but the large number of +1's is certainly encouraging.

**Comment by kmacoskey** [comment]
+1 yay! This issue was opened in 2015!

**Comment by cwb124** [comment]
+1

**Comment by kitsirota** [comment]
+1

**Comment by jhunt** [comment]
+1

**Comment by byllc** [comment]
+1

**Comment by pivotal-jamil-shamy** [comment]
@mfine30 
Please note that when using non absolute credhub variable names (i.e. they do not start with a `/`), the director will append the director name and _**Deployment Name**_ before it fetches/generates these variables from credhub.

Need to take that into consideration this feature is worked on.

**Comment by frankgh** [comment]
+1

**Comment by tyacovone** [comment]
+1

**Comment by kitsirota** [comment]
+1 Looks like https://www.pivotaltracker.com/n/projects/956238/stories/159605314 hasnt been updated since Sept 27th.  

Will this feature ever make it on the roadmap?

**Comment by amuessig** [comment]
Any updates on this? I would love to use this feature.

**Comment by vinioskii** [comment]
+1

**Comment by jhunt** [comment]
@cppforlife did https://www.pivotaltracker.com/story/show/100170490 ever get merged?

**Comment by jhunt** [comment]
+1

**Comment by bgandon** [comment]
Dmitriy has evolved away from BOSH since last Basel CF Summit… like 3 years ago… But hey James, I'm glad to see you still care in your post-S&W life! ;-)

By the way, does anyone know what “_dynamic provisioning_” is supposed to mean, in [this Tracker Story #100170490](https://www.pivotaltracker.com/story/show/100170490)

About CredHub secrets, that's a tricky matter. I have a tough experience in “moving” them inside the CredHub directory (after renaming a Concourse pipeline, for instance). Only updating the path in the database does not work. There is some fingerprinting or encryption that needs to be updated using the new path, which makes me wonder what is the design (and why).
