### ISSUE TITLE
Need to upgrade PostgreSQL due to security issues.

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#980]
There still uses a pretty old PostgreSQL DB 9.0.3.1 (https://github.com/cloudfoundry/bosh/blob/ede389a2e112e1b4f2dbc4495c08977da4439483/release/packages/postgres/spec). Please consider to upgrade PostgreSQL to 9.0.23 (the latest version for 9.0.x) due to the following 2 security issues, thanks.

https://exchange.xforce.ibmcloud.com/vulnerabilities/107026
https://exchange.xforce.ibmcloud.com/vulnerabilities/107027

CC @maximilien

**Comment by cppforlife** [comment]
Story in progress: https://www.pivotaltracker.com/story/show/105585496

**Comment by cppforlife** [comment]
Fixed in bosh-release v215 (3104)
