### ISSUE TITLE
bosh status does not show names of external CPI

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#985]
Here is the sample output of `bosh status`
```
Director
  Name       my-bosh
  URL        https://<redacted>:25555
  Version    1.3100.0 (00000000)
  User       admin
  UUID      <redacted>
  CPI        cpi
  dns        disabled
  compiled_package_cache disabled
  snapshots  disabled
```

I'm using an external CPI, and the information provided by the `/info` endpoint boils down to ` 'cpi' => Config.cloud_type`, which is `cpi` for all external ones.

Internal cpis provided their actual name (e.g. `aws`), which was kind of neat. Can we have that back, pls?

**Comment by cppforlife** [comment]
Story created: https://www.pivotaltracker.com/story/show/105868858

We are just planning to rename cpi jobs for now. Eventually we can have more comprehensive solution.

**Comment by voelzmo** [comment]
Fixed with openstack-cpi-release v16 and corresponding new versions of the other CPIs.
