### ISSUE TITLE
bosh upload release fails

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/bosh#991]
Hi, 
I am trying to setup CF via bosh on OS based on: http://docs.cloudfoundry.org/deploying/openstack/install_cf_openstack.html. When I do a `bosh upload release` I get a 

`Uploading release
release.tgz:   100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|   2.3GB  17.9MB/s Time: 00:02:09
HTTP 401: Not authorized: '/releases'`

Any hint I can start to debug?

Is this perhaps a bug in the nginx configuration of the director?

Doing a: 

`curl https://172.24.100.5:25555/releases -k`

also results in:

`Not authorized: '/releases'`

**Comment by cppforlife** [comment]
Do you have BOSH_USER/PASSWORD env vars set with wrong credentials?

**Comment by jhiemer** [comment]
Hi @cppforlife,
I have just deployed my Director with Credentials and it work. Is there any other option to set the credentials in the environment properties?

**Comment by jhiemer** [comment]
My fault forgot to login with the new user.
