### ISSUE TITLE
mutli-homed VMs gateway/dns is not correctly set

### ISSUE THREAD

**Issue by jcarrothers-sap** [cloudfoundry/bosh#996]
I've been experimenting with mult-homed VMs in my deployments and I believe I've found a problem where bosh is not correctly configuring the networking.  Here is the relevent excerpt from my job config:

```jobs:
- instances: 1
  networks:
  - name: internal
    default: [ dns ]
  - name: external
    default: [ gateway ]
    static_ips:
    - 10.160.191.254
networks:
- name: internal
  subnets:
    - range: 192.168.0.0/16
      reserved: ["192.168.0.2-192.168.4.255", "192.168.6.0-192.168.255.254"]
      dns: [192.168.0.5]
      gateway: 192.168.0.1
- name: external
  subnets:
    - range: 10.160.160.0/19
      static: <not relevent>
      dns: <not relevent>
      gateway: 10.160.160.1
```

However, when the VM is deployed, the `/etc/resolve.conf` is empty and the default gateway is configured for eth0 and a gateway of 192.168.0.1 instead of eth1 with a gateway of 10.160.160.1.

**Comment by bosh-ci-push-pull** [comment]
Just to make sure, in your real manifest is `subnets` value an array?

**Comment by jcarrothers-sap** [comment]
Yes, my mistake.  I tried to prune irrelevant information and failed to ensure the yml syntax was still valid.

As an additional piece of information, I've ensured I'm using the latest BOSH release (217), the latest vcloud_cpi release (18).  I'm using the `bosh-vcloud-esxi-ubuntu-trusty-go_agent` stemcell release 3115 for the multihomed VMs deployed by BOSH.

**Comment by poblin-orange** [comment]
I did previously open an issue on this point (maybe in a wrong location)
https://github.com/cloudfoundry-attic/bosh_vcloud_cpi/issues/16

Had no time to reproduce the issue, but its looking very similar (vcloud cpi, multi homed nics)

**Comment by cppforlife** [comment]
After looking into this more I do think we may have a bug regarding improperly configure multiple nets. Will have more details tomorrow.

**Comment by cppforlife** [comment]
Story created: https://www.pivotaltracker.com/story/show/107452992. We will pick it up tomorrow.

**Comment by cppforlife** [comment]
@jcarrothers-sap we believe 3137 stemcell fixes this problem. please reopen if issue persists.

@poblin-orange i dont believe your issue is the same; moved it here: https://github.com/cloudfoundry-incubator/bosh-vcloud-cpi-release/issues/9

**Comment by jcarrothers-sap** [comment]
Confirmed fixed with bosh-vcloud-esxi-ubuntu-trusty-go_agent v3137
