### ISSUE TITLE
bosh upload release is broken

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/bosh#997]
Using 1.3115
```
Generated /var/folders/tp/mfydkfq136l964tfdb6fgh5c0000gn/T/d20151027-37913-p1lmaw/d20151027-37913-1a6nsjg/release.tgz
Release size: 2.2G
Cannot find file `/var/folders/tp/mfydkfq136l964tfdb6fgh5c0000gn/T/d20151027-37913-p1lmaw/d20151027-37913-18m9whn/release.MF'
```

If I look at the $TMPDIR, it should be`/var/folders/tp/mfydkfq136l964tfdb6fgh5c0000gn/T/d20151027-37913-p1lmaw/release.MF`

If I drop to 1.3100, it all works.

**Comment by pivotal-nader-ziada** [comment]
Hello 

We can't seem to recreate the issue, tried to create and upload a release on both mac and linux without issues. Can you maybe give us more details about your environment and maybe a debug log?

Thanks

**Comment by fraenkel** [comment]
I am more than happy to give you a debug log. Where is it on my local machine?

**Comment by pivotal-nader-ziada** [comment]
can you run: bosh task {the_failed_task_number} --debug

**Comment by fraenkel** [comment]
There is no task since it didn't get that far.

**Comment by pivotal-nader-ziada** [comment]
is it possible to share the release tarball you were trying to upload? and are you running on mac?

**Comment by fraenkel** [comment]
It was the develop branch of cf-release with updated loggregator code.
I am on a Mac. I was using 3115 but dropped to 3100 to get things working.

**Comment by pivotal-nader-ziada** [comment]
We still can't seem to recreate the problem. Did you create the tarball using create release? We have seen cases where this error happens when the tarball is created manually.  Can you send the listing for tar -tvf against the tarball you are using?

**Comment by fraenkel** [comment]
I can no longer recreate the issue.

**Comment by fraenkel** [comment]
I located the source of the problem.

https://github.com/cloudfoundry/bosh/blob/master/bosh_cli/lib/cli/release_tarball.rb#L47

On my machine, I have gnu tar installed and --fast-read is a mac specific option which fails.

**Comment by cppforlife** [comment]
@fraenkel please try 3148. we believe https://github.com/cloudfoundry/bosh/commit/dddb47433d75f3087d650d71d9ff47030b562980 fixes this problem. reopen if problem persists.

**Comment by simonleung8** [comment]
@cppforlife I have using 3215 and run into the exact problem. I am using the default BSD tar that shipped with mac.

**Comment by cppforlife** [comment]
@simonleung8 this issue has been closed for a long time. please open a different issue and include necessary info like cli and director version, error stacktrace, etc.
